### ISSUE TITLE
Why DeepAI always return 401 

### ISSUE THREAD

**Issue by embarce** [xtekky/gpt4free#1001]
**Bug description**
When I use DeepAI to generate conversations, it always returns a 401 error. I've tried changing the API key to my own account's fixed API key, and I've also tried changing proxy services and use the try-it api key , but it still returns a 401 error code.

401, message='Unauthorized', url=URL('https://api.deepai.org/hacking_is_a_crime')

curl --location --request POST 'https://api.deepai.org/hacking_is_a_crime' --header 'api-key: 8********f1f' --form 'chatHistory="[{\"role\":\"user\",\"content\":\"Hello\"},{\"role\":\"assistant\",\"content\":\"what can i do for you today?\"},{\"role\":\"user\",\"content\":\"who are you？\"}]"' --form 'chat_style="chat"'

{"status": "signed in try-it quota exceeded"}

* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=deepai.org
*  start date: Apr  6 00:00:00 2023 GMT
*  expire date: May  4 23:59:59 2024 GMT
*  subjectAltName: host "api.deepai.org" matched cert's "*.deepai.org"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5563461458d0)
> POST /hacking_is_a_crime HTTP/2
> Host: api.deepai.org
> user-agent: curl/7.68.0
> accept: */*
> api-key: 8*****f
> content-length: 389
> content-type: multipart/form-data; boundary=------------------------f8cfc948a73a94c5
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
< HTTP/2 401 
< date: Sat, 07 Oct 2023 03:48:42 GMT
< content-type: application/json
< content-length: 45
< status: 401 Unauthorized
< vary: origin
< referrer-policy: same-origin
< x-frame-options: ALLOWALL
< x-content-type-options: nosniff
< x-powered-by: Phusion Passenger(R)
< server: nginx + Phusion Passenger(R)
< 
* Connection #0 to host api.deepai.org left intac

PS: When I use the postman to call api seems is noraml

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/34028684/cd5066d1-a3ef-435b-a98e-7346dd0873b8)

**Environement**
- python version 3.9
- JP

**Comment by hlohaus** [comment]
The tryit token is invalid:

def get_api_key(user_agent: str):

**Comment by embarce** [comment]
Thx @hlohaus 

Although I used get_api_key method , it seems that  still return error code 401. 

By the way, why is using Postman normal ? (PS: in Postman , I am using my api_key)

![image](https://github.com/xtekky/gpt4free/assets/34028684/56f3a431-36fb-4373-a406-0aa73f66e39a)

**Comment by hlohaus** [comment]
> Thx @hlohaus 
> 
> Although I used get_api_key method , it seems that  still return error code 401. 
> 
> By the way, why is using Postman normal ? (PS: in Postman , I am using my api_key)
> 
> ![image](https://github.com/xtekky/gpt4free/assets/34028684/56f3a431-36fb-4373-a406-0aa73f66e39a)
> 

Maybe the logic has changed.
The Python def is only my new function.
The old logic is javascript in the top of the Provider. I have the same issue. Error

**Comment by embarce** [comment]
> > Thx @hlohaus
> > Although I used get_api_key method , it seems that  still return error code 401.
> > By the way, why is using Postman normal ? (PS: in Postman , I am using my api_key)
> > ![image](https://user-images.githubusercontent.com/34028684/273383898-56f3a431-36fb-4373-a406-0aa73f66e39a.png)
> 
> Maybe the logic has changed. The Python def is only my new function. The old logic is javascript in the top of the Provider. I have the same issue. Error

Yes I think logic has changed. Its not working now. thx your help 😊

**Comment by deepai-org** [comment]
Hacking is a crime.
