### ISSUE TITLE
please delete site chat.aivvm.com

### ISSUE THREAD

**Issue by CaoYunzhou** [xtekky/gpt4free#1003]
**Known Issues** // delete this
please delete site `chat.aivvm.com`

**Delete site description**
Gpt4free maintainers, I am the administrator of chat.aivvm.com and request to delete this site. My website is already under high load

**Comment by su-fen** [comment]
That's true

**Comment by CaoYunzhou** [comment]
`https://github.com/xtekky/gpt4free/pull/894/files`
This is bad thing

**Comment by hlohaus** [comment]
The Provider will selected with RoundRobin from `best_provider`. I can create a PR, when i am home. The package have no Session, so there is by default no RateLimit.

**Comment by CaoYunzhou** [comment]
https://github.com/xtekky/gpt4free/commit/3430b04f870d982d7fba34e3b9d6e5cf3bd3b847
@hlohaus thky bro
I will close issue
