### ISSUE TITLE
Bing is not GPT 4 

### ISSUE THREAD

**Issue by Eikosa** [xtekky/gpt4free#1006]
When I try it, I see that the answers it gives on the site and the bing answers I produced with g4f are definitely very different, I do not think it is gpt 4

**Comment by Eikosa** [comment]
I'll try it both ways with same prompt:
prompt: `what is the difference between restrictive and obstructive lung diseases`

---

**Answer of g4f:**
<details><summary>Click me</summary>
<p>

Restrictive and obstructive lung diseases are two types of lung conditions that affect breathing. Obstructive lung diseases make it hard to exhale all the air in your lungs, while restrictive lung diseases limit your ability to inhale air fully . Both can cause shortness of breath, coughing and shallow breaths. Some examples of obstructive lung diseases are asthma and COPD, while some examples of restrictive lung diseases are pulmonary fibrosis and sarcoidosis . Do you want to know more about the causes, symptoms or treatments of these lung diseases?

</p>
</details> 

**Answer of creative bing web app:**
<details><summary>See</summary>
<p>

The difference between restrictive and obstructive lung diseases is mainly related to how they affect the breathing process. Obstructive lung diseases make it hard to exhale all the air from the lungs, while restrictive lung diseases make it hard to inhale air into the lungs. Here is a summary of the main differences:

- Obstructive lung diseases are caused by narrowing or blockage of the airways, which reduces the airflow out of the lungs. [Some examples of obstructive lung diseases are chronic obstructive pulmonary disease (COPD), asthma, bronchiectasis, and cystic fibrosis](https://www.webmd.com/lung/obstructive-and-restrictive-lung-disease)¹².
- Restrictive lung diseases are caused by stiffness or reduced elasticity of the lungs or the chest wall, which limits the expansion of the lungs. Some examples of restrictive lung diseases are interstitial lung disease, sarcoidosis, obesity, scoliosis, and neuromuscular disease¹².
- Obstructive and restrictive lung diseases share the same main symptom: shortness of breath when you exert yourself. However, obstructive lung diseases cause more trouble when you're exhaling air, while restrictive lung diseases cause more trouble when you're inhaling air².
- Obstructive and restrictive lung diseases are diagnosed using pulmonary function tests, which measure the volume and flow of air through your lungs. Obstructive lung diseases are characterized by a reduced ratio of forced expiratory volume in one second (FEV[1](https://www.webmd.com/lung/obstructive-and-restrictive-lung-disease)) to forced vital capacity (FVC), which indicates how much air you can exhale in one second compared to your total lung capacity. Restrictive lung diseases are characterized by a reduced FVC, which indicates how much air you can inhale into your lungs¹².
- Obstructive and restrictive lung diseases have different treatments depending on the cause and severity of the condition. Some common treatments for obstructive lung diseases are bronchodilators, which relax the muscles around the airways; corticosteroids, which reduce inflammation; and oxygen therapy, which provides extra oxygen to breathe. Some common treatments for restrictive lung diseases are anti-inflammatory drugs, which reduce inflammation; immunosuppressants, which suppress the immune system; and lung transplantation, which replaces damaged lungs with healthy ones¹².

</p>
</details>

**Comment by swordliongit** [comment]
Bump
