### ISSUE TITLE
How i can dont use Bing?

### ISSUE THREAD

**Issue by tima24312** [xtekky/gpt4free#1014]
Hello, I am completely bad at programming and very bad at coding. How can I disable the use of provider "Bing" when replying via GPT-4 in the web interface? I have installed this via "pip install -U g4f". Or how can I set up a specific provider

**Comment by xtekky** [comment]
setting a specific provider is not available at the moment on the web interface

**Comment by tima24312** [comment]
> setting a specific provider is not available at the moment on the web interface

Could there be an opportunity to do so in the near future?
