### ISSUE TITLE
"GET /favicon.ico HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by lixiang12345** [xtekky/gpt4free#1015]
when i use docker compose up , start http://localhost:1337/, get "GET /favicon.ico HTTP/1.1" 404 -

**Comment by sirius-zyj** [comment]
I encountered the same problem when I deployed through Docker under Ubuntu22

**Comment by lixiang12345** [comment]
I deployed through Docker under MacOS sonoma

**Comment by lixiang12345** [comment]
> I encountered the same problem when I deployed through Docker under Ubuntu22
Have you solved it yet

**Comment by zukixa** [comment]
this error shouldn't affect the interference operations, as the error represents that there is no website logo associated with your app

shouldn't be a problem, but if you want a fix, google how to add one
