### ISSUE TITLE
completion not working properly

### ISSUE THREAD

**Issue by sahilbrandwala** [xtekky/gpt4free#1016]
import g4f

# streamed completion
response = g4f.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "email?"},{"role": "system", "content": "email address is demo@demo.com"}],
    stream=False,
)

for message in response:
    print(message, flush=True, end='')

**Comment by sdaqo** [comment]
You will have to add further context (e.g. error messages, output etc.) or else it will be hard to help you. Also please put code in a code block like this much easier to read e.g.: 
```python
import g4f

response = g4f.ChatCompletion.create(
	model="gpt-3.5-turbo",
	messages=[{"role": "user", "content": "email?"},{"role": "system", "content": "email address is [demo@demo.com]	(mailto:demo@demo.com)"}],
	stream=False,
)

for message in response:
	print(message, flush=True, end='')
```

**Comment by sdaqo** [comment]
Well then it works properly, no? That's chat gpt responding, you just have to work on your prompt. Tho this is probably not the place for asking about ai prompts. You can probably find some forum dedicated to that. This issue tracker is mainly for tracking bugs and feature requests of g4f.
