### ISSUE TITLE
Problen with curl-cffi

### ISSUE THREAD

**Issue by naduvatel** [xtekky/gpt4free#1019]
When i try install gpt4free this hapend:
× Building wheel for curl-cffi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-38
      creating build\lib.win32-cpython-38\curl_cffi
      copying curl_cffi\aio.py -> build\lib.win32-cpython-38\curl_cffi
      copying curl_cffi\build.py -> build\lib.win32-cpython-38\curl_cffi
      copying curl_cffi\const.py -> build\lib.win32-cpython-38\curl_cffi
      copying curl_cffi\curl.py -> build\lib.win32-cpython-38\curl_cffi
      copying curl_cffi\__init__.py -> build\lib.win32-cpython-38\curl_cffi
      creating build\lib.win32-cpython-38\curl_cffi\requests
      copying curl_cffi\requests\cookies.py -> build\lib.win32-cpython-38\curl_cffi\requests
      copying curl_cffi\requests\errors.py -> build\lib.win32-cpython-38\curl_cffi\requests
      copying curl_cffi\requests\headers.py -> build\lib.win32-cpython-38\curl_cffi\requests
      copying curl_cffi\requests\models.py -> build\lib.win32-cpython-38\curl_cffi\requests
      copying curl_cffi\requests\session.py -> build\lib.win32-cpython-38\curl_cffi\requests
      copying curl_cffi\requests\__init__.py -> build\lib.win32-cpython-38\curl_cffi\requests
      running egg_info
      writing curl_cffi.egg-info\PKG-INFO
      writing dependency_links to curl_cffi.egg-info\dependency_links.txt
      writing requirements to curl_cffi.egg-info\requires.txt
      writing top-level names to curl_cffi.egg-info\top_level.txt
      reading manifest file 'curl_cffi.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'curl_cffi\cacert.pem'
      warning: no files found matching 'curl_cffi\_wrapper.*'
      warning: no files found matching 'curl_cffi\include\curl\*'
      adding license file 'LICENSE'
      writing manifest file 'curl_cffi.egg-info\SOURCES.txt'
      creating build\lib.win32-cpython-38\curl_cffi\ffi
      copying curl_cffi\ffi\cdef.c -> build\lib.win32-cpython-38\curl_cffi\ffi
      copying curl_cffi\ffi\shim.c -> build\lib.win32-cpython-38\curl_cffi\ffi
      copying curl_cffi\ffi\shim.h -> build\lib.win32-cpython-38\curl_cffi\ffi
      running build_ext
      generating cffi module 'build\\temp.win32-cpython-38\\Release\\curl_cffi._wrapper.c'
      creating build\temp.win32-cpython-38
      creating build\temp.win32-cpython-38\Release
      building 'curl_cffi._wrapper' extension
      creating build\temp.win32-cpython-38\Release\build
      creating build\temp.win32-cpython-38\Release\build\temp.win32-cpython-38
      creating build\temp.win32-cpython-38\Release\build\temp.win32-cpython-38\Release
      creating build\temp.win32-cpython-38\Release\curl_cffi
      creating build\temp.win32-cpython-38\Release\curl_cffi\ffi
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Icurl_
cffi\include -Icurl_cffi\ffi -IC:\Users\User\PycharmProjects\gpt_test\venv\include -IC:\Python\include -IC:\Python\Include "-IC:\Program Files (x86)\Microsoft Visu
al Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Progr
am Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Ki
ts\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.
0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcbuild\temp.win32-cpython-38\Release\curl_cffi._wrapper.c /Fobuild\temp.win3
2-cpython-38\Release\build\temp.win32-cpython-38\Release\curl_cffi._wrapper.obj
      curl_cffi._wrapper.c
      curl_cffi\ffi\shim.h(5): fatal error C1083: ЌҐ г¤ Ґвбп ®вЄалвм д ©« ўЄ«озҐ­ЁҐ: curl/curl.h: No such file or directory,
      C:\Users\User\AppData\Local\Temp\pip-build-env-yupo13fj\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'curl_cffi.ffi' is ab
sent from the `packages` configuration.
      !!
     
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'curl_cffi.ffi' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
     
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'curl_cffi.ffi' is explicitly added
              to the `packages` configuration field.
     
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
     
              You can read more about "package discovery" on setuptools documentation page:
     
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
     
              If you don't want 'curl_cffi.ffi' to be distributed and are
              already explicitly excluding 'curl_cffi.ffi' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
     
              You can read more about "package data files" on setuptools documentation page:
     
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
     
     
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
     
      !!
        check.warn(importable)
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x86\\cl.exe' failed with exit
 code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for curl-cffi
Failed to build curl-cffi
ERROR: Could not build wheels for curl-cffi, which is required to install pyproject.toml-based projects
(venv) PS C:\Users\User\PycharmProjects\gpt_test>

**Comment by hlohaus** [comment]
Curl-cffi doesn't support Windows 32 bit

**Comment by thanhtoan1196** [comment]
I can't install g4f because curl-cffi on alpine
https://github.com/xtekky/gpt4free/issues/1171

**Comment by FujiwaraChoki** [comment]
> Curl-cffi doesn't support Windows 32 bit

So then how do we install the library?
