### ISSUE TITLE
Cloudflare Clearance bypass API

### ISSUE THREAD

**Issue by localuser-isback** [xtekky/gpt4free#102]
I have an API (currently no server for it yet) but its able to generate a cf_clearance token, the only 2 requirements are the requests sent right now using gpt4free need to use the firefox useragent since its less detected and they need to use a proxy, this is becasue clearance tokens are IP locked but you can host your own proxy with your network or wherever your running gpt4free and use that. The API supports authorized and non-authorized proxies and i think the usage of this API could really help as there would be no more need for manually getting the token yourself. I already dm'ed you on discord but making this post so more people can see it and i can get some ideas or questions.

**Comment by AbdelrhmanNile** [comment]
how to get the token manually?
