### ISSUE TITLE
All providers failed

### ISSUE THREAD

**Issue by ilyaChuk** [xtekky/gpt4free#1022]
does not work with any parameters, with any models, with any providers

```
import g4f
message_content = sys.argv[1] if len(sys.argv) > 1 else "hello"
response = g4f.ChatCompletion.create(
    model='gpt-3.5-turbo',
    messages=[{"role": "user", "content": message_content}],
    stream=True,
)

for message in response:
    print(message, flush=True)
```

gpt4free# python test.py
Traceback (most recent call last):
  File "/root/sentry/sh/gpt4free/test.py", line 41, in <module>
    for message in response:
  File "/root/sentry/sh/gpt4free/g4f/Provider/retry_provider.py", line 54, in create_completion
    self.raise_exceptions()
  File "/root/sentry/sh/gpt4free/g4f/Provider/retry_provider.py", line 77, in raise_exceptions
    raise RuntimeError("\n".join(["All providers failed:"] + [
RuntimeError: All providers failed:
Aibn: AttributeError: 'NoneType' object has no attribute 'create_future'
Myshell: WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://api.myshell.ai/ws/?EIO=4&transport=websocket')
ChatgptAi: RuntimeError: No system data
Aivvm: HTTPError: 403 Client Error: Forbidden for url: https://chat.geekgpt.org/
AItianhuSpace: AttributeError: 'NoneType' object has no attribute 'create_future'
DeepAi: ClientResponseError: 404, message='Not Found', url=URL('https://api.deepai.org/make_me_a_sandwich')
GptGo: ClientResponseError: 403, message='Forbidden', url=URL('https://gptgo.ai/action_get_token.php?q=%D0%97%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5+%D0%BF%D0%BE+%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E&hlgpt=default&hl=en')

(venv) root@cv3239573:~/sentry/sh/gpt4free# pip list
Package            Version
------------------ ---------
.......
g4f                0.1.5.6

**Comment by Doutianbao** [comment]
almost all providers failed

**Comment by zhangzhangzhiyuan** [comment]
meeeeeeeeeeeee tooooooooooooooooooooo

**Comment by DQ2020scut** [comment]
Mee too!!

**Comment by hlohaus** [comment]
Do you test other providers? The providers from the default list are almost not working.

And should try use a other IP address.
I used yesterday a VPN for GeminiPro and then almost other providers was not working anymore for me too
