### ISSUE TITLE
Could someone please make a video tutorial?

### ISSUE THREAD

**Issue by MattisBeck** [xtekky/gpt4free#1023]
Could someone please make a video tutorial on how to install and set this up properly? I just can't access the GUI and thus I can't use it. Thank you.

**Comment by zhangzhangzhiyuan** [comment]
hey bro, i have the same question. enen though i can access the gui, but the gpt cannot give any answer under my prompt

**Comment by 666demi** [comment]
Here's a video tutorial I just made: https://youtu.be/_NISztWi_yY
