### ISSUE TITLE
always religion words in Chinese

### ISSUE THREAD

**Issue by python-studio** [xtekky/gpt4free#1024]
![image](https://github.com/xtekky/gpt4free/assets/4996887/cbd20e20-93f0-41f1-90af-44985a0ddfa5)

**# OUTPUT: 和平归于你。我是《古兰经》的AI助手，有什么问题我可以帮助你解答吗？
OUTPUT means：
 Peace be upon you. I am an AI assistant for the Quran, are there any questions I can help you answer?**

### Quran：The classics of Islam

CODE：
import g4f
response = g4f.ChatCompletion.create(model='gpt-4',  # gpt-3.5-turbo, gpt-4
                                     provider=g4f.Provider.ChatBase,
                                     messages=[{"role": "user", "content": "你好"}],
                                     stream=False)

print(response) # OUTPUT: 和平归于你。我是《古兰经》的AI助手，有什么问题我可以帮助你解答吗？

response = g4f.ChatCompletion.create(model='gpt-4',  # gpt-3.5-turbo, gpt-4
                                     provider=g4f.Provider.ChatBase,
                                     messages=[{"role": "user", "content": "hello"}],
                                     stream=False)

print(response) # OUTPUT: Hello! How can I assist you today?

**Comment by zukixa** [comment]
this is a provider issue, do not use the gpt-4 of chatbase without a jailbreak

the bot of chatbase is a fine-tuned version that is system-prompted to be a Quran AI Assistant lol

use bing/myshell/phind/liaobots instead

**Comment by pygc** [comment]
@zukixa Haha, this is dangerous!

**Comment by luiso198** [comment]
How can I jailbreack with bing?


I have tried to use the api without success so I opted for this script.
I am using this script.

import g4f
from g4f.Provider import (
    Bing,
)
import io

response = g4f.ChatCompletion.create(
    model="gpt-4-32k",
    provider=g4f.Provider.Bing,
    messages=[{"role": "user", "content": "Write a 1000-word article on birds of prey"}],
    stream=True,
)

archive = io.open("respuesta.txt", "w")

for message in response:
    archivo.write(message + "\n")

archive.close()
