### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by zhangzhangzhiyuan** [xtekky/gpt4free#1027]
![image](https://github.com/xtekky/gpt4free/assets/105276759/069363ff-c1e1-4cb2-8705-ed9257d45d2c)
as the image shows that i dont know whether i have use the g4f correctly? 

if i use the that correctly, why it return the answear:<!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

i have to menthioned that : i located in China, so i used the Clash for github. is that any influences?

thanks for everyone,s reply

**Comment by Commenter123321** [comment]
if my pull request https://github.com/xtekky/gpt4free/pull/1033 gets approved, set the provider to aivvm and it will probably work

**Comment by xtekky** [comment]
The repository got updated, download a new version. I will soon add a proxy command line argument to `g4f.gui.run` or perhaps will you @Commenter123321 ?

you can also add a proxy to `g4f.ChatCompletion` via the `proxy` arg ( more documentation in the README.md)

**Comment by zhangzhangzhiyuan** [comment]
> if my pull request #1033 gets approved, download the updated version, set the provider to aivvm and it will probably work edit: the reason I say probably, is because I don't know if aivvm (provider) is blocked in china

so sad, i will try later and return you feedback

**Comment by zhangzhangzhiyuan** [comment]
> The repository got updated, download a new version. I will soon add a proxy command line argument to `g4f.gui.run` or perhaps will you @Commenter123321 ?
> 
> you can also add a proxy to `g4f.ChatCompletion` via the `proxy` arg ( more documentation in the README.md)

thansk for reply, hope the new version can work~  i use the network from educational net,  mayebe there is some restrictions tos top me~ thanks a lot!

**Comment by wangshuang0220** [comment]
> > The repository got updated, download a new version. I will soon add a proxy command line argument to `g4f.gui.run` or perhaps will you @Commenter123321 ?
> > you can also add a proxy to `g4f.ChatCompletion` via the `proxy` arg ( more documentation in the README.md)
> 
> thansk for reply, hope the new version can work~ i use the network from educational net, mayebe there is some restrictions tos top me~ thanks a lot!

500的问题解决了吗？我这里也是一样的错误，docker启动的

**Comment by LokeYourC3PH** [comment]
Issue persists, keep getting: 
<!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
