### ISSUE TITLE
H2o unavailable

### ISSUE THREAD

**Issue by vmjcv** [xtekky/gpt4free#1028]
**Bug description**

H2o is not working, They replaced it with a flow that works using websocket, but the gpt4free code flow was not updated

**Comment by xtekky** [comment]
hi, will update this ; )

**Comment by vmjcv** [comment]
other is the openaichat module with the
        headers = {
            "Accept": "text/event-stream",
            "Authorization": f "Bearer {access_token}".
        }
should be modified to headers = {
            "Content type: "application/json",
            "Authorization": f "Bearer {access_token}".
        }
 
 So that everything works.
