### ISSUE TITLE
Get 404 NOT FOUND in http://localhost:1337/ 

### ISSUE THREAD

**Issue by Doplars** [xtekky/gpt4free#1030]
**Bug description**
I followed the tutorial step by step. But after I entered 'docker compose up', I start http://localhost:1337/ in Edge , only to show '404 NOT FOUND'.

**Environement**
- WINDOWS 11
- PYTHON 3.11

**Screenshots**
![cmd](https://github.com/xtekky/gpt4free/assets/60698628/c5b9b105-7953-46d9-b9ab-add940f84f64)
![127 0 0 1](https://github.com/xtekky/gpt4free/assets/60698628/0ce34296-065d-418f-bfdf-0b6d5af84d97)

**Comment by 247592839** [comment]
![404](https://github.com/xtekky/gpt4free/assets/60698628/a957cafa-03af-473a-93c2-bd6dd3118655)

**Comment by xtekky** [comment]
this is the interference api, not the gui

**Comment by Doplars** [comment]
Thx, i got it.
