### ISSUE TITLE
Unable to install via pip install -U g4f

### ISSUE THREAD

**Issue by 666demi** [xtekky/gpt4free#1031]
**Bug description**
Yesterday I installed g4f on windows as the guide on Github says and successfully ran a local server for the GUI. I then shut down the PC. Today I ran the command to start a local server and this error showed up:
`C:\Python312\python.exe: Error while finding module specification for 'g4f.gui.run' (ModuleNotFoundError: No module named 'g4f')`

I then tried to reinstall g4f via pip, but another error showed up, saying that the installation required vcredist 14 or superior, which I had already installed but tried to reinstall anyway, without success in installing g4f afterwards.

**Log file**
[gpt_log.txt](https://github.com/xtekky/gpt4free/files/12855527/gpt_log.txt)

**Environement**
- python 311 when I first installed g4f, upgraded to 312 afterwards.
- location ( are you in a cloudfare flagged country ) ?

**Comment by xtekky** [comment]
Try installing [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/)

**Comment by Phleesty** [comment]
I have the same problem, should I install all 6 gb?

**Comment by 666demi** [comment]
for me the problem was python3.12 for whatever reason. I just uninstalled python and reinstalled its 3.11.x version and everything worked just fine. I don't know why and I don't think it is an issue directly caused by python312 but more likely by some compatibiliy issues between multiple things.

**Comment by Phleesty** [comment]
Indeed, the problem was in python 3.12. Reinstalled on 3.11.6 and everything was installed. Thanks

**Comment by deezed420** [comment]
does anybody know how to use it with 3.12? I just upgraded and I want all the benefits of 3.12
