### ISSUE TITLE
Remove DeepAI

### ISSUE THREAD

**Issue by deepai-org** [xtekky/gpt4free#1038]
Per the legal notice, "Sites may contact me to improve their security or request the removal of their site from this repository."

We would appreciate DeepAI being removed from this project. We consider it an unauthorized and harmful usage. Thank you.

**Comment by xtekky** [comment]
removed: https://github.com/xtekky/gpt4free/commit/c9c573a6e6721e84fd29ddbcd1911466db82aad0
