### ISSUE TITLE
ChatgptDuo inaccessible

### ISSUE THREAD

**Issue by vmjcv** [xtekky/gpt4free#1040]
**Bug description**
ChatgptDuo inaccessible
https://chatgptduo.com/ Cannot be successfully accessed from the Internet

**Comment by DoxrGitHub** [comment]
not really something you can control
![image](https://github.com/xtekky/gpt4free/assets/132623420/547954fd-efe1-46b4-9974-de330cb42377)

**Comment by Samari4052** [comment]
Remove

**Comment by DoxrGitHub** [comment]
sorry, wdym?

**Comment by zukixa** [comment]
site is back up, worth closing @xtekky

**Comment by vmjcv** [comment]
It's already accessible. It's probably just a maintenance outage.

![image](https://github.com/xtekky/gpt4free/assets/25278695/9b249e31-1f08-446f-a912-90e25cc6576e)

**Comment by vmjcv** [comment]
close it
