### ISSUE TITLE
How do I use the api in other clients

### ISSUE THREAD

**Issue by Joackk** [xtekky/gpt4free#1041]
**Bug description**
I used docker for the setup, and everything worked fine when I used the python scripts in the documentation to call the api, but I did not work properly in the client using the api, such as ChatGPT Next Web and Chatbox, how do I use the api in these programs?
![image](https://github.com/xtekky/gpt4free/assets/45162558/96a21824-f622-481b-9f66-c02814a99ea8)
![image](https://github.com/xtekky/gpt4free/assets/45162558/a9ccd10f-797a-4a2f-b79c-62e0fe27215f)

**Comment by zukixa** [comment]
you can only use these on selfhosted instances, and with localhost urls like http://127.0.0.1:1337, as you can't go on an online chatgpt nextweb site and plug in the interference app

and even then, do not add the http:// in that field, just the 127.0.0.1:1337 part, that's a chatgptnextweb thing

**Comment by Joackk** [comment]
> you can only use these on selfhosted instances, and with localhost urls like http://127.0.0.1:1337, as you can't go on an online chatgpt nextweb site and plug in the interference app
> 
> and even then, do not add the http:// in that field, just the 127.0.0.1:1337 part, that's a chatgptnextweb thing

I installed docker in my virtual machine. So here I'm using a LAN address. So we can't use it in some third-party programs? Are there any examples of such self-hosted programs?

**Comment by hussen1968** [comment]
you could try turning the local host into a normal host

**Comment by hlohaus** [comment]
i think the url is: http://127.0.0.1:1337/v1
