### ISSUE TITLE
Using the context of previous messages

### ISSUE THREAD

**Issue by danyl756** [xtekky/gpt4free#1045]
Hi, I'm creating a bot, how can I make GPT chat use the context of previous messages when a new message is sent from a user?

**Comment by huachuman** [comment]
This would be great to know. I don't see a point in using this API unless it can use the chat context.

**Comment by hlohaus** [comment]
You can have a chat context. Simply add your context to the messages.

A Conversation API is not planned or wanted.

**Comment by huachuman** [comment]
> You can have a chat context. Simply add your context to the messages.
> 
> A Conversation API is not planned or wanted.
> 
> Only Bing has in g4f a Conversation Api, but there is no Documentation jet.

I don't quite understand why it's set up the way it is then, to look and act as a chat interface, if it was never intended to take context into account.

**Comment by hlohaus** [comment]
Every provider support conversation with messages
