### ISSUE TITLE
llama (vercel) is broken

### ISSUE THREAD

**Issue by DoxrGitHub** [xtekky/gpt4free#1048]
if you try to use any of the llama models with vercel it returns
```
 raise ValueError(f"Model are not supported: {model}")
ValueError: Model are not supported: replicate:a16z-infra/llama13b-v2-chat
```

weirdly on vercel the model is the same and it's fine so idk what's happening. any fixes? (btw vercel provider seems fine)

**Comment by DoxrGitHub** [comment]
any umm updates or fixes on this?

**Comment by DoxrGitHub** [comment]
bruh does nobody care

**Comment by hlohaus** [comment]
They are many other llama provider
