### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by xtekky** [xtekky/gpt4free#105]
Hi, would someone be kind and make a video tutorial / youtube video on how to use this repo.
A lot of beginners have recently showed up in the issues and the instructions in the readme might not be enough

**Comment by DanielShemesh** [comment]
I made this replit based on the webui you provided https://replit.com/@gpt4free/gpt4free-webui
You can put this in the readme file so that people can fork this repl

**Comment by DanielShemesh** [comment]
I made this Jupyter notebook that might help
https://github.com/DanielShemesh/gpt4free-colab/blob/main/gpt4free.ipynb

I also submitted a pull request to add a link to the notebook in this repo

**Comment by d2rgaming-9000** [comment]
Iv never tried jupyter, I'll talk a look at it however.
