### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Whhhatttt** [xtekky/gpt4free#1054]
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1 (char 0)

Well.. For some reason - its not work. Not work when i try to get response.

**Comment by Lin-jun-xiang** [comment]
@DimasRulit 

I think this problem is same with #1052 when provider is `GptGo`
