### ISSUE TITLE
Not installed.

### ISSUE THREAD

**Issue by says112** [xtekky/gpt4free#1059]
Not installed.
![Снимок экрана (352)](https://github.com/xtekky/gpt4free/assets/22127398/2e5f343b-e132-428d-ba05-afb4a7d6bd30)

**Comment by xtekky** [comment]
this is an error with [curl_cffi](https://github.com/yifeikong/curl_cffi), not g4f.
Could you please send a full error log.
Also, It's not recommended to use g4f on server as server ip's are mostly flagged and g4f wont work

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by hlohaus** [comment]
I maked curl_cffi optional. I close this issue. Ok?
