### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CaiozScripts** [xtekky/gpt4free#106]
https://chat.forefront.ai/ 
It has GPT-4. You just sign up, click the + button 
![image](https://user-images.githubusercontent.com/117036935/234085169-0c44acb2-92d1-408f-87b3-c308a53b9bdd.png)
and it lets you change to GPT-4 model
![image](https://user-images.githubusercontent.com/117036935/234085718-589cae43-0325-43f6-a23d-ac3e41ee6312.png)
The thing is you can only have 10 prompts every 3 hours, but it at least has GPT-4

**Comment by Al3xlol** [comment]
Not worth adding due to limit unless there's way to bypass

**Comment by DanielShemesh** [comment]
you can simply automate creating new accounts as well, that's actually a great site (btw ora is also similarly limited)

**Comment by CaiozScripts** [comment]
> you can simply automate creating new accounts as well, that's actually a great site (btw ora is also similarly limited)

True, you can just put in a fake email address and boom

**Comment by xtekky** [comment]
ora has only gmail register, thats the problem, give me 2s and I'll reverse it, timer on

**Comment by xtekky** [comment]
will be added soon
