### ISSUE TITLE
Completion return something strange

### ISSUE THREAD

**Issue by kobzantsev** [xtekky/gpt4free#1061]
When I make 
response = g4f.ChatCompletion.create(
      model=model,
      messages=[{"role": "system", "content": "My Content."}, {"role": "user", "content": message}], stream=True,)
I see in print(response) this:

<generator object _create_completion at 0x7f60c8190ba0>

How I can see returned message from GPT?

**Comment by hoosnick** [comment]
The response with the `stream=True` parameter returns a generator, which you must iterate to see the messages.
Here's how to do it:

```python
# Streamed completion
response = g4f.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Hello"}],
    stream=True,
)

for message in response:
    print(message, flush=True, end='')
```
This code will print each message as it is generated by GPT. If you prefer not to use the `stream` parameter (or set it to `False`), you can use the following code to receive a normal response:

```python
# Normal response
response = g4f.ChatCompletion.create(
    model=g4f.models.gpt_4,
    messages=[{"role": "user", "content": "Hello"}],
)  # Alternative model setting

print(response)
```
This will print the complete response from GPT in a non-streamed manner.

**Comment by kobzantsev** [comment]
> The response with the `stream=True` parameter returns a generator, which you must iterate to see the messages. Here's how to do it:
> 
> ```python
> # Streamed completion
> response = g4f.ChatCompletion.create(
>     model="gpt-3.5-turbo",
>     messages=[{"role": "user", "content": "Hello"}],
>     stream=True,
> )
> 
> for message in response:
>     print(message, flush=True, end='')
> ```
> 
> This code will print each message as it is generated by GPT. If you prefer not to use the `stream` parameter (or set it to `False`), you can use the following code to receive a normal response:
> 
> ```python
> # Normal response
> response = g4f.ChatCompletion.create(
>     model=g4f.models.gpt_4,
>     messages=[{"role": "user", "content": "Hello"}],
> )  # Alternative model setting
> 
> print(response)
> ```
> 
> This will print the complete response from GPT in a non-streamed manner.

Thanks you, but with stream=False print(response) return nothng....

**Comment by kobzantsev** [comment]
One more: 
messages=[{"role": "system", "content": "My Content."}, {"role": "user", "content": message}], stream=True,)
Is this normal for g4f? I use this with openai and works fine

**Comment by sahilbrandwala** [comment]
+1
