### ISSUE TITLE
 cannot import name 'DDGS' from 'duckduckgo_search'

### ISSUE THREAD

**Issue by xgrons** [xtekky/gpt4free#1067]
**Bug description**
1. run g4f gui or python -m g4f.gui.run
2. See error  cannot import name 'DDGS' from 'duckduckgo_search'

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/62064902/87a5a4df-a3ec-497e-9756-0939b6a276f2)

**Environment**
- python

**Comment by mosfetti** [comment]
if this helps I solved by upgrading duckduckgo_search

`pip install --upgrade duckduckgo_search`

and upgrading pip

`python.exe -m pip install --upgrade pip `

**Comment by xgrons** [comment]
Thanks Worked
