### ISSUE TITLE
I don't understand why it's not working

### ISSUE THREAD

**Issue by LibertyEqualityFraternity** [xtekky/gpt4free#1071]
I've got an issue here:

* Serving Flask app 'g4f.api'
gpt4free-gpt4free-1  |  * Debug mode: off
gpt4free-gpt4free-1  | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
gpt4free-gpt4free-1  |  * Running on all addresses (0.0.0.0)
gpt4free-gpt4free-1  |  * Running on http://127.0.0.1:1337
gpt4free-gpt4free-1  |  * Running on http://172.18.0.2:1337

1. following the link http://127.0.0.1:1337 I see only a completely empty site with this: 'interference api, url: http://127.0.0.1:1337'
2. the link http://172.18.0.2:1337 doesn't work at all

127.0.0.1 - - [14/Oct/2023 18:41:04] "GET / HTTP/1.1" 200 -
172.20.10.3 - - [14/Oct/2023 18:41:14] "GET / HTTP/1.1" 200 -

**Environment**
- python version 3.11.6
- Russia

**Comment by kkarimwahba** [comment]
how to make it work again quickly?
