### ISSUE TITLE
quota limit (10) :(

### ISSUE THREAD

**Issue by ugh2235** [xtekky/gpt4free#1075]
Error Response: {'response': False, 'quota': {'total': 10, 'left': 0}, 'error': 'quota'}
why is there a limit of 10? I've tried every chat bot

**Comment by zukixa** [comment]
this is I think just actyoo/aichat provider, not any other provider. dont use either of those two lol

**Comment by ugh2235** [comment]
> this is I think just the aichat provider, not any other provider. only the aichat provider limits the quota to 10. replace ur provider

yeah I did that, but even after I changed it took a day to stop giving that error. works now taught thanks!
