### ISSUE TITLE
GptChatly and Phind not working at the moment, but fixable

### ISSUE THREAD

**Issue by Luneye** [xtekky/gpt4free#1079]
GptChatly now has a cloudflare protection, but we can get around it using TLS spoofing. If @hlohaus has some motivation to integrate one, that would be awesome knowing that it's one of the only gpt-4 fully working provider for now.

![image](https://github.com/xtekky/gpt4free/assets/73485421/131a298e-8aea-4558-945a-d6536c359c7d)

As for Phind, the service is just not available at the moment, which means the devs could be deploying a protection too. Let's hope it's not the case though!

![image](https://github.com/xtekky/gpt4free/assets/73485421/92c344db-a416-4865-8bce-d814b2e83a71)

**Comment by zukixa** [comment]
the phind error is usually just their server's shitting themselves, happens from time to time as I end up seeing these errors occasionally, doubt it's security

**Comment by Luneye** [comment]
Phind just came back indeed, I was worried for nothing lol
