### ISSUE TITLE
How to use private http proxies with Opchatgpts?

### ISSUE THREAD

**Issue by marz1k** [xtekky/gpt4free#1080]
How to use private http proxies with Opchatgpts?

response = await g4f.Provider.Opchatgpts.create_async(
                model="gpt-3.5-turbo",
                messages=message,
                proxies="https://ip:port@username:pass")

trying smth like this but it gives me an empty response. Before it was working

**Comment by hlohaus** [comment]
Try:
https://github.com/xtekky/gpt4free#proxy-support
```
response = await g4f.ChatCompletion.create_async(
    model=g4f.models.default,
    provider=g4f.Provider.Opchatgpts,
    messages=[{"role": "user", "content": "Hello"}],
    proxy="http://host:port",
    # or socks5://user:pass@host:port
)
```

**Comment by marz1k** [comment]
> Try: https://github.com/xtekky/gpt4free#proxy-support
> 
> ```
> response = await g4f.ChatCompletion.create_async(
>     model=g4f.models.default,
>     provider=g4f.Provider.Opchatgpts,
>     messages=[{"role": "user", "content": "Hello"}],
>     proxy="http://host:port",
>     # or socks5://user:pass@host:port
> )
> ```

Yeah, i tried it. I think the problem that the provider is not working
