### ISSUE TITLE
Fatal error from pip prevented installation.

### ISSUE THREAD

**Issue by BlKoolaid** [xtekky/gpt4free#1091]
**Screenshots**
![Screenshot 2023-10-16 224136](https://github.com/xtekky/gpt4free/assets/98129804/9f1c8829-a274-4b1c-bd29-d4af03364f1f)
![image](https://github.com/xtekky/gpt4free/assets/98129804/411f4e25-69cb-461e-8e42-a36af19d8133)

**Environment**
- 3.10.8. I installed 3.12 but every time I do python --version, it shows up as 3.10.8
- United States

**Additional context**
Never done something like this before so it's taken a couple days to get to this point (and i restarted because of other issues), but I've made it to where I need to install g4f, and neither method has worked for me.

**Comment by xtekky** [comment]
Hi, you can always git clone this repo aswell, and use `pip` instead of `pipx`

**Comment by 1202-Akinola-Terrence** [comment]
I tried pip and still had issues

**Comment by BlKoolaid** [comment]
I did, I tried pip and pipx and neither one worked for me.

**Comment by NiNiyas** [comment]
The first issue, aiohttp install error is because the stable version lf aiohttp, i.e 3.8.6 doesn't support python 3.12 yet, you have to downgrade python to 3.11 or install a beta build `pip install aiohttp==3.9.0b0`

**Comment by BlKoolaid** [comment]
i restarted it again and i'm still having troubles with the same error

**Comment by UntaDotMy** [comment]
try python 3.10.11

**Comment by BlKoolaid** [comment]
I fixed the past issue but now I'm getting:
Running on port 80
 * Serving Flask app 'g4f.gui.server.app'
 * Debug mode: off
Permission denied

when I run the GUI and:
 * Serving Flask app 'g4f.api'
 * Debug mode: off
Address already in use
Port 1337 is in use by another program. Either identify and stop that program, or start the server with a different port.

with the api

**Comment by BlKoolaid** [comment]
I don't think i'm getting the api error anymore, but I'm not sure how to fix the gui one
