### ISSUE TITLE
How can we do function calling like openai does with their models

### ISSUE THREAD

**Issue by Meshwa428** [xtekky/gpt4free#1093]
Is the function calling feature integrated in this library. If so then please help me out by providing a simple example please. Thanks in advance for help 🙏

**Comment by egorgutorovv** [comment]
The same request! At least it is possible to specify gpt-3.5-turbo-0613 as model parameter, and this version of model supports function calling in API

**Comment by Meshwa428** [comment]
Ya but here they are not using any sort of api, they are just bypassing and using the model's from other websites, so realy want to know that how will @xtekky do it

**Comment by egorgutorovv** [comment]
@Meshwa428 wow, thank you for insight. I thought ChatCompletion.create() replicates all input parameters from openai method calling API. That's why tried to inject function parameter by myself. No error occurred and I decided smth is wrong with my code.

**Comment by xtekky** [comment]
Unfortunately there is no api yet that allows passing on function calling.
