### ISSUE TITLE
Chinese text in the response even if the request is in another language

### ISSUE THREAD

**Issue by nBalykin** [xtekky/gpt4free#1094]
I made myself a personal telegram bot with your API. it's magical. but there is a problem. If I use "gpt-3.5-turbo", the api bot often responds with the text 流量异常. I tried to understand through logging which provider it was and simply remove it from the g4f code, but in the log the call goes to RetryProvider.

In this regard, I have two questions:
1. What kind of provider can behave this way?
2. Is there a way to display the real provider in the log, and not the RetryProvider layer?

![image](https://github.com/xtekky/gpt4free/assets/42620164/94dc6160-ff05-4414-9b11-ed21cf891bc3)

**Comment by zukixa** [comment]
pretty sure its yqcloud, could also be acytoo/aitanthu/aichat, but not sure on those

**Comment by zukixa** [comment]
as per https://github.com/xtekky/gpt4free/pull/1064
<img width="729" alt="image" src="https://github.com/xtekky/gpt4free/assets/56563509/3d13c58b-0171-49c7-ab77-5ca008fadf73">

**Comment by nBalykin** [comment]
If I understand everything correctly, these providers are used when choosing the gpt-3.5-turbo model. Now I’ll try to disable each of them in turn and write if the problem is solved. It will probably be necessary to remove this Chinese provider
![image](https://github.com/xtekky/gpt4free/assets/42620164/b5e365f8-a4f3-411d-bca9-2df0a37918ee)

**Comment by 321nextdev** [comment]
Same issue here too

**Comment by 321nextdev** [comment]
![image](https://github.com/xtekky/gpt4free/assets/131906037/4f9971b2-4abd-4687-bbb4-922d08b8f22a)

**Comment by 321nextdev** [comment]
> as per #1064 <img alt="image" width="729" src="https://user-images.githubusercontent.com/56563509/275979864-3d13c58b-0171-49c7-ab77-5ca008fadf73.png">

sadly didn't help

**Comment by Lin-jun-xiang** [comment]
@nBalykin 
Now u can upgrade `g4f`, then use `g4f.logging=True`.

When the `logging=True`, the terminal will show u which provider was trying.

```python
import g4f

g4f.logging = True # enable

print(
    g4f.ChatCompletion.create(
            model='gpt-3.5-turbo',
            messages=[{"role": "user", "content": "hello"}],
    )
)
```
