### ISSUE TITLE
It shows "当前地区当日额度已消耗完"

### ISSUE THREAD

**Issue by 321nextdev** [xtekky/gpt4free#1097]
**Bug description**
1. Install g4f from pip
2. Run the basic code from [here](https://github.com/xtekky/gpt4free#chatcompletion)
3. Wait a bit
4. See error which shows "当前地区当日额度已消耗完" (The quota for the current day in the current region has been exhausted.)

**Screenshots**
![screenshot](https://github.com/xtekky/gpt4free/assets/131906037/6c92b127-dfb1-4353-bf28-2d60d0b9fea0)

**Environment**
- python version Python 3.10.11
- location India
- running on Replit

**Additional context**
Firstly I got the "流量异常" occasionally then started always getting this ^ error.

**Comment by kobzantsev** [comment]
当前地区当日额度已消耗完 - what is this? After 0.1.6.6 update

**Comment by catmeowjiao** [comment]
看样子是提供商的问题，重新选择一个服务提供商
