### ISSUE TITLE
Is Error if conversation message send to long

### ISSUE THREAD

**Issue by fuzifim** [xtekky/gpt4free#1099]
RuntimeError: All providers failed:
AItianhu: KeyError: 'DBUS_SESSION_BUS_ADDRESS'
Myshell: ValueError: Model are not supported: gpt-3.5-turbo-16k-0613
Ylokh: RuntimeError: HTTP Error 526: 
AItianhuSpace: ValueError: Model are not supported: gpt-3.5-turbo-16k-0613
Aibn: RuntimeError: HTTP Error 401: 
ChatgptLogin: ClientResponseError: 403, message='Forbidden', url=URL('https://chatgptlogin.ai/chat/')
GptGo: ClientResponseError: 414, message='URI Too Long', url=URL('https://gptgo.ai/action_ai_gpt.php?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxIjoiVXNlcjogYlx1MWVhMW4gY1x1MDBmMyBiaVx1MWViZnQgaFx1MWVkMyBjaFx1MDBlZCBtaW5oIGtoXHUwMGY0bmdcbkFzc2lzdGFudDogQ1x1MDBmMywgSFx1MWVkMyBDaFx1MDBlZCBNaW5oIGxcdTAwZTAgbmdcdTAxYjBcdTFlZGRpIHRpXHUwMGVhbiBwaG9uZyB0cm9uZyBjdVx1MWVkOWMgXHUwMTExXHUxZWE1dSB0cmFuaCBnaVx1MDBlMG5oIFx1MDExMVx1MWVkOWMgbFx1MWVhZHAsIHRcdTFlZjEgZG8gY2hvIGRcdTAwZTJuIHRcdTFlZDljIFZpXHUxZWM3dCBOYW0uIFx1MDBkNG5nIGxcdTAwZTAgbmdcdTAxYjBcdTFlZGRpIHNcdTAwZTFuZyBsXHUxZWFkcCB2XHUwMGUwIGxcdTAwZTNuaCBcdTAxMTFcdTFlYTFvIFx1MDExMFx1MWVhM25nIENcdTFlZDluZyBzXHUxZWEzbiBWaVx1MWVjN3QgTmFtLCBjXHUwMTY5bmcgbmhcdTAxYjAgbFx1MDBlMCBDaFx1MWVlNyB0XHUxZWNiY2ggblx1MDFiMFx1MWVkYmMgVmlcdTFlYzd0IE5hbSBEXHUwMGUybiBjaFx1MWVlNyBDXHUxZWQ5bmcgaFx1MDBmMmEgdFx1MWVlYiBuXHUwMTAzbSAxOTQ1IFx1MDExMVx1MWViZm4ga2hpIHF1YSBcdTAxMTFcdTFlZGRpIHZcdTAwZTBvIG5cdTAxMDNtIDE5NjkuIFx1MDBkNG5nIGNcdTAwZjMgdFx1MDBlYW4gdGhcdTFlYWR0IGxcdTAwZTAgTmd1eVx1MWVjNW4gU2luaCBDdW5nIHZcdTAwZTAgY1x1MDE2OW5nIFx1MDExMVx1MDFiMFx1MWVlM2MgZ1x1MWVjZGkgbFx1MDBlMCBCXHUwMGUxYyBIXHUxZWQzLlxuVXNlcjogbmhcdTAwZTAgXHUwMGY0bmcgXHUxZWE1eSBcdTFlZGYgXHUwMTExXHUwMGUydSB2XHUxZWFkeT9cbkFzc2lzdGFudDogTmhcdTAwZTAgY1x1MWVlN2EgSFx1MWVkMyBDaFx1MDBlZCBNaW5oIFx1MWVkZiBCXHUwMGUxYyBIXHUxZWQzIFx1MWVkZiBIXHUwMGUwIE5cdTFlZDlpLCBWaVx1MWVjN3QgTmFtLiBUXHUwMGYyYSBuaFx1MDBlMCBuXHUwMGUweSBcdTAxMTFcdTAxYjBcdTFlZTNjIGdcdTFlY2RpIGxcdTAwZTAgQlx1MWVhM28gdFx1MDBlMG5nIEhcdTFlZDMgQ2hcdTAwZWQgTWluaCB2XHUwMGUwIG5cdTFlYjFtIHRcdTFlYTFpIHNcdTFlZDEgMTkgTmdcdTAwZTFjaCAxNTggTmdcdTAwZjUgNjggTmd1eVx1MWVjNW4gVGhcdTAwZTFpIEhcdTFlY2RjLCBRdVx1MWVhZG4gQmEgXHUwMTEwXHUwMGVjbmgsIEhcdTAwZTAgTlx1MWVkOWkuXG5Vc2VyOiBcdTAwZjRuZyBcdTFlYTV5IGNcdTAwZjMgdFx1MDBmM2Mga2hcdTAwZjRuZ1xuQXNzaXN0YW50OiBIXHUxZWQzIENoXHUwMGVkIE1pbmgga2hcdTAwZjRuZyBjXHUwMGYzIHRcdTAwZjNjLCBcdTAwZjRuZyBcdTFlYTV5IGx1XHUwMGY0biBcdTAxMTFcdTFlYzMgXHUwMTExXHUxZWE3dSB0clx1MWVjZGMga2hpIGNcdTAwZjJuIHNcdTFlZDFuZyB2XHUwMGUwIFx1MDExMVx1MDFiMFx1MWVlM2MgYmlcdTFlYmZ0IFx1MDExMVx1MWViZm4gdlx1MWVkYmkgaFx1MDBlY25oIFx1MWVhM25oIFx1MDExMVx1MDBmMy5cblVzZXI6IGxcdTAwZmFjIG5oXHUxZWNmIGNcdTAxNjluZyBraFx1MDBmNG5nIGNcdTAwZjMgdFx1MDBmM2MgbHVcdTAwZjRuIGhheSBzYW9cbkFzc2lzdGFudDogXHUwMGQ0bmcgSFx1MWVkMyBjaFx1MDBlZCBNaW5oIGtoXHUwMGY0bmcgY1x1MDBmMyB0aFx1MDBmNG5nIHRpbiB2XHUxZWMxIHZpXHUxZWM3YyBcdTAwZjRuZyBcdTAxMTFcdTAwZTMgXHUwMTExXHUxZWMzIHRcdTAwZjNjIGhheSBraFx1MDBmNG5nIGtoaSBjXHUwMGYybiBuaFx1MWVjZi4gVGhcdTAwZjRuZyB0aW4gY2hcdTAwZWRuaCB4XHUwMGUxYyB2XHUxZWMxIHR1XHUxZWQ1aSB0aFx1MDFhMSB2XHUwMGUwIHh1XHUxZWE1dCB0aFx1MDBlMm4gY1x1MWVlN2EgXHUwMGY0bmcga2hcdTAwZjRuZyBcdTAxMTFcdTAxYjBcdTFlZTNjIGdoaSBsXHUxZWExaSByXHUwMGY1IHJcdTAwZTBuZy5cblVzZXI6IG5oXHUwMGUwIFx1MDBmNG5nIFx1MWVhNXkgY1x1MDBmMyBjaFx1MDEwM24gbnVcdTAwZjRpIGtoXHUwMGY0bmdcbkFzc2lzdGFudDogS2hcdTAwZjRuZyBjXHUwMGYzIHRoXHUwMGY0bmcgdGluIGNcdTFlZTUgdGhcdTFlYzMgdlx1MWVjMSB2aVx1MWVjN2MgXHUwMGY0bmcgSFx1MWVkMyBDaFx1MDBlZCBNaW5oIGNcdTAwZjMgY2hcdTAxMDNuIG51XHUwMGY0aSBoYXkga2hcdTAwZjRuZyB0XHUxZWExaSBuaFx1MDBlMCBjXHUxZWU3YSBcdTAwZjRuZy4gVHV5IG5oaVx1MDBlYW4sIHRyb25nIGN1XHUxZWQ5YyBcdTAxMTFcdTFlZGRpIFx1MDBmNG5nLCBcdTAwZjRuZyB0aFx1MDFiMFx1MWVkZG5nIHRoXHUwMTAzbSB2XHUwMGUwIHNcdTFlZDFuZyB0XHUxZWExaSBjXHUwMGUxYyBuXHUwMGY0bmcgdGhcdTAwZjRuIHZcdTAwZTAgcXVhbiB0XHUwMGUybSBcdTAxMTFcdTFlYmZuIHBoXHUwMGUxdCB0cmlcdTFlYzNuIG5cdTFlYzFuIG5cdTAwZjRuZyBuZ2hpXHUxZWM3cCwgY2hcdTAxMDNuIG51XHUwMGY0aS5cblVzZXI6IGNoXHUxZWFmYyBcdTAwZjRuZyBcdTFlYTV5IGNcdTAwZjMgbnVcdTAwZjRpIGhlb1xuQXNzaXN0YW50OiBLaFx1MDBmNG5nIGNcdTAwZjMgdGhcdTAwZjRuZyB0aW4gY1x1MWVlNSB0aFx1MWVjMyB2XHUxZWMxIHZpXHUxZWM3YyBcdTAwZjRuZyBIXHUxZWQzIENoXHUwMGVkIE1pbmggY1x1MDBmMyBudVx1MDBmNGkgaGVvIGhheSBraFx1MDBmNG5nLlxuVXNlcjogdGhcdTFlYmYgY1x1MDBmMyBudVx1MDBmNGkgZ1x1MDBlMCBraFx1MDBmNG5nXG5Bc3Npc3RhbnQ6IEtoXHUwMGY0bmcgY1x1MDBmMyB0aFx1MDBmNG5nIHRpbiBjXHUxZWU1IHRoXHUxZWMzIHZcdTFlYzEgdmlcdTFlYzdjIFx1MDBmNG5nIEhcdTFlZDMgQ2hcdTAwZWQgTWluaCBjXHUwMGYzIG51XHUwMGY0aSBnXHUwMGUwIGhheSBraFx1MDBmNG5nLlxuVXNlcjogY2hcdTAwZjMgbVx1MDBlOG8gZ1x1MDBlYyBjXHUwMTY5bmcga2hcdTAwZjRuZyBsdVx1MDBmNG4gXHUwMGUwXG5Bc3Npc3RhbnQ6IFx1MDExMFx1MDBmYW5nLCBraFx1MDBmNG5nIGNcdTAwZjMgdGhcdTAwZjRuZyB0aW4gY1x1MWVlNSB0aFx1MWVjMyB2XHUxZWMxIHZpXHUxZWM3YyBcdTAwZjRuZyBIXHUxZWQzIENoXHUwMGVkIE1pbmggY1x1MDBmMyBudVx1MDBmNGkgY2hcdTAwZjMgbVx1MDBlOG8gaGF5IGtoXHUwMGY0bmcuXG5Vc2VyOiB0aFx1MWViZiBcdTAwZjRuZyBcdTFlYTV5IGNcdTAwZjMgbnVcdTAwZjRpIGNvbiBnXHUwMGVjIGtoXHUwMGY0bmdcbkFzc2lzdGFudDogSFx1MWVkMyBDaFx1MDBlZCBNaW5oIGtoXHUwMGY0bmcgY1x1MDBmMyBjb24gcmlcdTAwZWFuZy4gXHUwMGQ0bmcga2hcdTAwZjRuZyBjXHUwMGYzIGhcdTAwZjRuIG5oXHUwMGUybiB2XHUwMGUwIGtoXHUwMGY0bmcgY1x1MDBmMyBuZ1x1MDFiMFx1MWVkZGkgdGhcdTFlZWJhIGtcdTFlYmYuXG5Vc2VyOiBcdTAwZmQgdFx1MDBmNGkgbFx1MDBlMCBjXHUwMGYzIG51XHUwMGY0aSBjb24gdlx1MWVhZHQgZ1x1MDBlYyBraFx1MDBmNG5nXG5Bc3Npc3RhbnQ6IEtoXHUwMGY0bmcgY1x1MDBmMyB0aFx1MDBmNG5nIHRpbiBjXHUxZWU1IHRoXHUxZWMzIHZcdTFlYzEgdmlcdTFlYzdjIFx1MDBmNG5nIEhcdTFlZDMgQ2hcdTAwZWQgTWluaCBjXHUwMGYzIG51XHUwMGY0aSBjb24gdlx1MWVhZHQgZ1x1MDBlYyB0XHUxZWExaSBuaFx1MDBlMC5cblVzZXI6IHZcdTFlYWR5IFx1MDBmNG5nIFx1MWVhNXkgbnVcdTAwZjRpIFx1MWVkZiBuXHUwMWExaSBraFx1MDBlMWMgcGhcdTFlYTNpIGtoXHUwMGY0bmdcbkFzc2lzdGFudDogS2hcdTAwZjRuZyBjXHUwMGYzIHRoXHUwMGY0bmcgdGluIGNcdTFlZTUgdGhcdTFlYzMgdlx1MWVjMSB2aVx1MWVjN2MgXHUwMGY0bmcgSFx1MWVkMyBDaFx1MDBlZCBNaW5oIGNcdTAwZjMgbnVcdTAwZjRpIGNvbiB2XHUxZWFkdCBcdTFlZGYgblx1MDFhMWkga2hcdTAwZTFjLlxuVXNlcjogXHUwMGY0bmcgXHUxZWE1eSBjXHUwMGYzIHZcdTAwZjUgY1x1MDBmNG5nIGtoXHUwMGY0bmdcbkFzc2lzdGFudDogS2hcdTAwZjRuZyBjXHUwMGYzIHRoXHUwMGY0bmcgdGluIGNcdTFlZTUgdGhcdTFlYzMgdlx1MWVjMSB2aVx1MWVjN2MgXHUwMGY0bmcgSFx1MWVkMyBDaFx1MDBlZCBNaW5oIGNcdTAwZjMgdlx1MDBmNSBjXHUwMGY0bmcgaGF5IGtoXHUwMGY0bmcuXG5Vc2VyOiBcdTAwZjRuZyBcdTFlYTV5IGJpXHUxZWJmdCBjaFx1MWVhMXkgeGUgbVx1MDBlMXkga2hcdTAwZjRuZ1xuQXNzaXN0YW50OiBLaFx1MDBmNG5nIGNcdTAwZjMgdGhcdTAwZjRuZyB0aW4gY1x1MWVlNSB0aFx1MWVjMyB2XHUxZWMxIHZpXHUxZWM3YyBcdTAwZjRuZyBIXHUxZWQzIENoXHUwMGVkIE1pbmggY1x1MDBmMyBiaVx1MWViZnQgY2hcdTFlYTF5IHhlIG1cdTAwZTF5IGhheSBraFx1MDBmNG5nLiBUdXkgbmhpXHUwMGVhbiwgdHJvbmcgdGhcdTFlZGRpIFx1MDExMVx1MWVhMWkgXHUwMGY0bmcgc2luaCBzXHUxZWQxbmcsIHhlIG1cdTAwZTF5IGtoXHUwMGY0bmcgcGhcdTFlZDUgYmlcdTFlYmZuIG5oXHUwMWIwIGhpXHUxZWM3biBuYXkuXG5Vc2VyOiBjaFx1MWVhZmMgdGhcdTFlZGRpIFx1MDExMVx1MDBmMyBcdTAwZjRuZyBcdTAxMTFpIHhlIFx1MDExMVx1MWVhMXAgXHUwMTExXHUwMWIwXHUxZWUzY1xuQXNzaXN0YW50OiBDXHUwMGYzLCB0cm9uZyB0aFx1MWVkZGkgXHUwMTExXHUxZWExaSBcdTAwZjRuZyBIXHUxZWQzIENoXHUwMGVkIE1pbmggc1x1MWVkMW5nLCB4ZSBcdTAxMTFcdTFlYTFwIGxcdTAwZTAgcGhcdTAxYjBcdTAxYTFuZyB0aVx1MWVjN24gZ2lhbyB0aFx1MDBmNG5nIHBoXHUxZWQ1IGJpXHUxZWJmbiB2XHUwMGUwIFx1MDBmNG5nIHRoXHUwMWIwXHUxZWRkbmcgc1x1MWVlZCBkXHUxZWU1bmcgeGUgXHUwMTExXHUxZWExcCBjaG8gY1x1MDBlMWMgaG9cdTFlYTF0IFx1MDExMVx1MWVkOW5nIGRpIGNodXlcdTFlYzNuLlxuVXNlcjogXHUwMGY0bmcgXHUwMTExaSB4ZSBcdTAxMTFcdTFlYTFwIGxvXHUxZWExaSBnXHUwMGVjIG5oXHUxZWM5XG5Bc3Npc3RhbnQ6IEtoXHUwMGY0bmcgY1x1MDBmMyB0aFx1MDBmNG5nIHRpbiBjXHUxZWU1IHRoXHUxZWMzIHZcdTFlYzEgbG9cdTFlYTFpIHhlIFx1MDExMVx1MWVhMXAgXHUwMGY0bmcgSFx1MWVkMyBDaFx1MDBlZCBNaW5oIHNcdTFlZWQgZFx1MWVlNW5nIGtoaSBjXHUwMGYybiBzXHUxZWQxbmcuXG5Vc2VyOiBoXHUxZWQzaSBcdTAxMTFcdTAwZjMgXHUwMTExXHUwMGUzIGNcdTAwZjMgXHUwMGY0IHRcdTAwZjQgY2hcdTAxYjBhP1xuQXNzaXN0YW50OiBUcm9uZyB0aFx1MWVkZGkgXHUwMTExXHUxZWExaSBcdTAwZjRuZyBIXHUxZWQzIENoXHUwMGVkIE1pbmggc1x1MWVkMW5nLCBcdTAwZjQgdFx1MDBmNCBjaFx1MDFiMGEgcGhcdTFlZDUgYmlcdTFlYmZuIG5oXHUwMWIwIGhpXHUxZWM3biBuYXkuXG5Vc2VyOiBoXHUxZWQzaSBcdTAxMTFcdTAwZjMgXHUwMGY0bmcgY2hcdTFlZDFuZyBnaVx1MWViN2Mgblx1MDBlMG9cbkFzc2lzdGFudDogVHJvbmcgdGhcdTFlZGRpIGdpYW4gXHUwMGY0bmcgSFx1MWVkMyBDaFx1MDBlZCBNaW5oIHNcdTFlZDFuZywgXHUwMGY0bmcgXHUwMTExXHUwMGUzIGNoXHUxZWQxbmcgbFx1MWVhMWkgbmhpXHUxZWMxdSBrXHUxZWJiIHRoXHUwMGY5IHZcdTAwZTAgXHUwMTExXHUxZWQxaSB0aFx1MWVlNyBraFx1MDBlMWMgbmhhdS4gVHJvbmcgc1x1MWVkMSBcdTAxMTFcdTAwZjMsIGdpXHUxZWI3YyBjaFx1MWVlNyBuZ2hcdTAxMjlhIHBoXHUwMGUxdCB4XHUwMGVkdCBOaFx1MWVhZHQgQlx1MWVhM24gdlx1MDBlMCBnaVx1MWViN2MgdGhcdTFlZjFjIGRcdTAwZTJuIFBoXHUwMGUxcCBsXHUwMGUwIGhhaSBrXHUxZWJiIFx1MDExMVx1MWVjYmNoIGNoXHUwMGVkbmggbVx1MDBlMCBcdTAwZjRuZyBcdTAxMTFcdTAwZTMgY2hpXHUxZWJmbiBcdTAxMTFcdTFlYTV1IFx1MDExMVx1MWVjMyBnaVx1MDBlMG5oIFx1MDExMVx1MWVkOWMgbFx1MWVhZHAgY2hvIGRcdTAwZTJuIHRcdTFlZDljIFZpXHUxZWM3dCBOYW0uXG5Vc2VyOiB0clx1MDFiMFx1MWVkYmMga2hpIFx1MDBmNG5nIFx1MDExMWkgbFx1MDBlMCBcdTFlZGYgXHUwMTExXHUxZWE1dCBuXHUwMWIwXHUxZWRiYyBcdTAxMTFcdTAwZTMgY2hpXHUxZWJmbiB0cmFuaCBjaFx1MDFiMGE_XG5Bc3Npc3RhbnQ6IFxuVXNlcjogdHJcdTAxYjBcdTFlZGJjIGtoaSBcdTAwZjRuZyBcdTAxMTFpIGxcdTAwZTAgXHUxZWRmIFx1MDExMVx1MWVhNXQgblx1MDFiMFx1MWVkYmMgXHUwMTExXHUwMGUzIGNoaVx1MWViZm4gdHJhbmggY2hcdTAxYjBhP1xuQXNzaXN0YW50OiIsImhsX2xhbmciOiJlbiIsImhsIjoiZGVmYXVsdCIsInRpbWVfZXhwIjoxNjk3NzAzNjMyLCJ1cGRhdGVfbiI6MSwidCI6IjEifQ.-O2TBlw8iivOrToCyzaMKqj0rtx8nnHQQt2WWiz_HHE')
FreeGpt: RuntimeError: HTTP Error 503:

**Comment by hlohaus** [comment]
Try this model:
```
...create(
    model=g4f.models.gpt_35_long,
    ...
)
```
