### ISSUE TITLE
How to build g4f on my machine?

### ISSUE THREAD

**Issue by catmeowjiao** [xtekky/gpt4free#1103]
I encountered an issue when building g4f on my own.

Here are the steps I followed:

1. Cloned the g4f repository.
2. Created a virtual environment using virtualenv.
3. Ran "pip install -r requirements.txt".
4. Ran "pip install --upgrade pip".
5. Ran "python setup.py build".
6. Ran "python setup.py install".
7. Ran "g4f gui".

I received an error at step 7:
"from .server.app import app
g4f.gui.server.app not found."

Upon checking the site-packages directory, I found that "g4f/gui/server" is missing. I would like to know why this is happening. Please note that I cannot use PyPI for building as I require support for "/v1". Can you provide me the correct build command?

System: Arch Linux x86_64
Python Version: 3.11

Thank you!

Translate by ChatGPT

**Comment by catmeowjiao** [comment]
@xtekky

**Comment by catmeowjiao** [comment]
I understand that you have not uploaded MANIFEST.in to the GitHub repository. I suggest removing the ignore on that file, otherwise, users will not be able to build g4f on their own.
@xtekky

**Comment by xtekky** [comment]
fixed
