### ISSUE TITLE
Cloud Hosting is broken with latest commit.

### ISSUE THREAD

**Issue by Aman122641** [xtekky/gpt4free#1104]
**Known Issues** // delete this
- you.com issue / fix: use proxy, or vpn, your country is probably flagged
- forefront account creation error / use your own session or wait for fix

**Bug description**
When trying to host on any hosting site, it works for a few minutes, but then it breaks and becomes unusable.

ex.
1. Go to 'any hosting site'
2. Host this project
3. Wait a few minutes

**Screenshots**

**Environment**
- 3.9-10
- USA ( are you in a cloudfare flagged country ) ?

**Additional context**’
When you host on a hosting platform, it breaks after a couple mins. The model list fails to load and you are unable to send messages.

**Comment by xtekky** [comment]
Was this not an issue before ?

**Comment by Aman122641** [comment]
My second issue was, but not the first

**Comment by xtekky** [comment]
should be fixed now in latest update, let me know if it works @Aman122641

**Comment by Aman122641** [comment]
My first one just started happening after the update

**Comment by Aman122641** [comment]
Okay, Thanks!

**Comment by xtekky** [comment]
iOS does not seem to be working, I just checked, I will be trying to solve the issue ; )

**Comment by xtekky** [comment]
this is now fixed in the latest commit, the changed were not published to pypi yet, so you can git clone the project to get the latest gui version

**Comment by Aman122641** [comment]
Do you think you will be able to solve the issue about iframe? Last question.

**Comment by Aman122641** [comment]
> this is now fixed in the latest commit [04edb66](https://github.com/xtekky/gpt4free/commit/04edb6606512172262b33859a42d132012373d88), the changes were not published to pypi yet, so you can git clone the project to get the latest gui version

Do you think you will be able to solve the issue about the website scrolling down when in a iframe? Last question. @xtekky
