### ISSUE TITLE
No module named 'tiktoken'

### ISSUE THREAD

**Issue by tomasantunes** [xtekky/gpt4free#1109]
**Bug description**
I used docker-compose to build the repo and when I entered the command "docker compose up" I got an error saying "No module named tiktoken".

**Screenshots**
![gpt4free-error](https://github.com/xtekky/gpt4free/assets/12017352/97728fae-64a6-4c64-ae79-4231772b6cc8)

**Environment**
Windows 10
Docker v20.10.22

**Comment by xtekky** [comment]
fixed it in the latest commit

**Comment by taotokio** [comment]
> fixed it in the latest commit

windows CMD run "g4f gui"  also tip "No module named tiktoken" too
![image](https://github.com/xtekky/gpt4free/assets/90232612/c7540b0f-de66-495d-b371-a5989e1813ed)

**Comment by prstzbd** [comment]
> windows CMD run "g4f gui" also tip "No module named tiktoken" too
pip install tiktoken
