### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by tomasantunes** [xtekky/gpt4free#1110]
**Bug description**
I built the repo with docker-compose and when I enter the command "docker-compose up" I get the following error: "Cannot assign requested address".

**Screenshots**
![gpt4free-error2](https://github.com/xtekky/gpt4free/assets/12017352/efff1658-aafa-4830-9649-7138df314850)

**Environment**
Windows 10
Docker v20.10.22

**Comment by dsakura** [comment]
same here, thanks

**Comment by xtekky** [comment]
fixed
