### ISSUE TITLE
How to ignore certain providers in api?

### ISSUE THREAD

**Issue by AndPim4912** [xtekky/gpt4free#1114]
g4f api uses iteration to choose working provider.

I want to write custom cli endpoint with optional arguments to ignore certain providers by name.
Please, advice me, what g4f library code is responsible for ignoring certain providers? I'll gently inherit it.

**Comment by xtekky** [comment]
```py
class ChatCompletion:
    @staticmethod
    def create(model    : Union[Model, str],
               messages : Messages,
               provider : Union[type[BaseProvider], None] = None,
               stream   : bool = False,
               auth     : Union[str, None] = None,
               ignored  : List[str] = None, # <----- ignore Providers
               ignore_working: bool = False, **kwargs) -> Union[CreateResult, str]:
```

you can use the `ignored` argument

```py
import g4f
from g4f.Provider import A, B, C

completion = g4f.ChatCompletion,create(..., ignored = [A, B, C])
```

**Comment by nBalykin** [comment]
> from g4f.Provider import A, B, C

For me ignored works withoot import providers in this case. 
But I use srt: ignored = ['name_ignored_1', 'Name_ignored_2']

**Comment by egcash** [comment]
Will ignored argument work with Openai request method??
