### ISSUE TITLE
Got Runtime Error on Render

### ISSUE THREAD

**Issue by egcash** [xtekky/gpt4free#1116]
When I deployed this service on Render,gpt 3 and 4 models were working correctly,but as soon as I try to use another models like santacoder,bloom or command-nigtly etc... got the **ERROR**:

**Could not find an available JavaScript runtime."
}**

**Comment by zukixa** [comment]
vercel provider needs javascript on the device, so a node/nvm instance is needed
need to set that up correctly on render so that it works properly
