### ISSUE TITLE
Work with files

### ISSUE THREAD

**Issue by nBalykin** [xtekky/gpt4free#1117]
I have a couple of questions:

Can any of the providers work with images? Perhaps there is a way to send them to the API or receive them from it.

Second question - do the APIs support file transfers? One time gpt4 replied to me that it sent me a file. But I work through a telegram bot and could not accept this file (it’s trivial that I don’t have such code for file resend in telebot).

**Comment by hlohaus** [comment]
Bing supports since yesterday passing a image. You can add files in your prompt. Example:
```
` ` ` py
print("Hello")
` ` `
Without spaces
```
