### ISSUE TITLE
openai chat need arkose

### ISSUE THREAD

**Issue by vmjcv** [xtekky/gpt4free#1129]
**Bug description**
- the chat.openai.com need add arkose_token
- If you make a request on the website, the required structure is
![image](https://github.com/xtekky/gpt4free/assets/25278695/14a93d5d-7422-4847-9647-c35b93604c55)
- but we do not add arkose_token, so you will get response like this:
{"message": null, "conversation_id": "2d7c72e7-cd52-4d36-9749-253053f54045", "error": "Our systems have detected unusual activity from your system. Please try again later."}

**Environment**
- python version

**Additional context**
i think you need add arkose_token support. 
The codes that can be referenced are:
https://github.com/linweiyuan/chatgpt-arkose-token-api/blob/main/browser/browser.go
https://github.com/acheong08/funcaptcha/commit/f4d081d60ac780f9ff558c29f42f452e057b84db
https://linweiyuan.github.io/2023/06/24/%E5%A6%82%E4%BD%95%E7%94%9F%E6%88%90-GPT-4-arkose-token.html

**Comment by hlohaus** [comment]
There are openai proxy Projects. They solve it with a hosted custom url. Should i add a config? I added the provider in my free time. For g4f i need python code not Go.

**Comment by vmjcv** [comment]
>They solve it with a hosted custom url
There is a high probability that this solution will not solve the problem

>For g4f i need python code not Go.
Yes, you need Python code equivalent to this go code, or you can use js2py to call the JavaScript code to obtain the arkose_ Token

>Should i add a config.  The FakeGpt Provider use/has the Openai GPT 3 Chat too. For example
if you just add arkose_token = "", the response is "Our systems have detected unusual activity from your system. Please try again later.". You need an effective arkose_ Token

If you don't add arkose_Token, for most users, this provider is not immediately available and it is best to add support

**Comment by hlohaus** [comment]
@vmjcv  I created a PR with arkose_token. Can you test it?
https://github.com/xtekky/gpt4free/pull/1177

**Comment by vmjcv** [comment]
> 我用arkose_token创建了一个 PR。你能测试一下吗？ #1177

Not responding in a timely manner due to travel reasons

Let me test it

**Comment by vmjcv** [comment]
RuntimeError: Our systems have detected unusual activity from your system. Please try again later.

my test code
```
import g4f

from g4f.Provider import (
    OpenaiChat,
)

# Usage:
response = g4f.ChatCompletion.create(
    model=g4f.models.default,
    messages=[{"role": "user", "content": "Hello"}],
    provider=OpenaiChat,
    access_token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ2bWpjdjY2NkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJwb2lkIjoib3JnLTZFRjBVbG8yYUFOajY2d3VOYVk0WjRRWiIsInVzZXJfaWQiOiJ1c2VyLTZDWWppTGtYS2g1aDBIbXJMVjlLc1VDbiJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTQxNzU1MjUzMTE4MTIxNjUyOTIiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk4OTI1OTg1LCJleHAiOjE2OTk3ODk5ODUsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb3JnYW5pemF0aW9uLndyaXRlIG9mZmxpbmVfYWNjZXNzIn0.GribU6YP507-dh5R917wNklfZVzTlySqk158QtWlcMkFLhtGBzcrBcRrHXCRly1ZHImpHhhJcRlFNYD-9vAIYVXQFqfelSTFKNUP18R7vq4etHGM4x7IAfdEZ_RXnlqxhp7qOLXHlCR06jIv0cf_Kq3ozTjXqROgCjEOGp0XJ4_KLLaaJWk8verqzj7AE__FJCp__n_e_YBwtjmeB4MGyXTwFKieS5sRbooiccm04e7L_EQE0PoXvK4kGwVtQvOYyO7O5m96SWPFPWd8YW4syuS6YekeOYTIAtA3SJtR9K4V6radUdD4dGKccY5NCPmVNvyy2g_u1ZV9zMCRg20C2w",
    proxy = "127.0.0.1:55235",
    auth=True
)
```

**Comment by thanhtoan1196** [comment]
FakeGpt provider is not working now :(

**Comment by thanhtoan1196** [comment]
> FakeGpt provider is not working now :(

any updates?
