### ISSUE TITLE
No module named g4f.api.__main__; 'g4f.api' is a package and cannot be directly executed. How to fix it?

### ISSUE THREAD

**Issue by My12123** [xtekky/gpt4free#1130]
```python
(venv) F:\gpt4free>python -m g4f.api
F:\gpt4free\venv\Scripts\python.exe: No module named g4f.api.__main__; 'g4f.api' is a package and cannot be directly executed
``` 
![2023-10-23_19-05-07](https://github.com/xtekky/gpt4free/assets/49092250/a467dada-5f7d-4246-b843-4ad775ee6588)

**Comment by hlohaus** [comment]
You forgot Step 4:
Activate the virtual environment:

On Windows:

.\venv\Scripts\activate 

On macOS and Linux:

source venv/bin/activate

**Comment by My12123** [comment]
![2023-10-23_19-36-54](https://github.com/xtekky/gpt4free/assets/49092250/693289cc-d4be-46b0-8e45-0d57ac002076)
the environment is activated

**Comment by My12123** [comment]
No module named g4f.api.__main__; 'g4f.api' is a package and cannot be directly executed. How to fix it?

**Comment by luiso198** [comment]
Same problem.

**Comment by luiso198** [comment]
I am using docker

**Comment by grandpa1946** [comment]
still no solution...

**Comment by cbrom** [comment]
you could use `python -m g4f.api.run` I guess.

**Comment by grandpa1946** [comment]
> you could use `python -m g4f.api.run` I guess.

ok thanks
