### ISSUE TITLE
Suggesting another chatbot model💪

### ISSUE THREAD

**Issue by Meshwa428** [xtekky/gpt4free#1138]
It would be great to have PI in this project, because why not? It's the best chatbot available at this time

You can try PI here:
[`PI`](https://pi.ai/)

**Comment by xtekky** [comment]
Not really, they have their own model and it offers poor performance 
<img width="675" alt="image" src="https://github.com/xtekky/gpt4free/assets/98614666/e6c4f05c-1f9a-48b6-ac58-3dd5c5e2eb57">

**Comment by Turbo1337GS** [comment]
Hello, find a list of SOCK5 proxy servers on GitHub and use them! The provider will then think that someone new is connecting
