### ISSUE TITLE
Fix for "Permission Denied" when running g4f gui (port `80` blocked)

### ISSUE THREAD

**Issue by avionmission** [xtekky/gpt4free#1139]
**Error description**
I'm trying to run g4f gui locally but facing an error. I executed the following command:
```bash
pipx install g4f
```
The package installed successfully and notified "These apps are now globally available - g4f".

But when I run `g4f gui`, I get the following response:
```bash
Running on port 80
 * Serving Flask app 'g4f.gui.server.app'
 * Debug mode: off
Permission denied
```
I tried executing the g4f command as a root user in ubuntu which also did not work.

Can anyone help me with how to fix this "Permission denied" error? Thanks.

**Comment by Lin-jun-xiang** [comment]
In my case, I used different port instead of 80 to solved:

**CLI**:
```
python -m g4f.gui.run -port 5000
```

**Python**:

```python
from g4f.gui import run_gui

run_gui()
```

**Comment by xtekky** [comment]
I figured out that there is poor documentation on the args of the gui, but I am writing docs at the moment which will be published soon.

i believe that the port 80 is not available on linux due to another application running on it, but changing it with the `-port` arg is the right solution indeed

**Comment by avionmission** [comment]
Thanks @Lin-jun-xiang , the app is running fine at port 5000.
