### ISSUE TITLE
Can't access Bing ("Attempt to decode JSON with unexpected mimetype")

### ISSUE THREAD

**Issue by Yaroslav-Knol** [xtekky/gpt4free#1161]
**Bug description**
Can't access Bing.
Full view of the code and error in the screenshot.

**Screenshots**
![2023-10-26_10-04-17](https://github.com/xtekky/gpt4free/assets/126708559/de0d3f81-4173-4e54-a953-37937bdc06c7)

**Environment**
- Python 3.11.0
- Russia

**Comment by Luneye** [comment]
hello, would you mind going into the Bing provider file and printing the response variable, at line 158?

**Comment by Yaroslav-Knol** [comment]
> hello, would you mind going into the Bing provider file and printing the response variable, at line 158?

```python
157    async with session.post(url, json=json, proxy=proxy) as response:
158        response = await response.json()
159        return response["result"]["value"] == "Success"
```

**Comment by Luneye** [comment]
i meant, just add a print(response) between line 157 and line 158, and tell me what is displayed after running the code

**Comment by Yaroslav-Knol** [comment]
Added two lines at the beginning:

```
Added two lines at the beginning: <ClientResponse(https://sydney.bing.com/sydney/DeleteSingleConversation) [200 OK]>
<CIMultiDictProxy('X-MSEdge-Ref': 'Ref A: E2F2821519D2492DA9F2981333D73EB3 Ref B: HEL01EDGE1614 Ref C: 2023-10-27T11:55:14Z', 'Date': 'Fri, 27 Oct 2023 11:5 5:13 GMT ', 'Connection': 'close')>
``` 

**The problem was solved using VPN.**

**Comment by Luneye** [comment]
Was almost sure that was the issue :)! Nice that you solved it!
