### ISSUE TITLE
ERR_EMPTY_RESPONSE with docker

### ISSUE THREAD

**Issue by giagara** [xtekky/gpt4free#1164]
Just installed via Docker following the commands in readme.
Gui is working on port 8080.
Api is not working on port 1337.
Even changing the port is not working: api:8080 and gui:8081 -> api not working | gui is working
The error i get on chrome is ERR_EMPTY_RESPONSE

**Environment**
- Docker

**Comment by AiPilotDev** [comment]
I have the same error

**Comment by feresberbeche** [comment]
me too
