### ISSUE TITLE
problem with gui on docker

### ISSUE THREAD

**Issue by Skiptik** [xtekky/gpt4free#1165]
**Bug description**
I can't get to the interface page with the chat, I use the joker, I have assembled the environment, I launch it, I get a warning in the console and nothing appears on the page, I attached screenshots

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/49202184/d26ff93e-6848-499c-867e-d2eec28e58fb)
![image](https://github.com/xtekky/gpt4free/assets/49202184/3ecf2bc8-4a99-403f-805e-5b790c82b48f)

**Comment by giagara** [comment]
the gui is exposed on port 8080. Please navigate to htto://localhost:8080
That's the api url, and i got the same error.

**Comment by luiso198** [comment]
I have the same problem I can't use the api: http://localhost:1337/v1

**Comment by luiso198** [comment]
Can someone help us?

**Comment by Frehyyy** [comment]
> Can someone help us?

+. I have that problem too. Do u resolve it?
