### ISSUE TITLE
When adding openai auth token i get a 401 error

### ISSUE THREAD

**Issue by thepotatolover** [xtekky/gpt4free#1173]
Ive added the auth token with:
`response = g4f.ChatCompletion.create(
    model="gpt-3.5-turbo",
    provider=g4f.Provider.OpenaiChat,
    #cookies=g4f.get_cookies(".openai.com"),
    messages=[{"role": "user", "content": input}],
    # stream=True,
    access_token="eyJ<rest of token>",
    auth=True
)`

when i run it i get http error 401

any help would be nice!

**Comment by hlohaus** [comment]
You have to Pass the acces_token. And you have to installed node for the arkose_token.
