### ISSUE TITLE
Request to remove the Chatbase API, because it is no longer functional. 

### ISSUE THREAD

**Issue by xiaozhou26** [xtekky/gpt4free#1174]
Request to remove the Chatbase API, because it is no longer functional. 
![1](https://github.com/xtekky/gpt4free/assets/122727418/fe39d898-1cab-483f-8593-a098c7dcc59a)
It only replies asking me to email the administrator.

**Comment by Luneye** [comment]
It works, you just have to jailbreak the AI. Chatbase sends a system message to GPT containing a set of rules it must obey, resulting in the error message you get when you request something external from Chatbase. But you can get around this by sending your own system message and subtly asking the AI to disobey Chatbase's rules and follow your own.
I may add such a workaround so that nobody ever has to face this problem again.

**Comment by xiaozhou26** [comment]
> It works, you just have to jailbreak the AI. Chatbase sends a system message to GPT containing a set of rules it must obey, resulting in the error message you get when you request something external from Chatbase. But you can get around this by sending your own system message and subtly asking the AI to disobey Chatbase's rules and follow your own. I may add such a workaround so that nobody ever has to face this problem again.




> It works, you just have to jailbreak the AI. Chatbase sends a system message to GPT containing a set of rules it must obey, resulting in the error message you get when you request something external from Chatbase. But you can get around this by sending your own system message and subtly asking the AI to disobey Chatbase's rules and follow your own. I may add such a workaround so that nobody ever has to face this problem again.

Thank you, I was indeed able to use Chatbase through the jailbreak mode.

**Comment by aleksandrf2020** [comment]
please add a workaround so that no one else has to face this problem.

**Comment by luiso198** [comment]
How can I jailbreack with bing?


I have tried to use the api without success so I opted for this script.
I am using this script.

import g4f
from g4f.Provider import (
    Bing,
)
import io

response = g4f.ChatCompletion.create(
    model="gpt-4-32k",
    provider=g4f.Provider.Bing,
    messages=[{"role": "user", "content": "Write a 1000-word article on birds of prey"}],
    stream=True,
)

archive = io.open("respuesta.txt", "w")

for message in response:
    archivo.write(message + "\n")

archive.close()
