### ISSUE TITLE
OpenaiChat model have another error "Our systems have detected unusual activity from your system. Please try again later."

### ISSUE THREAD

**Issue by hdsz25** [xtekky/gpt4free#1179]
After update with the latest new version, I got the follow error(I can use web browser to access chat gpt):
"Our systems have detected unusual activity from your system. Please try again later."
![image](https://github.com/xtekky/gpt4free/assets/37258899/9cb78d27-8162-48eb-83ba-4a338cefde08)

**Comment by hlohaus** [comment]
The new arkose token is maybe the Problem. Can you print / debug the request Data?

**Comment by hdsz25** [comment]
![image](https://github.com/xtekky/gpt4free/assets/37258899/0483d6d7-60a3-47b7-96b6-d43a787853a8)

**Comment by hdsz25** [comment]
![image](https://github.com/xtekky/gpt4free/assets/37258899/5bb1840c-cfd2-4a6a-b75c-39dab3615b33)

**Comment by hdsz25** [comment]
> The new arkose token is maybe the Problem. Can you print / debug the request Data?

you are right! problem fixed by manually download and extract npm to the package folder "g4f/Provider/npm". The problem is because of the missing "npm" folder through pip install!

**Comment by hlohaus** [comment]
Thats good. Oh why are npm dir is missing
