### ISSUE TITLE
Welcome gpt4free authors to enter TG group for communication.

### ISSUE THREAD

**Issue by CaoYunzhou** [xtekky/gpt4free#1183]
**Known Issues**
We are some defenders of the reverse of your project, and hope that the author of this project can enter the telegram group to communicate.

The following are the websites we maintain:
- https://chat-shared2.zhile.io/shared.html?v=2
- https://chat.geekgpt.org/
- https://chat.aivvm.com

Contact information:
- https://t.me/ja_netfilter_group

**Comment by su-fen** [comment]
That's good!

**Comment by SuiYunsy** [comment]
vv bro!

**Comment by CaoYunzhou** [comment]
https://github.com/zhile-io/pandora

by @zhile-io

**Comment by hlohaus** [comment]
How do you do create the arkose_token?
