### ISSUE TITLE
ERROR: Failed building wheel for tiktoken, aiohttp

### ISSUE THREAD

**Issue by nitsik** [xtekky/gpt4free#1187]
```
(venv) # pip --version
pip 23.2.1 from /gpt4free/gpt4free/venv/lib/python3.12/site-packages/pip (python 3.12)
(venv) # python --version
Python 3.12.0
```

```
ERROR: Failed building wheel for tiktoken
Failed to build aiohttp tiktoken
ERROR: Could not build wheels for aiohttp, tiktoken, which is required to install pyproject.toml-based projects
```

When try 

`(venv) # pip install -r requirements.txt`

Why? I use debian.

**Comment by nitsik** [comment]
I change aiohttp to aiohttp==3.9.0b0, but problem with tiktoken stay

**Comment by nitsik** [comment]
`deactivete`
venv, then
```
rm -rf venv
apt-get -y install curl build-essential gcc make && curl https://sh.rustup.rs -sSf | sh -s -- -y
env PATH="/root/.cargo/bin:${PATH}"
```
then
```
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```
solve tiktoken problem - https://github.com/openai/tiktoken/issues/205#issuecomment-1783955751

**Comment by grandpa1946** [comment]
have you found a solution?

**Comment by nitsik** [comment]
> have you found a solution?

Yes, I wrote the solution in previous posts

**Comment by junoriosity** [comment]
@nitsik Have you made some progress here, I am experiencing the same problem.

**Comment by cipri-tom** [comment]
@nitsik  installing rust just for this package is more like a workaround than a solution. I am waiting for https://github.com/openai/tiktoken/pull/200 so that there are wheels published
