### ISSUE TITLE
Proposal: Convert apps to Typescript

### ISSUE THREAD

**Issue by vanbasten17** [xtekky/gpt4free#119]
Are you considering migrating these python apps to be used with Typescript, or create a fork project?

**Comment by wingeva1986** [comment]
> Are you considering migrating these python apps to be used with Typescript, or create a fork project?

u can use http request to call Python service in your ts project

**Comment by vanbasten17** [comment]
I think it could be handy to have these services too in a JS environment, as it's closer for working with web services
