### ISSUE TITLE
AttributeError: module 'attr' has no attribute 's'

### ISSUE THREAD

**Issue by Timop4iK** [xtekky/gpt4free#1190]
**Bug description**
I just updated g4f and got this error.

**Screenshots**
![Screenshot_48](https://github.com/xtekky/gpt4free/assets/112824210/e25ad06f-8f30-4a11-8423-0c5d1143b07e)

**Environment**
- Python 3.11 pip venv
- Russia

**Additional context**
I tried to update g4f, aiohttp, and attr. I still getting this error

**Comment by zhongzhixinLvoe** [comment]
May I ask how to solve this problem? I am currently using version 3.6.8 of Python, and this error has also occurred

**Comment by zhongzhixinLvoe** [comment]
I just solved the problem. First, execute pip3 uninstall attr and then pip3 install attrs
