### ISSUE TITLE
OpenaiChat:\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport     raise NotImplementedError

### ISSUE THREAD

**Issue by hdsz25** [xtekky/gpt4free#1206]
![image](https://github.com/xtekky/gpt4free/assets/37258899/c14b81f6-a429-4cb9-9029-4fab53d0e812)
this problem happens today after I update to the latest version!

**Comment by hdsz25** [comment]
@hlohaus after I implement your change now I got the below error:

\g4f\Provider\needs_auth\OpenaiChat.py", line 75, in create_async_generator
    raise RuntimeError(line["error"])
RuntimeError: Our systems have detected unusual activity from your system. Please try again later.

**Comment by hlohaus** [comment]
Did have node installed?

**Comment by hdsz25** [comment]
Node is

> Did you have node installed?

node is installed. I debugged and actually the extra token is generated through the execution of the js file.

**Comment by hdsz25** [comment]
it works 3 days ago

**Comment by hdsz25** [comment]
by the way I use proxy to connect to openai

**Comment by hdsz25** [comment]
> unsuseal Activity means the Missing akorse_token? Did you have the arkose_token from the node_script?
Yes, the akorse_token is created!

![image](https://github.com/xtekky/gpt4free/assets/37258899/488d47e7-634f-44cc-b191-8d5093bdcb08)
