### ISSUE TITLE
rise exception ora config

### ISSUE THREAD

**Issue by lu5her-s** [xtekky/gpt4free#121]
it show 
raise Exception('''set ora.user_id and ora.session_token\napi response: %s''' % response['error'])
Exception: set ora.user_id and ora.session_token
api response: {'title': 'Missing required header', 'message': 'Oops, `x-signed-token` is missing from header'}

I add user_id and token it get from network tab

**Comment by xtekky** [comment]
will fix

**Comment by xtekky** [comment]
look at #125

**Comment by lu5her-s** [comment]
Oh, thank for reply
