### ISSUE TITLE
How use API ?

### ISSUE THREAD

**Issue by wilkensgomes** [xtekky/gpt4free#1214]
![image](https://github.com/xtekky/gpt4free/assets/38788876/2c9275c9-e9e8-4e84-a545-b31db8a455c6)
![image](https://github.com/xtekky/gpt4free/assets/38788876/6acf47a7-458c-4120-b694-69f39d8cea25)
How do I access the API? I can access the Gui but not the API. Can anyone help please!

**Comment by piyushpranjal03** [comment]
Use their package bro.
Use any IDE of your choice e.g PyCharm

install their g4f package and flask:
```
pip install g4f
pip install Flask
```

Create a .py file in ide and run it.
```
import g4f
from flask_cors import CORS
from flask import Flask, request, jsonify

app = Flask(__name__)
app.config['JSON_AS_ASCII'] = False
CORS(app, resources={r"/*": {"origins": "*"}})
g4f.logging = True


@app.route('/', methods=['POST'])
def spin_content():
    data = request.json
    content = data.get("content")
    response = g4f.ChatCompletion.create(
        model=g4f.models.default,
        provider=None,
        messages=[{"role": "user", "content": content}]
    )

    return jsonify({"response": response}) if response else jsonify({"error": "No data received"})


if __name__ == '__main__':
    app.run(debug=True, host='localhost', port=8085)

```

now you can send your post request to `localhost:8085` with a json body `{"content": "Question you want to ask"}`

**Comment by luiso198** [comment]
@piyushpranjal03 

I have tried the script you have provided and I get this error even though I have defined the provider, do you know why?

----------------------------

import g4f
from flask_cors import CORS
from flask import Flask, request, jsonify
from g4f.Provider import (
    Bard,
    Bing,
)

app = Flask(__name__)
app.config['JSON_AS_ASCII'] = False
CORS(app, resources={r"/*": {"origins": "*"}})
g4f.logging = True


@app.route('/', methods=['POST'])
def spin_content():
    data = request.json
    content = data.get("content")
    response = g4f.chat.completions.create(
        model=gpt-4,
        provider=g4f.Provider.Bing,
        messages=[{"role": "user", "content": content}]
    )

    return jsonify({"response": response}) if response else jsonify({"error": "No data received"})


if __name__ == '__main__':
    app.run(debug=True, host='localhost', port=8085)
--------------------------------------------

ERROR: ------------------------------------------

openai.NotFoundError: <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
(venv) wilson@wilson-virtual-machine:~/demo2$ python 1.py
Traceback (most recent call last):
  File "/home/wilson/demo2/1.py", line 9, in <module>
    response = openai.chat.completions.create(
  File "/home/wilson/demo2/venv/lib/python3.10/site-packages/openai/_utils/_utils.py", line 301, in wrapper
    return func(*args, **kwargs)
  File "/home/wilson/demo2/venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
  File "/home/wilson/demo2/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1063, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/wilson/demo2/venv/lib/python3.10/site-packages/openai/_base_client.py", line 842, in request
    return self._request(
  File "/home/wilson/demo2/venv/lib/python3.10/site-packages/openai/_base_client.py", line 885, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
