### ISSUE TITLE
ModuleNotFoundError: No module named 'flask' in Docker Compose

### ISSUE THREAD

**Issue by seth100** [xtekky/gpt4free#1216]
**Bug description**

Following [these steps](https://github.com/xtekky/gpt4free#setting-up-with-docker) to use it via Docker Compose, has always worked, but today, after pulling latest changes from repo, I got:

```sh
gpt4free-api  | Traceback (most recent call last):
gpt4free-api  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
gpt4free-api  |     return _run_code(code, main_globals, None,
gpt4free-api  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
gpt4free-api  |     exec(code, run_globals)
gpt4free-api  |   File "/app/g4f/cli.py", line 8, in <module>
gpt4free-api  |     from g4f.gui.run import gui_parser, run_gui_args
gpt4free-api  |   File "/app/g4f/gui/__init__.py", line 1, in <module>
gpt4free-api  |     from .server.app     import app
gpt4free-api  |   File "/app/g4f/gui/server/app.py", line 1, in <module>
gpt4free-api  |     from flask import Flask
gpt4free-api  | ModuleNotFoundError: No module named 'flask'

gpt4free-gui  | Traceback (most recent call last):
gpt4free-gui  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
gpt4free-gui  |     return _run_code(code, main_globals, None,
gpt4free-gui  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
gpt4free-gui  |     exec(code, run_globals)
gpt4free-gui  |   File "/app/g4f/cli.py", line 8, in <module>
gpt4free-gui  |     from g4f.gui.run import gui_parser, run_gui_args
gpt4free-gui  |   File "/app/g4f/gui/__init__.py", line 1, in <module>
gpt4free-gui  |     from .server.app     import app
gpt4free-gui  |   File "/app/g4f/gui/server/app.py", line 1, in <module>
gpt4free-gui  |     from flask import Flask
gpt4free-gui  | ModuleNotFoundError: No module named 'flask'
```

**Environment**
- Docker v24.0.7
- Docker Compose v2.21.0
- Ubuntu 22.04

**Comment by Arifsha40** [comment]
✔ Container gpt4free-gpt4free-gui-1  Created                                                                      0.0s
 ✔ Container gpt4free-gpt4free-api-1  Created                                                                      0.0s
Attaching to gpt4free-gpt4free-api-1, gpt4free-gpt4free-gui-1
gpt4free-gpt4free-api-1  | Traceback (most recent call last):
gpt4free-gpt4free-api-1  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
gpt4free-gpt4free-api-1  |     return _run_code(code, main_globals, None,
gpt4free-gpt4free-api-1  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
gpt4free-gpt4free-api-1  |     exec(code, run_globals)
gpt4free-gpt4free-api-1  |   File "/app/g4f/cli.py", line 8, in <module>
gpt4free-gpt4free-api-1  |     from g4f.gui.run import gui_parser, run_gui_args
gpt4free-gpt4free-api-1  |   File "/app/g4f/gui/__init__.py", line 1, in <module>
gpt4free-gpt4free-api-1  |     from .server.app     import app
gpt4free-gpt4free-api-1  |   File "/app/g4f/gui/server/app.py", line 1, in <module>
gpt4free-gpt4free-api-1  |     from flask import Flask
gpt4free-gpt4free-api-1  | ModuleNotFoundError: No module named 'flask'
gpt4free-gpt4free-gui-1  | Traceback (most recent call last):
gpt4free-gpt4free-gui-1  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
gpt4free-gpt4free-gui-1  |     return _run_code(code, main_globals, None,
gpt4free-gpt4free-gui-1  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
gpt4free-gpt4free-gui-1  |     exec(code, run_globals)
gpt4free-gpt4free-gui-1  |   File "/app/g4f/cli.py", line 8, in <module>
gpt4free-gpt4free-gui-1  |     from g4f.gui.run import gui_parser, run_gui_args
gpt4free-gpt4free-gui-1  |   File "/app/g4f/gui/__init__.py", line 1, in <module>
gpt4free-gpt4free-gui-1  |     from .server.app     import app
gpt4free-gpt4free-gui-1  |   File "/app/g4f/gui/server/app.py", line 1, in <module>
gpt4free-gpt4free-gui-1  |     from flask import Flask
gpt4free-gpt4free-gui-1  | ModuleNotFoundError: No module named 'flask'
gpt4free-gpt4free-api-1 exited with code 1
gpt4free-gpt4free-gui-1 exited with code 1

yeah having same issues

**Comment by xtekky** [comment]
this got fixed
