### ISSUE TITLE
Can support gpt-3.5-turbo-instruct

### ISSUE THREAD

**Issue by ayoubelmhamdi** [xtekky/gpt4free#1217]
https://github.com/xtekky/gpt4free/blob/fc2894a07ffaa50dbdc3e26bb52c49f7cf40d14a/g4f/models.py#L294

Can support [gpt-3.5-turbo-instruct](https://platform.openai.com/docs/api-reference/completions/create), I believe it is powerful for non-chat purposes, with various NLP tasks like summarizing or paraphrasing. Extracting, editing...

```md
/v1/completions (Legacy) | gpt-3.5-turbo-instruct, babbage-002, davinci-002
```

**Comment by ayoubelmhamdi** [comment]
i think it useful

**Comment by AngelFireLA** [comment]
good idea

**Comment by davidmartinrius** [comment]
> https://github.com/xtekky/gpt4free/blob/fc2894a07ffaa50dbdc3e26bb52c49f7cf40d14a/g4f/models.py#L294
> 
> Can support [gpt-3.5-turbo-instruct](https://platform.openai.com/docs/api-reference/completions/create), I believe it is powerful for non-chat purposes, with various NLP tasks like summarizing or paraphrasing. Extracting, editing...
> 
> ```
> /v1/completions (Legacy) | gpt-3.5-turbo-instruct, babbage-002, davinci-002
> ```

Absolutely, It could be great. Do you have any idea where to start?
