### ISSUE TITLE
Is gpt-4-1106-preview(GPT-4 Turbo) on the pipeline for the next release?

### ISSUE THREAD

**Issue by hernandosalas** [xtekky/gpt4free#1222]
https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by xtekky** [comment]
still have to find a site/provider which provides this model, but I dont thin this will be easy/soon.

**Comment by zukixa** [comment]
there's a provider (fakegpt) inside the gpt4free library already that can technically provide it, requires however some arkose_token shenanigans that I absolutely am not skilled enough to bypass lol @xtekky
