### ISSUE TITLE
Choosing a provider

### ISSUE THREAD

**Issue by toxa1818** [xtekky/gpt4free#1226]
Greetings!
I'm trying to use a library to get a short description of the text of a news story that I get after scraping a news site. I use this short description for publication in the telegram channel. I'm using the following function:

```py
import g4f

g4f.debug.logging = True


def get_summary(article, max_length=900, max_attempts=10):
    ignored_providers = [g4f.Provider.FreeGpt.__name__, g4f.Provider.FakeGpt.__name__, g4f.Provider.AiAsk.__name__, 
                                      g4f.Provider.GptChatly.__name__, g4f.Provider.Phind.__name__, g4f.Provider.NoowAi.__name__, 
                                      g4f.Provider.GptForLove.__name__, g4f.Provider.Aichat.__name__] 
    attempt = 0
    while attempt <= max_attempts:
        try:
            response = g4f.ChatCompletion.create(
                model="gpt-3.5-turbo-16k", 
                messages=[{"role": "user", "content": f"{article}\n Summarize this article in Ukrainian language. Sammary must meet the 
                                      following criteria:\n - Structure sammary as social media post, use emojies and make a list if needed.\n - The 
                                      max length of the summary must be no more than {max_length} characters and do not include links in the 
                                      summary."}], 
                ignored=ignored_providers
            )
            if len(response) <= max_length:
                return response
            else:
                raise ValueError(f"Summary length {len(response)} exceeds maximum length {max_length}.")
        except Exception as e:
            print(f"Error with provider: {e}")
            attempt += 1

    raise ValueError("Failed to generate summary after maximum attempts.")
```

When I run the use of this function in a loop for several news stories, the console shows the use of only two providers: You and GeekGpt. However, there are many more providers in total. And at each iteration, RetryProvider is used. Maybe this is the reason?

Can you also explain how to use cookies correctly in my case? So that I can use more providers...

**Comment by Timop4iK** [comment]
Most providers just don't work. For example, only FakeGPT, GeekGPT, and Phind work for me. What's the problem with using them?

**Comment by toxa1818** [comment]
> Most providers just don't work. For example, only FakeGPT, GeekGPT, and Phind work for me. What's the problem with using them?

With these providers I get the following errors:
GeekGpt: HTTPError: 403 Client Error: Forbidden for url: https://ai.fakeopen.com/v1/chat/completio
Phind: RuntimeError: HTTP Error 403:

**Comment by thanhtoan1196** [comment]
any updates?
