### ISSUE TITLE
Doesn't respond the same

### ISSUE THREAD

**Issue by huachuman** [xtekky/gpt4free#1228]
This doesn't respond the same as the originals. E.g. it constantly tells me it can't do things like code a GUI, yet when asking the providers directly there is no issue. It constantly responds like "sorry, I can't help with that" even trying different jailbreaks.

I'm mainly using Bing, and I can do countless things using Bing chat's official interface, but it fails miserably through g4f to the point of being practically unusable...

am I doing something wrong or is this an inherent limitation of the reversed API or of the gf package or UI?

Also it seems unable to use previous messages as context. Is that just another limitation of the package/UI?

**Comment by nikita-sedletskiy** [comment]
Following

**Comment by swordliongit** [comment]
Bump
