### ISSUE TITLE
phind.com | how to set cf_clearance and user_agent

### ISSUE THREAD

**Issue by zjrwtx** [xtekky/gpt4free#123]
![image](https://user-images.githubusercontent.com/86822589/234267213-519a099a-0211-4c1d-bcbd-e39ba044d3d9.png)

**Comment by Z3R0F0** [comment]
same

**Comment by coding-bug-git** [comment]
same,  found cf_clearance token still not work

**Comment by joshyorko** [comment]
same

**Comment by ozkanuysal** [comment]
> did u guys set the correct user_agent from your browser ?

Yeah, actually i set my agent from whatismybrowser.com

**Comment by AndroidTest10** [comment]
@zjrwtx we need to set user_agent only in the file streamlit_app.py ?

and is there a need to set any value in cf_clearance in the same file?

**Comment by giottobright** [comment]
> > did u guys set the correct user_agent from your browser ?
> 
> Yeah, actually i set my agent from whatismybrowser.com

hey, and where exactly you add agent in the code?

**Comment by giottobright** [comment]
and which cf_clearance token to use?

**Comment by shubhamwagh** [comment]
I too get the same error:
Following are my settings:
```@python
phind.user_agent = <set using https://whatmyuseragent.com>
phind.cf_clearance = ''
```

**Comment by localuser-isback** [comment]
Are you running the program on localhost or a server?

**Comment by localuser-isback** [comment]
> same issue, running on localhost

Are you getting the clearance token from the API page? aka the page that the GPT is located

**Comment by localuser-isback** [comment]
Main things are: make sure your using the CORRECT useragent, 2 make sure your getting the clearance token FROM THE API SITE aka if its from phind go to the phind API and get the clearance  and lastly IF ITS ON A REMOTE SERVER like a vps the clearance WILL NOT WORK because the IP has to match, make sure to use a proxy server hosted on that VPS then get the clerance with that proxy

**Comment by Z3R0F0** [comment]
> Main things are: make sure your using the CORRECT useragent, 2 make sure your getting the clearance token FROM THE API SITE aka if its from phind go to the phind API and get the clearance and lastly IF ITS ON A REMOTE SERVER like a vps the clearance WILL NOT WORK because the IP has to match, make sure to use a proxy server hosted on that VPS then get the clerance with that proxy

so, i got my useragent from whatismybrowser, and got cf_clearance from phind.com (cookies). Still same error. Am I wrong somewhere ?

**Comment by localuser-isback** [comment]
> Bare with me please, i got my useragent and put it in phind.user_agent '" and im on phind.com, how am i supposed to get my clearence token to fill in the phind.cf_clearence = i suppose ?

You get it using the chrome dev tools and going to cookies
![image](https://user-images.githubusercontent.com/121312523/234301086-ca067bc7-5df8-49f0-95c2-6879d4a83a53.png)

**Comment by maxolie00** [comment]
> > Bare with me please, i got my useragent and put it in phind.user_agent '" and im on phind.com, how am i supposed to get my clearence token to fill in the phind.cf_clearence = i suppose ?
> 
> You get it using the chrome dev tools and going to cookies ![image](https://user-images.githubusercontent.com/121312523/234301086-ca067bc7-5df8-49f0-95c2-6879d4a83a53.png)

Thank you for showing me this, I got my cf_clearance and i got the user id from whatmyuseragent.com and filled them in the right places in the streamlit_app.py 
running it again i get this new error : An error occured, please make sure you are using a cf_clearance token and correct useragent | 'rawBingResults'

**Comment by localuser-isback** [comment]
> > > Bare with me please, i got my useragent and put it in phind.user_agent '" and im on phind.com, how am i supposed to get my clearence token to fill in the phind.cf_clearence = i suppose ?
> > 
> > 
> > You get it using the chrome dev tools and going to cookies ![image](https://user-images.githubusercontent.com/121312523/234301086-ca067bc7-5df8-49f0-95c2-6879d4a83a53.png)
> 
> Thank you for showing me this, I got my cf_clearance and i got the user id from whatmyuseragent.com and filled them in the right places in the streamlit_app.py running it again i get this new error : An error occured, please make sure you are using a cf_clearance token and correct useragent | 'rawBingResults'

Get your useragent from here https://www.whatismybrowser.com/detect/what-is-my-user-agent/

**Comment by shubhamwagh** [comment]
@maxolie00 , I got it working jut after couple of refreshes

**Comment by maxolie00** [comment]
> @maxolie00 , I got it working jut after couple of refreshes Thanks @localuser-isback for your help :)

Same, now working after refreshes to, thanks all

**Comment by pheonis2** [comment]
> > Bare with me please, i got my useragent and put it in phind.user_agent '" and im on phind.com, how am i supposed to get my clearence token to fill in the phind.cf_clearence = i suppose ?
> 
> You get it using the chrome dev tools and going to cookies ![image](https://user-images.githubusercontent.com/121312523/234301086-ca067bc7-5df8-49f0-95c2-6879d4a83a53.png)

Thanks, I managed to get this running. My question is, do i need to get the cf_clearance token everytime i start the streamlit app?

**Comment by ODomWang** [comment]
now this  error 
curl_cffi.requests.cookies.Response object at 0x7f22c3588b80

**Comment by Ilan1274** [comment]
Why is there only “https://www.phind.com/” in my cookies ，and I don't see the cf_clearance
![image](https://user-images.githubusercontent.com/130030193/234566641-215e2f60-8ef2-4b73-9703-d8ee5d3cd2b8.png)

**Comment by localuser-isback** [comment]
> > > Bare with me please, i got my useragent and put it in phind.user_agent '" and im on phind.com, how am i supposed to get my clearence token to fill in the phind.cf_clearence = i suppose ?
> > 
> > 
> > You get it using the chrome dev tools and going to cookies ![image](https://user-images.githubusercontent.com/121312523/234301086-ca067bc7-5df8-49f0-95c2-6879d4a83a53.png)
> 
> Thanks, I managed to get this running. My question is, do i need to get the cf_clearance token everytime i start the streamlit app?

The app uses something called "cloudflare" it protects it from things like bots so you need to manually get it

**Comment by localuser-isback** [comment]
> Why is there only “[https://www.phind.com/”](https://www.phind.com/%E2%80%9D) in my cookies ，and I don't see the cf_clearance ![image](https://user-images.githubusercontent.com/130030193/234566641-215e2f60-8ef2-4b73-9703-d8ee5d3cd2b8.png)

These places sometimes turn cloudflare on and off so its not always going to be there

**Comment by Ilan1274** [comment]
can i use the chai.openai.com cf_clearance? I can see two cf_clearance from the cookies
![image](https://user-images.githubusercontent.com/130030193/234570580-870a6e35-bb0e-4cfd-b1e5-1c97d560bc19.png)

**Comment by Ilan1274** [comment]
maybe the project need a clearer tutorial /(ㄒoㄒ)/~~

**Comment by AbdelrhmanNile** [comment]
i examined the response, it returns an html page, looks like its not passing the cloudflare captcha

**Comment by suckurmom** [comment]
Im also getting the same error, "An error occured, please make sure you are using a cf_clearance token and correct useragent | Expecting value: line 1 column 1 (char 0)"

I've made sure my useragent and cf_clearance are both filled in correctly as well

**Comment by BastienYTB** [comment]
![image](https://user-images.githubusercontent.com/71925197/234708193-eede531f-da38-4126-bc05-4d0b8c458423.png)

;-;

**Comment by jarvisar** [comment]
My solution was to set `phind.cf_clearance` and `phind.user_agent` in streamlit_app.py

**Comment by richen666** [comment]
@jarvisar 
Thank you, and you're right. But after trying several times, the similar errors still occur and you must gain cf_clearance and copy it.
It doesn't seem very convenient.

**Comment by arianyambao** [comment]
> @jarvisar Thank you, and you're right. But after trying several times, the similar errors still occur and you must gain cf_clearance and copy it. It doesn't seem very convenient.

Yes, the clearance, similar to cookies expires and gets renewed...

**Comment by arianyambao** [comment]
@AbdelrhmanNile have you tried pasting a new cf_clearance? It might be because the one you use expired... Expires after some time

**Comment by tikserziku** [comment]
The local version works, but slower than the real chatgpt

**Comment by EricDylan47** [comment]
> 编辑：这只是使其工作的创可贴解决方案。另外，请记住，过期，您需要刷新页面才能获得新页面。在这里：第 1 步：转到 [phind.com](https://www.phind.com/) 并通过检查元素获取您的cf_clearance ->应用程序 ->存储 -> cookie（请参阅上面其他人的图像）-- **它们过期**。第 [2](https://whatmyuseragent.com/) 步：在这里获取您的 第 3 步：编辑您的 phind 文件夹（基本上复制此文件夹并继续执行。我已经删除了一些行，您可以稍后将它们与原始代码进行比较。`cf_clearance``user-agent``__init__.py`
> 
> * 手动粘贴您的行：、 和`cf_clearance``79``139``203`
> * 手动粘贴您的行：、 和`user-agent``88``146``212`
> 
> ```
> from urllib.parse import quote
> from time         import time
> from datetime     import datetime
> from queue        import Queue, Empty
> from threading    import Thread
> from re           import findall
> 
> from curl_cffi.requests import post
> 
> cf_clearance = '' # No need to put anything here (gets wiped)
> user_agent   = '' # No need to put anything here (gets wiped)
> 
> class PhindResponse:
>     
>     class Completion:
>         
>         class Choices:
>             def __init__(self, choice: dict) -> None:
>                 self.text           = choice['text']
>                 self.content        = self.text.encode()
>                 self.index          = choice['index']
>                 self.logprobs       = choice['logprobs']
>                 self.finish_reason  = choice['finish_reason']
>                 
>             def __repr__(self) -> str:
>                 return f'''<__main__.APIResponse.Completion.Choices(\n    text           = {self.text.encode()},\n    index          = {self.index},\n    logprobs       = {self.logprobs},\n    finish_reason  = {self.finish_reason})object at 0x1337>'''
> 
>         def __init__(self, choices: dict) -> None:
>             self.choices = [self.Choices(choice) for choice in choices]
> 
>     class Usage:
>         def __init__(self, usage_dict: dict) -> None:
>             self.prompt_tokens      = usage_dict['prompt_tokens']
>             self.completion_tokens  = usage_dict['completion_tokens']
>             self.total_tokens       = usage_dict['total_tokens']
> 
>         def __repr__(self):
>             return f'''<__main__.APIResponse.Usage(\n    prompt_tokens      = {self.prompt_tokens},\n    completion_tokens  = {self.completion_tokens},\n    total_tokens       = {self.total_tokens})object at 0x1337>'''
>     
>     def __init__(self, response_dict: dict) -> None:
>         
>         self.response_dict  = response_dict
>         self.id             = response_dict['id']
>         self.object         = response_dict['object']
>         self.created        = response_dict['created']
>         self.model          = response_dict['model']
>         self.completion     = self.Completion(response_dict['choices'])
>         self.usage          = self.Usage(response_dict['usage'])
> 
>     def json(self) -> dict:
>         return self.response_dict
> 
> 
> class Search:
>     def create(prompt: str, actualSearch: bool = True, language: str = 'en') -> dict: # None = no search
> 
>         if not actualSearch:
>             return {
>                 '_type': 'SearchResponse',
>                 'queryContext': {
>                     'originalQuery': prompt
>                 },
>                 'webPages': {
>                     'webSearchUrl': f'https://www.bing.com/search?q={quote(prompt)}',
>                     'totalEstimatedMatches': 0,
>                     'value': []
>                 },
>                 'rankingResponse': {
>                     'mainline': {
>                         'items': []
>                     }
>                 }
>             }
>         
>         headers = {
>             'authority': 'www.phind.com',
>             'accept': '*/*',
>             'accept-language': 'en,fr-FR;q=0.9,fr;q=0.8,es-ES;q=0.7,es;q=0.6,en-US;q=0.5,am;q=0.4,de;q=0.3',
>             'cookie': f'cf_clearance=PASTEHERE',
>             'origin': 'https://www.phind.com',
>             'referer': 'https://www.phind.com/search?q=hi&c=&source=searchbox&init=true',
>             'sec-ch-ua': '"Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"',
>             'sec-ch-ua-mobile': '?0',
>             'sec-ch-ua-platform': '"macOS"',
>             'sec-fetch-dest': 'empty',
>             'sec-fetch-mode': 'cors',
>             'sec-fetch-site': 'same-origin',
>             'user-agent': '' # PASTE HERE
>         }
>         
>         return post('https://www.phind.com/api/bing/search', headers = headers, json = { 
>             'q': prompt,
>             'userRankList': {},
>             'browserLanguage': language}).json()['rawBingResults']
> 
> 
> class Completion:
>     def create(
>         model = 'gpt-4', 
>         prompt: str = '', 
>         results: dict = None, 
>         creative: bool = False, 
>         detailed: bool = False, 
>         codeContext: str = '',
>         language: str = 'en') -> PhindResponse:
>   
>         if results is None:
>             results = Search.create(prompt, actualSearch = True)
>         
>         if len(codeContext) > 2999:
>             raise ValueError('codeContext must be less than 3000 characters')
>         
>         models = {
>             'gpt-4' : 'expert',
>             'gpt-3.5-turbo' : 'intermediate',
>             'gpt-3.5': 'intermediate',
>         }
>         
>         json_data = {
>             'question'    : prompt,
>             'bingResults' : results, #response.json()['rawBingResults'],
>             'codeContext' : codeContext,
>             'options': {
>                 'skill'   : models[model],
>                 'date'    : datetime.now().strftime("%d/%m/%Y"),
>                 'language': language,
>                 'detailed': detailed,
>                 'creative': creative
>             }
>         }
>         
>         headers = {
>             'authority': 'www.phind.com',
>             'accept': '*/*',
>             'accept-language': 'en,fr-FR;q=0.9,fr;q=0.8,es-ES;q=0.7,es;q=0.6,en-US;q=0.5,am;q=0.4,de;q=0.3',
>             'content-type': 'application/json',
>             'cookie': f'cf_clearance=PASTEHERE',
>             'origin': 'https://www.phind.com',
>             'referer': 'https://www.phind.com/search?q=hi&c=&source=searchbox&init=true',
>             'sec-ch-ua': '"Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"',
>             'sec-ch-ua-mobile': '?0',
>             'sec-ch-ua-platform': '"macOS"',
>             'sec-fetch-dest': 'empty',
>             'sec-fetch-mode': 'cors',
>             'sec-fetch-site': 'same-origin',
>             'user-agent': '' # PASTE HERE
>         }
>         
>         completion = ''
>         response   = post('https://www.phind.com/api/infer/answer', headers = headers, json = json_data, timeout=99999, impersonate='chrome110')
>         for line in response.text.split('\r\n\r\n'):
>             completion += (line.replace('data: ', ''))
>         
>         return PhindResponse({
>             'id'     : f'cmpl-1337-{int(time())}', 
>             'object' : 'text_completion', 
>             'created': int(time()), 
>             'model'  : models[model], 
>             'choices': [{
>                     'text'          : completion, 
>                     'index'         : 0, 
>                     'logprobs'      : None, 
>                     'finish_reason' : 'stop'
>             }], 
>             'usage': {
>                 'prompt_tokens'     : len(prompt), 
>                 'completion_tokens' : len(completion), 
>                 'total_tokens'      : len(prompt) + len(completion)
>             }
>         })
>         
> 
> class StreamingCompletion:
>     message_queue    = Queue()
>     stream_completed = False
>     
>     def request(model, prompt, results, creative, detailed, codeContext, language) -> None:
>         
>         models = {
>             'gpt-4' : 'expert',
>             'gpt-3.5-turbo' : 'intermediate',
>             'gpt-3.5': 'intermediate',
>         }
> 
>         json_data = {
>             'question'    : prompt,
>             'bingResults' : results,
>             'codeContext' : codeContext,
>             'options': {
>                 'skill'   : models[model],
>                 'date'    : datetime.now().strftime("%d/%m/%Y"),
>                 'language': language,
>                 'detailed': detailed,
>                 'creative': creative
>             }
>         }
> 
>         headers = {
>             'authority': 'www.phind.com',
>             'accept': '*/*',
>             'accept-language': 'en,fr-FR;q=0.9,fr;q=0.8,es-ES;q=0.7,es;q=0.6,en-US;q=0.5,am;q=0.4,de;q=0.3',
>             'content-type': 'application/json',
>             'cookie': f'cf_clearance=PASTEHERE',
>             'origin': 'https://www.phind.com',
>             'referer': 'https://www.phind.com/search?q=hi&c=&source=searchbox&init=true',
>             'sec-ch-ua': '"Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"',
>             'sec-ch-ua-mobile': '?0',
>             'sec-ch-ua-platform': '"macOS"',
>             'sec-fetch-dest': 'empty',
>             'sec-fetch-mode': 'cors',
>             'sec-fetch-site': 'same-origin',
>             'user-agent': '' # PASTE HERE
>         }
>         
>         response   = post('https://www.phind.com/api/infer/answer', 
>             headers = headers, json = json_data, timeout=99999, impersonate='chrome110', content_callback=StreamingCompletion.handle_stream_response)
> 
> 
>         StreamingCompletion.stream_completed = True
> 
>     @staticmethod
>     def create(
>         model       : str = 'gpt-4', 
>         prompt      : str = '', 
>         results     : dict = None, 
>         creative    : bool = False, 
>         detailed    : bool = False, 
>         codeContext : str = '',
>         language    : str = 'en'):
>         
>         
>         if results is None:
>             results = Search.create(prompt, actualSearch = True)
>         
>         if len(codeContext) > 2999:
>             raise ValueError('codeContext must be less than 3000 characters')
>         
>         Thread(target = StreamingCompletion.request, args = [
>             model, prompt, results, creative, detailed, codeContext, language]).start()
>         
>         while StreamingCompletion.stream_completed != True or not StreamingCompletion.message_queue.empty():
>             try:
>                 chunk = StreamingCompletion.message_queue.get(timeout=0)
> 
>                 if chunk == b'data:  \r\ndata: \r\ndata: \r\n\r\n':
>                     chunk = b'data:  \n\n\r\n\r\n'
>                 
>                 chunk = chunk.decode()
>                 
>                 chunk = chunk.replace('data: \r\n\r\ndata: ', 'data: \n')
>                 chunk = chunk.replace('\r\ndata: \r\ndata: \r\n\r\n', '\n\n\r\n\r\n')
>                 chunk = chunk.replace('data: ', '').replace('\r\n\r\n', '')
>                 
>                 yield PhindResponse({
>                     'id'     : f'cmpl-1337-{int(time())}', 
>                     'object' : 'text_completion', 
>                     'created': int(time()), 
>                     'model'  : model, 
>                     'choices': [{
>                             'text'          : chunk, 
>                             'index'         : 0, 
>                             'logprobs'      : None, 
>                             'finish_reason' : 'stop'
>                     }], 
>                     'usage': {
>                         'prompt_tokens'     : len(prompt), 
>                         'completion_tokens' : len(chunk), 
>                         'total_tokens'      : len(prompt) + len(chunk)
>                     }
>                 })
> 
>             except Empty:
>                 pass
> 
>     @staticmethod
>     def handle_stream_response(response):
>         StreamingCompletion.message_queue.put(response)
> ```
> 
> ![图像](https://user-images.githubusercontent.com/29201095/234626169-0ff36e98-5e2b-4144-a48a-4094e53d866e.png)
> 
> 附言这里的改进可能是通过 streamlit 的实现设置键，看起来由于某种原因每次调用都会擦除键`session_state`

sstillll not work

**Comment by shubhamwagh** [comment]
Check this issue #153 , phind.com is forbidden now

**Comment by suckurmom** [comment]
After updating my cookies it seems to work now, thanks

**Comment by xtekky** [comment]
#194 and #153

**Comment by liuSir2022** [comment]
This problem is so serious that the project cannot be deployed. Most of us have encountered this problem. Please come out and give a correct answer
