### ISSUE TITLE
!doctype html>\n<html lang=en>\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n '}, {'role': 'user', 'content': '1'}]

### ISSUE THREAD

**Issue by leezanla** [xtekky/gpt4free#1231]
When a run 'g4f gui', then I write a word in my localhost:80, but it appear following wrong
![image](https://github.com/xtekky/gpt4free/assets/30462256/3161bf02-d5bc-4c80-85d2-6e1916e10034)
How I fix it?

**Comment by DataReset** [comment]
same

**Comment by songyp0505** [comment]
Hey Bro，Did you resolve this problem? I got the same error.🫠

**Comment by NotFenixio** [comment]
Looks like they banned the proxy.

**Comment by LX-u0** [comment]
I'm having the same problem, how can I fix it?

**Comment by z0r2y3** [comment]
<img width="1252" alt="屏幕截图 2023-12-01 035857" src="https://github.com/xtekky/gpt4free/assets/105439032/0f343e07-ca4a-4c45-954d-30c71d9d4c96">
