### ISSUE TITLE
repl problems

### ISSUE THREAD

**Issue by qrach** [xtekky/gpt4free#124]
I was thinking of using the repl linked for a project, as I was making a browser-only tool, but the repl isn't functioning correctly. I get these two response codes in the console when running it, and the repl does not work.
`
172.31.128.1 - - [25/Apr/2023 11:45:21] "GET / HTTP/1.1" 302 -
172.31.128.1 - - [25/Apr/2023 11:45:21] "GET /chat HTTP/1.1" 308 -
`

Also, a side note: I think if you made a repl that would extract code from this repo and run a webgui with an easy-to-use API endpoint (including service and model as arguments) that this could reach wider audiences and be a helpful tool universally. Enterprise, academic, or government workplaces sometimes use web filtering to block stuff like this (ex: cisco webfilters, any random school-enforced extensions or policies on some shitty chromebook, etc.) and a reliable repl API, or at least a completely ready-to-deploy API would be an easy solution for this, as well as a good tool for external use.

**Comment by DanielShemesh** [comment]
I made the repl, it still works for me. I will try to improve it over time and add support for all the APIs in this repo
