### ISSUE TITLE
New Error for OpenaiChat

### ISSUE THREAD

**Issue by hdsz25** [xtekky/gpt4free#1242]
lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 56, in create_async_generator
    while not end_turn:
UnboundLocalError: local variable 'end_turn' referenced before assignment

**Comment by jkoestner** [comment]
yeah i got this too

**Comment by loganbaby** [comment]
the same issue when I fill access_token

**Comment by jkoestner** [comment]
not getting issue anymore - i think it can be closed

**Comment by loganbaby** [comment]
Hm, so before closing how can I fix it?

**Comment by jkoestner** [comment]
this is how i was initiating it

```
response = g4f.ChatCompletion.create(
    model=g4f.models.default,
    messages=[{"role": "user", "content": """
                      what version are you
                       """}],
    provider=OpenaiChat,
    auth=True,
    access_token=access_token
)
```
