### ISSUE TITLE
ora.sh takedown request

### ISSUE THREAD

**Issue by xtekky** [xtekky/gpt4free#125]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/98614666/234317100-5fbf806b-50d2-4c4b-aab7-9f5f7f10fc20.png">

as per request, I will be taking this api down, but do not worry, other api's will replace it and you may find another repo for ora.sh

**Comment by taiyi747** [comment]
Very agree with your approach.
 Ora has provided services for so long without charging fees. They have done their best. I hope their website can continue operating.

**Comment by hrizal** [comment]
Come on, keep spirit Samora, you are useful for many people, but I understand what happened, you are cool, keep going
