### ISSUE TITLE
GPTalk issue

### ISSUE THREAD

**Issue by loganbaby** [xtekky/gpt4free#1255]
**Bug description**
When I try to generate some through GPTalk provider, I can generate only 5 times. Then, I can see this Error in console log:

```
KeyError: 'data'
```

I can fix it by restarting my script at all. But if I set a timeout, even in 5 minutes - nothing won't work. I see this problem -> I restart script -> all work in next 5 generations. How can I fix it, or maybe @xtekky fix it in near future? (It's big trouble with this Provider, because of it is one of the most stable providers)

ex.
```
await g4f.ChatCompletion.create_async(
  model=g4f.models.gpt_35_turbo,
  messages=[{'role': 'user', 'content': 'hello world!',
  provider=g4f.Provider.GPTalk
)
```

Give this error in 5 times.

**Comment by Lin-jun-xiang** [comment]
@loganbaby
Thank you for reporting this issue!
I have created a PR for solve this problem.

**Comment by loganbaby** [comment]
Thanks, nice solution!
