### ISSUE TITLE
New website to add and reverse-engineering

### ISSUE THREAD

**Issue by EvPix** [xtekky/gpt4free#127]
There is another site with free access to GPT-3.5 and GPT-4. It's worth studying it too. And it seems like he has no restrictions on the number of requests in the chat.

https://chat.forefront.ai

And thanks for accessing GPT-3.5 and GPT-4.

**Comment by 9fo** [comment]
Forefront has already been reversed, but thanks for ur input

**Comment by xtekky** [comment]
added
