### ISSUE TITLE
docker Error: Invalid value: File does not exist: streamlit_app.py

### ISSUE THREAD

**Issue by amilcarpg** [xtekky/gpt4free#128]
congratulations great job!

The following steps were executed.

- docker build -t gpt4free:latest -f Docker/Dockerfile .

- docker run -p 8501:8501 gpt4free:latest

receive the following error message

> Usage: streamlit run [OPTIONS] TARGET [ARGS]...
> Try 'streamlit run --help' for help.
> 
> Error: Invalid value: File does not exist: streamlit_app.py

**Comment by xtekky** [comment]
its now in `/gui`

**Comment by gliptak** [comment]
#136
