### ISSUE TITLE
Provider GPTalk is down

### ISSUE THREAD

**Issue by loganbaby** [xtekky/gpt4free#1290]
Since today, Provider GPTalk is down. It was the most capable provider of all list with providers

Rest in piece, my legend 😔

Maybe, smb have more info about this service??? I wanna use it un future

**Comment by Lin-jun-xiang** [comment]
@loganbaby 

I've used `GPTalk` successfully now.

Could u show the error logs? Thanks!

**Comment by loganbaby** [comment]
How? The GPTalk is down with internal server error.

Look: 👀
https://check-host.net/check-http?host=https://gptalk.net&csrf_token=4cb5899a1dbc9d3fb06e44db4388e6fa213fb697

**Comment by loganbaby** [comment]
Hm... It's so strange! Now, with Error code 500 it works for me, but I can't to get their site.

Yesterday, for all day it was with Error code 503 (connection timeout). And it didn't work.

Magic? Why?

**Comment by loganbaby** [comment]
Its code 200 for now, closing the issue
