### ISSUE TITLE
I'm a novice, can you guys make an API call tutorial, what to call when using software, and how to use API

### ISSUE THREAD

**Issue by LX-u0** [xtekky/gpt4free#1299]

**Comment by xugliang** [comment]
我也看不懂，不会配置，希望有大神能出详细教程

**Comment by MauryaAnurag** [comment]
i dont know much i started using this repo just today , i think  u can make a code in python and then add this gpt4free code  in function and u can use flask or django and then run that api and just pass to the api the prompt in parameter or as u wish get or post request.
u can use like this below and make api, i generated the below with chatgpt


![image](https://github.com/xtekky/gpt4free/assets/78605303/c3e3c67f-17f6-447b-9bdc-bcec3f5c3751)

Should i provide u the below code??
