### ISSUE TITLE
Image on Docker Hub

### ISSUE THREAD

**Issue by aloneguid** [xtekky/gpt4free#1306]
Seems like building docker image manually or trying to set up often fails. There are plenty of "gpt4free" images on docker hub, but not sure which are working.
Would it be possible to release docker images to official docker hub from here?

**Comment by rpodgorny** [comment]
i've just tried this image: docker.io/hlohaus789/g4f:latest

it does not seem to work, at least under podman:

```
Running on port 80
 * Serving Flask app 'g4f.gui.server.app'
 * Debug mode: off
Permission denied
```

this is most probably a problem of "gui" trying to start on port 80 which is available only to root. it may work in docker but since podman also supports root-less mode, i'd recommend changing the default to something over 1024 (such as 8080?).

**Comment by rpodgorny** [comment]
also, it seems, the started "api" part only listens on 127.0.0.1 so connecting port 1337 to the outside world is useless, anyway... ...it should listen on all interfaces (0.0.0.0) just as the "web" part does...

**Comment by hlohaus** [comment]
Both issues are on the old docker images too. But may i will have a look there too

**Comment by hlohaus** [comment]
i fixed the issues

**Comment by capfzgs** [comment]
I have push image，looks like it can not  be work，i can’t send my question, do you have any idea? May I ask how to make sure it can be work?thanks 
![image](https://github.com/xtekky/gpt4free/assets/11909943/d07ff896-0213-47fa-b006-0a4dbd41e074)

**Comment by hlohaus** [comment]
You can look in the browser console for errors or:

docker-compose logs

**Comment by capfzgs** [comment]
Hi Lohaus，
thanks for your responding，first let me introduce the background.
1) system info
Centos stream 9(workstation vm),4c,12G
2）gpt 4 running for the GitHub option1（quick start）


a.Download and install Docker
Pull latest image and run the container:
docker pull hlohaus789/g4f
docker run -p 8080:8080 -p 1337:1337 -p 7900:7900 --shm-size="2g" hlohaus789/g4f:latest
b. access web，but i can not put my question.
Ｉdont used docker-composer，how to get the logs？any ideas？I will collect the logs，please help review on this issue.thanks




发自我的iPhone


------------------ Original ------------------
From: H Lohaus ***@***.***&gt;
Date: Tue,Jan 30,2024 3:52 PM
To: xtekky/gpt4free ***@***.***&gt;
Cc: capfzgs ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xtekky/gpt4free] Image on Docker Hub (Issue #1306)





 
You can look in the browser console for errors or:
 
docker-compose logs

**Comment by hlohaus** [comment]
You can see the log with:

docker-compose logs
