### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by SunYy0919** [xtekky/gpt4free#1313]
无法安装这四个包
aiohttp, browser-cookie3,typing-extensions,py-arkosegenerator

**Comment by MauryaAnurag** [comment]
where is the image??

**Comment by SunYy0919** [comment]
> 图片在哪里？？
aiohttp, browser-cookie3,typing-extensions,py-arkosegenerator
four package

**Comment by MauryaAnurag** [comment]
sorry about pictures.
can u show error or screenshots why u are facing the error in installing packages
