### ISSUE TITLE
Please provide code on  how to run gpts by adding cookies on bing or chatgpt....

### ISSUE THREAD

**Issue by MauryaAnurag** [xtekky/gpt4free#1319]
can someone please tell me , if i want to add the code on some server how can i add cookies , bcoz in server we will need to add cookies of bing, chatgpt, or any other

**Comment by radityaharya** [comment]
You can pass it like this:

```python
response = g4f.ChatCompletion.create(
  model=model,
  stream=stream,
  messages=messages,
  provider=engine.Provider.Bing,
  cookies={...cookies...}
)
```

You can also get your cookies by using the following script in the browser console:

```javascript
JSON.stringify(document.cookie.split('; ').map(c => c.split('=')).reduce((c, [k, v]) => ({ ...c, [k]: v }), {}))
```

**Comment by MauryaAnurag** [comment]
[/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py](https://localhost:8080/#) in json(self, encoding, loads, content_type)
   1163             ctype = self.headers.get(hdrs.CONTENT_TYPE, "").lower()
   1164             if not _is_expected_content_type(ctype, content_type):
-> 1165                 raise ContentTypeError(
   1166                     self.request_info,
   1167                     self.history,

ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1199.4')

**this error is coming when i add the cookie with the above method**
