### ISSUE TITLE
BARD - cutting off response message

### ISSUE THREAD

**Issue by jkoestner** [xtekky/gpt4free#1322]
**Bug description**
Trying to use Bard in outputting results. It is only providing one line from the output. I believe the provider code `script` may be too specific.

```
response = g4f.ChatCompletion.create(
    model=g4f.models.default,
    messages=[
        {
            "role": "user",
            "content":  f"what's a summary of what a teacher does",
        }
    ],
    provider=Bard,
    auth='cookie',
)

print(response)
```

The print response
---------------------
> ## The Role of a Teacher: A Summary
> 
> Teachers play a vital role in society, shaping the minds of future generations. Their responsibilities extend far beyond simply
> 

**Screenshots**
N/A

**Environment**
g4f 1.9.2

**Additional context**
N/A

**Comment by hlohaus** [comment]
@jkoestner i can't reproduce that

**Comment by iG8R** [comment]
Same here https://github.com/xtekky/gpt4free/issues/1346
