### ISSUE TITLE
顾子明私享会，原件569元，现在79元 微信 :fa234567fa

### ISSUE THREAD

**Issue by 18813055625** [xtekky/gpt4free#1323]
**Known Issues** // delete this
- you.com issue / fix: use proxy, or vpn, your country is probably flagged
- forefront account creation error / use your own session or wait for fix

**Bug description**
What did you do, what happened, which file did you try to run, in which directory
Describe what you did after downloading repo, such as moving to this repo, running this file.

ex.

**Screenshots**

**Environment**
- python version
- location ( are you in a cloudfare flagged country ) ?

**Additional context**

**Comment by catmeowjiao** [comment]
请立刻删除此issue，不要在任何开源项目的issue区打广告！

**Comment by catmeowjiao** [comment]
@xtekky please delete this issue,thanks!
