### ISSUE TITLE
when cannot use it , then how to delete it ?

### ISSUE THREAD

**Issue by circle2nd** [xtekky/gpt4free#133]
when cannot use it , then how to delete it ?

**Comment by amdjedbens** [comment]
- Navigate to project directory, you can use: `pip uninstall -r requirements.txt` to delete all the packages installed from requirements.txt file.
**N.B:** You could do more damage by uninstalling something that another program needs. Having a couple of libs installed on your system should be fine.
- Delete the folder gpt4free that you created when cloning the repo.
