### ISSUE TITLE
Phind returns an empty string

### ISSUE THREAD

**Issue by VanshShah1** [xtekky/gpt4free#1337]
**Bug description**
when I used Phind model with gpt 3.5 turbo in g4f, It returns an empty string. 

<img width="733" alt="Screenshot 2023-12-12 at 12 20 18 AM" src="https://github.com/xtekky/gpt4free/assets/75292413/c5259b87-cc35-4726-824f-99543cdc6d56">
<img width="798" alt="Screenshot 2023-12-12 at 12 20 59 AM" src="https://github.com/xtekky/gpt4free/assets/75292413/8950147d-b2b5-456f-ab6a-c3766f28b867">

**Environment**
- VS Code
- location-India

**Comment by SilverMarcs** [comment]
Were you able to get it to work?

**Comment by VanshShah1** [comment]
nope still not working
