### ISSUE TITLE
How to use providers via HTTP Request ?

### ISSUE THREAD

**Issue by alvarosoaress** [xtekky/gpt4free#1338]
I am trying to use the api version of this project, but, the providers option in my request is not working, am i doing something wrong?

```js
const response = await axios.post(
      `${API_BASE}`,
      {
        provider: 'g4f.Provider.ChatgptAi',
        temperature:0.75,
        top_p: 0.6,
        model: 'gpt-3.5-long',
        messages: [            
          {role: 'user', content: msg }
        ],
      },
      {
        headers: {
          'Content-Type': 'application/json',
        }
      }
    );
    return response.data.choices[0].message.content
```

this is the code, i already tried with `provider: 'ChatgptAi'` and others providers, but the api always ignore the option providers.

**Comment by Vanfreddy** [comment]
you mean like this? import g4f.api

g4f.debug.logging = True # enable loggin
# List of providers
ignored_providers = [
    "Koala",
    "ChatAnywhere",
    "ChatgptDemoAi",
    # ... (add other providers)
    "Berlin"
]

g4f.api.Api(engine = g4f, debug = True ,list_ignored_providers=ignored_providers).run(ip = "localhost:1337")

**Comment by Vanfreddy** [comment]
you mean like this   

```python
import g4f.api

g4f.debug.logging = True # enable loggin
# List of providers
ignored_providers = [
    "Koala",
    "ChatAnywhere",
    "ChatgptDemoAi",
    # ... (add other providers)
    "Berlin"
]

g4f.api.Api(engine = g4f, debug = True ,list_ignored_providers=ignored_providers).run(ip = "localhost:1337")
   ```
