### ISSUE TITLE
ModuleNotFoundError: No module named 'g4f.Provider.VoiGpt'

### ISSUE THREAD

**Issue by MemeticGitHubUser** [xtekky/gpt4free#1345]
**Bug description**
1. Create app.py in root folder after downloading the repo and it's dependencies
2. Run it
3. See error

I tried to run the G4F API. this error happens when running some scripts in the "testing" folder too. The app.py file I made is located in the root folder as the api guide instructed.

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/40185397/466cf6d0-f623-4c57-869f-dc4770da028f)

**Environment**
- Python 3.11.7
- United States

**Comment by hlohaus** [comment]
Please try again. The last user PR moved VoiGpt to deprecated, but don't removed it.
