### ISSUE TITLE
Bing stopped working

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1347]
**Bug description**
Yesterday, Bing still worked, but today brings up only:
```
Using Bing provider
0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1381.8')
127.0.0.1 - - [14/Dec/2023 20:22:32] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/11407417/3f562cfb-2596-4f65-ba75-4efec77d0f3e)

**Environment**
- python version: 3.12
- location ( are you in a cloudfare flagged country ) : Ukraine

**Comment by VaMPIRESqq** [comment]
me too

**Comment by VaMPIRESqq** [comment]
![Uploading Screenshot_2023-12-15-07-14-09-935_com.android.chrome.png…]()

**Comment by VaMPIRESqq** [comment]
![Screenshot_2023-12-15-07-14-09-935_com android chrome](https://github.com/xtekky/gpt4free/assets/146086035/6ead4ea4-53c8-4bbc-abf6-31205f53194c)

**Comment by eminemkun** [comment]
#1356 
#1364 
I have solved this problem.

**Comment by iG8R** [comment]
@eminemkun 
Thanks a lot!
