### ISSUE TITLE
Indicate in the chat which provider is being used

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1348]
**Describe the solution you'd like**

Is there a way to indicate(highlight) the provider that was used in response to one or another request.

For example, with an icon or inscription, or both together:

![image](https://github.com/xtekky/gpt4free/assets/11407417/b4f9f061-3690-4c65-b7e0-e8acbb427b85)

**Comment by sharoz-27** [comment]
Shows sequential search of providers until it finds a working one

```
g4f.debug.logging = True # enable logging
print(g4f.Provider.Ails.params)  # supported args
```
![image](https://github.com/xtekky/gpt4free/assets/145263538/42ffc355-c871-4725-a2eb-35cca58a110f)

**Comment by iG8R** [comment]
Thanks, but I wasn't asking about finding a working provider, but about indicating which provider gives the answer.

**Comment by iG8R** [comment]
Up.

**Comment by hlohaus** [comment]
I added it to the included gui.
Also i added this function:
```py
g4f.get_last_provider(True)
```
