### ISSUE TITLE
Issue with gpt 3.5 turbo

### ISSUE THREAD

**Issue by Lanc1um** [xtekky/gpt4free#1349]
After some time using gpt 3.5 turbo it sends me this message: "It seems you want to use our service but are not doing so from VoiGPT.com Come over to VoiGPT.com to experience a free in the web voice assistant. VoiGPT has identifed your IP address to be linked with illegal use of our service. If you are using a VPN, please change servers or turn it off to continue use."
Is there anything I can do?

**Comment by hlohaus** [comment]
I already removed it in the master. Wait for a Release.
