### ISSUE TITLE
ModuleNotFoundError: No module named 'g4f.Provider.NoowAi'

### ISSUE THREAD

**Issue by wxzex** [xtekky/gpt4free#1353]
**Bug description**
I tried running g4f with this code
import g4f
response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Liaobots,
                                    messages=[{"role": "user", "content": "test"}], stream=g4f.Provider.Liaobots.supports_stream)

for message in response:
    print(message, flush=True, end='') and it gave me that error.

ex.
1. Open the file.
2. Get the error.

**Environment**
- python version
- location ( are you in a cloudfare flagged country ) ? No, cloudflare works for me perfectly.

**Comment by modasser69** [comment]
im using python 3.11.4
and im in  the netherlands

**Comment by hurleychin** [comment]
File "/home/qinhulin/.local/bin/g4f", line 5, in <module>
    from g4f.cli import main
  File "/home/qinhulin/.local/lib/python3.11/site-packages/g4f/__init__.py", line 6, in <module>
    from .models   import Model, ModelUtils, _all_models
  File "/home/qinhulin/.local/lib/python3.11/site-packages/g4f/models.py", line 4, in <module>
    from .Provider   import BaseProvider, RetryProvider
  File "/home/qinhulin/.local/lib/python3.11/site-packages/g4f/Provider/__init__.py", line 42, in <module>
    from .NoowAi          import NoowAi
ModuleNotFoundError: No module named 'g4f.Provider.NoowAi'

**Comment by progech** [comment]
probably typo issue is breaking the package

**Comment by modasser69** [comment]
> probably typo issue is breaking the package

whats should i do then?

**Comment by nbowisdar** [comment]
The same problem.

**Comment by chekamarue** [comment]
> > probably typo issue is breaking the package
> 
> whats should i do then?

roll back to previous version

execute : pip install g4f==0.1.9.3

**Comment by fermani10** [comment]
I have the same problem and the older version gives me an error and does not return results.
