### ISSUE TITLE
ModuleNotFoundError: No module named 'g4f.Provider.NoowAi'

### ISSUE THREAD

**Issue by progech** [xtekky/gpt4free#1354]

**Comment by eminsk** [comment]
The problem was solved by removing it from the file g4f/Provider/init.py
from .NoowAi import NoowAi

**Comment by aVitomin** [comment]
For windows:
Go to %appdata%
AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider
Open __init__.py and remove `from .NoowAi import NoowAi` line

**Comment by FujiwaraChoki** [comment]
> For windows: Go to %appdata% AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider Open **init**.py and remove `from .NoowAi import NoowAi` line

And programatically?

**Comment by meteor260** [comment]
Today issue still happens by pip install.

**Comment by loganbaby** [comment]
hope fix will be in next update

**Comment by agn-7** [comment]
when the fixed version is going to be released?
still has the problem in `0.1.9.4`

**Comment by FujiwaraChoki** [comment]
> when the fixed version is going to be released? still has the problem in `0.1.9.4`

I'm pretty sure if we run this:
```
pip install git+https://github.com/xtekky/gpt4free
```
It might work, since the issue only persists in pip.

**Comment by Mr-Khans** [comment]
Uninstall g4f and next step re-install pip install g4f==0.1.9.3

**Comment by efefew** [comment]
Still don't working on latest version

**Comment by hlohaus** [comment]
In the meantime is it fixed.
