### ISSUE TITLE
Free openchat_v3.2_mistra by OpenChat Aura API

### ISSUE THREAD

**Issue by OmiiiDev** [xtekky/gpt4free#1369]
OpenChat Aura is giving us free online demo of their openchat_v3.2_mistra and it can be used to add as a new model to this repo!
online demo: https://openchat.team/

**Comment by devAdityaa** [comment]
Will take a look at it, it looks promising. Thanks for for finding it!

**Comment by OmiiiDev** [comment]
Will this be added to the models in this repo?
