### ISSUE TITLE
{ "error": { "message": "This model's maximum context length is 4097 tokens. However, your messages resulted in 4301 tokens. Please reduce the length of the messages.", "type": "invalid_request_error", "param": "messages", "code": "context_length_exceeded" } }

### ISSUE THREAD

**Issue by ChasLui** [xtekky/gpt4free#137]
{ "error": { "message": "This model's maximum context length is 4097 tokens. However, your messages resulted in 4301 tokens. Please reduce the length of the messages.", "type": "invalid_request_error", "param": "messages", "code": "context_length_exceeded" } }

**Comment by vatva691** [comment]
You copied a prompt that is too long. Please delete your messages and try something shorter.
