### ISSUE TITLE
HTML code as an answer

### ISSUE THREAD

**Issue by artemline2020** [xtekky/gpt4free#1373]
**Bug description**
I runned a code and have code as answer

That's my code

import g4f

g4f.logging = True

def ask_gpt(messages) -> str:
    response = g4f.ChatCompletion.create(
        model=g4f.models.gpt_4,
        messages=messages,
    )
    print(response)
    return response        
messages = []
while True:

    messages.append({"role": "user", "content": input("You: ")})
    messages.append({"role": "assistant", "content": ask_gpt(messages)})

It happens 1 of 3 asking

That's code I have as answer

<!DOCTYPE html>
<html coupert-item="9AF8D9A4E502F3784AD24272D81F0381"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>人机验证</title>
    <script src="assets/jquery.min.js"></script>
    <script src="assets/layer.js"></script>
    <link rel="stylesheet" href="assets/layer.css" id="layuicss-layer">
    <style>
        body {
            margin: 0;
            height: 100vh;
            width: 100vw;
            display: flex;
            align-items: center;
            justify-content: center;
            font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
            font-size: 14px;
            background-color: #1F1F1F;
        }

        .background {
            position: relative;
            background: RGBA(60,60,60, 0.6);
            border-radius: 20px;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            box-shadow: 0 5px 15px 0 rgba(0, 0, 0, 0.25);
            width: 400px;
            height: 400px;
            color: white;
        }

        .background input {
            display: none;
        }

        .background .button {
            display: flex;
            justify-content: center;
            align-items: center;
            width: 260px;
            height: 60px;
            border: 2px solid white;
            border-radius: 30px;
            text-align: center;
            font-size: 20px;
            text-transform: uppercase;
            font-weight: bold;
            letter-spacing: 2px;
            transition: all 0.3s ease-in-out;
            cursor: pointer;
        }

        .background .button:hover {
            background-color: #343541;
        }

        .background .button .fas {
            position: absolute;
            color: #4caf50;
            z-index: 2;
            opacity: 0;
        }

        .background .circle {
            position: absolute;
            width: 65px;
            height: 65px;
            fill: none;
            stroke: white;
            stroke-width: 2px;
            stroke-linecap: round;
            stroke-dasharray: 183 183;
            stroke-dashoffset: 183;
            opacity: 0;
            left: 0;
            bottom: 0;
            right: 0;
            top: 0;
            margin: auto;
            pointer-events: none;
            transform: rotate(-90deg);
        }

        .background input:checked ~ .button {
            animation: button 0.5s ease both, fill 0.5s ease-out 1.5s forwards;
        }

        .background input:checked ~ .button .fas {
            animation: check 0.5s ease-out 1.5s both;
        }

        .background input:checked ~ .circle {
            animation: circle 2s ease-out 0.5s both;
        }

        @keyframes button {
            0% {
                width: 260px;
                left: 70px;
                border-color: white;
                color: white;
            }
            50% {
                color: transparent;
            }
            100% {
                width: 60px;
                left: 170px;
                border-color: #45b078;
                background: transparent;
                color: transparent;
            }
        }

        @keyframes circle {
            0% {
                stroke-dashoffset: 183;
            }
            50% {
                stroke-dashoffset: 0;
                stroke-dasharray: 183;
                transform: rotate(-90deg) scale(1);
                opacity: 1;
            }
            90%,
            100% {
                stroke-dasharray: 500 500;
                transform: rotate(-90deg) scale(2);
                opacity: 0;
            }
        }

        @keyframes fill {
            0% {
                background: transparent;
                border-color: white;
            }
            100% {
                background: white;
            }
        }

        @keyframes check {
            0% {
                opacity: 0;
            }
            100% {
                opacity: 1;
            }
        }
    </style>
<style>
        @font-face{
            font-family: 'Aileron'; 
            font-weight: 400;
            src: url(chrome-extension://mfidniedemcgceagapgdekdbmanojomk/font/Roboto-Regular.ttf);  
        }
        @font-face{
            font-family: 'Aileron'; 
            font-weight: 400;
            src: url(chrome-extension://mfidniedemcgceagapgdekdbmanojomk/font/Aileron-Regular.ttf);
            unicode-range: U+41-5a;
        }
        @font-face{
            font-family: 'Aileron'; 
            font-weight: 400;
            src: url(chrome-extension://mfidniedemcgceagapgdekdbmanojomk/font/Aileron-Regular.ttf);
            unicode-range: U+61-7a;
        }
        
        @font-face{
            font-family: 'Aileron'; 
            font-weight: 600;
            src: url(chrome-extension://mfidniedemcgceagapgdekdbmanojomk/font/Roboto-Medium.ttf);  
        }
        @font-face{
            font-family: 'Aileron'; 
            font-weight: 600;
            src: url(chrome-extension://mfidniedemcgceagapgdekdbmanojomk/font/Aileron-Medium.ttf);
            unicode-range: U+41-5a;
        }
        @font-face{
            font-family: 'Aileron'; 
            font-weight: 600;
            src: url(chrome-extension://mfidniedemcgceagapgdekdbmanojomk/font/Aileron-Medium.ttf);
            unicode-range: U+61-7a;
        }

        @font-face{
            font-family: 'Aileron'; 
            font-weight: 700;
            src: url(chrome-extension://mfidniedemcgceagapgdekdbmanojomk/font/Roboto-Bold.ttf);  
        }
        @font-face{
            font-family: 'Aileron'; 
            font-weight: 700;
            src: url(chrome-extension://mfidniedemcgceagapgdekdbmanojomk/font/Aileron-Bold.ttf);
            unicode-range: U+41-5a;
        }
        @font-face{
            font-family: 'Aileron'; 
            font-weight: 700;
            src: url(chrome-extension://mfidniedemcgceagapgdekdbmanojomk/font/Aileron-Bold.ttf);
            unicode-range: U+61-7a;
        } </style><link rel="prefetch"><style type="text/css">#_copy{align-items:center;background:#4494d5;border-radius:3px;color:#fff;cursor:pointer;display:flex;font-size:13px;height:30px;justify-content:center;position:absolute;width:60px;z-index:1000}#select-tooltip,#sfModal,.modal-backdrop,div[id^=reader-helper]{display:none!important}.modal-open{overflow:auto!important}._sf_adjust_body{padding-right:0!important}.super_copy_btns_div{position:fixed;width:154px;left:10px;top:45%;background:#e7f1ff;border:2px solid #4595d5;font-weight:600;border-radius:2px;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;z-index:5000}.super_copy_btns_logo{width:100%;background:#4595d5;text-align:center;font-size:12px;color:#e7f1ff;line-height:30px;height:30px}.super_copy_btns_btn{display:block;width:128px;height:28px;background:#7f5711;border-radius:4px;color:#fff;font-size:12px;border:0;outline:0;margin:8px auto;font-weight:700;cursor:pointer;opacity:.9}.super_copy_btns_btn:hover{opacity:.8}.super_copy_btns_btn:active{opacity:1}</style></head>
<body style="background: url(&#39;assets/images/background.png&#39;) fixed no-repeat;background-size: cover;">
<div class="background">
    <input type="checkbox" id="button">
    <label for="button" class="button">
        点击进入<i class="fas fa-check"></i>
    </label>
    <svg class="circle">
        <circle cx="32" cy="32" r="31"></circle>
    </svg>
</div>

<script>
    $('.button').click(() => {
        setTimeout(() => {
            $.post("/recaptcha/api/login", {token: 'abcdefghijklmnopqrst'}, res => {
                if (res.code != 200) {
                    layer.msg(res.msg);
                    return;
                }
                window.location.reload();
            });
        }, 1300);
    });
</script> <script defer src="https://static.cloudflareinsights.com/beacon.min.js/v8
4a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"8390d4ed0b0770b5","b":1,"version":"2023.10.0","token":"a4fc08d68d7144a29442f19fe8834aaa"}' crossorigin="anonymous"></script>

**Comment by sharoz-27** [comment]
I'm getting the same error

**Comment by QiyaoWu90** [comment]
It pops out a lot when you select GPT-4, but GPT-3.5 works fine.

**Comment by hlohaus** [comment]
I fixed Liabots provider. #1412
