### ISSUE TITLE
add Mixtral-8x7B-instruct from perplexity.ai

### ISSUE THREAD

**Issue by sharoz-27** [xtekky/gpt4free#1376]
Pls add model: "Mixtral-8x7B-instruct" from provider: "perplexity.ai" - this is a great solution for work. Chat page: https://labs.perplexity.ai/

**Comment by sharoz-27** [comment]
I apologize, I read in other topics that Cloudflare is blocking there. The question regarding the perplexity.ai provider has been resolved. What about the model Mixtral-8x7B-instruct but from other providers?

**Comment by hlohaus** [comment]
I think HuggingChat has mixtral model.

**Comment by sharoz-27** [comment]
HuggingChat does not have an API for working with mixtral. api-inference also prevents us from using it, due to the volume of the model. If you know how you can use this model quickly and for free, then let me know pls.

**Comment by hlohaus** [comment]
The provider HuggingChat here in g4f support mixtral model. ;)

**Comment by sharoz-27** [comment]
Really! It’s strange, but I couldn’t find this earlier))) Thank you!
