### ISSUE TITLE
gpt4 now error { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }

### ISSUE THREAD

**Issue by vatva691** [xtekky/gpt4free#138]
{ "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }

**Comment by richigamer** [comment]
Same issue for me

**Comment by marwenbk** [comment]
even gpt 3.5 on the site

**Comment by xtekky** [comment]
please join the discord server for future updates: https://discord.gg/gpt4free, I am looking into it
