### ISSUE TITLE
New provider

### ISSUE THREAD

**Issue by OmiiiDev** [xtekky/gpt4free#1384]
I have no idea what model this is but it works...

https://chat.chatgptdemo.net/

**Comment by OmiiiDev** [comment]
And another one:

https://gpt6.ai/chat

**Comment by hlohaus** [comment]
https://github.com/xtekky/gpt4free/pull/1389

**Comment by owlcloud** [comment]
https://gptnederlands.nl/chatgpt-online/

**Comment by owlcloud** [comment]
https://www.aichatting.net/
