### ISSUE TITLE
Add a few models that is available from two providers

### ISSUE THREAD

**Issue by sharoz-27** [xtekky/gpt4free#1391]
I didn't find the OpenChat and vicuna-13b model that the providers have: h2o and huggingChat. Can you add them?

h2o: 
![image](https://github.com/xtekky/gpt4free/assets/145263538/33a07215-d8a5-4cce-8dd3-554bf815719d)
![image](https://github.com/xtekky/gpt4free/assets/145263538/0b9c3181-ac01-4177-9502-459e95c25d10)

huggingChat: 
![image](https://github.com/xtekky/gpt4free/assets/145263538/6e0e489a-7719-407f-98cc-412ec7aa5f4a)

**Comment by sharoz-27** [comment]
I just noticed that the provider h2o is not working

**Comment by hlohaus** [comment]
I added the openchat model to g4f. Yes, h2o is not workng.
