### ISSUE TITLE
docker run failed

### ISSUE THREAD

**Issue by wuye251** [xtekky/gpt4free#140]
docker build success; then docker run is failed.
container message is:

Usage: streamlit run [OPTIONS] TARGET [ARGS]...

Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: streamlit_app.py
<img width="552" alt="image" src="https://user-images.githubusercontent.com/24435699/234466009-3b5c3fad-9e9c-40a4-aed9-1c13b4d49ca6.png">

**Comment by jomozz** [comment]
you can try use this Dockerfile
`FROM python:3.10

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/xtekky/gpt4free.git

WORKDIR /gpt4free
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

COPY gui/streamlit_app.py ./

CMD ["streamlit", "run", "streamlit_app.py"]`


build and run again

**Comment by jomozz** [comment]
> FROM python:3.10

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/xtekky/gpt4free.git

WORKDIR /gpt4free
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

COPY gui/streamlit_app.py ./

CMD ["streamlit", "run", "streamlit_app.py"]

use this Dockerfile ,  build and run again

**Comment by wuye251** [comment]
> > FROM python:3.10
> 
> > RUN apt-get update && apt-get install -y git
> 
> > RUN git clone https://github.com/xtekky/gpt4free.git
> 
> > WORKDIR /gpt4free
> > RUN pip install --no-cache-dir -r requirements.txt
> 
> > EXPOSE 8501
> 
> > COPY gui/streamlit_app.py ./
> 
> > CMD ["streamlit", "run", "streamlit_app.py"]
> 
> use this Dockerfile , build and run again

you're right. I found same fix at [Correct Dockerfile #136](gliptak:patch-1)

**Comment by wuye251** [comment]
fixed.
