### ISSUE TITLE
How to hide warning

### ISSUE THREAD

**Issue by GDPlayer** [xtekky/gpt4free#1401]
**Bug description**
Used pyinstaller to convert the python script to an executable
upon running the executable and generating, this error shows up:
```
Failed to check g4f pypi version: [WinError 2] The system cannot find the file specified
```

**Environment**
- python version 3.12.1

**Comment by hlohaus** [comment]
In python:
```py
import g4f

g4f.debug.check_version = False
```
or
```bash
export G4F_VERSION=0.1.9.7
```

**Comment by GDPlayer** [comment]
already tried that
doesn't hide the warning completeluy
