### ISSUE TITLE
what's wrong with this error : please make sure you are using a cf_clearance token and correct useragent | Expecting value: line 1 column 1?

### ISSUE THREAD

**Issue by jomozz** [xtekky/gpt4free#141]
<img width="913" alt="image" src="https://user-images.githubusercontent.com/6438089/234469962-789e3d58-bdc5-4c50-a88b-25beb71a779d.png">

Tried to switch multiple agent, but it didn't work

**Comment by GentlemanMC** [comment]
i got the same error
![image](https://user-images.githubusercontent.com/76640636/234475678-b7d33278-972f-42d0-a0e8-100775b3ea71.png)

**Comment by DGabri** [comment]
same here

**Comment by GentlemanMC** [comment]
< same here

what version of python are you using
try running `python` in console

**Comment by singularitti** [comment]
My Python version is 3.11.2 and has the same error @GentlemanMC.

**Comment by Darvinleo** [comment]
Got the same error.  Python 3.10.11 build from docker

**Comment by pheonis2** [comment]
This thread has the solution:https://github.com/xtekky/gpt4free/issues/123

I just fixed mine following this thread

**Comment by singularitti** [comment]
I got it run, too. Thanks @pheonis2
For future users, please see: https://github.com/xtekky/gpt4free/issues/123#issuecomment-1521788874 and https://github.com/xtekky/gpt4free/issues/123#issuecomment-1521879306

**Comment by xtekky** [comment]
#153
