### ISSUE TITLE
Providers are taking too long to respond

### ISSUE THREAD

**Issue by Meshwa428** [xtekky/gpt4free#1410]
From my analysis I found that the minimum time taken for the bot to respond with openai api is 2 to 7 seconds. But here with this library it takes the minimum of 7 seconds(rarely happens) and maximum of 50 to 80 seconds(in almost all cases).

Isn't there a way to optimize and reduce the time taken to fetch the response from the providers?

**Comment by hlohaus** [comment]
You can call the providers async. The requests needs this time. Maybe a better internet connection can improve the execution time.

**Comment by Meshwa428** [comment]
But the opanai api always takes 4 to 7 seconds for each response.

And this one takes a lot more time than that
