### ISSUE TITLE
Add proxy option to gui cli agruments

### ISSUE THREAD

**Issue by l4v3nx** [xtekky/gpt4free#1418]
**Is your feature request related to a problem? Please describe.**
We already have proxy option when using g4f package in python file. It's a good idea to add this option for deploying gui server

**Describe the solution you'd like**
I'm not a programmer, but you can somehow link ```proxy``` [method](https://github.com/xtekky/gpt4free/blob/e64a00332385d749d9c778f93421610ceb1eab54/g4f/__init__.py#L73C2-L73C2) of ```ChatCompletion```  class to gui server sources

**Comment by hlohaus** [comment]
You can set a proxy via a environment variable in gui and api:
```bash
export G4F_PROXY=http:/proxy:ip
```

**Comment by l4v3nx** [comment]
> You can set a proxy via a environment variable in gui and api:
> 
> ```shell
> export G4F_PROXY=http:/proxy:ip
> ```

oh, didn't know that, thanks
