### ISSUE TITLE
GPT-4 is not free atleast not right now, Phind also using gpt 3.5

### ISSUE THREAD

**Issue by pheonis2** [xtekky/gpt4free#142]
Got this out put when i saked phind if its using gpt-4 or gpt-3.5 in the backend.

"I am using the GPT-3.5 model in the backend, specifically the gpt-35-turbo version, which is equivalent to the gpt-3.5-turbo model from OpenAI [Source 0](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/chatgpt). GPT-4 models are also available, but they are currently in a limited preview and require applying for access [Source 1](https://techcommunity.microsoft.com/t5/ai-cognitive-services-blog/working-with-gpt-4-and-chatgpt-models-on-azure-preview/ba-p/3773595)."

My question now is, when we can use free chatgpt, then why will we use this repo?

**Comment by xtekky** [comment]
...
