### ISSUE TITLE
Found another website that uses gpt 3.5

### ISSUE THREAD

**Issue by Meshwa428** [xtekky/gpt4free#1420]
guys i found another link, this one is by a well known library owner LANGCHAIN

this is a free hosted website of langchain's openGPT's which allows us to use gpt 3.5 for free with custom tools like search and all other stuff

here is the link
https://opengpts-example-vz4y4ooboq-uc.a.run.app/

You can literally find the docs to reverse it here😂😂😂
https://github.com/langchain-ai/opengpts/blob/main/API.md

@hlohaus please take a look

**Comment by llaichiyu** [comment]
thanks a lot~
