### ISSUE TITLE
support DALLE-3 in ChatGPT Plus with 1792x1024 generate images

### ISSUE THREAD

**Issue by OlegRuban-ai** [xtekky/gpt4free#1432]
I want to use a ChatGPT Plus account to generate images in 1792x1024 resolution. Tell me, is this possible with this package?

**Comment by Argrarorg** [comment]
no

**Comment by subhadeeproy3902** [comment]
I wanna contribute to this repo

**Comment by hlohaus** [comment]
I added support for ChatGPT Plus and Images
