### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by edenlith** [xtekky/gpt4free#1439]
Hi there. Everytime I use g4f it starts well but after a few questions I get this error "An error occured, please try again, if the problem persists, please use a other model or provider". I've tried all models and providers but I still get the error after a while. I've toggled on and off Web Access and tried a VPN but I still get the error after a while. My internet is alright so I don't think the internet is the problem.

**Comment by hlohaus** [comment]
The errors are log to the browser console. What are the error message?

**Comment by edenlith** [comment]
Hi. G4f started working alright but I had to reinstall it and now I'm getting this output:  Traceback (most recent call last):
  File "/home/.pyenv/versions/3.10.4/bin/g4f", line 5, in <module>
    from g4f.cli import main
  File "/home/.pyenv/versions/3.10.4/lib/python3.10/site-packages/g4f/__init__.py", line 6, in <module>
    from .models   import Model, ModelUtils, _all_models
  File "/home/.pyenv/versions/3.10.4/lib/python3.10/site-packages/g4f/models.py", line 3, in <module>
    from .Provider   import RetryProvider, ProviderType
  File "/home/.pyenv/versions/3.10.4/lib/python3.10/site-packages/g4f/Provider/__init__.py", line 19, in <module>
    from .Bing            import Bing
  File "/home/.pyenv/versions/3.10.4/lib/python3.10/site-packages/g4f/Provider/Bing.py", line 252
    timeout = int = 900
                  ^
SyntaxError: invalid syntax 

I'm kinda new to this can you tell why i'm getting this ouput

**Comment by BenutzerEinsZweiDrei** [comment]
Same error for me

**Comment by hlohaus** [comment]
Try to update your installation

**Comment by BenutzerEinsZweiDrei** [comment]
Updating solved it. Now i have "vercel is not working"

**Comment by BenutzerEinsZweiDrei** [comment]
```python
import g4f

allowed_models = [
    'code-davinci-002',
    'text-ada-001',
    'text-babbage-001',
    'text-curie-001',
    'text-davinci-002',
    'text-davinci-003'
]

prompt = "What"


response = g4f.Completion.create(
    model='text-davinci-003',
    prompt=prompt
)

print(response)
```

**Comment by BenutzerEinsZweiDrei** [comment]
![Screenshot_2024-01-14-01-20-58-873-edit_com server auditor ssh client](https://github.com/xtekky/gpt4free/assets/57397036/05c2fd75-5fa7-440d-86ba-21e2a19c96f9)

**Comment by hlohaus** [comment]
Use ChatCompletion not Completion.
Then you can use a other Provider.
