### ISSUE TITLE
New site with Gemini pro, llama and others 

### ISSUE THREAD

**Issue by OmiiiDev** [xtekky/gpt4free#1442]
Site: https://ai.jaze.top/

Model support

VisionGeminiPro Vision
Vincentian picturestable-diffusion-xl-base-1.0
text generationGeminiPro llama-2-7b-chat-fp16 llama-2-7b-chat-int8 mistral-7b-instruct-v0.1 gpt-3.5-turbo
code generationcodellama-7b-instruct-awq
translatem2m100-1.2b

Not a bug sorry...

**Comment by devAdityaa** [comment]
Wow Where do you find all these amazing sites lol. Anyways, I'll add it.
