### ISSUE TITLE
Incorrect param in func stream_generate

### ISSUE THREAD

**Issue by maximmensah** [xtekky/gpt4free#1443]
`async def stream_generate(
        prompt: str,
        tone: str,
        image: str = None,
        context: str = None,
        proxy: str = None,
        cookies: dict = None,
        web_search: bool = False,
        gpt4_turbo: bool = False,
        timeout = int = 900  <<< incorrect
    ):`

g4f.Provider.Bing func stream_generate

I have python 3.11, and have installed g4f==0.2.0.0

**Comment by Eikosa** [comment]
Fixed, sorry
