### ISSUE TITLE
API is not working - using  docker & http://127.0.0.1:1337 & Hugging Face Token

### ISSUE THREAD

**Issue by changeng2006** [xtekky/gpt4free#1457]
**Bug description**
API is not working - using  docker ,
using [Hugging Face Tokens](https://huggingface.co/settings/tokens) ,and  http://127.0.0.1:1337/

retunback error: 
{
  "error": true,
  "message": "Failed to fetch"
}

**Comment by voynovia** [comment]
also

**Comment by Thomashighbaugh** [comment]
use http://0.0.0.0:1337 which works for me right now just fine.
