### ISSUE TITLE
Massive Providers list of URLs (Claude, Gemini Pro w/ vision, GPT4 w/ plugins & Vision and custom models

### ISSUE THREAD

**Issue by OmiiiDev** [xtekky/gpt4free#1458]
### Here is a list of new possible providers:
_some may have been already implemented_

**gpt3,5 and random**
https://chat-gpt.org/chat
https://hf4all-bingo.hf.space/
https://chatgpt.ai/
https://deepai.org/
https://lobe.eqing.tech/
https://chat4.free2gpt.xyz/
https://pizzagpt.it/
https://chat.nbox.ai/
https://promptboom.com/PowerChat/

**Claude, claude instant, gpt4, gemini, gpt3.5:**
https://room.chatgpt.org.uk/
https://ai.chatgpt.org.uk/
https://free.chatgpt.org.uk/

### Custom LLMs:
**Models:** h2oai/h2ogpt-4096-llama2-70b-chat, mistralai/Mixtral-8x7B-Instruct-v0.1, HuggingFaceH4/zephyr-7b-beta, gpt-3.5-turbo-0613, h2oGPT [Model: openchat/openchat-3.5-1210], h2oGPT [Model: lmsys/vicuna-13b-v1.5-16k], h2oGPT [Model: h2oai/h2ogpt-32k-codellama-34b-instruct]:
https://gpt-gm.h2o.ai/  <-- Very customizable

**Models:** pplx-7b-online, pplx-70b-online, pplx-7b-chat, pplx-70b-chat, mistral-7b-instruct, codellama-34b-instruct, llama-2-70b-chat, llava-7b-chat, mixtral-8x7b-instruct, mistral-medium
https://labs.perplexity.ai/
 
 
###  Coolest models:
**Gemini pro, GPT-4 (all) w/vision w/ plugins, TTS, Chat GLM, Gemini Pro Vision etc...** : https://chat.eqing.tech/   --> Mirror sites: https://origin.eqing.tech/ , https://origin.nextway.top/ , https://chat3.eqing.tech/ , https://chat3.eqing.tech/ , https://vip.easychat.work/

**Comment by PasEytan** [comment]
thanks fam
