### ISSUE TITLE
Error Bing

### ISSUE THREAD

**Issue by GolikovStepan48** [xtekky/gpt4free#1469]
Traceback (most recent call last):
  File "a:\Python\RobotAI\main.py", line 9, in <module>
    for message in response:
  File "A:\Python 312\Lib\site-packages\g4f\Provider\base_provider.py", line 142, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Python 312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "A:\Python 312\Lib\site-packages\g4f\Provider\Bing.py", line 270, in stream_generate
    async with session.ws_connect(
  File "A:\Python 312\Lib\site-packages\aiohttp\client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "A:\Python 312\Lib\site-packages\aiohttp\client.py", line 841, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub?sec_access_token=rCnCM6B8IlvoE9un9UCZ5reC8eNUjq4EmQLH7TLzmy/HpF9Pliw7SZgude3xdDfhW7yucahQVuuwQdKOujyqauHY4L/sRUyrYjjhDwB5RBoVkSIllJ%2B%2ByiTfozCvXGvfm26DazElSDdN9pCS1SSt04e2EFFFtW6AqvPzOi8PP2QVM9NkCepeagYICDGqN5iOU4DVKukabugiI%2B0632Zfy1HqAJwmf42xeSRP%2BckZUr2Qpb756rWkLKo4J5XefepPfN%2B8hs19nrtUw5sLKZpny3Q8%2BkIsxgTiO5q4vZBb1efwDjBUU50OgN3NtWuG3RmN7a8whnry374lozjC5PgbCN9B43PIvtUqDS1Qx70D6J%2BQWu7%2BC44whxt%2BslLErK7Rolx%2BPwUsicB8EBMatolR8i%2BaKijfkoqiee1ouuIqwpqSrNUYJQRkf4b/9NmPVbrX/WrPOugPAE28yOEkHvF8jqwg4MmxsTzep5L43tBiBWi7iD6sNWMUzxxnUhJK1dmiSliZ3ud/EneGONq2mLJGzCvf5r3p9CIViZB%2BFcST7kqr3WrGU6Nhdc0k/PYsoAiOpfJq06PKYCmXGGPPvZJS0Rf0K%2B5ogdy9gMbQbGDIAtsvyBUzozXiiugRrDBF5ORe1%2Bg8zjTQQIjyjzKtGCZ3xe9FfQyZ0h91peCJaAI9r1XhmewptZVj8dgvGLTGIwH7qDiPj9xgr217BtSq00Ome6qzro0o0gnOlxIhVdD%2BNFbRkvU2t/WaQbgQ//S2c53Fa8r0cK6oIOO/BLh/C/6ZVTMT6WKK55/OK3H00dAD%2BJTdqZFbIkTKjtnHMMlnGsjyoQKVM5fcbRRS6Wdtjk6GDuECjQdC2iDtmm9bRXfmbxpsQnjB0IBMVgCPttLb8iRkcGksEjEFnPV%2B51XIGedsyK2IG6nSOPxhUk2LTiexEwQ9p1m%2BRaPYzV93CT5UuLrQu043SNZbc51mWrokOaRCfLKVEl7P6s%2BRJTkipqkCKWbC2DZSE89vyTWrP4NXT5n2XuCXeg27zlJ0NFb7guMxV2/XmkOqw5rhSZ6AKvyqL2qEiPebuOPwwRAlysM%2BxY4x1P2UsAMM9pxk186Yf/FRzJQ1f1yljuQ5iQw4k89oowCYgmNuLUgcYCWKKlHpzKBVrxRiHGKN0i6g0oIgsX0UdQ%3D%3D')

**Comment by GlitchOwl** [comment]
have u found the way to fix this?
