### ISSUE TITLE
Easier to read menu's

### ISSUE THREAD

**Issue by techcow2** [xtekky/gpt4free#1474]
**Is your feature request related to a problem? Please describe.**
Yes, it's really hard to read the menu's with their current styling.

**Describe the solution you'd like**
Make the menus easier to see

**Describe alternatives you've considered**
When I turn on Dark reader, that actually fixes the problem.

**Additional context**

![Screenshot 2024-01-15 061812](https://github.com/xtekky/gpt4free/assets/108380065/bfb833f6-60bd-4a05-a2d1-a7e026ae65cd)

**Comment by hlohaus** [comment]
I changed the background colors of select boxes. Now it is white on black.
