### ISSUE TITLE
CaptchaChallenge in Bing

### ISSUE THREAD

**Issue by piotr25691** [xtekky/gpt4free#1483]
**Bug description**
What did you do, what happened, which file did you try to run, in which directory
Describe what you did after downloading repo, such as moving to this repo, running this file.

Bing is giving us a CaptchaChallenge after we've used it for 2 months.

ex.
1. Use Bing for a while
2. Eventually Bing will want you to solve the CAPTCHA

**Screenshots**

![image](https://github.com/xtekky/gpt4free/assets/71488561/d4f1aa3d-943c-4707-85f7-d490748edf15)

**Environment**
- python version - 3.11.6
- location ( are you in a cloudfare flagged country ) - Germany (it's a VPS)

**Additional context**

None

**Comment by Alienpups** [comment]
Just encountered the same problem. If you wait a minute it gets resolved but you will encouter it again by using it too frequently.

**Comment by piotr25691** [comment]
this might be more than just a spam cuz i've been getting captchas for a month with no break, im gonna just close this
