### ISSUE TITLE
how to use image generation on the ubuntu server?

### ISSUE THREAD

**Issue by Lein000** [xtekky/gpt4free#1493]
how to use image generation on the ubuntu server?

ERROR:root:Binary Location Must be a String
Traceback (most recent call last):
  File "/root/gpt4free-main/g4f/gui/g4f/gui/server/backend.py", line 185, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/root/gpt4free-main/g4f/gui/g4f/Provider/create_images.py", line 103, in create_completion
    yield from self.create_images(prompt)
  File "/root/gpt4free-main/g4f/gui/g4f/Provider/bing/create_images.py", line 219, in create_completion
    cls._cookies = cookies = get_cookies_from_browser(proxy)
  File "/root/gpt4free-main/g4f/gui/g4f/Provider/bing/create_images.py", line 190, in get_cookies_from_browser
    with get_browser(proxy=proxy) as driver:
  File "/root/gpt4free-main/g4f/gui/g4f/webdriver.py", line 48, in get_browser
    return Chrome(
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 372, in __init__
    options.binary_location = (
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/options.py", line 55, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String

**Comment by hlohaus** [comment]
You need Google Chrome on the server. It Open the browser for login. Currently you can't pass own cookies.

**Comment by Lein000** [comment]
would this work in ubuntu without a GUI?

**Comment by hlohaus** [comment]
There is website in docker with the desktop of the maschine. The Browser open his windows in this desktop. noVNC is the name of the service. This can you use to login in a provider. Bing - Create Images required a active session for example.

**Comment by hlohaus** [comment]
Or you do pass the cookies in your own code:
```python
import g4f
from g4f.Provider.create_images import CreateImagesProvider
from g4f.Provider.bing.create_images import CreateImagesBing

service = CreateImagesBing(cookies = {})

def patch_provider(provider: ProviderType):
    return CreateImagesProvider(
        provider,
        service.create_completion,
        service.create_async
    )

for chunk in ChatCompletion.create(
  g4f.models.default,
  messages,
  stream = True,
  patch_provider = patch_provider
):
    print(chunk)
```

**Comment by Lein000** [comment]
Thanks for the reply. Is it even possible to solve a captcha in the same way? It's just that socks5 proxies don't work in Bing, and public http proxies are not stable. By the way, here is the code and the error:@staticmethod
    def create_async_generator(
        model: str,
        messages: Messages,
        proxy: str = "socks5://pXXXXXe:WXXXXXpK@163.198.232.164:8000",
        timeout: int = 900,
        cookies: dict = None,
        tone: str = Tones.balanced,
        image: ImageType = None,
        web_search: bool = False,

400, message="Expected HTTP/:\n\n  b''\n    ^", url=URL('socks5://pXXXXXe:XXXXXXXK@163.198.232.164:8000')
<traceback object at 0x00000286EC05FB80>

**Comment by hlohaus** [comment]
aiohttp doesn't support socks proxies by default.
I found aiohttp_socks for that. I included it here:
#1510

**Comment by Lein000** [comment]
thanks for the answer
