### ISSUE TITLE
gpt4一直调用bing这个供应商

### ISSUE THREAD

**Issue by hua-ge** [xtekky/gpt4free#1499]
gpt4一直调用bing这个供应商，部署的话，如何删除这个供应商？

**Comment by catmeowjiao** [comment]
1.不建议删除，因为bing是目前最可靠的gpt4供应商，其它供应商随时会不可用，若您删除了它，可能导致使用gpt4时无回复。
2.如果您要删除，请将[您的gpt4free目录]/g4f/Provider/Bing.py第32行中的`working = True`改为`working = False`。
