### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by Monika01002** [xtekky/gpt4free#1500]
When I run it in huggingface spaces, this error appears. But this error does not appear when run on google colab or locally

{
  "response": "401, message='Unauthorized', url=URL('https://liaobots.work/api/user')"
}

**Comment by FujiwaraChoki** [comment]
+1

**Comment by hlohaus** [comment]
With Liabots do you have only 10 free messages. On the 11th message this error raise.
