### ISSUE TITLE
Using global proxy

### ISSUE THREAD

**Issue by mat-674** [xtekky/gpt4free#1517]
Hello! Maybe i'm something don't understand, but i can't set global proxy for g4f by this code
`export G4F_PROXY="http://host:port"`

I taking an error 
`File "C:\gpt4free\main.py", line 3
    export G4F_PROXY=https//45.87.68.3:15321 
SyntaxError: invalid syntax`

Can  somebody explain me where i need put this code?

**Comment by catmeowjiao** [comment]
1. This command should be executed in the Linux terminal, not added to main.py.
2. You are using Windows, so you should execute `set G4F_PROXY=http://host:port` in cmd or powershell.

**Comment by mat-674** [comment]
Thank you. That's working.
