### ISSUE TITLE
Additional info disapeared in the console in version 2.0.6

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1518]
Previously, at least in 2.0.4 version, there was additional info in the console showing, e.g. what provider and model were used
`Using OpenaiChat provider and gpt-4-turbo model`,
but in 2.0.6 version this convenient info disappeared, only displaying
`127.0.0.1 - - [27/Jan/2024 04:08:15] "POST /backend-api/v2/conversation HTTP/1.1" 200 -`

Is there a way to bring this info back?

**Comment by hlohaus** [comment]
You want the debug logging. You can enable it with:
```python
import g4f
g4f.debug.logging = True
```

**Comment by iG8R** [comment]
Thanks for the quick reply.
I used `g4f gui -debug` but nothing changed

![image](https://github.com/xtekky/gpt4free/assets/11407417/18504eba-6398-4629-a937-114565f96fe1)

**Comment by iG8R** [comment]
I added the following code into `c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.7-py3.12.egg\g4f\gui\__init__.py` and it works now, but why did it work fine in previous builds without this modification?

```
    raise MissingRequirementsError('Install "flask" package for the gui')

# start of inserted code

import g4f
from .. import debug

debug.logging = True

# end of inserted code

def run_gui(host: str = '0.0.0.0', port: int = 8080, debug: bool = False) -> None:
```
