### ISSUE TITLE
G4F_PROXY no longer works

### ISSUE THREAD

**Issue by firengate** [xtekky/gpt4free#1525]
The G4F_PROXY variable does not work on version 0.2.0.7
On version 0.2.0.4 everything works.

g4f@9c97f643683d:/app$ echo $G4F_PROXY
http://xx.xx.xx.xx:443

I take it this has to do with the commit:
Add aiohttp_socks support by @hlohaus in #1510

But there is no information anywhere, what format should be used for G4F_PROXY now?

**Comment by hlohaus** [comment]
Do you have aiohttp_socks installed?
- pip install aiohttp_socks
