### ISSUE TITLE
Providers aren't listed correctly

### ISSUE THREAD

**Issue by mak448a** [xtekky/gpt4free#1528]
**Bug description**
When you run the [provider list command from the readme](https://github.com/xtekky/gpt4free?tab=readme-ov-file#providers) it prints out the providers that are working. However, some of these statuses are incorrect. For example, g4f.Provider.OpenAIChat. This is listed in "Unknown" in the readme.

**Screenshots**

**Environment**
- Python 3.11
- United States
- Latest version of g4f from pip

**Comment by mak448a** [comment]
Please don't close it.

**Comment by mak448a** [comment]
Please don't close it.

**Comment by hlohaus** [comment]
I updated the provider list with current status

**Comment by mak448a** [comment]
Thanks!
