### ISSUE TITLE
phind.com takedown request

### ISSUE THREAD

**Issue by xtekky** [xtekky/gpt4free#153]
Unfortunately I will have to take down code for phind.com soon,

<img width="780" alt="image" src="https://user-images.githubusercontent.com/98614666/234576741-caa88f51-ff7b-4e85-911b-d2a19c890793.png">

will be replaced by an alternative gpt-4 i am working on at the moment

**Comment by 9xN** [comment]
damn

**Comment by cometbus** [comment]
Is there a work around? is this broken for now?

**Comment by xtekky** [comment]
its still working atm and will prolly be revived by another repo, watch out I am not the only reverse egineer on github...

**Comment by 9xN** [comment]
> its still working atm and will prolly be revived by another repo, watch out I am not the only reverse egineer on github...

i dont believe it is working atm but i might make a fork and make a repo for it

**Comment by AbdelrhmanNile** [comment]
> 
its not working

**Comment by mishalhossin** [comment]
> > its still working atm and will prolly be revived by another repo, watch out I am not the only reverse egineer on github...
> 
> i dont believe it is working atm but i might make a fork and make a repo for it

It's working 
![image](https://user-images.githubusercontent.com/91066601/235299786-db8aec2b-52c3-4f44-8dc7-75e02288b2df.png)

**Comment by Pozaza** [comment]
> It's working ![image](https://user-images.githubusercontent.com/91066601/235299786-db8aec2b-52c3-4f44-8dc7-75e02288b2df.png)

can you send me the code?

**Comment by mishalhossin** [comment]
> > It's working ![image](https://user-images.githubusercontent.com/91066601/235299786-db8aec2b-52c3-4f44-8dc7-75e02288b2df.png)
> 
> can you send me the code?

not working now

**Comment by 0dminnimda** [comment]
> > > It's working ![image](https://user-images.githubusercontent.com/91066601/235299786-db8aec2b-52c3-4f44-8dc7-75e02288b2df.png)
> > 
> > 
> > can you send me the code?
> 
> not working now

because of cloudflare?
