### ISSUE TITLE
NestAsyncioError: Use "create_async" instead of "create" function in a running event loop. Or use "nest_asyncio" package.

### ISSUE THREAD

**Issue by messizqin** [xtekky/gpt4free#1530]
sorry that this bug has nothing associated with g4f, it was my code's problem, pls close it

**Comment by t-dsai** [comment]
@messizqin 
I'm also facing this exact problem. How did you solve it?

@hlohaus : If I use version 0.2.0.3 or below, there is no problem with my code, and I get expected results. However, for all the versions >=0.2.0.4, I'm getting this error.
