### ISSUE TITLE
g4f[all] installation fails, setup.py is missing a comma

### ISSUE THREAD

**Issue by t-dsai** [xtekky/gpt4free#1533]
**Known Issues**
The installation of `g4f[all]` option fails.

**Bug description**
In the file `setup.py`, in the dict part `EXTRA_REQUIRE`, a comma `(,)` is missing after `aiohttp_socks`. This causes `aiohttp_socks` to be joined with the next line package name `pillow`.

**Screenshots**
![gpt4free_aiohttp_socks_pillow](https://github.com/xtekky/gpt4free/assets/146815985/a5ed5690-7690-452e-807d-5a22d7fa49be)

**Environment**
Debian: 12.4
Python: 3.11.7

**Comment by hlohaus** [comment]
I released a fix. Thank you
