### ISSUE TITLE
Import error: cannot import name 'set_cookies'

### ISSUE THREAD

**Issue by 0x32-l3git** [xtekky/gpt4free#1534]
`from g4f import set_cookies`
ImportError: cannot import name 'set_cookies' from 'g4f' (C:\Users\null\AppData\Roaming\Python\Python312\site-packages\g4f\__init__.py)

and
 import g4f
g4f.set_cookies(stuff)
AttributeError: module 'g4f' has no attribute 'set_cookies'

**Comment by hlohaus** [comment]
It is only a alias import. And I don't know why it is not working.  But you can try this import:

from g4f.Provider.helper import get_cookies, set_cookies
