### ISSUE TITLE
Repeat of closed issue #1530: NestAsyncioError: Use "create_async" instead of "create" function ... Or use "nest_asyncio" package.

### ISSUE THREAD

**Issue by t-dsai** [xtekky/gpt4free#1538]
**Known Issues**
I've installed g4f with all the required packages (with [all] option).

I'm using a simple test prompt, say to ask why the sky is blue.

If I use version 0.2.0.3 or below, there is no problem with my code, and I get expected results. However, for all the versions above and equal to 0.2.0.4, I'm getting the error mentioned in the title line:
`NestAsyncioError: Use "create_async" instead of "create" function in a running event loop. Or use "nest_asyncio" package. `

This was also reported in issue #1530, although that has been closed.

How do I resolve this issue?

**Environment**
- python 3.11.7
- Debian 12.4

PS: Although I've also commented about my problem in issue #1530 , but I'm not sure if that will be read after closing or not. Therefore, my apologies in advance if a new issue opening wasn't required.

**Comment by hlohaus** [comment]
You have to patch asyncio with nest_asyncio.
Because you call the sync api in your async loop.
your async loop > g4f sync api > g4f async loop > async provider
It's nested. Or you use create_async:
your async loop > g4f async api
No nested. Before 0.2.0.4 maybe we patched asyncio without a warning. (not good)

Could i help you?

**Comment by t-dsai** [comment]
> You have to patch asyncio with nest_asyncio. Because you call the sync api in your async loop. your async loop > g4f sync api > g4f async loop > async provider It's nested. Or you use create_async: your async loop > g4f async api No nested. Before 0.2.0.4 maybe we patched asyncio without a warning. (not good)
> 
> Could i help you?

@hlohaus Thank you very much for taking time to respond.

I don't know whether you meant some intrinsic calling of sync/async loop, but explicitly I'm not calling/using it.

For your immediate reference, I attach 3 png files of screenshots. The first one, with name 0203, shows that the program is giving expected results. The ones with 0209 in name, shows that when I upgrade to 0209, the same program gives the said error.

![g4f_0203](https://github.com/xtekky/gpt4free/assets/146815985/bac13ae2-c6ea-4bb8-9000-c5b07824f566)
![g4f_0209_1](https://github.com/xtekky/gpt4free/assets/146815985/193fe952-eb5e-4761-9ef7-c09b2300d1fa)
![g4f_0209_2](https://github.com/xtekky/gpt4free/assets/146815985/005566e6-04a9-471a-ba3c-4ecb8fdf421a)

If some explicit changes are required in my code according to your hint, are there some examples/templates so that I can accordingly modify my code snippet?

Thank you very much once again for taking time to respond to all the issues, and running this project.

**Comment by hlohaus** [comment]
Okay, here the examples.

This at the beginning of your script:
``
import nest_asyncio
nest_asyncio.apply()
```

Or:
```
        response = await g4f.ChatCompletion.create_async(
            model=g4f.models.default,
            messages=[{"role": "user", "content": "Hello"}],
            provider=provider,
        )
```

**Comment by t-dsai** [comment]
> Okay, here the examples.
> 
> This at the beginning of your script:
> 
> ```
> import nest_asyncio
> nest_asyncio.apply()
> ```
> 
> Or:
> 
> ```
>         response = await g4f.ChatCompletion.create_async(
>             model=g4f.models.default,
>             messages=[{"role": "user", "content": "Hello"}],
>             provider=provider,
>         )
> ```

Thank you very much once again.
I updated to 0.2.0.9 version and used the first approach successfully.

Thereby, I'm closing this issue.

**Comment by thangckt** [comment]
hi 
can you have a littel help?
After using this 
```
        response = await g4f.ChatCompletion.create_async(
            model=g4f.models.default,
            messages=[{"role": "user", "content": "Hello"}],
            provider=provider,
        )
```
how to get the content of response?

thank

**Comment by hlohaus** [comment]
response should are the content:

print(response)
