### ISSUE TITLE
How to use openaichat provider?

### ISSUE THREAD

**Issue by mak448a** [xtekky/gpt4free#1539]
What do I put into the auth key?

**Comment by lotusnowshen** [comment]
`def request_chatgpt(content):
    response = g4f.ChatCompletion.create(
        model=g4f.models.gpt_35_turbo,
        messages=[{"role": "user", "content": content}],
        provider=OpenaiChat,
        auth=cookie,
    )  # Alternative model setting
    print('ChatGPT resp: ', response)
    return response`

**Comment by lotusnowshen** [comment]
```python 

def request_chatgpt(content):
    response = g4f.ChatCompletion.create(
        model=g4f.models.gpt_35_turbo,
        messages=[{"role": "user", "content": content}],
        provider=OpenaiChat,
        auth=cookie,   # Note that the cookie is passed from here
    )  # Alternative model setting
    print('ChatGPT resp: ', response)
    return response
```

**Comment by mak448a** [comment]
Is the cookie the "cookie" in the inspector on the web browser? Also, do I need chrome installed to have this work?

**Comment by hlohaus** [comment]
You need to pass a acces_token or else it open a browser window. The token can you get from here:
https://chat.openai.com/api/auth/session
You have to be logged in.

Example:
```python
g4f.ChatCompletion.create(
     ...,
     access_token="base64 value"
)
```

**Comment by mak448a** [comment]
Thanks

**Comment by mak448a** [comment]
Should I open an issue to add this to the docs repo?
