### ISSUE TITLE
Providers

### ISSUE THREAD

**Issue by BuninSil** [xtekky/gpt4free#1546]
Tell me the most stable provider at the moment, most have tried, most knock out errors, and those that work do not work stably

**Comment by hlohaus** [comment]
I like to use Bing, because it has the best model. Also all Providers with own/ open source models are working good. And a good provider with GPT 3 is You.

**Comment by iG8R** [comment]
I use g4f with gpt-4 model for translation from Chinese (novels) into English, and the best ones in terms of translation and stability are Bing and OpenaiChat, maybe Bing is a wee better.
OpenaiChat has a leverage from the standpoint of the amount of text it can translate in one go, translating really large texts, while Bing may interrupt translation halfway through.

**Comment by Lanc1um** [comment]
> I like to use Bing, because it has the best model. Also all Providers with own/ open source models are working good. And a good provider with GPT 3 is You.

What should I do if I got this message using Bing: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub?sec_access_token=aiYJQBhio9Iv0rDtFgf5P4gtOdiwcoEzMj/s/08L1kfywQgBVQvefflJ%2BlWXLxcplRXN/aixtcNwpShIILZX7epZubwgOA8%2BYqO0HfveZlFLNdC81neBIjU4VT/XOUT087Fr5VfLdwT20cFksPNVH75UVeNm8hIgHRWqDfJr1Aru2QGbqU6FyVqh4vuQIeEdy4xu0XNqcKVF3ezZ52vw4d8%2BHunyP5IGPmlpo1gi7eSdn5W7fiEhRTzY4yfT9keeSIlQ/h7uWdG4ov%2BMiFnOxSJkF1SaK%2B2hl/lVuXJA8XAjWEGvdpUMAbDZgWL1VHCH7rsZ0c8ZKb5WhzDOcD4hNPj2ZxAcGMzCe6zOrb7FsCmCisV9AVdAp183rMT7L9Ib/xdFzc9YeBoLB5C520bL6c8UKgIBrYdUQjgYQUB/BoNfU3ReU8ihowCcc1U7fRKpWnTbR528QwWr/gmVNz7FzOa7awwzyCxsCvxCj70StMZ5k6O7oCZVIwE0Q30jpm9uP0X2Ej/UgBeouKQlxb7VIbrLzyGvUN%2Btmwod82NBXdj4OEPh0mGKALVZEQOzFR2BMWayP4HBaWi22hYn4P3u%2BZdvZYXrx6Q4AzsOF04Eyoi/tdEY1v0yhB26/%2BID3b4yKlGDqisr9/7oCmtzKW/A7aBnT00z/2XorXkKe83lwzBpiBOqTN6Ws4TD3%2BaHcBL3cMphfcAfhFsyK57uT4yBmF%2BirCYRU9rKbTwDioKTC7MkepaD8idebtltWX6HQZX183HKRiKUkQEf7wYC5x7EFcFw%2BgMP7vFF/Mc2Whm6Es6owUt%2Bh4sQe/%2BHpojbw4cwL5x5gLkhE8vfD/JJ62wGJ0S9tBQpHQa4vnKducnZP%2B9R626/OWG7thQNHoHfEeEEEnvyXrs2i%2BqoL2L7%2BAdYAts9SMMHshyQpBybn/6DXwO2N1GhBVzoj40C3IkyPBHqYM/iivNivjvJxFhwBf%2B92TpxynSDzbk4/RX6EwMYAa0II3cm13TQTBLJRm3YfxxH7qljWRkgEtq8dg55cTajkidC13gWhDp124C/20w%2B5FUKGCEfAPF2VDHsXMefeRIfv/OkiWBERKHBThJRbw8rBPFaFNyHutSGOMPjMIVVWzC9wJ2Y0RkT4fT2F36LX7u/mYa6pgHj/lTs4tvTEKQbCbAJG83dV5e8rNCAdTHjNmJbFXDt7YN5ZI6yo39LCEzM0%2BXkWgLYmJV5CSyJD3xoDeN9jNtTJpXy/OX4rBIMVxM%3D')

**Comment by BuninSil** [comment]
Thanks. But I can't figure out how to use Bing correctly, I can't use it correctly for the bot in the Telegram. Can you tell me?

**Comment by BuninSil** [comment]
it's just that when I access Bing, I get this error
```
200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub?sec_access_token=562wwyZzF4K0oOktcVPTeyP1EmNZIEIpD62Fs/gtE%2BFUrFBUpn5vSBWZVZjJ%2BUmlWoD%2BglZJD2RmSndzP/sDnJD/yDsZ6uPoXr/O3lAYyXquodE6Fuu66rvsjWT66SmeQRpnN2Wdi9U3V%2BZwO5JHkkBeLVsjwE1S8EsZpKrPLyR0QUupzGkZFwN8ePuNOLI%2BVgULj3dC9yU5%2BVEFrrJL6FMl3UvSUUY7UuQH/u9fS/wjm5P/dXKVppxjbq8ZBI5C6Ryx/0sNl%2BLLs5Q%2BbrNa69eUZU6G/lSbKV27ruo%2Becxxs0gijmUMBybjzkTq35Pt6hb/lfCmmN5xLapbMI9k/RP6aEM31FvgLw3ZQ9xP4ZkTvOKskVDkkrLjesIXQC6kKOm8Qx3ij5dFzB/sSk2KBhjmAehoQ/d9JtgYv61SSwuoYAXY5VAWeP9r%2BaQT09UBKmEESdlrBG7Zz5Vs/uBjl9erFvIOOMwi8Haze8lQFwMXO%2Bm7oI5yUrPIFcJsmP/6TYwYA6xq//B1Vq3CMpkrhIftqhrPThyqHG5lSZYnkcw//JUiptanBRJDMCAR37zH482U7l9AZQwkVKFxNGb85AMPunluX7jxs5LXl537y2L50OXwKgpojdkpj9M4YD35QcwMk32QG%2BVmQT2oYgsQNBL4zgi/pU9abqzsnXjdGlbo8MXM0P%2BS2c4cNIUKduOrF/qbfg0%2BMw1Vd0XrBmsJSDWJ0MsEMyvGd32jsG5W05eF9ZAh8V4AICTt/k4iJykYfDXYTeVpzEr3srVe/TVGb4NhwPAzxi81r15L2/14Uwr08nThuSTAlHRoMwq3ddmsVcusTidkLOnLdeX4ZphIKyKDHXBIOKFQ0w2V/tcesrgyz1fIR9IPrlfzvUYNr2UkRgeQYd4kaGKvTbR2zFlvBKs8vw4Bj5Y0cFK3DG7mDo1dOYAaOJdhnsQavfMK47ArO9rfn9e4CTUybWskn5UUqgp3v4NJwHRnY4DBgIko9FfyXwuS57mEUr6eliNjXweKXol1mPQBNBLQzy42v9CffWTsMnCDZ5hhl7tEALsjBegCvWlQI1BE2RK1kHuXi3vbVeVPeoQ717eKyGejJ7WRAx9kAkwGCOCiCVddXcvH14hKiQIWzPe7PSLJzBBYielUfnuo%2B7ULbkpzp/HQpVGH1Ti5oX1%2B6FbKVKEfmjSIBDzJeC0eErkryRHRJrF/IJwpDkLE3/bbQbeqH6fl6YnDMpLXHjHThikn3kwXaB2THyU%3D')
```
