### ISSUE TITLE
g4f commandline interface

### ISSUE THREAD

**Issue by Simatwa** [xtekky/gpt4free#1553]
I just like the current Web-UI but as a terminal enthusiast I would find it much cool to interact with the AIs while still in terminal. It is due to this that actually fueled the motive behind creating [python-tgpt](https://github.com/Simatwa/python-tgpt). This tool plays a crucial role in achieving the same. Moreover, it features a dedicated command for explicitly interacting with providers happily offered by gpt4free. I had divided idea on submitting a pull request here while still retaining dependency on python-tgpt, of which will bring about dependency conflicts. So I ended up taking this route. Your idea will really help in deciding the way forward.

**Comment by hlohaus** [comment]
Thank you. You could add a link to the Readme.
