### ISSUE TITLE
Next Todos and Maybes

### ISSUE THREAD

**Issue by hlohaus** [xtekky/gpt4free#1556]
Please give Feedback :)

- New Google Bard provider without webdriver, but with image gen and upload ✅
- Update the provider list with the tool ✅
- Add a example for the image generator's in the readme ✅
- Remove required auth check for all providers or only for providers with webdriver login ✅
- Blog Post about g4f on Smartphone✅
- New Provider: https://chat.deepseek.com/coder
- Add Python API for creating images ✅

Maybes:
- CLI interface for ChatCompletion
- Python API like from OpenAi working ✅
- Better example for ChatCompletion / history support
- new API for Conversations / create conversation / too long message in OpenaiChat issue
- or/and Disable History Button in GUI ✅
- Auth for providers with GPT 4 and Auth: You ✅, Phind..
- Add more image gen providers
- Check and improve bot detection bypass for OpenaiChat ✅ and Bing
- Add provider: https://flowgpt.com/✅
- Remove allowed models check in Completion API?
- Bard Speech Api, OpenAi Speech Api
- Improve Error Messages:
-- MissingGoogleChromeError
-- MultipleWebDriverSessionError
-- TooLongMessageOpenAiError

Also should we add account generation? It is too silly? today, all providers with GPT 4 requiring a account.
- Added You provider with account generation ✅

**Comment by OmiiiDev** [comment]
If you need I have plenty image Gen providers that I reverse engineered

**Comment by hlohaus** [comment]
Hello, yes, please. I have image gen added to readme. With Gemini we have 3 providers.

**Comment by OmiiiDev** [comment]
Alright but it's a lot of lines of code and providers so how can I send it to you?

**Comment by hlohaus** [comment]
Can't you create a repo? Or you create a PR with your draft?

**Comment by hlohaus** [comment]
Okay, write me a Email to:
 heiner.loh789 (at) gmail.com

**Comment by OmiiiDev** [comment]
Alright will send the email asap

**Comment by OmiiiDev** [comment]
I emailed you with the code snippets

**Comment by hlohaus** [comment]
I have your email. I could copy your generate_image to g4f.Provider.NewImgGen and we a have new Provider. Good idea?

**Comment by OmiiiDev** [comment]
Yes sounds good

**Comment by OmiiiDev** [comment]
I reverse engineered a tts model, so if you need it I can send it aswell

**Comment by thangckt** [comment]
can you include references for Phind response

**Comment by hlohaus** [comment]
The provider g4f.Provider.Phind are working, but only they Phind model are supported.

**Comment by freedomforwhat** [comment]
Hello! Is it possible to add a check for a new version of the repository when starting the GUI and when starting any chat in the GUI?

**Comment by skoenig** [comment]
Would be really nice to include a small CLI tool to enter (or pipe) prompts to a model and receive the answer via the command line. Some basic options besides provider and language model could be: context ID (to pick up the conversation where you left), initial prompt, load and modify chat history.

**Comment by plia7** [comment]
> * CLI interface for ChatCompletion

Yes, @hlohaus is it possible to add CLI interface for ChatCompletion please? Thanks a great project.

**Comment by TungusSs** [comment]
Is it possible?
#1766

**Comment by thisisjerk** [comment]
Is it possible to include a conversation rename feature in the left panel?

**Comment by hlohaus** [comment]
Yeah, that's possible. I'm doing that.

**Comment by Hydra566** [comment]
I can suggest pollinations.ai as an image provider.

Images are generated quickly and the quality is good. Powered by SDXL.

Queries are also easy to create:
```
https://image.pollinations.ai/prompt/dog,%20high%20quality,%20high%20detail,%20hyperrealism,%208k,%2016k?width=1024&height=1024&seed=43&nofeed=true&nologo=true
``` 
![Dog](https://image.pollinations.ai/prompt/dog,%20high%20quality,%20high%20detail,%20hyperrealism,%208k,%2016k?width=1024&height=1024&seed=43&nofeed=true&nologo=true)

To get a new image, you need to replace seed=43 with any random number, for example seed=45645673457.

**Comment by MavisHoot** [comment]
Allow downloading of the read aloud audio

**Comment by hlohaus** [comment]
Hey, I just added a Pollinations.AI provider in g4f. You can use this provider in your environment now.

**Comment by Ggre55** [comment]
> I reverse engineered a tts model, so if you need it I can send it aswell

hey can u share not the code but just the sites u reversed 
i wanna try and crack it would be nice tnks

**Comment by hlohaus** [comment]
g4f supports tts:

 /v1/synthesize/Gemini?text=your text

**Comment by carryingwater** [comment]
@hlohaus Sora 2 and Veo3.1-fast error: "Missing_api_key" in `https://g4f.dev/v1` Custom Provider even after generating an api key.

**Comment by amirhossein8410h** [comment]
so i didnt get it what to do so that g4f generait photo for me can you explain pls
