### ISSUE TITLE
Please update pypi version & fix bugs

### ISSUE THREAD

**Issue by OmiiiDev** [xtekky/gpt4free#1558]
Nothing works anymore, when I try to talk with a model (using requests, not the gui, the gui and some models on the gui work) it doesn't work.
Also Liaobots doesnt work anymore for me...

**Comment by RasyiidWho** [comment]
Can you give us more detail and bug reproduction along w/ code?

**Comment by JaDenis** [comment]
i'd confirm this, no providers work anymore for like 2-3 days
happened to me after i decided to update
(New pypi version: 0.2.1.0 (current: 0.1.7.6) | pip install -U g4f)

**Comment by OmiiiDev** [comment]
Yes same here

**Comment by hlohaus** [comment]
For GPT 4 you need now a account on Phind, You..

I added today the Gemini provider.
