### ISSUE TITLE
Problem with Bing

### ISSUE THREAD

**Issue by Lanc1um** [xtekky/gpt4free#1559]
I get this message when I try to use Bing: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub?sec_access_token=aiYJQBhio9Iv0rDtFgf5P4gtOdiwcoEzMj/s/08L1kfywQgBVQvefflJ%2BlWXLxcplRXN/aixtcNwpShIILZX7epZubwgOA8%2BYqO0HfveZlFLNdC81neBIjU4VT/XOUT087Fr5VfLdwT20cFksPNVH75UVeNm8hIgHRWqDfJr1Aru2QGbqU6FyVqh4vuQIeEdy4xu0XNqcKVF3ezZ52vw4d8%2BHunyP5IGPmlpo1gi7eSdn5W7fiEhRTzY4yfT9keeSIlQ/h7uWdG4ov%2BMiFnOxSJkF1SaK%2B2hl/lVuXJA8XAjWEGvdpUMAbDZgWL1VHCH7rsZ0c8ZKb5WhzDOcD4hNPj2ZxAcGMzCe6zOrb7FsCmCisV9AVdAp183rMT7L9Ib/xdFzc9YeBoLB5C520bL6c8UKgIBrYdUQjgYQUB/BoNfU3ReU8ihowCcc1U7fRKpWnTbR528QwWr/gmVNz7FzOa7awwzyCxsCvxCj70StMZ5k6O7oCZVIwE0Q30jpm9uP0X2Ej/UgBeouKQlxb7VIbrLzyGvUN%2Btmwod82NBXdj4OEPh0mGKALVZEQOzFR2BMWayP4HBaWi22hYn4P3u%2BZdvZYXrx6Q4AzsOF04Eyoi/tdEY1v0yhB26/%2BID3b4yKlGDqisr9/7oCmtzKW/A7aBnT00z/2XorXkKe83lwzBpiBOqTN6Ws4TD3%2BaHcBL3cMphfcAfhFsyK57uT4yBmF%2BirCYRU9rKbTwDioKTC7MkepaD8idebtltWX6HQZX183HKRiKUkQEf7wYC5x7EFcFw%2BgMP7vFF/Mc2Whm6Es6owUt%2Bh4sQe/%2BHpojbw4cwL5x5gLkhE8vfD/JJ62wGJ0S9tBQpHQa4vnKducnZP%2B9R626/OWG7thQNHoHfEeEEEnvyXrs2i%2BqoL2L7%2BAdYAts9SMMHshyQpBybn/6DXwO2N1GhBVzoj40C3IkyPBHqYM/iivNivjvJxFhwBf%2B92TpxynSDzbk4/RX6EwMYAa0II3cm13TQTBLJRm3YfxxH7qljWRkgEtq8dg55cTajkidC13gWhDp124C/20w%2B5FUKGCEfAPF2VDHsXMefeRIfv/OkiWBERKHBThJRbw8rBPFaFNyHutSGOMPjMIVVWzC9wJ2Y0RkT4fT2F36LX7u/mYa6pgHj/lTs4tvTEKQbCbAJG83dV5e8rNCAdTHjNmJbFXDt7YN5ZI6yo39LCEzM0%2BXkWgLYmJV5CSyJD3xoDeN9jNtTJpXy/OX4rBIMVxM%3D')
It doesn't crash, just keep spamming this message in the console

**Comment by zestloveheart** [comment]
same problem

**Comment by Anybodyy** [comment]
Same problem
