### ISSUE TITLE
Is possibile to use the GPT4 API in AUTOGPT?

### ISSUE THREAD

**Issue by iSte94** [xtekky/gpt4free#156]
Hello, as title I'd like to know if is it possible to obtain a GPT4 API to use it in AUTOGPT.

Thanks

**Comment by rtisne** [comment]
@xtekky is currently working on an alternative for GTP 4, I will then test with this new version

**Comment by 9fo** [comment]
We are currently working on that all of the modules work with AutoGPT

**Comment by sebramirez44** [comment]
How are you guys getting data from gpt4free that autogpt can use? is there a request I need to make to the docker server that I'm not finding?

**Comment by thanhtoan1196** [comment]
any updates?
