### ISSUE TITLE
mathematical formulas

### ISSUE THREAD

**Issue by Lein000** [xtekky/gpt4free#1563]
Someone add support for mathematical formulas(Katex,MathJax) to the GUI, I tried, but nothing comes out due to streaming generation.

**Comment by hlohaus** [comment]
What do you need for that?
Did you try it with GPT 4 from Bing?

**Comment by Lein000** [comment]
they are not properly reflected
![Снимок экрана 2024-02-11 033328](https://github.com/xtekky/gpt4free/assets/157303952/77d7de13-f04b-4ba7-97a3-828e2db296f7)

**Comment by hlohaus** [comment]
I understand. I never used somethings like this before, but I could add it to the gui.

Should I create button for enabling it?
Should I add KaTex or MathJax?

**Comment by Lein000** [comment]
I think the button is not needed, since GPT only in the case of a formula encloses the text in $$ $$ mathjax, it will be easier to add a lot.

**Comment by Lein000** [comment]
Thank you, the formulas work fine, but maybe only I have, but there was a bug with scrolling when generating formulas, returns the window to the top.
