### ISSUE TITLE
[Gemini] ERROR:root:SNlM0e not found

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1576]
After rebooting the system and first run of gpt4free via `g4f gui`, cannot use the Gemini provider in any way whatever with the following error in the terminal, even after manually logging into Gemini in Chrome, Firefox, Edge.
But, after all these manipulations with manual login and relaunching gpt4free via `Ctrl+C` -> `g4f gui`, Gemini starts working OK.
```
Using Gemini provider and gpt-4 model
ERROR:root:SNlM0e not found
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 185, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\base_provider.py", line 201, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\needs_auth\Gemini.py", line 108, in create_async_generator
    raise RuntimeError("SNlM0e not found")
RuntimeError: SNlM0e not found
127.0.0.1 - - [11/Feb/2024 07:11:44] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Feb/2024 07:11:44] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by hlohaus** [comment]
SNlM0e not found: means you are not logged in.
You had maybe invalid cookies somewhere.
To solve this issue, you could start the g4f brower manually:
``
import time
from g4f import webdriver
driver = webdriver.get_browser()
try:
    driver.get("https://gemini.google.com/app")
    time.sleep(10000)
finally:
    driver.quit()
``
and log you in.

**Comment by iG8R** [comment]
Is it possible to insert this code into `Gemini.py` to avoid all these manual manipulations, as happens with OpenaiChat when g4f starts for the first time after OS boot?
```
107:	            else:
108:	                raise RuntimeError("SNlM0e not found")
```

**Comment by mrbuslov** [comment]
You should copy all of your cookies, that start with `__Secure-1PSID`
To find cookies, follow these steps:

- login into the account [gemini.google.com/app](https://gemini.google.com/app)
- F12 > Applications > Cookies > accounts... or gemini...  > Filter (input) > __Secure-1PSID

Example (insert it before `client.images.generate` as pointed in tutorial readme)
```
set_cookies(
    ".google.com",
    {
        "__Secure-1PSID": "g.a000hwiteqQb...0076",
        "__Secure-1PSIDCC": "AKEy...Xl8dc7g",
        "__Secure-1PSIDTS": "sidts-CjEB...SEAA"
    },
)
```
