### ISSUE TITLE
GeminiPro provider

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1579]
Hello.
Could you please add the GeminiPro provider from here https://ai.google.dev/docs/gemini_api_overview
Although it needs an API key, but it's quite easy to get, and the quality of this model, I don't know why, is much better than https://gemini.google.com/app
At least every time I try to request https://gemini.google.com/app for the translation of a large text, it responds with only confusing `我没法提供帮助。我只是一个语言模型，无法处理和理解这个问题。`
But when earlier I used https://ai.google.dev/docs/gemini_api_overview via the https://geminiprochat.com provider, whatever the size of the requested text was, it was always translated.

PS. BTW, https://geminiprochat.com stopped working with the error `[GoogleGenerativeAI Error]: Error fetching from [526 ]` in response to any request.

**Comment by hlohaus** [comment]
I added GeminiPro API as provider

**Comment by hypersad** [comment]
Avoid Gemini and use ChatGPT. It is wasting time on some bots keen on ethics detection than its primary purpose.
