### ISSUE TITLE
How use proxy

### ISSUE THREAD

**Issue by SN4RK** [xtekky/gpt4free#1588]
Использую контейнер hlohaus789/g4f:latest. Как мне использовать прокси для gpt? Условно при создании контейнера я прописываю `docker run -p 8080:8080 -p 1337:1337 -p 7900:7900 --shm-size="2g" hlohaus789/g4f:latest`. Видел что добавили -e G4F_PROXY=.... Но когда запускаю докер выдает ошибку 

> (HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-e": executable file not found in $PATH: unknown
 
Если это делается не так, буду благодарен за небольшую инструкцию.

**Comment by houtarchat-cyber** [comment]
The most common error is that the -e argument is incorrectly placed at the end of the command.
A proper docker run command should look similar to the following format:
docker run -p 8080:8080 -p 1337:1337 -p 7900:7900 -e G4F_PROXY=..... --shm-size="2g" hlohaus789/g4f:latest
Check your docker run command to make sure that the -e parameter is used correctly. You may need to give the full run command out.

---

Самая распространенная ошибка заключается в том, что аргумент -e неправильно расположен в конце команды.
Правильная команда docker run должна выглядеть следующим образом:
docker run -p 8080:8080 -p 1337:1337 -p 7900:7900 -e G4F_PROXY=..... --shm-size="2g" hlohaus789/g4f:latest
Проверьте команду docker run, чтобы убедиться, что параметр -e используется правильно.

**Comment by AndPim4912** [comment]
Maybe
proxychains g4f api ...
https://github.com/haad/proxychains
