### ISSUE TITLE
"Failed Captcha" Response from ChatBase Provider

### ISSUE THREAD

**Issue by AHiXilTOr** [xtekky/gpt4free#1589]
**Bug Description**

When making a request to the ChatBase provider API in Python, the `captchaCode` parameter suddenly stopped functioning correctly. Instead of receiving the expected response, the API returns `b'{"message":"Failed Captcha"}'`.

**Environment**
- Python version: Any
- Location: Any

**Steps to Reproduce**
1. Execute the script that sends a request to the ChatBase provider.
2. Observe the response received from the API, which returns `b'{"message":"Failed Captcha"}'`.

**Additional Context**
- This issue was not observed previously and has arisen suddenly.
- No changes were made to the code handling the `captchaCode` parameter or the API request.
- Attempts to troubleshoot the issue by checking network connectivity, API documentation, and request parameters have been unsuccessful.
- The issue persists even after retrying the request multiple times.

**Comment by maxkonushev** [comment]
Now there's cloudflare turnstile invisible protection
