### ISSUE TITLE
Image generation Bing

### ISSUE THREAD

**Issue by SN4RK** [xtekky/gpt4free#1590]
На запрос "Create image wolf" (как и на любой другой) получаю ответ:

`![wolf](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAABmklEQVR4nO3BMQEAAADCoPVPbQhfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA....`

Использую контейнер hlohaus789/g4f

![Безымянный (1)](https://github.com/xtekky/gpt4free/assets/97697782/e3e5bef1-1af0-4184-aad3-445f51b5716f)

**Comment by hlohaus** [comment]
I improved the system message for create images. Please test agin

**Comment by SN4RK** [comment]
![error](https://github.com/xtekky/gpt4free/assets/97697782/6e823232-3609-4957-8eb3-10702a031cb3)
![promt](https://github.com/xtekky/gpt4free/assets/97697782/22cd1000-cc45-4518-923f-d1b4a267ddf0)
![promt2](https://github.com/xtekky/gpt4free/assets/97697782/0a4f42a5-8310-4be3-b993-d2da652b04dd)

**Comment by hlohaus** [comment]
You have to start a new conversation after the update
