### ISSUE TITLE
A lot of providers are not working

### ISSUE THREAD

**Issue by Def-Try** [xtekky/gpt4free#1594]
**Bug description**
Basically, literally no good provider responds to my requests.
(see screenshot)

**Screenshots**
![изображение](https://github.com/xtekky/gpt4free/assets/71168720/6ef36e65-f0cc-4765-abb6-3a61c60c70d7)

**Environment**
- python version: 3.10.12
- location: russia, but some providers were working before, so i don't think it's cloudflare

**Additional context**

**Comment by Der4ik0** [comment]
Локация РФ недоступна почти у многих провайдеров, либо используйте LiaBots либо поставьте на хостинг США

**Comment by Def-Try** [comment]
argh alright. thanks for explaining
