### ISSUE TITLE
Здравствуйте, как правильно экранировать GPT 4 от bing 

### ISSUE THREAD

**Issue by Der4ik0** [xtekky/gpt4free#1595]
Как правильно экранировать gpt 4 от bing чтобы на вопросы по химии и физике он отвечал не так как в примере ниже, а нормальными словами:
Я: напиши формулу азот плюс углерод
gpt: Конечно! Вот формула для азота (N) и углерода (C):

$$
`\text{Азот} + \text{Углерод} = \text{Органическое вещество}`
$$

Надеюсь, это поможет вам! Если у вас есть еще какие-либо вопросы, не стесняйтесь спрашивать. 😊

Я: Напиши формулу работы физика
GPT:
Конечно! Вот формула для вычисления работы в физике:

```
$$
\text{Работа (W)} = \text{Сила (F)} \cdot \text{Расстояние (d)} \cdot \cos(\theta)
$$
```

```
Где:
- Работа (W) измеряется в джоулях (Дж).
- Сила (F) представляет собой приложенную силу в направлении движения.
- Расстояние (d) - это перемещение объекта в направлении силы.
- $\theta$ - угол между направлением силы и направлением перемещения.
```

Надеюсь, это поможет вам! Если у вас есть еще какие-либо вопросы, не стесняйтесь спрашивать. 😊

**Comment by VadimBoev** [comment]
Привет. Мне помогло добавление https://github.com/goessner/markdown-it-texmath

**Comment by Der4ik0** [comment]
Привет, спасибо, а как правильно применить это python aiogram?

**Comment by VadimBoev** [comment]
> Привет, спасибо, а как правильно применить это python aiogram?

без понятия

**Comment by AndPim4912** [comment]
> python aiogram

Очень просто. Пишешь в gpt. Предложи python код для выполнения [твоя идея] c использованием aiogram

**Comment by iG8R** [comment]
Что-то последнее обновление хоть и говорит, что исправило проблему с отображением формул, но всё равно не всегда с этим справляется.
![image](https://github.com/xtekky/gpt4free/assets/11407417/8b8b5f79-b64c-4f28-86f6-c67e2dcde386)
![image](https://github.com/xtekky/gpt4free/assets/11407417/9b5f0b14-0049-49f5-ae77-126b505e638f)

**Comment by hlohaus** [comment]
I added mathJax support some days ago
