### ISSUE TITLE
Gemini prochat provider

### ISSUE THREAD

**Issue by feedain9** [xtekky/gpt4free#1596]
It seems that geminiprochat.com is down, so i found an other provider : https://gemini-chatbot-sigma.vercel.app/

I try to reverse it but it seems that the signature type has been modified in comparison to geminiprochat.com...

**Comment by OmiiiDev** [comment]
I Also found a provider, seems easy to reverse engineer, because the Gemini google API key is getting leaked...

**Comment by feedain9** [comment]
> I Also found a provider, seems easy to reverse engineer, because the Gemini google API key is getting leaked...

Can you share the provider link ?

**Comment by feedain9** [comment]
> so to all the maintainers, take the existing GeminiProChat provider and replace the URL with "https://gemini-chatbot-sigma.vercel.app/api/generate" to fix it since they're essentially same websites with same frontends and backends

It doesn't work, It return 401 with "incorrect signature"

**Comment by iG8R** [comment]
```
Using GeminiProChat provider
ERROR:root:401, message='Unauthorized', url=URL('https://gemini-chatbot-sigma.vercel.app/api/generate')
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\base_provider.py", line 205, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\base_provider.py", line 201, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\GeminiProChat.py", line 50, in create_async_generator
    response.raise_for_status()
  File "c:\gpt4free\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1059, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://gemini-chatbot-sigma.vercel.app/api/generate')
127.0.0.1 - - [18/Feb/2024 15:12:37] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 15:12:37] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by piotr25691** [comment]
> > so to all the maintainers, take the existing GeminiProChat provider and replace the URL with "[gemini-chatbot-sigma.vercel.app/api/generate](https://gemini-chatbot-sigma.vercel.app/api/generate)" to fix it since they're essentially same websites with same frontends and backends
> 
> It doesn't work, It return 401 with "incorrect signature"

well someone must edit it then, i close PR

**Comment by iG8R** [comment]
Here is the fixed working version of the `GeminiChatPro (gemini-chatbot-sigma.vercel.app)` provider.
Save it as `GeminiProChat.py` and replace the old one.
```
from __future__ import annotations

import time
from hashlib import sha256
from aiohttp import ClientSession

from ..typing import AsyncResult, Messages
from .base_provider import AsyncGeneratorProvider


class GeminiProChat(AsyncGeneratorProvider):
    url = "https://gemini-chatbot-sigma.vercel.app"
    working = True
    supports_gpt_35_turbo = True

    @classmethod
    async def create_async_generator(
        cls,
        model: str,
        messages: Messages,
        proxy: str = None,
        **kwargs
    ) -> AsyncResult:
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0",
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate, br",
            "Content-Type": "text/plain;charset=UTF-8",
            "Referer": "https://gemini-chatbot-sigma.vercel.app/",
            "Origin": "https://gemini-chatbot-sigma.vercel.app",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "Connection": "keep-alive",
            "TE": "trailers",
        }
        async with ClientSession(headers=headers) as session:
            timestamp = int(time.time() * 1e3)
            data = {
                "messages":[{
                    "role": "model" if message["role"] == "assistant" else "user",
                    "parts": [{"text": message["content"]}]
                } for message in messages],
                "time": timestamp,
                "pass": None,
                "sign": generate_signature(timestamp, messages[-1]["content"]),
            }
            async with session.post(f"{cls.url}/api/generate", json=data, proxy=proxy) as response:
                response.raise_for_status()
                async for chunk in response.content.iter_any():
                    yield chunk.decode()
                        
def generate_signature(time: int, text: str, secret: str = ""):
    message = f'{time}:{text}:{secret}';
    return sha256(message.encode()).hexdigest()
```

**Comment by piotr25691** [comment]
> Here is the fixed working version of the `GeminiChatPro (gemini-chatbot-sigma.vercel.app)` provider. Save it as `GeminiProChat.py` and replace the old one.
> 
> ```
> from __future__ import annotations
> 
> import time
> from hashlib import sha256
> from aiohttp import ClientSession
> 
> from ..typing import AsyncResult, Messages
> from .base_provider import AsyncGeneratorProvider
> 
> 
> class GeminiProChat(AsyncGeneratorProvider):
>     url = "https://gemini-chatbot-sigma.vercel.app"
>     working = True
>     supports_gpt_35_turbo = True
> 
>     @classmethod
>     async def create_async_generator(
>         cls,
>         model: str,
>         messages: Messages,
>         proxy: str = None,
>         **kwargs
>     ) -> AsyncResult:
>         headers = {
>             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0",
>             "Accept": "*/*",
>             "Accept-Language": "en-US,en;q=0.5",
>             "Accept-Encoding": "gzip, deflate, br",
>             "Content-Type": "text/plain;charset=UTF-8",
>             "Referer": "https://gemini-chatbot-sigma.vercel.app/",
>             "Origin": "https://gemini-chatbot-sigma.vercel.app",
>             "Sec-Fetch-Dest": "empty",
>             "Sec-Fetch-Mode": "cors",
>             "Sec-Fetch-Site": "same-origin",
>             "Connection": "keep-alive",
>             "TE": "trailers",
>         }
>         async with ClientSession(headers=headers) as session:
>             timestamp = int(time.time() * 1e3)
>             data = {
>                 "messages":[{
>                     "role": "model" if message["role"] == "assistant" else "user",
>                     "parts": [{"text": message["content"]}]
>                 } for message in messages],
>                 "time": timestamp,
>                 "pass": None,
>                 "sign": generate_signature(timestamp, messages[-1]["content"]),
>             }
>             async with session.post(f"{cls.url}/api/generate", json=data, proxy=proxy) as response:
>                 response.raise_for_status()
>                 async for chunk in response.content.iter_any():
>                     yield chunk.decode()
>                         
> def generate_signature(time: int, text: str, secret: str = ""):
>     message = f'{time}:{text}:{secret}';
>     return sha256(message.encode()).hexdigest()
> ```

here is the GeminiProChat.diff file to apply the patch:

```diff
12c12
<     url = "https://geminiprochat.com"
---
>     url = "https://gemini-chatbot-sigma.vercel.app"
25c25
<             "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0",
---
>             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0",
27c27
<             "Accept-Language": "de,en-US;q=0.7,en;q=0.3",
---
>             "Accept-Language": "en-US,en;q=0.5",
30,31c30,31
<             "Referer": "https://geminiprochat.com/",
<             "Origin": "https://geminiprochat.com",
---
>             "Referer": "https://gemini-chatbot-sigma.vercel.app/",
>             "Origin": "https://gemini-chatbot-sigma.vercel.app",
54,55c54,55
< def generate_signature(time: int, text: str):
<     message = f'{time}:{text}:9C4680FB-A4E1-6BC7-052A-7F68F9F5AD1F';
---
> def generate_signature(time: int, text: str, secret: str = ""):
>     message = f'{time}:{text}:{secret}';
```

**Comment by iG8R** [comment]
@piotr25691 
It'd be better you correct your PR.

**Comment by piotr25691** [comment]
> @piotr25691 It'd be better you correct your PR.

Let me fix it
