### ISSUE TITLE
More meaningful explanation of what exactly the error is instead of "An error occurred, please try again..." in the WebUI

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1599]
Is there a way to make explanations more meaningful of what exactly the error is instead of "An error occurred, please try again..." in the WebUI, like in the console?

**Comment by hlohaus** [comment]
The error message are printed in the browser console. But I look mostly only in the terminal log.

**Comment by iG8R** [comment]
Oh... I forgot about the browser console. But it would be great, if a more meaningful explanation also would be present in the WebUI.
I also prefer to look at errors in the terminal, but my question arose after I started to use g4f on another computer on my LAN and was unable to figure out why this or that error occurs.

**Comment by hlohaus** [comment]
But you can look in the browser console on the other PC? I don't like to see such error messages in the gui

**Comment by iG8R** [comment]
Yes, I can look into the browser console log, but it's such a hassle... going through all the console log, whereas if there was a meaningful explanation in the WebUI, it would immediately show the cause of the issue, and there would be no need to be Sherlock Holmes.
All the more so, the errors aren't saved in the conversation history anyway.

**Comment by nitianVSdahuai** [comment]
Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by iG8R** [comment]
@hlohaus 
Thank you so much!
