### ISSUE TITLE
Some dialogs disappear after reloading the coversation

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1602]
The title says for itself.

Initial conversation:
![image](https://github.com/xtekky/gpt4free/assets/11407417/3ae0004e-2ec1-4a5b-8774-3f780b567909)

After reloading the conversation:
![image](https://github.com/xtekky/gpt4free/assets/11407417/4a6ce86e-548a-4043-8ffe-edb4a3746384)

**Comment by hlohaus** [comment]
If you use regenerate, it removes the last answer from the history. It is required for proper results. Also it will always show only the last response.

**Comment by iG8R** [comment]
> But error messages can be disappear?

Error messages? I didn't see any in the console or WebUI.

**Comment by hlohaus** [comment]
😁 I use regenerate mostly for failed messages.

I am good in solving bugs, but also I create sometimes bugs

**Comment by hlohaus** [comment]
I improved the dialogs in gui.
Messages should not disappear anymore.
Also i added a remove message option.
#1622
