### ISSUE TITLE
New client error

### ISSUE THREAD

**Issue by long202258** [xtekky/gpt4free#1605]
from g4f.client import Client
from g4f.Provider import BingCreateImages, OpenaiChat, Gemini

client = Client(
    provider=OpenaiChat,
    image_provider=Gemini,
    proxies=None
)
stream = client.chat.completions.create(
    model="gpt-4",
    messages=[{"role": "user", "content": "Say this is a test"}],
    stream=True,
)
for chunk in stream:
    if chunk.choices[0].delta.content:
        print(chunk.choices[0].delta.content, end="")

NestAsyncioError: Use "create_async" instead of "create" function in a running event loop. Or use "nest_asyncio" package.

**Comment by hlohaus** [comment]
import nest_asyncio
nest_asyncio.apply()

Add this lines to your code.
