### ISSUE TITLE
Yandex GPT 2

### ISSUE THREAD

**Issue by V1RUSnya** [xtekky/gpt4free#1606]
Could you add Yandex GP2 to the list of providers? Especially important for Russians
https://ya.ru/ai/gpt-2?utm_source=portal&utm_medium=yagpt2&utm_content=mainbanner&yclid=15611831662307442687 - about
https://a.ya.ru/ - site

**Comment by hlohaus** [comment]
I don't found a web version from Alice. I found only a app for phone's.

**Comment by V1RUSnya** [comment]
It hides on Yandex pages - for example, in the lower right corner of www.ya.ru (purple circle)
P.s This is not its only application; in Russia it is built into stationary speakers, televisions and smart homes, etc.

You can also try to interact with Api (requires ya.mail registration)
https://cloud.yandex.ru/ru/services/yandexgpt

**Comment by hlohaus** [comment]
I can't create me a account for the API. Maybe it don't like my german credit card.

**Comment by Lein000** [comment]
https://ya.ru/alisa_davay_pridumaem?utm_source=landing

**Comment by Lein000** [comment]
It should be easy. Registration is not required
