### ISSUE TITLE
Sometimes the answer comes cropped

### ISSUE THREAD

**Issue by BokDan93** [xtekky/gpt4free#1607]
Hello everyone. Guys, what to do when the answer comes cropped. For example, the text may break off in mid-word or 2 sentences with a cut word at the end are sent at all.How to get a complete answer and how to deal with such a situation? I use both gpt 3.5 and 4

**Comment by iG8R** [comment]
You need to show more info - debug log from the console, examples of requests and texts, what provider and model are you using.

**Comment by hlohaus** [comment]
Not all providers support long responses. This I create the pseudo model gpt_35_long.
