### ISSUE TITLE
[OpenaiChat] Adding the 'system' role

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1612]
Could you please add the `system` role to the `OpenaiChat` provider and other `gpt`-compatible providers with the corresponding field in the WebUI.
https://platform.openai.com/docs/guides/text-generation

**Comment by hlohaus** [comment]
You can set globally a system message in OpenAI Chat, but not for a conversation. By default the system message are added to the user message with System: and then the message. But if you write: Instructions: and then the system message, it should works better.

**Comment by iG8R** [comment]
E.g. if I need OpenaiChat to translate some text with the system message, i have to write the following in the prompt field?
`Instructions: You are a professional, authentic translation engine, only returns translations. Translate the following text to English: /here is some text/`
But how OpenaiChat separate `Instructions:` from `Translate the following text to English:`?

**Comment by hlohaus** [comment]
There is no reason to separate it. It is also a instruction. But between the instructions and the text, you should add 2 or 3 line breaks.

**Comment by hlohaus** [comment]
Why you are using not the API from OpenAI? I can't change companys

**Comment by iG8R** [comment]
> Why you are using not the API from OpenAI?

What do you mean? I exactly try to use OpenAI API - https://help.openai.com/en/articles/7042661-moving-from-completions-to-chat-completions-in-the-openai-api - which postulates:

**`You can also use a system level instruction to guide the model's behavior throughout the conversation. `**

There is also a man here who was wondering the same thing - https://community.openai.com/t/understanding-role-management-in-openais-api-two-methods-compared/253289

**Comment by hlohaus** [comment]
OpenaiChat use not the Chat API. It use the Frontend of chat.openai.com, because it is free. You can use system messages only with the paid API.

**Comment by iG8R** [comment]
IMHO, it's not quite like that.
I use following apps to translate texts using g4f as an API proxy:
1. pot-desktop https://github.com/pot-app/pot-desktop
2. immersive-translate https://github.com/immersive-translate/immersive-translate/

Here are their settings, which differ only in the `system` fields:
<img src="https://github.com/xtekky/gpt4free/assets/11407417/05280638-352d-424a-bc6f-d60bce2667ee" width="350"> <img src="https://github.com/xtekky/gpt4free/assets/11407417/1ac397f3-2574-4966-8112-a3a21e9df8fe" width="350">

But, the translation differs in meaning and fluent in some places quite a lot.
![image](https://github.com/xtekky/gpt4free/assets/11407417/b1e189eb-c017-43df-b035-bc87cf40895f)

**Comment by hlohaus** [comment]
I added a message history and system message support to OpenaiChat.
I convert now the messages for the Chat API.

**Comment by nullstreak** [comment]
@hlohaus Custom instructions from the web app are transferred to the G4F. Is this intended behavior?

**Comment by hlohaus** [comment]
It is a excepted behavior. It is the Web API.

**Comment by iG8R** [comment]
Is it possible to add a `message` support into the WebUI?
So that there are 2 separate text input fields for `message` and for `user`.

**Comment by iG8R** [comment]
Like in LiaobotsUI

![image](https://github.com/xtekky/gpt4free/assets/11407417/6b85df53-9f8f-4f85-8551-6b673b19c061)

**Comment by iG8R** [comment]
Thank you very much!
