### ISSUE TITLE
Word count, token count, tokens used in the WebUI like in Chatbox

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1614]
Is it possible to implement the same feature as in Chatbox (https://chatboxai.app https://github.com/Bin-Huang/chatbox), where the following additional info about the dialogs is displayed: word count, token count and tokens used?

<img src="https://github.com/xtekky/gpt4free/assets/11407417/54a340c8-1966-4c31-bc49-aed999e0984a" width="550">

**Comment by hlohaus** [comment]
I addded word count and token count to messages. also i added a total token count.

The total token count use the gpt-3 way.
The message token count use the used model way.
currently llama2, mistral and gpt are supported.

**Comment by hlohaus** [comment]
I released it now

**Comment by iG8R** [comment]
Thanks a lot!
