### ISSUE TITLE
cf_clearance token  error

### ISSUE THREAD

**Issue by PhoenixNil** [xtekky/gpt4free#162]
when I run your app in the docker the website show An error occured, please make sure you are using a cf_clearance token and correct useragent | cf_clearance must be set, refer to documentation
![image](https://user-images.githubusercontent.com/33974040/234654418-0e67e0c4-3e68-4e82-ab5d-b85d8b325210.png)

**Comment by Perl404** [comment]
same

**Comment by MilianDevOps** [comment]
same

**Comment by plinkr** [comment]
You can find more information about it here:
#153

**Comment by 123jimenez99** [comment]
> You can find more information about it here: #153

Oh... Thanks for guiding us in what is going on at the moment, I'll be following #153 closely now on

**Comment by xtekky** [comment]
#153
