### ISSUE TITLE
Unauthorized bug

### ISSUE THREAD

**Issue by Baldi89989** [xtekky/gpt4free#1624]
**Bug description**
I'm recreating the chatbot AI discord (clyde) using this library. I make it uses gpt 4 (because gpt 3.5 doesn't work) with the role system modified so that it acts like the real clyde. All goes well, the bot responds. However, I get errors such as "Payment Required" or "Internal Server Error", but also "Unauthorized". When I get "Unauthorized", I have to restart my computer to get it to work again. For the other errors, I have to restart my code and it works. The api is liaobots, could you fix this error and prevent me from restarting my computer when I get the "unauthorized" error? is there a solution? Because these errors annoy me a lot. Bye.

**Environment**
Python version: 3.12.1

**Comment by hlohaus** [comment]
The API usage of some providers are limited. Try a other working providers from the list.
