### ISSUE TITLE
When using Bing provider, response stops after ":" sign and doesnt print anything on enumeration

### ISSUE THREAD

**Issue by artizzq** [xtekky/gpt4free#1626]
**Bug description**

ex.
1. Chose 'Bing' provider
2. Use very big text (few A4 pages) as reference and write a question for it (for e.g. generate me N ideas of 'bla-bla')
3. Wait for response
4. See that after it starts making enumeration it doesnt print anything (cursor flashes and stops after ":" sign and nothing prints)

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/56273839/c5046eec-14d0-4743-8146-9f03a5edd3f5)
![problem](https://github.com/xtekky/gpt4free/assets/56273839/e494e337-7412-4ce9-acb3-ffe87a1adb23)

I wait too much so I aborted answer generation because nothing is printed after
This is what inside cmd window
![image](https://github.com/xtekky/gpt4free/assets/56273839/1a1c7575-7e1e-4103-868e-0764276ad2fe)

**Environment**
- Python 3.8

**Comment by hlohaus** [comment]
I fixed a issue with the courser and ul li lists
Maybe it was this
