### ISSUE TITLE
Wrong host in "Please login: " url

### ISSUE THREAD

**Issue by zavaruev** [xtekky/gpt4free#1628]
In web gui at 8080 port of docker container when you need to login to for example Google Gemin you get url with localhost instead of docker container ip/hostname. See attached image.
![Screenshot_20240224_221458](https://github.com/xtekky/gpt4free/assets/29773394/d44d922c-5f5d-4bb1-8333-b4dea666cc1e)

**Comment by hlohaus** [comment]
You could change the ENV in your docker.
The name is G4F_LOGIN_URL i think.
