### ISSUE TITLE
[GeminiPro] "User location is not supported for the API use" workaround

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1629]
Is there any way to implement workarounds for the "User location is not supported for the API use" issue in GeminiPro for those in geo-restricted countries, which are described here 
https://stackoverflow.com/questions/77659552/google-generative-ai-api-error-user-location-is-not-supported-for-the-api-use ?

**Comment by feedain9** [comment]
You need a proxy or a vpn in the country which are allowed by Google Gemini

**Comment by iG8R** [comment]
Sure, I already use Netlify as a proxy, but it would be way more convenient if g4f had native support to workaround this issue.

**Comment by hlohaus** [comment]
The proxy support is the native way. ?

**Comment by iG8R** [comment]
:) I meant that if g4f could access the GeminiPro API through VertexAPI, that would be considered the native way.

**Comment by hlohaus** [comment]
I can't create a Vertex Account for me. Sorry

**Comment by iG8R** [comment]
Thank you.
I'll try it and report later.
