### ISSUE TITLE
Token limit exceeded, please start a new conversation

### ISSUE THREAD

**Issue by QueenUlyana** [xtekky/gpt4free#163]
How do I continue to communicate? How do I turn off the limit?
https://chat.chatbot.sex/chat/

![2023-04-26_202742](https://user-images.githubusercontent.com/83131824/234656985-234d3340-5e77-4484-b20b-50bf6c945619.png)

**Comment by xtekky** [comment]
just start a new conversation as indicateed...

**Comment by QueenUlyana** [comment]
I don't want a new one, I want to continue this one.


> just start a new conversation as indicateed...
