### ISSUE TITLE
Gemini image generation URL

### ISSUE THREAD

**Issue by Cha14ka** [xtekky/gpt4free#1631]
How to download with requests the image that is returned in the example from README? It requires google authorization to see what is in the link

```python
client = Client()
response = client.images.generate(
  model="gemini",
  prompt="a white siamese cat",
)
image_url = response.data[0].url
#image = requests.get(image_url).content
```

**Comment by hlohaus** [comment]
I added already the resolving of images links. How do you use the provider? Do you send all cookies?

**Comment by Cha14ka** [comment]
I use provider just like in example. It returns url what I cant open without login in google account. 
Tried with cookies but it didnt help
```python
cookies = g4f.Provider.helper.get_cookies('.google.com', False, True)
requests.get(url, cookies=cookies)
```
https://imgur.com/a/MCcG6Vc

**Comment by Cha14ka** [comment]
Didnt work until I did 

```python
cookies = get_cookies(".google.com", False, True)
del cookies['__Secure-OSID']
del cookies['OSID']
del cookies['ACCOUNT_CHOOSER']
```

**Comment by hlohaus** [comment]
I don't have this cookies. But good to know.
