### ISSUE TITLE
Tokens and words in real time

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1639]
Is it possible to implement displaying token and word counts in real time as the text is being typed like on https://aistudio.google.com/app/prompts/new_chat

[gf4-live-tokens-2024-02-28_15-58-58.webm](https://github.com/xtekky/gpt4free/assets/11407417/874e2472-be9e-477c-a552-b7875dc8b6d9)

**Comment by hlohaus** [comment]
Good idea. Also the total are wrong. It don't count the answer.

**Comment by iG8R** [comment]
Why not combine two approaches - show the number of tokens in real time when the user enters text, and when the AI gives an answer, use the mechanism that is currently available?
It is just that sometimes it needs to know if the text being sent exceeds a certain number of tokens or words, so as not to cause an error or truncation of the response.

**Comment by iG8R** [comment]
Thank you very much!
But something is off with the token calculation when using

**OpenaiChat**:

1st session
![image](https://github.com/xtekky/gpt4free/assets/11407417/0daa2864-f14c-4f86-9da1-606b8aff32fb)


2nd session
<img src="https://github.com/xtekky/gpt4free/assets/11407417/7345e7a2-1a97-47da-ae73-a3024ffe242a" width="350">

![image](https://github.com/xtekky/gpt4free/assets/11407417/d609ba7a-b972-4daf-80cf-e4ceae9bb64f)

![image](https://github.com/xtekky/gpt4free/assets/11407417/20c3f06f-44b0-4263-97c2-03800a4500da)

**GeminiPro:**

![image](https://github.com/xtekky/gpt4free/assets/11407417/39bc0493-f009-4413-bde6-2e58c381b47a)

Could you please add a character count, as Asian languages use a different text counting mechanism:

![image](https://github.com/xtekky/gpt4free/assets/11407417/80e98c5b-f31d-4fbe-821c-7d7e977f29c2)

**Comment by iG8R** [comment]
At the same time on https://aistudio.google.com/app/prompts/new_chat

![image](https://github.com/xtekky/gpt4free/assets/11407417/24b5b09b-4512-4077-979a-5b2777f8002b)

**Comment by hlohaus** [comment]
It show the count for the complete chat. Like OpenAI it does. Start message token + message tokens + end message token + role token + new line token or

Each message +4 or +5 tokens.

**Comment by hlohaus** [comment]
Ok. It is right or wrong? I used the code from stackoverflow, when I search for word count from chinese and english with JavaScript.

**Comment by hlohaus** [comment]
I could add this word count for you:

https://github.com/thecodrr/alfaaz

**Comment by iG8R** [comment]
Thank you very much! It would be great!
Please have a look at https://koala.sh/tools/free-gpt-tokenizer - it is the most correct tokenizer I could find, it can also accurately highlight characters.
There is also https://platform.openai.com/tokenizer, but it can't count words.

**Comment by hlohaus** [comment]
I use gpt-tokenizer too.
I can't highlight them because the markdown render.
I am working at the word count.

**Comment by iG8R** [comment]
Unfortunately, the update in version 0.2.2.8 still doesn't work properly.

Example from https://koala.sh/tools/free-gpt-tokenizer:
<img src="https://github.com/xtekky/gpt4free/assets/11407417/3e6a885e-cc30-432a-8028-884252662b40" width="350">

And here is my UserScript:
<img src="https://github.com/xtekky/gpt4free/assets/11407417/c481b56f-3658-4ee8-9f5a-7124d807c7b3" width="350">

Here is the source code of the UserScript (Tampermonkey ):
```
// ==UserScript==
// @name         OpenAI Tokenizer
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Automatically count tokens, all characters, characters excluding punctuation and spaces, and words of the selected text, including Chinese. Based on https://update.greasyfork.org/scripts/484043/OpenAI%20Token%20Counter%20for%20Selected%20Text.user.js
// @author       iG8R
// @match        *://*/*
// @grant        none
// @require      https://unpkg.com/gpt-tokenizer/dist/cl100k_base.js
// @downloadURL
// @updateURL
// ==/UserScript==

(function() {
    'use strict';

    // Creating a pop-up window
    const popup = document.createElement('div');
    popup.id = 'TokenCounter';
    // "white-space: pre" is necessary for \n work
    //popup.style.whiteSpace = 'pre';
    popup.style.display = 'none';
    popup.style.width = '190px';
    popup.style.lineHeight = '1.3';
    popup.style.position = 'fixed';
    popup.style.right = '20px';
    popup.style.bottom = '300px';
    popup.style.backgroundColor = '#333';
    popup.style.color = '#fff';
    popup.style.padding = '10px';
    popup.style.borderRadius = '5px';
    popup.style.zIndex = '1001';
    document.body.appendChild(popup);

    // Functions to display tokens and etc.
    // (wordsCount ? wordsCount.length : 0) and (charsCount ? charsCount.length : 0) are mandatory
    // otherwise an error will occur if only punctuation marks are selected
    function showTokenCount(tokensCount, wordsCount, charsCount, allcharsCount) {
        popup.innerHTML = `
        <div style="display: flex; justify-content: space-between;">
            <div>Tokens:</div>
            <div>${tokensCount ? tokensCount.length : 0}</div>
        </div>
        <div style="display: flex; justify-content: space-between;">
            <div>All chars:</div>
            <div>${allcharsCount ? allcharsCount.length : 0}</div>
        </div>
        <div style="display: flex; justify-content: space-between;">
            <div>Chars(letters):</div>
            <div>${charsCount ? charsCount.length : 0}</div>
        </div>
        <div style="display: flex; justify-content: space-between;">
            <div>Words:</div>
            <div>${wordsCount ? wordsCount.length : 0}</div>
        </div>
        `;
        popup.style.display = 'block';
    }

    // Calculate and display the number of tokens for the selected text
    function countAndShowTokens(selectedText) {
        if (selectedText) {
        // Count tokens
            const tokensCount = GPTTokenizer_cl100k_base.encode(selectedText);
        // Count words
            const wordsCount = selectedText.trim().match(/[\w\u4E00-\u9FA5]+/gu);
        // Count characters excluding punctuation and spaces
            const charsCount = selectedText.match(/[^\s\p{P}]/gu) || [];
        // Count all characters
            const allcharsCount = selectedText;
            showTokenCount(tokensCount, wordsCount, charsCount, allcharsCount);
            checkSelection(); // Check if the text is still selected
        } else {
            popup.style.display = 'none'; // If no text is selected, no popup window is displayed
        }
    }

    // Check if any text is still selected
    function checkSelection() {
        const checkInterval = 500; // Check every 500ms
        const interval = setInterval(() => {
            let currentSelection = ''; //window.getSelection().toString();
            if (document.activeElement.tagName !== 'TEXTAREA') {
                currentSelection = window.getSelection().toString();
            } else {
                const textarea = document.activeElement;
                currentSelection = textarea.value.substring(textarea.selectionStart, textarea.selectionEnd);
             }
            if (!currentSelection) {
                popup.style.display = 'none';
                clearInterval(interval); // discontinue
            }
        }, checkInterval);
    }

    // Adding Event Listeners to Documents to Detect Text Selection
    document.addEventListener('selectionchange', function() {
        if (document.activeElement.tagName !== 'TEXTAREA') {
            const selectedText = window.getSelection().toString();
            countAndShowTokens(selectedText); // Called when the text is selected.
        }
    });

    const textareas = document.querySelectorAll('textarea');
    textareas.forEach(textarea => {
        textarea.addEventListener('selectionchange', function() {
            if (document.activeElement.tagName === 'TEXTAREA') {
                const selectedText = textarea.value.substring(textarea.selectionStart, textarea.selectionEnd);
                countAndShowTokens(selectedText);
            }
        });
    });

})();
```

**Comment by hlohaus** [comment]
I added you count words and i added system messages to gui

**Comment by iG8R** [comment]
Thanks!
Could you please add also add the number of characters excluding punctuation and spaces?
```
// Count characters excluding punctuation and spaces
const charsCount = selectedText.match(/[^\s\p{P}]/gu) || [];
```

since for the Asian languages it seems a bit odd to count words like this:

![image](https://github.com/xtekky/gpt4free/assets/11407417/38713dc1-6d24-401e-9ee8-b535f626e696)

**Comment by iG8R** [comment]
Thank you very much!
It works like a charm.
