### ISSUE TITLE
Bug with g4f markdown links output

### ISSUE THREAD

**Issue by Aarushb** [xtekky/gpt4free#1643]
Hello,
For a month or so, I've  been getting a strange error with g4f to where if it generates hyperlinks in markdown, the output just cuts off after the markdown code for said link. 
something like so:
> Machine learning is a branch of artificial intelligence that focuses on creating systems that can learn from data and improve their performance without explicit programming. Machine learning algorithms can be used for various tasks, such as classification, regression, clustering, anomaly detection, recommendation, natural language processing, computer vision, and more.
>
> If you want to learn more about machine learning, you can check out the following resources:
>
> - The [uais website](https://uais.dev/
> ....
> ** cuts off after the ( link**

Anyone else facing this?
Library is up to date for me, btw.
Tested with g4f.provider.Bing and g4f.provider.Phind so far.

Thanks

**Comment by hlohaus** [comment]
I think it is a issue only with Bing. Maybe we send a wrong option. But I don't know which.
