### ISSUE TITLE
Bro You  used copilot in gpt-4? 

### ISSUE THREAD

**Issue by 1234worldcom** [xtekky/gpt4free#1647]
In it is copilot with name and anyone can easily find  and not giving good outputs and custom system prompt not good prompt output anyway please add new providers for gpt-4

**Comment by 1234worldcom** [comment]
I made code to get Gpt-4 with history would u Add it please

**Comment by hlohaus** [comment]
Can you send us the code?

**Comment by whenheliom45678** [comment]
No, GPT-4 doesn't use Copilot or any other external tools or plugins. It operates based on its training data up until its last update in April 2023. Regarding your interest, " [Download Geometry Dash](https://thegeometrydash.com/) " to embark on a thrilling adventure of rhythm-based levels that challenge your timing and reflexes. This popular game combines music, precision, and a dash of frustration with fun, offering endless entertainment for players looking for a compelling digital experience.

**Comment by hlohaus** [comment]
Ok. I will take a look. Can you share the code with us?

**Comment by 1234worldcom** [comment]
Sorry the code has a bug right now!

**Comment by 1234worldcom** [comment]
hello @hlohaus can u help me in my project
