### ISSUE TITLE
Can you give me a sample code to generate an image using geminiPro in legacyAPI?

### ISSUE THREAD

**Issue by gamelist1990** [xtekky/gpt4free#1648]
chunks = await g4f.ChatCompletion.create_async(
        model="gemini-pro-vision", # Using the default model
        provider=g4f.Provider.GeminiPro, # Specifying the provider as OpenaiChat
        messages=[{"role": "user", "content": f"Create images with {prompt}"}],
        api_key="xxxxx"
        
    )   
Is the code now only available for gemini-pro-vision in the client?

**Comment by hlohaus** [comment]
We haven't a async API for generating images. But you can using streaming and one chunk can be a image response.

**Comment by hlohaus** [comment]
We haven't a async API for generating images. But you can using streaming and one chunk can be a image response.

And g4f.Provider.GeminiPro doesn't support ImageGeneration. Only g4f.Provider.Gemini does it.
