### ISSUE TITLE
asking for login every time submit a question

### ISSUE THREAD

**Issue by utlimate** [xtekky/gpt4free#1652]
asking for login in every time in openaichat and bard

this may avoid if use global WebDriverSession. This will not open new web driver on every time asked question.
we can also open webdriver until api or gui is running
we can also use undetected selenium libraries like undetected_chromedriver

**Comment by hlohaus** [comment]
Both providers also use get_cookies. It reads the cookies from browser. It also reads the cookies from the "_g4f" browser (webdriver).

**Comment by utlimate** [comment]
It asked for login every time i send query
