### ISSUE TITLE
GeminiPro multiturn error

### ISSUE THREAD

**Issue by Cha14ka** [xtekky/gpt4free#1654]
**Bug description**
GeminiPro gives an error about multiturn if you use the "system" role at the beginning of list before "user" role, but at the same time just Gemini responds without problems

```python
from g4f.client import Client
from g4f.Provider.GeminiPro import GeminiPro

history = [{'role':'system', 'content':'you are bot'}, {'role':'user', 'content':'hello'}]

client = Client()
client.chat.completions.create(model='gemini', messages=history) #ok

client = Client(api_key=token, provider=GeminiPro)
client.chat.completions.create(model='gemini-pro', messages=history) #gives error
```

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/16352397/bb2fd9b6-4439-40bb-b5d4-e4b542e994c1)

**Comment by hlohaus** [comment]
The Gemini provider put everythings in one field. That is the reason why it works. I think gemini doesn't support system messages. There is nothing in the documentation about it.
