### ISSUE TITLE
Bing CAPTCHA

### ISSUE THREAD

**Issue by Lein000** [xtekky/gpt4free#1655]
I can't figure out why the captcha error pops up even when changing the proxy, although it disappears after restarting the entire code. Do you have any thoughts?
Code snippet
@staticmethod
    def change_proxy():
        
        proxies = ["socks5://proxy2:proxy2@ip2:port2",
                   "socks5://proxy:proxy@ip:port"] 
        new_proxy = random.choice(proxies)  
        with open('proxy.json', 'w') as f:
            json.dump({'proxy': new_proxy}, f)  
            print("PROXY CHANGED")
        return new_proxy

    @staticmethod
    def create_async_generator(
        model: str,
        messages: Messages,
        timeout: int = 900,
        cookies: dict = None,
        connector: BaseConnector = None,
        tone: str = Tones.creative,
        image: ImageType = None,
        web_search: bool = False,
        **kwargs
    ) -> AsyncResult:
        with open('proxy.json', 'r') as f:
            data = json.load(f)  
            proxy = data['proxy']
Code snippet2:
 elif response.get('type') == 2:
                            result = response['item']['result']
                            if result.get('error'):
                                Bing.change_proxy()
                                print("PROXY CHANGE")
                                if result["value"] == "CaptchaChallenge":
                                    raise Exception(f"{result['value']}: Use other cookies or/and ip address")
                                else:
                                    raise Exception(f"{result['value']}: {result['message']}")
                            return
        finally:
            await delete_conversation(session, conversation)

**Comment by hlohaus** [comment]
I updated a url in Bing. Maybe it works now better.

**Comment by Lein000** [comment]
![image](https://github.com/xtekky/gpt4free/assets/157303952/91cb8f35-b11c-4007-aad3-d9cb0a4f20a7)
no, a captcha error is consistently obtained.((

**Comment by Lein000** [comment]
but at the same time, when the GUI script code is reloaded, the error disappears.

**Comment by distributev** [comment]
What do you mean by "_when the GUI script code is reloaded_"

I run using "docker-compose up -d" an not matter how many times I stop/start the app bing captcha or another bing error is coming. 

Where do you place this code 

```proxies = ["socks5://proxy2:proxy2@ip2:port2",
               "socks5://proxy:proxy@ip:port"] 
    new_proxy = random.choice(proxies)  
    with open('proxy.json', 'w') as f:
        json.dump({'proxy': new_proxy}, f)  
        print("PROXY CHANGED")
    return new_proxy``` 

and from where did you get your proxies for using here?

**Comment by hlohaus** [comment]
I have not released the changes.
The changes are currently only in my pull request.
