### ISSUE TITLE
oracle cloud

### ISSUE THREAD

**Issue by criticalswateam1** [xtekky/gpt4free#1658]
**Bug description**
Hosting on oracle cloud using docker issue with the processor using ampere

ex.
Create a oracle cloud instance using ampere you will get a error when trying to run the build

```
root@inference:~# docker run -p 8080:8080 -p 1337:1337 -p 7900:7900 --shm-size="2g" hlohaus789/g4f:latest --platform linux/arm64
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--platform": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container:
```

**Environment**
-Python 3.6.9
- No

**Comment by dsymbol** [comment]
orcale cloud ampere is arm64, the docker image is only for amd64.
`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)`

**Comment by hlohaus** [comment]
Look in #1535 form a ARM image. I will not release images, which I can't test. So you have to use user images for ARM.

**Comment by criticalswateam1** [comment]
Hi thanks so much! Will test now

**Comment by criticalswateam1** [comment]
> Look in #1535 for a ARM image. I will not release images, which I can't test. So you have to use user images for ARM.

Thanks so much! This has worked for me
