### ISSUE TITLE
Phind takedown request

### ISSUE THREAD

**Issue by michaelroyzen** [xtekky/gpt4free#1662]
Hello,

Founder of Phind here. I'm kindly requesting that you once again remove Phind from your providers list @xtekky. We've previously asked to be removed, and we appreciated your cooperation with #153.

I'm not quite sure why Phind is back, but as I said in #153, we are a small team with limited resources. We provide our services for free anyway, and the right thing for you to do is to take it down once again.

I hope that you can consider the ethics of the situation and make the right decision.

Thanks,

Michael

**Comment by hlohaus** [comment]
Hello Michael,

I didn't know this. I will create a pull request.

Greets
