### ISSUE TITLE
how to fix "Task was destroyed but it is pending! task: ..."

### ISSUE THREAD

**Issue by Mylinde** [xtekky/gpt4free#1666]
Need some help to fix error while using mixtral or mistral with provider PerplexityLabs. After typing "continue" the interrupted task contiunes in a new answer.

provider PerplexityLab
127.0.0.1 - - [08/Mar/2024 10:00:12] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
Task was destroyed but it is pending!
task: <Task pending name='Task-2995' coro=<<async_generator_athrow without __name__>()>>
provider PerplexityLab
127.0.0.1 - - [08/Mar/2024 10:00:31] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
Task was destroyed but it is pending!
task: <Task pending name='Task-3516' coro=<<async_generator_athrow without __name__>()>>
provider PerplexityLab
127.0.0.1 - - [08/Mar/2024 10:00:48] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
Task was destroyed but it is pending!
task: <Task pending name='Task-3903' coro=<<async_generator_athrow without __name__>()>>
provider PerplexityLab
127.0.0.1 - - [08/Mar/2024 10:02:50] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
Task was destroyed but it is pending!
task: <Task pending name='Task-4420' coro=<<async_generator_athrow without __name__>()>>

**Comment by hlohaus** [comment]
PerplexityLabs has a infinite loop for me. Maybe it's broken.
