### ISSUE TITLE
None of the GPT4 providers seems to be working

### ISSUE THREAD

**Issue by XenocodeRCE** [xtekky/gpt4free#1669]
Error message : 
```
Using RetryProvider provider and gpt-4 model
Using Bing provider
Bing: TypeError: ClientSession.ws_connect() got an unexpected keyword argument 'params'
Using Liaobots provider
Liaobots: RateLimitError: Rate limit reached. Use a other provider or ip address
```

The code I use : 

```python
response = g4f.ChatCompletion.create(
                model=g4f.models.gpt_4,
                messages=[
                    {"role": "system", "content": sysprompt},
                    {"role": "user", "content": msg},
                ],
            )
```        

The bing issue seems to be related to gpt4free core code

python 3.10

**Comment by XenocodeRCE** [comment]
and the GPT-3 ones I tried using this : 

```python
response = g4f.ChatCompletion.create(
                model=g4f.models.gpt_35_long,
                messages=messages,
            )  # Alternative model setting
```

gives very relativistic and average blurry answers, which I need to avoid. Even the local Ollama 7b gives such relativistic answers.

**Comment by hlohaus** [comment]
Try to update aiohttp for Bing:

pip install -U aiohttp

The error is from the aiohttp package.

**Comment by XenocodeRCE** [comment]
> Try to update aiohttp for Bing:
> 
> pip install -U aiohttp
> 
> The error is from the aiohttp package.

Thank you ! Would be nice to add update aiohttp to the pip update cmd for g4f; it fixed the issue thank you :D

**Comment by XenocodeRCE** [comment]
I had to add cookie to my script : 


```
from g4f.cookies import set_cookies

set_cookies(".bing.com", {
  "_U": "..."
})
```

so now it works, i'll close the issue. If this still doesn't work i'll have to switch to GPT3.5

again, thank you a lot :-)
