### ISSUE TITLE
Bing is not working

### ISSUE THREAD

**Issue by distributev** [xtekky/gpt4free#1673]
![image](https://github.com/xtekky/gpt4free/assets/19224635/2bd42cfb-6bb9-4842-af30-15c1873be76a)

**Comment by distributev** [comment]
I use the latest source code from git clone.

The error from the log is 
```
lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1166, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1626.1')

During handling of the above exception, another exception occurred:
```

**Comment by distributev** [comment]
One step further, it is still failing but this time wiht a Captcha Error

![image](https://github.com/xtekky/gpt4free/assets/19224635/c6d9872b-a93d-4688-9e8b-ad374f222573)

**Comment by hlohaus** [comment]
I worked hard to solve the issues.
I added a wait and retry to Bing.
It also protects you against bans.
You will never become this error again:
* Can't create a new chat 
* CaptchaChallenge

**Comment by distributev** [comment]
@hlohaus did you push the fix already? I have the latest code and I still get the CaptchaChallenge error.

**Comment by distributev** [comment]
Captcha hell
Unfortunately even with the latest version I get only the CaptchaError

```  raise RuntimeError(f"{result['value']}: Use other cookies or/and ip address")
RuntimeError: CaptchaChallenge: Use other cookies or/and ip address

  raise RuntimeError(f"{result['value']}: Use other cookies or/and ip address")
RuntimeError: CaptchaChallenge: Use other cookies or/and ip address```
