### ISSUE TITLE
Help! Could anyone  provide a sample code to generate text using GPT4 API from Bing for me?

### ISSUE THREAD

**Issue by JingyaSusieWu** [xtekky/gpt4free#1674]
I have tried numerous times to use gpt-4 API from Bing,  but all defeated, always got the errors like TooManyRedirects or RetryProviderError, it seems that  there were always limits. I also tried to set cookies and proxies, didn't succeed, maybe I don't set the cookies and proxy right. Could anyone provide a sample code including cookies and proxies setting for me? Please!!!

the codes that I tried are as follows:

import g4f
import nest_asyncio

nest_asyncio.apply()

response = g4f.ChatCompletion.create(
    model='gpt-4', 
    messages=[{"role": "user", "content": "Hello"}], 
    stream=False, 
    provider= g4f.Provider.Bing,
    cookies = {"_U": "my cookie value"} 
)
print(response)

-----------------------------------------------------------------------------------------------------------

import g4f
from g4f.cookies import set_cookies
import nest_asyncio

nest_asyncio.apply()

set_cookies("bing.com", {"_U": "my cookie value"} )

response = g4f.ChatCompletion.create(
    model='gpt-4', 
    messages=[{"role": "user", "content": "Hello"}], 
    stream=False, 
    provider= g4f.Provider.Bing 
)

print(response)

and I  set G4F_PROXY=http://host:port in cmd

**Comment by JingyaSusieWu** [comment]
I also try to set proxy as an environment variable in my python code like：

import os
# Set proxy environment variables
os.environ['G4F_PROXY'] = 'http://host:port'

it doesn't work: ValueError: Invalid port component

**Comment by whenheliom45678** [comment]
Sure, here's a sample code snippet in Python to generate text using the GPT-4 API from Bing  "[high end aprons](https://cotonmode.co.uk/collections/aprons) "  This code sends a prompt to the OpenAI API requesting it to generate a description for a collection of  . Adjust the prompt and parameters according to your specific use case and preferences.

**Comment by hlohaus** [comment]
Do the proxy url have a append port number? If not, you should try to add a port number.

**Comment by gavinyeah** [comment]
I met the same issue.
