### ISSUE TITLE
AI model can't remember previous conversation

### ISSUE THREAD

**Issue by rmondal-official** [xtekky/gpt4free#1676]
**Bug description**
```
client = Client()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "hello"}])

print(response.choices[0].message.content)
```
Model cant remember previous conversation. Just after answering the question, it forgets about it.

**Comment by whenheliom45678** [comment]
Apologies for the inconvenience. Regarding the " [old roll apk](https://oldrollapk.com/disposable-camera-old-roll-mod-apk/) " it's essential to ensure you're using the most updated version to avoid potential security risks and ensure optimal performance. Regularly updating your applications helps maintain compatibility with new features and security patches, enhancing your overall experience. If you're encountering issues, consider reaching out to the developer for assistance or exploring alternative solutions.

**Comment by rmondal-official** [comment]
Understood, however, it appears that it may not function as effectively for certain models."
