### ISSUE TITLE
g4f.errors.MissingRequirementsError: Install "undetected_chromedriver" and "platformdirs" package

### ISSUE THREAD

**Issue by rick0101** [xtekky/gpt4free#1681]
**Bug description**
I used venv environment with g4f and it gives me the following error: g4f.errors.MissingRequirementsError: Install "undetected_chromedriver" and "platformdirs" package.
Even if I have already installed those pakages.

**Environment**
- python version 3.12
- location (Italy) ?

**Comment by johnwee1** [comment]
i don't think its in the requirements.txt, u have to pip install those packages. did you do that?

**Comment by hlohaus** [comment]
Did you install this additionally packages?
Also you need a installed Google Chrome to run the webdriver.
Here are the command to install all webdriver requirements:

pip install g4f[webdriver]

**Comment by rick0101** [comment]
> Did you install this additionally packages? Also you need a installed Google Chrome to run the webdriver. Here are the command to install all webdriver requirements:
> 
> pip install g4f[webdriver]



That works, Thank you!!! 
I installed the packages in local, not in venv environment, and now it worked
