### ISSUE TITLE
Bing seems dead

### ISSUE THREAD

**Issue by sjrsjz** [xtekky/gpt4free#1682]
the log:
Using Bing provider and gpt-4-turbo model
Traceback (most recent call last):                           File "/sdcard/mirai/mirai/AliceBot-main/AliceBot.py", line 48, in <module>
    g4f.ChatCompletion().create(                             File "/usr/local/lib/python3.10/dist-packages/g4f/__init__.py", line 146, in create
    return result if stream else ''.join([str(chunk) for chunk in result])                                              File "/usr/local/lib/python3.10/dist-packages/g4f/__init__.py", line 146, in <listcomp>
    return result if stream else ''.join([str(chunk) for chunk in result])
  File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result                                                      raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)                                 File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 200, in await_callback              return await callback()                                  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/Bing.py", line 326, in stream_generate                       conversation = await create_conversation(session)
  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/bing/conversation.py", line 55, in create_conversation
    raise ResponseStatusError(f"Response {response.status}: Can't create a new chat")
g4f.errors.ResponseStatusError: Response 404: Can't create a new chat

**Comment by sjrsjz** [comment]
another error:
Using Bing provider and gpt-4-turbo model
Traceback (most recent call last):                           File "/sdcard/mirai/mirai/AliceBot-main/AliceBot.py", line 48, in <module>                                              g4f.ChatCompletion().create(
  File "/usr/local/lib/python3.10/dist-packages/g4f/__init__.py", line 146, in create
    return result if stream else ''.join([str(chunk) for chunk in result])                                              File "/usr/local/lib/python3.10/dist-packages/g4f/__init__.py", line 146, in <listcomp>
    return result if stream else ''.join([str(chunk) for chunk in result])
  File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 204, in create_completion           yield loop.run_until_complete(await_callback(gen.__anext__))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)                                                            File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step                                                        result = coro.send(None)
  File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 200, in await_callback
    return await callback()                                  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/Bing.py", line 346, in stream_generate                       objects = msg.data.split(Defaults.delimiter)
AttributeError: 'int' object has no attribute 'split'

however it worked yesterday,so i don't think it is my problem

**Comment by jesst3r** [comment]
Same here, absolutely same error message.

**Comment by 7cripter** [comment]
same, i am very much looking forward to the fix, also bing worked before but became very censored, I hope the gpt4free team will find a solution to the problem and return everything to the way it was before.

**Comment by hlohaus** [comment]
I worked hard to solve the issues.
I added a wait and retry to Bing.
It also protects you against bans.
You will never become this error again:
   Can't create a new chat
and 
   CaptchaChallenge

**Comment by 7cripter** [comment]
I also have big problems with my prompt, yesterday it worked correctly although it started to censor strongly (before this was not the case), now without prompt at all and just on the messages the result is but on the messages with my old prompt that used to work I get "", literally nothing.

**Comment by 7cripter** [comment]
> I worked hard to solve the issues. I added a wait and retry to Bing. It also protects you against bans. You will never become this errors again:
> 
> * Can't create a new chat
> * CaptchaChallenge

Thank you very much for your work, but do you plan to fix the issue with returning an empty string? It works very strangely but I've come to the conclusion that it happens now in almost any usage scenario.

**Comment by sjrsjz** [comment]
new error:

When I pass in a large number of contexts (probably twenty or more) to the bing, it will respond nothing

This may have something to do with this:

 "throttling":{"maxNumUserMessagesInConversation":10, "numUserMessagesInConversation":1," maxNumLongDocSummaryUserMessagesInConversation":5, "numLongDocSummaryUserMessagesInConversation":0}

Other than that, basically only 404 errors occur now. For simple contexts, bing is now able to correctly respond

**Comment by hlohaus** [comment]
I could add a error message for this case:

Your request body is to long

**Comment by sjrsjz** [comment]
> I could add a error message for this case:
> 
> Your request body is to long
I suspect that's not the main reason, because if I just gave bing the following context he would still refuse to answer: My mistake, I can't give a response to that right now.

[{'role': 'user', 'content': '"At:123456789":你好'}, {'role': 'assistant', 'content': '你好！有什么我可以帮助您的吗？'}, {'role': 'user', 'content': '"At:123456789":你叫什么'}],

bing:My mistake, I can't give a response to that right now. let's try a different topic.

and bing will respond nothing.

I think it might be a problem with g4f's handling of context formatting? Because it doesn't happen when I talk directly on the webpage.

**Comment by hlohaus** [comment]
g4f use a special context. It creates a new conversation and adds previous messages to the new message. We can't reuse the conversation because the last message could be answered from a other provider.

But if we pin the conversation to the provider, we could reuse the old conversation.

**Comment by sjrsjz** [comment]
> g4f use a special context. It creates a new conversation and adds previous messages to the new message. We can't reuse the conversation because the last message could be answered from a other provider.
> 
> But if we pin the conversation to the provider, we could reuse the old conversation.

In create_message(), if I change

    if context:
        struct['arguments'][0]['previousMessages'] = [{
            "author": "user",
            "description": context,
            "contextType": "WebPage",
            "messageType": "Context",
            "messageId": "discover-web--page-ping-mriduna-----"
        }]

to

    if context:
        struct['arguments'][0]['previousMessages'] = [{
            "author": "user",
            "description": context,
            "contextType": "ClientApp",
            "messageType": "Context",
            "messageId": "discover-web--page-ping-mriduna-----"
        }]

it will work again. Very weird

**Comment by sjrsjz** [comment]
> > g4f use a special context. It creates a new conversation and adds previous messages to the new message. We can't reuse the conversation because the last message could be answered from a other provider.
> > But if we pin the conversation to the provider, we could reuse the old conversation.
> 
> In create_message(), if I change
> 
> ```
> if context:
>     struct['arguments'][0]['previousMessages'] = [{
>         "author": "user",
>         "description": context,
>         "contextType": "WebPage",
>         "messageType": "Context",
>         "messageId": "discover-web--page-ping-mriduna-----"
>     }]
> ```
> 
> to
> 
> ```
> if context:
>     struct['arguments'][0]['previousMessages'] = [{
>         "author": "user",
>         "description": context,
>         "contextType": "ClientApp",
>         "messageType": "Context",
>         "messageId": "discover-web--page-ping-mriduna-----"
>     }]
> ```
> 
> it will work again. Very weird

This method causes context to become useless

**Comment by Mylinde** [comment]
> g4f use a special context. It creates a new conversation and adds previous messages to the new message. We can't reuse the conversation because the last message could be answered from a other provider.
> 
> But if we pin the conversation to the provider, we could reuse the old conversation.

May be useful if not solved so far. Works iif provider is not used in "auto".
https://github.com/VadimBoev/freegpt-webui-v2/pull/29
