### ISSUE TITLE
completions ` haven't `create_async

### ISSUE THREAD

**Issue by blackkvadrat** [xtekky/gpt4free#1683]
I'm using this construction with aiogram in old version on this library(0.2.2.8):

```
 response = await g4f.ChatCompletion.create_async(model=g4f.models.gpt_4_turbo,
                                                          messages=[{'role': 'user',
                                                                      "content": message.text}])
```

await message.answer(response)

in version 0.2.4.0 we should use 

```
response = await client.chat.completions.create(model=g4f.models.gpt_4_turbo,
                                                          messages=[{'role': 'user',
                                                                     "content": message.text}]) 
```
but `completions ` haven't `create_async` func and i have this answer "Use "create_async" instead of "create" function in a running event loop. Or use "nest_asyncio" package."

we can'y using nest_asynci with aiogram,  it's lead to exception and we don't have create_async. 
What should i do ?

**Comment by hlohaus** [comment]
We will add a AsyncClient for new API in the future.
But it not finished jet. You could it use in the leagcy api.
(See Docs in Readme)
Or you add this lines to your file header:

``
import nest_asyncio
nest_asyncio.apply()
``
