### ISSUE TITLE
Something strange

### ISSUE THREAD

**Issue by kobzantsev** [xtekky/gpt4free#1685]
After 0.2.4 update I see in logs this:

GptGo: RuntimeError: Response: error token
ChatBase: ClientResponseError: 429, message='Too Many Requests', url=URL('https://www.chatbase.co/api/fe/chat')
You: ResponseStatusError: Response 403: Cloudflare detected

WTF?

**Comment by kobzantsev** [comment]
Only with New Client API - with Legacy all fine. And now with both APIs when ChatCompletion - Google Chrome opens for few seconds.

**Comment by hlohaus** [comment]
You added a the bot detection from cloudflare to there services.
Only with fresh cookies and headers from browser can you bypass them.
That are the reason that a browser opening.
