### ISSUE TITLE
Please Add Gpt-4-Vision

### ISSUE THREAD

**Issue by 1234worldcom** [xtekky/gpt4free#1688]
Please Add Gpt-4-Vision.

**Comment by hlohaus** [comment]
Bing and OpenaiChat with gpt-4 supports images as input. They are also gpt-4-vision

**Comment by 1234worldcom** [comment]
But BING AND OPENaiCHat not working

**Comment by hlohaus** [comment]
Also You and GeminiPro support image upload. I will create a list.

**Comment by 1234worldcom** [comment]
@xtekky You can add Gpt-4v please
