### ISSUE TITLE
How to use ChatGPT for free after all?

### ISSUE THREAD

**Issue by GariBolter** [xtekky/gpt4free#169]
I tried using phind and poe, but they are taked down, if im not mistaking, all of them took down. And how do i use chatgpt? Maybe there is a way to bypass blocking? Or another way to use chatGPT for free?

**Comment by DanielShemesh** [comment]
Poe should still work

**Comment by xtekky** [comment]
hi, they are not taken down yet till i push new repos, and you can check out `./` unfinished

**Comment by GariBolter** [comment]
> hi, they are not taken down yet till i push new repos, and you can check out `./unfinished`

I don't know, i tried using all of possible chatapis, but all of them just don't work. You worked but i updated it with your update from github and IT ALSO STOPPED WORKIG. I don't know what to do, in desperate, i make my project with openAI but it asked for payment. And now i don't know what to do
