### ISSUE TITLE
Something really odd going on with Bing provider

### ISSUE THREAD

**Issue by jesst3r** [xtekky/gpt4free#1690]
Hello everyone, there's something really odd going on with Bing. It responds to everything with the message:
"My mistake, I can’t give a response to that right now. Let’s try a different topic."
I suppose that the developers of Bing have simply found a way to block unwelcome requests.
### Using version
0.2.4.1

**Comment by AuroraWright** [comment]
Try 0.2.3.3, it works here

**Comment by sjrsjz** [comment]
same, bing will refuse to answer even if i give it simple contexts(like "1+1=?")
