### ISSUE TITLE
Bing, Gemini and e.t.c doesn't work (except Llama)

### ISSUE THREAD

**Issue by shishkin-github** [xtekky/gpt4free#1692]
**Bug description**
Trying to get answer to my question and get an error "
An error occured: Chatgpt4Online: RetryProviderError: RetryProvider failed: You: TypeError: Binary Location Must be a String Bing: ClientResponseError: 400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1626.1') ChatgptAi: RateLimitError: Rate limit reached GptGo: ClientResponseError: 403, message='Forbidden', url=URL('https://gptgo.ai/get_token.php') Chatgpt4Online: TypeError: Binary Location Must be a String"

Llama 2 works fine

<img width="1083" alt="Снимок экрана 2024-03-13 в 22 13 35" src="https://github.com/xtekky/gpt4free/assets/149713156/eb1344c3-2092-40b5-8b57-57f51b245c7f">

**Environment**
- python version 3.8.10
- server located in Germany
- g4f 0.2.4.1 version

**Comment by hlohaus** [comment]
Binary Location Must be a String: You need Google Chrome installed.

Also you could install Brotli for Bing.

And the other error message is a rate limit error.

**Comment by shishkin-github** [comment]
Thanks
