### ISSUE TITLE
OpenaiChat throws a 401 Unauthorized

### ISSUE THREAD

**Issue by txmazing** [xtekky/gpt4free#1693]
**Bug description**
This worked 3 days ago i think, but now throws a 401 Unauthorized:

```
g4f.set_cookies("chat.openai.com", {"access_token": self.oai_access_token})

response = g4f.ChatCompletion.create(
    model=g4f.models.gpt_4,
    provider=g4f.Provider.OpenaiChat,
    messages=[{"role": "user", "content": prompt}],
)
```

I updated to "Client Mode", but isnt working too.
```
client = Client(provider=g4f.Provider.OpenaiChat)

response = client.chat.completions.create(
  model="gpt-4",
  messages=[{"role": "user", "content": prompt}],
  access_token=self.oai_access_token,
)
```

`401, message='Unauthorized', url=URL('https://chat.openai.com/backend-api/sentinel/chat-requirements')`

**Screenshots**
---

**Environment**
- python version
- location germany

**Additional context**
---

**Comment by hlohaus** [comment]
OpenaiChat with Plus Accounts doesn't work anymore. They use a new Bot Protection. I can't solve the Challenge. :/

**Comment by whenheliom45678** [comment]
" [Resso for PC](http://reesoapk.com/resso-for-pc?fbclid=IwAR2SSC3tlEReE52c2nzC_9z6AXeL4llvab35YQv1mwOXds65jOFGF0ma4k8) " offers a seamless way to enjoy your favorite music on a larger screen. With its user-friendly interface and extensive library, Resso enhances your music streaming experience, making it perfect for PC users who love to groove to their favorite tunes while working or relaxing."

**Comment by VadimBoev** [comment]
> OpenaiChat with Plus Accounts doesn't work anymore. They use a new **Bot Protection**. I can't solve the Challenge. :/

I think 'HAR file' should solve this problem. Pay attention to: https://github.com/xqdoo00o/ChatGPT-to-API

**Comment by hlohaus** [comment]
I added the .har file solution from you.
