### ISSUE TITLE
Now Not completely available for offline use, after installation using docker

### ISSUE THREAD

**Issue by HeroSong666** [xtekky/gpt4free#1695]
After I follow the steps in :https://github.com/xtekky/gpt4free#docker-container

I notice that:
![2](https://github.com/xtekky/gpt4free/assets/142960235/63920410-0660-4650-aec2-7695830eaa1e)

My usage environment is completely offline, and some resource packages that need to be downloaded online cannot be downloaded, making the local chat mode unusable.

Is it possible to integrate these resources into docker and specify the loading path as docker local resources, so that complete offline use can be achieved?

**Comment by hlohaus** [comment]
The GUI doesn't support local models jet.
