### ISSUE TITLE
Documentation on 'Install Google Chrome'

### ISSUE THREAD

**Issue by distributev** [xtekky/gpt4free#1698]
On the github readme I see a Pre-requisite as

[Install Google Chrome](https://www.google.com/chrome/) for providers with webdriver

1. Please mention on the readme for which functionality is Google Chrome required?
2. Requiring google chrome means that a full blown x.org/x11 installation is required in order to use gpt4free? (I installed gpt4free on a linux server where x11/x.org is not installed) - if so please add also x.org/x11 as pre-requisite for gpt4free
3. Would opensource alternatives like https://github.com/chromium/chromium achieve the same?

**Comment by hlohaus** [comment]
For the "Webdriver". We use the Webdriver to bypass Cloudflare or for easy login with your Browser. But it is not a requirement for all providers.

**Comment by whenheliom45678** [comment]
To install Google Chrome, simply visit the official Chrome website and download the installer. Once downloaded, run the installer and follow the on-screen instructions. During installation, you might encounter prompts for permissions or agreements. After installation, you can launch Chrome and start browsing. If needed, you can utilize a " [Token Maker](https://tokenmakerpro.com/) " for generating authentication tokens or access keys for specific services or applications within Chrome.

**Comment by distributev** [comment]
So is  x.org/x11 a pre-requisites for 'Install Google Chrome' required by gpt4free

If so, I believe it is better to be mentioned in the docs - I installed gpt4free on a linux server where, by default, x.org/x11 are not installed.

**Comment by hlohaus** [comment]
It isn't a requirement. A full example: a "How do i set up a server with Webdriver?" Would look like a dockerfile.
So you could look in the dockerfile of selenium (our base image).
