### ISSUE TITLE
Alternative domain for the gpt-clone?

### ISSUE THREAD

**Issue by alanjsebas** [xtekky/gpt4free#170]
Project and it's development seem perfect, just wondering if there are any alternative domains to access it rather chatbot.sex ....

**Comment by xtekky** [comment]
Hi, this website was intended to be a meme, I am planning to get an official domain soon ; )

**Comment by ryanm101** [comment]
Agreed, there is just no way i can click that link in work and honestly even as generally uncaring as I am about names (I don't care about GIMP being GIMP for example as it is just an acronym) but .sex is too on the nose. 
Happy for swearing/jokes in comments etc but I cant get behind chatbot.sex.. I've no way to ever pass that as "it's legit".
