### ISSUE TITLE
The response is returned to generate an image for the text https://www.bing.com/images/create for GPT 4

### ISSUE THREAD

**Issue by BokDan93** [xtekky/gpt4free#1701]
After the update, when calling the GPT4 text function it often returns https://www.bing.com/images/create?q=...

or just text generated images

My function doesn’t ask me to generate images at all.

My function:
response = client.chat.completions.create(
                model="gpt-4-turbo",
                messages=[{"role": "user", "content": full_request}],
                )
            response_str = response.choices[0].message.content

**Comment by BokDan93** [comment]
The thing is, I don't need image generation, I just need text. But periodically it just returns a link to https://www.bing.com/images/create?q =

**Comment by hlohaus** [comment]
There is a
   do_read = False
after the returning of the link.
Maybe we can remove it and Bing generates a text too.
