### ISSUE TITLE
Errors when receiving a response from gemini and claude 3 Opus

### ISSUE THREAD

**Issue by BokDan93** [xtekky/gpt4free#1705]
Errors when receiving a response from gemini and claude 3 Opus. When requested via telegram bot, the browser opens on the server side, tries to pass the captcha check by opening two tabs. Then one is closed, the second captcha is not passed. After a while, the browser closes and an error is returned

ResponseStatusError: Response 500: {"error":{"code":"Error","message":"[GoogleGenerativeAI Error]: Error fetching from  [403 Forbidden] This API method requires billing to be enabled. Please enable billing on project #556908318160 by visiting  then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry. [{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Google developers console billing\",\"url\":\""}}
You: TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00618D03+51395]
        (No symbol) [0x00585F61]
        (No symbol) [0x0043E13A]
        (No symbol) [0x004762BB]
        (No symbol) [0x004763EB]
        (No symbol) [0x004AC162]
        (No symbol) [0x00493ED4]
        (No symbol) [0x004AA570]
        (No symbol) [0x00493C26]
        (No symbol) [0x0046C629]
        (No symbol) [0x0046D40D]
        GetHandleVerifier [0x009968D3+3712147]
        GetHandleVerifier [0x009D5CBA+3971194]
        GetHandleVerifier [0x009D0FA8+3951464]
        GetHandleVerifier [0x006C9D09+776393]
        (No symbol) [0x00591734]
        (No symbol) [0x0058C618]
        (No symbol) [0x0058C7C9]
        (No symbol) [0x0057DDF0]
        BaseThreadInitThunk [0x764F6A39+25]
        RtlGetFullPathName_UEx [0x7736800D+173]
        RtlGetFullPathName_UEx [0x77367FDB+123]

**Comment by hlohaus** [comment]
I changed the You.com provider from Google Chrome to curl_cffi. Now it doesn't need to start a browser.
