### ISSUE TITLE
Chatgpt-4-turbo not working on streamlit server

### ISSUE THREAD

**Issue by codewithdark-git** [xtekky/gpt4free#1709]
## **Description:**
I'm encountering an issue with the chatgpt-4-turbo model while running my Streamlit app on a server. The model works perfectly fine on my local machine, but when I deploy the app on a Streamlit server, it throws the following error:

"An error occurred: CaptchaChallenge: Use other cookies or/and ip address."

I have ensured that all the requirements are installed properly, including the necessary 

**Screenshots**
### On Local machine:
![Screenshot 2024-03-15 194146](https://github.com/xtekky/gpt4free/assets/144595403/ed3f380f-b5b9-4ad9-a001-1514bc53a7d3)
### On Server
![Screenshot 2024-03-15 200354](https://github.com/xtekky/gpt4free/assets/144595403/fdccd5e0-f3ed-4196-8a38-a0e7d1c3d084)

## **Environment**
- python version : 3.10
- location : Pakistan

## **Additional context**
I have verified that all requirements are installed correctly.
Any insights or suggestions on resolving this issue would be greatly appreciated.

**Comment by XenocodeRCE** [comment]
It happens for me too, randomly. It's an issue with GPT4 providers. My solution is a loop in the code, if this error msg is detected I just re run the code till it works fine. And it does

**Comment by hlohaus** [comment]
I added a , max_retries=5 option some versions ago. Also it wait 15 seconds. That is important.

**Comment by 1234worldcom** [comment]
@hlohaus Can You Help Me in gpt4 Rev Api
