### ISSUE TITLE
Issue with the GUI version: An error occured...

### ISSUE THREAD

**Issue by ecxdev** [xtekky/gpt4free#171]
I installed and ran the GUI version. 
Then I wrote my query and clicked the Think button. The result is shown below:
### An error occured, please make sure you are using a cf_clearance token and correct useragent | cf_clearance must be set, refer to documentation

**Comment by Worrah** [comment]
same for me but slightly different without gui:

`An error occured, please make sure you are using a cf_clearance token and correct useragent | Expecting value: line 1 column 1 (char 0)`

**Comment by rexzhang2023** [comment]
An error occured, please make sure you are using a cf_clearance token and correct useragent | cf_clearance must be set, refer to documentation
where can I find the documentation to setup above request?

**Comment by joeysantana3** [comment]
If you follow the setup instructions on the main page, one of the steps is copying/moving `streamlit_app.py` to the main folder and then running it. After you do that, open up the `streamlist_app.py` file in a text editor.

You should see two lines in the python script, `phind.cf_clearance = ...` and `phind.user_agent = ...`.

Go to https://www.phind.com/ in your web browse and open developer tools. Go to storage -> Cookies -> then select the phind.com cookie. You should see `cf_clearance` in the cookie data. Copy that value and replace whats in the `streamlit_app.py` file with your value. For the user_agent value, you need to copy and paste the user agent identifier of the browser you used to access the site. There are a few ways to get your browser user agent, but one way is to go to the network tab of the developer tools, select a row (may need to refresh the page), then in the Headers section you should see request header. Your user-agent is there.

![Screenshot from 2023-04-26 17-55-17](https://user-images.githubusercontent.com/40314133/234733199-98ad7647-a4f4-41cf-9c69-a345a8daaa4d.png)
![Screenshot from 2023-04-26 17-55-37](https://user-images.githubusercontent.com/40314133/234733206-5084cb1b-7949-4773-a9ad-627871175bb6.png)

**Comment by starryhcy** [comment]
> Disclaimer: this is what worked for me, not sure this is the right way...
> 
> If you follow the setup instructions on the main page, one of the steps is copying/moving `streamlit_app.py` to the main folder and then running it. After you copy it, open up the `streamlit_app.py` file in a text editor.
> 
> You should see two lines in the python script, `phind.cf_clearance = ...` and `phind.user_agent = ...`.
> 
> Go to https://www.phind.com/ in your web browser and open developer tools. Go to storage -> Cookies -> then select the phind.com cookie. You should see `cf_clearance` in the cookie data. Copy that value and replace whats in the `streamlit_app.py` file with your value. For the user_agent value, you need to copy and paste the user agent identifier of the browser you used to access the site. There are a few ways to get your browser user agent, but one way is to go to the network tab of the developer tools, select a row (may need to refresh the page), then in the Headers section you should see request header. Your user-agent is there.
> 
> ![Screenshot from 2023-04-26 17-55-17](https://user-images.githubusercontent.com/40314133/234733199-98ad7647-a4f4-41cf-9c69-a345a8daaa4d.png) ![Screenshot from 2023-04-26 17-55-37](https://user-images.githubusercontent.com/40314133/234733206-5084cb1b-7949-4773-a9ad-627871175bb6.png)

I tried this method but it still didn't work

![image](https://user-images.githubusercontent.com/30070551/234748252-61513269-7d10-46d3-aafd-08b4d328a238.png)
![image](https://user-images.githubusercontent.com/30070551/234748377-8089efd2-6fa1-4242-a55f-566887c4e187.png)

**Comment by nongfu9woo** [comment]
> Disclaimer: this is what worked for me, not sure this is the right way...
> 
> If you follow the setup instructions on the main page, one of the steps is copying/moving `streamlit_app.py` to the main folder and then running it. After you copy it, open up the `streamlit_app.py` file in a text editor.
> 
> You should see two lines in the python script, `phind.cf_clearance = ...` and `phind.user_agent = ...`.
> 
> Go to https://www.phind.com/ in your web browser and open developer tools. Go to storage -> Cookies -> then select the phind.com cookie. You should see `cf_clearance` in the cookie data. Copy that value and replace whats in the `streamlit_app.py` file with your value. For the user_agent value, you need to copy and paste the user agent identifier of the browser you used to access the site. There are a few ways to get your browser user agent, but one way is to go to the network tab of the developer tools, select a row (may need to refresh the page), then in the Headers section you should see request header. Your user-agent is there.
> 
> ![Screenshot from 2023-04-26 17-55-17](https://user-images.githubusercontent.com/40314133/234733199-98ad7647-a4f4-41cf-9c69-a345a8daaa4d.png) ![Screenshot from 2023-04-26 17-55-37](https://user-images.githubusercontent.com/40314133/234733206-5084cb1b-7949-4773-a9ad-627871175bb6.png)

**Comment by nongfu9woo** [comment]
@joeysantana3 
After setting it up, it still reports the same error

**Comment by tomstsai** [comment]
> Disclaimer: this is what worked for me, not sure this is the right way...
> 
> If you follow the setup instructions on the main page, one of the steps is copying/moving `streamlit_app.py` to the main folder and then running it. After you copy it, open up the `streamlit_app.py` file in a text editor.
> 
> You should see two lines in the python script, `phind.cf_clearance = ...` and `phind.user_agent = ...`.
> 
> Go to https://www.phind.com/ in your web browser and open developer tools. Go to storage -> Cookies -> then select the phind.com cookie. You should see `cf_clearance` in the cookie data. Copy that value and replace whats in the `streamlit_app.py` file with your value. For the user_agent value, you need to copy and paste the user agent identifier of the browser you used to access the site. There are a few ways to get your browser user agent, but one way is to go to the network tab of the developer tools, select a row (may need to refresh the page), then in the Headers section you should see request header. Your user-agent is there.
> 
> ![Screenshot from 2023-04-26 17-55-17](https://user-images.githubusercontent.com/40314133/234733199-98ad7647-a4f4-41cf-9c69-a345a8daaa4d.png) ![Screenshot from 2023-04-26 17-55-37](https://user-images.githubusercontent.com/40314133/234733206-5084cb1b-7949-4773-a9ad-627871175bb6.png)

Thx! 
but a new probrom:
the connetcion was reset in connection to [www.phind.com:443](http://www.phind.com:443/)

**Comment by pearSix66** [comment]
it seems no use to me

**Comment by Chenm4** [comment]
> same for me but slightly different without gui:
> 
> `An error occured, please make sure you are using a cf_clearance token and correct useragent | Expecting value: line 1 column 1 (char 0)`

i have the same problem, have you resolve it?

**Comment by xtekky** [comment]
#194

**Comment by EugeneFlash** [comment]
I have this after the solution: An error occured, please make sure you are using a cf_clearance token and correct useragent | Failed to perform, ErrCode: 60, Reason: 'SSL certificate problem: self signed certificate in certificate chain'

**Comment by Lucky-lhq** [comment]
An error occured, please make sure you are using a cf_clearance token and correct useragent | Expecting value: line 1 column 1 (char 0)

**Comment by SergeyPolud** [comment]
now getting An error occured, please make sure you are using a cf_clearance token and correct useragent | Expecting value: line 1 column 1 (char 0)

**Comment by OPbjO** [comment]
An error occurred: Expecting value: line 1 column 1 (char 0). Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by SergeyPolud** [comment]
> An error occurred: Expecting value: line 1 column 1 (char 0). Please make sure you are using a valid cloudflare clearance token and user agent.

Resolved: do a git pull

**Comment by xzcccc** [comment]
It worked for me, Thanks!
