### ISSUE TITLE
AttributeError: module 'g4f' has no attribute 'client'

### ISSUE THREAD

**Issue by Samsonenko-Stanislav** [xtekky/gpt4free#1710]
**Bug description** 
When trying to run script from Quickstart, i get this error.

Traceback (most recent call last):
  File "C:/Users/samso/AppData/Local/Programs/Python/Python311/test.py", line 3, in <module>
    engine = g4f.client.Client()
AttributeError: module 'g4f' has no attribute 'client'

**Environment**
Python version: 3.11.7

**Comment by hlohaus** [comment]
Import it first:

import g4f.client;
client = g4f.client.Client()

Or

from g4f.client import Client;
client = Client()
