### ISSUE TITLE
Bing issue

### ISSUE THREAD

**Issue by 7cripter** [xtekky/gpt4free#1711]
will there be a bing fix ? on 2 - 3 posts it always gives an answer like: "Sorry! That’s on me, I can’t give a response to that right now. What else can I help you with?"

**Comment by jesst3r** [comment]
Ahoy matey, da same, shiver me timbers dats just killhaulin me an me hearties

**Comment by hlohaus** [comment]
I released a fix for bing with the gui.
Bing had a security fix.
You can't send or read conversations anymore:
You have to reuse them.

**Comment by 7cripter** [comment]
Okay, thanks.

**Comment by 7cripter** [comment]
Can you please tell me which providers still provide similar functionality as Bing had using API? It suited me by the fact that it processed a large amount of prompt and also was not highly censored.

**Comment by hlohaus** [comment]
I can maybe add the fix to the API too.
But you need have to send a conversation_id. With the default API it is not possible.

**Comment by 7cripter** [comment]
I would be happy to, where would I need to get the conversation_id and where do I put it? I tried gemini but couldn't get it to run, gemini-pro is paid if I'm not mistaken.

**Comment by hlohaus** [comment]
gemini-pro is free. Only if you use Vertex, you need to pay.
But the gemini API is only available outside europe.
Also you could try to use You or OpenaiChat.

**Comment by 7cripter** [comment]
> gemini-pro is free. Only if you use Vertex, you need to pay. But the gemini API is only available outside europe. Also you could try to use You or OpenaiChat.

I tried again to use gemini and gemini-pro but I got only api key and query errors, what am I doing wrong? My current code:
from aiohttp import web
```
import g4f
from g4f.cookies import set_cookies

async def handle(request):
    data_received = await request.json()
    print(f"Data received: {data_received}")

    set_cookies(".google.com", {
    "__Secure-1PSID": "****"
    })

    response_data = await g4f.ChatCompletion.create_async(
        model=g4f.models.gemini_pro,
        provider=g4f.Provider.GeminiPro,
        messages=data_received,
    )

    return web.json_response(response_data)

app = web.Application()
app.router.add_post('/post_data', handle)

web.run_app(app, host='localhost', port=6789)
```

**Comment by hlohaus** [comment]
g4f.Provider.GeminiPro use a api_key and

g4f.Provider.Gemini use the cookie.

You can get a api key form google.ai I think.

**Comment by 7cripter** [comment]
> g4f.Provider.GeminiPro use a api_key and
> 
> g4f.Provider.Gemini use the cookie.
> 
> You can get a api key form google.ai I think.

indeed, I was able to get the google ai API key, but when querying I get "User location is not supported for the API use.". I ran it from Ukraine and from hosting from Poland, getting the same answers, I also tried to use a proxy but I failed, I get "Couldn't connect to proxy", I set the proxy in the request to ChatCompletion and also tried through set G4F_PROXY=http://host:port but setting environment variables didn't help at all and when setting in arguments I get an error. g4f.ChatCompletion.create_async(
        # proxy="http://208.102.51.6:58208",
    ).
Can you tell me how to use proxy correctly and where it is better to get it from?

Translated with DeepL.com (free version)

**Comment by XenocodeRCE** [comment]
> > g4f.Provider.GeminiPro use a api_key and
> > g4f.Provider.Gemini use the cookie.
> > You can get a api key form google.ai I think.
> 
> indeed, I was able to get the google ai API key (using vpn), but when querying I get "User location is not supported for the API use.". I ran it from Ukraine and from hosting from Poland, getting the same answers, I also tried to use a proxy but I failed, I get "Couldn't connect to proxy", I set the proxy in the request to ChatCompletion and also tried through set G4F_PROXY=http://host:port but setting environment variables didn't help at all and when setting in arguments I get an error.
> 
> ```
> g4f.ChatCompletion.create_async(
>         proxy="http://208.102.51.6:58208",
>     ).
> ```
> 
> Can you tell me how to use proxy correctly and where it is better to get it from?

He told you outside from Europe, Ukraine is in Europe continent. Get an U.S.A. VPN / PROXY :)

**Comment by hlohaus** [comment]
I use free usa VPN for that, but the other providers stop working. (Bad IP)

**Comment by XenocodeRCE** [comment]
> I use free usa VPN for that, but the other providers stop working. (Bad IP)

Bad IP simply means bing prevents you from using it from your VPN ip. Free VPN IP are flagged and mostly used by tons of people. Either buy a premium VPN or something. From my understanding your issue has nothing to do with gpt4free

**Comment by hlohaus** [comment]
I wanted help @7cripter 
In Germany we say a 0815 number. (free calls) Free US VPN is enough for GeminiPro.

**Comment by 7cripter** [comment]
I've already run Gemini with VPN USA running, it really doesn't work badly although it has a lot of censorship, but it was a VPN running on the system, whatever proxies I wrote in "g4f.ChatCompletion.create_async(proxy" I got an error.
