### ISSUE TITLE
ГигаЧат

### ISSUE THREAD

**Issue by den47999** [xtekky/gpt4free#1713]
Добрый день:) в проект
можно добавить модель GigaChat  https://developers.sber.ru/docs/ru/gigachat/api/reference/rest/gigachat-api  в ваш проект?
данная модель модель GigaChat может кроме текста рисовать используя [Kandinsky 3.0](https://www.sberbank.com/promo/kandinsky/)

**Comment by ComRSMaster** [comment]
[GigaChat was added today](https://github.com/xtekky/gpt4free/blob/main/g4f/Provider/GigaChat.py), Kandinsky 3.0 is not yet
> в проект можно добавить модель GigaChat

**Comment by den47999** [comment]
не отвечает
![Screenshot_1](https://github.com/xtekky/gpt4free/assets/118296790/74c47942-8180-4d89-94ac-090a70dbb25e)
я в коде не могу найти куда вставить ключ API?

**Comment by den47999** [comment]
не отвечает я в коде  не могу найти куда вставить ключ API?
![Screenshot_1](https://github.com/xtekky/gpt4free/assets/118296790/d561cedb-2f98-4a40-80fb-cef5bc467a78)

**Comment by den47999** [comment]
подскажите пожалуйста как мне добавить в рабочие модели гига чат?
![Screenshot_1](https://github.com/xtekky/gpt4free/assets/118296790/050d3907-c5e7-49a4-9b7d-e42669ddf21a)

**Comment by den47999** [comment]
подскажите как можно настроить температуру и максимальное количество токенов? пример:
![Screenshot_2](https://github.com/xtekky/gpt4free/assets/118296790/f89e005e-046b-4cf4-bbbf-c7086bc9fd27)

**Comment by den47999** [comment]
подскажите я установил версию gpt4free-0.2.5.4 но у меня отображается
![Screenshot_1](https://github.com/xtekky/gpt4free/assets/118296790/f3df18cc-3109-49b3-9fbb-8843e92a8b4d)
как настроить что бы версии совпадали?

**Comment by den47999** [comment]
Кто сможет мне помочь?

**Comment by TheSashaDev** [comment]
Чтобы тебе тут ответили, пиши на английском

**Comment by Anonymous6598** [comment]
И про печеньки не забудь

**Comment by Anonymous6598** [comment]
https://g4f.mintlify.app/docs/get-started/introduction документация в помощь.

**Comment by Anonymous6598** [comment]
А картинки сохраняются в виде юрл адреса, переходя к которому ты увидишь картинку.

**Comment by Anonymous6598** [comment]
У меня так было с бингом и гемини

**Comment by Anonymous6598** [comment]
```python
from g4f.local import LocalClient

client   = LocalClient() # в терминале напиши `pip install -U g4f[local]`
response = client.chat.completions.create(
    model    = 'orca-mini-3b', # название большой языковой модели
    messages = [{"role": "user", "content": "hi"}],
    stream   = True
)

for token in response:
    print(token.choices[0].delta.content or "")

```

**Comment by Anonymous6598** [comment]
И ещё, обновись до 0.2.8.2. А ты в какой версии питона установил?

**Comment by ZhymabekRoman** [comment]
@Anonymous6598 Please do not use Russian, Google Translate (DeepL or even sometimes Yandex) are bad in translation of some terminology.

**Comment by Anonymous6598** [comment]
Alright, I apologize for using Russian. I just wanted to help. If @den47999 doesn't know English, how will he understand me?

**Comment by den47999** [comment]
I'm not a programmer and don't understand much about writing code so I asked for help:)

**Comment by Anonymous6598** [comment]
@den47999, are you system administrator?

**Comment by den47999** [comment]
no :) I'm a simple user :)

**Comment by Anonymous6598** [comment]
Did it help

**Comment by den47999** [comment]
No, I need the code ready to go or a step-by-step demonstration.
