### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'choices'

### ISSUE THREAD

**Issue by Fabbbr0** [xtekky/gpt4free#1714]
**Bug description**
i tried to run from another script (main.py) this function (startchat(question))
but i get the error :
    ReplyText = response.choices[0].message.content
                ^^^^^^^^^^^^^^^^
AttributeError: 'generator' object has no attribute 'choices'

i dont think there are any errors in the main.py file

i tried to change provider and model but nothing worked

`from g4f.client import Client

client = Client()
MessageStorage = []
first = 0
ReplyText = ""
questionNum = 15

def startchat(domanda):
    global MessageStorage
    global first
    global questionNum
    global ReplyText
    if first == 0:
        MessageStorage = [{'role': 'user', 'content': domanda}]
    else:
        MessageStorage.append({'role': 'user', 'content': domanda})
        testo = domanda
    response = client.chat.completions.create(
        messages=MessageStorage,
        model="gpt-4-turbo",
        max_tokens=30000,
        provider="Bing",
        stream=True
    )
    first += 1
    ReplyText = response.choices[0].message.content
    print()
    if first < questionNum:
        MessageStorage.append({'role': 'assistant', 'content': ReplyText})
    else:
        del MessageStorage[0]
        del MessageStorage[0]
        MessageStorage.append({'role': 'assistant', 'content': ReplyText})
    print(MessageStorage)
    return response.choices[0].message.content
`
**Environment**
- python version: 3.11.8
- location : italy

**Comment by Fabbbr0** [comment]
> Remove this line: stream=True Or use the streaming.

If i dont use the stream=True line the output is

Hmm…let’s try a different topic. Sorry about that. What else is on your mind?

**Comment by hlohaus** [comment]
That are from Bing. You can't ask him about the conversation. It's a security feature.

If you want history or multiple messages, you have to do this:
```python
            from g4f.Provider.Bing import Conversation
            conversations: dict[str, Conversation] = {}
            for chunk in ChatCompletion.create(
                model, messages, g4f.Provider.Bing,
                stream=True, ignore_stream=True,
                return_conversation=True,
                conversation=conversation
            )
                    "stream": True,
                    "ignore_stream": True,
                    "return_conversation": True,
                    "conversation": conversations[conversation_id] if conversation_id in conversations else None
                }}):
                if isinstance(chunk, Conversation):
                    conversations[conversation_id] = chunk
                print(chunk, end="")
``

**Comment by Fabbbr0** [comment]
> That are from Bing. You can't ask him about the conversation. It's a security feature.
> 
> If you want history or multiple messages, you have to do this:
> 
> ```python
>             from g4f.Provider.Bing import Conversation
>             conversations: dict[str, Conversation] = {}
>             for chunk in ChatCompletion.create(
>                 model, messages, g4f.Provider.Bing,
>                 stream=True, ignore_stream=True,
>                 return_conversation=True,
>                 conversation=conversation
>             )
>                     "stream": True,
>                     "ignore_stream": True,
>                     "return_conversation": True,
>                     "conversation": conversations[conversation_id] if conversation_id in conversations else None
>                 }}):
>                 if isinstance(chunk, Conversation):
>                     conversations[conversation_id] = chunk
>                 print(chunk, end="")
> ``
> ```

sorry where should i put this?
