### ISSUE TITLE
Новый сервер

### ISSUE THREAD

**Issue by den47999** [xtekky/gpt4free#1722]
Добрый день:) в проект
можно добавить подключение через сервер LeinAPI http://212.113.116.85:10000/v1/chat/completions а так же добавить строку api ключ
`
from flask import Flask, request, jsonify, render_template
from flask_socketio import SocketIO, emit
import webbrowser
import logging
import os
import json
import requests

# Настройка логирования
logging.basicConfig(filename=os.path.expanduser('~/Desktop/api_logs.txt'), level=logging.INFO)

app = Flask(__name__)
socketio = SocketIO(app, cors_allowed_origins="*")

def stream_responses(url, body):
    response_text = ""
    with requests.post(url, json=body, stream=True) as response:
        if response.encoding is None:
            response.encoding = 'utf-8'
        
        for line in response.iter_lines(decode_unicode=True):
            if line and not line.isspace():  # Проверка на непустую строку
                try:
                    # Удаление "data: " из строки, если оно присутствует
                    line = line.replace('data: ', '', 1)
                    data = json.loads(line)  # Преобразование строки в объект
                    if 'choices' in data and data['choices'][0].get('delta', {}).get('content'):
                        response_text += data['choices'][0]['delta']['content']
                except json.JSONDecodeError:
                    logging.error(f"Ошибка декодирования JSON: {line}")
        
        return response_text

def log_request_response(url, headers, data, response_text):
    logging.info(f"URL: {url}")
    logging.info(f"Request Headers: {headers}")
    logging.info(f"Request Body: {data}")
    logging.info(f"Response Text: {response_text}")
    logging.info("\n\n")

@app.route('/', methods=['POST', 'GET'])  # Allow both POST and GET requests
def handle_request():
    if request.method == 'POST':
        data = request.get_json()
        question = data.get('question')
        prompt = data.get('prompt')
        model = data.get('model')
        max_tokens = data.get('max_tokens')  # Получение максимального количества токенов из данных запроса

        logging.info(f"Question: {question}")
        logging.info(f"Model: {model}")

        url = "http://212.113.116.85:10000/v1/chat/completions"
        body = {
            "model": model,
            "stream": True,
            "messages": [
                {"role": "system", "content": prompt},
                {"role": "user", "content": question}
            ],
            "max_tokens": max_tokens  # Использование максимального количества токенов в запросе
        }

        response_text = stream_responses(url, body)

        log_request_response(url, request.headers, data, response_text)

        return jsonify({'text': response_text})
    else:
        return render_template('index.html')  # Render the HTML template for GET requests

@socketio.on('connect')
def handle_connection():
    print('Client connected')

@socketio.on('disconnect')
def handle_disconnection():
    print('Client disconnected')

if __name__ == '__main__':

import json
import requests

def stream_responses(url, body):
    with requests.post(url, json=body, stream=True) as response:
        if response.encoding is None:
            response.encoding = 'utf-8'
        for line in response.iter_lines(decode_unicode=True):
            if line and not line.isspace():  
                try:
                    
                    line = line.replace('data: ', '', 1)
                    data = json.loads(line)  
                    if 'choices' in data and data['choices'][0].get('delta', {}).get('content'):
                        print(data['choices'][0]['delta']['content'], end="")
                except json.JSONDecodeError:
                    print(f"Ошибка декодирования JSON: {line}")

# Пример использования
url = "http://212.113.116.85:10000/v1/chat/completions"
body = {
    "model": "gpt_4_toch",
    "stream": True,
    "messages": [
        {"role": "assistant", "content": "What can you do?"}
    ]
}

stream_responses(url, body)

**Comment by Woukim** [comment]
привет, можешь подсказать пожалуйста 🙏
очень нужна помощь: https://github.com/xtekky/gpt4free/discussions/1721

**Comment by den47999** [comment]
не подхватывает и не отвечает

**Comment by Woukim** [comment]
> не подхватывает и не отвечает

а что делать? как исправить :(

**Comment by Lein000** [comment]
можете не пытаться я доступ к api закрыл
