### ISSUE TITLE
GPT-4 Turbo Bing issue

### ISSUE THREAD

**Issue by Hinata29304** [xtekky/gpt4free#1730]
<img width="544" alt="Screenshot 2024-03-19 200447" src="https://github.com/xtekky/gpt4free/assets/143138230/49cd7c28-de9d-470a-80a4-b4cf9165118e">

g4f version: 0.2.6.1
Using VPN? Yes

**Comment by hlohaus** [comment]
Only some requests are without captcha. You can solve the captcha on the provider website. For my task with Bing. I need only some requests every hour.
