### ISSUE TITLE
gpt 3.5 turbo Poe issue

### ISSUE THREAD

**Issue by Hinata29304** [xtekky/gpt4free#1735]
<img width="566" alt="Screenshot 2024-03-20 163256" src="https://github.com/xtekky/gpt4free/assets/143138230/e394ff74-0bc0-48bf-80ec-74b230e91502">

g4f version: 0.2.6.1
Using VPN? Yes

**Comment by hlohaus** [comment]
This is stack trace from "undectable_chromedriver". The driver requirement are the problem.
There is a update with the name "nodriver".

**Comment by shashankshet** [comment]
This is the exact error 

<img width="833" alt="Screenshot 2024-03-21 at 8 35 01 PM" src="https://github.com/xtekky/gpt4free/assets/48438739/37123273-a4a8-4064-98f7-0066740cea45">
