### ISSUE TITLE
How to auth with HuggingChat provider?

### ISSUE THREAD

**Issue by eienmojiki206** [xtekky/gpt4free#1737]
Is there a way to authenticate when using models from the HuggingChat provider?

**Comment by hlohaus** [comment]
You could pass your cookies to the HuggingChat provider.
Then you are logged in.

**Comment by eienmojiki206** [comment]
> You could pass your cookies to the HuggingChat provider. Then you are logged in.

How about use it in Interference API?

**Comment by hlohaus** [comment]
You can add the set_cookies function to your start script. Then you can start the API with your cookies.
