### ISSUE TITLE
anyone have the variables to get this working on unraid?

### ISSUE THREAD

**Issue by osnapitsjoey** [xtekky/gpt4free#174]
cloned and installed repo, added container to docker page...but I dont know what variables to plug in

**Comment by blaisep** [comment]
I'm not a member of the team, but I want to make life easier for everyone If you want help, you need to provide more info.....Be kind to the maintainers and include some kind of error message. 
What is a docker page?
What commit of the repo did you install?

....If you think that the instructions are not clear then include a snippet with a suggestion of how to improve.

**Comment by osnapitsjoey** [comment]
Whoops. I meant docker file. Do I just need to add the port for a variable?
It just seemed too easy do I thought I did something wrong

**Comment by ali0902hmd** [comment]
Unsubscribe
