### ISSUE TITLE
Error in GUI when using an Image: An error occured: TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by OmiiiDev** [xtekky/gpt4free#1743]
I get this issue: An error occured: TypeError: Assignment to constant variable.
when i upload an image to bing or gemini and send it.

I am using the latest g4f version

**Comment by hlohaus** [comment]
I released a fix for the image upload in gui

**Comment by kainjinez** [comment]
The current 0.2.9.4 with the docker version still faces this issue.

**Comment by universewill** [comment]
> I released a fix for the image upload in gui

@hlohaus the error still exists. Any help here?

**Comment by HamzaYslmn** [comment]
![image](https://github.com/user-attachments/assets/d9bc74ee-62ca-4f4f-9533-fb366edae54e)
Still ı got error.
