### ISSUE TITLE
Add slider for mobile gui

### ISSUE THREAD

**Issue by iMahmoudz** [xtekky/gpt4free#1745]
I find difficulty when I'm using the GUI on smartphone, I can't go up and down with any slider.

You can add it to GUI in style.css

/* Style for scrollbar */
::-webkit-scrollbar {
    width: 10px; /* Width of the scrollbar */
}

/* Track */
::-webkit-scrollbar-track {
    background: #f1f1f1; /* Color of the track */
}

/* Handle */
::-webkit-scrollbar-thumb {
    background: #888; /* Color of the scrollbar handle */
    border-radius: 5px; /* Rounded corners of the handle */
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
    background: #555; /* Color of the handle when hovered */
}

Thank you!

**Comment by hlohaus** [comment]
I added the scrollbar styles. I used the colors from the theme.
