### ISSUE TITLE
An error occured: You: ResponseStatusError: Response 401: DFP telemetry ID not set   (Opus and Sonnet model)

### ISSUE THREAD

**Issue by Woukim** [xtekky/gpt4free#1746]
![image](https://github.com/xtekky/gpt4free/assets/138323639/2992375c-518c-42bc-851c-e6657f2ccd5e)

**Bug description**
 just start chat and got an error

**Environment**
last docker

**Comment by hlohaus** [comment]
You need a account for all models except gpt-3.5. The account creation may have changed. You.com is the only provider, who have a auto account creation in g4f. I don't like to create and new prov of the account creation. You can use a free account only 5x times. Maybe we can separate the account creation and the requests to the models?

**Comment by kirill670** [comment]
![image](https://github.com/xtekky/gpt4free/assets/51964569/5cda8633-75da-4682-927e-3eff70699508)
Same thing with You.

**Comment by rqi14** [comment]
Same problem

**Comment by BokDan93** [comment]
I agree, I have this problem too. Already tried changing the ip and server

**Comment by rqi14** [comment]
Any possibility to fix this?

**Comment by AksLolCoding** [comment]
i got a fix to work by creating an account in the browser and then loading those into g4f
i'm making a pr to implement this
but it requires you to be signed in already

**Comment by AksLolCoding** [comment]
I fixed the issue and created a [pull request](https://github.com/xtekky/gpt4free/pull/1794)
I tested that it works

**Comment by rqi14** [comment]
> I fixed the issue and created a [pull request](https://github.com/xtekky/gpt4free/pull/1794) I tested that it works

Thank you very much!
