### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by hasanelfalakiy** [xtekky/gpt4free#1751]
I'm a beginner, is gpt4free really free? So can it be made into a mobile application later?

**Comment by hlohaus** [comment]
I created a app, but the upload of files are not working.
Also i created a one file app for linux.
But both are not released jet.

**Comment by hasanelfalakiy** [comment]
> I created a app, but the upload of files are not working.
> Also i created a one file app for linux.
> But both are not released jet.

i want to make it into a car app but I don't really understand how it works

**Comment by hlohaus** [comment]
I use pywebview. It has a new android support. It uses Kivy with a python-to-android bridge. To run python you need only the python-to-android. To create a view, you can use Kivy for example.

**Comment by hasanelfalakiy** [comment]
> I use pywebview. It has a new android support. It uses Kivy with a python-to-android bridge. To run python you need only the python-to-android. To create a view, you can use Kivy for example.

Kivy is a framework, right? Just like flets, can also use flets, right?

**Comment by hasanelfalakiy** [comment]
> ```python
> def ask_me(query):
>     messages = [{"role": "user", "content": query}]
>     response =  g4f.ChatCompletion.create(
>         # model="gpt-4-turbo",
>         model=None,
>         provider=g4f.Provider.HuggingFace,
>         messages=messages
>     )
>     return response
> ```
> - **This is the base code**. Use **Different Provider** by changing `provider=`, and put your desired provider from the given in README.
> - If the provider **supports GPT-3.5** put `model="gpt-3.5-turbo"`, if **supports GPT-4** then `model="gpt-4-turbo"`. But if it **supports any other model** then put `model=None`.
> - In the message section you can put your previous conversation for the model, but keep it in the same format
> 
> I hope this will help you to get started 😊

thank you, This doesn't use a framework yet, right? is it still showing on the console?

**Comment by rmondal-official** [comment]
Take the response as text and display on your GUI framework 🤦‍♂️

**Comment by hasanelfalakiy** [comment]
> Take the response as text and display on your GUI framework 🤦‍♂️

oh okay I understand 😁
