### ISSUE TITLE
using VPN but can't get OpenaiChat working

### ISSUE THREAD

**Issue by albusmaxgrangerthu** [xtekky/gpt4free#1752]
My code for Openaichat is below, and i run into a ResponseStatusError: Response 403
`from g4f.client import Client
from g4f.Provider import RetryProvider, Bing, OpenaiChat, GeminiPro, Poe, You
import g4f.debug
g4f.debug.logging = True
import nest_asyncio
nest_asyncio.apply()

def handle_chat(prompt):
    response = g4f.ChatCompletion.create(
        model=g4f.models.default,
        provider=OpenaiChat,
        messages=[{"role": "user", "content": prompt}],
        auto_continue= "True", #OpenAi
        access_token="my_token", #get it from https://chat.openai.com/api/auth/session
        )
    return response
    
prompt='tell me a funny ai story'
message=handle_chat(prompt)
print(message)`

I thought it was because IP block stuff, so i used a vpn to route to Singapore and run the same code again, This time run into
ProviderNotWorkingError: OpenAI Plus Subscriber are not working

don't know what i should do when using a VPN, set a proxy first?
`set G4F_PROXY = "http://host:port"`
but i don't know how to set the exact host and port for my windows laptop

**Comment by hlohaus** [comment]
I fixed:
   ProviderNotWorkingError: OpenAI Plus Subscriber are not working
I added .har file support for OpenaiChat.
Simple download the .har file from the OpenAI Chat and place them in current dir ./ or in a sub dir.

**Comment by albusmaxgrangerthu** [comment]
Many thx! I will have a try now
