### ISSUE TITLE
Why does it keep showing "Please wait..."

### ISSUE THREAD

**Issue by t1w0n3e9e8e8git** [xtekky/gpt4free#176]
Why does it keep showing "Please wait..." after running "python3 -m streamlit run streamlit_app.py"? Thanks.

**Comment by BenSmithLight** [comment]
Try this `streamlit run streamlit_app.py`, I got nothing happend when using `python3 -m ...`.

**Comment by BenSmithLight** [comment]
> 


> Why does it keep showing "Please wait..." after running "python3 -m streamlit run streamlit_app.py"? Thanks.

Try this `streamlit run streamlit_app.py`, I got nothing happend when using `python3 -m ....`

**Comment by t1w0n3e9e8e8git** [comment]
Then how to fix the error  "bash: streamlit: command not found" when running "run streamlit_app.py"? Thanks.

**Comment by t1w0n3e9e8e8git** [comment]
Why does it show "An error occured, please make sure you are using a cf_clearance token and correct useragent | cf_clearance must be set, refer to documentation"? Tahnks.

**Comment by xtekky** [comment]
refer to documentation
