### ISSUE TITLE
Bing strange response when i use it

### ISSUE THREAD

**Issue by rocryptogroup** [xtekky/gpt4free#1761]
I'm having problems when I use Bing.
Usually i use bing gpt4 to research various topics, works a week ago but not now.
He did not want to access internet, it's not gpt-4-turbo because it's stupid.

CODE:

"""
from g4f.client import Client
from g4f.Provider import Bing

import g4f.debug
g4f.debug.logging = True
g4f.check_version = True

client = Client(
provider=Bing,
)

response = g4f.ChatCompletion.create(
    model="gpt-4-turbo",
    provider=g4f.Provider.Bing,
    messages=[{"role": "user", "content": "explain this article https://openai.com/blog/openai-elon-musk"}],
)
print(response)
"""
![Untitled](https://github.com/xtekky/gpt4free/assets/39518490/d3df2036-0a85-4a3e-b436-7ed685ee8e2d)

**prompt: Give me the Bitcoin price for today.**

![Untitled2](https://github.com/xtekky/gpt4free/assets/39518490/46f02ea6-5197-4cbe-8682-e7f89c5cc54d)

Environment

Windows 10
Anaconda
Python 3.9.13 (this is my application requirements)
Last version 0.2.7.1

What am I missing?

**Comment by zukixa** [comment]
https://twitter.com/emollick/status/1747091246860894479

**Comment by jesst3r** [comment]
Bing provider RIP :(
