### ISSUE TITLE
哪位大神能给个具体的示例RuntimeError: No .har file found错误

### ISSUE THREAD

**Issue by long202258** [xtekky/gpt4free#1773]
from g4f.client import Client as OpenAI
from g4f.client import Client
from g4f.Provider import BingCreateImages, OpenaiChat, Gemini

client = Client(
    provider=OpenaiChat,
    image_provider=Gemini,
    ...
)
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Say this is a test"}],
    ...
)
print(response.choices[0].message.content)
这个示例报错，RuntimeError: No .har file found，谁能给指点下，给个正确的示例代码

**Comment by hlohaus** [comment]
Please remove the following lines or modify them:
请删除以下行或修改它们:

```
provider=OpenaiChat,
image_provider=Gemini,
```

**Comment by eagle2021-web** [comment]
中国大陆能用吗 ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
