### ISSUE TITLE
Use the authless ChatGPT for gpt3.5-turbo

### ISSUE THREAD

**Issue by jawshoeadan** [xtekky/gpt4free#1776]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
You prob don't need any of the other providers now that it's officially supported by OpenAI

**Describe alternatives you've considered**
N/A

**Additional context**
https://twitter.com/OpenAI/status/1774848681981710821
https://openai.com/blog/start-using-chatgpt-instantly
Surprisingly this isn't an april fools joke

**Comment by jesst3r** [comment]
Arr matey! Time's come to hoist the Jolly Roger 🦜🏴‍☠️

**Comment by Ilyaprok** [comment]
any plans to integrate gpt3.5 from official site to gpt4free?

**Comment by hlohaus** [comment]
Good day,

I have implemented an authentication-free OpenAI Chat feature. Kindly review it at your earliest convenience.

Thank you.

**Comment by Invisibilities** [comment]
Keep getting cloudflare detected, how to solve this?
