### ISSUE TITLE
Problem with generating images when using Bing or Gemeni

### ISSUE THREAD

**Issue by ebullienc3** [xtekky/gpt4free#1779]
Hello. Both models are giving the same error: 
Error Message:Create images failed: we can't create your images right now

My tokens/accounts are valid.

**Comment by ebullienc3** [comment]
> The error message: we can't create your images right now are from Bing. For create images with Genimi you need a ip adress from outside europe.

Please add me in Discord, I will donate for the help. 
ebullienceog

**Comment by hlohaus** [comment]
Hey, I've sent you an invite
