### ISSUE TITLE
about Smartphone

### ISSUE THREAD

**Issue by kpsmail** [xtekky/gpt4free#1782]
![1712145250991](https://github.com/xtekky/gpt4free/assets/156741049/16c64de5-5fcc-48c6-afa3-6353b4083bac)
![1712145250952](https://github.com/xtekky/gpt4free/assets/156741049/cd0f5fa5-6ffe-4c41-a256-b1716c58b7e6)
![1712145251004](https://github.com/xtekky/gpt4free/assets/156741049/9cf58555-558a-4372-9071-925e8a8a80ac)
![1712145250972](https://github.com/xtekky/gpt4free/assets/156741049/e352780a-47bf-435c-b9a6-6a710fa1c96f)

Are there any more detailed steps on the mobile phone? After I executed the code, it looked like this. doesn't seem to work。

**Comment by hlohaus** [comment]
I fixed the issue on the smartphone. Please update the g4f package.

**Comment by George-Seven** [comment]
Try Termux, it's more compatible -

https://github.com/xtekky/gpt4free/issues/1107#issuecomment-2041214520
