### ISSUE TITLE
Gemini broken?

### ISSUE THREAD

**Issue by ayonovdenizs** [xtekky/gpt4free#1784]
**Bug description**
Gemini does not work. All data is correct. Error log:

> >>> completion_createv2('bard', 'say test', 'hello', 231231)
> Using Gemini provider and gemini model
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\проекты\chatgptbot\settings_db.py", line 171, in completion_createv2
>     req = g4f.ChatCompletion.create(model=g4f.models.gemini, auth={
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\проекты\chatgptbot\venv\Lib\site-packages\g4f\__init__.py", line 149, in create
>     return result if stream else ''.join([str(chunk) for chunk in result])
>                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\проекты\chatgptbot\venv\Lib\site-packages\g4f\providers\base_provider.py", line 206, in create_completion
>     yield loop.run_until_complete(await_callback(gen.__anext__))
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\kupur\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "C:\проекты\chatgptbot\venv\Lib\site-packages\g4f\providers\base_provider.py", line 202, in await_callback
>     return await callback()
>            ^^^^^^^^^^^^^^^^
>   File "C:\проекты\chatgptbot\venv\Lib\site-packages\g4f\Provider\needs_auth\Gemini.py", line 96, in create_async_generator
>     raise RuntimeError("Invalid auth. SNlM0e not found")
> RuntimeError: Invalid auth. SNlM0e not found

**Environment**
- Python 3.12.2 (venv)

**Comment by mrbuslov** [comment]
You should copy all of your cookies, that start with `__Secure-1PSID`
To find cookies, follow these steps:

- login into the account [gemini.google.com/app](https://gemini.google.com/app)
- F12 > Applications > Cookies > accounts... or gemini...  > Filter (input) > __Secure-1PSID

Example (insert it before `client.images.generate` as pointed in tutorial readme)
```
set_cookies(
    ".google.com",
    {
        "__Secure-1PSID": "g.a000hwiteqQb...0076",
        "__Secure-1PSIDCC": "AKEy...Xl8dc7g",
        "__Secure-1PSIDTS": "sidts-CjEB...SEAA"
    },
)
```

**Comment by Allamaris0** [comment]
> You should copy all of your cookies, that start with `__Secure-1PSID` To find cookies, follow these steps:
> 
> * login into the account [gemini.google.com/app](https://gemini.google.com/app)
> * F12 > Applications > Cookies > accounts... or gemini...  > Filter (input) > __Secure-1PSID
> 
> Example (insert it before `client.images.generate` as pointed in tutorial readme)
> 
> ```
> set_cookies(
>     ".google.com",
>     {
>         "__Secure-1PSID": "g.a000hwiteqQb...0076",
>         "__Secure-1PSIDCC": "AKEy...Xl8dc7g",
>         "__Secure-1PSIDTS": "sidts-CjEB...SEAA"
>     },
> )
> ```

```
set_cookies(
    ".google.com",
    {
        "__Secure-1PSID": google_cookie1,
        "__Secure-1PSIDCC": google_cookie2,
        "__Secure-1PSIDTS": google_cookie3
    },
)

client = Client()
response = client.chat.completions.create(
    model="gemini",
    messages=[{"role": "user", "content": "Hello"}],
)
print(response.choices[0].message.content)

```

And I get error:
```
Traceback (most recent call last):
  File "C:\Users\Emilia\PycharmProjects\freegpt\gptforfree.py", line 19, in <module>
    response = client.chat.completions.create(
  File "C:\Users\Emilia\PycharmProjects\freegpt\venv\lib\site-packages\g4f\client\client.py", line 114, in create
    return response if stream else next(response)
  File "C:\Users\Emilia\PycharmProjects\freegpt\venv\lib\site-packages\g4f\client\client.py", line 53, in iter_append_model_and_provider
    for chunk in response:
  File "C:\Users\Emilia\PycharmProjects\freegpt\venv\lib\site-packages\g4f\client\client.py", line 28, in iter_response
    for idx, chunk in enumerate(response):
  File "C:\Users\Emilia\PycharmProjects\freegpt\venv\lib\site-packages\g4f\providers\base_provider.py", line 216, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
  File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Emilia\PycharmProjects\freegpt\venv\lib\site-packages\g4f\providers\base_provider.py", line 45, in await_callback
    return await callback()
  File "C:\Users\Emilia\PycharmProjects\freegpt\venv\lib\site-packages\g4f\Provider\needs_auth\Gemini.py", line 177, in create_async_generator
    response_part = json.loads(json.loads(response.splitlines()[-5])[0][2])
  File "C:\Python310\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```
