### ISSUE TITLE
Streaming in sentences instead of words possible? Error with example

### ISSUE THREAD

**Issue by plia7** [xtekky/gpt4free#1787]
Hello,

I was trying to follow the streaming example in the documentation and created this script:

```
from g4f.client import Client
from g4f.Provider import OpenaiChat

def main():
   stream = g4f.chat.completions.create(
     model=g4f.models.default,
     messages=[{"role": "user", "content": "What is Crazy Taxi?"}],
     stream=True,
   )
   for chunk in stream:
     if chunk.choices[0].delta.content:
        print(chunk.choices[0].delta.content or "", end="")
```

But when I run this, I get this error:

AttributeError: 'str' object has no attribute 'choices'

So instead of chunk.choices[0].delta.content 
I print chunk, but that is just a single word. There could be 400-500 chunks/words in this case (depends on the answer length).

How can I print one whole sentence at a time instead of printing one word at a time?

Do you have any suggestions how to achieve that?

Thank you.

**Comment by Anonymous6598** [comment]
try: 
```python
for message in in stream:
      print(message, end="")
```

**Comment by plia7** [comment]
> try: 
> 
> ```python
> 
> for message in in stream:
> 
>       print(message, end="")
> 
> ``` 

Is this different than

for chunk in stream
    print(chunk, end="")

You use there two "in" is that on purpose?

Thanks.

**Comment by hlohaus** [comment]
Use this example from the readme:

```python
from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Hello"}],
    ...
)
print(response.choices[0].message.content)
```

**Comment by plia7** [comment]
> Use this example from the readme:
> 
> ```python
> from g4f.client import Client
> 
> client = Client()
> response = client.chat.completions.create(
>     model="gpt-3.5-turbo",
>     messages=[{"role": "user", "content": "Hello"}],
>     ...
> )
> print(response.choices[0].message.content)
> ```

But you're not passing stream=True in your snippet?
Is this example for non-streaming?

**Comment by hlohaus** [comment]
Hello, you can make a generator for your response.

Here's how you do it:

```python
def my_generator(iter):
    buffer = ""
    for chunk in iter:
        buffer += chunk
        if "\n" in buffer:
            yield buffer
            buffer = "'"
    if buffer:
        yield buffer
```

And the chat completion response has choises like OpenAI has.

**Comment by plia7** [comment]
> Hello, you could make a generator for your response.
> 
> Here's how you do it:
> 
> ```python
> def my_generator(iter):
>     buffer = ""
>     for chunk in iter:
>         buffer += chunk
>         if "\n" in buffer:
>             yield buffer
>             buffer = ""
>     if buffer:
>         yield buffer
> ```
> 
> And the chat completion response has choises like OpenAI has.

Is this for stream equals true or not?

The choices attribute doesn't exist. Do I need to import something or could it be the structure changed for it?

Thanks.
