### ISSUE TITLE
An error occured: OpenaiChat: ResponseStatusError: Response 403: Bot are detected

### ISSUE THREAD

**Issue by Woukim** [xtekky/gpt4free#1791]
**Bug description**
![image](https://github.com/xtekky/gpt4free/assets/138323639/0952de0f-c67a-4764-a8f2-e1604b14e87f)

0.2.8.0 version

**Environment**
docker

**Comment by hlohaus** [comment]
You could try modifying the request headers. Although there is no configuration yet, this solution has been effective in resolving similar issues for me.

**Comment by Woukim** [comment]
> You could try modifying the request headers. Although there is no configuration yet, this solution has been effective in resolving similar issues for me.

Okay, but how exactly do I do that?

**Comment by Anonymous6598** [comment]
The same issue. Reinstalled curl_cffi - didn't work

**Comment by diro-atk** [comment]
The same issue. There is a solution ?

**Comment by diro-atk** [comment]
Version 0.2.7.0 works without errors

**Comment by notsungod** [comment]
I have the same issue :(

**Comment by karlovm** [comment]
same issue
