### ISSUE TITLE
'utf-8' codec can't decode byte 0xd0 in position 139: unexpected end of data

### ISSUE THREAD

**Issue by Tefosu** [xtekky/gpt4free#1793]
**Bug description**
When I run the code and send a request to the provider, an exception occurs.
*'utf-8' codec can't decode byte 0xd0 in position 139: unexpected end of data*

**Code**
```python
def gpt(text):
    try:
     #  print("Готов.")
       history["main"].append({"role": "user", "content": text})
       result = g4f.ChatCompletion.create(model="gpt-3.5-turbo",
       provider=g4f.Provider.FreeGpt,
       messages=history["main"])
       history["main"].append({"role": "assistant", "content": str(result)})
       return result
    except Exception as e:
       return e
       if len(history["main"])!=0:
           history["main"].pop((len(history["main"])-1))
       else: history["main"]=[]
```
**Environment**
- Python Version: 3.11.4 (aarch64 )
- Country: Russian Federation.
- G4F Version: 0.2.8.0 (Latest)

**Comment by hlohaus** [comment]
I added a errors="ignore" to every sting.decode() i found.
This issue should now be solved.
