### ISSUE TITLE
Service 'gpt4free' failed to build: The command '/bin/sh -c if [ "$G4F_VERSION" = "" ] ; then   sudo apt-get -qqy update &&   sudo apt-get -qqy install git   ; fi' returned a non-zero code: 100

### ISSUE THREAD

**Issue by cryptoshell33** [xtekky/gpt4free#1798]
Hi,
    I had ONE issue on my mac when using Docker and running command docker-compose build. Then I get some errors:

Building gpt4free
Step 1/41 : FROM seleniarm/node-chromium
 ---> d2261ccd1d32
Step 2/41 : ARG G4F_VERSION
 ---> Using cache
 ---> 3ea406f4d46e
Step 3/41 : ARG G4F_USER=g4f
 ---> Using cache
 ---> 2213df9cdaba
Step 4/41 : ARG G4F_USER_ID=1000
 ---> Using cache
 ---> b9a28c6dc830
Step 5/41 : ARG G4F_NO_GUI
 ---> Using cache
 ---> 6eb823f31c4c
Step 6/41 : ARG G4F_PASS=secret
 ---> Using cache
 ---> 92e907c6d078
Step 7/41 : ENV G4F_VERSION $G4F_VERSION
 ---> Using cache
 ---> 5e78fa5fe9dd
Step 8/41 : ENV G4F_USER $G4F_USER
 ---> Using cache
 ---> 105cc6572712
Step 9/41 : ENV G4F_USER_ID $G4F_USER_ID
 ---> Using cache
 ---> 2cc02f0ccd6a
Step 10/41 : ENV G4F_NO_GUI $G4F_NO_GUI
 ---> Using cache
 ---> fd1e88f0de43
Step 11/41 : ENV SE_SCREEN_WIDTH 1850
 ---> Using cache
 ---> 84f536295381
Step 12/41 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> f51802006a37
Step 13/41 : ENV G4F_DIR /app
 ---> Using cache
 ---> 0c782fda4b72
Step 14/41 : ENV G4F_LOGIN_URL http://localhost:7900/?autoconnect=1&resize=scale&password=$G4F_PASS
 ---> Using cache
 ---> 39184f8c1869
Step 15/41 : ENV HOME /home/$G4F_USER
 ---> Using cache
 ---> 426de5cc0a65
Step 16/41 : ENV PATH $PATH:$HOME/.local/bin
 ---> Using cache
 ---> 00138714ec47
Step 17/41 : ENV SE_DOWNLOAD_DIR $HOME/Downloads
 ---> Using cache
 ---> 10891b3d9ae8
Step 18/41 : ENV SEL_USER $G4F_USER
 ---> Using cache
 ---> 75ccc791e237
Step 19/41 : ENV SEL_UID $G4F_USER_ID
 ---> Using cache
 ---> fd630b0b28bb
Step 20/41 : ENV SEL_GID $G4F_USER_ID
 ---> Using cache
 ---> f1dee9afc417
Step 21/41 : USER root
 ---> Using cache
 ---> 4c16a3cf9bc7
Step 22/41 : RUN if [ "$G4F_VERSION" = "" ] ; then   sudo apt-get -qqy update &&   sudo apt-get -qqy install git   ; fi
 ---> Running in 892ee66c5a92
W: GPG error: http://deb.debian.org/debian sid InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian sid InRelease' is not signed.
W: GPG error: https://packages.adoptium.net/artifactory/deb bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 843C48A565F8F04B
E: The repository 'https://packages.adoptium.net/artifactory/deb bookworm InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
ERROR: Service 'gpt4free' failed to build: The command '/bin/sh -c if [ "$G4F_VERSION" = "" ] ; then   sudo apt-get -qqy update &&   sudo apt-get -qqy install git   ; fi' returned a non-zero code: 100

Environment
  Docker Community Edition (Version 18.06.1-ce-mac73 (26764))
  macOS 10.15.6

How can I resolve this issue?

**Comment by hlohaus** [comment]
Good day, this may be a transient issue. Please try again at a later time.

Alternatively, you may utilize a pre-built Docker image.

Simply execute the Docker run command provided in the Readme.
