### ISSUE TITLE
An error occured, please make sure you are using a cf_clearance token and correct useragent | Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by cheng-orange** [xtekky/gpt4free#180]
Hello
I would like to know if this project can run locally?
I tried to run it on both Windows and Ubuntu operating systems, and filled in the corresponding cf_clearance and useragent, but it didn't seem to work.

**Comment by cheng-orange** [comment]
> The solution is here [#171 (comment)](https://github.com/xtekky/gpt4free/issues/171#issuecomment-1524337883)

I tried a few hours before submitting the question, but it seems to be of no use to me.

**Comment by wenpeng-desyn** [comment]
I have a same error, and also have setted cf_clearance and useragent, but it still report error

**Comment by shubhamwagh** [comment]
Check this #153 , phoned.com has been taken down I think.

**Comment by YPB123** [comment]
应该是ip被禁了，估计得换节点。
我在作者的脚本里加了代码调试。
![image](https://user-images.githubusercontent.com/34567359/234826607-40322683-f9d5-4a7e-90c8-4c2b14cef217.png)
最终表现是 phind的接口返回403
![image](https://user-images.githubusercontent.com/34567359/234826977-b2be35fb-6f6e-4744-b1b0-9f89fb31d8d3.png)
