### ISSUE TITLE
About grabbing audio from openai 

### ISSUE THREAD

**Issue by rocryptogroup** [xtekky/gpt4free#1803]
I was looking at all AIs (OpenAI/Google/Bard) noticing the voice button. 
![Untitled](https://github.com/xtekky/gpt4free/assets/39518490/9def967d-87b4-48e0-a365-50ba4a6b81b5)

Is there any possibility to obtain audio through cookie API?

**Comment by AksLolCoding** [comment]
Yes, there is an (API)[https://platform.openai.com/docs/guides/text-to-speech] for this that you can use.

**Comment by hlohaus** [comment]
You can run it in your browser. But i don't found a good example jet.
