### ISSUE TITLE
Bug / Error: Network is unreachable

### ISSUE THREAD

**Issue by TheSashaDev** [xtekky/gpt4free#1805]
**Bug description**
I'm using pythonanywhere and ran my server.
After connecting to it I saw:
{'response': 'Error: Cannot connect to host chat.openai.com:443 ssl:default [Network is unreachable]'}

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/132156447/1928193a-65a2-400a-ad78-ef33a46ee396)

**Environment**
- pythonanywhere = 3.10.5
- my = 3.10.11

**Comment by AksLolCoding** [comment]
Free pythonanywhere accounts can only access sites on this [whitelist](https://www.pythonanywhere.com/whitelist/).
