### ISSUE TITLE
New Provider: DuckDuckGo AI

### ISSUE THREAD

**Issue by Steve78392** [xtekky/gpt4free#1806]
Browser URL: https://duckduckgo.com/?t=fpas&q=example&ia=chat
Models: GPT-3.5-turbo, Claude 1.2 Instant

**Comment by TheSashaDev** [comment]
I NEED Claude 1.2 Instant

**Comment by TheSashaDev** [comment]
I AM CREATING A GAME WITH MY ICT TEACHER ABOUT DOG AI CHAT AND I NEED FASTEST RESPONSES

**Comment by hlohaus** [comment]
I am working on a DuckDuckGoProvider. The API has only 2 request parameter. Messages and Model

**Comment by dene-** [comment]
Unfortunately you can only send a first message with an "user" role, subsequent messages need to be tied to newly created `x-vqd-4` headers that come from the chat responses 🤔

**Comment by Steve78392** [comment]
:(

**Comment by hlohaus** [comment]
Hey, I just added support for conversations and integrated it into the web GUI.
