### ISSUE TITLE
Get provider parameters

### ISSUE THREAD

**Issue by chekamarue** [xtekky/gpt4free#1808]
How we can get the parameters for a specific provider ? since  print(g4f.Provider.provider_name.params) is not working !

**Comment by AksLolCoding** [comment]
Internally, each provider calls the `provider.create_async_generator` function and the parameters to this function are what you are looking for. You can get these parameters and their default values as follows:
```python
provider = g4f.Provider.provider_name_here
parameters = provider.create_async_generator.__code__.co_varnames # tuple of parameter names
```

**Comment by hlohaus** [comment]
The bug in g4f.Provider...params has been resolved. It will be available for use shortly.

**Comment by chekamarue** [comment]
fixed
