### ISSUE TITLE
 No module named 'phind'

### ISSUE THREAD

**Issue by Rs529811807** [xtekky/gpt4free#181]
No module named 'phind'

**Comment by Rs529811807** [comment]
ModuleNotFoundError: No module named 'phind'
Traceback:
File "C:\Users\rs\AppData\Roaming\Python\Python310\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "C:\Users\rs\Desktop\免费chatgpt4使用微信公众号【小莫理】\gpt4free\gui\streamlit_app.py", line 2, in <module>
    import phind

**Comment by arronKler** [comment]
> ModuleNotFoundError: No module named 'phind' Traceback: File "C:\Users\rs\AppData\Roaming\Python\Python310\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script exec(code, module.**dict**) File "C:\Users\rs\Desktop\免费chatgpt4使用微信公众号【小莫理】\gpt4free\gui\streamlit_app.py", line 2, in import phind

把你的 streamlit_app.py 文件从 gui 里面移出来

**Comment by Rs529811807** [comment]
thanks

**Comment by Rs529811807** [comment]
@arronKler 多谢。但是运行起来后，无法链接测试。没数据的
