### ISSUE TITLE
Version 0.2.9.3 now detected Microsoft Defender is Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by TheFirstNoob** [xtekky/gpt4free#1818]
Hi! Latest update now detected Microsoft Defender is Trojan:Script/Wacatac.B!ml.
File: gpt4free-0.2.9.3/g4f/gui/client/index.html
Previous versions works correctly. I think is false alarm but maybe is fixeble.

**Comment by TheFirstNoob** [comment]
Ok, i reinstall Defender Database for new (latest) version and still false alarm on all previous versions but VT say All fine... I think issues can close because is localy false alarm and all fine on code.


zip file full:
https://www.virustotal.com/gui/file/5cbec9e594b8cabd3ecefdd75a406bda360f0f63991ea419219ccd233f4dc2f1

Index.html
https://www.virustotal.com/gui/file/eee217e95e48feac52a130f24703d430af56f64e6a460b79d688c05e6d7e053f?nocache=1

**Comment by xtekky** [comment]
Yes, this is likely a false alarm because the file `gpt4free-0.2.9.3/g4f/gui/client/index.html`, is just pure html.
