### ISSUE TITLE
new provider : ecosia

### ISSUE THREAD

**Issue by BenchBadr** [xtekky/gpt4free#1838]
Hello everyone, I am not sure if this is the right place but there is a new provider available with no auth : https://www.ecosia.org/chat?q=Hello 

It seems like it doesn't check for bots (at least, for now) I did some attempts with Playwright and didn't get any issue.

Hope it helps!

Btw, when will `OpenAiChat` provider will be used with no auth as of the new update that doesn't require signing in anymore ?

Thanks a lot for your hard work!

**Comment by alluding** [comment]
> Hello everyone, I am not sure if this is the right place but there is a new provider available with no auth : https://www.ecosia.org/chat?q=Hello
> 
> It seems like it doesn't check for bots (at least, for now) I did some attempts with Playwright and didn't get any issue.
> 
> Hope it helps!
> 
> Btw, when will `OpenAiChat` provider will be used with no auth as of the new update that doesn't require signing in anymore ?
> 
> Thanks a lot for your hard work!

The messages inside the payload are just base64 encoded.

**Comment by hlohaus** [comment]
Hey, I added Ecosia in the latest release. You can enable the eco mode by setting "green" to True.
