### ISSUE TITLE
An error occured, please make sure you are using a cf_clearance token and correct useragent | cf_clearance must be set, refer to documentation

### ISSUE THREAD

**Issue by yccn1314** [xtekky/gpt4free#184]

**Comment by yeahno** [comment]
same question

**Comment by LiDongDong1996** [comment]
I also encounter this question.

**Comment by mkile** [comment]
Same here.

**Comment by vincke** [comment]
An error occured, please make sure you are using a cf_clearance token and correct useragent | cf_clearance must be set, refer to documentation

**Comment by wangcy727** [comment]
An error occured, please make sure you are using a cf_clearance token and correct useragent | cf_clearance must be set, refer to documentation

**Comment by yeahno** [comment]
i tried it refer by https://github.com/xtekky/gpt4free/issues/171，something are right, but another error occured.

**Comment by Dev-it-a-dev** [comment]
> i tried it refer by [https://github.com/xtekky/gpt4free/issues/171，something](https://github.com/xtekky/gpt4free/issues/171%EF%BC%8Csomething) are right, but another error occured.

I had problems to make it work with Firefox, Changed to Chrome and it worked fine.

**Comment by yeahno** [comment]
> > i tried it refer by [https://github.com/xtekky/gpt4free/issues/171，something](https://github.com/xtekky/gpt4free/issues/171%EF%BC%8Csomething) are right, but another error occured.
> 
> I had problems to make it work with Firefox, Changed to Chrome and it worked fine.

it's a very useful message, but i'm abandoned, why don't i use phind directly? 😄

**Comment by bargantokgoz** [comment]
I found how to solve it. Open [phib](https://www.phind.com/) , take cf_clearance from cookies ( dev console, applications, storage, cookies), get your user.agent ( just google my user.agent) and add this to streamlit_app.py. Restart app.

**Comment by shubhamwagh** [comment]
Check this #153 , phind.com has been taken down I think.

**Comment by adai5210** [comment]
1，“请确保您使用的是 cf_clearance 令牌和正确的用户代理 | 必须设置 cf_clearance，请参阅文档”和“请确保您使用的是 cf_clearance 令牌和正确的用户代理 | 期望值：第 1 行第 1 列（字符 0）” 是两种类型的错误。
2.cf_clearance会周期性变化，而且user_agent一定要和自己的浏览器匹配，cf_clearance或user_agent错误，均会导致“请确保您使用的是 cf_clearance 令牌和正确的用户代理 | 必须设置 cf_clearance”报错。
3.中国的朋友登录https://www.phind.com/，会使用代理，代理的设置配置不正确会导致“请确保您使用的是 cf_clearance 令牌和正确的用户代理 | 期望值：第 1 行第 1 列（字符 0）”报错，使用代理的碰，在自己使用时，需要TUN模式
