### ISSUE TITLE
Async client doesn't behave the same as sync client

### ISSUE THREAD

**Issue by azowrle** [xtekky/gpt4free#1840]
**Bug description**
Firstly, there is a bug in async client when I pass image parameter to Bing provider, it doesn't receive it. After going through the code I see that comma is missing in *kwargs. Screenshot bellow.

Also async client is not behaving the same as sync client for Bing provider, proxy is timing out and it's throwing error of: "No reusable session"

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/40940156/503567fc-9574-4fbc-8b10-32149072ded5)

**Environment**
Python 3.8

**Additional context**
I am using HQ residental proxies for my requests. Sync client is working perfectly, async has issues. Please guys look into this request I beg you!

**Comment by xtekky** [comment]
this was solved did not push it to pypi yet, will do that now

**Comment by azowrle** [comment]
> this was solved did not push it to pypi yet, will do that now

Hey thanks for that. Do you know also why the async client is throwing this error: "Response 404: Do less requests and reuse conversations"

I tried same config as the sync client and the sync client does work for me, but the async is getting 404 status for some reason.

Does the request differ in any way from the sync client?

I am using the same proxies for both.

**Comment by azowrle** [comment]
> The error: "Response 404: Do less requests and reuse conversations" are from the Microsoft Firewall.
> Passing other cookies helps for example. 

I am literally passing cookies={} as empty dict so that it doesn't pull any cookies from my browser. The request fails in async client, but doesn't fail in sync client.

I am using the same proxies, same parameters, everything.

Error is easily reproducable:
1. Pass a proxy to the client
2. Try to create chat completion using async client and then one using sync client
3. Async client fails with "Do less requests and reuse conversations"

**Comment by hlohaus** [comment]
Wait some time also helps passing the firewall. Maybe is that the reason that it works / not works sometimes.

**Comment by hlohaus** [comment]
Nah, I don't think the behavior is different. The AsyncClient is just a copy of the Client with some "async" and "await"s and no event loop. And the bug with the kwargs is fixed.
