### ISSUE TITLE
stopped working after the release of update 0.2.9.9

### ISSUE THREAD

**Issue by VladimirKarpenkoMain** [xtekky/gpt4free#1842]
**Bug description**
On-demand generation stopped working after the release of update 0.2.9.9, it doesn’t work even on older versions, depending on the provider there are different errors from 403, 404 to problems with curl.  Before the library was updated everything worked

```
def generate_comment(product):
    try:
        response = client.chat.completions.create(
            model=config['MODEL'],
            messages=[
                {
                    "role": config['ROLE'],
                    "content": f"{config['PROMPT']} {product}."
                }
            ],
        )
        comment = response.choices[0].message.content.strip()
        cleaned_comment = comment.replace('"', '')
        return cleaned_comment
    except Exception as e:
        logging.error(f"Ошибка при генерации комментария: {e}")
        return ""
```

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/148718679/0ac158fd-4d4a-453c-b7ca-7ea84c6f61da)

**Environment**
- python 3.11
- location Russia

**Comment by fL0P1337** [comment]
Vladimir, the problem should be on the providers side, not the g4f. Before it worked because you semeed to use Chatgptnext provider, that have request cooldown

**Comment by VladimirKarpenkoMain** [comment]
Thank you, I already realized that the problem is in my location, but it’s just strange that it was after the update that everything broke, and before the update everything worked
