### ISSUE TITLE
Gemini : {"error": "Invalid auth. SNlM0e not found"}

### ISSUE THREAD

**Issue by chekamarue** [xtekky/gpt4free#1847]
Using Gemini provider ! am getting! {"error": "Invalid auth. SNlM0e not found"}

couldn't find that cookies value 

Here my cookies structure 
```
cookies={
  #google
        "__Secure-1PSID": "g.a*",
        "__Secure-1PSIDCC": "*",
        "__Secure-1PSIDTS": "*",
        "__Secure-3PAPISID": "*",
        "__Secure-3PSID": "g.a*",
        "__Secure-3PSIDCC": "*",
        "__Secure-3PSIDTS": "*",
    }
```

**Comment by mrbuslov** [comment]
You should copy all of your cookies, that start with `__Secure-1PSID`
To find cookies, follow these steps:

- login into the account [gemini.google.com/app](https://gemini.google.com/app)
- F12 > Applications > Cookies > accounts... or gemini...  > Filter (input) > __Secure-1PSID

Example (insert it before `client.images.generate` as pointed in tutorial readme)
```
set_cookies(
    ".google.com",
    {
        "__Secure-1PSID": "g.a000hwiteqQb...0076",
        "__Secure-1PSIDCC": "AKEy...Xl8dc7g",
        "__Secure-1PSIDTS": "sidts-CjEB...SEAA"
    },
)
```
