### ISSUE TITLE
https://chat.chatbot.sex/chat/ does not work at all

### ISSUE THREAD

**Issue by rozek** [xtekky/gpt4free#185]
I just wanted to give `https://chat.chatbot.sex/chat/` a try but failed completely:

* whenever I enter a prompt and press the "send" button, nothing happens

(more precisely: the browser console does not log any outgoing network request)

Before, I already got several error messages in the browser console, the most important seem to be

```
Failed to load resource: the server responded with a status of 403 () site.webmanifest:1
Manifest: Line: 1, column: 1, Syntax error. site.webmanifest:1
```

**Comment by Ro0tk1t** [comment]
same
