### ISSUE TITLE
I`m trying to use your api in my c# project but I am getting 422

### ISSUE THREAD

**Issue by TarasKo444** [xtekky/gpt4free#1858]
<pre>using System.Text;
using System.Text.Json;

using var client = new HttpClient();

var obj = new Request();
var json = JsonSerializer.Serialize(obj);

Console.WriteLine(json);

var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:1337/v1/chat/completions")
{
    Content = new StringContent(json, Encoding.UTF8, "application/x-www-form-urlencoded"),
};

var response = await client.SendAsync(request);

var res = await response.Content.ReadAsStringAsync();
Console.WriteLine(res);
Console.WriteLine(response);

class Request
{
    public string model { get; set; } = "gpt-3.5-turbo";
    public string provider { get; set; } = "FreeGpt";
    public float temperature { get; set; } = 0.5f;
    public bool stream { get; set; } = false;
    public Message[] messages { get; set; } = { new Message() };
}

class Message
{
    public string role { get; set; } = "assistant";
    public string content { get; set; } = "What can you do?";
}</pre>

Output: 
`{"detail":[{"loc":["body"],"message":"Input should be a valid dictionary or object to extract fields from","type":"model_attributes_type"}]}
StatusCode: 422, ReasonPhrase: 'Unprocessable Entity', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Thu, 18 Apr 2024 18:49:02 GMT
  Server: uvicorn
  Content-Length: 140
  Content-Type: application/json
}
`

**Comment by Hydra566** [comment]
@TarasKo444 Друг, ты отправляешь json, а тип данных у тебя указан "application/x-www-form-urlencoded", а должен быть "application/json".

```c#
Content = new StringContent(json, Encoding.UTF8, "application/json"),
```

**Comment by TarasKo444** [comment]
> @TarasKo444 Друг, ты отправляешь json, а тип данных у тебя указан "application/x-www-form-urlencoded", а должен быть "application/json".
> 
> ```cs
> Content = new StringContent(json, Encoding.UTF8, "application/json"),
> ```

емае, я до этого пробовал с жсон, было 422, я сделал несколько изменений, а x-www-form-urlencoded не поменял

Спасибо

**Comment by Hydra566** [comment]
> > @TarasKo444 Друг, ты отправляешь json, а тип данных у тебя указан "application/x-www-form-urlencoded", а должен быть "application/json".
> > ```cs
> > Content = new StringContent(json, Encoding.UTF8, "application/json"),
> > ```
> 
> емае, я до этого пробовал с жсон, было 422, я сделал несколько изменений, а x-www-form-urlencoded не поменял
> 
> Спасибо

Ооо, и тут русские =) Да не за что, главное что бы заработало.
