### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by notsungod** [xtekky/gpt4free#1859]
Hey guys i followed [the text-generation guide](https://github.com/xtekky/gpt4free#text-generation) of the README and it works like a charm i love it.
But with my python-lsp i get an error that i dont understand:
`Cannot access attribute "choices" for class "Iterator[ChatCompletionChunk]" Pyright (reportAttributeAccessIssue) [25, 23]
 │        Attribute "choices" is unknown `.
Its specifically from this line: `response.choices[0].message.content`. What exactly is this? Sorry if Im asking in the wrong place :(. Thanks for answering!

**Comment by hlohaus** [comment]
Hello. 
Remove stream=True or iterate the response.

**Comment by notsungod** [comment]
Where is this stream=True? I dont have one in my code.When i iterate like `for i in response.choices;` the error persists.

**Comment by hlohaus** [comment]
You need:

async for chunk in response

**Comment by hlohaus** [comment]
What are the error messages?
What do you see when you type:

print(response)

**Comment by notsungod** [comment]
it works as expected. maybe its a pyright issue (lsp)?
