### ISSUE TITLE
CaptchaChallenge: User needs to solve CAPTCHA to continue

### ISSUE THREAD

**Issue by sunqiuming526** [xtekky/gpt4free#1866]
**Bug description**
When using GPT-4 Turbo via Bing, the error "Bing: Retry: CaptchaChallenge: User needs to solve CAPTCHA to continue" frequently occurs. Maybe using curl_cffi.requests.AsyncSession instead of aiohttp.ClientSession might mitigate the issue.

**Screenshots**
<img width="612" alt="Snipaste_2024-04-20_21-28-59" src="https://github.com/xtekky/gpt4free/assets/21358630/29a3c7c5-6aee-4853-82af-402f7be88206">

**Comment by hlohaus** [comment]
Hey, I added more cookies for Bing. The issue you mentioned should be fixed now. Can you try again and let me know if it works?

**Comment by sunqiuming526** [comment]
> Hey, I added more cookies for Bing. The issue you mentioned should be fixed now. Can you try again and let me know if it works?

@hlohaus Hi! Yes it works now! thx so much
