### ISSUE TITLE
liaobots does not work

### ISSUE THREAD

**Issue by skullcrushercmd** [xtekky/gpt4free#1868]
**Known Issues** // delete this
- you.com issue / fix: use proxy, or vpn, your country is probably flagged
- forefront account creation error / use your own session or wait for fix

**Bug description**
What did you do, what happened, which file did you try to run, in which directory
Describe what you did after downloading repo, such as moving to this repo, running this file.

ex.

**Screenshots**

**Environment**
- python version
- location ( are you in a cloudfare flagged country ) ?

**Additional context**

tried it, gets this error (authentication error) when requesting to https://liaobots.work/api/user 

{"code":200,"msg":"success","data":"Too many requests"}

**Comment by skullcrushercmd** [comment]
totally wasnt tryna recreate it in js and just now found out it doesnt even work in g4f 💀

**Comment by skullcrushercmd** [comment]
const axios = require('axios');
const { v4: uuidv4 } = require('uuid');
const { wrapper: axiosCookieJarSupport } = require('axios-cookiejar-support');
const { CookieJar } = require('tough-cookie');
const https = require('https');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
const models = {
    "gpt-3.5-turbo": {
        "id": "gpt-3.5-turbo",
        "name": "GPT-3.5-Turbo",
        "maxLength": 48000,
        "tokenLimit": 14000,
        "context": "16K",
    },
    "gpt-4-turbo": {
        "id": "gpt-4-turbo-preview",
        "name": "GPT-4-Turbo",
        "maxLength": 260000,
        "tokenLimit": 126000,
        "context": "128K",
    },
    "gpt-4": {
        "id": "gpt-4-plus",
        "name": "GPT-4-Plus",
        "maxLength": 130000,
        "tokenLimit": 31000,
        "context": "32K",
    },
    "gpt-4-0613": {
        "id": "gpt-4-0613",
        "name": "GPT-4-0613",
        "maxLength": 60000,
        "tokenLimit": 15000,
        "context": "16K",
    },
    "gemini-pro": {
        "id": "gemini-pro",
        "name": "Gemini-Pro",
        "maxLength": 120000,
        "tokenLimit": 30000,
        "context": "32K",
    },
    "claude-3-opus-20240229": {
        "id": "claude-3-opus-20240229",
        "name": "Claude-3-Opus",
        "maxLength": 800000,
        "tokenLimit": 200000,
        "context": "200K",
    },
    "claude-3-sonnet-20240229": {
        "id": "claude-3-sonnet-20240229",
        "name": "Claude-3-Sonnet",
        "maxLength": 800000,
        "tokenLimit": 200000,
        "context": "200K",
    },
    "claude-2.1": {
        "id": "claude-2.1",
        "name": "Claude-2.1-200k",
        "maxLength": 800000,
        "tokenLimit": 200000,
        "context": "200K",
    },
    "claude-2.0": {
        "id": "claude-2.0",
        "name": "Claude-2.0-100k",
        "maxLength": 400000,
        "tokenLimit": 100000,
        "context": "100K",
    },
    "claude-instant-1": {
        "id": "claude-instant-1",
        "name": "Claude-instant-1",
        "maxLength": 400000,
        "tokenLimit": 100000,
        "context": "100K",
    }
}

axiosCookieJarSupport(axios);

const cookieJar = new CookieJar();
const axiosInstance = axios.create({
  jar: cookieJar,
  withCredentials: true
});

class Liaobots {
    static url = "https://liaobots.site";
    static working = true;
    static supportsMessageHistory = true;
    static supportsSystemMessage = true;
    static supportsGpt35Turbo = true;
    static supportsGpt4 = true;
    static defaultModel = "gpt-3.5-turbo";
    static models = Object.keys(models); // Ensure 'models' is defined somewhere in this script
    static modelAliases = {
      "claude-v2": "claude-2"
    };
    static _authCode = null;
    static _cookieJar = cookieJar; // Use the instantiated CookieJar
  
    static async authenticate(auth = null) {
        this._authCode = auth || this._authCode;
        if (!this._authCode) {
            try {
                await axiosInstance.post("https://liaobots.work/recaptcha/api/login", {
                    data: { token: "abcdefghijklmnopqrst" },
                });
                const userResponse = await axiosInstance.post("https://liaobots.work/api/user", {
                    data: { "authcode": "" },
                });
                // Assuming the auth code is in the response headers
                this._authCode = userResponse.headers['x-auth-code'];
            } catch (error) {
                console.error("Authentication Error:", error.response ? error.response.data : error.message);
                throw error;
            }
        }
    }

    static async createAsyncGenerator(model, messages, auth = null, proxy = null, connector = null, ...kwargs) {
        await this.authenticate(auth);

        const data = {
            "conversationId": uuidv4(),
            "model": this.models[this.getModel(model)],
            "messages": messages,
            "key": "",
            "prompt": kwargs.systemMessage || "You are a helpful assistant.",
        };

        try {
            const response = await axiosInstance.post("https://liaobots.work/api/chat", data, {
                headers: { "x-auth-code": this._authCode },
            });
            return response.data;
        } catch (error) {
            console.error("Async Generator Error:", error.response ? error.response.data : error.message);
            throw error; // Re-throw the error if you want to handle it further up the call stack
        }
    }

  
    static getModel(model) {
      return this.modelAliases[model] || model;
    }
}

const args = process.argv.slice(2); 
const message = args.join(' '); // Join all arguments to handle messages with spaces

(async () => {
  try {
    const result = await Liaobots.createAsyncGenerator("gpt-4-turbo", [message]); // Pass message as an array
    console.log(result);
  } catch (error) {
    console.error("Error:", error);
  }
})();

**Comment by skullcrushercmd** [comment]
so after a lot of hours, was able to get it to work. will be available in my own repo

**Comment by Happ1ness-dev** [comment]
> will be available in my own repo

Can you please link it here? I tried the code you posted in the comment above, but it doesn't seem to work for me, it just returns `{"code":200,"msg":"success","data":"Too many requests"}` when trying to access the user.

**Comment by skullcrushercmd** [comment]
> > will be available in my own repo
> 
> Can you please link it here? I tried the code you posted in the comment above, but it doesn't seem to work for me, it just returns `{"code":200,"msg":"success","data":"Too many requests"}` when trying to access the user.

The code above is not updated, the issue with liaobots is that you can only get around 8k tokens or 4 auth codes per ip address so I've since moved on to recreating you.com, the code I have for liaobots still work and could be functional with some tweaks (change hard-coded stuff to dynamic and add proxy connection + list to get as many codes as possible) but liaobots is extremely slow so I'd rather just rip off you.com. to find the semi working script it's under anyvm org in my bio and in anyvm-bot repo

**Comment by Happ1ness-dev** [comment]
> so I've since moved on to recreating you.com

Yeah, but you.com has a hardcoded system prompt, and there's no way to change it. It also has no vision support, at least in g4f.

**Comment by skullcrushercmd** [comment]
> > so I've since moved on to recreating you.com
> 
> Yeah, but you.com has a hardcoded system prompt, and there's no way to change it. It also has no vision support, at least in g4f.

their site doesnt have gpt vision nor does it support attaching any images, but its not rll a problem as i can either extract any text from the image or send it to a dif specialized provider that has image ( either gpt4vision or some model on huggingface to include in the prompt when sending to you.com)

**Comment by hlohaus** [comment]
You.com does support image attaching. For a overview, please refer to the Readme file after the models.

**Comment by skullcrushercmd** [comment]
> You.com does support image attaching. For a overview, please refer to the Readme file after the models.

You can attach it but it will not send it, you.com doesn't have any image models nor does it even let you attach an image. Within the code it's semi done to add pictures but that's whenever there's a visual model which is not listed so it's not used

**Comment by hlohaus** [comment]
It use the pseudo model "agent". It is a good vission model.
