### ISSUE TITLE
can not generate an image

### ISSUE THREAD

**Issue by ClareXUse** [xtekky/gpt4free#1870]
import re
import os
import g4f
import json
import openai
from PIL import Image
import requests
import os
from g4f.client import Client
from dotenv import load_dotenv
from typing import Tuple, List
from g4f.cookies import set_cookies
def generate_response(prompt: str, ai_model: str) -> str:
    if ai_model == 'g4f':
        # Newest G4F Architecture
        client = Client()
        response = client.chat.completions.create(
            model="gpt-4",
            provider=g4f.Provider.Liaobots,
            messages=[{"role": "user", "content": prompt}],
        ).choices[0].message.content
        return response

def generate_image(prompt: str, ai_model: str) -> str:
    if ai_model == 'g4f':
        client = Client()
        response = client.images.generate(model="dall-e-3", prompt=prompt)
        image_url = response.data[0].url
        # 获取图像文件名
        filename = image_url.split("/")[-1]
        # 保存图像到同级目录
        image_path = os.path.join(os.getcwd(), filename)
        with open(image_path, "wb") as f:
            f.write(requests.get(image_url).content)
        print(f"Image saved to: {image_path}")
        # 显示图像
        img = Image.open(image_path)
        img.show()
        return response
def read_text_file(file_path: str) -> str:
    with open(file_path, "r", encoding="utf-8") as file:
        file_content = file.read()
    return file_content

# 使用示例
# file_path = "example.txt"  # 替换为你的文件路径
# file_content = read_text_file(file_path)

#
# # 向 GPT 发送 "你好"
# prompt = "你可以生成图片吗"
# ai_model = 'g4f'
# response = generate_response(prompt, ai_model)
#
# print(response)

ai_model = 'g4f'
prompt = "a white siamese cat"
generate_image(prompt,ai_model)

this is my code 
I'm able to open the website but however the google chorme opened the website remains still and nothing happened.
in my code ,to send the text is perfectly performed ,however I cannot generate an image? how should I do
![Uploading image.png…]()

**Comment by hlohaus** [comment]
Try other login cookies from bing.com or use a different image provider like MetaAI. But you'll need valid cookies for MetaAI too.
