### ISSUE TITLE
Command-r-plus not working

### ISSUE THREAD

**Issue by scuty2000** [xtekky/gpt4free#1874]
**Bug description**

Command-r-plus stopped working, even using proxies

```bash
[-] Error: RetryProvider failed:
Cohere: KeyError: 'data'
HuggingChat: ResponseStatusError: Response 500: {"message":"Internal Error"}
```

**Comment by hlohaus** [comment]
Try use the HuggingChat provider

**Comment by scuty2000** [comment]
`An error occured: HuggingChat: RetryProviderError: RetryProvider failed: Cohere: KeyError: 'data' HuggingChat: ResponseStatusError: Response 401: {"error":"You have to be logged in."}`

**Comment by hlohaus** [comment]
You need to add cookies from account session now.
