### ISSUE TITLE
bing: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by bsbrother** [xtekky/gpt4free#1876]
provider bing error: 
...
File "/home/kasm-user/.pyenv/versions/3.11.7/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by hlohaus** [comment]
Hey, your request might be blocked by the firewall. Try using a different IP address or cookies.
