### ISSUE TITLE
Gemini Provider not working

### ISSUE THREAD

**Issue by martinezart87** [xtekky/gpt4free#1878]
I added cookies from Google, unfortunately I get the message below:

`Gemini: WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:43765`

I'm using a docker image.

**Comment by hlohaus** [comment]
You'll need cookies for the Gemini provider. You can use WebDriver, nodriver, or cookie files to pass them. If WebDriver doesn't work for you, try nodriver:

pip install nodriver

Or make a .har or cookie file.

**Comment by thisisjerk** [comment]
Has anyone found a solution to this issue? If so, please share the steps you took to resolve it.

**Comment by martinezart87** [comment]
After updating to version 0.3.0.6, cookies work for me, but only for about 10 minutes. After this time I have an error:

`An error occured: Gemini: Exception: --------------------- Failed to connect to browser --------------------- One of the causes could be when you are running as root. In that case you need to pass no_sandbox=True`

Steps that worked for me:
1. Install https://chromewebstore.google.com/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?pli=1
2. Visit google.com and log in
3. Esport cookies to .json file and paste to har_and_cookies folder
4. Restrat Docker Container

**Comment by martinezart87** [comment]
I am attaching the log:
`
192.168.0.180 - - [25/Apr/2024 11:45:40] "GET /static/img/user.png HTTP/1.1" 304 -
ERROR:root:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
Traceback (most recent call last):
  File "/app/g4f/gui/server/api.py", line 174, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/providers/base_provider.py", line 216, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/g4f/providers/base_provider.py", line 45, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/app/g4f/Provider/needs_auth/Gemini.py", line 134, in create_async_generator
    cls._cookies = await cls.nodriver_login();
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/Provider/needs_auth/Gemini.py", line 74, in nodriver_login
    browser = await uc.start(user_data_dir=user_data_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/nodriver/core/util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/nodriver/core/browser.py", line 87, in create
    await instance.start()
  File "/home/g4f/.local/lib/python3.11/site-packages/nodriver/core/browser.py", line 343, in start
    raise Exception(
Exception: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
192.168.0.180 - - [25/Apr/2024 11:47:27] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.180 - - [25/Apr/2024 11:47:27] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
`

**Comment by hlohaus** [comment]
Did you enter your account data in the vm browser?

**Comment by thisisjerk** [comment]
> Did you enter your account data in the vm browser?

This resolved it. Thanks!

**Comment by HYP312** [comment]
my problem is. Response 400: Please ensure that multiturn requests ends with a user role or a function response.

please help me guys

**Comment by martinezart87** [comment]
> Did you enter your account data in the vm browser?
Working for me. Thanks.
