### ISSUE TITLE
Bing Failed to perform, curl: (77) error

### ISSUE THREAD

**Issue by seitymoe** [xtekky/gpt4free#1885]
When using gpt-4 with Bing provider. I get this error:
Bing: RequestsError: Failed to perform, curl: (77) error setting certificate verify locations:  CAfile: K:\PROJECTS\ABC\code\venv\lib\site-packages\certifi\cacert.pem CApath: none. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

I followed this https://github.com/xtekky/gpt4free/issues/1319 to set cookies. I am using proxy too.
`
        set_cookies(".bing.com", {
            "_U": '{"MUID":"1AFE******","SRCHD":"AF"......}'
        })
`
Am I adding the cookie correctly?
Please help me with this problem. Thank you.

**Environment**
- python version
- windows

**Comment by jiangyao123** [comment]
It seems like that the content of cookies was wrong, it's just  one cookie
<img width="503" alt="截屏2024-04-24 下午2 49 43" src="https://github.com/xtekky/gpt4free/assets/34278932/da37ed7f-be5c-407b-bb1a-863acc0eef0b">

**Comment by hlohaus** [comment]
You don't need to set cookies in Bing. I'm glad it works now.

**Comment by seitymoe** [comment]
> You don't need to set cookies in Bing. I'm glad it works now.

Thank you.
Do you have any idea why I am getting this error?↓
Failed to perform, curl: (77) error setting certificate verify locations

**Comment by hlohaus** [comment]
Hey, try updating certifi. The errors are because of the certifi ca file.

**Comment by seitymoe** [comment]
thank you. 

> Hey, try updating certifi. The errors are because of the certifi ca file.

it solved the problem!
