### ISSUE TITLE
can't run API server successfully

### ISSUE THREAD

**Issue by jackiezhangcn** [xtekky/gpt4free#1886]
with the latest version(v 0.3.0.6), I can't run API server successfully, it reports the bug of "405 Method Not Allowed", but operation of listing all models works.

screen snapshot:
INFO:     Uvicorn running on http://0.0.0.0:1337 (Press CTRL+C to quit)
INFO:     127.0.0.1:41366 - "GET / HTTP/1.1" 302 Found
INFO:     127.0.0.1:41366 - "GET /v1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41366 - "GET /v1/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:41366 - "GET /v1/chat/completions HTTP/1.1" 405 Method Not Allowed

**Comment by hlohaus** [comment]
It is essential to perform a POST request rather than a GET request. Accessing the URL directly through a browser initiates a GET request.

**Comment by jackiezhangcn** [comment]
I wish to set up a API server so that my App can access it smoothly

**Comment by jackiezhangcn** [comment]
> It is essential to perform a POST request rather than a GET request. Accessing the URL directly through a browser initiates a GET request.

when I tried POST, got the error:
INFO:     127.0.0.1:50006 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application

**Comment by iG8R** [comment]
Oh, a familiar situation. https://github.com/xtekky/gpt4free/issues/1795#issuecomment-2073296688

**Comment by Hydra566** [comment]
@iG8R @jackiezhangcn  I use REST API, I don't have any problems. You are most likely making the request incorrectly. What programming language are you using, perhaps I can help?
1) Is your JSON valid?
2) Did you specify content-type: application/json in the request?
3) Are you making a POST request to http://localhost:1337/v1/chat/completions? Perhaps you do not have localhost, but the IP address of your server.

**Comment by Hydra566** [comment]
> 405 Method Not Allowed

The error speaks for itself, you are making a request using an invalid method, you need a post request and content-type: application/json.

**Comment by jackiezhangcn** [comment]
> @iG8R @jackiezhangcn I use REST API, I don't have any problems. You are most likely making the request incorrectly. What programming language are you using, perhaps I can help?
> 
> 1. Is your JSON valid?
> 2. Did you specify content-type: application/json in the request?
> 3. Are you making a POST request to http://localhost:1337/v1/chat/completions? Perhaps you do not have localhost, but the IP address of your server.

Appreciated your kind help. By re-downloading docker image, the problem gone away. 

by the way, the 'api_key' in the demo code can't be empty, should be like a normal one.

**Comment by jackiezhangcn** [comment]
this thread can be closed, thanks everyone!
