### ISSUE TITLE
phind_test not working

### ISSUE THREAD

**Issue by AymaneHrouch** [xtekky/gpt4free#189]
/home/aymane/Desktop/code/python/gpt4free/venv/bin/python /home/aymane/Desktop/code/python/gpt4free/testing/phind_test.py
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7be623289eebc724')"></div>
        <form id="challenge-form" action="/api/infer/answer?__cf_chl_f_tk=7hYD1Dw2Ovrl4gAG7in_6etNB0Ntb_fhNaviSqoFNNs-1682588775-0-gaNycGzNDZA" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="PYl84SwTL8bxX4xaJZtV.noPVDTqWfws_TyGB8YNg1s-1682588775-0-AdK7PoOuTn7Jyonp7-5cJBuP9QdZ0GYoo8famyLKCS32YCARaETvlcnkoPLpnPSRq1XTIvrQ2uiRZAsoK90XYR3AbxnxcsVfTErnQmk4MPk5z6kfWLcsUGglGl2f6jmrBSCsuRXl9beOfUXTYxaiOx1hNZeWzt4w45GmQUI_27NapSlElsbU0C0yctsJM8h0wxfUNPDCs-aQ_jj6r-TmHQJeKvbPF5qZ8J9xZJJPQYQ2evZIL0FSudmovvy818Yis1Z_CFg_w661FQNv3m25CHiBjfGfUlKtQoQp6DJy_N9BocgjifoWO8AP8FNprQqF8PIbtR2r-5D5tyaMyNGUNzDZ41ygaNrFFlnsEa2KtJkP_C7mngOKQSdJWAaMzRTqHcQOxmBz6sieC2Jb8CXoX3CiF2-0bhMyXsTkcUSYaquoUpn08ln7xuuDFohea5_fpQrUvaJJ_wyL_d0ikkxqdN-toa6YAKVFlAlGlhPnNeeSs-l3V_04nk5NgFpKHHT1iIkWLjkGP1mFLIg2aN-otu4ib15lTXUUgYoHjMDzTKEBj3VKU0OnoUQZg2b5GdLbfROvIFPkpSIkbv2dmdA3WZWOmCaUkUDwH8X-vwK6AkgnLppsVATW4J9rpLD_CNJMI66o8ghi1vLnWyrLNaS686WhJonZGhD69Wa8NZssxIf6OrxkzwJK5tcTSf4WeLxFGSRDJpeLyQcVJnfpdKR6dIdiAAzdUGo6j-lgzSaVc4eVGj_9c4omxYw8lCva_wWzsolYM-gLg-2jgVjqYt56eJ-1cO4AMhFBiXzrz8_m8PNxeXeNWXxYlGYp1NpFhOSSr6FvSj4UbP9ZHJ7eAjOMc4abGpAnS9CXTgvKk8MzIKF8lGsXUnZmNT533JSh1DmonFJ9qSHU0VvPp1Vyg0h8opQADE0nz5Nx33VaXaJ04oIJCrt6y5jkwb9KtKvuZWh0uTQwV7vHKgBWi9flcvnXoYyhuPmNCtKq8wUn7ZnUM6tDA5NE1WIkSrivd5twjidipGi6H9QSK7BM2wcduj9kmfVOtOYM4YAtRDgAqgbG8W9MwA7Vhmq5hmZVwGnytbhhmC86gfnFWH_vZRpmkwxqMor8LigAitPeLTVAPiADWv09wBeH_KTVko8UFAWgRn-nf5fAnepRrvgIwjFBTczsnIbIbKjIaTMjMO4Q5YE77G6htGaSgapDfYZfsnRrqb4UZ3rFeC4y_hGHIJBRYiLqfoC0RubgCXonPRYVDTTAZbg9YoaND21gXllJQlIlizVG2ujMZlNFazoK8oaj0WUrTNEUfSzRLvFYky4P1qlERsVOMxZhAsDeW3oeh3cdtAJaYadfxZNLZCzOk0FyyMA3anxwG0RDr6aD2EPQW9UMgcNcVgTroxmjiu-nS8P_xC-OclO4FyrSNS70wV_fm46aSdsxCtqzpeeX-ySdB0s7f-Iekp9coek3NxpUGp1se4NRt_6PizP2s6DmBVu4-q5T2ZChG3g9iP9JdselqgAjnymP55HNo3bHSr-MZ-4C_NabMPVI-yBSIEGrIRPGGGT7bZJq2hyor9OVtcuUECK7IDaFxsZomCYQSJG3p7OmbDf9nR2xkMxPqX7C8sqOpBci0cl41aDoh802RHfrYJwXL9Y918aY2uG-B3nHTyS7Ww4koTSiiHaw7bZBJgzqXY2FxG4j9tZeUlZbU7EX4d7cc2OHduDlFiBwB7h2E8Gn-SJAvCgkeIwKoWw_iFmtkZ1hw4LYXbrWwz0iYd2ExQvcU1KKyVnPsHA-j9VzxCGeD6G9IFVkWB4QA8WpLCp_Y5QHR04Wtv4spJBlJ3GUX1txFkfskbqpI-z1R4LeW1QE0j3Z7uYJ_6eQndX_3ksQIwZp41W_s06bzYciKiet-7ytKPTSsC1OPdea5lMQPhLgmVUjptFmjghbmetYOsga00t7D_eEJmprsxRMAGxHn5DBl7sEMC8Te2ULIBesOUo6_yWYu8s2DHNlqOpY3QVYjNMcEcPkKL9T8tM-dNtwyyyeYr3vOeXEUrkZiSFzPb9ncv-UMRtGxiwCKoFtCG9_yf4Fy1femGSy6AmcvpfEsjqG3qUl84-EojvYFgSnh7NwolTymoyfzJDtHQRf1OwsHIzBkS_7g8WagUEn-Uuoz9b-_F00EICkBAqFoHYWRkmHzB-ZP47TIsDV76ORTMeQ9QIPfBFDJS8ZWkYWH5FvmuTOySuYGTIGJ6sgfa-TG3lzgrZjc_P-yKK7CeEf1eJY8lXKvTH2KZYzv2T1mVGf_Nrl9AGI823KkBtcGW6jn5MDtvI8SQIOXlI536kHNvreIp1CMRbmhk2Kzww0JKov4WwUOBsk99PaIRosx7rBbc5SrthIPLnoEKFrSVa7muNGnqBjd9T5Y4sRYc7bcnNUfC9zZf07YskKayvI59d7DvL9AlctaPHFDMbUzFDHkGcdMHGZpeSyyUUnT7hL3nIjCMv7Qxb_2tmQfaw_xiad0xJjv7r990u3ttDGUQkaBhqaPsaOVBcKGRguXLsixpzKONfoX_TMdvZADlIP7yGbsL6Flkl6D62PqKKUFUCgXuTlXswr0ir7yozOXkPm4g8jXkOZ4wr2vU1Nza-fMlvdP6VrXfRR6o1BChNdR2Au8SbRnVv3t2_YbdAYJuarkHWNZlagqotyHjXt1_q5sZqAaxifuTKTriHu_2y_Exl-_4wj29vlR5RFoCjEss1iKXkOF41K3IVYiz54WRAKcFRHBlxy5957__gT2kpa2OZTblaXYTh4NMreUWXN41h_t-a8RYd_TlMi5zGh9YgOkfBoUIPtEa4zgFH43p5dShnNCJkWN5EDALqM3xpF8yVLYs2Bad8Xq4VHRUBL-Z2_qaO4D80IAGWFZJribJd4Dl5C6gceHOL4bPvfs3zaD9akxSq7W10bqqstKoZmpOwBmpPl8z5WkN6Oh421Xhy6c5Pyk86sKVTAfVXDY5xVzkKweYycXx15KyUg_k0GKlTUtUDVVbkFJHL41Ob7r4xVPVwwRhBE1OShs2ipx2FvZd5JmsF2jzRDWU7j2uHFGIdrZ7RYs30XjP-42RGFd3kt_ZBxo10iNP0ZjGD_QymUa1x2pOJ9uCR720sei6NXFBH0gCPXO4xUtjxz3d1-_EkkBovxVb5ZMo8fGXIjdz7FcRHycCJcY5UiGsg0cIi7eMUsczuA2gsPpoO3yetWQHsxjpzIudHBlwZOiBI-RCSD8zYC73qT5N-XPfFVAP4Jkh6j4EhTm-NQjc93Zw85f9HnBZb25c3PCBC3Tj81_v3MH4xxp08HODp1T5SldZC1S0zbaU9P-ic8QHcWq-IeX2Dr_bIixP2Vzl7BaF-x-PDalGVqwVgNPiR7vKCp-XnH5_08l1RKBcV0DtsuyypGO3yYLaROBIGs9ana270">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'www.phind.com',
            cType: 'managed',
            cNounce: '16080',
            cRay: '7be623289eebc724',
            cHash: '84060f76f47cb0c',
            cUPMDTk: "\/api\/infer\/answer?__cf_chl_tk=7hYD1Dw2Ovrl4gAG7in_6etNB0Ntb_fhNaviSqoFNNs-1682588775-0-gaNycGzNDZA",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cMTimeMs: '0',
            cTplV: 5,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly93d3cucGhpbmQuY29tL2FwaS9pbmZlci9hbnN3ZXI=',
                ra: 'TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzExMi4wLjAuMCBTYWZhcmkvNTM3LjM2',
                rm: 'UE9TVA==',
                d: 'N8Mvxl3GfPBsPitKJ99y9x3ZUHxsqUzzrR7/IFJwIrVzk8ueFxZsSijGDOP5IfnjqNfa/kqQfwZlE25fax6kGvYfDitG5kPFS/wXYP7P9I86sRKZHSLsLsjENa0WDRk3e43wpHN+DkhFOpW7mL9ty9sQ8dVnxBGWdFvU07EtKpMqvAeifOnbhv2IGefuX38BVs+C//2grmIAZatYnJkKYRbjs+7HL0CV08ff2xgT+w6EEu9UHLYWWUoe3VEIeHunZsMKXlafQ3M4rOdgzK4L1Jw2uwqzuE/4S7ygZaXJVHZjmFD33JkmFvamt957uScPzAlLgPHjf5g6gDxM1T39YVSkpXGggtVRsAJh5NfIhGkRimjNxXrh+a5+PdVjmcaLHKokHKW8tbGJqs0elwIcZFwlXQP9WHy0LFs+V69qXimHLVdCLO0jy9sjHVlWIo6b1xyXWyyfywCidXw2H0v1ivGIM5jxUWCPG2X6hc+jeFSS29UD3ltMp5uHgMhvN6+vxFDLJ6sEIWCaxz4SldAD7Y4yUgJlxuZ8myQPGQIhnMQ=',
                t: 'MTY4MjU4ODc3NS43ODYwMDA=',
                m: 'XHFEsNsKq4LnZMO27W1ZFvAHGzYIYFNnkt7p1mBRjsQ=',
                i1: 'lHQQxMALWSF/kIsms95PPQ==',
                i2: 'DB143XiBJZevWsbdrwMbrg==',
                zh: 'bW8wvari4RrHgfvv3gHlYdvlbboFVBGG5znQ/udGch0=',
                uh: 'KHK2rFuElrK5yT+xHUaUe3iPn4Ubhk37QHLDdxqPYlA=',
                hh: 'GiY/pWTdSpNnEgCWROB4TeDwU7/UC4zuGuhCvVoBx7A=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=7be623289eebc724');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/managed/v1?ray=7be623289eebc724';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/infer\/answer?__cf_chl_rt_tk=7hYD1Dw2Ovrl4gAG7in_6etNB0Ntb_fhNaviSqoFNNs-1682588775-0-gaNycGzNDZA" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

</body>
</html>

Traceback (most recent call last):
  File "/home/aymane/Desktop/code/python/gpt4free/testing/phind_test.py", line 27, in <module>
    results     = phind.Search.create(prompt, actualSearch = True), # create search (set actualSearch to False to disable internet)
  File "/home/aymane/Desktop/code/python/gpt4free/phind/__init__.py", line 98, in create
    'browserLanguage': language}).json()['rawBingResults']
  File "/home/aymane/Desktop/code/python/gpt4free/venv/lib/python3.10/site-packages/curl_cffi/requests/cookies.py", line 54, in json
    return loads(self.content, **kw)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by AymaneHrouch** [comment]
Apparently when `actualSearch` is `True`, the result of the post request is an HTML page that says in the title "Just a moment..." instead of a json response, does anybody have any idea how to solve this?

**Comment by 9fo** [comment]
web search is broking at the moment

**Comment by xtekky** [comment]
@AymaneHrouch did you set cf_clearance ?

**Comment by thrivepro** [comment]
> @AymaneHrouch did you set cf_clearance ?

Am currently facing an almost similar issue...how do I set this @xtekky ?

**Comment by xtekky** [comment]
phind is not working atm and will be taken down soon, refer to another module in the meantime
