### ISSUE TITLE
ResponseStatusError: Response 401: {"message":"401 Unauthorized"}

### ISSUE THREAD

**Issue by zhongzhixinLvoe** [xtekky/gpt4free#1893]
An error occured: Liaobots: ResponseStatusError: Response 401: {"message":"401 Unauthorized"}     At present, I use the latest version, but this problem still occurs. I have seen the problems raised by other brothers and sisters, but I have not found a solution. Is it impossible to use it normally at present

**Comment by martinezart87** [comment]
Has anyone resolved this problem?
