### ISSUE TITLE
Bing TypeError: Received message 257:None is not str

### ISSUE THREAD

**Issue by seitymoe** [xtekky/gpt4free#1894]
**Bug description**
When I use gpt-4 model I get this error most of the time:

`Bing: TypeError: Received message 257:None is not str
`
I have tried different prompts but Usually I get this error. the number in the error message is always 257.
Sometimes I get response successfully.

I use proxy too.

**Environment**
- python version
- windows

what does this error mean and What should I fix?
Thank you

**Comment by hlohaus** [comment]
Did you have curl_cffi installed?
pip install -U curl_cffi

**Comment by seitymoe** [comment]
> Did you have curl_cffi installed? pip install -U curl_cffi

Thank you.
I have remade the venv and and reinstalled g4f.
The `TypeError: Received message 257:None is not str` has disappeared but now I get different error.


```Bing: CurlError: Failed to WS_RECV, curl: (52) . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Liaobots: ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
ERROR:root:Error: RetryProvider failed:
Bing: CurlError: Failed to WS_RECV, curl: (52) . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Liaobots: RateLimitError: Response 402: Rate limit reached
ERROR:root:Error: RetryProvider failed:
Bing: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Liaobots: RateLimitError: Response 402: Rate limit reached
```

I have tried on another pc but I get the  same error.

Here is the code to get the compilation.
```
                response = self.client.chat.completions.create(
                    model='gpt-4',
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=10000,
                    proxy=os.environ.get(
                        "G4F_PROXY") if self.proxy_enabled else None
                )
```

Is gpt-4 working for you?

**Comment by seitymoe** [comment]
Is Bing gpt-4 working for anyone?
I use the har file that I extracted from bing.com but I am not sure if I am doing correctly.
I am wondering if this is why the Bing is not working for me.
Could anyone show me how to do it?
