### ISSUE TITLE
(HTTP code 500) server error - Ports are not available: exposing port TCP 0.0.0.0:1337 -> 0.0.0.0:0: listen tcp 0.0.0.0:1337: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by 1426002590** [xtekky/gpt4free#1903]
(HTTP code 500) server error - Ports are not available: exposing port TCP 0.0.0.0:1337 -> 0.0.0.0:0: listen tcp 0.0.0.0:1337: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by hlohaus** [comment]
Hey, try changing the port in your command. Make sure you quit the previous call. Add --port=free_number to your command.
