### ISSUE TITLE
gemini doesnt work

### ISSUE THREAD

**Issue by HuskyTuskySatyr** [xtekky/gpt4free#1919]
Gemini returns NoneType error

**Comment by noneherel** [comment]
Same

**Comment by alluding** [comment]
Standard `Gemini` or `GeminiPro`?

**Comment by OE-LUCIFER** [comment]
does anyone know how to use replicate in g4f

**Comment by noneherel** [comment]
> Standard `Gemini` or `GeminiPro`?

Standard Gemeni

**Comment by rkuo2000** [comment]
same problem

**Comment by hlohaus** [comment]
Maybe missing cookies? I did not receive any error message, so I am unsure of the issue..
