### ISSUE TITLE
.har file for you.com

### ISSUE THREAD

**Issue by amjiddader** [xtekky/gpt4free#1936]
- you.com issue / need .har file 

**Bug description**
When we use you.com it does work if we have nodriver and if we use Proxy or VPN it fails because of captcha.

So how can we create a .har file you.com \
I tried to use .har file in ./har_and_cookies/you.com.har 
I do not know which file we need to take .har i tried almost all but it never worked.

- error / File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/you/har_file.py", line 87, in get_telemetry_ids
    raise MissingRequirementsError('Add .har file from you.com or install "nodriver" package | pip install -U nodriver')

Can anyone tell me how to and for which link / file in you.com i have to capture .har ( without nodriver

Note: I dont want to use nodrver (Thats working)

Error log: https://gist.githubusercontent.com/amjiddader/626c913d2e39d58594ba5604471ca16f/raw/e86b9f8c0fd634462c711c90dd6ae581f2d42b7b/error.log

you.com.har: https://gist.githubusercontent.com/amjiddader/2542e82121b8c008821cd0eb122a8c25/raw/ab9c96ccc44565d4d1ceb941b1ca6f2d21da9b1f/you.com.har

**Comment by Anonymous6598** [comment]
Did you install nodriver?

**Comment by Anonymous6598** [comment]
Because it's missing

**Comment by amjiddader** [comment]
> Did you install nodriver?

Its working with nodriver i dont want to use nodrive.

**Comment by Anonymous6598** [comment]
Well, in error message nodriver was mentioned. My advice - just install nodriver instead of playing with .har file. Or use another provider, which doesn't need .har files.

**Comment by Anonymous6598** [comment]
Maybe this article can help: https://www.stackpath.com/edge-academy/what-is-a-har-file/

**Comment by Anonymous6598** [comment]
It is connected with .har files

**Comment by Anonymous6598** [comment]
Use chrome, firefox, opera or edge utility for creating specific .har file for url you.com

**Comment by amjiddader** [comment]
> Use chrome, firefox, opera or edge utility for creating specific .har file for url you.com

I actually have included have included .har file it is supposed to work.
Because its correct. 
If we use bing har file with same steps thats working fine . Taking cookie from har and works. 

But when it comes to you.com .har file seems valid and i have exported from chrome and Mozilla does not work.


Also just to mention its working with if we install nodriver but, i want to use without nodriver.

Thanks

**Comment by Anonymous6598** [comment]
Maybe it's a bug

**Comment by Anonymous6598** [comment]
Have you tried exporting from edge?

**Comment by Anonymous6598** [comment]
Or change utility. Or switch to another g4f api version

**Comment by amjiddader** [comment]
> Or change utility. Or switch to another g4f api version

Tried getting .har from edge.. Does not work.
I was trying to make you.com work..

Others are working  fine.

**Comment by Anonymous6598** [comment]
What browser do you use? Use .har utility for you browser. My suggestion - use firefox developer edition. It might work.

**Comment by Anonymous6598** [comment]
Or try opera

**Comment by amjiddader** [comment]
Never mind i got it working.
Here is how 
> Logout or use private TAB 
> Open Developer Mode first then open you.com
> Once website is fully loaded, Login (in private mode make sure you are logged out)
> Switch to any different model i.e: gemini or gpt4 
> Start a chat , ask anything.
> Export .har ( Browser does not matter)

PS: I tried exporting without switching models it did not worked. 
But following above methods > Now its working.

Thanks @Anonymous6598

**Comment by amjiddader** [comment]
> What browser do you use? Use .har utility for you browser. My suggestion - use firefox developer edition. It might work.

That does not metter, ( maybe for BING Designer that might make sense using Edge.
Now its working and i guess we should close this issue.

**Comment by Anonymous6598** [comment]
Your welcome. I'm glad that I helped you.

**Comment by amjiddader** [comment]
Closing this now..
