### ISSUE TITLE
The passed context is not taken into account when accessing the API

### ISSUE THREAD

**Issue by xannanov** [xtekky/gpt4free#1937]
**Bug description**
Hello, thank you for the great product. I found a bug: when running with Docker and accessing the API on port 1337, the model does not retain the passed context. It is clearly demonstrated in the screenshot with Postman.

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/122401155/cc657761-f88f-45ac-8f83-77b860f5aa41)

**Environment**
- docker

**Comment by hlohaus** [comment]
Not all models answer direct questions, and not all providers support context. For example, Bing has limitations in its context API.

**Comment by xannanov** [comment]
I'm using the gpt-4-turbo model without specifying a provider. The response is returned from the Bing provider. At the same time, the same actions in the UI version on http://localhost:8080/chat remember the context and the same uses bing
