### ISSUE TITLE
update DuckDuckGo models

### ISSUE THREAD

**Issue by TheFirstNoob** [xtekky/gpt4free#1938]
Before DuckDuckGo Provider used: Claude 1.2 and gpt-3.5-turbo
Now used: Claude 3 Haiku and gpt-3.5-turbo

Rate limit: 50 messages/day

Thx

**Comment by TheFirstNoob** [comment]
updated:
Model used: claude-3-haiku-20240307

https://github.com/xtekky/gpt4free/blob/main/g4f/Provider/DuckDuckGo.py#L19

update to: `models = ["gpt-3.5-turbo-0125", "claude-3-haiku-20240307"]`

**Comment by hlohaus** [comment]
I have updated the model list in g4f.
