### ISSUE TITLE
Claude-3-opus, a series of models are not usable. It seems all models provided by the supplier you.com are now unusable, probably due to an update."

### ISSUE THREAD

**Issue by doudingai** [xtekky/gpt4free#1940]
Please developers, take a good look and check if it's no longer working. This issue is specific to the series of models provided by you.com.

**Comment by doudingai** [comment]
An error occured: You: CloudflareError: Response 403: Cloudflare detected

**Comment by amjiddader** [comment]
> An error occured: You: CloudflareError: Response 403: Cloudflare detected

Its not an error its because of Cloudflare captcha.
Either you are using a server .
Using on local IP should work.

**Comment by Looksh190** [comment]
only gpt4 for now :(

**Comment by Looksh190** [comment]
[You.com] with claude-3-opus

Hello! I'm an assistant powered by the GPT-4 language model developed by OpenAI and enhanced with You.com's AI capabilities. I'm here to provide you with information [aborted]

**Comment by cloudygtosis** [comment]
"I'm an assistant powered by the GPT-4 language model developed by OpenAI and enhanced with You.com's AI capabilities."
I also encountered the same problem.

**Comment by hlohaus** [comment]
I fixed the issue with wrong selected models.
