### ISSUE TITLE
API /images/generation 

### ISSUE THREAD

**Issue by amjiddader** [xtekky/gpt4free#1944]
Add api endpoint for create.images so we can we use to create images.

##Problem
Currently it only works for /v1/chat ..
But if we have to generate images even from GUI i can't see any option to generate images. 

##Solution

Create api endpoint similar to dall-e that can be used to generate images.
OpenAI: https://api.openai.com/v1/images/generations
So gpt4free : http://127.0.0.1:1337/v1/images/generation

Or by setting header option like method?

method=Chat
method=Images 

Thanks.

**Comment by hlohaus** [comment]
Hello @amjiddader,

I have added a image generation api endpoint to g4f.
You can now use them.
