### ISSUE TITLE
[OpenaiChat] Response 403: {"detail":"Unusual activity has been detected from your device. Try again later. (8xxxxxxxxxxxxxx5-WAW)"}

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1947]
Until today, any access to OpenaiChat via the `g4f API` worked fine, but suddenly it gave the following error, although chat via https://chatgpt.com works fine.

![image](https://github.com/xtekky/gpt4free/assets/11407417/4d97fe37-bae9-4628-9ad2-2564ff75e920)

![image](https://github.com/xtekky/gpt4free/assets/11407417/64e0d1e5-cf81-4a19-b30d-93c37fbece31)

**Comment by iG8R** [comment]
With version `0.3.1.1`, still the same result. I've already tried changing the IP via VPN - in some cases the error remains the same, in others it becomes `Response 403: Cloudflare detected`.
What info or logs could I provide to help resolve this issue?

![image](https://github.com/xtekky/gpt4free/assets/11407417/dd78df4c-5f58-4d69-96dd-003b884ba4a9)

![image](https://github.com/xtekky/gpt4free/assets/11407417/b85728f6-5a20-448f-82e0-5c37a885a138)

**Comment by johnroven** [comment]
I have the same same issue.

**Comment by plia7** [comment]
Hello, I can confirm I have the same issue in my working environment.

**Comment by iG8R** [comment]
With version `0.3.1.2`, the `g4f API` started working, but there are sometimes occurrences with the same aforementioned error and it doesn't depend on the requests' frequency.

![image](https://github.com/xtekky/gpt4free/assets/11407417/7390cfbe-032f-4ba0-a06c-8cec47f6c403)

**Comment by iG8R** [comment]
And now the error has changed to 
```
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 421, in create_async_generator
    blob = data["arkose"]["dx"]
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'dx'
```

![image](https://github.com/xtekky/gpt4free/assets/11407417/5a7426a1-5098-4726-ae0b-61c36d60d7be)

**Comment by hlohaus** [comment]
They changed they prooftoken and maybe the arkose token.
I doesn't found a solution for that jet.

**Comment by iG8R** [comment]
@hlohaus 
Thank you! Now in version `0.3.1.4` it started working fine.

![image](https://github.com/xtekky/gpt4free/assets/11407417/a43b97af-d6f3-4294-bb54-05a7b7ee2f38)
