### ISSUE TITLE
how to install phynd or poe?

### ISSUE THREAD

**Issue by KoLL4IK** [xtekky/gpt4free#195]
i'm have an error: ModuleNotFoundError: No module named 'phind'.

**Comment by KoLL4IK** [comment]
> you don't need to install them as they are not pypi modules (at least not yet). you need to clone the repo

i need to replace my file to poe directory?

**Comment by DanielShemesh** [comment]
just clone the repo and then move the files from the testing directory to the base directory

**Comment by 9fo** [comment]
u can download the folder of the module u want to use, and drag it in
