### ISSUE TITLE
provider You - Cloudflare detected- help?

### ISSUE THREAD

**Issue by vvostokov** [xtekky/gpt4free#1953]
raise CloudflareError(f"Response {response.status}: Cloudflare detected")
g4f.requests.raise_for_status.CloudflareError: Response 403: Cloudflare detected
can you tell me how to solve the problem?

**Comment by hlohaus** [comment]
Installing curl_cffi might help bypass Cloudflare.

**Comment by vrashad** [comment]
use mobile proxy
