### ISSUE TITLE
You are using an unsupported command-line flag: --no-sandbox. Stability and security will suffer.

### ISSUE THREAD

**Issue by doudingai** [xtekky/gpt4free#1954]
You are using an unsupported command-line flag: --no-sandbox. Stability and security will suffer.

**Comment by hlohaus** [comment]
This command argument is not utilized by us.

**Comment by doudingai** [comment]
You: Exception: --------------------- Failed to connect to browser --------------------- One of the causes could be when you are running as root. In that case you need to pass no_sandbox=True

**Comment by hlohaus** [comment]
Hey, your browser won't open. There could be a few reasons. First, you might not have enough memory. Maybe it's restricted for Docker. Second, you might have too many browsers open or you didn't close all the open ones.

**Comment by John4650-hub** [comment]
Am getting the same error. I run docker container from github actions

**Comment by Eva-Skye** [comment]
i got the same error
