### ISSUE TITLE
perplexity pro

### ISSUE THREAD

**Issue by f1shy-dev** [xtekky/gpt4free#1956]
Could it be possible to get these models in g4f if i have a perplexity pro subscription?

<img width="721" alt="image" src="https://github.com/xtekky/gpt4free/assets/56125930/e15af7d8-d5ed-4925-8bd9-b518e3711211">

**Comment by hlohaus** [comment]
Hey, so I don't have a Perplexity pro account, but I added the Perplexity API provider. The thing is, it doesn't have all the models from the image.
