### ISSUE TITLE
Command-r+ is unavailable

### ISSUE THREAD

**Issue by tastypear** [xtekky/gpt4free#1957]
**Bug description**

I deploy hlohaus789/g4f docker in HF Space: 
[https://huggingface.co/spaces/tastypear/g4f](https://huggingface.co/spaces/tastypear/g4f)

Then I try to visit it with curl:
```bash
curl https://tastypear-g4f.hf.space/v1/chat/completions -d '{
    "model": "command-r+",
    "messages": [
      {
        "role": "system",
        "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."
      },
      {
        "role": "user",
        "content": "Compose a poem that explains the concept of recursion in programming."
      }
    ]
  }'
```

It returns `{"error":{"proxy_note":"Server unavailable, error code: 349453"}}`

There is no other useful logs.

**Comment by hlohaus** [comment]
Hey, the provider for this model is no longer working. You should use HuggingFace with Account cookies instead.
