### ISSUE TITLE
How do I download it? 

### ISSUE THREAD

**Issue by LuizH2409** [xtekky/gpt4free#1962]
Hello,

I would like to know how to download the app and what the requirements are for downloading it. Could you please provide me with detailed instructions?

Thank you,

**Comment by hlohaus** [comment]
Hey, there are a few ways to do this. You can use Python or Docker to run it. Have you used either of those before?

**Comment by LuizH2409** [comment]
I have used python sometimes, but my knowledge about it is almost zero

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hlohaus** [comment]
You can install g4f with:

`pip install -U g4f[all]`

and run it with:

`python -m g4f.cli gui --debug`

Then open the url in terminal.
