### ISSUE TITLE
Perplexity labs error 403

### ISSUE THREAD

**Issue by osangni101020** [xtekky/gpt4free#1963]
**Known Issues** 
perplexity labs getting this error

**Bug description**
getting 403 error

**Screenshots**
![Screenshot_2024-05-17-12-30-42-502_com android chrome-edit](https://github.com/xtekky/gpt4free/assets/156106886/e0a208c8-b1ac-4f62-8f9b-49230aaa63ae)

**Environment**
- python version 3.10.14
- location don't know... using replit

**Comment by raisajannat4466** [comment]
anyone?
