### ISSUE TITLE
Getting System Announcement in Every response and Other Models not Working

### ISSUE THREAD

**Issue by kkhatke** [xtekky/gpt4free#1964]
**Bug description**

After Installing the g4f 
 `pip install -U g4f` 

Define a Function
```
def get_updates(prompt):
    """
    Function to get updates based on a prompt using the GPT-3.5-turbo model.
    Parameters: prompt (str): The prompt for generating updates.
    Returns: str: The content of the response message.
    """
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{
            "role": "user", 
            "content": f"{prompt}"
        }]
    )
    return response.choices[0].message.content
```
```
about_prompt = f"Update the {about} for {state} with the following information: {resource_name}, and keep it in 2-3 lines in English"
about_update = get_updates(about_prompt)
```

it will give me a response everytime

> [System Announcement] 2024/05/17 17:12 The website interface is faulty, and the webmaster is expediting it.
> It will be fixed before the weekend. Please be patient and get off work on Friday and have a good weekend. The latest address of this website is https://chat18.aichatos.xyz. Please bookmark it in your browser to open it permanently. Open a new session to view the latest address.

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/113087478/bd3e0bab-820b-402e-9281-f50dbdc3c5b8)

**Environment**
- python version - 3.11.0

**Additional context**
and if I change the model 
In  model = gpt-4

> g4f.errors.RetryProviderError: RetryProvider failed:
> Liaobots: ResponseStatusError: Response 500: Error
> Bing: RateLimitError: CaptchaChallenge: Use other cookies or/and ip address 

and in all other models 

> g4f.errors.RetryProviderError: RetryProvider failed:
> You: Exception:
>                 ---------------------
>                 Failed to connect to browser
>                 ---------------------
>                 One of the causes could be when you are running as root.       
>                 In that case you need to pass no_sandbox=True

**Comment by pythonmanGo** [comment]
the  same problem ，wethear  set  cookie  jason  or  har  or  login  in   in  VM chorme   or   pip  install  nodriver,that's no work  for me  to   use gpt4o
