### ISSUE TITLE
Cloud Flare error

### ISSUE THREAD

**Issue by noneherel** [xtekky/gpt4free#1965]
in the last version 0.3.1.2 I'm getting cloud flare detection error, the most time I'm using VPN on Nethrlands, and and the version 0.3.1.1 i've never got any error or anything else with YOU provider but when i updated to 0.3.1.2 i got this error with using VPN and when i turn the vpn off it worked, but when i got back to v0.3.1.1 the error has gone, so can anyone tell me the problem? i really need to use VPN.

**Comment by vrashad** [comment]
Yes same error. İ use mobile Proxy
