### ISSUE TITLE
Bing ends communication after the fifth message

### ISSUE THREAD

**Issue by KweezyCode** [xtekky/gpt4free#1967]
Bing sends an empty chunk after the fifth message (I don't get any response to the last message) if I use Conversation saving and stream=True

**Comment by vrashad** [comment]
Try use proxy anf change ip after 5-10 request

**Comment by hlohaus** [comment]
You can only do 4 requests? You can't create new conversations? Do you use the return_conversation=True argument to get the conversation to reuse them?

**Comment by KweezyCode** [comment]
> You can only do 4 requests? You can't create a new conversations? Do you use the return_conversation=True argument to get the conversation to reuse them?

i can create new conversations, but i can't send more than 4 messages in 1 conversation. I don't have conversation limit

**Comment by hlohaus** [comment]
Hello,

I would like to suggest adding the argument "return_conversation=True" to your request. This will allow you to retrieve the conversation object and include it in your subsequent messages.

Please note that you can only send one message at a time, but you can send multiple messages within a single conversation.

**Comment by KweezyCode** [comment]
> I would like to suggest adding the argument "return_conversation=True" to your request. This will allow you to retrieve the conversation object and include it in your subsequent messages.

i am already using it https://github.com/KweezyCode/TelegramGPTBot/blob/main/main.py

**Comment by hlohaus** [comment]
Okay, so the problem might be with return_conversation. Maybe I should refresh the session.

**Comment by KweezyCode** [comment]
![Screenshot_20240612-135516~2](https://github.com/xtekky/gpt4free/assets/36813920/368e02e9-a03d-4648-9e8c-541f995a2da0)

okay, i got it, it is not a bug, but a bing limit for unauthed users. How could i check limits using code?
