### ISSUE TITLE
Selecting "gpt-4o" as a model opens you.com automated browser window every 3-4 requests, doesn't run in headless mode

### ISSUE THREAD

**Issue by augusto-rehfeldt-2** [xtekky/gpt4free#1968]
**Bug description**
When using "gpt-4o" as the model in the chat.completions.create method, the webdriver opens and closes a window to you.com. This is a nuissance and should run in the background.

Console throws this, don't know if it's related, but the request works nevertheless and the provider returns a response.
```
 Proactor event loop does not implement add_reader family of methods required.
    Registering an additional selector thread for add_reader support.
    To avoid this warning use:
        asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())

  warnings.warn(PROACTOR_WARNING, RuntimeWarning)
```

ex.
1. Follow the text generation example
2. 
```
from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[{"role": "user", "content": "Hello"}],
    ...
)
print(response.choices[0].message.content)
```

3. Run and wait for a browser window to open and close immediately.
4. Notice unwanted behaviour.

**Environment**
- 3.11
- Argentina

Thanks!

**Comment by hlohaus** [comment]
Hey, you'll need to make an account for you.com. It creates an account every five requests using the browser. Don't worry about the warning.

**Comment by augusto-rehfeldt-2** [comment]
Thanks! But could it do so in --headless mode, so it doesn't just pop in?

**Comment by augusto-rehfeldt-2** [comment]
> Hey, you'll need to make an account for you.com. It creates an account every five requests using the browser. Don't worry about the warning.

Thanks! But could it do so in --headless mode, so it doesn't just pop in?

**Comment by hlohaus** [comment]
It doesn't works in headless mode. But you can use the docker image to hide it.
