### ISSUE TITLE
[You.com] Remove temp browser after use

### ISSUE THREAD

**Issue by vrashad** [xtekky/gpt4free#1980]
Is it possible to make it so that browsers are deleted after they have completed 5 requests while the code is running and not after stopping?

**Comment by hlohaus** [comment]
Hey, I'm not sure if I understand you correctly. But if you don't want to open a browser, you can create a .har file with telemetry requests. Once it finds a valid har file, it won't need a browser anymore.

**Comment by vrashad** [comment]
> Hey, I'm not sure if I understand you correctly. But if you don't want to use a browser here, you can create a .har file with the telemetry requests. Once it finds a valid har file, it won't need a browser anymore.

For every 5 requests, a Chrome browser profile is created in the temp folder. If you do not stop the process, the number of these profiles grows and the disk space that these profiles occupy increases. I mean, is it possible to make sure that used profiles are deleted immediately after they are used?

**Comment by hlohaus** [comment]
Maybe ask the nodriver package to change somethings
