### ISSUE TITLE
DeepInfra Provider

### ISSUE THREAD

**Issue by AHiXilTOr** [xtekky/gpt4free#1983]
**Bug description**
```
default_model = "meta-llama/Meta-Llama-3-70b-instruct"
```
the name does not match must be 
```
default_model = "meta-llama/Meta-Llama-3-70B-Instruct"
```

**Additional context**
`Error: Model is not supported: meta-llama/Meta-Llama-3-70b-instruct in: DeepInfra`

**Comment by hlohaus** [comment]
Hey, I just fixed the typo in the DeepInfra provider.
