### ISSUE TITLE
Docker image installation issue

### ISSUE THREAD

**Issue by joe-middys** [xtekky/gpt4free#1986]
I had the display issue after the docker image was installed, the chat page always shows the html source codes, please see below screenshot. I have installed it several times, the issue still occurred.
![mmexport1716182923259](https://github.com/xtekky/gpt4free/assets/113480910/b65fb89f-ce7f-49b5-9278-af36739cc494)

**Comment by hlohaus** [comment]
Hey, try using other model engines. Ecosia returns this HTML.

**Comment by joe-middys** [comment]
Thanks @hlohaus, I will try Ecosia.
