### ISSUE TITLE
windows python3.11 run error

### ISSUE THREAD

**Issue by recentcome** [xtekky/gpt4free#1987]
File "D:\chatgptcode\gpt4free\g4f\typing.py", line 2, in <module>
      from typing import Any, AsyncGenerator, Generator, AsyncIterator, Iterator, NewType, Tuple, Union, List, Dict, Type, IO, Optional
  ImportError: cannot import name 'Any' from partially initialized module 'typing' (most likely due to a circular import) (D:\chatgptcode\gpt4free\g4f\typing.py)

Remainder of file ignored
Traceback (most recent call last):
  File "D:\chatgptcode\gpt4free\g4f\gui\run.py", line 1, in <module>
    from .gui_parser import gui_parser
ImportError: attempted relative import with no known parent package

**Comment by hlohaus** [comment]
Weird. I use Python 3.11 too. Try using the .exe application from the release page.
