### ISSUE TITLE
422 Unprocessable Entity Error when using gpt4free with Dify 

### ISSUE THREAD

**Issue by muchkanensys** [xtekky/gpt4free#1989]
I am trying to use gpt4free with Dify on my Windows 11 environment, but I am encountering an error. Below are the details of my setup and the error message I received.

![image](https://github.com/xtekky/gpt4free/assets/82218031/8b31170f-70e4-4da1-93f3-39fe14782f94)

![image](https://github.com/xtekky/gpt4free/assets/82218031/f4fd201b-ca2d-472f-a7bb-362f3bc84653)

I would appreciate any guidance or suggestions on how to resolve this issue. If there are any additional logs or information needed, please let me know.
Thank you for your assistance.

**Comment by hlohaus** [comment]
The instructions are in the response. Your request data is invalid.

**Comment by muchkanensys** [comment]
from Dify

POST /v1/chat/completions HTTP/1.1
Host: host.docker.internal:1337
User-Agent: python-requests/2.31.0
Accept-Encoding: gzip, deflate, br, zstd
Accept: */*
Connection: keep-alive
Content-Type: application/json
Authorization: Bearer [__HIDDEN__]
Content-Length: 61

{"model": "gpt-3.5-turbo", "max_tokens": 5, "prompt": "ping"}


From g4f

HTTP/1.1 422 Unprocessable Entity
date: Mon, 20 May 2024 17:25:07 GMT
server: uvicorn
content-length: 84
content-type: application/json

{"detail":[{"loc":["body","messages"],"message":"Field required","type":"missing"}]}

**Comment by hlohaus** [comment]
The message fields are not present.
  "messages": [{"role": "user", "content", prompt}]
It does not support "prompt".

**Comment by muchkanensys** [comment]
Thank you for your response. 
Since it seems that the format is not supported, I will try to handle it myself.
 Thank you very much.
