### ISSUE TITLE
Image generation failed anytime

### ISSUE THREAD

**Issue by RobertAzovski** [xtekky/gpt4free#1990]
`from g4f.client import Client

client = Client()
response = client.images.generate(
  model="gemini",
  prompt="a white siamese cat",
)
image_url = response.data[0].url`

I used this sample from Quick Start here but it fails with error `g4f.errors.MissingAuthError: Missing "__Secure-1PSID" cookie`.

I also tried all other models to generate any image and it failed everytime.

**Comment by hlohaus** [comment]
Hey, have you tried the You, DeepInfra, and Replicate providers? Or you need an account with Microsoft, Google, or OpenAI to use them.
