### ISSUE TITLE
[OpenaiChat] Often reponds with Error 403: {"detail":"Unusual activity has been detected from your device..."} and [{"index":0,"message":{"role":"assistant","content":""},"finish_reason":"stop"}]

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1994]
I use the following code for the test:
```
from openai import OpenAI

client = OpenAI(
    api_key="asdf",
    base_url="http://localhost:1337/v1"
)

response = client.chat.completions.create(
    model="gpt-4o",
    extra_body={"provider": "OpenaiChat"},
    messages=[
      {
        "role": "system",
        "content": "You will be provided with a sentence in English, and your task is to translate it into French."
      },
      {
        "role": "user",
        "content": "This"
      }
    ],
    temperature=0.7,
    max_tokens=64,
    top_p=1
)
print(response.choices[0].message.content)
```

Almost every time I get
`Error 403: {"detail":"Unusual activity has been detected from your device..."}`
with the following
```
g4f.errors.RateLimitError: Response 429: Rate limit reached
INFO:     127.0.0.1:58861 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
```

And even when there are no errors - only the blank response but through the sniffer I see the following:
`[{"index":0,"message":{"role":"assistant","content":""},"finish_reason":"stop"}]`

![image](https://github.com/xtekky/gpt4free/assets/11407417/21962afb-0782-4d52-8d8c-b387d8738e52)

**Comment by iG8R** [comment]
Now, 22 May, 2024, 1:46 - to every request there is only one response
`[{"index":0,"message":{"role":"assistant","content":""},"finish_reason":"stop"}]`

And it doesn't depend on by what means the request to the `g4f API` was created - through the Python script or by other apps which worked fine before.
E.g.

<img src="https://github.com/xtekky/gpt4free/assets/11407417/7d32a6ec-79ce-4f44-b355-4a86c1498045" width="450">

**Comment by iG8R** [comment]
Error `[{ "index":0, "message":{ "role": "assistant", "content":""}, "finish_reason": "stop"}]` always arises when using 1 to 3 characters to translate via the `g4f API`.

**1 character example:**
```
from openai import OpenAI

client = OpenAI(
    api_key="asdf",
    base_url="http://localhost:1337/v1"
)

response = client.chat.completions.create(
    model="gpt-4o",
    extra_body={"provider": "OpenaiChat"},
    messages=[
      {
        "role": "user",
        "content": "Translate to English: 古"
      }
    ],
    temperature=0.7,
    max_tokens=64,
    top_p=1
)
print(response.choices[0].message.content)
```

**The sentence example:**
```
from openai import OpenAI

client = OpenAI(
    api_key="asdf",
    base_url="http://localhost:1337/v1"
)

response = client.chat.completions.create(
    model="gpt-4o",
    extra_body={"provider": "OpenaiChat"},
    messages=[
      {
        "role": "user",
        "content": "Translate to English: 有了古國四器在手，南柯老仙便可使用太古逆月陣，引下古國月光，來爲北蠻神療傷。"
      }
    ],
    temperature=0.7,
    max_tokens=64,
    top_p=1
)
print(response.choices[0].message.content)
```

![image](https://github.com/xtekky/gpt4free/assets/11407417/b5cd0598-2fdd-42ed-9905-cfb04e22ea89)

**Comment by iG8R** [comment]
Up

**Comment by KYKKIS2** [comment]
Same issue here, rate limit reached and goes for my gpt account too and i need to wait sometime till i continue using it again. Is there a workaround so we can use it for unlimited requests?

It's like g4f just uses my account that i have on chatgpt.com without me buying the API. That's what it's doing, i didnt buy the API but we have for it free using g4f. Isn't there a way to increase the requests?

**Comment by iG8R** [comment]
up

**Comment by iG8R** [comment]
up

**Comment by iG8R** [comment]
up

**Comment by Lorodn4x** [comment]
up
