### ISSUE TITLE
Rate limit reached error

### ISSUE THREAD

**Issue by peme969** [xtekky/gpt4free#1996]
**Known Issues** 
I have used other models before but I got a Chinese response when translated said that the system quota was reached in  your area. But for this gpt-4o model it returns a ratelimit reached error. Possibly due to bug when retrying providers?

**Bug description**
I simply used this code to use the model:
```python
    person = "bot personality here"
    message = input("enter chat message")
    client = Client()
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "system", "content": person}, {"role": "user", "content": message}]
    )
    return response.choices[0].message.content
```

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/136040410/dcc64ca1-c33c-4017-b1a6-a04d286bed17)

**Environment**
- python3.12
- Texas, USA

**Comment by againh3x** [comment]
i had the same issue with the Chinese response when using the gpt3.5-turbo model. I thought this was because I set my location to china a month prior by accident.

**Comment by peme969** [comment]
> i had the same issue with the Chinese response when using the gpt3.5-turbo model. I thought this was because I set my location to china a month prior by accident.

thats because the system quota was reached. i had that error **only** with the gpt-3.5/gpt-3.5-turbo model. i had to translate it and it says that the system quota was reached in my area

**Comment by againh3x** [comment]
> > i had the same issue with the Chinese response when using the gpt3.5-turbo model. I thought this was because I set my location to china a month prior by accident.
> 
> thats because the system quota was reached. i had that error **only** with the gpt-3.5/gpt-3.5-turbo model. i had to translate it and it says that the system quota was reached in my area

We have the same problem. I only get this error with gpt-3.5-turbo, and it assumes my location is in China when it is in the United States. When I use another model like gpt-4o, it gives me a CORS error which is weird because I have the correct header required. Someties when I run 3.5-turbo I don't get the Chinese response error which is also weird. its sort of random.

**Comment by peme969** [comment]
it doesnt assume your location is in china. its because the API's system
that xtekky hacked is in china. also for the gpt-4o model i think it works
but i tried it like a few weeks ago so i dont know what happen currently.
its not random. i feel like when we hit the limit usage it instantly
returns that chinese response. i dont know the limits so it *may* seem
random
