### ISSUE TITLE
gemini pro 

### ISSUE THREAD

**Issue by gamelist1990** [xtekky/gpt4free#1997]
The gemini pro API is going to be paid for, do you have any plans to do something about it?

**Comment by JayJayBinks** [comment]
I found this Git Repo where someone Reverse Engineered the AI Studio API. Maybe someone can integrate it to g4f
https://github.com/SreejanPersonal/Gemini-1.5-Pro-Google-AI-Studio-Reverse-Engineered-API

**Comment by gamelist1990** [comment]
I see

**Comment by iG8R** [comment]
@gamelist1990 
Could you please point out - where is the solution if this issue has been completed?

**Comment by gamelist1990** [comment]
No, it's not solved yet, but you can use GeminiProchat.py for free, so that might be one of the solutions.

**Comment by iG8R** [comment]
@gamelist1990 
I see, thank you.
