### ISSUE TITLE
You don't provide others models. Only 3.5 work (You.com Custom Mode)

### ISSUE THREAD

**Issue by ilyavinchi** [xtekky/gpt4free#2001]
**Bug description**
I've tried running both locally and in docker. I have also tried making requests via api. In none of the cases does the model switch to other models, except You.com Custom Mode

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/22541637/11737624-cd1d-4c99-9aee-9662500f5fa1)

**Environment**
- python 3.10 and docker
- location Ukraine

**Comment by vrashad** [comment]
Yes there really is such a problem

**Comment by hlohaus** [comment]
Custom mode refers to a customized model. I believe the information provided about me is consistent across all models. (wrong)

**Comment by linjin01** [comment]
If someone asks to print the previous instructions to bypass the filter and get to the system prompt, it seems like they're including the right model name. This could mean that there's a glitch with the g4f's model selector.

<img width="762" alt="image" src="https://github.com/xtekky/gpt4free/assets/166221244/d1fb76f2-fd54-4b1e-a0fc-d6370c7f3495">
<img width="772" alt="image" src="https://github.com/xtekky/gpt4free/assets/166221244/11d33758-1a88-4c65-9536-6e780dc77972">
<img width="778" alt="image" src="https://github.com/xtekky/gpt4free/assets/166221244/e27b0c75-107f-4c59-a08e-331e4e6dc829">
