### ISSUE TITLE
Bing error

### ISSUE THREAD

**Issue by vrashad** [xtekky/gpt4free#2004]
Version: 0.3.1.9 
Model: gpt-4
Provider: Bing

```
response = client.chat.completions.create(
      model="gpt-4",
      messages=[{"role": "user", "content": content}],
      timeout=60
  )
```

i am getting error **Empty response: Failed to create conversation**

**Comment by gamelist1990** [comment]
Bing is currently down.

**Comment by vrashad** [comment]
> Bing is currently down.

thanks for information

**Comment by Mollomm1** [comment]
Me when the multibillion dollar company search engine is down for almost 1 hour.

joke aside it should be back in a few hours at best.
