### ISSUE TITLE
Connection response error

### ISSUE THREAD

**Issue by ronalbo** [xtekky/gpt4free#2007]
This error occurs：aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host chatgpt.com:443 ssl:default [信号灯超时时间已到]
INFO:werkzeug:127.0.0.1 - - [23/May/2024 22:25:15] "POST /backend-api/v2/conversation HTTP/1.1" 200 -

**Comment by cjw-bbxc** [comment]
I also encountered the same problem, how to solve it?
