### ISSUE TITLE
This is the error in the Chrome browser on my smartphone:

### ISSUE THREAD

**Issue by dvetreti** [xtekky/gpt4free#2010]
An error occured: Liaobots: RetryProviderError: RetryProvider failed: You: FileNotFoundError: could not find a valid chrome browser binary. please make sure chrome is installed.or use the keyword argument 'browser_executable_path=/path/to/your/browser' Liaobots: ResponseStatusError: Response 500: Error

**Comment by kaileysong** [comment]
true too for me. working normally only when select gpt-4o

**Comment by dvetreti** [comment]
> true too for me. working normally only when select gpt-4o

This is actually a GPT-4 model, not a GPT-4o.  You can ask her yourself.

**Comment by kaileysong** [comment]
> > true too for me. working normally only when select gpt-4o
> 
> This is actually a GPT-4 model, not a GPT-4o. You can ask her yourself.

even better, considering unpleasant experience with it lately

**Comment by JimiPinorix** [comment]
Hello!

RetryProvider failed:
You: FileNotFoundError: could not find a valid chrome browser binary. please make sure chrome is installed.or use the keyword argument 'browser_executable_path=/path/to/your/browser' 
Liaobots: ResponseStatusError: Response 500: Error

How can I fix it?
