### ISSUE TITLE
GPT-4o not work?

### ISSUE THREAD

**Issue by babwyesdx** [xtekky/gpt4free#2011]
I'm confused about what I'm doing wrong. I'm using the aiogram library and gpt4free. At first, everything worked smoothly without any errors, but it was using the "gpt-3.5-turbo" model. Then, I decided to try the new "gpt-4o" model. I modified the code (without entering the API from the website), launched it, and the requests work, and responses are received. However, the responses started displaying "" instead of bold text, so I started changing the code (nothing worked, but it's fine). After a while, the model simply stopped working, regardless of the changes I made. I tried changing library versions, switching providers, but I get the same error:

Error: RetryProvider failed:
You: MissingRequirementsError: Add .har file from you.com or install "nodriver" package | pip install -U nodriver
Liaobots: TypeError: Object of type Message is not JSON serializable

Following the instructions, I installed "nodriver". After installation, the code started opening a page in Chrome, accessing the "You" provider website (which it didn't do before I started modifying the code because of the bold text issue). It seems like it should work, but even if it does, it launches the GPT-3.5 Turbo version from the "You" provider, not even "OpenAi".

I don't know what the exact problem could be. I suspect it might be due to running out of prompts, but when the code was working, only 3/5 responses were received, not 5/5. I'm using the code provided in the Text Generation section on the main page, only replacing "gpt-3.5-turbo" with "gpt-4o". Could this be because I didn't enter the API? If so, why did the code work initially? Is it possible to retrieve the responses?

**Comment by hasanelfalakiy** [comment]
I also have this problem

**Comment by Nofolobricity** [comment]
same

**Comment by hasanelfalakiy** [comment]
I just tried it again and it worked
![Screenshot_20240525_192228](https://github.com/xtekky/gpt4free/assets/96150715/834a04a6-79b1-4550-97a1-3b7ff23272e5)
![Screenshot_20240525_192043](https://github.com/xtekky/gpt4free/assets/96150715/f79c0e03-8127-4a1b-92cb-8e23c386f659)

**Comment by Lorodn4x** [comment]
I also have similar problems, 5 days ago everything worked, but now it doesn’t work; some models and changing the library version do not help.

**Comment by hasanelfalakiy** [comment]
Last night I tried again and many models didn't work
