### ISSUE TITLE
Bad Docs

### ISSUE THREAD

**Issue by BurgeEater** [xtekky/gpt4free#2015]
docs use this image generation example which is a wrong example:

from g4f.client import Client

client = Client()

response = client.images.generate(
    model="dall-e-3",
    prompt="a white siamese cat",
    ...
)

print(response.data[0].url)

**Comment by hlohaus** [comment]
What is wrong with this example?

**Comment by BurgeEater** [comment]
well even if you remove the 3 dots to correct the code you still get an error
