### ISSUE TITLE
local reasoning

### ISSUE THREAD

**Issue by gamelist1990** [xtekky/gpt4free#2021]
Can you tell me how to do local reasoning?

**Comment by Zedai00** [comment]
you're talking about  [this](https://g4f.mintlify.app/docs/core/usage/local)?

**Comment by gamelist1990** [comment]
That's right Can you tell me which model you recommend?

**Comment by Zedai00** [comment]
I have'nt used it yet but mistral or orca for conversations

**Comment by gamelist1990** [comment]
thank you

**Comment by Zedai00** [comment]
@gamelist1990 if it is complete can you close it
