### ISSUE TITLE
Issue with Recognizing Cookies from .har File Using OpenaiChat Provider

### ISSUE THREAD

**Issue by mf-skjung** [xtekky/gpt4free#2035]
I followed the instructions to access https://chatgpt.com and generated a .har file, which I then placed in the `har_and_cookies` folder. I have also configured the code to track this using the following setup:

```
import g4f.debug
g4f.debug.logging = True

cookies_dir = "har_and_cookies"
set_cookies_dir(cookies_dir)
read_cookie_files(cookies_dir)
```

However, while the .har file is detected correctly, the internal cookies are not being properly added.

![image](https://github.com/xtekky/gpt4free/assets/102794650/89f83ba9-f079-477e-b102-b4694594865b)

Until a few days ago, the OpenaiChat Provider was working fine, but now I'm encountering an error where the cookies from the .har file are not being recognized.

What could be the problem here? Any insights or suggestions on how to resolve this issue would be greatly appreciated.

**Comment by ozipoetra** [comment]
I thought this only happen to me

**Comment by Mohamed3nan** [comment]
Same!

I guess because OpenAI changed the link from "https://chat.openai.com" to "https://chatgpt.com"

**Comment by gamelist1990** [comment]
Apparently [openai/har_file.py] and [OpenAIChat.py] seem to support url = "https://chatgpt.com"

**Comment by alikhankrutoi** [comment]
same problem with the file .har, it was working fine, but it stopped working a week or even two weeks ago, it's reading .har at startup, but when you send a message, an error is returned and it says that it is missing .har
