### ISSUE TITLE
Gives this error on windows g4f.errors.MissingAuthError: Add a "api_key" or a .har file

### ISSUE THREAD

**Issue by ivyy7** [xtekky/gpt4free#2040]
g4f.errors.MissingAuthError: Add a "api_key" or a .har file

**Comment by BurgeEater** [comment]
just add a har file dude

**Comment by CaesarCzechUnleashed** [comment]
Would like to ask where do i put har file on windows install ? i tried placing it g4f directory in internal etc and it doesnt seem to work, is it possible to have it on the easy to use win install or do i need to go for docker or python to get it working  ?

**Comment by iG8R** [comment]
Still the same error.

![image](https://github.com/xtekky/gpt4free/assets/11407417/7df64bde-de74-4536-b10a-d3e04a011964)

**Comment by ZohaibAhmadDev** [comment]
Too much late response and also give error on adding image   
An error occured: TypeError: Assignment to constant variable. 

Also not image genrate .Its totally useless behavior in my case.

**Comment by iG8R** [comment]
up
