### ISSUE TITLE
I get this error when trying to get a response from the gpt-4 model (provider - You):

### ISSUE THREAD

**Issue by LimePeople** [xtekky/gpt4free#2041]
You: MissingRequirementsError: Add .har file from you.com or install "nodriver" package | pip install -U nodriver

**Comment by comeback01** [comment]
With which application?

On my side, I have no problem.

![image](https://github.com/xtekky/gpt4free/assets/17897116/fa229e60-feba-4d2f-8947-8b0a078364a0)
![image](https://github.com/xtekky/gpt4free/assets/17897116/47d84b49-83e7-4b1e-b24a-b06009fa6f13)

**Comment by LimePeople** [comment]
![error](https://github.com/xtekky/gpt4free/assets/135664781/0a825fc0-5933-46da-8061-c309a5cd8cde)
The program gives me this message when I try to ask for any model of You provider (gpt 3.5 works, however other models do not)

**Comment by Zedai00** [comment]
@LimePeople did you read [this](https://github.com/xtekky/gpt4free?tab=readme-ov-file#using-har-and-cookie-files)
