### ISSUE TITLE
Provider You gpt-4o not working

### ISSUE THREAD

**Issue by bsbrother** [xtekky/gpt4free#2046]
$ python -m g4f.cli gui -port 8080 
# GUI 
    ->Goto bottom, select 'gpt-4o' 'You'
    ->Prompt: Linda has 3 sisters, Paul has 4 sisters, Can Linda and Paul be siblings
# Provider You is not correct:
An error occured: You: ResponseStatusError: Response 401: {"status_code":401,"request_id":"request-id-live-60b307df-c033-4ab4-8491-c0352fe09bf1","error_type":"endpoint_not_authorized_for_sdk","error_message":"The project owner has not authorized the SDK to call this endpoint. Please enable it in the dashboard to continue: https://stytch.com/dashboard/sdk-configuration.","error_url":"https://stytch.com/docs/api/errors/401#endpoint_not_authorized_for_sdk"}
 
Thank you !

**Comment by Looksh190** [comment]
Saame!

**Comment by Looksh190** [comment]
I checked you.com and noticed that they no longer provide 5 free requests for unregistered users.
Gone is the era...

**Comment by SP-l33t** [comment]
> I checked you.com and noticed that they no longer provide 5 free requests for unregistered users. Gone is the era...
> 
> PS:Or maybe I'm just stupid

You seem to be wrong, because I just made a new account and had 3 free requests (not 5 like before). Bit they changed the auth, so the old method doesn't work anymore, unless someone finds a way to fix.
