### ISSUE TITLE
You.com - The project owner has not authorized the SDK to call this endpoint

### ISSUE THREAD

**Issue by Looksh190** [xtekky/gpt4free#2048]
C:\Users\User>g4f api
Starting server... [g4f v-0.3.2.0]
[32mINFO[0m:     Started server process [[36m6004[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:1337[0m (Press CTRL+C to quit)
[32mINFO[0m:     127.0.0.1:49931 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
ERROR:root:Response 401: {"status_code":401,"request_id":"request-id-live-bfe65645-85d3-4576-bb6c-1ee26f6ba59f","error_type":"endpoint_not_authorized_for_sdk","error_message":"The project owner has not authorized the SDK to call this endpoint. Please enable it in the dashboard to continue: https://stytch.com/dashboard/sdk-configuration.","error_url":"https://stytch.com/docs/api/errors/401#endpoint_not_authorized_for_sdk"}
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\api\__init__.py", line 167, in chat_completions
    return JSONResponse((await response).to_json())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\client\async_client.py", line 71, in iter_append_model_and_provider
    async for chunk in response:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\client\async_client.py", line 42, in iter_response
    async for chunk in response:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\You.py", line 80, in create_async_generator
    cookies = await cls.get_cookies(session) if chat_mode != "default" else None
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\You.py", line 167, in get_cookies
    cls._cookies = await cls.create_cookies(client)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\You.py", line 215, in create_cookies
    await raise_for_status(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\requests\raise_for_status.py", line 28, in raise_for_status_async
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 401: {"status_code":401,"request_id":"request-id-live-bfe65645-85d3-4576-bb6c-1ee26f6ba59f","error_type":"endpoint_not_authorized_for_sdk","error_message":"The project owner has not authorized the SDK to call this endpoint. Please enable it in the dashboard to continue: https://stytch.com/dashboard/sdk-configuration.","error_url":"https://stytch.com/docs/api/errors/401#endpoint_not_authorized_for_sdk"}

**Comment by ZodiussDev** [comment]
me too

**Comment by giaphupham** [comment]
me too !

**Comment by Anonymous6598** [comment]
Have you read docs about YOU.com provider?

**Comment by Anonymous6598** [comment]
It seems that YOU provider is broken and requires some fixes. Try using another provider or use `LocalClient()` class, therefore you will not need to depend on the provider. Use mistral-7b-openorca model, because YOU uses it. But to install it, you need to run IDE or code editor in admin mode.

**Comment by Anonymous6598** [comment]
Do you want me to show you, how to use the local model?

**Comment by Looksh190** [comment]
> Do you want me to show you, how to use the local model?

I originally wanted to get some kind of answer from xtekky about this, perhaps to find a solution to this problem with other users, since YOU.com provider has limited its use again. Where did YOU see even a word about local models? We are talking about Claude and GPT-4. Thank YOU, but that's not a solution to the problem.

**Comment by Anonymous6598** [comment]
From g4f docs site

**Comment by Anonymous6598** [comment]
https://g4f.mintlify.app/docs/core/usage/local

**Comment by Anonymous6598** [comment]
You can see list of local models. Perhaps something might be suitable.

**Comment by Anonymous6598** [comment]
@Looksh190, did it help?

**Comment by ExecutedPoorly** [comment]
@Anonymous6598 
Just wanted to say thanks, I'm using another local image model and with this I can completely automate everything now.

**Comment by Anonymous6598** [comment]
You're welcome

**Comment by Anonymous6598** [comment]
> @Anonymous6598 
> Just wanted to say thanks, I'm using another local image model and with this I can completely automate everything now.

You're welcome

**Comment by Anonymous6598** [comment]
@Looksh190, are you going to close this issue as finished?

**Comment by Looksh190** [comment]
> @Looksh190, are you going to close this issue as finished?

Your alternative doesn't solve the problem with You.com, I still get the SDK error and the local models don't interest me

**Comment by Anonymous6598** [comment]
Wait, try installing Claude-3.gguf file and put it in the folder for local models. Consider this option only if you can do it.

**Comment by Looksh190** [comment]
> Wait, try installing Claude-3.gguf file and put it in the folder for local models. Consider this option only if you can do it.

You seem to be a bit misunderstanding the phenomenon of models like the Claude and GPT-3.5/4/4o. These aren't small local models, they have completely different weight classes, literally. They run on huge servers, not desktop PCs. That's why I need help with a You.com provider that provides access to such modern language models

**Comment by Anonymous6598** [comment]
I get it.

**Comment by Looksh190** [comment]
Are they going to remove You.com from the list of providers?
