### ISSUE TITLE
 IP has been blocked

### ISSUE THREAD

**Issue by RezaRamezanisani** [xtekky/gpt4free#2066]
when request i see this response:

`Sorry, your IP has been blocked due to triggering anti-abuse detection. It may be because you use a cloud server such as Tencent Cloud or a foreign proxy (VPN) to access this website. If you use a VPN, you can continue to use it by turning off the VPN or proxy. The website address of this service is https://chat18.aichatos8.com. If you need to call the cooperative interface, please contact WeChat chatkf123 or go to https://binjie09.shop to purchase a key by yourself. If you think it is a mistaken block and need to be unblocked, please go to https://www.ip.cn/ to query the IP information and send a message to gpt33@binjie.site. The webmaster will check the email regularly and handle the unblocking and cooperation issues. If you need to call the interface, please see the interface document https://apifox.com/apidoc/shared-803d9df6-a071-4b3e-9d69-ea1281614d82. If you need to call the cooperative interface, please contact WeChat chatkf123 or go to https://cat.gptxyy.cn to register and use it (gpt4 can be used for a fee). Register for free to use 3.5)`

how to fix bug?
thanks

**Comment by kpripper** [comment]
The same problem.

**Comment by Hydra566** [comment]
> when request i see this response:
> 
> `Sorry, your IP has been blocked due to triggering anti-abuse detection. It may be because you use a cloud server such as Tencent Cloud or a foreign proxy (VPN) to access this website. If you use a VPN, you can continue to use it by turning off the VPN or proxy. The website address of this service is https://chat18.aichatos8.com. If you need to call the cooperative interface, please contact WeChat chatkf123 or go to https://binjie09.shop to purchase a key by yourself. If you think it is a mistaken block and need to be unblocked, please go to https://www.ip.cn/ to query the IP information and send a message to gpt33@binjie.site. The webmaster will check the email regularly and handle the unblocking and cooperation issues. If you need to call the interface, please see the interface document https://apifox.com/apidoc/shared-803d9df6-a071-4b3e-9d69-ea1281614d82. If you need to call the cooperative interface, please contact WeChat chatkf123 or go to https://cat.gptxyy.cn to register and use it (gpt4 can be used for a fee). Register for free to use 3.5)`
> 
> how to fix bug? thanks

This is not a bug or an error, these are limitations of the provider. He blocked your IP for excessive use. Everything is stated in the message. This can only be solved by changing your IP, for example by using a Proxy.
