### ISSUE TITLE
libllmodel.dll is missing

### ISSUE THREAD

**Issue by Anonymous6598** [xtekky/gpt4free#2067]
My python script is complaining about missing libllmodel.dll instruction. How to fix it?
error message:
```
FileNotFoundError: Could not find module 'C:\Users\USER\AppData\Local\Temp\_MEI137762\gpt4all\llmodel_DO_NOT_MODIFY\build\libllmodel.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by Anonymous6598** [comment]
Fixed

**Comment by Tkag0001** [comment]
I have same issue, how can you fix it?

**Comment by Anonymous6598** [comment]
Just downgrade gpt4all from 2.7.0 to 2.6.0 . This will be a solution to your problem. Gpt4all API was installed incorrectly, therefore just downgrade. It worked for me.

**Comment by Tkag0001** [comment]
Thannk you sir, it work <3
