### ISSUE TITLE
Liaobots and You don't work

### ISSUE THREAD

**Issue by Hydra566** [xtekky/gpt4free#2070]
Liaobots and You do not work, they give the following errors:

```
Liaobots: ResponseStatusError: Response 500: Error
``` 

```
You: ResponseStatusError: Response 401: {"status_code":401,"request_id":"request-id-live-183191e7-adc1-4838-8e29-6e0c5c3ca048","error_type":"endpoint_not_authorized_for_sdk","error_message":"The project owner has not authorized the SDK to call this endpoint. Please enable it in the dashboard to continue: https://stytch.com/dashboard/sdk-configuration.","error_url":"https://stytch.com/docs/api/errors/401#endpoint_not_authorized_for_sdk"}
``` 
@xtekky @hlohaus

**Comment by gamelist1990** [comment]
As for the Liaobots, I have a solution.

**Comment by gamelist1990** [comment]
![image](https://github.com/xtekky/gpt4free/assets/118247906/d057162b-7316-4477-94f7-8d0f85a2cdc1)
Lines 177 through 177 in liaobots.py async with session.post(
                    "https://liaobots.work/api/user",.
                    json={"authcode": "xxxxxxxxxx"},#Change authcode ,gain by Lianobots
                    verify_ssl=False
                ) with the authcode obtained from the Liaobots site replaced with xxxxxxxxxx will work

**Comment by gamelist1990** [comment]
@Hydra566 Try it out.

**Comment by gamelist1990** [comment]
And if you want to use geminipro1.5 in addition to the current model, add
 "gemini-1.5-pro-latest": {
        "id": "gemini-1.5-pro-latest", "name": "Gemini-1.5-pro-latest", {
        "name": "Gemini-1.5-Pro-1M", { "id": "gemini-1.5-pro-latest", { "maxLength": 4000000000000
        "maxLength": 4000000, "tokenLimit": 1000000
        "tokenLimit": 1000000, "context": "1024K", "name": "Gemini-1.5-Pro-1M", "maxLength": 4000000, "tokenLimit": 1000000
        "context": "1024K", }
    } 
try adding

**Comment by hikenneth** [comment]
> And if you want to use geminipro1.5 in addition to the current model, add "gemini-1.5-pro-latest": { "id": "gemini-1.5-pro-latest", "name": "Gemini-1.5-Pro-1M", "maxLength": 4000000, "tokenLimit": 1000000, "context": "1024K", } try adding

pls give more detail, thank you!

**Comment by gamelist1990** [comment]
As for the you provider, I did a little research on Logging, but it doesn't work, but the default model gpt3.5turbo seems to work.

**Comment by gamelist1990** [comment]
As for the You provider, I see from your error message that you're calling the SDK endpoint in the Stytch API, but the owner of You.com forbids you from calling the sdk.
