### ISSUE TITLE
chinese characters output

### ISSUE THREAD

**Issue by glennford49** [xtekky/gpt4free#2073]
why is some output chinese characters?

**Comment by Redditask** [comment]
this lib also use chinese sites as providers

**Comment by Redditask** [comment]
what output you get?

**Comment by wwwjj2** [comment]
It is closed but I also get chinese half-russian half-chinese output when I prompt in russian and expect russian response all the time.
This is nonsense:

> В этом тексте, который был ошибочно распознан, упоминается💡 процесс передачи на радио, связанный с защитными кристаллами² (вероятно, это были кристаллы дляコンテンツа или фильтрации).模样 стали активными或者说 начали функционировать大概20 лет назад. Europol,这个名字, скорее всего, связан с сетью или广播, начал свою работу. В эпизоде, который продолжался 20 минут, номер был 1502, и упоминается о локонах (предположительно, это сцены, эпизоды или возможные студийные участки).

**Comment by wwwjj2** [comment]
Another output example (prompt is 100% russian):

> 根据提供的文本， radioshow 的内容主要是关于一场大火的报道。事件发生在“Смыкова”村，火灾的中心位于“центры занятости населения”（可能是指人口聚居点）。人员已经开启了“седьмое отделение”和“двадцать первое отделение”等消防队伍，以扑灭大火。同时，救援人员也部署在“шестнадцатой части”和“восьмой части”，并且已经发送了“третья цистерна”以提供援助。事件的发展情况没有提供详细信息，但可以看出消防队伍和救援人员正在努力扑灭大火。

**Comment by wwwjj2** [comment]
@Redditask can you please take a look at the output and give any advice on it? I really don't know what to do with this. By the way, rarely I get some decent responses in russian, but most cases include half-russian half-chinese respose
