### ISSUE TITLE
The 3.5 model has stopped working

### ISSUE THREAD

**Issue by BokDan93** [xtekky/gpt4free#2074]
The gpt 3.5 model has stopped working
Errors:

You: CloudflareError: Response 403: Cloudflare detected
Cnote: ClientResponseError: 404, message='Not Found', url=URL('https://p1api.xjai.pro/freeapi/chat-process')
Aichatos: ClientResponseError: 403, message='Forbidden', url=URL('https://api.binjie.fun/api/generateStream')
ChatgptNext: ClientResponseError: 429, message='Too Many Requests', url=URL('https://chat.fstha.com/api/openai/v1/chat/completions')
OpenaiChat: MissingAuthError: Add a "api_key" or a .har file

use providers:
client = G4fClient(provider=RetryProvider([Aichatos, Cnote, ChatgptNext, OpenaiChat, You]))

**Comment by Najmul190** [comment]
real 😔
