### ISSUE TITLE
HuggingChat provider is not working - ResponseStatusError: Response 500

### ISSUE THREAD

**Issue by MRGRD56** [xtekky/gpt4free#2078]
### Bug description

When I try to use the HuggingChat provider, having added a cookies/har file, I always get the same error: `An error occurred: HuggingChat: ResponseStatusError: Response 500:`

```
Using HuggingChat provider and CohereForAI/c4ai-command-r-plus model
INFO:werkzeug:192.168.80.1 - - [22/Jun/2024 16:31:48] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
ERROR:root:Response 500: 
Traceback (most recent call last):
  File "/app/g4f/gui/server/api.py", line 177, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/providers/base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/g4f/providers/base_provider.py", line 52, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/app/g4f/Provider/HuggingChat.py", line 99, in create_async_generator
    await raise_for_status(response)
  File "/app/g4f/requests/raise_for_status.py", line 28, in raise_for_status_async
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 500:
```

### Steps to reproduce

1. Put your cookies json file / har file for `huggingface.co` in the `har_and_cookies` directory
2. Run gpt4free in Docker using docker compose
3. Open g4f web ui (using OpenAI compatible API (port `1337`) gives the same error, though)
4. Select this provider: `HuggingChat (Auth)`
5. Select any model, for example `CohereForAI/c4ai-command-r-plus`
6. Send any message to the LLM
7. See the error

### Screenshot

![image](https://github.com/xtekky/gpt4free/assets/35491968/7afaf19b-4af2-4703-8bf3-c4c02eb511fc)

### Environment

- gpt4free version 0.3.2.0 (this git repository, commit `e8f6013d`)
- docker compose
- Ubuntu 22.04.4 LTS x86_64

-----

duplicates https://github.com/xtekky/gpt4free/issues/2053 which is closed

**Comment by Anurag-Varma** [comment]
To reproduce, you should go to https://huggingface.co/chat/ and then get the cookies.

You mentioned to get cookies from https://huggingface.co/, which doesn't work.

Apart from this, i tried it and getting 

[HuggingChat ](https://huggingface.co/chat)with CohereForAI/c4ai-command-r-plus
An error occured: HuggingChat: ResponseStatusError: Response 500:

**Comment by Anurag-Varma** [comment]
Hi @xtekky or @MRGRD56 

I fixed the bug in my local repo, can you say on how to do any kind of unit tests to verify it ?
(I am a new contributer, so dont know much of the rules, Sorry)

Thanks

**Comment by MRGRD56** [comment]
@Anurag-Varma Hi! I'm not a contributor so I don't know

But, could you please share your solution? Even if it's not tested well

**Comment by Anurag-Varma** [comment]
@MRGRD56 there are few lines which were changed in the pull request.

This fixed 500 response error, but still the logic in this provider is wrong, dont know who did it.

 According to the present code it basically replaces the 1st command each time a new message is sent, So multiple versions of the first command are being created when i checked in huggingface chat website. Instead it should create separate chats for each message sent from user.
 
 And also it has wrong code related to stream flag, should modify event that.

**Comment by MRGRD56** [comment]
@Anurag-Varma 
Thank you! I've tried it out, seems to be working

> Instead it should create separate chats for each message sent from user.

Separate _chats_ for each message?

do you mean something like this, separate _messages_?

<img src="https://github.com/xtekky/gpt4free/assets/35491968/ce220f5d-83d5-4c78-abaf-8f1911a4012a" width="350"></img>

but not like this, in a single message as it is right now?

<img src="https://github.com/xtekky/gpt4free/assets/35491968/8f49b53e-70e7-4cf6-b503-b51bc3f457d6" width="500"></img>

or what do you mean?

**Comment by Anurag-Varma** [comment]
For hugging face provider:

Currently running it in http://127.0.0.1:8080/chat for a chat gives the below image 
![image](https://github.com/xtekky/gpt4free/assets/62068859/22f61eba-41df-48d3-9f24-b63d8034184b)

For the same chat which is saved in huggingface website, below is the image.
![image](https://github.com/xtekky/gpt4free/assets/62068859/772964fc-77b5-4152-b4b8-16ced5ff75d4)


As you see, it's just over riding the 1st message and unable to remember previous messages.

This is not like how it's present in your ss images.

**Comment by xtekky** [comment]
Fixed
