### ISSUE TITLE
how to disable check g4f version while running?

### ISSUE THREAD

**Issue by maston2** [xtekky/gpt4free#2083]
Every time g4f is used, it will automatically check for version updates, resulting in longer response time. Can this check be disabled?

![image](https://github.com/xtekky/gpt4free/assets/124343921/37ce4476-fc56-4e3f-8f7d-bfb0c334e7cc)

**Comment by Anurag-Varma** [comment]
In g4f folder, in the debug.py file:

By default version checking is set true

```
version_check: bool = True
```

Just change it to ```False```


If this fixes the problem, then can close this issue.
