### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by f1ttJK** [xtekky/gpt4free#2084]
The error appeared after I installed `nodriver`.

Console log: https://mystb.in/fe2ed6bb9e55ddbd22

![image](https://github.com/xtekky/gpt4free/assets/114262309/2dbca522-4ac5-48f5-aabb-4173d3d252d1)

**Comment by Anurag-Varma** [comment]
Use .har file with cookies for You provider

For Liaobots, you have the limit reached for gpt-4o

**Comment by 1426002590** [comment]
> 将 .har 文件与 Cookie 一起用于 You 提供程序
> 
> 对于 Liaobots，您已经达到了 gpt-4o 的限制

Hoe werk dit?.har en wat is koekies?
