### ISSUE TITLE
Please make sure you are using a valid cloudflare clearance token and user agent.

### ISSUE THREAD

**Issue by OPbjO** [xtekky/gpt4free#209]
![image](https://user-images.githubusercontent.com/40695047/234940229-e2cb1bb1-945e-4efd-899c-eb6cd6379ff6.png)
streamlit_app.py：
![image](https://user-images.githubusercontent.com/40695047/234940514-75a0d0cd-c128-4267-90b2-58f6d2169feb.png)

What should I do?

**Comment by OPbjO** [comment]
![image](https://user-images.githubusercontent.com/40695047/234941439-ff10e581-c8fa-4f84-a764-2da3697ac73d.png)

**Comment by Yreidn** [comment]
Same error here.

**Comment by sedrof** [comment]
same error, this should be a new one

**Comment by d2rgaming-9000** [comment]
How are you even supposed to use and install this one.

**Comment by petitsurfeur** [comment]
I get the same error

**Comment by xtekky** [comment]
phind got removed

**Comment by Cheizr** [comment]
Welp it seems that we are all on the same boat

**Comment by sergioparadiso** [comment]
> ![image](https://user-images.githubusercontent.com/40695047/234941439-ff10e581-c8fa-4f84-a764-2da3697ac73d.png)

i didn't do this way but seems pretty the same thing.
to trick cloudfare you have to specify a user agent, you can edit here **/you/__init__.py**

and change the line marked below.
![image](https://user-images.githubusercontent.com/60114754/235308596-21607111-943b-44bc-8635-7c06cdd66e2b.png)

if it still not working try to change the line below in the same file matching your chromebrowser version (mine it's 111.xxx.xxx) you have to match the first 3 numbers (how to set this is explained widely on the net)
![image](https://user-images.githubusercontent.com/60114754/235308755-75166eb9-5b91-4e22-914f-32e07a6dfc12.png)

**Comment by SUGAM-ARORA** [comment]
got it

**Comment by devsidenl** [comment]
What helped me is:
`pip install --upgrade fake-useragent`
