### ISSUE TITLE
you.com GPT4.0 cannot be used

### ISSUE THREAD

**Issue by 1426002590** [xtekky/gpt4free#2093]
you.com GPT4.0 cannot be used
![屏幕截图 2024-07-04 202305](https://github.com/xtekky/gpt4free/assets/167799793/1bf5c4d6-7876-4952-a6c8-9a2961a8e6d8)
Only GPT3.5 can be used

**Comment by noneherel** [comment]
> you.com GPT4.0 cannot be used ![屏幕截图 2024-07-04 202305](https://private-user-images.githubusercontent.com/167799793/345830303-1bf5c4d6-7876-4952-a6c8-9a2961a8e6d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNzg2NzcsIm5iZiI6MTcyMDI3ODM3NywicGF0aCI6Ii8xNjc3OTk3OTMvMzQ1ODMwMzAzLTFiZjVjNGQ2LTc4NzYtNDk1Mi1hNmM4LTlhMjk2MWE4ZTZkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNTA2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmYyMTE1NzM0M2I0YWIyNDY4ZmJjNDhlYmIxMzQ3OTg5NzE5YWEzZmZiMmQ2Nzg4MmM0ZGY2OTAyYWNhNTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.57dOjBoaEAE5yxnw_ETmA5s_ef3I_TQiwgn6Vp54NwM) Only GPT3.5 can be used

Same
