### ISSUE TITLE
How to generate Images ??

### ISSUE THREAD

**Issue by RobertAzovski** [xtekky/gpt4free#2096]
I tried several models and providers that are supposed to generate images but everytime either get `ERROR:root:[Errno 2] No such file or directory: './generated_images\\1720182687_d4ebaebe-3013-4bbc-960e-cf4e0088a7ef'` or it requires api_key.

Could someone write a list of working models and providers combination that can generate images

**Comment by BinhPQ2** [comment]
Here is the code I usually use, bear in mind that I have just know about this repo for 2 hours.

```
from g4f.client import Client

img_models = ['flux-anime','sdxl', 'sd-3', 'playground-v2.5', 'flux', 'flux-realism', 'dalle', 'dalle-2', 'dalle-mini', 'emi']

client = Client()

for model in img_models:
    try:
        print(f'Generating image with {model}')
        response = client.images.generate(
            model=model,
            prompt="create a picture in anime style of a long blue hair girl in evangelion style",
        )
        image_url = response.data[0].url
        print(f"Generated image URL: {image_url}")
    except Exception as e:
        print(f"Error with {model}: {str(e)}")
    print("------------------------")
```
