### ISSUE TITLE
HuggingChat some model request conversationId

### ISSUE THREAD

**Issue by TheFirstNoob** [xtekky/gpt4free#2101]
Hi, i test HuggingChat provider for avalable models and find error:
`HuggingChat: KeyError: 'conversationId'`

**Model who need this key param:**
```
HuggingFaceH4/zephyr-orpo-141b-A35b-v0.1
google/gemma-1.1-7b-it

```

Other models working fine and not request this key param

**Comment by Anurag-Varma** [comment]
Verified this bug exists in HuggingFaceH4/zephyr-orpo-141b-A35b-v0.1:

![image](https://github.com/xtekky/gpt4free/assets/62068859/fad60f0d-782d-4e9c-860b-2199fbfa4ef3)


```
Using HuggingChat provider and HuggingFaceH4/zephyr-orpo-141b-A35b-v0.1 model
INFO:werkzeug:127.0.0.1 - - [11/Jul/2024 01:37:37] "GET /static/img/user.png HTTP/1.1" 304 -
ERROR:root:'conversationId'
Traceback (most recent call last):
  File "C:\Users\panur\gpt4free\g4f\gui\server\api.py", line 177, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "C:\Users\panur\gpt4free\g4f\Provider\HuggingChat.py", line 80, in create_completion
    conversationId = response.json()['conversationId']
KeyError: 'conversationId'
INFO:werkzeug:127.0.0.1 - - [11/Jul/2024 01:37:38] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by Anurag-Varma** [comment]
The below models are removed from [https://huggingface.co/chat/settings](https://huggingface.co/chat/settings)

```
HuggingFaceH4/zephyr-orpo-141b-A35b-v0.1
google/gemma-1.1-7b-it
```

![image](https://github.com/xtekky/gpt4free/assets/62068859/a4637560-8ab7-487b-9cd1-f67c8e279911)

**Comment by Anurag-Varma** [comment]
Hi @xtekky ,

Can you check the issue, I verified it issue exists and sent a PR fix for it.

**Comment by Anurag-Varma** [comment]
There is already a PR #2103

It fixes this issue, once the PR is merged, this issue can be closed
