### ISSUE TITLE
how to use local api

### ISSUE THREAD

**Issue by cstybbt** [xtekky/gpt4free#2116]
![77453E13-E797-443A-9BB5-9DC31A3AFD02](https://github.com/user-attachments/assets/a4129b15-8769-4708-a26a-a7e7e76cfe68)
![1A7A0246-F86E-46B6-87B9-50493DA66BC8](https://github.com/user-attachments/assets/5f6ba647-716d-4c15-84fb-49464c1de35b)
![90A2F708-2694-4048-96A3-A0C13C1B88DE](https://github.com/user-attachments/assets/731c873a-b746-481d-8220-22fa8a95fc8e)
![528D1E34-58AB-4B7C-BA95-3FF9C5D3233B](https://github.com/user-attachments/assets/ed66e7e9-c2de-4504-9515-35bd5a7c599e)
The project is running in a Docker container and the .har file has been added to the directory. When calling the 1337 port with Python, an error occurs.

**Comment by cstybbt** [comment]
![03E492F7-6D0B-4DBC-B651-33BCD3AD50A2](https://github.com/user-attachments/assets/1aa8ac79-6d1c-4d97-8eb0-920252bcdc79)
Is it set up like this

**Comment by junjiezhou1122** [comment]
Hi, I have the same problem. If you solve the problem, please comment to me. Thank you.
`#!/usr/bin/env python3

import os
import sys
from g4f.client import Client
from colorama import Fore, Style, init

# Initialize colorama
init()

# Function to clear the terminal screen
def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

# Create a client instance
client = Client()

# Initialize chat history and add a system prompt, specifying the response language as Chinese
chat_history = [
    {"role": "system", "content": "Explain it to me and give me some insights about the topic. Please respond in English as defult"},
]

try:
    while True:
        user_message = input(Fore.YELLOW + "You: " + Style.RESET_ALL)  # User inputs a message with colored prompt
        if user_message.lower() == 'exit':
            break
        
        if user_message.lower() == 'clear':
            clear_screen()
            continue

        # Add the user's message to the chat history
        chat_history.append({"role": "user", "content": user_message})

        # Generate the AI's response
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=chat_history  # Pass the entire chat history
        )

        # Get the AI's response content
        ai_response = response.choices[0].message.content

        # Add the AI's response to the chat history
        chat_history.append({"role": "assistant", "content": ai_response})

        # Print the AI's response with styling
        print(Fore.GREEN + "AI: " + Style.BRIGHT + ai_response + Style.RESET_ALL)
except KeyboardInterrupt:
    print(Fore.RED + "\nExiting..." + Style.RESET_ALL)` 
It works on the terminal. I know that we all wanna solve problem about how to use our local environment to using gpt api.

**Comment by junjiezhou1122** [comment]
Hi, I have the same problem. If you solve the problem, please comment on it for me. Thank you.
```
#!/usr/bin/env python3

import os
import sys
from g4f.client import Client
from colorama import Fore, Style, init

# Initialize colorama
init()

# Function to clear the terminal screen
def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

# Create a client instance
client = Client()

# Initialize chat history and add a system prompt, specifying the response language as Chinese
chat_history = [
    {"role": "system", "content": "Explain it to me and give me some insights about the topic. Please respond in English as defult"},
]

try:
    while True:
        user_message = input(Fore.YELLOW + "You: " + Style.RESET_ALL)  # User inputs a message with colored prompt
        if user_message.lower() == 'exit':
            break
        
        if user_message.lower() == 'clear':
            clear_screen()
            continue

        # Add the user's message to the chat history
        chat_history.append({"role": "user", "content": user_message})

        # Generate the AI's response
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=chat_history  # Pass the entire chat history
        )

        # Get the AI's response content
        ai_response = response.choices[0].message.content

        # Add the AI's response to the chat history
        chat_history.append({"role": "assistant", "content": ai_response})

        # Print the AI's response with styling
        print(Fore.GREEN + "AI: " + Style.BRIGHT + ai_response + Style.RESET_ALL)
except KeyboardInterrupt:
    print(Fore.RED + "\nExiting..." + Style.RESET_ALL)
```
This works well on the terminal. But I can't use other apps to refer to the local address.

**Comment by mak448a** [comment]
I know this is unrelated, but do you know how to use the .har file?
