### ISSUE TITLE
Hi, can it find objects in a picture?

### ISSUE THREAD

**Issue by lLoki2022** [xtekky/gpt4free#2122]
Hi, can it find objects in a picture?
![2](https://github.com/user-attachments/assets/5cd8e2e3-6ed9-4b0d-84cd-226ce5e3a25e)

**Comment by Anonymous6598** [comment]
Be more specific.

**Comment by Anonymous6598** [comment]
What's the issue?

**Comment by kizux1** [comment]
DO YOU MEAN U WANT IT REALIZE THE HEADPHONE OR ANYTHING ELSE IN PIC?

**Comment by lLoki2022** [comment]
> ВЫ ИМЕЕТЕ В ВИДУ, ЧТО ХОТИТЕ, ЧТОБЫ НА ФОТОГРАФИИ БЫЛИ НАУШНИКИ ИЛИ ЧТО-НИБУДЬ ДРУГОЕ?

well look at the example on the picture it says headphone then you have to find the headphone icon or it says helicopter then you have to find the helicopter icon

**Comment by Anonymous6598** [comment]
Do you need script?

**Comment by lLoki2022** [comment]
> Do you need script?

I guess I just haven't done it before Help how to solve captcha on auto

**Comment by Anonymous6598** [comment]
> > Do you need script?
> 
> I guess I just haven't done it before Help how to solve captcha on auto

So, what do you exactly need? Is it connected with script or something else?

**Comment by Anonymous6598** [comment]
Do you need script?

**Comment by lLoki2022** [comment]
> > > Do you need script?
> > 
> > 
> > I guess I just haven't done it before Help how to solve captcha on auto
> 
> So, what do you exactly need? Is it connected with script or something else?

is there any way to detect text and icons in a picture?

**Comment by Anonymous6598** [comment]
Your question is connected to models or captcha?

**Comment by lLoki2022** [comment]
> Your question is connected to models or captcha?

captcha

**Comment by Xanderplayz16** [comment]
Try using the audio captchas, usually they can be beaten easily.
