### ISSUE TITLE
I am creating my own program and I want only one provider to be used. At the same time, I sometimes get a response from him, but I don't know what kind of provider it is. How do I understand which provider processed this request?

### ISSUE THREAD

**Issue by Igor-chuk** [xtekky/gpt4free#2126]

**Comment by kqlio67** [comment]
To understand which provider processed your request, you can enable debugging in the G4F client by adding these two lines at the beginning of your code:

```python
import g4f.debug
g4f.debug.logging = True
```

After adding these lines, your code should look like this:

```python
import g4f.debug
g4f.debug.logging = True

from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Hello"}],
)
print(response.choices[0].message.content)
```

When you run the code with debugging enabled, it will show the type of model used and the provider in the console output.

Example output:
```
Using RetryProvider provider and gpt-3.5-turbo model
Using FreeGpt provider
你好！我很高兴能为你服务。请随时提出你的问题或需求，我会尽力回答和帮助你。
```

In this example, you can see that the `RetryProvider` is used with the `gpt-3.5-turbo` model, and the actual provider that processed the request is `FreeGpt`.

By enabling debugging, you can easily identify which provider is handling your requests.

**Comment by Igor-chuk** [comment]
Thank you very much!
