### ISSUE TITLE
Experience the unparalleled power of the truly free GPT-4o API, with an astounding daily limit of $200!

### ISSUE THREAD

**Issue by tiffanggang** [xtekky/gpt4free#2127]
Experience the unparalleled power of the truly free GPT-4o API, with an astounding daily limit of $200!

https://aiagent.marsyoo.com/chat/LjHsubj68LMvBOBr

**Comment by piotr25691** [comment]
good I guess but it censors a lot

Even when redacting the bad words by yourself
