### ISSUE TITLE
Please limit conversations for 20/200 a day.

### ISSUE THREAD

**Issue by NSbuilder** [xtekky/gpt4free#213]
This is a really cool project. But I think everybody knows what's gonna happen, it will blow up and everyone will use it until usage loads and takedown requests will make it slow and unusable. I will also cost 3d party companies a lot which is quite unfair ( and will likely make takedown requests worse). This situation will ruin the project for everyone. It would be advisable to try and set a limit and a cooldown after each message. Irritating but at least the project will survive and benefit most users.

Right now it is "too good to be true" and it will not last. Even microsoft set some usage limits, so of course a small project will have to..

BTW: This message is not written by chatgpt :)

( I'm serious, here is the message written by chatgpt ) :

>I appreciate your cool project. However, I’m concerned that it will become too popular and face problems with high demand and legal issues. This could make it slow and unusable for everyone. That would be unfortunate. Maybe you could consider implementing some usage limits and cooldowns to keep the project sustainable and beneficial for most users.

>I know this sounds frustrating, but it might be better than losing the project altogether. Even Microsoft has some usage restrictions, so I think it’s reasonable for a small project to have some too.

**Comment by pinokaille** [comment]
No.

**Comment by ess3sq** [comment]
Correct me if I'm wrong, but this project being open source means one could probably easily remove a cooldown clause. I don't think purposefully making use more difficult makes sense.

**Comment by NSbuilder** [comment]
> No.

Explain.

**Comment by NSbuilder** [comment]
> Correct me if I'm wrong, but this project being open source means one could probably easily remove a cooldown clause. I don't think purposefully making use more difficult makes sense
> 
> EDIT: In particular since improving on ChatGPT by OpenAI is the whole point

Of course everything you might do can be problematic, I just do not see a way it will continue working and  if left unrestricted ( which I would really like myself ). Just imagine the traffic and usage loads

**Comment by ess3sq** [comment]
> > Correct me if I'm wrong, but this project being open source means one could probably easily remove a cooldown clause. I don't think purposefully making use more difficult makes sense
> > EDIT: In particular since improving on ChatGPT by OpenAI is the whole point
> 
> Of course everything you might do can be problematic, I just do not see a the project will continue working and if left unrestricted ( which I would really like myself ). Just imagine the traffic and usage loads

You know you can run it locally for yourself, and not have to rely on public instances, right?

**Comment by NSbuilder** [comment]
> > > Correct me if I'm wrong, but this project being open source means one could probably easily remove a cooldown clause. I don't think purposefully making use more difficult makes sense
> > > EDIT: In particular since improving on ChatGPT by OpenAI is the whole point
> > 
> > 
> > Of course everything you might do can be problematic, I just do not see a the project will continue working and if left unrestricted ( which I would really like myself ). Just imagine the traffic and usage loads
> 
> You know you can run it locally for yourself, and not have to rely on public instances, right? If it really comes down to it.

At least limit the public instance  ( which most less technical users use ) which will most likely aggravate most of the takedown requests from companies and user load.

If I am missing something here I would be happy to get some feedbacks, I know this sounds frustrating, but it might be better than losing the project altogether ( @xtekky )

**Comment by ScripterSugar** [comment]
The project itself is just pirating misconfigured insecure endpoints which means this project is just abusing and taking advantages from other people's security vulnerabilities :) the concept is nothing different from stealing electricities from the power sockets open in public spaces. it's hilarious that you're yet asking them to have any ethical baseline.

**Comment by xtekky** [comment]
sleeps can get removed easily...,
