### ISSUE TITLE
No module named g4f.client

### ISSUE THREAD

**Issue by im-a-mango** [xtekky/gpt4free#2131]
I was trying to understand the syntax and how the module works, to do so I copied the first example given. And I installed all prequisites with pip install -U g4f[all]. I'm not sure why it isn't working but then again I am a bit stupid so hey ho.

`from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Hello"}],
)
print(response.choices[0].message.content)`

  File "path to the python file", line 1, in <module>
    from g4f.client import Client
ModuleNotFoundError: No module named 'g4f.client'

- python version 3.11
- UK (not sure why that matters)

Thanks

**Comment by Allamaris0** [comment]
Use `pip freeze` and check if g4f there is.
