### ISSUE TITLE
How to use the HTTP API

### ISSUE THREAD

**Issue by manuasir** [xtekky/gpt4free#2137]
Hi team,

First, kudos for the awesome work here. 

### Context:

I'm developing a dummy Node.JS testing project to generate images. I already run the docker service successfully via docker-compose, and now I'm able to interact with the service with the `curl` tool, but I'm not able to send actions to it. The thing is that I'm trying to get the API specfication, so I can integrate this with my Node.JS project (using any HTTP client as axios): endpoints, required payloads, and so.

Any help on this?

Thanks!

**Comment by manuasir** [comment]
This is _not_ a bug. The label was automatically added.

**Comment by shindi-renuo** [comment]
For me, none of the models work.

**Comment by websurfed** [comment]
Liaobots works about 50% of the time.
