### ISSUE TITLE
Cnote website is Down

### ISSUE THREAD

**Issue by on4r4p** [xtekky/gpt4free#2139]
Connection refused from f1.cnote.top .
g4f.Provider.Cnote.working should return False .
And section Cnote in Providers and Models from README.md shoud be update to Inactive or Unknown.
Same thing about section Duckduckgo in Providers and Models from README.md as g4f.Provider.DuckDuckGo does not exist.

**Comment by TheFirstNoob** [comment]
ReadMe not updated after 1-2 latest update.
Cnote is disabled.
DuckDuckGo used DDG file.

```g4f.Provider.DDG```

**Comment by on4r4p** [comment]
> ReadMe not updated after 1-2 latest update. Cnote is disabled. DuckDuckGo used DDG file.
> 
> `g4f.Provider.DDG`

Im using your readme as a way to retreive valid server .
If you are not planing to keep it up to date 
can you give me another solution to get a list of g4f.Provider that are working in the current version ?

**Comment by TheFirstNoob** [comment]
Its actual (on 0.3.2.4 update). Open ReadMe again. 
For my bot i use `from g4f.Provider import (RetryProvider, Chatgpt4o, FreeChatgpt, DDG, Liaobots, Blackbox, GeminiProChat, ChatGot, HuggingChat, HuggingFace, PerplexityLabs, Pi, Marsyoo, LiteIcoding, FreeNetfly, MagickPenAsk, MagickPenChat, TeachAnything, DeepInfra, DeepInfraImage)`

Other providers i didnt check. Open git for find needed models and see what provider you need use.
