### ISSUE TITLE
https://chat.chatbot.sex/chat stopped working!

### ISSUE THREAD

**Issue by markstark74** [xtekky/gpt4free#214]
Does not respond to requests and does not write anything! 
Please tell me what happened to the site?
![image](https://user-images.githubusercontent.com/131982682/234975919-26f09fee-6b78-495d-be58-511cef9dfca3.png)

**Comment by 9fo** [comment]
Please look at our Discord server for more information!
https://discord.gg/gpt4free

**Comment by markstark74** [comment]
@9fo thank you very much)

**Comment by 9fo** [comment]
No problem!
