### ISSUE TITLE
Gemini Pro became unusable

### ISSUE THREAD

**Issue by DuyguA** [xtekky/gpt4free#2140]
I was using Gemini Pro fine until a couple of hours. Now I'm getting this error:

```
    response = client.chat.completions.create(
  File "/usr/local/lib/python3.9/dist-packages/g4f/client/client.py", line 118, in create
    return response if stream else next(response)
  File "/usr/local/lib/python3.9/dist-packages/g4f/client/client.py", line 57, in iter_append_model_and_provider
    for chunk in response:
  File "/usr/local/lib/python3.9/dist-packages/g4f/client/client.py", line 29, in iter_response
    for idx, chunk in enumerate(response):
  File "/usr/local/lib/python3.9/dist-packages/g4f/providers/retry_provider.py", line 68, in create_completion
    raise_exceptions(exceptions)
  File "/usr/local/lib/python3.9/dist-packages/g4f/providers/retry_provider.py", line 324, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
LiteIcoding: RuntimeError: ClientResponseError 401: , url=https://lite.icoding.ink/api/v1/gpt/message, data={'model': 'gemini-1.5', 'chatId': '-1', 'messages': [{'role': 'user', 'content': 'Can you translate something for me?', 'time': '', 'attachments': []}], 'plugins': [], 'systemPrompt': '', 'temperature': 0.5}
```

Also Claude gives the same error:

```
LiteIcoding: RuntimeError: ClientResponseError 401: , url=https://lite.icoding.ink/api/v1/gpt/message, data={'model': 'claude-3', 'chatId': '-1', 'messages': [{'role': 'user', 'content': 'Can you translate something for me?', 'time': '', 'attachments': []}], 'plugins': [], 'systemPrompt': '', 'temperature': 0.5}
```

**Comment by DuyguA** [comment]
Still same issue, up!

**Comment by onlyGuo** [comment]
> 我一直在使用 Gemini Pro 直到几个小时。现在我收到这个错误：
> 
> ```
>     response = client.chat.completions.create(
>   File "/usr/local/lib/python3.9/dist-packages/g4f/client/client.py", line 118, in create
>     return response if stream else next(response)
>   File "/usr/local/lib/python3.9/dist-packages/g4f/client/client.py", line 57, in iter_append_model_and_provider
>     for chunk in response:
>   File "/usr/local/lib/python3.9/dist-packages/g4f/client/client.py", line 29, in iter_response
>     for idx, chunk in enumerate(response):
>   File "/usr/local/lib/python3.9/dist-packages/g4f/providers/retry_provider.py", line 68, in create_completion
>     raise_exceptions(exceptions)
>   File "/usr/local/lib/python3.9/dist-packages/g4f/providers/retry_provider.py", line 324, in raise_exceptions
>     raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
> g4f.errors.RetryProviderError: RetryProvider failed:
> LiteIcoding: RuntimeError: ClientResponseError 401: , url=https://lite.icoding.ink/api/v1/gpt/message, data={'model': 'gemini-1.5', 'chatId': '-1', 'messages': [{'role': 'user', 'content': 'Can you translate something for me?', 'time': '', 'attachments': []}], 'plugins': [], 'systemPrompt': '', 'temperature': 0.5}
> ```
> 
> Claude 也给出了同样的错误：
> 
> ```
> LiteIcoding: RuntimeError: ClientResponseError 401: , url=https://lite.icoding.ink/api/v1/gpt/message, data={'model': 'claude-3', 'chatId': '-1', 'messages': [{'role': 'user', 'content': 'Can you translate something for me?', 'time': '', 'attachments': []}], 'plugins': [], 'systemPrompt': '', 'temperature': 0.5}
> ```

Hi, I am the author of liteicoding. This issue is caused by your unauthorized use of my free API. Although we provide free GPT services, we do not offer a public API and do not allow malicious calls from third-party programs.
