### ISSUE TITLE
0 providers works for now (without and with vpn)

### ISSUE THREAD

**Issue by Looksh190** [xtekky/gpt4free#2146]
INFO:     192.168.31.5:46762 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:root:RetryProvider failed:
AI365VIP: ClientResponseError: 403, message='Forbidden', url='https://chat.ai365vip.com/api/chat'
LiteIcoding: RuntimeError: ClientResponseError 401: , url=https://lite.icoding.ink/api/v1/gpt/message, data={'model': 'gpt-4o', 'chatId': '-1', 'messages': [{'role': 'user', 'content': 'Hi', 'time': '', 'attachments': []}], 'plugins': [], 'systemPrompt': '', 'temperature': 0.5}
OpenaiChat: ResponseStatusError: Response 403: Bot are detected
MagickPenAsk: ClientResponseError: 403, message='Forbidden', url='https://api.magickpen.com/ask'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\api\__init__.py", line 167, in chat_completions
    return JSONResponse((await response).to_json())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\client\async_client.py", line 71, in iter_append_model_and_provider
    async for chunk in response:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\client\async_client.py", line 42, in iter_response
    async for chunk in response:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\providers\retry_provider.py", line 143, in create_async_generator
    raise_exceptions(exceptions)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\providers\retry_provider.py", line 324, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
AI365VIP: ClientResponseError: 403, message='Forbidden', url='https://chat.ai365vip.com/api/chat'
LiteIcoding: RuntimeError: ClientResponseError 401: , url=https://lite.icoding.ink/api/v1/gpt/message, data={'model': 'gpt-4o', 'chatId': '-1', 'messages': [{'role': 'user', 'content': 'Hi', 'time': '', 'attachments': []}], 'plugins': [], 'systemPrompt': '', 'temperature': 0.5}
OpenaiChat: ResponseStatusError: Response 403: Bot are detected
MagickPenAsk: ClientResponseError: 403, message='Forbidden', url='https://api.magickpen.com/ask'

**Comment by Bluryxz** [comment]
Hey! I have the same issue, how you solved it?
Got some ideas, but your help won't be superfluous

**Comment by Woukim** [comment]
yes how to solved it?

**Comment by onlyGuo** [comment]
Hi, I am the author of liteicoding. This issue is caused by your unauthorized use of my free API. Although we provide free GPT services, we do not offer a public API and do not allow malicious calls from third-party programs.

**Comment by Bluryxz** [comment]
> This issue is caused by your unauthorized use of my free API
No it's not lol
The issue is about multiple providers, not only yours

**Comment by Bluryxz** [comment]
> This issue is caused by your unauthorized use of my free API

No it's not lol
The issue is about multiple providers, not only yours

**Comment by onlyGuo** [comment]
Multiple suppliers returned a 401 or 403 status code, indicating that they have all blocked access to g4f.

**Comment by onlyGuo** [comment]
> > This issue is caused by your unauthorized use of my free API
> 
> No it's not lol The issue is about multiple providers, not only yours

Multiple suppliers returned a 401 or 403 status code, indicating that they have all blocked access to g4f.
