### ISSUE TITLE
when I setup openwebui  OpenAI API to http://localhost:1337/v1,  it not work.    {"detail":"Method Not Allowed"} when I visit http://localhost:1337/v1/chat/completions

### ISSUE THREAD

**Issue by jchgjchg** [xtekky/gpt4free#2149]
我想设置其他的工具来使用各种模型来工作，但open webui无法完成设置。

 {"detail":"Method Not Allowed"} when I visit http://localhost:1337/v1/chat/completions

这是什么原因呢？ 怎样能让这个 not allowed 变成 allowed 呢？

怎样才能在其他工具里用这些模型来正常工作呢？

**Comment by 3377** [comment]
mee too，so what?

**Comment by david116** [comment]
me 2. I just open the api server, then click, it shows : INFO:     127.0.0.1:49610 - "GET /v1/chat/completions HTTP/1.1" 405 Method Not Allowed , click chat/completions, or images/generate show this error too. INFO:     Uvicorn running on http://0.0.0.0:1337 (Press CTRL+C to quit)
INFO:     127.0.0.1:49610 - "GET /v1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:49610 - "GET /v1/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:49610 - "GET /v1/chat/completions HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:49879 - "GET /v1/images/generate HTTP/1.1" 405 Method Not Allowed

**Comment by hlohaus** [comment]
The /chat/completions endpoint is not accessible via a browser. Instead, you must send an API request to the specified URL. To begin, launch and open the GUI, which operates within the browser.
