### ISSUE TITLE
GPT 4o

### ISSUE THREAD

**Issue by BYxarek** [xtekky/gpt4free#2151]
When I use GPT-4o, supplier: auto, I get an error:

Python version: 3.12.4
![image](https://github.com/user-attachments/assets/ce051e2a-b773-4bb5-a59d-e5dbd965b7b5)

g4f - 0.3.2.3

**Comment by internetwarrior** [comment]
It happens everywhere, have to make a algorithm to bypass this things. I have no idea what is happening and how the repo works, but I probably would make some kind algorithm and function to over pass this
