### ISSUE TITLE
Unable to fetch the response, Please try again.

### ISSUE THREAD

**Issue by deneal123** [xtekky/gpt4free#216]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/52132611/234985210-d7944aaf-17a9-4e6d-9a8b-3a559887e613.png">

<img width="950" alt="image" src="https://user-images.githubusercontent.com/52132611/234985243-8286fff1-58b2-4b3e-92d1-d484181a6bbb.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/52132611/234985434-97424421-4532-4191-9ef7-1083cbefe5c3.png">

I did everything according to the instructions. Returns an error.

**Comment by deneal123** [comment]
VPN solve the problem

**Comment by yxmnjxzx** [comment]
Unable to fetch the response, Please try again. the same problem

**Comment by yxmnjxzx** [comment]
![image](https://user-images.githubusercontent.com/95153568/235028997-9c198ec9-4c33-485d-9ed8-90abeea98ba3.png)

**Comment by OrangeMaid** [comment]
Is the server in Hong Kong available?

**Comment by OrangeMaid** [comment]
> VPN solve the problem

Is the server in Hong Kong available?

**Comment by nikitalotts** [comment]
Connect Stockholm VPN, the problem still exists

**Comment by wuyuesong** [comment]
> VPN solve the problem

it works for me

**Comment by wuyuesong** [comment]
> > VPN solve the problem
> 
> Is the server in Hong Kong available?

I switch form HongKong to The United States,the problem solved

**Comment by aad233** [comment]
> > > VPN solve the problem
> > 
> > 
> > Is the server in Hong Kong available?
> 
> I switch from HongKong to The United States,the problem solved

what VPN are you using? i want it to work as well.

**Comment by wq245139833** [comment]
I switch from HongKong to The United States,the problem solved
