### ISSUE TITLE
issue with messaging feature potentially overloading API

### ISSUE THREAD

**Issue by Moslihbadr** [xtekky/gpt4free#217]
Dear website team,

I have identified an issue with the messaging feature on your website. As you are using several APIs including poe.com, phind.com, chat.openai.com, writesonic.com, sqlchat.ai, t3nsor.com, and you.com, I want to bring to your attention the potential risk of overloading these APIs.

Specifically, after a user enters a message and clicks the send button, the button remains clickable even if the message is still being processed by the API. This can result in multiple requests being sent simultaneously and may cause the API to become overloaded.

To avoid such a situation, I suggest adding a processing indicator that appears when the user clicks on the send button, and disabling the button until the API has responded. This will prevent users from accidentally sending multiple requests and ensure that the API is used efficiently.

I hope you will take this issue into consideration and implement a solution that prevents potential API overload.

Best regards,
Badr Moslih

<a href="https://ibb.co/W2svHXK"><img src="https://i.ibb.co/3CkmTbh/issue.png" alt="issue" border="0"></a>

**Comment by xtekky** [comment]
hi, the site was down for a moment all good now
