### ISSUE TITLE
YOU.com problem with Image generator & gpt-4 

### ISSUE THREAD

**Issue by noneherel** [xtekky/gpt4free#2195]
this is my code:

```
from g4f.client import Client as client_ai
from g4f.Provider import You
client = client_ai(provider=You, image_provider=You)
response = client.images.generate(
    model='dall-e',
    prompt='a white cat on the moon.',
)
image_url = response.data[0].url
print(image_url)
```

whenever i try to run this code, it appears a chrome pop up window to **'you.com' web**.
This is the photo for the pop up window:
Note: I tried to log in with my account but it doesn't work sill the page appears without close or anything else happen.
![image](https://github.com/user-attachments/assets/b46ca5cd-7e5f-47e4-8f65-f6e698858756)

any solution Please?

**Comment by noneherel** [comment]
> It happens because it uses nodriver. I find it annoying, so I use other provider.

what is the provider that you're using ?

**Comment by Allamaris0** [comment]
> > It happens because it uses nodriver. I find it annoying, so I use other provider.
> 
> what is the provider that you're using ?

I don't use any for creating images ^_^ AI images still aren't enough realistic for me. However when I want to slightly change an image with AI, I use fal with SDXL. It's not in g4f but they have 10$ free credits.

**Comment by Parthsadaria** [comment]
I use free integration of pollination ai check my repo NEXUAI where I have implemented all

**Comment by AppSolves** [comment]
I have the same 'problem' with `nodriver`, however, when I just login and let it run, nothing happens. The browser does not close, I get no response, etc. As soon as I close the window manually, I get a `ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection`. May somebody explain what the intention of `nodriver` is when nothing happens and the browser stays open?

**Comment by noneherel** [comment]
> I have the same 'problem' with `nodriver`, however, when I just login and let it run, nothing happens. The browser does not close, I get no response, etc. As soon as I close the window manually, I get a `ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection`. May somebody explain what the intention of `nodriver` is when nothing happens and the browser stays open?

that's my point, i want a solution as well. But there's no response from the owners.

**Comment by Allamaris0** [comment]
Have you tried that pull request https://github.com/xtekky/gpt4free/pull/2207#issue-2498689727 ? There are some fixes for you.com

**Comment by noneherel** [comment]
> Have you tried that pull request [#2207 (comment)](https://github.com/xtekky/gpt4free/pull/2207#issue-2498689727) ? There are some fixes for you.com

yes i've just tried it, but still the same problem unfortunately ):

**Comment by AppSolves** [comment]
up
