### ISSUE TITLE
Support for 32bit and Arm processors

### ISSUE THREAD

**Issue by Worrah** [xtekky/gpt4free#220]
by any chance, could you change the TSL client dependency for something else?
It won't work on arm processors for me, giving the 
` OSError: /home/wolh/.local/lib/python3.9/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory
`
as i know, the same problem was here: https://github.com/acheong08/ChatGPT/issues/35

**Comment by 9fo** [comment]
u can also change the tls client to requests, if u actually need it and it doesn't work on their system!

**Comment by Worrah** [comment]
> u can also change the tls client to requests, if u actually need it and it doesn't work on their system!

it wont work with requests for me, even with user agent in headers, idk, maybe need to add more sofisticated auth

**Comment by xtekky** [comment]
this is not a problem with this repo but rather modules used

**Comment by Worrah** [comment]
still not working even with curl_cffi :( 
cant build it on arm
