### ISSUE TITLE
An error occured: OpenaiChat: ClientConnectorError: Cannot connect to host chatgpt.com:443 ssl:default [None]

### ISSUE THREAD

**Issue by rcejzibjks38** [xtekky/gpt4free#2214]
**Bug description**
it already loaded .har file，but i got a error when using gui：An error occured: OpenaiChat: ClientConnectorError: Cannot connect to host chatgpt.com:443 ssl:default [None]

**Screenshots**
service already start:
![image](https://github.com/user-attachments/assets/6e4c8f52-daf6-4f94-9220-f8fbc4468bda)
gui error:
![image](https://github.com/user-attachments/assets/c4218716-aacf-47bf-bfd5-60f970b34472)
service error:
![image](https://github.com/user-attachments/assets/c05dff44-22ff-40e0-9a14-9637f47eda07)

**Environment**
- python 3.12
- China (But I can access ChatGPT normally through VPN)

**Comment by gamelist1990** [comment]
OpenAI is currently not working
