### ISSUE TITLE
Trying to make bing read images ?

### ISSUE THREAD

**Issue by Baldi89989** [xtekky/gpt4free#2216]
Hey, i am trying to make the bot read images but how i can make it read images, i saw with gemini pro vision that the ai could say what’s going on with the image, does bing do the same thing? When i put BingCreateImages provider with image url, it generate an image instead. 

Is bing support reading images or it’s only gemini pro vision?

**Comment by Baldi89989** [comment]
I tried with Bing provider and got an error saying "Bing doesn’t have ‘startWith’".

And blackbox is free to use?

**Comment by TheFirstNoob** [comment]
> And blackbox is free to use?
Completly free

**Comment by Baldi89989** [comment]
Oh cool (i hope it doesn’t open my browser when sending a request).

**Comment by Baldi89989** [comment]
Well uhm i keep getting error code 500 internal server error when attempting to read images

**Comment by phinwww** [comment]
^ Yeah same
