### ISSUE TITLE
Why is it writing an error

### ISSUE THREAD

**Issue by OlegEGV** [xtekky/gpt4free#2229]
claude-3-sonnet
Provider: Auto
An error occured: Liaobots: RetryProviderError: RetryProvider failed: Liaobots: RateLimitError: Response 402: Rate limit reached
Why is it writing an error ?

Screenshots
[https://ibb.co/Tc89kWg](url)

![Claude](https://github.com/user-attachments/assets/65fd1684-9267-4b6a-bc8f-f5c5d00351d5)

**Comment by TheFirstNoob** [comment]
Hey! Thats normal for liaobots provider. Sometimes need wait to refresh tokens rate count. Try to use other provider (Like DDG for this model) or other model.
