### ISSUE TITLE
Advertisement in answers 

### ISSUE THREAD

**Issue by nBalykin** [xtekky/gpt4free#2233]
I use llama-3.1-70b and sometimes I get this answer. But gpt-4o has this issue too:

`One message exceeds the 1000chars per message limit. Join our discord for more: [https://discord.com/invite/q55gsH8z5F](https://discord.com/invite/q55gsH8z5F)
`

I use g4f as telegram bot. My request code (python)

```python
response = g4f.ChatCompletion.create(
model = "llama-3.1-70b",
messages = text
) 
```
![Screenshot_2024-09-19-19-26-53-75_4495e6112227b794374c62341ece5829](https://github.com/user-attachments/assets/3da73c90-0e9b-45c7-955c-c7443ce9592f)

**Comment by TheFirstNoob** [comment]
Try to use other provider for this model like HuggingChat.
I think its provider problem.

```
response = g4f.ChatCompletion.create(
model = "llama-3.1-70b",
provider="HuggingChat",
messages = text
) 
```

**Comment by nBalykin** [comment]
Upd: I've removed airforce in section llama in models.py file. Now I don't have this message. O think this is Airforce provider advertisement.
