### ISSUE TITLE
Airforce Image Provider / ValueError: Invalid data URI image.

### ISSUE THREAD

**Issue by chekamarue** [xtekky/gpt4free#2237]
Can't generate image using Airforce Provider, Even tho the it is marked as working

```
from g4f.client import Client
from g4f.Provider import Airforce
import g4f.debug

g4f.debug.logging = True

client = Client(
    image_provider=Airforce
)

response = client.images.generate(
    model="",
    prompt="a white siamese cat",

)
image_url = response.data[0].url
print(image_url)
```
output
```
ValueError: Invalid data URI image.
```

**Same case for Gemini**

**Comment by kqlio67** [comment]
Hello @chekamarue, I noticed you're trying to generate an image URI, but you haven't specified a model in your code. 

**The Airforce provider supports several models, including:**
- `flux`
- `flux-realism`
- `flux-anime`
- `flux-3d`
- `flux-disney`
- `flux-pixel`
- `any-dark`

**Here's an example of how you can modify your code to work correctly:**
```python
from g4f.client import Client
from g4f.Provider import Airforce

client = Client()
response = client.images.generate(
  provider=Airforce,
  model="flux",
  prompt="a white siamese cat",
)
image_url = response.data[0].url
print(f"Generated image URL: {image_url}")
```

**When I ran this code, I got the following result:**
```
Generated image URL: https://api.airforce/v1/imagine2?prompt=a+white+siamese+cat&size=1:1&model=flux
```

**This demonstrates that the Airforce provider is working as expected. The key changes are:**
- Specifying a model (in this case, "flux")

I hope this helps resolve your issue.

**Comment by chekamarue** [comment]
Hi @kqlio67 Thank you for your help, that actually resolved the issue.

Would you please tell me if there a page or doc listing all models for each provider, or is there a parameter to dump Model lists of each provider?

That would be such a great help

**Comment by kqlio67** [comment]
@chekamarue! I'm glad I could help resolve the issue.

Regarding your question about documentation for models and providers - there isn't a separate page with a complete list at the moment. But I want to share some good news - I'm currently working on creating such documentation!

**For now, you can see the available models for text generation here:**
https://github.com/xtekky/gpt4free/blob/main/g4f/models.py#L623

**And models for image generation here:**
https://github.com/xtekky/gpt4free/blob/main/g4f/models.py#L772

I'm actively working on creating a comprehensive list of providers with information about which models they support. I hope to have this ready by the next project update and submit a pull request with the new documentation. This should help users easily find the information they need.

Currently, most models can be used without specifying a particular provider. But if you need a specific provider, you'll have to manually check which models it supports.

**Comment by chekamarue** [comment]
@kqlio67 Looking forward to see the next update, hopeful you will make it .

I want to thank you guys for the all the work you are providing to the community, much appreciated 💯

**Comment by chekamarue** [comment]
solved
