### ISSUE TITLE
One message exceeds the 1000chars per message limit. Join our discord for more

### ISSUE THREAD

**Issue by Smerch1** [xtekky/gpt4free#2244]
When I use any model after several messages no response is generated: `One message exceeds the 1000chars per message limit. Join our discord for more`

![image](https://github.com/user-attachments/assets/bccdef99-2164-4ea4-9863-62fbd31ae4e6)

I've already seen a similar question, but it wasn't resolved.

**Comment by TheFirstNoob** [comment]
If you have already seen a similar topic before, then deleting Airforce did not solve your problem? The list of providers for the models is large. Just use another provider.

**Comment by Smerch1** [comment]
@TheFirstNoob thanks, tried changing the provider to ReplicateHome, everything works. 

Code:
```py
stream = gpt_client.chat.completions.create(
    model="llama-3-70b",
    provider='ReplicateHome',
    messages= ...
)
```
