### ISSUE TITLE
OpenAPI-compatible APIs not compatible with Vision

### ISSUE THREAD

**Issue by c7e715d1b04b17683718fb1e8944cc28** [xtekky/gpt4free#2249]
**Known Issues**
- Self-hosting OpenAI-compatible API gives 422 error when sending Vision request body

**Bug description**
Sending Messages with Vision to OpenAI Compatible Self-Hosted API Causes 422 Error Code
https://platform.openai.com/docs/guides/vision

ex.
1. Deploy API
2. Set .har file
3. Using OpenaiChat Provider to Send Requests Including Vision

**Screenshots**
![image](https://github.com/user-attachments/assets/98a3d9a2-c4fb-4cc5-85ee-6749ddf34e2d)

**Environment**
- Docker

**Comment by The2Alert** [comment]
Please add support..
