### ISSUE TITLE
which gpt version is gpt4free GUI using

### ISSUE THREAD

**Issue by fastfading** [xtekky/gpt4free#225]
which gpt version is gpt4free GUI using
which site api is gpt4free GUI using
how to verify that

**Comment by LukeSaward1** [comment]
You can choose between GPT-3.5-turbo and GPT-4.

**Comment by yxmnjxzx** [comment]
> You can choose between GPT-3.5-turbo and GPT-4.

how can i choose the model？

**Comment by LukeSaward1** [comment]
> > You can choose between GPT-3.5-turbo and GPT-4.
> 
> how can i choose the model？

![image](https://user-images.githubusercontent.com/55454721/235265736-b4d45138-88a2-4ed3-b202-c95b0422e2e5.png)

**Comment by yxmnjxzx** [comment]
> > > You can choose between GPT-3.5-turbo and GPT-4.
> > 
> > 
> > how can i choose the model？
> 
> ![image](https://user-images.githubusercontent.com/55454721/235265736-b4d45138-88a2-4ed3-b202-c95b0422e2e5.png)
This is function in”https://chat.chatbot.sex/chat/ “. I know it.  I'm referring to is how to configure the model or API in "GPT4free GUI" .

**Comment by fastfading** [comment]
the answer is wrong 

This is function in”https://chat.chatbot.sex/chat/ “. I know it. I'm referring to is how to configure the model or API in "GPT4free GUI" .

**Comment by 0fan** [comment]
+1
