### ISSUE TITLE
remove snova as provider as they changed to api key model.

### ISSUE THREAD

**Issue by DarkReaperBoy** [xtekky/gpt4free#2253]
maybe instead implement openai compatible api for it so we can import api keys

here is the error:
```
An error occured: Snova: ClientResponseError: 400, message='Bad Request', url='https://fast.snova.ai/api/completion'
```

**Comment by TheFirstNoob** [comment]
Hey, Snova already removed in next update: https://github.com/xtekky/gpt4free/pull/2246
