### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by ProgramingPro2** [xtekky/gpt4free#2261]
The discord link for your discord community server is no longer working and has expired, pls fix

**Comment by UX0l0l** [comment]
bump

**Comment by Intiiii** [comment]
pls fix the link, I'm trying to get some code working and a discord where I can ask questions would really help

**Comment by Intiiii** [comment]
pls dont bump but fix =D (and dont forget to set te settings so that the link will never expire)

**Comment by hlohaus** [comment]
Hey, I just added a new Discord link.
