### ISSUE TITLE
failed to do request

### ISSUE THREAD

**Issue by nongfu9woo** [xtekky/gpt4free#227]
encountered the following error : dial tcp 21.14.71.4:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Please make sure you are using a valid cloudflare clearance token and user agent.
How can I fix the error?

**Comment by Jeremy-J-J** [comment]
I meet the same problem, have you solved it yet

**Comment by misa527528** [comment]
same problem

**Comment by nongfu9woo** [comment]
@Jeremy-J-J @misa527528 According to the plan in #230, adding a proxy can solve this issue. Please note to change the port to your own.
