### ISSUE TITLE
Can't use module logging, when I use module g4f

### ISSUE THREAD

**Issue by Shwumper** [xtekky/gpt4free#2274]
When I import module logging, I can't use it. It doesn't work. When I remove module g4f, I can use module logging.
![image](https://github.com/user-attachments/assets/e166e01b-672c-416a-8777-dc62e46ee7f1)
![image](https://github.com/user-attachments/assets/dca84b1d-ce97-43af-af5d-d7be676e83c3)
![image](https://github.com/user-attachments/assets/fc446013-6133-48ff-b760-0d5a682e4c05)

**Comment by foxfire52** [comment]
You should post the error message and your full python imports.

**Comment by Shwumper** [comment]
Hello, I don't have any error messages, here are full imports:
![image](https://github.com/user-attachments/assets/32920fbf-c5e3-4792-a700-b2d0dbebdcb1)

**Comment by foxfire52** [comment]
if you use basicConfig() try setting a higher logging level like **level=logging.DEBUG**  and check for errors. I will try replicating this later.

**Comment by Shwumper** [comment]
Thank you

**Comment by foxfire52** [comment]
The problem is basicConfig(). As workaround you can add parameter **force=True** to basicConfig() to fix it. I will open another issue.
