### ISSUE TITLE
g4f v-0.3.3.0 - The API doesn't work since the update! 

### ISSUE THREAD

**Issue by comeback01** [xtekky/gpt4free#2276]
The API doesn't work since the update! While port 8080 works, port 1317 doesn't.

Here are the error messages:

`docker compose up
WARN[0000] /home/gpt4free/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 1/0
 ✔ Container gpt4free-gpt4free-1  Created                                                                                                                                                                                               0.0s
Attaching to gpt4free-1
gpt4free-1  | 2024-10-15 11:35:06,021 INFO Included extra file "/etc/supervisor/conf.d/gui.conf" during parsing
gpt4free-1  | 2024-10-15 11:35:06,021 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
gpt4free-1  | 2024-10-15 11:35:06,054 INFO RPC interface 'supervisor' initialized
gpt4free-1  | 2024-10-15 11:35:06,055 CRIT Server 'unix_http_server' running without any HTTP authentication checking
gpt4free-1  | 2024-10-15 11:35:06,055 INFO supervisord started with pid 9
gpt4free-1  | 2024-10-15 11:35:07,059 INFO spawned: 'xvfb' with pid 10
gpt4free-1  | 2024-10-15 11:35:07,064 INFO spawned: 'vnc' with pid 11
gpt4free-1  | 2024-10-15 11:35:07,069 INFO spawned: 'novnc' with pid 12
gpt4free-1  | 2024-10-15 11:35:07,071 INFO spawned: 'g4f-api' with pid 13
gpt4free-1  | 2024-10-15 11:35:07,074 INFO spawned: 'g4f-gui' with pid 14
gpt4free-1  | 2024-10-15 11:35:08,122 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gpt4free-1  | 2024-10-15 11:35:08,122 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gpt4free-1  | 2024-10-15 11:35:08,122 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gpt4free-1  | 2024-10-15 11:35:08,122 INFO success: g4f-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gpt4free-1  | 2024-10-15 11:35:08,122 INFO success: g4f-gui entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gpt4free-1  | Running on port 8080
gpt4free-1  |  * Serving Flask app 'g4f.gui.server.app'
gpt4free-1  |  * Debug mode: off
gpt4free-1  | INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
gpt4free-1  |  * Running on all addresses (0.0.0.0)
gpt4free-1  |  * Running on http://127.0.0.1:8080
gpt4free-1  |  * Running on http://172.21.0.2:8080
gpt4free-1  | INFO:werkzeug:Press CTRL+C to quit
gpt4free-1  | Traceback (most recent call last):
gpt4free-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
gpt4free-1  |   File "<frozen runpy>", line 88, in _run_code
gpt4free-1  |   File "/app/g4f/cli.py", line 56, in <module>
gpt4free-1  |     main()
gpt4free-1  |   File "/app/g4f/cli.py", line 28, in main
gpt4free-1  |     run_api_args(args)
gpt4free-1  |   File "/app/g4f/cli.py", line 36, in run_api_args
gpt4free-1  |     from g4f.api import AppConfig, run_api
gpt4free-1  |   File "/app/g4f/api/__init__.py", line 20, in <module>
gpt4free-1  |     from g4f.client import AsyncClient
gpt4free-1  | ImportError: cannot import name 'AsyncClient' from 'g4f.client' (/app/g4f/client/__init__.py)
gpt4free-1  | 2024-10-15 11:35:09,341 WARN exited: g4f-api (exit status 1; not expected)
gpt4free-1  | 2024-10-15 11:35:10,345 INFO spawned: 'g4f-api' with pid 104
gpt4free-1  | 2024-10-15 11:35:11,347 INFO success: g4f-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gpt4free-1  | Traceback (most recent call last):
gpt4free-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
gpt4free-1  |   File "<frozen runpy>", line 88, in _run_code
gpt4free-1  |   File "/app/g4f/cli.py", line 56, in <module>
gpt4free-1  |     main()
gpt4free-1  |   File "/app/g4f/cli.py", line 28, in main
gpt4free-1  |     run_api_args(args)
gpt4free-1  |   File "/app/g4f/cli.py", line 36, in run_api_args
gpt4free-1  |     from g4f.api import AppConfig, run_api
gpt4free-1  |   File "/app/g4f/api/__init__.py", line 20, in <module>
gpt4free-1  |     from g4f.client import AsyncClient
gpt4free-1  | ImportError: cannot import name 'AsyncClient' from 'g4f.client' (/app/g4f/client/__init__.py)
gpt4free-1  | 2024-10-15 11:35:12,246 WARN exited: g4f-api (exit status 1; not expected)
gpt4free-1  | 2024-10-15 11:35:13,252 INFO spawned: 'g4f-api' with pid 105
gpt4free-1  | 2024-10-15 11:35:14,255 INFO success: g4f-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gpt4free-1  | Traceback (most recent call last):
gpt4free-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
gpt4free-1  |   File "<frozen runpy>", line 88, in _run_code
gpt4free-1  |   File "/app/g4f/cli.py", line 56, in <module>
gpt4free-1  |     main()
gpt4free-1  |   File "/app/g4f/cli.py", line 28, in main
gpt4free-1  |     run_api_args(args)
gpt4free-1  |   File "/app/g4f/cli.py", line 36, in run_api_args
gpt4free-1  |     from g4f.api import AppConfig, run_api
gpt4free-1  |   File "/app/g4f/api/__init__.py", line 20, in <module>
gpt4free-1  |     from g4f.client import AsyncClient
gpt4free-1  | ImportError: cannot import name 'AsyncClient' from 'g4f.client' (/app/g4f/client/__init__.py)
gpt4free-1  | 2024-10-15 11:35:15,209 WARN exited: g4f-api (exit status 1; not expected)
gpt4free-1  | 2024-10-15 11:35:16,212 INFO spawned: 'g4f-api' with pid 106
gpt4free-1  | 2024-10-15 11:35:17,214 INFO success: g4f-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gpt4free-1  | Traceback (most recent call last):
gpt4free-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
gpt4free-1  |   File "<frozen runpy>", line 88, in _run_code
gpt4free-1  |   File "/app/g4f/cli.py", line 56, in <module>
gpt4free-1  |     main()
gpt4free-1  |   File "/app/g4f/cli.py", line 28, in main
gpt4free-1  |     run_api_args(args)
gpt4free-1  |   File "/app/g4f/cli.py", line 36, in run_api_args
gpt4free-1  |     from g4f.api import AppConfig, run_api
gpt4free-1  |   File "/app/g4f/api/__init__.py", line 20, in <module>
gpt4free-1  |     from g4f.client import AsyncClient
gpt4free-1  | ImportError: cannot import name 'AsyncClient' from 'g4f.client' (/app/g4f/client/__init__.py)
gpt4free-1  | 2024-10-15 11:35:18,251 WARN exited: g4f-api (exit status 1; not expected)
^CGracefully stopping... (press Ctrl+C again to force)
`

**Comment by Auximen** [comment]
Same problem, Docker / Synology Container Manager, ver. 0.3.3.0. Version 0.3.2.9 works.

**Comment by yimuc** [comment]
> Same problem, Docker / Synology Container Manager, ver. 0.3.3.0. Version 0.3.2.9 works.

Me too.
