### ISSUE TITLE
Airforce only supports flux, not dalle-3

### ISSUE THREAD

**Issue by henxforever** [xtekky/gpt4free#2286]
I was watching repository and I found the dalle-3 api "api.airforce" that’s GET request and no authorization, but I found it when I’m trying this api, when set model param to dalle-3 or unsupported something, that’s returns the image generated by flux.

check these urls:
https://api.airforce/imagine2?model=dall-e-3&prompt=car&size=1:1&seed=6293
https://api.airforce/imagine2?model=flux&prompt=car&size=1:1&seed=6293
https://api.airforce/imagine2?model=flux-3d&prompt=car&size=1:1&seed=6293
https://api.airforce/imagine2?model=qwertyu7292728&prompt=car&size=1:1&seed=6293

**Comment by henxforever** [comment]
Or just I typo model?

**Comment by TheFirstNoob** [comment]
`dalle-3` model name. G4f automatic use alias for models cause all site have different name like adding model.

Works on me
```
        app_commands.Choice(name="Stable Diffusion XL", value="sdxl"),
        app_commands.Choice(name="Stable Diffusion v3", value="sd-3"),
        app_commands.Choice(name="Playground v2.5", value="playground-v2.5"),
        app_commands.Choice(name="FLUX", value="flux"),
        app_commands.Choice(name="FLUX 4o", value="flux-4o"),
        app_commands.Choice(name="FLUX Schnell", value="flux-schnell"),
        app_commands.Choice(name="FLUX Realism", value="flux-realism"),
        app_commands.Choice(name="FLUX Anime", value="flux-anime"),
        app_commands.Choice(name="FLUX 3D", value="flux-3d"),
        app_commands.Choice(name="FLUX Disney", value="flux-disney"),
        app_commands.Choice(name="FLUX Pixel", value="flux-pixel"),
        app_commands.Choice(name="DALL-E v3", value="dalle-3"),
        app_commands.Choice(name="DALL-E v2", value="dalle-2"),
        app_commands.Choice(name="EMI Anime", value="emi"),
        app_commands.Choice(name="Any Dark", value="any-dark"),
```
