### ISSUE TITLE
Text is not copied when the Copy button is pressed

### ISSUE THREAD

**Issue by Vasabiko** [xtekky/gpt4free#2287]
Steps to playback
Send a request to the chatbot to output the response in block code, click on the Copy copied copied and try to paste the text into any text field (e.g. notepad).

**Comment by foxfire52** [comment]
Your OS and Browser version?

**Comment by Vasabiko** [comment]
> Ваша версия ОС и браузера?

Win 11 23H3  22635.4300,  Tried it in 3 different browsers, Chrom, Vivaldi, Edge. My friend also has the same problem.

**Comment by foxfire52** [comment]
I can't replicate the bug.

Try these steps:
1. Clear Browser cache and history.
2. Open Developer Tools >> "Console" [Instructions](https://www.youtube.com/watch?v=iXl3jUrZICI)
3. Go to http://localhost:8080
4. Open chat and click Copy button.
5. Inside Console window, right-click on text >> Save As >> Save.
6. Attach saved .log file here

**Comment by foxfire52** [comment]
> Tried it in 3 different browsers, Chrom, Vivaldi, Edge.
Try Firefox

**Comment by Vasabiko** [comment]
> Я не могу воспроизвести ошибку.
> 
> Попробуйте выполнить следующие действия (Google Chrome):
> 
> 1. Очистить кэш браузера и историю.
> 2. Открыть инструменты разработчика >> "Консоль" ([Инструкция](https://www.youtube.com/watch?v=iXl3jUrZICI))
> 3. Перейти к http://localhost:8080
> 4. Откройте чат и нажмите кнопку Копировать.
> 5. Внутри окна консоли щелкните правой кнопкой мыши текст >> Сохранить как >> Сохранить.
> 6. Прикрепите сохраненный файл.log сюда

[Log.log](https://github.com/user-attachments/files/17495993/Log.log)

**Comment by Vasabiko** [comment]
> I can't replicate the bug.
> 
> Try these steps (Google Chrome):
> 
> 1. Clear Browser cache and history.
> 2. Open Developer Tools >> "Console" ([Instructions](https://www.youtube.com/watch?v=iXl3jUrZICI))
> 3. Go to http://localhost:8080
> 4. Open chat and click Copy button.
> 5. Inside Console window, right-click on text >> Save As >> Save.
> 6. Attach saved .log file here
[Log.log](https://github.com/user-attachments/files/17496025/Log.log)

**Comment by Vasabiko** [comment]
> > Tried it in 3 different browsers, Chrom, Vivaldi, Edge.
> 
> Try Firefox

unchanged

**Comment by foxfire52** [comment]
I suspect the bug is **line 97** the writeText call is not awaited and can throw exceptions.
https://github.com/xtekky/gpt4free/blob/04386f7b4b70db6b0fbc5747f530e58c2638d4b6/g4f/gui/client/static/js/chat.v1.js#L90-L99

I pushed a fix and added a fallback function using  `document.exec("copy")`

This is my repository:
https://github.com/foxfire52/gpt4free/tree/copy-patch
[repository zip](https://github.com/foxfire52/gpt4free/archive/refs/heads/copy-patch.zip) 

Would you please download, run it and repeat steps 1-6?

**Comment by Vasabiko** [comment]
> Would you please download, run it and repeat steps 1-6?

[Log1.log](https://github.com/user-attachments/files/17509893/Log1.log)

**Comment by foxfire52** [comment]
Are you sure you ran my repository?

Do this
- Install **Docker Desktop**
- Extract zip file
- Open **Command Line**
- change directory to extracted folder **path** `cd "C://path..."`
- run `docker compose up --build`

When server is running follow step 1-6

**Comment by Vasabiko** [comment]
> Are you sure you ran my repository?
> 
> Do this
> 
> * Install **Docker Desktop** [Docker Instruction](https://docs.docker.com/desktop/install/windows-install/)
> * Extract zip file
> * Open **Command Line**
> * change directory to extracted folder **path** `cd "C://path..."`
> * run `docker compose up --build`
> 
> If you need help with Docker, you can ask.
> 
> When server is running follow step 1-6

No, not in the docker, in Windows itself via the command line

**Comment by foxfire52** [comment]
> No, not in the docker, in Windows itself via the command line

Are you using python?

**Comment by Vasabiko** [comment]
> > No, not in the docker, in Windows itself via the command line
> 
> Are you using python?

yes, Python 3.12.5

**Comment by foxfire52** [comment]
These instructions?
https://github.com/xtekky/gpt4free/blob/main/docs/git.md#installation-steps

**Comment by Vasabiko** [comment]
> Do you use these instructions to run the server? https://github.com/xtekky/gpt4free/blob/main/docs/git.md#installation-steps
> 
> in command line, inside extracted _gpt4free/_ folder run `git switch copy-patch`

almost, downloaded the archive and ran the .bat file. 
```
@echo off
chcp 65001
REM Переход в нужную директорию
cd /d d:\gpt4free

REM Проверка наличия Python
where python >nul 2>nul
if errorlevel 1 (
    echo Python не найден. Пожалуйста, установите Python и добавьте его в PATH.
    exit /b
)

REM Проверка на существование виртуального окружения
if exist venv (
    echo Виртуальное окружение уже существует. Активируем его...
) else (
    echo Создаем новое виртуальное окружение...
    python.exe -m venv venv
)

REM Активация виртуального окружения
call venv\Scripts\activate

REM Установка зависимостей
pip install -r requirements.txt
pip install -U g4f[webdriver]

REM Запуск скрипта
python -m g4f.gui.run

REM Деактивация виртуального окружения
deactivate

pause
```

**Comment by Mr4Mike4** [comment]
What button are their talking about?

Example promt:
`Write image generation promts for Midjorney about gemstones, different minerals, close-up, in English and each promt in its own block code`

This button doesn't work:
![2024-10-24 213728](https://github.com/user-attachments/assets/5e10a39b-6804-48c9-b81d-d075cf0aff92)

**Comment by Vasabiko** [comment]
> What button are their talking about?
> 
> Promt example: `Write image generation promts for Midjorney about gemstones, different minerals, close-up, in English and each promt in its own block code`
> 
> This button doesn't work: ![2024-10-24 213728](https://private-user-images.githubusercontent.com/6643879/379899076-5e10a39b-6804-48c9-b81d-d075cf0aff92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3OTYyMDEsIm5iZiI6MTcyOTc5NTkwMSwicGF0aCI6Ii82NjQzODc5LzM3OTg5OTA3Ni01ZTEwYTM5Yi02ODA0LTQ4YzktYjgxZC1kMDc1Y2YwYWZmOTIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTg1MTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ3OTk1N2IzOTgxNDczOTJlODVlNDhiYmIwNGQxNGE4NjQzZThjNjI1ZTg4Yjk2MTU3ZTFiZmFlOGJkYjI3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.c93K8qDnCJTuj50Wj0Xkar0cyiWVDkgdSP4Z0eY-W9o)

Yeah, that's exactly what I meant.

**Comment by Mr4Mike4** [comment]
1. Enter chrome://flags in your browser's address bar.
2. Search for Insecure origins treated as secure.
3. Enable the setting by clicking on the button to the right.
4. Type the origins that you want to enable the setting for, e.g.
`http://localhost:3000` or `http://example.com`.
![image](https://github.com/user-attachments/assets/ee6518f3-94cf-486c-bb1e-a498e7087121)

- Multiple origins can be specified as a comma-separated list.

```
http://localhost:3000,http://example.com
```

- Origins must have their protocol specified (`http://` or `https://`).

5. **NOTE:** After you enable the setting, you have to relaunch Chrome for the changes to take effect.

[Сopied from the site](https://bobbyhadz.com/blog/navigator-clipboard-is-undefined-in-javascript#enable-the-insecure-origins-treated-as-secure-setting)

It solves the copying problem

**Comment by Vasabiko** [comment]
> 
> It solves the copying problem

Yes, that's it, thank you very much

**Comment by foxfire52** [comment]
> What button are their talking about?
> 
> Promt example: `Write image generation promts for Midjorney about gemstones, different minerals, close-up, in English and each promt in its own block code`
> 
> This button doesn't work: ![2024-10-24 213728](https://private-user-images.githubusercontent.com/6643879/379899076-5e10a39b-6804-48c9-b81d-d075cf0aff92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4ODI1NTksIm5iZiI6MTcyOTg4MjI1OSwicGF0aCI6Ii82NjQzODc5LzM3OTg5OTA3Ni01ZTEwYTM5Yi02ODA0LTQ4YzktYjgxZC1kMDc1Y2YwYWZmOTIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMTg1MDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM2YjJlYjk2Y2RlOTlhODJiZDdjYTYzZTY4OGY3OTNlZGIwY2NmMGRmMjA5NzVkYjkzOGVkNzdhMTFkMTk2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PoMKyBNhoeoJAzyHMoXjOQ74s2xGM6uGIjZWXXF7uOU)

I forgot to fix this one. Thank you for reporting It.




> 1. Enter `chrome://flags` in your browser's address bar.
> 2. Search for `Insecure origins treated as secure`.
> 3. Enable the setting by clicking on the button to the right.
> 4. Type the origins that you want to enable the setting for, e.g.
> ...
> 5. **NOTE:** After you enable the setting, you have to relaunch Chrome for the changes to take effect.
> 
> [Сopied from the site](https://bobbyhadz.com/blog/navigator-clipboard-is-undefined-in-javascript#enable-the-insecure-origins-treated-as-secure-setting)
> 
> It solves the copying problem

This confirms the cause of this issue. Clipboard.writeText() fails if context is not Secure.

**Comment by foxfire52** [comment]
Tomorrow I will send a Pull Request to add fallback copy function. 
If you use **Docker** you can already download my repository
https://github.com/foxfire52/gpt4free/tree/copy-patch

Code is part of **highlight.js** copy plugin, I may open a PR there top.

**Comment by foxfire52** [comment]
@Vasabiko Have you tested latest version?

**Comment by Vasabiko** [comment]
> @Vasabiko Have you tested latest version?

Yeah, it's fine, it's working. Thank you
