### ISSUE TITLE
DuckDuckGO Ai chat

### ISSUE THREAD

**Issue by chebupelka10** [xtekky/gpt4free#2303]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't find a reliable and free AI chat service that supports chat history. Many existing options are either paid or lack essential features.

**Describe the solution you'd like**
I would like to see DuckDuckGo AI chat added to the gpt4free library. This service provides a variety of free neural networks and includes support for chat history, which would enhance the user experience significantly.

**Describe alternatives you've considered**
I have considered other free AI chat services, but they often do not offer chat history or have limitations on usage. DuckDuckGo AI chat stands out because it combines both features effectively.

**Additional context**
DuckDuckGo AI chat is known for its privacy-focused approach and user-friendly interface, making it a great fit for the gpt4free library. Adding this service would provide users with more options and improve overall satisfaction.

**Comment by TheFirstNoob** [comment]
@chebupelka10 Hi, DDG already added and used in G4F libs with all models
https://github.com/xtekky/gpt4free/blob/main/g4f/Provider/DDG.py

**Comment by chebupelka10** [comment]
This implementation has a lot of bugs and a very long generation. Either I have problems or, I don't know.

**Comment by TheFirstNoob** [comment]
Fully working and fast.
If you have problems please provide information whats is not working/bug or long time generation

(Time in seconds)
```
{
        "model": "gpt-4o-mini",
        "provider": "DDG",
        "response": "Hello! How can I assist you today?",
        "response_time": 1.9907548427581787
    },
    {
        "model": "claude-3-haiku",
        "provider": "DDG",
        "response": "Hello! I'm happy to assist you. How can I help you today?",
        "response_time": 3.3645637035369873
    },
    {
        "model": "llama-3.1-70b",
        "provider": "DDG",
        "response": "Hello. How can I assist you today?",
        "response_time": 4.5606606006622314
    },
    {
        "model": "mixtral-8x7b",
        "provider": "DDG",
        "response": " Hello! How can I assist you today? I'm here to provide answers to your questions and help with any programming or general knowledge topics you're interested in. Please note that all communications are completely anonymous and none of your metadata or personal information is stored or used for any purpose. Let me know how I can help!",
        "response_time": 2.7606701850891113
    },
```
