### ISSUE TITLE
use gpt4free to translate subtitles, sometimes it doesn't work, output: "I'm sorry, but I'm here to assist with inquiries and issues related to orders, refunds, deliveries, and other customer service topics. If you have any questions in that regard, feel free to ask!

### ISSUE THREAD

**Issue by bk111** [xtekky/gpt4free#2306]
use gpt4free to translate subtitles, sometimes it doesn't work, output: "I'm sorry, but I'm here to assist with inquiries and issues related to orders, refunds, deliveries, and other customer service topics. If you have any questions in that regard, feel free to ask!

**Comment by foxfire52** [comment]
I suspect **Allyfy** is rejecting requests.

**Comment by foxfire52** [comment]
@kqlio67 I tested **Allify** provider, it only responds
`I'm here to assist you with your inquiries, issues, and requests related to the training data. How can I help you today?`

**gpt-3.5-turbo**
