### ISSUE TITLE
from g4f.client import AsyncClient

### ISSUE THREAD

**Issue by AndreySupr** [xtekky/gpt4free#2308]
I have version 0.3.2.9 and everything works.
updated to the latest, error
from g4f.client import AsyncClient
ImportError: Unable to import name 'AsyncClient' from 'g4f.client' (/usr/local/lib/python3>

**Comment by kqlio67** [comment]
@AndreySupr Hi! The old version using `g4f.client import AsyncClient` is no longer supported. The library has been simplified, and now both async and sync methods are handled through a unified interface using `from g4f.client import Client`.

You can check the updated documentation here:
- Async usage: https://github.com/xtekky/gpt4free/blob/main/docs/async_client.md
- Sync usage: https://github.com/xtekky/gpt4free/blob/main/docs/client.md

This change was made to streamline the API and make it more maintainable.

**Comment by xtekky** [comment]
This was fixed in my latest commit:

https://github.com/xtekky/gpt4free/commit/b1d5af85aec21dc1d0813ed8bf99f3081bdceb5e

while waiting for this to be pushed to pypi, use a clone of the latest version.

**Comment by AndreySupr** [comment]
> Это было исправлено в моем последнем коммите:
> 
> [б1д5аф8](https://github.com/xtekky/gpt4free/commit/b1d5af85aec21dc1d0813ed8bf99f3081bdceb5e)
> 
> пока вы ждете, пока это будет отправлено на pypi, используйте клон последней версии.

ok. thx
