### ISSUE TITLE
How to solve 

### ISSUE THREAD

**Issue by Tanjirotg** [xtekky/gpt4free#2315]
File "/app/.heroku/python/lib/python3.10/site-packages/g4f/client/client.py", line 449, in async_generate
    raise ValueError(f"Unknown model: {model}")
ValueError: Unknown model: dall-e-3

This error showing in this code

from g4f.client import Client

client = Client()
response = client.images.generate(
    model="dall-e-3",
    prompt="a white siamese cat",
    # Add any other necessary parameters
)

image_url = response.data[0].url
print(f"Generated image URL: {image_url}")

I see in docs that model

Iam using latest version

**Comment by TheFirstNoob** [comment]
@Tanjirotg Hi, Dalle-3 now not avalable. Docs has been updated to next merge pull.
Use other model like `Flux`, `Playground`, SD models. (Dont use nexra provider for image cause is temporarily not working).
