### ISSUE TITLE
error: Provider <class 'g4f.Provider.nexra.NexraDallE2.NexraDallE2'> does not support image generation

### ISSUE THREAD

**Issue by newsister** [xtekky/gpt4free#2318]
When I try to create an image, I keep getting the following error.. Is it impossible to create an image? I tried to use the dalle-2 model.

error : Provider <class 'g4f.Provider.nexra.NexraDallE2.NexraDallE2'> does not support image generation

**Comment by TheFirstNoob** [comment]
@newsister Hi, at the moment Nexra temporarily not working. We know about this problem.

**Comment by newsister** [comment]
Oh, I'm sorry 😥 I didn't check the error in advance
