### ISSUE TITLE
Blackbox.AI pops up

### ISSUE THREAD

**Issue by iiTzXyZ11** [xtekky/gpt4free#2325]
**Known Issues**
G4F not being able to properly process.

**Bug description**
i was creating a text summarizer and grader using g4f. the code runs smoothly at some times while not  so smooth. at times that it doesnt run smoothly, a response comes up stating "Thank you for using BlackBox.AI ..."

**Screenshots**
![Screenshot 2024-11-02 165552](https://github.com/user-attachments/assets/6f972fb0-442d-46d4-b7ce-9dd1c666d994)
![Screenshot 2024-11-02 165633](https://github.com/user-attachments/assets/e39187fc-3e5e-4b27-b823-f43031039108)

![Screenshot 2024-11-02 141710](https://github.com/user-attachments/assets/dc1c52ff-5a76-421b-bdde-0310ca52dbb3)

**Environment**
- python 3.12.7
- Philippines

**Comment by QingChengLineOne** [comment]
I have same problem
