### ISSUE TITLE
"New version of g4f" and "BlackBox.ai" message

### ISSUE THREAD

**Issue by Shwumper** [xtekky/gpt4free#2326]
![image](https://github.com/user-attachments/assets/439e8fe3-bcc3-4fef-8ddc-77c825bcaef1)
![image](https://github.com/user-attachments/assets/e9d6ae1a-151d-43d3-9f0a-de68c976e38f)
Python version: 3.11.1

![image](https://github.com/user-attachments/assets/64b9fcad-7d4e-4f50-a343-95aeb4141983)
![image](https://github.com/user-attachments/assets/88476e8f-37ef-4bd0-a988-d1c61c6b352e)

**Comment by testrustic** [comment]
I have the same problem, it is the best AI and it has never given me problems until today.

**Comment by Mishel-Tg** [comment]
Dm me in discord I'll give a api

**Comment by DinacoStudio** [comment]
whats you discord @Mishel-Tg

**Comment by Mishel-Tg** [comment]
lexica.dev/docs

**Comment by Badim41** [comment]
Add "validation" header.

![image](https://github.com/user-attachments/assets/4ec88aae-0c1b-41b5-9556-909f8ce5654e)
![image](https://github.com/user-attachments/assets/72d9ae4b-4326-4537-a11b-ebe84ce39b81)

I don't know if the same "validated" header "69783381-2ce4-4dbd-ac78-35e9063feabc" will work in all cases, but it worked several times for me even from different IP addresses.

**Comment by newsister** [comment]
How can I remove that message?

**Comment by Linden10** [comment]
> Add "validation" header.
> 
> ![image](https://private-user-images.githubusercontent.com/115208665/382998251-4ec88aae-0c1b-41b5-9556-909f8ce5654e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTc1ODYsIm5iZiI6MTczMDk1NzI4NiwicGF0aCI6Ii8xMTUyMDg2NjUvMzgyOTk4MjUxLTRlYzg4YWFlLTBjMWItNDFiNS05NTU2LTkwOWY4Y2U1NjU0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwNTI4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzQ0YjExYmVmYTVlOGY0ZmQ1ZDA1NDUwODlmY2ZlNzk2YmIzMTlkODAyMDZmNTQzZTdiOTk2ZGJjOGNjNjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9_kB2C8DCbslUfIrt9wTbRsE4Cu9eGnac-hi377DUsE) ![image](https://private-user-images.githubusercontent.com/115208665/382998261-72d9ae4b-4326-4537-a11b-ebe84ce39b81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTc1ODYsIm5iZiI6MTczMDk1NzI4NiwicGF0aCI6Ii8xMTUyMDg2NjUvMzgyOTk4MjYxLTcyZDlhZTRiLTQzMjYtNDUzNy1hMTFiLWViZTg0Y2UzOWI4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwNTI4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTRlMjEyZTRjMzdiYzZkNGE4MTFlZGIyN2M1MDVjMTJlNzI0OGYzODMyMGUyOWE4YTI1ZDI0MTRhMGRkZWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tK1GpUyM7Zhr-zOk7HJE6DXlxGbRxq7FUhG39GCFqdQ)
> 
> I don't know if the same "validated" header "69783381-2ce4-4dbd-ac78-35e9063feabc" will work in all cases, but it worked several times for me even from different IP addresses and messages.

Thank you! This fixed the issue of the api constantly not returning the full messaging and cutting off when using blackbox through the interference api!

Basically I had to open up blackbox.py (normally located in your python site-packages g4f folder) and add this line:
"validated": "69783381-2ce4-4dbd-ac78-35e9063feabc"

within the payload_api_chat headers function, right below "userSelectedModel".

Again thank you!
Hope this is incorporated into g4f if no problems arise form using it!

**Comment by DinacoStudio** [comment]
this id generated dynamic
```js
function uuidv4() {
    return "10000000-1000-4000-8000-100000000000".replace(/[018]/g, e => (Number(e) ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> Number(e) / 4).toString(16))
}
```

**Comment by Linden10** [comment]
> this id generated dynamic
> 
> ```js
> function uuidv4() {
>     return "10000000-1000-4000-8000-100000000000".replace(/[018]/g, e => (Number(e) ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> Number(e) / 4).toString(16))
> }
> ```

Very interesting! How would you integrate this with the blackbox.py script?
Can you explain where to put this? I love to use it when using g4f api alright, Thank you!

**Comment by DinacoStudio** [comment]
> > this id generated dynamic
> > ```js
> > function uuidv4() {
> >     return "10000000-1000-4000-8000-100000000000".replace(/[018]/g, e => (Number(e) ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> Number(e) / 4).toString(16))
> > }
> > ```
> 
> Very interesting! How would you integrate this with the blackbox.py script? Can you explain where to put this? I love to use it when using g4f api alright, Thank you!

I made fix using nodejs to find key in js using headless browser
```js
async function getKey() {
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox"],
  });
  const page = await browser.newPage();
  const regexp = /,w="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})"/;
  let k = "";
  page.on("response", async (response) => {
    if (response.request().resourceType() === "script") {
      try {
        let j = await response.text();
        if (j.match(regexp) !== null) {
          k = j.match(regexp)[1];
        }
      } catch {}
    }
  });

  await page.goto("https://www.blackbox.ai");
  await browser.close();
  return k;
}```

**Comment by Linden10** [comment]
> > > this id generated dynamic
> > > ```js
> > > function uuidv4() {
> > >     return "10000000-1000-4000-8000-100000000000".replace(/[018]/g, e => (Number(e) ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> Number(e) / 4).toString(16))
> > > }
> > > ```
> > 
> > 
> > Very interesting! How would you integrate this with the blackbox.py script? Can you explain where to put this? I love to use it when using g4f api alright, Thank you!
> 
> I made fix using nodejs to find key in js using headless browser
> 
> ```js
> async function getKey() {
>   const browser = await puppeteer.launch({
>     headless: true,
>     args: ["--no-sandbox"],
>   });
>   const page = await browser.newPage();
>   const regexp = /,w="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})"/;
>   let k = "";
>   page.on("response", async (response) => {
>     if (response.request().resourceType() === "script") {
>       try {
>         let j = await response.text();
>         if (j.match(regexp) !== null) {
>           k = j.match(regexp)[1];
>         }
>       } catch {}
>     }
>   });
> 
>   await page.goto("https://www.blackbox.ai");
>   await browser.close();
>   return k;
> }
> ```

That's very nice! I tried integrating it into blackbox.py but I wasn't working for me heh...still thanks for sharing!
I will say, that regex code...I used it to find the script containing that string on the website and used what was found in blackbox.py with the validated header!

I think it's working...thanks again!

**Comment by DinacoStudio** [comment]
I am very glad that my script will be useful
