### ISSUE TITLE
Please reply

### ISSUE THREAD

**Issue by Tanjirotg** [xtekky/gpt4free#2328]
How to set gemini cookies

**Comment by Tanjirotg** [comment]
Can u give me the code
I'll have cookies but idk where I'll add that

**Comment by TheFirstNoob** [comment]
@Tanjirotg Hi. use this docs: https://github.com/xtekky/gpt4free?tab=readme-ov-file#cookies
set_cookies params:
1. site (`.google.com`)
2. variable for needed cookies (`__Secure-1PSID`)
3. Value (like key)

Or other way  get info. Go to needed site and press `F12 -> Network`. Find `___Secure-1PSID` and copy for variable above.

**Comment by hlohaus** [comment]
Hey, you need to load cookies in Python. Check out the documentation for more info. Turn on debug mode to see more details.
