### ISSUE TITLE
meta ai problem

### ISSUE THREAD

**Issue by MH140000** [xtekky/gpt4free#2329]
An error occured: MetaAI: AbraGeoBlockedError: Meta AI isn't available yet in your country

**Comment by TheFirstNoob** [comment]
@MH140000 Hi. your region is blocked for use this provider. G4F didnt have functionals for evade block cause is most individuals for each user. Use other providers or models.

**Comment by MH140000** [comment]
But I can use it with other extension

**Comment by TheFirstNoob** [comment]
Provide more info like extensions and how you call this provider.

**Comment by MH140000** [comment]
I mean, I installed on a German server and got this error.

**Comment by TheFirstNoob** [comment]
Try to use proxy: https://github.com/xtekky/gpt4free?tab=readme-ov-file#using-proxy
Check your VPN settings maybe G4F use direct access w/o VPN. And try to change region in VPN to another and test again.

Note: Some providers not working on some regions. Always check all needed models.
