### ISSUE TITLE
Model "command-r+" returning 401 error: "You have to be logged in"

### ISSUE THREAD

**Issue by restartxx** [xtekky/gpt4free#2334]
**Bug description**

I'm experiencing an issue with the model "command-r+" not working. When attempting to use this model through the g4f API (running "g4f api"), I receive the following error:

```
ERROR:root:Request failed with status code: 401, response: {"error":"You have to be logged in."}
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/g4f/api/__init__.py", line 177, in chat_completions
    response = self.client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/g4f/client/client.py", line 241, in create
    return next(response)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/g4f/client/client.py", line 119, in iter_append_model_and_provider
    for chunk in response:
  File "/usr/lib/python3.11/site-packages/g4f/client/client.py", line 79, in iter_response
    for chunk in response:
  File "/usr/lib/python3.11/site-packages/g4f/Provider/HuggingChat.py", line 83, in create_completion
    raise RuntimeError(f"Request failed with status code: {response.status_code}, response: {response.text}")
RuntimeError: Request failed with status code: 401, response: {"error":"You have to be logged in."}
```

The model "command-r+" was working perfectly until yesterday. I am using g4f with Docker.

**Steps to Reproduce**

1. Run "g4f api" with the "command-r+" model.
2. Observe the error message in the terminal output.

**Environment**
- Python version: 3.11
- Location: Not in a Cloudflare-flagged country
- g4f version: [g4f v-0.3.3.3]

**Additional context**
No recent changes were made on my side. The model was working without issues until yesterday.

**Comment by Ragvard** [comment]
All models from HuggingChat provider return this error

**Comment by restartxx** [comment]
> All models from HuggingChat provider return this error

Hmm... Well, I hope it can be fixed soon. Do you know if there is a workaround?

**Comment by restartxx** [comment]
Solved!

**Comment by rodege** [comment]
> Solved!

this problem has appeared again :(

**Comment by restartxx** [comment]
(Keeping it open)

**Comment by restartxx** [comment]
Since the 'problem' was solved when HuggingChat was added to the providers that require cookies, simply providing g4f with the cookies is enough for the model Command-r+ (and any other HuggingChat model) to work. 
Closing this issue.
Thanks to the devs! 👏🏻🛴
