### ISSUE TITLE
you.com error

### ISSUE THREAD

**Issue by bejokun** [xtekky/gpt4free#2337]
G:\aiku>py tes2.py
G:\aiku\you.com.har
Using You provider and gpt-4-turbo model
ERROR:root:No telemetry in .har files found
ERROR:root:Getting telemetry_id for you.com with nodriver
ERROR:root:[WinError 1225] The remote computer refused the network connection
Using You provider and gpt-4-turbo model
ERROR:root:No telemetry in .har files found
ERROR:root:Getting telemetry_id for you.com with nodriver

**Comment by hlohaus** [comment]
Hey, we need a telemetry ID to create an account in You. They changed their account handling and now you can only use the free model.

**Comment by bejokun** [comment]
I create my own using requests and cookie using browser_cookie3, my account is premium and its work. is its still free model ?

https://i.imgur.com/DTy4c6m.png

**Comment by hlohaus** [comment]
I will be adding support for browser cookies and potentially implementing a nodriver login feature.
