### ISSUE TITLE
.har for chatgpt.com problem

### ISSUE THREAD

**Issue by MH140000** [xtekky/gpt4free#2338]
hello I got the .har by google chrome and placed it in the corresponding folder. But when I try to work with the chatgpt.com provider, it doesn't work. log:
 Read .har file: ./har_and_cookies/chatgpt.com.har                               
 Running on port 3333                                                            
  * Serving Flask app 'g4f.gui.server.app'                                       
  * Debug mode: on                                                               
 INFO:werkzeug:WARNING: This is a development server. Do not use it in a producti
 on deployment. Use a production WSGI server instead.                            
  * Running on all addresses (0.0.0.0)                                           
  * Running on http://127.0.0.1:3333                                             
  * Running on http://xxxx:3333                                          
 INFO:werkzeug:Press CTRL+C to quit                                              
 INFO:werkzeug: * Restarting with stat                                           
 Read .har file: ./har_and_cookies/chatgpt.com.har                               
 Running on port 3333                                                            
 WARNING:werkzeug: * Debugger is active!                                         
 INFO:werkzeug: * Debugger PIN: 405-973-995                                      
                                                                                 
  INFO:werkzeug:xxxx - - [07/Nov/2024 07:14:26] "GET /static/img/favicon-3
 2x32.png HTTP/1.1" 304 -                                                        
 INFO:werkzeug:xxxx - - [07/Nov/2024 07:14:27] "GET /static/js/text_to_sp
 eech/900.index.js HTTP/1.1" 304 -                                               
 INFO:werkzeug:xxxx - - [07/Nov/2024 07:14:27] "GET /static/img/gpt.png H
 TTP/1.1" 304 -                                                                  
 INFO:werkzeug:xxxx - - [07/Nov/2024 07:14:27] "GET /backend-api/v2/model
 s HTTP/1.1" 200 -                                                               
 INFO:werkzeug:xxxx - - [07/Nov/2024 07:14:27] "GET /backend-api/v2/provi
 ders HTTP/1.1" 200 -                                                            
 INFO:werkzeug:xxxx - - [07/Nov/2024 07:14:27] "GET /backend-api/v2/model
 s/ChatGpt HTTP/1.1" 200 -                                                       
 INFO:werkzeug:xxxx - - [07/Nov/2024 07:14:29] "GET /backend-api/v2/versi
 on HTTP/1.1" 200 -                                                              
 INFO:werkzeug:xxxx - - [07/Nov/2024 07:14:32] "GET /static/img/user.png 
 HTTP/1.1" 304 -                                                                 
 Failed to check g4f version: Version not found                                  
 Using ChatGpt provider and gpt-3.5-turbo model                                  
 {"detail":"Unusual activity has been detected from your device. Try again later.
  (8deb86f9fbc218e2-FRA)"}                                                       
 INFO:werkzeug:xxxx - - [07/Nov/2024 07:14:35] "POST /backend-api/v2/conv
 ersation HTTP/1.1" 200 -

**Comment by TheFirstNoob** [comment]
@MH140000 
Direct connect to chatgpt com working correct? w\o VPN?

Try to create new .har file w\o extensions browsers (Disable)

**Comment by MH140000** [comment]
Can you write step by step?

**Comment by MH140000** [comment]
Yes I can use chatgpt.com

**Comment by TheFirstNoob** [comment]
1. Open Browser
2. If you have extensions - disable them all
2.1 Disable all VPN programs
3. Go in Chatgpt.com and go in Chat.
4. Send any message to GPT
5. Create new .har file: https://github.com/xtekky/gpt4free?tab=readme-ov-file#using-har-and-cookie-files
6. Move .har in har folder.
7. Test again your problem. (Should be fix)

**Comment by MH140000** [comment]
I did these things but it didn't work. Note that I'm in a country where I can't open chatgpt.com without vpn, but vpn is not a google chrome extension. How to generate the har file is as follows:
I open Chrome, hit f12 and go to the network section, send a message to chatgpt and then select the Export HAR (sanitized)... option.

**Comment by TheFirstNoob** [comment]
If you cannot open chatgpt.com w\o VPN - .har file won't help you.
.har working directly to connect and log ```{"detail":"Unusual activity has been detected from your device. Try again later.
(8deb86f9fbc218e2-FRA)"}``` told Block Detection region and detect you.

webdriver is installed? _(You use g4f[all]?)_

**Comment by MH140000** [comment]
Yes. But my vps ip and vpn is same.

**Comment by MH140000** [comment]
sorry. I really need this file. Can you give me an email so I can send you the .har? Or, for example, should I give you my email address so that you can create one for me?

**Comment by TheFirstNoob** [comment]
You should create a .har file for yourself.
.har file save personal info like sessions or id data, cookies, POST/GET calls and results. HAR file is personal.
HAR file always need update after time (For me 1 har ~ 3 days. After stop work cause session change).

**Comment by MH140000** [comment]
i change my timezone but doesn't work. thanks for your help

**Comment by MH140000** [comment]
Can you check that the Export HAR (sanitized) button exports the .har correctly? Isn't there a plugin for this? The extension introduced in the project has been removed from the Chrome store.

**Comment by MH140000** [comment]
yes I want to know if the Export HAR (sanitized) button is different from right clicking and...?

**Comment by TheFirstNoob** [comment]
Nothing diffs like Export or
Right click - copy all to har - Open any txt or notepad and Ctrl + V. Rename file as you want site.har

Right clicking give more options for some each contenters sites individual if needed. Like copy only userID or what do you want.

Export is... full copy.

**Comment by MH140000** [comment]
I did this and selected copy all as har. Now, when I send a message to chatgpt in gpt4free, there is no error in the log, but I don't receive a message either.

**Comment by TheFirstNoob** [comment]
Try to set model `gpt-4o-mini` and test again.

**Comment by MH140000** [comment]
no. don't work and don't show error!

**Comment by MH140000** [comment]
Of course, I just ran git pull on the https://github.com/kqlio67/gpt4free project, maybe there is a problem.

**Comment by MH140000** [comment]
@kqlio67 thanks very much. Can you write how to generate the correct .har file?

**Comment by MH140000** [comment]
@kqlio67 i got accessToken not found error but i search in har file and found accessToken. but my har file is big about 30mb

**Comment by MH140000** [comment]
@kqlio67 An error occured: OpenaiChat: NoValidHarFileError: No accessToken found in .har files
I got the correct file with firefox and it contains all the required information, but it still shows the above error. The log also shows that 13 cookies have been entered.

**Comment by MH140000** [comment]
@kqlio67 hello I don't know why this happens. I open the developer, clear the log, refresh the chatgpt.com page and send a message to chat gpt and save the har. I logged in with Google and did not logout. I was logged in before I recorded har.

**Comment by MH140000** [comment]
@kqlio67 hello I really thank you. My problem is solved. The reason was adguard software. Just why is there no access to vision models through chatgpt, but in chatgpt.com it is able to describe the photo?
