### ISSUE TITLE
Model not found?

### ISSUE THREAD

**Issue by iiTzXyZ11** [xtekky/gpt4free#2343]
**Bug description**
I was trying to create a Summarizer and it is showing this error: "Model not found or too long input. Or any other error (xD)"

**Screenshots**
![image](https://github.com/user-attachments/assets/a5147667-d45c-452d-a6a9-8b3bee7f92d3)
![image](https://github.com/user-attachments/assets/cb7a7b13-176d-429b-81dd-1d235db35d34)

**Environment**
- 3.12.7
- Philippines

**Additional context**
I was trying to create a text summarizer just for fun and when i tested it out with a text that is around 200 words, the error showed up. This didnt happen a few weeks ago and everything was normal and functioning properly until recently.

**Comment by lnris2** [comment]
Same here, 

`[2024-11-11 20:24:17] Full detailed prompt response: {'id': 'chatcmpl-75cCr2aJYeD1O0QKpY9trI6Niu2B', 'object': 'chat.completion', 'created': 1731367457, 'model': 'gpt-3.5-turbo', 'provider': 'Airforce', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': 'Model not found or too long input. Or any other error (xD)'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 0, 'completion_tokens': 0, 'total_tokens': 0}}`

**Comment by foxfire52** [comment]
@lnris2  You should change Provider. I suspect it doesn't support `gpt-3.5-turbo` anymore.
Pull request #2313 should fix automatic provider selection for `gpt-3.5-turbo`.

**Comment by hlohaus** [comment]
Yeah, just use a different provider or model. I fixed the errors where it said the model wasn't found.
