### ISSUE TITLE
cloudscraper won't install

### ISSUE THREAD

**Issue by BokDan93** [xtekky/gpt4free#2344]
cloudscraper won't install

pip install cloudscraper doesn't help

The project does not start because of this. Help!
I don't want to clean everything by hand. How to ignore CloudFlare in the entire project?

Error:
Traceback (most recent call last):
  File "c:\Bots\GPT-Telegram Bot\bot.py", line 13, in <module>
    from g4f.client import Client
  File "c:\Bots\GPT-Telegram Bot\g4f\__init__.py", line 6, in <module>
    from .models import Model
  File "c:\Bots\GPT-Telegram Bot\g4f\models.py", line 5, in <module>
    from .Provider import IterListProvider, ProviderType
  File "c:\Bots\GPT-Telegram Bot\g4f\Provider\__init__.py", line 37, in <module> 
    from .Cloudflare       import Cloudflare
  File "c:\Bots\GPT-Telegram Bot\g4f\Provider\Cloudflare.py", line 6, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'

**Comment by TheFirstNoob** [comment]
@BokDan93 Hi!
How about base command?
```
pip install -U g4f
```

after this check like `pip show cloudscraper` or `pip list` and find this module

**Comment by BokDan93** [comment]
I have already used different commands, including reinstalling cloudscraper directly.

Used pip install -U g4f

Then:
pip show cloudscraper:

Name: cloudscraper
Version: 1.2.71
Summary: A Python module to bypass Cloudflare's anti-bot page.
Home-page: https://github.com/venomous/cloudscraper
Author: VeNoMouS
Author-email: venom@gen-x.co.nz
License: UNKNOWN
Location: c:\users\user\appdata\local\programs\python\python310\lib\site-packages
Requires: pyparsing, requests, requests-toolbelt
Required-by: g4f

Then:
pip list

cloudscraper            1.2.71

**Comment by BokDan93** [comment]
Thanks for your help, the problem is solved. I just deleted everything and cloned the repository again
