### ISSUE TITLE
OpenaiChat Provider, the paid features of the plus subscription do not work

### ISSUE THREAD

**Issue by dent0s** [xtekky/gpt4free#2354]
When using OpenaiChat, the paid ChatGPT Plus features (internet browsing, file and image viewing, analysis, image creation) are not working. I am using a .har file from an active session.

**Comment by 4mitabh** [comment]
can you post your test code? 
How have you been trying to access these features and what error do you get ?

**Comment by Techbeastz** [comment]
Bro do you got solution, I got same problem man. Is there another repositories you know.

**Comment by dent0s** [comment]
@4mitabh 
> can you post your test code? How have you been trying to access these features and what error do you get ?

```
import g4f
import os

cookies_dir = os.path.join(os.path.dirname(__file__), 'har_and_cookies')  
g4f.cookies.set_cookies_dir(cookies_dir)
g4f.cookies.read_cookie_files(cookies_dir)

response = g4f.ChatCompletion.create(
    model=g4f.models.gpt_4o,
    provider=g4f.Provider.OpenaiChat,
    messages=[{"role": "user", "content": "Prompt"}],
    auth=True
)

print(response)
```

input: Create an image of a cat
output: I don't have the ability to create images directly. However, I can help you imagine an adorable cat or provide instructions for drawing one!

input: Do a search on the Internet and find the current dollar to euro exchange rate
output:  I don't have the ability to browse the internet in real-time, so I can't provide the current dollar-to-euro exchange rate. 

Also, the model does not perceive images and files

But if you specify the id of an already created chat via the official client in the conversation_id parameter, then this chat will support paid functions

**Comment by 4mitabh** [comment]
According to https://github.com/xtekky/gpt4free/blob/main/docs/providers-and-models.md only the following models are supported on ChatGPT provider: gpt-4o, gpt-4o-mini, gpt-4
Specifically, dall-e and others models are not supported.

So, looks like this is a missing feature, and not a bug.

**Comment by hlohaus** [comment]
Hey there! I've got some good news! I managed to fix the image generation issue in the OpenaiChat provider. You can go ahead and use that awesome feature again!
