### ISSUE TITLE
INFO model not found or too long input. or any other error (xd)

### ISSUE THREAD

**Issue by AndreySupr** [xtekky/gpt4free#2355]
INFO model not found or too long input. or any other error (xd)

**Comment by Techbeastz** [comment]
Bro do you got solution, I got same problem man. Is there another repositories you know.

**Comment by TheFirstNoob** [comment]
@AndreySupr @Techbeastz Hi. provide please code or what provider, or what model you try run for replicate this problem.

**Comment by Techbeastz** [comment]
I am running the chat code "https://github.com/xtekky/gpt4free" and here's the code I am trying to run "from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Hello"}],
    # Add any other necessary parameters
)
print(response.choices[0].message.content)"

**Comment by TheFirstNoob** [comment]
![image](https://github.com/user-attachments/assets/baea76d5-63cf-49ae-9847-e2e772ad55ea)
Working correctly. Try to reinstall like `pip install -U g4f`

```
from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Hello"}],
# Add any other necessary parameters
)
print(response.choices[0].message.content)
```

**Comment by Techbeastz** [comment]
thank you so much man i love you, but gpt-4o-mini is working and gpt-3.5-turbo is not

**Comment by Techbeastz** [comment]
Bro I not check this code, but gpt-4o-mini is working.

**Comment by AndreySupr** [comment]
> Привет@AndreySuprи@Techbeastz,
> 
> Я тоже это тестировал, и похоже, что проблема, с которой вы столкнулись, связана именно с поставщиком Airforce. Недавно они прекратили поддержку модели gpt-3.5-turbo, поэтому у вас возникла эта проблема. Проблема была решена в этом pull request: #2313 .
> 
> Вероятно, в ближайшем будущем поддержка моделей gpt-3.5-turbo может еще больше сократиться, поскольку все меньше поставщиков продолжают использовать эту модель. Большинство переходят на модель gpt-4o-mini.
> 
> Поэтому я рекомендую перейти на более новую версию gpt-4o-mini, поскольку она предлагает более стабильную модель с лучшей поддержкой провайдера по сравнению с gpt-3.5-turbo. Найти провайдеров, которые все еще поддерживают gpt-3.5-turbo, становится все сложнее, и неизвестно, как долго они будут это делать.
> 
> Хотя некоторые поставщики все еще могут добавлять поддержку gpt-3.5-turbo, рекомендуется использовать gpt-4o-mini в качестве замены. По сути, gpt-4o-mini — это улучшенная версия gpt-3.5-turbo с дополнительным обучением, что приводит к немного лучшим ответам.
> 
> Более того, gpt-4o-mini немного более экономичен, поэтому многие провайдеры выбирают его вместо gpt-3.5-turbo.
> 
> Поэтому я бы рекомендовал перейти на gpt-4o-mini для более надежной и стабильной работы.

Thx Bro.
Here, I changed the code - it works. solution
        response = await g4f.ChatCompletion.create_async(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": f"{message_without_emojis}\n {req}"}],
        )
