### ISSUE TITLE
"mixtral-8x22b" is gone from 0.3.3.4 version ;-(

### ISSUE THREAD

**Issue by manatlan** [xtekky/gpt4free#2359]
"mixtral-8x22b" is gone ;-(

you can see it (dynamic list, ordered by nb of providers, of the models) : 
```
import g4f
all=[]
for model in g4f.models._all_models:
    m=g4f.models.ModelUtils.convert[model]
    o=m.best_provider
    if o is None:
        ll=[]
    elif isinstance(o,g4f.providers.retry_provider.IterListProvider):
        ll=o.providers
    else:
        ll=[o]
    all.append( (m.name, m.base_provider, len(ll),[i.__name__ for i in ll]) )

all.sort(key=lambda x: -x[2])
for model,society,nb,providers in all:
        print(nb,model,f"({society})",providers)

```

**Comment by TheFirstNoob** [comment]
@manatlan Hi, Yes, unfortunately there are currently no providers for this model or they work extremely unstable. If they are, the model will be returned back. Please check out other models for yourself here: https://github.com/xtekky/gpt4free/blob/main/g4f/models.py#L91

**Comment by manatlan** [comment]
but it worked well for me this morning, with 0.3.3.3 ...

**Comment by TheFirstNoob** [comment]
I check providers for 22b models on 0.3.3.3. Model is gone.

DeepInfra: https://deepinfra.com/chat
Airforce: https://api.airforce/v1/models
