### ISSUE TITLE
[Bug-List/Requests] New/Missing models, providers errors, Minor improvements

### ISSUE THREAD

**Issue by TheFirstNoob** [xtekky/gpt4free#2360]
### Actual for v0.3.8.1
List bugs and requests for g4f in issues list
This list will allow you to keep current issues and requests in case some of the topics were closed over time or lost.
**Please mark me if something is already fixed or I forgot to add a confirmed error. I will add/remove it.**

### REQUESTS: 
1. `Airforce` provider have more models and requested to add/restore `models.py` list (Need revert file to 0.3.3.4 version @kqlio67  version) + need split like `api.airforce` and `llmplayground` provider.
- For **Airforce** need use v0.3.3.4 version file (More chat-models, more stability, more faster response)
- For **LLM** need use actual version file (Actual LLM response but small stable + small models)

All this models work correctly on v0.3.3.4 version file!
- `gpt-3.5-turbo`
- `claude-3-haiku`
- `claude-3.5-sonnet`
- `gemini-flash`
- `gemini-pro`
- `llama-3.1-405b`
- `llama-3.2-90b`
- `mixtral-8x22b` https://github.com/xtekky/gpt4free/issues/2359
- `yi-34b`

2. Add Mistral large model with vision if possible https://github.com/xtekky/gpt4free/issues/2386
    - I think is new *Le Chat* model: https://chat.mistral.ai/chat
3. Add basic Auth/Managment user logic for WebUi: https://github.com/xtekky/gpt4free/issues/2407

### BUGS:
1. `PerplexityLabs` for `sonar-online` model response: `Unknown error`
2. `PizzaGPT` provider return `empty message` https://github.com/xtekky/gpt4free/issues/2392
3. `MagickPen` provider return:  `Unable to extract all the necessary data from the JavaScript file`
4. `Prodia` provider request cookies cause calling bing provider: `Error reading cookies from edge for .bing.com: ` (Only if try to use direct model call)

**Comment by AndreySupr** [comment]
request ended with status code 404

I have the same problem. Tell me, did you manage to fix it?
Version: 0.3.3.3

**Comment by hlohaus** [comment]
Hey Andrey, which provider did you use? Maybe try it with a different one.

**Comment by TheFirstNoob** [comment]
@hlohaus Hey.
1. I think user above tell about RubiksAI before fix we have 404 error. Other providers i didnt remember with this error.
2. I always try to check repo changes and update this thread for provider actual list bugs and requests. Please can you provide that i miss remove after fix/updates?

**Comment by hlohaus** [comment]
Thanks, @TheFirstNoob. What exactly do you miss after the updates?

**Comment by Linden10** [comment]
I don't know if you seen it but I made a comment about blackbox and it's issue with system prompts (when it comes to DazedMTL) here on the same post about chatgptes:
https://github.com/xtekky/gpt4free/issues/2393

It's only recently been happening (and to another user of DazedMTL) and I don't know why.

**Comment by TheFirstNoob** [comment]
@Linden10 Hi, Blackbox is sometimes overloaded and because of this the dialogue, instructions or system settings are lost. For this provider such data losses are quite normal already. That's why I didn't add this provider to the bug list.

**Comment by hlohaus** [comment]
You can also use providers with authentication such as OpenAI Chat and GeminiPro. They support system prompts.

**Comment by TheFirstNoob** [comment]
ok. now most bugs and feat. requests/questions are fixes/realised. I close this thread and recreate later new for more actualize list.
CLOSED!
