### ISSUE TITLE
Faulty 0.3.3.4 update: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by wwwjj2** [xtekky/gpt4free#2361]
**Bug description**
I have updated from 0.3.3.3 to 0.3.3.4 using `pip install -U g4f` and now I get an unhandled exception with every query. I have rolled back to 0.3.3.3 and it is fine 100% of queries. So this must be 0.3.3.4 issue.

The exception I get with 0.3.3.4:
Traceback (most recent call last):
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wwwjj\source\repos\******************", line 1, in <module>
    from g4f.client import Client
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\__init__.py", line 7, in <module>
    from .models import Model
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\models.py", line 5, in <module>
    from .Provider.not_working import Ai4Chat
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\__init__.py", line 15, in <module>
    from .Airforce         import Airforce
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\Airforce.py", line 10, in <module>
    from .airforce.AirforceChat import AirforceChat
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\airforce\__init__.py", line 1, in <module>
    from .AirforceChat        import AirforceChat
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\airforce\AirforceChat.py", line 45, in <module>
    class AirforceChat(AsyncGeneratorProvider, ProviderModelMixin):
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\airforce\AirforceChat.py", line 54, in AirforceChat
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\wwwjj\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Environment**
- python version: pip 24.1.2
- location ( are you in a cloudfare flagged country ) ? : Using VPN (own VPS)

**Additional context**
Since rolling back to 0.3.3.3 100% fixes the issue, the cause must be a faulty new version

**Comment by TheFirstNoob** [comment]
@wwwjj2 Hi! Should be fix right now. Its Airforce site problem - now resolved and work correclty.
Please check again your code for run.

**Comment by wwwjj2** [comment]
> @wwwjj2 Hi! Should be fix right now. Its Airforce site problem - now resolved and work correclty. Please check again your code for run.

Thank you, it seems to be working now. 

It seems like a terrible thing if this Airforce thing breaks the whole gpt4free module (since none of the providers worked), so is there a way to avoid this in the future? I mean, on my client side

Thank you

**Comment by TheFirstNoob** [comment]
g4f not fully breaks. Default model 3.5 turbo now have only 1 provider cause model is outdated.
You can use model=model_name_here for others for auto provider or set provider direclty.

**Comment by wwwjj2** [comment]
> g4f not fully breaks. Default model 3.5 turbo now have only 1 provider cause model is outdated. You can use model=model_name_here for others for auto provider or set provider direclty.

When it happened after an update, I had this set of providers (on success stop trying to prompt, on fail go to the next one from this list):
"OpenaiChat", "gpt-4o-mini")
"Bing", "gpt-4o")
"DDG", "gpt-4o-mini")
"Pizzagpt", "gpt-4o-mini")
"Ai4Chat", "gpt-4")
"HuggingChat", "command-r+")
"FreeGpt", "gpt-3.5")
"NexraChatGPT", "gpt-4")
"ChatgptFree", "gpt-4o-mini")
"Liaobots", "gpt-4o-mini")
"Airforce", "gpt-4o")

So I've tried removing all of them except one - "OpenaiChat" - and so on with every single provider from this list, and the issue still persisted, so I thought the new version is broken since when I rolled back it was totally fine.

Though I think I had [None, "gpt-4"] provider added to my providers_to_try array, so probably it tried to access the broken  Airforce as well.

But I'm really willing to find a way to avoid such crashes in the future if one or more providers crash internally. 
I have everything wrapped in "try-catch except Exception", but this one seemed to be uncatchable as it was some internal crash.

**Comment by TheFirstNoob** [comment]
For more stable you can try like this example i use
List providers like "Who start first" if provider not response - go next, if all provider not response - go next)

```
        # Chat providers
        "gpt-3.5-turbo": [Airforce],
        "gpt-4": [Mhystical],
        "gpt-4-turbo": [Airforce],
        "gpt-4o-mini": [Pizzagpt, Airforce, ChatGptEs, DDG],
        "gpt-4o": [Blackbox, ChatGptEs, Airforce],
        "claude-3-haiku": [DDG, Airforce],
        "claude-3.5-sonnet": [Blackbox, Airforce],
        "blackbox": [Blackbox],
        "blackbox-pro": [Blackbox],
        "gemini-flash": [Blackbox, Airforce],
        "gemini-pro": [Blackbox, Airforce],
        "gemma-2b-27b": [Airforce],
        "command-r-plus": [HuggingChat],
        "llama-3.1-70b": [HuggingChat, Blackbox, TeachAnything, Free2GPT, Airforce, DDG],
        "llama-3.1-405b": [Blackbox, Airforce],
        "llama-3.2-11b": [HuggingChat, HuggingFace],
        "llama-3.2-90b": [Airforce],
        "nemotron-70b": [HuggingChat],
        "sonar-chat": [PerplexityLabs],
        "lfm-40b": [PerplexityLabs],
        "qwen-2-72b": [HuggingChat],
        "mixtral-8x7b": [HuggingChat, DDG],
        "mixtral-8x22b": [Airforce],
        "yi-34b": [Airforce],
        "phi-3.5-mini": [HuggingChat],

        #"ai_uncensored": [AIUncensored],
        "any_uncensored": [Airforce],

        "llava-13b": [ReplicateHome], #vision model for later
```

**Comment by wwwjj2** [comment]
@TheFirstNoob Thank you for the list! 

The thing is, none of my try-catch blocks were able to catch the Airforce provider crash.
Basically, this is how it looks:
`try:
    client.chat.completions.create(...)
except Exception as e:
   ...`

So, this try-catch block was unable to catch the Airforce JSONDecodeError.

Can you please give me an advice on how to reliably catch it avoiding the whole script crash if something like this ever happens again with Airforce or any other provider?

Will this help?
`try:
    client.chat.completions.create(...)
except requests.exceptions.JSONDecodeError as json_err:
    ...
except Exception as e:
   ...`

**Comment by TheFirstNoob** [comment]
What i use
https://github.com/TheFirstNoob/Discord-ChatGPT/blob/main/src/aclient.py#L45
https://github.com/TheFirstNoob/Discord-ChatGPT/blob/main/src/aclient.py#L51
https://github.com/TheFirstNoob/Discord-ChatGPT/blob/main/src/aclient.py#L225
https://github.com/TheFirstNoob/Discord-ChatGPT/blob/main/src/aclient.py#L238
