### ISSUE TITLE
unsupported operand type(s) for ** or pow(): 'NoneType' and 'dict'

### ISSUE THREAD

**Issue by Phant0m3090** [xtekky/gpt4free#2363]
from g4f.client import Client

client = Client()
response = client.images.generate(
    model="flux",
    prompt="a white siamese cat",
    # Add any other necessary parameters
)

image_url = response.data[0].url
print(f"Generated image URL: {image_url}")

Error:
Traceback (most recent call last):
  File "C:\Users\Phant0m\Desktop\meme-generator.py", line 4, in <module>
    response = client.images.generate(
  File "C:\Users\Phant0m\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\client\__init__.py", line 250, in generate
    return asyncio.run(self.async_generate(prompt, model, provider, response_format=response_format, proxy=proxy **kwargs))
TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'dict'

**Comment by hlohaus** [comment]
I fixed this issue already 👍
