### ISSUE TITLE
why did you delete client.py?

### ISSUE THREAD

**Issue by andyvandaric** [xtekky/gpt4free#2368]
Why did you delete client.py? and in the tutorial still use client module?

in this commit you have deleted client.py https://github.com/xtekky/gpt4free/commit/6ce493d4dfc2884832ff5b5be4479a55818b2fe7#diff-0324575d39e48dbf4a98d4d47efc53a795406ffffbdf198e1aea94846af 1dc3c So how do you adjust the use of g4f?

Please let me know

**Comment by TheFirstNoob** [comment]
@andyvandaric Hi, now we back to Client and AsyncClient
Docs:
https://github.com/xtekky/gpt4free/blob/main/docs/client.md
https://github.com/xtekky/gpt4free/blob/main/docs/async_client.md

**Comment by hlohaus** [comment]
I moved the client to the __init__.py file.
