### ISSUE TITLE
Website Not Accessible - Error 522

### ISSUE THREAD

**Issue by ChsPranav** [xtekky/gpt4free#2371]
Attempted to access the website https://g4f.ai/, but encountered an Error 522: Connection Timed Out. This indicates that the server is taking too long to respond to Cloudflare's requests.

**Error Screenshot:**
![g4f](https://github.com/user-attachments/assets/bf8b7817-067f-43af-8166-5db52dab53b8)

**Steps to Reproduce:**
Attempt to visit https://g4f.ai/.
Observe the Error 522 message.
Confirm connectivity with the web server using the following checks:
Verify if the web server is operational.
Review and update Cloudflare DNS settings if necessary.
Inspect other relevant web server configurations.

**Suggested Resource:**
This [Hostinger guide](https://www.hostinger.com/tutorials/error-522) provides actionable steps to troubleshoot and resolve Error 522 issues.

**Additional Notes:**
Please check server logs to identify potential bottlenecks or misconfigurations.
Let me know if any further details or testing is needed to assist in resolving this issue.

**Comment by TheFirstNoob** [comment]
@ChsPranav Hi if i know site is down a long time.
