### ISSUE TITLE
bug : Unicode Conversion Error in kr , model support kr , ui not support kr

### ISSUE THREAD

**Issue by gudcks0305** [xtekky/gpt4free#239]
## Bug Images 

![image](https://user-images.githubusercontent.com/84506708/235077851-2876b8cc-4fa5-414e-8b3c-43908ce21c5e.png)

![image](https://user-images.githubusercontent.com/84506708/235077988-c4edff8a-fa2d-4cf9-8461-32336c89302e.png)
above response mean that this model support every languages for kr.

**Comment by zwjzxh520** [comment]
same for chinese

**Comment by nongfu9woo** [comment]
decode the answer text in streamlit_app.py (line 45)

**Comment by nongfu9woo** [comment]
> same for chinese

在streamlit_app.py中，将45行那获取到answer改成st.markdown(bytes(answer, 'utf-8').decode('unicode_escape'))

**Comment by xtekky** [comment]
got fixed
