### ISSUE TITLE
Some providers like TeachAnything or Pizzagpt aren't returning responses anymore 

### ISSUE THREAD

**Issue by unical1988** [xtekky/gpt4free#2392]
I have first tested TeachAnything with test-ada-001 model and it worked 2 months ago, but now it doesn't, same for Pizzagpt.

many other providers return errors 

is this accounted for / documented somewhere? how to fix these so that a seemless use of g4f can be possible?

**Comment by TheFirstNoob** [comment]
@unical1988 Hi, provide more information please.
TeachAnything use `gpt3.5-turbo-0125` model and `llama-3.1-70b`
PizzaGPT use `gpt-4o-mini` model

Old model not used for most main providers and can be remove later on site. Its not g4f bug.
Set correct model and repeat for answer check

**Comment by erstrik** [comment]
Hi, I confirm I can't use PizzaGPT anymore.

your avatar

test
(1 words, 4 chars, 1 tokens)
your avatar
Pizzagpt with gpt-4o-mini
(0 words, 0 chars, 0 tokens)

**Comment by unical1988** [comment]
@TheFirstNoob can you provide an exhaustive list of associations between the providers and the models they use?

**Comment by TheFirstNoob** [comment]
@unical1988 You can use this full list: https://github.com/xtekky/gpt4free/blob/main/g4f/models.py#L83
Or open g4f/Provider/Name provider and see what models each provider use direclty.

**Comment by TheFirstNoob** [comment]
@unical1988 Try to `claude-3.5-sonnet`. Liaobots provider not stable (Rate limits) with Blackbox provider

**Comment by TheFirstNoob** [comment]
@unical1988 `response = client.chat.completions.create`

https://github.com/xtekky/gpt4free/blob/main/docs/client.md

**Comment by unical1988** [comment]
@TheFirstNoob I don't want chat I just want text completion, what is the method to use?

**Comment by TheFirstNoob** [comment]
This example code above is text completion

https://github.com/xtekky/gpt4free/blob/main/docs/client.md#text-completions

**Comment by unical1988** [comment]
@TheFirstNoob it doesn't show all necessary parameters/attributes; how to specify the provider I want to select ?

**Comment by TheFirstNoob** [comment]
Please read docs full.
All answer have on docs: https://github.com/xtekky/gpt4free/blob/main/docs/client.md#using-a-list-of-providers-with-retryprovider

**Comment by unical1988** [comment]
@TheFirstNoob No I can't find the answer in the link you sent, I just need one example of text completion with specified params of model and provider. Thanks

**Comment by unical1988** [comment]
@TheFirstNoob also how to excluse certain providers when using RetryProvider

**Comment by TheFirstNoob** [comment]
The example above uses the providers and models exactly as you require. You can put them in arrays and RetryProvider will only work with the providers you specify. It will not work with those you do NOT specify.

Example array:

```
        "gpt-3.5-turbo": [Airforce],
        "gpt-4": [Mhystical],
        "gpt-4-turbo": [Airforce],
        "gpt-4o-mini": [Pizzagpt, Airforce, ChatGptEs, DDG],
        "gpt-4o": [Blackbox, ChatGptEs, Airforce],
        "claude-3-haiku": [DDG, Airforce],
        "claude-3.5-sonnet": [Blackbox, Airforce],
        "blackbox": [Blackbox],
        "blackbox-pro": [Blackbox],
        "gemini-flash": [Blackbox, Airforce],
        "gemini-pro": [Blackbox, Airforce],
        "gemma-2b-27b": [Airforce],
        "command-r-plus": [HuggingChat],
        "llama-3.1-70b": [HuggingChat, Blackbox, TeachAnything, Free2GPT, Airforce, DDG],
        "llama-3.1-405b": [Blackbox, Airforce],
        "llama-3.2-11b": [HuggingChat, HuggingFace],
        "llama-3.2-90b": [Airforce],
        "nemotron-70b": [HuggingChat],
        "sonar-chat": [PerplexityLabs],
        "lfm-40b": [PerplexityLabs],
        "qwen-2-72b": [HuggingChat],
        "mixtral-8x7b": [HuggingChat, DDG],
        "mixtral-8x22b": [Airforce],
        "yi-34b": [Airforce],
        "phi-3.5-mini": [HuggingChat],
 ```
 
 Example full base code:
 ```
 from g4f.client import Client
from g4f.Provider import RetryProvider, Airforce, Mhystical, Pizzagpt, Blackbox, HuggingChat, TeachAnything, Free2GPT, DDG, PerplexityLabs, ChatGptEs, HuggingFace
import g4f.debug

g4f.debug.logging = True
g4f.debug.version_check = False

# List of available models and their providers
models = {
    "gpt-3.5-turbo": [Airforce],
    "gpt-4": [Mhystical],
    "gpt-4-turbo": [Airforce],
    "gpt-4o-mini": [Pizzagpt, Airforce, ChatGptEs, DDG],
    "gpt-4o": [Blackbox, ChatGptEs, Airforce],
    "claude-3-haiku": [DDG, Airforce],
    "claude-3.5-sonnet": [Blackbox, Airforce],
    "blackbox": [Blackbox],
    "blackbox-pro": [Blackbox],
    "gemini-flash": [Blackbox, Airforce],
    "gemini-pro": [Blackbox, Airforce],
    "gemma-2b-27b": [Airforce],
    "command-r-plus": [HuggingChat],
    "llama-3.1-70b": [HuggingChat, Blackbox, TeachAnything, Free2GPT, Airforce, DDG],
    "llama-3.1-405b": [Blackbox, Airforce],
    "llama-3.2-11b": [HuggingChat, HuggingFace],
    "llama-3.2-90b": [Airforce],
    "nemotron-70b": [HuggingChat],
    "sonar-chat": [PerplexityLabs],
    "lfm-40b": [PerplexityLabs],
    "qwen-2-72b": [HuggingChat],
    "mixtral-8x7b": [HuggingChat, DDG],
    "mixtral-8x22b": [Airforce],
    "yi-34b": [Airforce],
    "phi-3.5-mini": [HuggingChat],
}

# Model selection
print("Available models:")
for i, model in enumerate(models.keys()):
    print(f"{i + 1}. {model}")

model_choice = int(input("Select the model number: ")) - 1
selected_model = list(models.keys())[model_choice]

# Input text for prompt
user_input = input("Enter your text: ")

client = Client(
    provider=RetryProvider(models[selected_model], shuffle=False)
)

response = client.chat.completions.create(
    model=selected_model,
    messages=[
        {
            "role": "user",
            "content": user_input
        }
    ]
)

print(response.choices[0].message.content)
```

**Comment by unical1988** [comment]
How to make RetryProvider work with all possible providers ? how to exclude certain from those?

**Comment by TheFirstNoob** [comment]
```"gpt-4o-mini": [Pizzagpt, Airforce, ChatGptEs, DDG, remove or add provider here],```
provider is not list here never called

**Comment by unical1988** [comment]
is 

    "gpt-3.5-turbo": [Airforce],
        "gpt-4": [Mhystical],
        "gpt-4-turbo": [Airforce],
        "gpt-4o-mini": [Pizzagpt, Airforce, ChatGptEs, DDG],
        "gpt-4o": [Blackbox, ChatGptEs, Airforce],
        "claude-3-haiku": [DDG, Airforce],
        "claude-3.5-sonnet": [Blackbox, Airforce],
        "blackbox": [Blackbox],
        "blackbox-pro": [Blackbox],
        "gemini-flash": [Blackbox, Airforce],
        "gemini-pro": [Blackbox, Airforce],
        "gemma-2b-27b": [Airforce],
        "command-r-plus": [HuggingChat],
        "llama-3.1-70b": [HuggingChat, Blackbox, TeachAnything, Free2GPT, Airforce, DDG],
        "llama-3.1-405b": [Blackbox, Airforce],
        "llama-3.2-11b": [HuggingChat, HuggingFace],
        "llama-3.2-90b": [Airforce],
        "nemotron-70b": [HuggingChat],
        "sonar-chat": [PerplexityLabs],
        "lfm-40b": [PerplexityLabs],
        "qwen-2-72b": [HuggingChat],
        "mixtral-8x7b": [HuggingChat, DDG],
        "mixtral-8x22b": [Airforce],
        "yi-34b": [Airforce],
        "phi-3.5-mini": [HuggingChat],

an exhaustive list, is there any other model/provider I can use for chat.completion? Thanks.

**Comment by TheFirstNoob** [comment]
You can create array for unused providers with IterListProvider class on excluded list
https://github.com/xtekky/gpt4free/blob/main/g4f/providers/retry_provider.py#L11

But I still recommend the option above because it has more control over the required models and providers.

**Comment by TheFirstNoob** [comment]
I have already written about models and providers above, directing you to `models.py` https://github.com/xtekky/gpt4free/blob/main/g4f/models.py#L83
It works exactly on the same principle that I suggested to you. The model is selected and goes through the list of providers that are indicated there. That is why it is better to make your own list for your needs and requirements.

The file list always indicates the models and providers available to them.
If you specify a model and select the wrong provider, you will get an error as expected.

Please create your own list that you need based on the example above and do not forget to update it if the library is updated.

**Comment by unical1988** [comment]
Could you explain more, how the state is saved?
