### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by raymerjacque** [xtekky/gpt4free#2401]
how to specify the image size ?

```
from g4f.client import Client

client = Client()
response = client.images.generate(
    model="flux",
    prompt="a white siamese cat",
    # Add any other necessary parameters
)

image_url = response.data[0].url
print(f"Generated image URL: {image_url}")
```

how do i add size paramters ? width x height doesnt seem to work, it always generates square...

**Comment by raymerjacque** [comment]
nevermind i figured it out.

**Comment by hlohaus** [comment]
Hey, most providers don't let you do this. Only PollinationsAI does it right now. Also, AI models aren't trained to very big sizes, so the results aren't always the best.
