### ISSUE TITLE
G4F

### ISSUE THREAD

**Issue by sanjar1221** [xtekky/gpt4free#2402]
const { G4F } = require("g4f");
const g4f = new G4F();

const messages = [
    { role: "user", content: "Hi, what's up?"}
];

const options = {
    provider: g4f.providers.GPT,  
    model: "gpt-3.5-turbo",          
    debug: true,                     
    proxy: ""                       
};

(async () => {
    try {
        console.log("Sending request...");
        
        // Отправляем запрос и получаем ответ
        const response = await g4f.chatCompletion(messages, options);
        
        // Логируем полученный ответ
        console.log("Raw response:", JSON.stringify(response, null, 2));

        if (!response) {
            console.error("No response returned.");
        } else {
            console.log("Response:", JSON.stringify(response, null, 2));
        }
    } catch (error) {
        console.error("Error:", error.message);
        console.error("Full Error:", JSON.stringify(error, null, 2));  // Логируем подробности ошибки
    }
})();

Sending request...
[provider] » ...  awaiting  Picking a provider from the working list...
[provider] » √  success   Provider found: GPT

[model] » √  success   Using the model: gpt-3.5-turbo

[provider] » ...  awaiting  Fetching data from the provider: GPT
Error: Invalid response.
Full Error: {}

**Comment by sanjar1221** [comment]
pls help

**Comment by hlohaus** [comment]
Try use a other model and/or provider:
```javascript
const options = {
    provider:  "Copilot",  // Microsoft Copilot
    model: "",  // Default model  
    debug: true,                     
    proxy: ""                       
};
```
