### ISSUE TITLE
SyntaxError: Invalid Character in g4f/api/__init__.py

### ISSUE THREAD

**Issue by restartxx** [xtekky/gpt4free#2411]
**Description:**

Hi,

I encountered an issue while running the `g4f` API. The error occurs when executing the following command:

```bash
g4f api
```

The full traceback is as follows:

```
Traceback (most recent call last):
  File "/usr/bin/g4f", line 8, in <module>
    sys.exit(main())                                                               ^^^^^^
  File "/usr/lib/python3.11/site-packages/g4f/cli.py", line 34, in main
    run_api_args(args)
  File "/usr/lib/python3.11/site-packages/g4f/cli.py", line 42, in run_api_args
    from g4f.api import AppConfig, run_api
  File "/usr/lib/python3.11/site-packages/g4f/api/__init__.py", line 91
    ⅞
    ^
SyntaxError: invalid character '⅞' (U+215E)
```

**Steps to reproduce:**
1. Run the following command:
   ```bash
   g4f api
   ```
2. The error will occur, pointing to an invalid character (`⅞`, U+215E) in the `g4f/api/__init__.py` file.

**Expected behavior:**
The API should run without syntax errors.

**Environment:**
- Python version: 3.11
- `g4f` version: (0.3.6.4)

**Comment by hlohaus** [comment]
I removed this invalid character
