### ISSUE TITLE
[Question] A way to disable new Chat creation for every prompt with ChatGPT provider & .har (OpenaiChat)

### ISSUE THREAD

**Issue by wwwjj2** [xtekky/gpt4free#2431]
I've noticed recently that now a new Chat is created on chatgpt.com for my account with every prompt by gpt4free when I use OpenaiChat provider with .har file. 
The chat (conversation) list is quite messy now. It wasn't like that before, I'm guessing it used "Temporary chat".

Is there a way to avoid creating a new chat with every prompt like it was before?

I'm expecting something like this (improvised code):
```
client.chat.completions.create(
                            model=model,
                            provider=provider,
                            **temporary_chat=True,**
                            messages=[{"role": "user", "content": prompt}])
```

My current version is 0.3.7.4

**Comment by hlohaus** [comment]
You are searching for:
  history_disabled=True
If you use the Python client, you can pass it in the create function.

**Comment by wwwjj2** [comment]
@hlohaus Thank you very much!

**Comment by taton331** [comment]
Is there a way to do this if I'm using docker?
