### ISSUE TITLE
the docker version is always lated

### ISSUE THREAD

**Issue by heartacker** [xtekky/gpt4free#2438]
**Bug description**
thus I pull the docker latest again and again， the local version is old， and the release version and docker tag is newer

**Screenshots**

![image](https://github.com/user-attachments/assets/d093ba18-5008-47d4-8863-79eeae004ba1)

**Environment**
docker

**Additional context**
docker pull latest

**Comment by hlohaus** [comment]
Hey, use this docker run command from the Readme:

```
docker run \
  -p 1337:1337 \
  -v ${PWD}/har_and_cookies:/app/har_and_cookies \
  -v ${PWD}/generated_images:/app/generated_images \
hlohaus789/g4f:latest-slim \
  rm -r -f /app/g4f/ \
  && pip install -U g4f[slim] \
  && python -m g4f.cli api --gui --debug
```
This will uninstall the package on the image and install the new version from pip. You don't need to pull the docker image every time.
