### ISSUE TITLE
Airforce image generation issue

### ISSUE THREAD

**Issue by chekamarue** [xtekky/gpt4free#2444]
what is the host of images generated by Airforce from my code bellow am getting only the path without host !
```
client = Client(
                provider=Airforce,
                image_provider=Airforce,
                #proxies=proxy,
                #timeout=3, 
            )
response = client.images.generate(
    model=flux, 
    prompt="cat"
    )
if response:
    print(response)
    link = response.data[0].url if response.data else None
    print(link)
```
output come like this 
```/images/1732997092_5fbc1284-3427-4d65-878b-45abba647788.jpg```

**Comment by hlohaus** [comment]
Please navigate to the generated_images directory. The images are stored there with their path names.

You can change the response format to "json_base64" or "original".

**Comment by chekamarue** [comment]
Thank you very much for all the work you are giving here ! I haven't notice that there is a new image directory in root folder of the script
