### ISSUE TITLE
None of the Vision Models work

### ISSUE THREAD

**Issue by aach360** [xtekky/gpt4free#2445]
According to docs, 
<img width="643" alt="image" src="https://github.com/user-attachments/assets/fd3d344d-b592-49f0-bf0a-5ac257a82b74">
I have tried all of these Vision Models and none of them work. 

Code as provided:
```python
import g4f
import requests
from g4f.client import Client
import g4f.Provider.Blackbox	

image = requests.get("https://raw.githubusercontent.com/xtekky/gpt4free/refs/heads/main/docs/cat.jpeg", stream=True).raw
# Or: image = open("docs/cat.jpeg", "rb")

client = Client(
    provider=g4f.Provider.Blackbox
)

response = client.chat.completions.create(
    model="gemini-pro",
    messages=[
        {
            "role": "user",
            "content": "What are on this image?"
        }
    ],
    image=image
    # Add any other necessary parameters
)

print(response.choices[0].message.content)

```

Output Recived:
"I am sorry, I do not have access to any image content or real-time information, including the internet. Therefore, I cannot provide any information about the image or what it contains."

When I used the blackbox ai, the output was as follows:
"There is no image provided in the context. The context only mentions a Github Repository code, but it's empty. If you provide the actual code or image, I'll be happy to help you with your question."

I would greatly appreciate any help with a functional model/provider/code or any insights in general you may have. Thanks!

Environment
- python version 3.12.7
- location: USA

**Comment by DeveleplorAbdullahH** [comment]
Can you please send the docs link or repository ID? I will look at the docs and reply to you. Maybe there are some issues with them in docs because they are working on G4F's local website.

**Comment by hlohaus** [comment]
The list has been recently updated.

Consider the following providers:

- OpenaiAccount
- GeminiPro
- Gemini
- CopilotAccount

Please note that all of these providers require a free account on their respective websites.

**Comment by aach360** [comment]
> The list has been recently updated.
> 
> Consider the following providers:
> 
> * OpenaiAccount
> * GeminiPro
> * Gemini
> * CopilotAccount
> 
> Please note that all of these providers require a free account on their respective websites.

Just to confirm, are you refrencing to use theese services sepreate from g4f, directly with their API's using the free credits offered?

If you are refrencing using g4f still, 

CopilotAccount is unrecognised as a model I think because bing is no longer supported
Gemini as a provider is unrecognized I think because it is also no longer supported
OpenaiAccount is also disfunctional as it returns the following error:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://chatgpt.com/backend-anon/conversation
