### ISSUE TITLE
Web Search Provider or model

### ISSUE THREAD

**Issue by DeveleplorAbdullahH** [xtekky/gpt4free#2448]
Hello. I want that there is a new model or Provider that provides gpt-4o model but it has also searching ability to search what user requested. It seems that in Blackbox AI's website, there is a web search ability. Please implement that to the g4f library or to another provider with gpt-4o model.

**Comment by hlohaus** [comment]
Hello @DeveleplorAbdullahH,

the Blackbox provider does support web search. To enable this feature, you will need to set the "web_search" argument to True.

Please let me know if you have any further questions or concerns.

**Comment by DeveleplorAbdullahH** [comment]
But it is not working. i wrote the web_search argument inside the completions create but it didn't work
