### ISSUE TITLE
I get error when use chatgpt model

### ISSUE THREAD

**Issue by daoquan99** [xtekky/gpt4free#2452]
![image](https://github.com/user-attachments/assets/66d5d001-ca76-4c9b-8fff-e5540c4b73cc)
![image](https://github.com/user-attachments/assets/1fc83fa3-4ac4-49aa-9db4-05405b278f89)
please help me!

**Comment by garfry** [comment]
Same issue. I also get this error:
An error occured: OpenaiChat: Exception: --------------------- Failed to connect to browser --------------------- One of the causes could be when you are running as root. In that case you need to pass no_sandbox=True

**Comment by hlohaus** [comment]
Hey, ChatGpt provider's down.  You could try OpenaiChat, but you'll need to make a .har file for that.
