### ISSUE TITLE
Image Generation with ChatGpt Plus

### ISSUE THREAD

**Issue by judo-sudo** [xtekky/gpt4free#2453]
i am trying to generate image with a chatgpt plus (paid) account.

```
        response = client.chat.completions.create(
            messages=[{"role": "user","content": promptText}] ,
            model='auto',
            conversation_id="674fef59-d9e8-800f-9621-xxxxxxxx",
            history_disabled=False,
            auth=True,
            provider=g4f.Provider.OpenaiChat)
```

The conversation id belongs to a conversation with dall-e, yet I get get an error saying: "I currently can\'t generate images, but I can describe how you might create one.... etc"

setting model to  'gpt-4o' does not work either.

The same code used to work until 3 weeks ago.

I am using g4f 0.3.8.1

**Comment by hlohaus** [comment]
I can't find anything wrong.

![Screenshot_20241204_222813_Chrome.jpg](https://github.com/user-attachments/assets/2b7bd091-6ced-49e5-9c74-899715ec4a23)

**Comment by judo-sudo** [comment]
Here are my logs:

It seems to send the request to wrong model, even if I select the dall-e model for image generation.

![Screenshot 2024-12-04 at 8 17 38 PM](https://github.com/user-attachments/assets/2c44bb78-8077-43da-b2e0-5e2ec477dc7d)


```
Using OpenaiChat provider and dall-e-3 model
Arkose: False
Proofofwork: gAAAAABWzMxM...
AccessToken: eyJhbGciOiJS...
OpenaiChat: New conversation: 
```

**Comment by hlohaus** [comment]
If you select dall-e-3 will be used "auto". Try choosing a different model.

**Comment by judo-sudo** [comment]
If i choose another model (like 4o) , I am not able to generate images. I get an error saying "I cannot generate images..." or "Image generation is currently unavailable"....

i get the same error when I try the 4o model via chatgpt.com.

However, I can generate images if I choose dall-e on chatgpt.com.


If there were were a way to force use of dall-e via g4f.

I also tried the following code, but no avail:

```

        response = client.chat.completions.create(
            messages=[{"role": "user","content": promptText}] ,
            model='dall-e-3',
            conversation_id="a-dalle-conversation-id",
            history_disabled=False,
            auth=True,
            provider=g4f.Provider.OpenaiChat)

```

**Comment by hlohaus** [comment]
ChatGPT's image generation incorporates robust bot protection.  Using outdated or self-generated proof tokens will prevent image generation; however, utilizing the current version resolves this issue.
