### ISSUE TITLE
Vision Support in OpenaiChat Provider

### ISSUE THREAD

**Issue by The2Alert** [xtekky/gpt4free#2461]
**Request**

Please improve the Vision function so that you can transfer several pre-loaded images.
Image parameters are not processed.

**API HTTP Request**
/v1/chat/completions

**Example Body**
```json
{
    "model": "gpt-4o-mini",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "What are in these images? Is there any difference between them?"
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
            }
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
            }
          }
        ]
      }
    ],
    "max_tokens": 300
  }
```

**OpenAI Official Docs**
https://platform.openai.com/docs/guides/vision

**Only text :(**

https://github.com/xtekky/gpt4free/blob/ead8230e4f771c6b840d5b27aa6cbbe1da2eb896/g4f/Provider/needs_auth/OpenaiChat.py#L164

**Comment by hlohaus** [comment]
Image data URIs are accepted within the designated image field; embedding them within message content is not supported.  Currently, only a single image is accommodated due to ongoing efforts to ensure broad provider compatibility.

**Comment by The2Alert** [comment]
add support for multiple images
![Screenshot 2024-12-10 210035](https://github.com/user-attachments/assets/e19847c1-cac3-4a3c-9548-7b3860cbe012)
![Screenshot 2024-12-10 210056](https://github.com/user-attachments/assets/a50b2109-d493-4560-af02-61c482680382)
