### ISSUE TITLE
request: InterferenceAPI Completions Support

### ISSUE THREAD

**Issue by kerichdev** [xtekky/gpt4free#2468]
**Is your feature request related to a problem? Please describe.**
I don't think its currently possible to use gpt4f's API (or any api-wrappers either, like OpenWebUI's API wrapper) to do `completions` for real-time code generation or inline editing. Applications like continue.dev are unable to work with the models, despite there being ones like qwen-coder.

**Describe the solution you'd like**
A `completions` (not /chat/completions, as it seems to give garbled results compared to what plugins like continue expect) endpoint implementation for the models that support it?

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by hlohaus** [comment]
The `/completions` API is deprecated.  All users should transition to `/chat/completions`.  However, tool calling is not currently supported due to limitations in our provider's capabilities.

**Comment by kerichdev** [comment]
Oh, alright, that makes sense - thanks!
