### ISSUE TITLE
SSL verify certificate failed with almost all providers

### ISSUE THREAD

**Issue by Miliardi** [xtekky/gpt4free#2471]
1) Pizzagpt

from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.pizzagpt.it:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

2) RubicsAI

from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host rubiks.ai:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

3) AirForce

from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.airforce:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')

Code

from g4f.client import Client
from g4f.Provider import Pizzagpt

client = Client(provider=Pizzagpt)
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[{"role": "user", "content": "What LLM model are you?"}],
    # Add any other necessary parameters
)
print(response.choices[0].message.content)

**Comment by Miliardi** [comment]
python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"

OpenSSL 3.0.13 30 Jan 2024

**Comment by Ggre55** [comment]
yeah thats ur problem not a bug dude do more researches about ssl crap i hate when i have to deal with that esspecially on outdated linux distro like the nightmare centos

**Comment by Miliardi** [comment]
🤝

**Comment by hlohaus** [comment]
This is my hack for windows:

```
import ssl
import certifi
from functools import partial

ssl.default_ca_certs = certifi.where()
ssl.create_default_context = partial(
    ssl.create_default_context,
    cafile=certifi.where()
)
```
I use certifi
