### ISSUE TITLE
add o1 model in OpenaiChat Provider

### ISSUE THREAD

**Issue by The2Alert** [xtekky/gpt4free#2472]
![Screenshot 2024-12-10 210740](https://github.com/user-attachments/assets/f67ff6a3-15b9-455e-a5c6-beea457a826f)
![Screenshot 2024-12-10 210744](https://github.com/user-attachments/assets/43dd3813-747b-4f34-8f09-d262eacc1c97)

**Comment by The2Alert** [comment]
@xtekky @hlohaus

**Comment by hlohaus** [comment]
Sending multiple images to Gemini has no effect:
#2478 2478
