### ISSUE TITLE
Rate limit reached in OpenaiChat Provider

### ISSUE THREAD

**Issue by The2Alert** [xtekky/gpt4free#2474]
**gpt-4o Error**
g4f.errors.RateLimitError: Response 429: Rate limit reached

**o1-mini Error**
ERROR:g4f.api:Response 403: {"detail":"Unusual activity has been detected from your device. Try again later. (8eff8e2a0e58bf16-WAW)"}

**Version**
0.3.9.1

**GUI**
It works in the GUI, but not through the API.

**Comment by The2Alert** [comment]
@xtekky @hlohaus

**Comment by hlohaus** [comment]
Hey, cut it out with the spam. I was trying to fix things, but now...
