### ISSUE TITLE
Concurrent Session / User handling .

### ISSUE THREAD

**Issue by gr8rehanna** [xtekky/gpt4free#2476]
- Uses same session for each user, does not remember past chats.
- using any model,  it does create session for each chat.

**Bug description**
Well i am not sure how will this work. But this is not  a big.

So we use docker and using GUI we can create multiple chats i.e sessions.
So it keeps a track of session and also remembers some of the info i.e
If i say: Hey remember my name is jack 
Then i ask, Who am i ? :>> Reponse: You are jack 

Perfect.

Now as i was create a python based api, simple GUI using flask.
So i.e 2 users chatting at same time, it does not create multiple session/chats for seperate users,
Also if reply to each message as new/fresh chat and dost not use session/hostroy.

So here if i say: Hey remember my name is Maria, 
Response: Ok i will remmeber you name is Maria.

Again..
Hey, What is my name is just told you.
Response: Sorry i cant recall your last message, tell me your name i will remmeber.

Example: code

```
async def get_ai_response():
        response = ai_client.chat.completions.create(
            model=AI_MODEL,
            messages=[{"role": "user", "content": user_input}]
        )
        return response.choices[0].message.content
```

In flash we do get some parameters in headers.
We can have cookies, session name i.e: session21 etc etc.

So you can help me what addational parameters we have pass after  model=AI_MODEL, 
or in messages

Thanks.

**Comment by gr8rehanna** [comment]
Anyone here? 

Who can help me to to get working?

**Comment by manatlan** [comment]
To keep "the context" between multiple consequents calls ... you should enrich the context : the list of "messages".
Each textual exchanges should be in the list messages : everything you send, and everything that you receive !
It's the only way to keep the context !

**Comment by gr8rehanna** [comment]
Yes that does work.
I was thinking if we can have a chatid session id etc insetad of using chat history and sending emmm..
EMMM, thanks btw.

**Comment by hlohaus** [comment]
There is also a conversion in some providers. You have to use stream=True and then you can enable it with return_conversion=True. The first response in the stream is then a Conversion object isinstance(chunk, BaseConversion).
You can see a example the backend or api server.py.

**Comment by gr8rehanna** [comment]
@hlohaus  Thanks, Well i dont know about this.

Also i tried backend-api aswell that is different from api.
Anyways thanks for help now u can close this thread. 😄
