### ISSUE TITLE
Permission error in image generation

### ISSUE THREAD

**Issue by masuriii** [xtekky/gpt4free#2477]
when i try to generate image i get en error
![image](https://github.com/user-attachments/assets/828a4528-4323-4996-b616-38f9d76738e6)

i use docker container

**Comment by masuriii** [comment]
@hlohaus i try to run docker from root with id 0
i need to create another user?

**Comment by hlohaus** [comment]
Hey @masuriii, that Dockerfile uses user ID 1000, so you should run it as that user too.  Otherwise, don't mount the images and cookies directories in your docker-compose file or your docker run command.
