### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by superturbik** [xtekky/gpt4free#2483]
Code:
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

g4f.debug.logging = True

response = g4f.ChatCompletion.create(
        model="gpt-4",
        messages=[{"role": "user", "content": 'Hello!'}],
        provider=g4f.Provider.OpenaiChat)

print(response)

cmd:
Using OpenaiChat provider and gpt-4 model
Arkose: False
Proofofwork: gAAAAABwQ8Lk...
AccessToken: False
Retry: Error 403: {"detail":"Unusual activity has been detected from your device. Try again later. (8f201bf85d609730-FRA)"}

Versions:
Python 3.11.9
g4f==0.3.9.2

Location:  Germany

How can I solve this problem?

**Comment by Arken1xs** [comment]
@superturbik hello, your issue was already mentioned here:
#2474 
Please, check other issues before creating yours to avoid the duplicating of issues and spam; be patient and wait until the issue os fixed.

**Comment by superturbik** [comment]
> @superturbik hello, your issue was already mentioned here: #2474 Please, check other issues before creating yours to avoid the duplicating of issues and spam; be patient and wait until the issue is fixed.

Oh, sorry. Thank you for information
