### ISSUE TITLE
forefront error (try and except)

### ISSUE THREAD

**Issue by AvenCores** [xtekky/gpt4free#251]
https://github.com/xtekky/gpt4free/blob/main/forefront/__init__.py

![image](https://user-images.githubusercontent.com/64781822/235178483-c6e487c8-ca10-472b-b8f0-7cf594a38d59.png)
(venv) avencores@rosa2021 ~/Загрузки/gpt4free $ python -V
Python 3.8.13

**on lines 42 and 45 you need to remove one space**
![image](https://user-images.githubusercontent.com/64781822/235179040-21c230e5-12ff-4dfb-acb0-1c1bdf0ae46b.png)

**Comment by xtekky** [comment]
i got a takedown request so we'll see, stick to other services for now
