### ISSUE TITLE
I am required to auth, what is this?

### ISSUE THREAD

**Issue by Ddtester5** [xtekky/gpt4free#2512]
//// My code ////
import OpenAI from "openai";

const client = new OpenAI({
  apiKey: "",
  baseURL: "https://effective-waffle-g4797744qxq52wvjv-1337.app.github.dev/v1",
});
const hi = async () => {
  const chatCompletion = await client.chat.completions.create({
    messages: [{ role: "user", content: "Say this is a test" }],
    model: "gpt-4",
  });
  console.log(chatCompletion);
};

hi();
//// Console Response ////
      return new AuthenticationError(status, error, message, headers);
             ^

AuthenticationError: 401 status code (no body)
    at Function.generate (/workspaces/NextTest/parse-test/node_modules/openai/src/error.ts:76:14)
    at OpenAI.makeStatusError (/workspaces/NextTest/parse-test/node_modules/openai/src/core.ts:435:21)
    at OpenAI.makeRequest (/workspaces/NextTest/parse-test/node_modules/openai/src/core.ts:499:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hi (/workspaces/NextTest/parse-test/parse_fn/utils/openai/translate_and_untc.ts:8:26) {
  status: 401,
  headers: {
    connection: 'keep-alive',
    'content-length': '0',
    date: 'Thu, 26 Dec 2024 16:27:53 GMT',
    'ratelimit-limit': 'HttpRequestRatePerPort:1500/m',
    'ratelimit-remaining': 'HttpRequestRatePerPort:1498',
    'ratelimit-reset': 'HttpRequestRatePerPort:31s',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    'vssaas-request-id': 'd5112eb0-6673-4d25-b8ed-99736101aaf4',
    'www-authenticate': 'tunnel',
    'x-content-type-options': 'nosniff',
    'x-served-by': 'tunnels-prod-rel-euw-v3-cluster'
  },
  request_id: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}

Node.js v20.17.0
////
Help me  please , where i need to auth ? 🥺
////

**Comment by hlohaus** [comment]
'www-authenticate': 'tunnel',

Maybe for your Development System. Not for G4F.

@Ddtester5
