### ISSUE TITLE
Microsoft Designer cookie

### ISSUE THREAD

**Issue by shizamuru-dev** [xtekky/gpt4free#2513]
How to get "_U" cookie?

**Comment by hlohaus** [comment]
Browser developer tools provide access to current page cookies; alternatively, browser extensions offer the same functionality.  Numerous online tutorials detail this process. @shizamuru-dev

**Comment by shizamuru-dev** [comment]
Here I disagree with you, all the information is reduced to a couple of issues on the github and irrelevant articles. Although I put the wrong question... The question was not what to get it through, but what is "_U cookie"? If you just log in to Microsoft Designer or Bign Chat, you won’t find it...  I was able to get it by going from here - https://packagist.org/packages/maximerenou/bing-ai may be useful to someone
