### ISSUE TITLE
ForeFront stranges 

### ISSUE THREAD

**Issue by DimasRulit** [xtekky/gpt4free#256]
In general, I used ForeFront. At each launch, a token is generated based on the created account. I wrote a While loop, the program waits for input and then should get a response. It only works the first time, then I get an empty response.

````
import forefront

token = forefront.Account.create(logging=False)




while True:
    txt = input('YOU: ')
    if txt == 'exit':
        break
    for response in forefront.StreamingCompletion.create(token = token,
        prompt = txt, model='gpt-4'):
        
        print(response.completion.choices[0].text, end = '')
    print("")
    print("")
````
    
    

![image](https://user-images.githubusercontent.com/40802556/235221533-210c9986-780f-4d81-8c28-3aa82b90304e.png)

**Comment by DimasRulit** [comment]
![image](https://user-images.githubusercontent.com/40802556/235224091-77dcd519-7578-44de-87d9-045794c16617.png)


And for now, i can start again, and i see this:

**Comment by wingeva1986** [comment]
same problem

**Comment by xtekky** [comment]
i got a takedown request so we'll see, stick to other services for now
