### ISSUE TITLE
integration with autogpt ?

### ISSUE THREAD

**Issue by glut410** [xtekky/gpt4free#258]
fees consumed on autogpt can run ur money out. chances are that gpt4free would be a money rescuer.

**Comment by xtekky** [comment]
yeah, working on this, join the discord server as I dont know what will happen to this repo

**Comment by glut410** [comment]
just found autogpt tends to depend on functions that 'openai' gives like Embedding, Image, etc.
apparently, Embedding is a main problem.
it implies there is a package required to support these kinds of functions.
so my idea is to use langchain with huggingface to do embedding works.
but it might be a burden for gpu to run the model from huggingface, although running it on colab can be a solution, but it does exist some limits.
is there any chances to reverse the embedding apis? cuz this way will fix both problems.

**Comment by thanhtoan1196** [comment]
any updates?
