### ISSUE TITLE
this is highly illegal

### ISSUE THREAD

**Issue by python-nerd-3** [xtekky/gpt4free#264]
you can't just take gpt's code and redistribute it for free of course the legal team is going to get you
you deserve to be imprisoned

**Comment by felphhh** [comment]
What a cuck

**Comment by python-nerd-3** [comment]
oh i'm sorry

**Comment by Plaba** [comment]
Do you even understand how this project works?

**Comment by python-nerd-3** [comment]
...i'm sorry i guess it got taken down by a legal team i apologize if i misunderstood

**Comment by lauralex** [comment]
troll xD

**Comment by LukeSaward1** [comment]
You are such a fucking idiot.
"i see this as illegal so I'm gonna complain on github"
If it's illegal why is `chatbot.sex` still up?
Dickhead.

**Comment by lauralex** [comment]
He's just trolling, check his profile

**Comment by LukeSaward1** [comment]
He's a roblox player, idk what I expected tbh

**Comment by xtekky** [comment]
bro's trolling lmfao
