### ISSUE TITLE
An error occurred: 'dict' object has no attribute 'text'.

### ISSUE THREAD

**Issue by OPbjO** [xtekky/gpt4free#271]
![微信截图_20230429124216](https://user-images.githubusercontent.com/40695047/235283917-54b5e33b-6921-456f-a11f-67751c5389b2.png)
An error occurred: 'dict' object has no attribute 'text'. Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by OPbjO** [comment]
env: VMware centOS7 docker

**Comment by GenifeUA** [comment]
Same

**Comment by teslashibe** [comment]
+1

**Comment by nongfu9woo** [comment]
+1

**Comment by cckuailong** [comment]
This pr has solved it. Please wait for merge.
