### ISSUE TITLE
cloudflare issue

### ISSUE THREAD

**Issue by kemier** [xtekky/gpt4free#273]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=how+to+install+k8s+cluster+version%28v1.24.0%29+using+kubeadm%3F%0A&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=8f26a3de-476d-4a00-9b37-394e6e180401&chat=%5B%5D": dial tcp 199.59.148.7:443: i/o timeout (Client.Timeout exceeded while awaiting headers). Please make sure you are using a valid cloudflare clearance token and user agent.

complain about this, how to avoid it, thanks!

**Comment by tatlilimon** [comment]
I got the same error as you.
![image](https://user-images.githubusercontent.com/43828285/235293560-2fbc1659-54b4-4622-a9db-451a2317f2c5.png)

**Comment by beggiatom** [comment]
Same here
![image](https://user-images.githubusercontent.com/8978624/235293725-8d1c9dc2-13cf-4fbf-b640-b462d79fc733.png)

**Comment by Maddaxman** [comment]
Is it my usage method that's causing the same problem?

**Comment by beggiatom** [comment]
I believe it’s the same error mentioned in issue #271

**Comment by maxens-git** [comment]
It is the same for me

**Comment by tatlilimon** [comment]
The problem was fixed afet this  [PR](https://github.com/xtekky/gpt4free/pulls?q=is%3Apr+is%3Aclosed)

**Comment by tatlilimon** [comment]
The problem was fixed after this [PR](https://github.com/xtekky/gpt4free/pull/276)

**Comment by 6vision** [comment]
not yet，same error also
![image](https://user-images.githubusercontent.com/38057450/235312644-8e5c4db9-1fd5-418f-9999-bf9a1ffc1199.png)

**Comment by xtekky** [comment]
please redownload repository and make sure your ip is not flagged by you.com
