### ISSUE TITLE
Error on the gui while trying to get a response

### ISSUE THREAD

**Issue by makarbaderko** [xtekky/gpt4free#277]
I've downloaded and set up everything as it has been said in the README file. For every response I get such an error:
An error occurred: 'dict' object has no attribute 'text'. Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by niklasbaranski** [comment]
+1

**Comment by Snoft** [comment]
+1

**Comment by Maddaxman** [comment]
+1 same

**Comment by xtekky** [comment]
should be updated
