### ISSUE TITLE
An error occurred: failed to do request:

### ISSUE THREAD

**Issue by Maddaxman** [xtekky/gpt4free#279]
I have already done a git pull for the latest version, but I am still getting an error. How can I solve this?

<img width="798" alt="image" src="https://user-images.githubusercontent.com/31379908/235304085-abb696e0-65e4-4be7-9d54-ce7e7d69cf36.png">

**Comment by agang-php** [comment]
i have the same problem

**Comment by FrankDiao** [comment]
You need to set the proxy here：`gpt4free.you.Completion.create`
Like this：
<img width="451" alt="image" src="https://user-images.githubusercontent.com/37222117/235345411-72658c21-3105-4ed0-b5f0-4e3a5d63cf49.png">

**Comment by QKJIN** [comment]
Yes. It can work when I added the proxy(tips: remember the port is your agent port to outside which maybe not 7890). Thank you very much. @FrankDiao

**Comment by elven2016** [comment]
> You need to set the proxy here：`gpt4free.you.Completion.create` Like this： <img alt="image" width="451" src="https://user-images.githubusercontent.com/37222117/235345411-72658c21-3105-4ed0-b5f0-4e3a5d63cf49.png">

this works，thanks very much
