### ISSUE TITLE
chat.chatbot.sex dont support GPT-4？

### ISSUE THREAD

**Issue by 6vision** [xtekky/gpt4free#286]
although i choose the gpt-4 model，the answer seems like come from gpt3.5？
![image](https://user-images.githubusercontent.com/38057450/235313319-e6e1ea47-a50b-4506-ae0e-f90c48b2fbc2.png)

**Comment by Maddaxman** [comment]
yes,don't support

**Comment by NSbuilder** [comment]
It's supposed to be gpt4 of you choose so. The response also seems gpt 4

**Comment by TheK0tYaRa** [comment]
Did you start the conversation with gpt-4 ?

**Comment by 6vision** [comment]
> 

yes，I did.as u can see, I have labeled at the bottom of the picture.

**Comment by 6vision** [comment]
> Did you start the conversation with gpt-4 ?

yes，I did.as u can see, I have labeled at the bottom of the picture

**Comment by TheK0tYaRa** [comment]
> I have labeled at the bottom of the picture

The GPT switch is not disabled after you begin the chatting so that's why i'm asking.

**Comment by 6vision** [comment]
> > I have labeled at the bottom of the picture
> 
> The GPT switch is not disabled after you begin the chatting so that's why i'm asking.

so how to use gpt4 correctly？
