### ISSUE TITLE
Takedown request from Writesonic

### ISSUE THREAD

**Issue by samanyougarg** [xtekky/gpt4free#290]
I am the founder and legal representative of Writesonic. It has come to our attention that your project has made numerous unauthorized requests to our API, significantly increasing operational costs. Consequently, this has forced us to discontinue API access for our free trial users, adversely impacting our ability to serve our genuine clientele.

We demand that you immediately cease and desist from all utilization of Writesonic's API in your project and remove any Writesonic-related content, data, or code from your repository. Failure to comply with this demand within 1 day will leave us with no option but to pursue legal action against you, including, but not limited to, seeking injunctive relief and monetary damages.

This serves as a formal notice and a final opportunity for you to resolve this matter amicably. We reserve all rights to seek appropriate legal remedies available under the law to protect our intellectual property rights and interests.

In the GitHub issue below, please confirm that you have complied with our demand by removing all Writesonic-related materials from your repository and ceasing any further unauthorized use of our API.

We look forward to your prompt cooperation in this matter.

**Comment by xtekky** [comment]
Hi, please provide some proof, and sorry I copy pasted some requests from devtools and posted them here

**Comment by DanielShemesh** [comment]
Could you please clarify which laws or terms of service this project has allegedly violated? More information on this matter would be appreciated to better understand the situation.

**Comment by xtekky** [comment]
closing as code was removed
