### ISSUE TITLE
Add GitStyle guidence 

### ISSUE THREAD

**Issue by valerii-chirkov** [xtekky/gpt4free#291]
Although the repository has gained popularity, navigating through its commits is difficult due to the absence of clear git-style conventions.
I recommend that the maintainer create a checklist to ensure a well-organized commit history.

[Example](https://gist.github.com/ericavonb/3c79e5035567c8ef3267)

**Comment by xtekky** [comment]
Hi, didnt really get to do it, had a lot of trouble and then also the takedown...
