### ISSUE TITLE
Error: Unable to fetch the response, Please try again.

### ISSUE THREAD

**Issue by MarkVorkosigan** [xtekky/gpt4free#312]
The only output is "Unable to fetch the response, Please try again".

**Comment by n0rb33r7** [comment]
same, stopped working approximately an hour ago

**Comment by 6vision** [comment]
+1

**Comment by Ron-Caster** [comment]
+1

Just blinks doesn't fetching any reply.

**Comment by xtekky** [comment]
hi, please give more details

**Comment by zgdeng** [comment]
![image](https://user-images.githubusercontent.com/44643726/235351171-85ce8822-f8f8-4847-8524-0616d991899d.png)

**Comment by zgdeng** [comment]
![image](https://user-images.githubusercontent.com/44643726/235351624-db090e2f-4d39-452b-ba39-bc998d20fd3b.png)

**Comment by n0rb33r7** [comment]
> hi, please give more details

It has started working again. Earlier, when I was attempting to retrieve data from https://chat.chatbot.sex, it would get stuck, but now when I request the data, it runs smoothly

**Comment by xtekky** [comment]
Hi, please redownload the repo there has been a lot of updates

**Comment by zgdeng** [comment]
![image](https://user-images.githubusercontent.com/44643726/235354064-9692293d-a89c-4288-8077-f948f125f9ca.png)
![image](https://user-images.githubusercontent.com/44643726/235354141-d4e9162f-7b8a-42c7-8533-6cd58851998e.png)

Thanks for the quick updates, I have pulled the latest changes, but seems the same error

**Comment by slotix** [comment]
What is the maximum length limit for prompts? It appears that errors occur with prompts that exceed this maximum length.

**Comment by Dymeth** [comment]
> Hi, please redownload the repo there has been a lot of updates

The problem problem is still present. There are no any messages in console

**Comment by artempavlov** [comment]
Hi! Same issue here. Still happening after redownloading the repo.

**Comment by akimmmq** [comment]
I've turned off VPN. For me, it solved my problem.
Also I cleared my cache, turned off adblocker.

**Comment by zgdeng** [comment]
After the VPN turned off, it shows me another error:
![image](https://user-images.githubusercontent.com/44643726/235393585-5a529eec-6cd8-499e-90c4-04e25acd3181.png)

**Comment by zgdeng** [comment]
Where can I get the token?
![image](https://user-images.githubusercontent.com/44643726/235438599-23b9b856-2b86-4f8d-a121-53888b9348b6.png)

**Comment by ZzZombo** [comment]
Please reopen. Doesn't work for me still.
