### ISSUE TITLE
unsupported syntax of a higher version of Python

### ISSUE THREAD

**Issue by wingeva1986** [xtekky/gpt4free#317]
File "D:\Python\openai-gpt4-main\gpt4free\quora\__init__.py", line 390
    if (cookie_file := Path(self.cookie_path)).exists():

 File "D:\Python\openai-gpt4-main\gpt4free\quora\__init__.py", line 461
   /,
   ^

    def create_bot(
        self,
        name: str,
        /,
        prompt: str = '',
        base_model: str = 'ChatGPT',
        description: str = '',
    ) -> None:

**Comment by sudouser777** [comment]
@wingeva1986 which version of python are you using?

**Comment by wingeva1986** [comment]
> @wingeva1986 which version of python are you using?

3.7

**Comment by sudouser777** [comment]
@wingeva1986 above syntax will work from 3.8
