### ISSUE TITLE
An error occurred: failed to do request

### ISSUE THREAD

**Issue by religou** [xtekky/gpt4free#334]
Hi:

When I input the question and click the 'thinking' button, the running icon is shown. But the result is failed and information is '**An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E4%BD%A0%E6%98%AF%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9E%8B&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=13421084-53f8-4410-bebc-f6c6f37736a7&chat=%5B%5D": dial tcp 199.96.58.157:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Please make sure you are using a valid cloudflare clearance token and user agent.**' Maybe i located in China and open the VPN. But i access you.com directly , it's success. This is confused~

**Comment by chunqiushi** [comment]
都一样

**Comment by Civitasv** [comment]
Use **streamlit_chat_app** instead of **streamlit_app**, the former supports proxy setting.

**Comment by religou** [comment]
@Civitasv

**Comment by Civitasv** [comment]
You should enter into `gui` folder and execute `streamlit run streamlit_chat_app.py`.

**Comment by SuperMalow** [comment]
The answer I got was:
Unable to fetch the response, please try again.

**Comment by religou** [comment]
I have solve this problem. First, you have installed all packages. Then you need to  modify the 'gpt4free/you/__init__.py' file. The content of modified is coming.
![image](https://user-images.githubusercontent.com/34397510/235550593-757d8e31-dc94-4998-aea9-e861e5578015.png)
Last, enter 'streamlit run streamlit_app.py' command in your terminal，terminal will show 'You can now view your Streamlit app in your browser.'. this is success!!!

**Comment by PHI6kai** [comment]
想问一下，用WSL的需要配置IP吗
