### ISSUE TITLE
AttributeError: 'ForeFrontResponse' object has no attribute 'completion'

### ISSUE THREAD

**Issue by cabfile** [xtekky/gpt4free#340]
tried the forefront example
im using python 3.8.10

**Comment by sagadav** [comment]
#335 fixed
it's just a typo

**Comment by phamxtien** [comment]
I get error as bellow:

forefront/__init__.py", line 76, in create
    token = response.json()['response']['sessions'][0]['last_active_token']['jwt']
TypeError: 'NoneType' object is not subscriptable

**Comment by xSebo** [comment]
I was having the same issue, try using the example found at:
https://github.com/xtekky/gpt4free/tree/main/gpt4free
Instead, this worked for me

**Comment by phamxtien** [comment]
> I was having the same issue, try using the example found at:
> https://github.com/xtekky/gpt4free/tree/main/gpt4free
> Instead, this worked for me
> 
> ```python
> import gpt4free
> from gpt4free import Provider, forefront
> 
> token=forefront.Account.create(logging=False)
> prompt = "Hello world"
> response = gpt4free.Completion.create(
>     Provider.ForeFront, prompt=prompt, model='gpt-4', token=token
> )
> print(response)
> ```

Still get the same error :)
