### ISSUE TITLE
Unable to fetch the response (also, no images)

### ISSUE THREAD

**Issue by EasternPA** [xtekky/gpt4free#344]
#312 may have been closed prematurely. I just cloned the repo a few minutes ago and built it using docker compose. Not only do I not get images on the web page, but I get the same error reported in 312. I tried both the docker-compose.yml and docker-compose.yaml (why are there two, and why are they different?)

Edit: I also get the same error on the console others have mentioned about not finding ffmpeg or avconv.

Thanks!

![gpt4free not working](https://user-images.githubusercontent.com/713544/235459422-67c77638-5816-4218-af15-248096edfbad.png)

**Comment by 1220515996** [comment]
me too

**Comment by EasternPA** [comment]
> me too

Which of the three issues? Cannot fetch, no images, or missing ffmpeg and avconv?

**Comment by EasternPA** [comment]
> Cannot fetch, missing ffmpeg and avconv

So you have images on the web page? None of my images are loading. Did you use the docker build?

**Comment by 1220515996** [comment]
just docker-compose

**Comment by EasternPA** [comment]
I added 'ffmpeg' to the apt command in Dockerfile. That corrected the error in the logs about not finding ffmpeg or avcon. I still don't have any images on the web page, and it still can't fetch any results.

I am running this behind pi-hole so I'm wondering if that's the problem. Someone on #312 mentioned shutting off their ad blocker and deleting cookies.

**Comment by EasternPA** [comment]
> I added 'ffmpeg' to the apt command in Dockerfile. That corrected the error in the logs about not finding ffmpeg or avcon. I still don't have any images on the web page, and it still can't fetch any results.
> 
> I am running this behind pi-hole so I'm wondering if that's the problem. Someone on #312 mentioned shutting off their ad blocker and deleting cookies.

I moved it to a Cloudflare tunnel and nothing changed. No images load and results cannot be fetched.

**Comment by EasternPA** [comment]
Update: deleted and started over this morning with a new git clone. Followed the steps to build the docker image by hand and run it. I now get results, but still don't have the icon images. Making progress.

**Comment by Ace167** [comment]
> Update: deleted and started over this morning with a new git clone. Followed the steps to build the docker image by hand and run it. I now get results, but still don't have the icon images. Making progress.
> 
> Update2: Switched back to docker compose and the same issues that caused me to open this issue persist. No images and no results.
> 
> Big update: The results vary by prompt. I am getting answers for "how do you fly a plane" and "how heavy is a typical freight train" but I am getting the error shown in when I opened this issue for "how do severe weather outbreaks begin?"

Same here

**Comment by EasternPA** [comment]
> > Big update: The results vary by prompt. I am getting answers for "how do you fly a plane" and "how heavy is a typical freight train" but I am getting the error shown in when I opened this issue for "how do severe weather outbreaks begin?"
> 
> Same here

I think it's time to close this. It looks like the project is closing and the resolution to this issue is much bigger than I thought. If only some prompts return this error but others work fine, I'm not going to have the time or skill to dig into it any further.
