### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Bennett-Fourr** [xtekky/gpt4free#361]
Traceback (most recent call last):
  File "C:\Users\user\gpt4free\streamlit_app.py", line 6, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'

I tryed pip install streamlit. This did not help.

**Comment by kamranhaq21** [comment]
add python\scripts in your env path to access streamlit.exe or call it directly by providing a complete path or C:\Python\Scripts\streamlit.exe  run streamlit_app.py
