### ISSUE TITLE
An error occurred: failed to do request

### ISSUE THREAD

**Issue by 6897889** [xtekky/gpt4free#365]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=1%2B1&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=6032566b-7852-4c3f-860f-4655e7b2243a&chat=%5B%5D": dial tcp 199.59.148.102:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Please make sure you are using a valid cloudflare clearance token and user agent.
![image](https://user-images.githubusercontent.com/31813628/235567015-aa863bee-6f78-47a4-8a96-b4033d845b44.png)

**Comment by 6897889** [comment]
![image](https://user-images.githubusercontent.com/31813628/235571991-61f2e53c-be79-45d1-a3e4-a0145b9d7d00.png)

10809 choose youself 
10809选择你自己的端口！

**Comment by Micah365** [comment]
> ![image](https://user-images.githubusercontent.com/31813628/235571991-61f2e53c-be79-45d1-a3e4-a0145b9d7d00.png)
> 
> 10809 choose youself 10809选择你自己的端口！

你好，这个“IP:端口”指的是什么？ 代理吗？ 什么类型的代理？

**Comment by glovebx** [comment]
> 

你代理的http端口

**Comment by xtekky** [comment]
fixed with retry logic normally
