### ISSUE TITLE
How to use other mods

### ISSUE THREAD

**Issue by zy-187** [xtekky/gpt4free#370]
Why do I get errors importing other models' modules, but not importing the you module

**Comment by sudouser777** [comment]
Can you post the error you are getting, also included the code to reproduce the issue

**Comment by zy-187** [comment]
> Can you post the error you are getting, also included the code to reproduce the issue

<img width="529" alt="1" src="https://user-images.githubusercontent.com/113878082/235614513-7a542387-10d0-4bc0-83b3-6a08c62c940b.png">
<img width="578" alt="2" src="https://user-images.githubusercontent.com/113878082/235614539-e2a860e5-1b6b-4aa6-b518-a1a34ad45287.png">

**Comment by sudouser777** [comment]
sometimes IDE may not recognise modules properly, Can you run your code and share the error.

**Comment by sudouser777** [comment]
Can you confirm, If you are using the latest code from the master branch.

**Comment by Micah365** [comment]
me too

**Comment by 1449362433** [comment]
> 括

除了you模型还有其他的模型吗

**Comment by ajh123** [comment]
In the last screenshot it says ` "theb": Unknown Word.  cSpell`. That isn't an error, its just the spell check extension. If there was an error then there would be a red line underneath instead.
