### ISSUE TITLE
发生错误：无法执行请求：获取“https://you.com/api/streamingSearch?q=%E4%BD%A0%E6%98%AF%E8%B0%81&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=6b01698c-8b27-44aa-994e-ff807feec13c&chat=%5B%5D“：拨打TCP 69.171.242.11：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或建立的连接失败，因为连接的主机无法响应。请确保您使用的是有效的 cloudflare 清除令牌和用户代理。

### ISSUE THREAD

**Issue by anyi61** [xtekky/gpt4free#376]
发生错误：无法执行请求：获取“https://you.com/api/streamingSearch?q=%E4%BD%A0%E6%98%AF%E8%B0%81&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=6b01698c-8b27-44aa-994e-ff807feec13c&chat=%5B%5D“：拨打TCP 69.171.242.11：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或建立的连接失败，因为连接的主机无法响应。请确保您使用的是有效的 cloudflare 清除令牌和用户代理。

**Comment by lori-kuo** [comment]
+1

**Comment by GMIS** [comment]
+1

**Comment by elven2016** [comment]
the same , how do you resolve it ?

**Comment by AJXGY** [comment]
+1

**Comment by HPC-NEAU** [comment]
+1

**Comment by Saix7** [comment]
+1

**Comment by wmf508** [comment]
same issue

**Comment by feitengbing2014** [comment]
check if you can access you.com in your browser, if not, add a valid proxy to your _init_.py file under you folder
<img width="874" alt="image" src="https://user-images.githubusercontent.com/6993521/236100234-dfd5716c-e3e8-417b-882c-f202ba8b7bed.png">

**Comment by Wigiesen** [comment]
me too

**Comment by xtekky** [comment]
use proxy, added retry logic aswell
