### ISSUE TITLE
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

### ISSUE THREAD

**Issue by anyi61** [xtekky/gpt4free#377]
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by HelloMorningStar** [comment]
sudo apt install ffmpeg

**Comment by Nyantad** [comment]
Same problem for me

**Comment by tsenkeo** [comment]
тоже не робит, сделайте плиз кто-нибудь

**Comment by SumitBando** [comment]
On a Ubuntu machine, the solution is to run:
```bash
sudo apt install ffmpeg
```

Should be similar for Docker.

**Comment by lex095** [comment]
pip install ffmpeg - Installed ffmpeg in python
streamlit run /gptfree/streamlit_app.py

**Comment by Nyantad** [comment]
> pip install ffmpeg - Installed ffmpeg in python streamlit run /gptfree/streamlit_app.py

thx it work for me

**Comment by zhuxt2015** [comment]
I'm already installed ffmpeg , it still reported error
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/13765310/236669690-9c0f578f-b0ea-4bf9-be14-4ad76fb0710c.png">

**Comment by univanxx** [comment]
`brew install ffmpeg` for macOS (and possibly Linux) helped me

**Comment by mafei100** [comment]
Go to ffmpeg official website to download the compiled ffmpeg, and then add the bin directory to the system environment variable, so this error will not be reported. However, asking questions on the web page still doesn't respond. Prompt "unable to fetch the response, please try again."

**Comment by mohamedibrahim95** [comment]
> Go to ffmpeg official website to download the compiled ffmpeg, and then add the bin directory to the system environment variable, so this error will not be reported. However, asking questions on the web page still doesn't respond. Prompt "unable to fetch the response, please try again."

I tried that method as well. Still didn't work
