### ISSUE TITLE
Request error

### ISSUE THREAD

**Issue by ITWho** [xtekky/gpt4free#378]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=hi&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=cc41e10f-99c7-4c36-9eb9-75b03e8233c5&chat=%5B%5D": dial tcp [2a03:2880:f11a:83:face:b00c:0:25de]:443: i/o timeout (Client.Timeout exceeded while awaiting headers). Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by liangddyy** [comment]
+1
