### ISSUE TITLE
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?

### ISSUE THREAD

**Issue by zhuqiyang** [xtekky/gpt4free#381]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E4%BD%BF%E7%94%A8golang%E5%86%99%E4%B8%80%E4%B8%AAwebserver&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=b8818001-99a8-4e63-b918-8d28c9608888&chat=%5B%5D": dial tcp 104.244.43.234:443: i/o timeout (Client.Timeout exceeded while awaiting headers). Please make sure you are using a valid cloudflare clearance token and user agent.

用docker跑的，在docker里设置代理或者在dockerfile中设置 ENV http_proxy=http://192.168.199.183:8118 ENV https_proxy=https://192.168.199.183:8118 都不行，跑docker的宿主机设置代理也不行，代理服务确定是没有问题的。

**Comment by zhuqiyang** [comment]
解决方法：
vim gpt4free/gpt4free/you/__init__.py

...
        proxy='192.168.199.183:8118'
        proxies = {'http': 'http://' + proxy, 'https': 'http://' + proxy} if proxy else {}
...

**Comment by paradoxgoo** [comment]
> 解决方法： 打开如下文件：
> 
> ```
> vim gpt4free/gpt4free/you/__init__.py
> ```
> 
> 编辑代码，添加proxy：
> 
> ```
>         proxy='192.168.199.1:8118'
>         proxies = {'http': 'http://' + proxy, 'https': 'http://' + proxy} if proxy else {}
> ```

出現了這個錯誤
An error occurred: execute_request() got an unexpected keyword argument 'proxies'. Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by Torres999** [comment]
添加了以下这段代码还是不行，和墙有关吗？
        proxy='192.168.199.1:8118'
        proxies = {'http': 'http://' + proxy, 'https': 'http://' + proxy} if proxy else {}

**Comment by paradoxgoo** [comment]
> 

我也是  添加了這段代碼，還是報錯

**Comment by agancqu** [comment]
> 添加了以下这段代码还是不行，和墙有关吗？ proxy='192.168.199.1:8118' proxies = {'http': 'http://' + proxy, 'https': 'http://' + proxy} if proxy else {}

你本地要能访问外网才行，本地的VPN代理服务器启动prox代理服务，一般是127.0.0.1:xxxx，其中端口号xxxx是可以本地VPN工具配置的端口号。IP+端口号配置好了，并且正常连接了翻墙VPN服务，添加的这行代码才有用。反正我测试是OK的：

<img width="557" alt="image" src="https://user-images.githubusercontent.com/3632705/236406268-158cafa0-afaa-4409-bb49-8680ef830a2e.png">

**Comment by git-guocc** [comment]
我是把docker-compose.yaml它注释的那两行给加上，改成clash的端口，然后clash开全局代理就可以了，但是原理不是很清楚

**Comment by git-guocc** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/81276451/236425909-82acf0ad-8a4b-4f82-9454-4858d056cb34.png">
这是gpt4吗？白搞了？

**Comment by WGXT** [comment]
> <img alt="image" width="620" src="https://user-images.githubusercontent.com/81276451/236425909-82acf0ad-8a4b-4f82-9454-4858d056cb34.png">
> 
> 这是gpt4吗？白搞了？

原来不是GPT4吗，那没必要搞了

**Comment by jiongjiongJOJO** [comment]
> <img alt="image" width="620" src="https://user-images.githubusercontent.com/81276451/236425909-82acf0ad-8a4b-4f82-9454-4858d056cb34.png">
> 
> 这是gpt4吗？白搞了？

麻烦看清楚[README.md](https://github.com/xtekky/gpt4free/blob/217d20d98d0fca0a7f6e82309b4568955e2119e3/README.md)

作者已经给了很多接口，你用的只是默认的，你不改就在这里乱说？

**Comment by lsxf** [comment]
> 解决方法： 打开如下文件：
> 
> ```
> vim gpt4free/gpt4free/you/__init__.py
> ```
> 
> 编辑代码，添加proxy：
> 
> ```
>         proxy='192.168.199.1:8118'
>         proxies = {'http': 'http://' + proxy, 'https': 'http://' + proxy} if proxy else {}
> ```

请问一下， vim gpt4free/gpt4free/you/__init__.py 这个路径是ssh上群晖还是要在docker里的容器里？
