### ISSUE TITLE
An error occurred: failed to do request: 

### ISSUE THREAD

**Issue by stoerry** [xtekky/gpt4free#384]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E8%AF%B7%E7%94%A8%E4%B8%AD%E6%96%87%E4%BA%A4%E6%B5%81%0A&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=ef3c2494-4df0-4289-b267-b8f24adbde03&chat=%5B%5D": dial tcp 128.242.245.93:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by zhengshihu** [comment]
the same error
