### ISSUE TITLE
save & reuse feature for poe.com accounts

### ISSUE THREAD

**Issue by DVerdeV** [xtekky/gpt4free#39]
First of all, I would like to thank you for the enormous effort to maintain this repository. I think they are very good solutions for using the latest models.

I don't know to what extent this is feasible/useful, but I have seen that the limit reset that applies for the use of GPT-4 on poe.com is a few hours (I think one day).

My question is this: wouldn't it be possible to save the accounts created in some kind of “pool” of accounts and when the daily limit is restored use them?

In this way we would be creating fewer accounts, and we would have immediate answers because it is not necessary to create it again (I don't know the expiration time of the token).

**Comment by xtekky** [comment]
alrady added this although not commented, cookies are in `quora/cookies.txt` and u can use them with `Account.load()`
I didnt test this feature enough so let me know if there are issues or something to improve @DVerdeV

**Comment by DVerdeV** [comment]
Great! Do you know if they expire?

**Comment by xtekky** [comment]
they should last for a long time but this is for me not an issue as i believe you should just create new ones, closing as I think this issue is resolved
