### ISSUE TITLE
ai.usesless.com

### ISSUE THREAD

**Issue by hzeyuan** [xtekky/gpt4free#394]
I am the developer of ai.usesless.com and perhaps we could offer our services in a more user-friendly way by providing specialized APIs.

The request frequency is already a bit too high now, which is not very good for a small personal development website

It was quite amusing and magical to discover my website featured in a repository that I have been following for some time now.

If anyone is interested, please feel free to reach out to me via the email address provided in my personal information.

**Comment by xtekky** [comment]
Hi, would you be able to contact me on discord ?
