### ISSUE TITLE
Forefront just stopped @bugfoo.com

### ISSUE THREAD

**Issue by bratisla** [xtekky/gpt4free#395]
So forefront wont let you register bugfoo.com emails anymore.

**Comment by zxy003512** [comment]
什么时候才能正常使用呀，显示Failed to create account!

**Comment by zxy003512** [comment]
> 因此，forefront 不会再让您注册 bugfoo.com 电子邮件。

您好，怎么样才能正常使用呢，显示Failed to create account!
