### ISSUE TITLE
An error occurred: failed to do request:

### ISSUE THREAD

**Issue by jiangyh1** [xtekky/gpt4free#396]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=Hello.&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=2cdd2534-148d-40d3-a3a5-d271d74fe556&chat=%5B%5D": dial tcp [2a03:2880:f126:83:face:b00c:0:25de]:443: i/o timeout (Client.Timeout exceeded while awaiting headers). Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by wmf508** [comment]
same issue

**Comment by Belissimo-T** [comment]
duplicates #384
