### ISSUE TITLE
ImportError: cannot import name 'quora' from 'gpt4free'

### ISSUE THREAD

**Issue by p1k0pan** [xtekky/gpt4free#398]
I have `pip install gpt4free` and tried to use poe

using Python: 3.8

-----
btw forefront is now `Failed to create account!`.

Does anyone have any clue?

**Comment by Azilone** [comment]
same here

**Comment by Filocava99** [comment]
Clone the repo locally and import the module from there, probably the pip package doesn't have the quora module

**Comment by francesco-plt** [comment]
> Clone the repo locally and import the module from there, probably the pip package doesn't have the quora module.
> 
> If you are using colab:
> 
> ```
> !git clone https://github.com/xtekky/gpt4free.git
> %cd gpt4free/
> !pip install -r requirements.txt
> 
> # import quora (poe) package
> from gpt4free import quora
> ```

```
Import "gpt4free" could not be resolved(reportMissingImports)
```
