### ISSUE TITLE
ModuleNotFoundError: No module named 'pypasser'

### ISSUE THREAD

**Issue by zangqiourun** [xtekky/gpt4free#399]
run streamlit run streamlit_app.py has an error
![1683106355323](https://user-images.githubusercontent.com/130052096/235880968-ac8390f1-6b1e-40d3-b701-57e8b0fbc578.png)
![1683106384271](https://user-images.githubusercontent.com/130052096/235881098-cf427feb-8bbb-47d2-87cf-3fed028994c3.png)

**Comment by DaleYan** [comment]
same

**Comment by Jeevaraz** [comment]
`pip3 install pypasser`
