### ISSUE TITLE
Ethics

### ISSUE THREAD

**Issue by gptlang** [xtekky/gpt4free#402]
You're going after a lot of smaller creators who can barely pay for the API. Can you try to reverse some bigger companies who actually have the funds to cover abuse?

**Comment by Anton293** [comment]
If you don't use it, the money won't carry over to the next month.

**Comment by taiyi747** [comment]
This question has been mentioned before, and I believe xtekky will arrange it properly. If it is a small studio or small creator, they can submit an issue request for deleting their site.
