### ISSUE TITLE
GPT4free GUI An error occurred: failed to do request:Get .......

### ISSUE THREAD

**Issue by Saix7** [xtekky/gpt4free#406]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E4%BD%A0%E5%A5%BD&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=7ebe3aac-e632-45a2-a3ba-ec756f20c882&chat=%5B%5D": dial tcp 69.63.176.59:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Please make sure you are using a valid cloudflare clearance token and user agent.

how to fix that the easy way plz step by step! thanks

**Comment by wmf508** [comment]
i have the same issue.

**Comment by wmf508** [comment]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E7%8E%B0%E5%9C%A8%E6%9C%89%E4%B8%A4%E4%B8%AA%E9%9D%9E%E5%B8%B8%E7%81%AB%E7%9A%84%E5%BC%80%E6%BA%90%E9%A1%B9%E7%9B%AE%EF%BC%9A%0A-+https%3A%2F%2Fgithub.com%2Fxtekky%2Fgpt4free%EF%BC%8C%E9%80%9A%E8%BF%87%E8%B0%83%E7%94%A8%E4%B8%8EopenAI%E6%9C%89%E5%90%88%E4%BD%9C%E7%9A%84%E7%BD%91%E7%AB%99%E7%9A%84api%E6%9D%A5%E5%AE%9E%E7%8E%B0%E5%85%8D%E8%B4%B9%E4%BD%BF%E7%94%A8gpt4%E7%9A%84%E5%8A%9F%E8%83%BD%E3%80%82%0A-+https%3A%2F%2Fgithub.com%2FSignificant-Gravitas%2FAuto-GPT%EF%BC%8C%E9%80%9A%E8%BF%87chatgpt+api%E8%83%BD%E8%AE%A9chatgpt%E9%80%9A%E8%BF%87%E8%87%AA%E5%8A%A8%E6%8B%86%E8%A7%A3%E4%BB%BB%E5%8A%A1%E3%80%81%E8%B0%83%E7%94%A8%E5%B7%A5%E5%85%B7%EF%BC%88%E7%BD%91%E7%BB%9C%E6%90%9C%E7%B4%A2%EF%BC%8C%E5%88%9B%E5%BB%BA%E6%96%87%E4%BB%B6%E7%AD%89%EF%BC%89%E3%80%81%E5%88%A9%E7%94%A8%E5%90%91%E9%87%8F%E6%95%B0%E6%8D%AE%E5%BA%93%E8%87%AA%E5%8A%A8%E5%AD%98%E5%82%A8%E9%95%BF%E6%9C%9F%E5%92%8C%E7%9F%AD%E6%9C%9F%E8%AE%B0%E5%BF%86%E6%9D%A5%E5%AE%8C%E6%88%90%E8%AE%BE%E7%BD%AE%E7%9A%84%E7%9B%AE%E6%A0%87%E4%BB%BB%E5%8A%A1%E3%80%82%0A%0A%E6%88%91%E7%8E%B0%E5%9C%A8%E5%B8%8C%E6%9C%9B%E8%83%BD%E9%80%9A%E8%BF%87%E5%8F%82%E8%80%83gpt4free%E9%A1%B9%E7%9B%AE%E7%9A%84%E5%AE%9E%E7%8E%B0%E6%96%B9%E6%B3%95%E6%9D%A5%E6%94%B9%E9%80%A0Auto-GPT%E9%A1%B9%E7%9B%AE%EF%BC%8C%E8%BE%BE%E5%88%B0%E5%85%8D%E8%B4%B9%E4%BD%BF%E7%94%A8Auto-GPT%E7%9A%84%E7%9B%AE%E7%9A%84%E3%80%82%E8%AF%B7%E9%97%AE%E6%80%8E%E4%B9%88%E5%81%9A%EF%BC%9F%E6%88%91%E5%8F%AF%E4%BB%A5%E4%B8%BA%E4%BD%A0%E6%8F%90%E4%BE%9B%E4%BB%BB%E4%BD%95%E6%9C%89%E5%85%B3%E4%BA%8E%E8%BF%99%E4%B8%A4%E4%B8%AA%E9%A1%B9%E7%9B%AE%E7%9A%84%E4%BF%A1%E6%81%AF%EF%BC%8C%E6%AF%94%E5%A6%82%E9%A1%B9%E7%9B%AE%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%EF%BC%8C%E6%96%87%E4%BB%B6%E7%9A%84%E5%86%85%E5%AE%B9%E7%AD%89%EF%BC%8C%E8%AF%B7%E4%BD%A0%E5%91%8A%E8%AF%89%E6%88%91%E9%9C%80%E8%A6%81%E4%B8%BA%E4%BD%A0%E6%8F%90%E4%BE%9B%E5%93%AA%E4%BA%9B%E4%BF%A1%E6%81%AF%EF%BC%9F%0A&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=25cc3939-ce3b-440f-8583-618eaf21e167&chat=%5B%5D": dial tcp 74.86.3.208:443: i/o timeout (Client.Timeout exceeded while awaiting headers). Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by hoppyzhu** [comment]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=HELLO&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=4b9ae82a-f901-499e-815d-3b5811d995e9&chat=%5B%5D": dial tcp 31.13.67.41:443: i/o timeout (Client.Timeout exceeded while awaiting headers). Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by cypggs** [comment]
i have the same issue.

**Comment by wqw547243068** [comment]
Me too ... 
> using a valid cloudflare clearance token and user agent

**Comment by ArlanCooper** [comment]
Me too, maybe openAI has already ban it ?

**Comment by ccccler** [comment]
Just like this prtscr . I have the same question ![image](https://user-images.githubusercontent.com/127079609/236159913-09d5e547-7718-426b-981f-d9913e06b95f.png)

**Comment by woshishenizkw** [comment]
I want to know how to solve this problem?

**Comment by paradoxgoo** [comment]
me too

**Comment by tb1over** [comment]
me too

**Comment by Pinyupen** [comment]
Me too
