### ISSUE TITLE
pip error while installing requirments.txt (using termux 32bit)

### ISSUE THREAD

**Issue by SecretGogeta** [xtekky/gpt4free#407]
pip3 install -r requirements.txt
Collecting https://github.com/AI-Yash/st-chat/archive/refs/pull/24/head.zip (from -r requirements.txt (line 12))
  Using cached https://github.com/AI-Yash/st-chat/archive/refs/pull/24/head.zip (5.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting websocket-client (from -r requirements.txt (line 1))
  Using cached websocket_client-1.5.1-py3-none-any.whl (55 kB)
Requirement already satisfied: requests in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (2.28.2)
Collecting tls-client (from -r requirements.txt (line 3))
  Using cached tls_client-0.2.1-py3-none-any.whl (35.2 MB)
Collecting pypasser (from -r requirements.txt (line 4))
  Using cached PyPasser-0.0.5.tar.gz (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting names (from -r requirements.txt (line 5))
  Using cached names-0.3.0.tar.gz (789 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: colorama in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (0.4.6)
Collecting curl_cffi (from -r requirements.txt (line 7))
  Using cached curl_cffi-0.5.5.tar.gz (27 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting streamlit==1.21.0 (from -r requirements.txt (line 8))
  Using cached streamlit-1.21.0-py2.py3-none-any.whl (9.7 MB)
Collecting selenium (from -r requirements.txt (line 9))
  Using cached selenium-4.9.0-py3-none-any.whl (6.5 MB)
Collecting fake-useragent (from -r requirements.txt (line 10))
  Using cached fake_useragent-1.1.3-py3-none-any.whl (50 kB)
Collecting twocaptcha (from -r requirements.txt (line 11))
  Using cached TwoCaptcha-0.0.1.tar.gz (2.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pydantic (from -r requirements.txt (line 13))
  Using cached pydantic-1.10.7-py3-none-any.whl (157 kB)
Collecting pymailtm (from -r requirements.txt (line 14))
  Using cached pymailtm-1.1.1-py3-none-any.whl (19 kB)
Collecting Levenshtein (from -r requirements.txt (line 15))
  Using cached Levenshtein-0.21.0.tar.gz (122 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Collecting cmake
        Using cached cmake-3.26.3.tar.gz (35 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: cmake
        Building wheel for cmake (pyproject.toml): started
        Building wheel for cmake (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cmake (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [34 lines of output]
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-u03v6pzo/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
                cmkr = cmaker.CMaker(cmake_executable)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-u03v6pzo/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 148, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-u03v6pzo/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
                raise SKBuildError(msg) from err

                =============================DEBUG ASSISTANCE=============================
                If you are seeing a compilation error please try the following steps to
                successfully install cmake:
                1) Upgrade to the latest pip and try again. This will fix errors for most
                   users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
                2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
                   order to retrieve the last manylinux1 compatible wheel.
                3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
                   requirements in order to retrieve the last manylinux1 compatible wheel.
                4) Open an issue with the debug information that follows at
                   https://github.com/scikit-build/cmake-python-distributions/issues

                Python: 3.11.3
                platform: Linux-4.4.302-p4Eureka_R11_A105-armv8l-with-libc
                machine: armv8l
                bits: 32
                pip: n/a
                setuptools: 67.7.2
                scikit-build: 0.17.3
                PEP517_BUILD_BACKEND=setuptools.build_meta
                =============================DEBUG ASSISTANCE=============================

            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
      Failed to build cmake
      ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by Belissimo-T** [comment]
This works on my machine. Do you have CMake installed?
