### ISSUE TITLE
alternative email provider with no limits

### ISSUE THREAD

**Issue by DVerdeV** [xtekky/gpt4free#41]
I would like to suggest a temporary mail provider that offers a free REST API. In my experience, using it in previous projects, they do not limit the number of addresses in any way (maximum 25 requests per second).

[DeveloperMail](https://developermail.com/api/v1)

**Comment by xtekky** [comment]
Alright will be checking it out, does it work with poe.com ?

**Comment by DVerdeV** [comment]
Yes!

![image](https://user-images.githubusercontent.com/99612385/232804854-af19ce00-392b-4fa6-9deb-efbed14e2442.png)

**Comment by xtekky** [comment]
closing as I am looking to integrate this soon

**Comment by dolodi** [comment]
But it doesnt work ? doesnt verify poe accounts
