### ISSUE TITLE
Failed to create account!

### ISSUE THREAD

**Issue by echoopen** [xtekky/gpt4free#411]
Failed to create account! Is forefront not working?

**Comment by acedia73** [comment]
Same trouble

**Comment by Ghxoxst** [comment]
Same here as well

**Comment by iaston** [comment]
so do I

**Comment by Gerrit1999** [comment]
same here

**Comment by choujayyl** [comment]
same

**Comment by p1k0pan** [comment]
same

**Comment by alaserm** [comment]
@xtekky, pls fix it asap, everybody seems to experience this issue

**Comment by AlephZero255** [comment]
I created a fork with changes in the initialization file. The bug is fixed here.
https://github.com/AlephZero255/gpt4free

**Comment by grayskripko** [comment]
> 

it hasn't help with forefront

**Comment by grayskripko** [comment]
> I created a fork with changes in the initialization file. The bug is fixed here. https://github.com/AlephZero255/gpt4free

It hasn't helped with forefront

**Comment by zxy003512** [comment]
> 

你解决这个问题了吗，我也是同样的问题

**Comment by AlephZero255** [comment]
> > I created a fork with changes in the initialization file. The bug is fixed here. https://github.com/AlephZero255/gpt4free
> 
> It hasn't helped with forefront

Yesterday everything was working. Now there is an error in establishing a connection to the link
https://chat-server.tenant-forefront-default.knative.chi.coreweave.com/chat 
404 error

**Comment by BadPotato1007** [comment]
same here!
