### ISSUE TITLE
Error with ForeFront provider: Unable to get the response, Please try again

### ISSUE THREAD

**Issue by amprodes** [xtekky/gpt4free#414]
try:
        token = forefront.Account.create(logging=False)
        response = gpt4free.Completion.create(Provider.ForeFront, prompt=prompt, model='gpt-4', token=token)
        return jsonify({"status": "success", "generated_text": response, "provider": "ForeFront"})
    except Exception as e:
        print(f"Error with ForeFront provider: {e}")
        pass
        
        this is trowing;
        Error with ForeFront provider: Unable to get the response, Please try again

**Comment by Cheukfung** [comment]
It seems that Forefront has ceased to offer GPT-4
