### ISSUE TITLE
request error

### ISSUE THREAD

**Issue by pianoplayeer** [xtekky/gpt4free#418]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=hi&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=4d8ff309-4fa8-4813-99cb-b47298510303&chat=%5B%5D": Proxy responded with non 200 code: 405 Method Not Allowed. Please make sure you are using a valid cloudflare clearance token and user agent.

Besides, I have added the proxy in you\__init__.py

**Comment by wqw547243068** [comment]
Similar error:

```
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=hello&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=414f00ec-1837-406c-936a-c5ceeb0cd087&chat=%5B%5D": x509: â*.facebook.comâ certificate name does not match input. Please make sure you are using a valid cloudflare clearance token and user agent.
```

**Comment by xiangsx** [comment]
![image](https://user-images.githubusercontent.com/29322721/236108904-5c60c7f1-380e-4c50-be04-a3e87c1382e6.png)

config proxy

**Comment by pianoplayeer** [comment]
But where can I find my proxy content? What content should I fill in ?

**Comment by YJ-KER** [comment]
+1

**Comment by xiangsx** [comment]
> But where can I find my proxy content? What content should I fill in ?

if do not know how to get your proxy, you should give up run this project

**Comment by YJ-KER** [comment]
+1

> > 但我在哪里可以找到我的代理的内容？ 什么内容我应该填写？
> 
> 如果不知道如何去得到你的代理，你应该放弃运行这个项目

Detailed introduction on how to set up

**Comment by xiangsx** [comment]
> ![image](https://user-images.githubusercontent.com/29322721/236108904-5c60c7f1-380e-4c50-be04-a3e87c1382e6.png)
> 
> config proxy

look at this line, just input your proxy

**Comment by Saix7** [comment]
> 

how to open window like that plz help！ ，，thank you very much！！

**Comment by xiangsx** [comment]
> > 
> 
> how to open window like that plz help！ ，，thank you very much！！

i guess you are not a developer, you do not know vscode?

**Comment by pianoplayeer** [comment]
Oh, I have found the right proxy. You need to see it in you network settings of your system.

**Comment by Saix7** [comment]
> > > 
> > 
> > 
> > how to open window like that plz help！ ，，thank you very much！！
> 
> i guess you are not a developer, you do not know vscode?

today i just know call （Visual Studio Code）now i am trying to change proxy but still not work 。 so sad！code  is very  fcking hard

**Comment by Saix7** [comment]
> > But where can I find my proxy content? What content should I fill in ?
> 
> if do not know how to get your proxy, you should give up run this project

can u plz teach me what app do u use for contact

**Comment by yang-luv-u** [comment]
> ![image](https://user-images.githubusercontent.com/29322721/236108904-5c60c7f1-380e-4c50-be04-a3e87c1382e6.png)
> 
> config proxy

3Q!
