### ISSUE TITLE
ora with multiple models

### ISSUE THREAD

**Issue by HexyeDEV** [xtekky/gpt4free#42]
Does ora work with multiple model instances? Because making 2 models instances, One with gpt3 and One with gpt4 both the gpt4 and gpt3 One at the question: what Is your language model answer with gpt4 even telling the gpt3 One that it's language model Is gpt3

**Comment by HexyeDEV** [comment]
also It looks like gpt4 gives more or less the same answers as gpt3.5 turbo and makes mistakes on the same things. Can It be that gpt4 of ora.sh Is not an actual gpt4?

**Comment by xtekky** [comment]
gpt4 saying its gpt3 is common, you should ask it complex questions or look at the speed, and ora.sh gpt4 model is gpt4 as they are making it paid and I dont think that they would afford to scam people.

closing as this issue is not productive for this repo
