### ISSUE TITLE
gpt4

### ISSUE THREAD

**Issue by maninet** [xtekky/gpt4free#423]

**Comment by 129lijun** [comment]
从以下这小说改编一下：
酒后睡了自己的前男友是一种什么样的体验？我睁开眼的时候已经日上三竿。窗帘遮光的那层没有拉上，剩白色薄纱与外界隔开。阳光让这一室的凌乱无所遁形，而我现在浑身上下一件衣服都没穿，默默坐在床上发懵。这会儿床上就我一个人，浴室传来的阵阵水声让我意识到钟皓还在。身上乱七八糟的痕迹也在提醒我，昨晚的一切是真实发生的。抓抓头发，心情复杂又懊恼。现在我无比羡慕那些喝酒断片失忆的人，就不像我，记得清清楚楚。我是楚然，28岁，破产律师。一个月前所里让我从A市和拉萨选一个地方出差。我毫不犹豫面不改色地选了A市，这给了我一个回来的理由。三天前我们团队来到A市做交接，昨天发了个带A市定位的朋友圈。大学同学有不少人毕业以后就留在这里，见我来纷纷说要趁此机会聚一下。我趁着工作还没展开欣然答应，昨晚开心赴约。平时大家各忙各的很难聚起来，这回虽说其实就是一大学聚会。却怎么也是打着我的名头在一块的，我也没想到钟皓也来了。吃饭的时候我大学最好的朋友帮我把我想知道的问题问得干干净净。比如钟皓还没女朋友更别说结婚，在A市开了几家连锁民宿。小日子过得很是滋润，每天漂亮妹妹排着队往上扑。有个人还惊讶地问了句：上次在xx饭店的那个女生不是你女朋友吗？钟皓看都没看我一眼，说：不是，朋友家妹妹，避不开。我刚开始还没觉得什么，到后边越听越酸。什么朋友家的妹妹这那的美女，他钟皓日子过得倒是很滋润。趁着大家都在说话，我也偷偷偏头看他。钟皓跟之前很不一样，我跟他分手那会儿他还是个黄毛小子。这会儿已经变成了一个能把控局面的成熟男人。岁月倒是对他很优待，对我就不怎么样了。想到前不久熬夜交接整个人憔悴到像是僵尸。昨天晚上认认真真敷了前男友面膜，今天还化了妆，毫无瑕疵一丝不苟那种。我放酒杯的手没把住力，不小心撞到自己的盘子，发出"叮"的声响。很快，一桌人的视线都移到我的身上。准确地说，他们在跟钟皓说话的时候都在用余光瞄我，此刻终于可以正大光明。毕竟当初在一起四年，分手以后谁都没有再找下一个。空气瞬间的寂静让我有点尴尬，正想要转移话题，就有人问了句很没眼色的话。楚校花这么多年也没跟我们皓哥联系过？当初大家还都以为你们能......他这样说着时，身边的人看我脸色有点不对，就立刻撞了他一下。你撞我干什么？还不让人说话了......我看了一眼，说话的人是我上学时候最讨厌的男同学。心里本就还酸，这会儿添上堵了，酒意上涌，我定定神，笑了一声：哪个做生意的想跟我扯上关系，不过如果哪天需要......钟老板倒是可以联系我。钟皓听了这话，终于抬头看我。四目相对，他意味不明地笑了一声，唇边微微上扬。不知道是不是头太晕了，这个笑让我仿佛瞬间回到学生时代。回忆一个劲儿地往脑袋里蹿，我差点坐不住。我有点后悔刚刚一时冲动说这种话，感觉自己仿佛是个傻子。好在酒桌热闹，很快便没有人在意。我被敬了几场酒，结束饭局却还有人觉得不尽兴，非要去唱歌。有人嚷嚷着让钟皓唱，我下意识看他，想想自己也很久没听过他唱歌了。可是钟皓还是没开口。KTV昏暗的灯光很容易让人卸下防备，钟皓也喝了不少，却看着比我清醒。他也没说话，就是一直抽烟，一直一直抽烟，就好像烟不要钱。座位换了几轮，他坐在我身边的时候我正闭着眼想事情。可是有些事情真的很神奇，有的人就算很久不见，但是当他靠近你的时候。哪怕你不去看，也知道是他。一整晚烟不离手，这会儿却是放下了。钟皓没看我，而是盯着前边的屏幕，对着莫名其妙的mv不知道在想什么。
