### ISSUE TITLE
docker run-- problem

### ISSUE THREAD

**Issue by Lotsoliu** [xtekky/gpt4free#425]
I have already build the image use the command:docker build -t gpt4free:latest .
It seems not work when I use docker run to start the container，below are the logs
$ sudo docker run -p 8501:8501 gpt4free:latest
Traceback (most recent call last):
  File "/usr/app/venv/lib/python3.11/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/app/venv/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/app/venv/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/app/venv/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/runtime.py", line 31, in <module>
    from streamlit.runtime.app_session import AppSession
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/app_session.py", line 35, in <module>
    from streamlit.runtime import caching, legacy_caching
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/caching/__init__.py", line 21, in <module>
    from streamlit.runtime.caching.cache_data_api import (
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 32, in <module>
    from streamlit.runtime.caching.cache_errors import CacheError, CacheKeyNotFoundError
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_errors.py", line 18, in <module>
    from streamlit import type_util
  File "/usr/app/venv/lib/python3.11/site-packages/streamlit/type_util.py", line 40, in <module>
    import numpy as np
  File "/usr/app/venv/lib/python3.11/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/usr/app/venv/lib/python3.11/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/usr/app/venv/bin/python"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by kainstan** [comment]
> I have already build the image use the command:docker build -t gpt4free:latest . It seems not work when I use docker run to start the container，below are the logs $ sudo docker run -p 8501:8501 gpt4free:latest Traceback (most recent call last): File "/usr/app/venv/lib/python3.11/site-packages/numpy/core/**init**.py", line 23, in from . import multiarray File "/usr/app/venv/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in from . import overrides File "/usr/app/venv/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in from numpy.core._multiarray_umath import ( ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/app/venv/bin/streamlit", line 5, in from streamlit.web.cli import main File "/usr/app/venv/lib/python3.11/site-packages/streamlit/**init**.py", line 55, in from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator File "/usr/app/venv/lib/python3.11/site-packages/streamlit/delta_generator.py", line 36, in from streamlit import config, cursor, env_util, logger, runtime, type_util, util File "/usr/app/venv/lib/python3.11/site-packages/streamlit/cursor.py", line 18, in from streamlit.runtime.scriptrunner import get_script_run_ctx File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/**init**.py", line 16, in from streamlit.runtime.runtime import Runtime as Runtime File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/runtime.py", line 31, in from streamlit.runtime.app_session import AppSession File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/app_session.py", line 35, in from streamlit.runtime import caching, legacy_caching File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/caching/**init**.py", line 21, in from streamlit.runtime.caching.cache_data_api import ( File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 32, in from streamlit.runtime.caching.cache_errors import CacheError, CacheKeyNotFoundError File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/caching/cache_errors.py", line 18, in from streamlit import type_util File "/usr/app/venv/lib/python3.11/site-packages/streamlit/type_util.py", line 40, in import numpy as np File "/usr/app/venv/lib/python3.11/site-packages/numpy/**init**.py", line 141, in from . import core File "/usr/app/venv/lib/python3.11/site-packages/numpy/core/**init**.py", line 49, in raise ImportError(msg) ImportError:
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed.
> 
> We have compiled some common reasons and troubleshooting tips at:
> 
> ```
> https://numpy.org/devdocs/user/troubleshooting-importerror.html
> ```
> 
> Please note and check the following:
> 
> * The Python version is: Python3.11 from "/usr/app/venv/bin/python"
> * The NumPy version is: "1.24.3"
> 
> and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help.
> 
> Original error was: No module named 'numpy.core._multiarray_umath'

I also encountered the same problem

**Comment by BanghuiSun** [comment]
我也遇到过同样的问题

**Comment by kokorousaki** [comment]
那个dockerfile本来就写的有问题，都没source虚拟环境，装完后拷贝到python镜像，拷贝个寂寞

**Comment by kainstan** [comment]
已修复，提交了pr

**Comment by 1714080902120** [comment]
https://github.com/xtekky/gpt4free/issues/413
