### ISSUE TITLE
Error: " ModuleNotFoundError: No module named 'user' "

### ISSUE THREAD

**Issue by KevinYamazaki** [xtekky/gpt4free#43]
Sorry to interrupt..  I tried to operate the POE test file, but met error.  The steps below are What I did to meet the error.

1. clone the git
2. pip install quora
3. copy poe test code from the "Readme"
4. python poe_test.py under the correct path
5. meet the error

here is the picture:
![1](https://user-images.githubusercontent.com/80442418/232951943-646f61b8-9512-42e2-9707-836f5b283628.jpg)
![2](https://user-images.githubusercontent.com/80442418/232951978-a96b8e6a-1b3d-495d-8159-d20f62a1d34f.jpg)

**Comment by zhanghaok** [comment]
the same problem ,have you solved the pro.?

**Comment by KevinYamazaki** [comment]
> the same problem ,have you solved the pro.?

No bro. I guess "quora" library might have problems，but  I don't know how to fix cause I have no idea how to use "quora"

**Comment by xtekky** [comment]
hey, why don't u guys just paste it in in chatgpt ? 😭

u have another module called quora I presume, "pip uninstall quora" and then try again

**Comment by KevinYamazaki** [comment]
> a"

Maybe it is not correct to uninstall it directly...    After uninstalling quora,  I occurred a new error like this:

![3](https://user-images.githubusercontent.com/80442418/233015622-51e9f2a9-4444-4d6d-b6f2-1a04aa2e04d5.jpg)

About the original problem, it says likes the library "quora" has no module named "user"

**Comment by KevinYamazaki** [comment]
> hey, why don't u guys just paste it in in chatgpt ? 😭
> 
> u have another module called quora I presume, "pip uninstall quora" and then try again

I tried to find libraries relative to "quora",  and the result showed  2 modules named "poe-api" and "pyquora" were most relative, then I installed them both, but still occurred error like this
![4](https://user-images.githubusercontent.com/80442418/233020276-542139f5-37b1-4556-9164-31ffa38522f3.jpg)

**Comment by xtekky** [comment]
you can try modify the quora folder name & imports in the folder and use it, make shure u are in the right configured work env with the quora folder in the same working dir, and uninstall all modules. I will be informing myself but this is rather an error occuring because of a bad configured pc rather than my repo itsself

**Comment by xtekky** [comment]
@KevinYamazaki, its not about installing but uninstalling them, the library causing the issue here is `pyquora`, if you are not using it, remove it with `pip uninstall pyquora`or `pip3 uninstall pyquora`or `{python prefix, ex: py, python, python3} -m pip uninstall pyquora`

**Comment by KevinYamazaki** [comment]
> @KevinYamazaki, its not about installing but uninstalling them, the library causing the issue here is `pyquora`, if you are not using it, remove it with `pip uninstall pyquora`or `pip3 uninstall pyquora`or `{python prefix, ex: py, python, python3} -m pip uninstall pyquora`

Sincerely apologize for my bad configured pc and thank you again for solving my issues.
I surely found some configuration problems while trying to make the `poe_test.py` work.
Now `poe_test.py` seems to run correctly(at least no basic errors), it told me as below:
```
PS D:\POE_bot_try\gpt4free\testing> python3 poe_test.py
'token'
email False
```

I'd like to share what I did to make the `poe_test.py` work, and it might help green hands(like me) to use the repo better.

**For POE only**
1.clone the git to local directory, or download the zip. (need to fix the folder name as "gpt4free")
2.go into the `gpt4free` folder, run `pip install -r requirement.txt`
3.copy folder `quora` to the folder `testing`
4.go to the folder `quora` in step3 and fix the name of folder `graphql` to `poe_graphql`
5.go to the folder `testing`, and `python3 poe_test.py`

**Comment by xtekky** [comment]
it might only be necessary to uninstall `pyquora`or `quora`, `poe-api` should work fine and u can even use it with the tokens.

as for you getting an error, its the email client which is quite unstable, i suggest usig a proxy if possible or waiting for an update which will come soon once i find another email client ; )

**Comment by KevinYamazaki** [comment]
You are right, it is not stable now. By the way, Where can I add my proxy into the code? `mail.py` or `__init__.py` or `api.py`?

**Comment by xtekky** [comment]
you can pass it in `quora.Account.create(proxy='user:pass@host.com:port'
