### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by xinmans** [xtekky/gpt4free#430]
Please note and check the following:

  * The Python version is: Python3.11 from "/usr/app/venv/bin/python"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by timewalk2012** [comment]
me too

**Comment by nevergiveup777** [comment]
Yeah, I am getting this too. I tried to put the numpy library as part of the requirement but that didn't solve the issue, it is till returning the same message.

**Comment by vual** [comment]
me too，how to resolve this？

**Comment by Olsondy** [comment]
how to resolve this？

**Comment by RhymeXY** [comment]
me too

**Comment by seeatiger** [comment]
+1

**Comment by EugeneKorneev** [comment]
+1

**Comment by braffour** [comment]
me too

**Comment by EugeneKorneev** [comment]
`FROM python:3.11 as builder

WORKDIR /usr/app
ENV PATH="/usr/app/venv/bin:$PATH"

RUN apt-get update && apt-get install -y git
RUN mkdir -p /usr/app
RUN python -m venv ./venv

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install numpy && pip install setuptools

# RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
# RUN pip config set global.trusted-host mirrors.aliyun.com

# FROM python:3.11-alpine
FROM python:3.11

WORKDIR /usr/app
ENV PATH="/usr/app/venv/bin:$PATH"

COPY --from=builder /usr/app/venv ./venv
COPY . .

RUN cp ./gui/streamlit_app.py .

CMD ["streamlit", "run", "streamlit_app.py"]

EXPOSE 8501`

frm [#413 ](https://github.com/xtekky/gpt4free/issues/413#issuecomment-1533837296)

**Comment by nevergiveup777** [comment]
I have done that as well and it doesn't work for me. I am still getting the same error.

**Comment by RhymeXY** [comment]
Git pull latest code and use the `To start gpt4free GUI` chapter to startup that works for me.
