### ISSUE TITLE
Unable to fetch the response, Please try again.

### ISSUE THREAD

**Issue by EnroXD1** [xtekky/gpt4free#433]
How to fix this problem?
![изображение_2023-05-04_131823414](https://user-images.githubusercontent.com/49277608/236176984-bf50723e-7536-44e2-a003-82d9737d502d.png)

**Comment by wszcl123456** [comment]
Me too

**Comment by Stoke6420** [comment]
This error occurs when it fails to connect to the servers. For example, this can happen because you may be from Russia

**Comment by dooooongyuan** [comment]
怎么解决

**Comment by wangerbin** [comment]
![image](https://user-images.githubusercontent.com/6681494/236369880-df67fb90-34b2-43be-8c28-fbbcec2daab2.png)
看之前的解决办法，加了代理，加完代理之后在浏览器直接访问可以 但是这个服务不行 
![image](https://user-images.githubusercontent.com/6681494/236370289-93ca3d01-23b3-4101-b9b0-e8cc99d2da54.png)

![image](https://user-images.githubusercontent.com/6681494/236370310-365f5996-f561-477a-94eb-5f7f438d47d4.png)
我这里需要怎么改？

**Comment by echozhangxiaomin** [comment]
![uTools_1683316276895](https://user-images.githubusercontent.com/86400430/236556241-6193c426-3b2b-4b0c-be76-00797240a452.png)

**Comment by hrkjqk** [comment]
how to fix this connect: connection refused. Please make sure you are using a valid cloudflare clearance token and user agent.
