### ISSUE TITLE
you.com error solution 

### ISSUE THREAD

**Issue by dooooongyuan** [xtekky/gpt4free#437]
Solution for "An error occurred: failed to do request: Get 'https://you.com/api/streamingSearch?q=%E4%BD%A0%E5%A5%BD&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=6def63ea-1627-4269-ae3a-e4df91fc0899&chat=%5B%5D': dial tcp 31.13.85.53:443: i/o timeout (Client.Timeout exceeded while awaiting headers). Please make sure you are using a valid cloudflare clearance token and user agent."
Please check that you are using a valid cloudflare clearance token and user agent.

Solution：
Add proxies to init.py line 56-57 in the 'you' folder.
![image](https://user-images.githubusercontent.com/128032721/236195156-5575bd9e-f357-473b-a662-c4d80c274b6e.png)

--------------------------------------------------------------------------------------------------------------------
Unable to fetch the response, Please try again. 

Solution：
Try to change the proxy location to Singapore or other regions."
--------------------------------------------------------------------------------------------------------------------
effect:
![image](https://user-images.githubusercontent.com/128032721/236196853-4a811c41-afd1-4a79-9291-6862327a23e4.png)

**Comment by lijiangdeshui2023** [comment]
加入那行代码会出现问题，不加入可以运行，但显示无法获取响应，改代理也不行

**Comment by sz-winner** [comment]
> 

最新的代码其实已经改过了，所以加那行代码进去不能运行
