### ISSUE TITLE
Unable to fetch the response, Please try again.

### ISSUE THREAD

**Issue by WGXT** [xtekky/gpt4free#445]
I build it by docker,and then run command`docker run -p 8501:8501 --name gpt4free gpt4free:latest`in cmd. On the web page, I type in the question, click the "think" button，it show me `Unable to fetch the response, Please try again.`  
in cmd:  
/usr/app/venv/lib/python3.11/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)  
how can I fix it?

**Comment by valerii-chirkov** [comment]
Will try to raise your error on my local machine

As for now try the first that comes in mind:
`sudo apt-get install ffmpeg`

**Comment by valerii-chirkov** [comment]
UPD: This issue was definitely related to ffmpeg package, that was not installed with Dockerfile.
Check this commit: https://github.com/xtekky/gpt4free/pull/451/commits/0d9ff6770488d19014c58393202228ebe8e01e74

**Comment by WGXT** [comment]
> UPD: This issue was definitely related to ffmpeg package, that was not installed with Dockerfile. Check this commit: [0d9ff67](https://github.com/xtekky/gpt4free/commit/0d9ff6770488d19014c58393202228ebe8e01e74)

you are right. Thanks!

**Comment by puyuanOT** [comment]
I have this issue when using gpt4free in Python. 

I used the example code:

```
import gpt4free
from gpt4free import Provider, quora, forefront

# usage You
response = gpt4free.Completion.create(Provider.You, prompt='Write a poem on Lionel Messi')
print(response)
```
