### ISSUE TITLE
Error: No response message when running poe_test.py

### ISSUE THREAD

**Issue by KevinYamazaki** [xtekky/gpt4free#45]
Thanks to Tekky, I have successfully operated `poe_test.py`, but it seems no response message.
To debug, I printed all of the values of model : `model.id \ model.name \ model.limit \ model.delected` , the operation result is as below:

![5](https://user-images.githubusercontent.com/80442418/233072962-55d1108b-77f5-4e56-af24-01c4b83b8059.jpg)

**Comment by xtekky** [comment]
they may have introduced a new patch, you can try using `poe-api` by @ading which also has this feature.

**Comment by KevinYamazaki** [comment]
> they may have introduced a new patch, you can try using `poe-api` by @ading2210 which also has this feature.

My God, I met the same problem using `poe-api`, and both projects share the same problem:  Get Stuck

**Comment by xtekky** [comment]
it's a general patch by Poe.com then will update when possible, closing as issue should get fixed soon ;)

**Comment by xtekky** [comment]
its working fine, please try again and reopen if needed
