### ISSUE TITLE
Proxy responded with non 200 code: 405 Method Not Allowed. Please make sure you are using a valid cloudflare clearance token and user agent.

### ISSUE THREAD

**Issue by dzgdp888** [xtekky/gpt4free#455]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/13160185/236364804-23df8b9d-1997-4df3-9af4-fef4b41a5ff2.png">

I set the proxy like this ,but it does`t work.how to solve this problem

![image](https://user-images.githubusercontent.com/13160185/236364884-b31d1e0a-4dc7-4d65-987f-3879a00c104d.png)

**Comment by xtekky** [comment]
add http:// before proxy 

http://ip:port 
or 
http://user:pass@ip:port
