### ISSUE TITLE
ModuleNotFoundError: No module named 'xtempmail'

### ISSUE THREAD

**Issue by vual** [xtekky/gpt4free#456]
File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/usr/app/streamlit_app.py", line 7, in <module>
    from gpt4free import you
File "/usr/app/gpt4free/__init__.py", line 4, in <module>
    from gpt4free import forefront
File "/usr/app/gpt4free/forefront/__init__.py", line 2, in <module>
    from xtempmail import Email

already import xtempmail, but not effective， how to fix？

**Comment by ilovepumpkin** [comment]
same error here

**Comment by lyfar** [comment]
same here

**Comment by ilovepumpkin** [comment]
fixed by installing the following two packages using "pip3 install"

- faker
- xtempmail

**Comment by ilovepumpkin** [comment]
However, unfortunately even the UI is shown up. It seems not working anymore. 

![image](https://user-images.githubusercontent.com/11310645/236366433-7ca29224-9e2e-40a3-89c5-006f3f8ff42d.png)

**Comment by 13640535881** [comment]
Me too

![image](https://user-images.githubusercontent.com/55781372/236366849-f17e7cbd-7b59-4ca2-8951-d4612f4961d8.png)

**Comment by angeles-renjo** [comment]
same here

**Comment by yangyueqiangyy** [comment]
pip install xtempmail
pip install faker

**Comment by LMFrank** [comment]
pip install

**Comment by zero3412** [comment]
xtempmail, faker already satisfied
<img alt="image" src="https://user-images.githubusercontent.com/6065014/236374023-04c89d93-b28e-474a-8a2c-df50853f5adb.png">

**Comment by zero3412** [comment]
python3 -m pip install --upgrade --force-reinstall xtempmail
python3 -m pip install --upgrade --force-reinstall faker
fixed Error

**Comment by artxia** [comment]
same here

**Comment by macshion** [comment]
add **xtempmail** and  **faker** in the [requirements.txt], then delete the image and run docker command again.

**Comment by 13640535881** [comment]
> 在 [requirements.txt] 中添加 **xtempmail** 和 **faker**，然后删除镜像并再次运行 docker 命令。

I have already tried,the UI is shown up.But it seems not working anymore.

**Comment by git-guocc** [comment]
Is that true of everyone？
<img width="910" alt="image" src="https://user-images.githubusercontent.com/81276451/236422832-5772dffe-2e10-465c-8743-c410c9f15d2d.png">

**Comment by macshion** [comment]
> Is that true of everyone？ <img alt="image" width="910" src="https://user-images.githubusercontent.com/81276451/236422832-5772dffe-2e10-465c-8743-c410c9f15d2d.png">

No. I just deployed successfully and it works well.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/31300385/236429145-b64f29f9-c236-4cc1-a66b-5c2e2b826424.png">

**Comment by macshion** [comment]
> > 在 [requirements.txt] 中添加 **xtempmail** 和 **faker**，然后删除镜像并再次运行 docker 命令。
> 
> I have already tried,the UI is shown up.But it seems not working anymore.

It works. Check if it is proxy problem.

**Comment by Coraline66** [comment]
<img width="449" alt="Screen Shot 2023-05-06 at 09 42 45" src="https://user-images.githubusercontent.com/20653003/236591617-f8564464-1239-4370-a81a-89b4269c010a.png">
Anyone having this issue?

**Comment by xiangsx** [comment]
> UI

https://github.com/xtekky/gpt4free/issues/418#issuecomment-1534060581

config proxy follow this

**Comment by Coraline66** [comment]
Thanks a lot but it does not work for my problem!

2023年5月6日(土) 10:38 Xiang ***@***.***>:
