### ISSUE TITLE
Incorrect encoding

### ISSUE THREAD

**Issue by AndroidTest10** [xtekky/gpt4free#457]
hi, does anyone have the same problem?
![image](https://user-images.githubusercontent.com/118258558/236367974-47edc0c0-aabc-46d0-854a-521e900fd552.png)

**Comment by Belissimo-T** [comment]
@AndroidTest10 What gpt4free module were you using?

**Comment by AndroidTest10** [comment]
> 

just run gui\streamlit_chat_app.py
