### ISSUE TITLE
[Question] Already set enable_bot_creation to true but still has this exception

### ISSUE THREAD

**Issue by realnoob007** [xtekky/gpt4free#46]
I followed steps in readme and run it with no issue, the network is good. But it still has the output when I tried it many times!!! I'm sure I set enable_bot_creation to true. Please take a look. I'm waiting for response.
<img width="852" alt="image" src="https://user-images.githubusercontent.com/87698941/233079509-20d06d5a-aff4-42a1-9639-1c1abbeaa396.png">

**Comment by KevinYamazaki** [comment]
get released, now connection to quora doesn't work even if you solve this problem.

**Comment by xtekky** [comment]
will check and unpatch when next possible

**Comment by xtekky** [comment]
Working perfectly, please check again / use proxies etc... reopen if issue persists and give details
