### ISSUE TITLE
how to get the proxy address?

### ISSUE THREAD

**Issue by vual** [xtekky/gpt4free#462]
vim gpt4free/gpt4free/you/__init__.py

        proxy='192.168.199.1:8118'
        proxies = {'http': 'http://' + proxy, 'https': 'http://' + proxy} if proxy else {}

how to get the proxy address?

**Comment by wangerbin** [comment]
![image](https://user-images.githubusercontent.com/6681494/236388885-ceb413aa-1616-4d14-884b-759cd6f37dee.png)
试试这样加，我这个不太好用 ，不知道是不是代理的国家有问题

**Comment by vual** [comment]
> ![image](https://user-images.githubusercontent.com/6681494/236388885-ceb413aa-1616-4d14-884b-759cd6f37dee.png) 试试这样加，我这个不太好用 ，不知道是不是代理的国家有问题

为啥是127.0.0.1？，为啥是7890端口？不是很明白，是需要而外的代理软件吗？

**Comment by wangerbin** [comment]
127.0.0.1 是我自己的本地代理地址，你可以写你自己的代理地址的IP，端口也是你自己的代理端口

**Comment by wangerbin** [comment]
VPN需要自己的，不翻墙出不去的

**Comment by git-guocc** [comment]
127.0.0.1？，为啥是7890端口？这个是clash默认端口的吧
