### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by persistanceTube** [xtekky/gpt4free#463]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=hi&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=999ed209-a5e9-4d85-ad01-4f0ff17b9844&chat=%5B%5D": http: server gave HTTP response to HTTPS client. Please make sure you are using a valid cloudflare clearance token and user agent.
how to fix it？

**Comment by xtekky** [comment]
you can try use proxies

**Comment by mayishidai** [comment]
output = query(user_input, st.session_state['query_method'])

**Comment by mayishidai** [comment]
没有将代理带入进去
