### ISSUE TITLE
Long answer leads to incomplete display

### ISSUE THREAD

**Issue by 397278900** [xtekky/gpt4free#466]
How to solve the incomplete loading when the answer exceeds a certain length? I tested it. If it is Chinese characters, if it exceeds 140, the loading will be incomplete.

**Comment by taiyi747** [comment]
Please provide a screenshot of the error message or the displayed results. Were you using Docker or running Python manually?

**Comment by 397278900** [comment]
thank you for your reply! I don't use docker, it's the python environment installed by anaconda. At the same time, I also use the debug mode. The session.py called in the source code seems to be the encapsulation of the request library. The answer it gets is incomplete, not incomplete

**Comment by 397278900** [comment]
> 

thank you for your reply! I don't use docker, it's the python environment installed by anaconda. At the same time, I also use the debug mode. The session.py called in the source code seems to be the encapsulation of the request library. The answer it gets is incomplete, not incomplete

**Comment by 397278900** [comment]
> Please provide a screenshot of the error message or the displayed results. Were you using Docker or running Python manually?
thank you for your reply! I don't use docker, it's the python environment installed by anaconda. At the same time, I also use the debug mode. The session.py called in the source code seems to be the encapsulation of the request library. The answer it gets is incomplete, not incomplete

**Comment by 397278900** [comment]
> Please provide a screenshot of the error message or the displayed results. Were you using Docker or running Python manually?

thank you for your reply! I don't use docker, it's the python environment installed by anaconda. At the same time, I also use the debug mode. The session.py called in the source code seems to be the encapsulation of the request library. The answer it gets is incomplete, not incomplete
