### ISSUE TITLE
An error occurred: failed to do request:

### ISSUE THREAD

**Issue by ZzUOsg** [xtekky/gpt4free#473]
Answer :

An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=are+you+gpt4%EF%BC%9F&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=8153d8b5-3f73-4d91-ba19-cdb44d62c694&chat=%5B%5D": dial tcp [2a03:2880:f10d:183:face:b00c:0:25de]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by xiangsx** [comment]
https://github.com/xtekky/gpt4free/issues/418#issuecomment-1534060581

config proxy follow this

**Comment by ruixule** [comment]
> [#418 (comment)](https://github.com/xtekky/gpt4free/issues/418#issuecomment-1534060581)
> 
> config proxy follow this

how to config proxy ？？？

**Comment by ZzUOsg** [comment]
thankyou
