### ISSUE TITLE
An error occurred: failed to do request. unexpected EOF.

### ISSUE THREAD

**Issue by panpengfei21** [xtekky/gpt4free#476]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E4%BD%A0%E5%A5%BD%0A&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=f3a40daa-92e0-4ca3-adfa-05b9ef91330e&chat=%5B%5D": unexpected EOF. Please make sure you are using a valid cloudflare clearance token and user agent

**Comment by xiangsx** [comment]
https://github.com/xtekky/gpt4free/issues/418#issuecomment-1534060581

config proxy follow this
