### ISSUE TITLE
Please make sure you are using a valid cloudflare clearance token and user agent.

### ISSUE THREAD

**Issue by hrkjqk** [xtekky/gpt4free#477]
dial tcp 127.0.0.1:7890: connect: connection refused. Please make sure you are using a valid cloudflare clearance token and user agent.
hot to fix this problem

**Comment by xiangsx** [comment]
> dial tcp 127.0.0.1:7890: connect: connection refused. Please make sure you are using a valid cloudflare clearance token and user agent. hot to fix this problem

which model you use?

**Comment by hrkjqk** [comment]
what is model? i use docker-compose up --build to run and try play "think" button

**Comment by xiangsx** [comment]
https://github.com/xtekky/gpt4free/issues/418#issuecomment-1534060581

try config proxy follow this

**Comment by xiangsx** [comment]
> [#418 (comment)](https://github.com/xtekky/gpt4free/issues/418#issuecomment-1534060581)
> 
> try config proxy follow this

and check docker-compose.yaml proxy config

**Comment by hrkjqk** [comment]
i already done and  got same error but i found two log " /usr/app/venv/lib/python3.11/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work"
" warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)" from my console

**Comment by xiangsx** [comment]
https://github.com/xtekky/gpt4free/issues/445#issuecomment-1535496411

try this, update your dockerfile

**Comment by hrkjqk** [comment]
i already update my dockerfile
![image](https://user-images.githubusercontent.com/89680866/236597850-a58934df-de59-4355-a857-27683f49f267.png)
but i got same error
![image](https://user-images.githubusercontent.com/89680866/236597913-e0d0f7de-3964-423f-80a1-b380c97c4c3f.png)

**Comment by Ya-Speak** [comment]
An error occurred: Maximum amount of retries reached. Please make sure you are using a valid cloudflare clearance token and user agent.
![image](https://user-images.githubusercontent.com/115214520/236680234-ce5d3adf-7b8d-489a-83d5-5557d9efdb56.png)
