### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c apt-get install ffmpeg" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by wocaishiniliu** [xtekky/gpt4free#478]
hello,
I met the same error: Unable to fetch the response, Please try again
And when I wanted to solve it, I found #445 
In #445 , valerii-chirkov mentioned that Check this commit: https://github.com/xtekky/gpt4free/commit/0d9ff6770488d19014c58393202228ebe8e01e74
And after doing that, here is the new error: 
ERROR: failed to solve: process "/bin/sh -c apt-get install ffmpeg" did not complete successfully: exit code: 1

Is the problem of the network? What should I do to fix it?

**Comment by xiangsx** [comment]
I don't understand why this project need ffmpeg.

@valerii-chirkov Could you help me get answer ?

**Comment by AmintaCCCP** [comment]
me too，macos m1

**Comment by valerii-chirkov** [comment]
The requirement added by @sudouser777 with adding pydub module for "Manipulate audio with an simple and easy high level interface".
It is added in 479b8d6d commit.

Guess it was intended to work with audio stream or something.
