### ISSUE TITLE
To solve "Unable to fetch the response, Please try again." 

### ISSUE THREAD

**Issue by RougeWhite** [xtekky/gpt4free#479]
1.修改streamlit_app.py中的get_answer函数 为you.Completion.create添加 参数 debug=True

当然你也可以按照英文版使用

2.在控制台使用 

```
streamlit run gui/streamlit_app.py
```
！！注意！！

> 如果需要代理，请修改streamlit_app.py中的get_answer函数 为you.Completion.create添加proxy值
> 
> 就像这样
> ```
> def get_answer(question: str) -> str:
>     # Set cloudflare clearance cookie and get answer from GPT-4 model
>     try:
>         result = you.Completion.create(prompt=question, proxy='127.0.0.1:4780')
> 
>         return result.text
> 
>     except Exception as e:
>         # Return error message if an exception occurs
>         return (
>             f'An error occurred: {e}. Please make sure you are using a valid cloudflare clearance token and user agent.'
>         )
>```

3.输入任意字符，点击Think
 
如果输出的错误中包括  **Just a moment...**
![image](https://user-images.githubusercontent.com/63292282/236595290-3874fcb2-e37f-4646-ad93-ea0124c52953.png)

其实是被服务器安全认证拦截导致无法访问

![image](https://user-images.githubusercontent.com/63292282/236595431-cfc670c6-a382-40fb-9cd2-01f882c73509.png)

解决方法：
1.更换一个安全的代理节点
2.修改代码，当进入后，通过自动程序点击，以通过人机验证

----------------------------------------------------------------------------------------------------------------------------------------------------

1. Modify gpt4free/you/__init__.py

```
if 'youChatToken' not in response.text:
return Completion.__get_failure_response(response.text)
```

2. Modify gpt4free/you/__init__.py to print error information

```
@staticmethod
def __get_failure_response(mm) -> PoeResponse:
return PoeResponse(text='Unable to fetch the response, Please try again.'+mm)
```
3. Use it on the console

```
streamlit run gui/streamlit_app.py\
```
!! Pay attention!!

> If you need a proxy, modify the get_answer function in streamlit_app.py to add a proxy value for you.pletion.create
>
> Like this
> ```
> def get_answer(question: str) -> str:
>     # Set cloudflare clearance cookie and get answer from GPT-4 model
>     try:
> result = you.pletion. create(prompt=question, proxy='127.0.0.1:4780')
>
>         return result.text
>
>     except Exception as e:
>         # Return error message if an exception occurs
>         return (
>             f'An error occurred:  {e}. Please make sure you are using a valid cloudflare clearance token and user agent.'
>)
>```

4. Type any character and click Think

If the output error includes **Just a moment... **
![image](https://user-images.githubusercontent.com/63292282/236595290-3874fcb2-e37f-4646-ad93-ea0124c52953.png)

In fact, it is blocked by the server security authentication

![image](https://user-images.githubusercontent.com/63292282/236595431-cfc670c6-a382-40fb-9cd2-01f882c73509.png)

Solution:
1. Replace a secure proxy node
2. Modify the code. After entering, click through the automatic program to pass man-machine verification

**Comment by shenxingchao** [comment]
可以提供一个模拟点击的代码吗。。

**Comment by pony-maggie** [comment]
同求自动点击的代码

**Comment by huankong233** [comment]
更换一个安全的代理节点感觉不太行，我把我有的都试了一遍了🤔
我美国原生ip都过不了

**Comment by RenHong-HC** [comment]
I clicked the man-machine verification, but it was unsuccessful, and I kept repeating the verification

**Comment by RougeWhite** [comment]
> 

对的 他就是一个安全验证 理论上添加个点击就能跳过 但是 目前我没有好的想法解决 如何点击的问题

**Comment by SunEternal** [comment]
> 更换一个安全的代理节点感觉不太行，我把我有的都试了一遍了🤔 我美国原生ip都过不了

Adding proxy cannot fetch response

**Comment by yujiayue123** [comment]
求一个模拟点击代码5555

**Comment by Cl0udG0d** [comment]
你确定是这个问题吗，我觉得是没有登录的原因，gpt4free默认用的是you.com，但是现在提问需要先登录了
![image](https://user-images.githubusercontent.com/45556496/236628308-4989cc18-10f2-4be5-be12-0860ce003df9.png)

**Comment by Cl0udG0d** [comment]
哦我自己也跑了一下确实也有防火墙验证的拦截
![image](https://user-images.githubusercontent.com/45556496/236628468-a4490700-ca5c-46c0-8591-945dc99bfbed.png)

**Comment by zjq2863974342** [comment]
![image](https://user-images.githubusercontent.com/38418205/236652214-6328767a-1626-46ba-a1dc-d9f5cb150298.png)
以子之矛，攻子之盾 X）
但我还没有尝试，有懂行的老哥可以探探路不？

**Comment by kiliyxiaohao** [comment]
额，不好意思，我水平太低了，没看明白，“Unable to fetch the response, Please try again.”是因为过不了验证嘛
![image](https://user-images.githubusercontent.com/128876653/236657524-d647cadc-811c-4530-9c49-37c54c93775d.png)

**Comment by RougeWhite** [comment]
> 



> 你确定是这个问题吗，我觉得是没有登录的原因，gpt4free默认用的是you.com，但是现在提问需要先登录了
> ![image](https://user-images.githubusercontent.com/45556496/236628308-4989cc18-10f

**Comment by RougeWhite** [comment]
> 额，不好意思，我水平太低了，没看明白，“Unable to fetch the response, Please try again.”是因为过不了验证嘛
> ![image](https://user-images.githubusercontent.com/128876653/236657524-d647cadc-811c-4530-9c49-37c54c93775d.png)

这个 unable 是作者写的异常捕捉 具体返回需要打印返回参数

**Comment by RougeWhite** [comment]
> 

这个只是理论可行 实际上不行 因为浏览器id不同 服务器那边的验证还是没法通过

**Comment by RougeWhite** [comment]
> 更换一个安全的代理节点感觉不太行，我把我有的都试了一遍了🤔
> 我美国原生ip都过不了

安全节点是指无验证的白名单ip

**Comment by kiliyxiaohao** [comment]
> > 额，不好意思，我水平太低了，没看明白，“Unable to fetch the response, Please try again.”是因为过不了验证嘛
> > ![image](https://user-images.githubusercontent.com/128876653/236657524-d647cadc-811c-4530-9c49-37c54c93775d.png)
> 
> 这个 unable 是作者写的异常捕捉 具体返回需要打印返回参数
 
噢噢，我也是出现了 **Just a moment... **，请问现在是需要我去自己找出相关代码，嵌入一个自动点击的脚本吗？？？大佬是否已经解决？可以教教吗~~~~~~~

**Comment by ZJDATY** [comment]
> ![image](https://user-images.githubusercontent.com/38418205/236652214-6328767a-1626-46ba-a1dc-d9f5cb150298.png) 以子之矛，攻子之盾 X） 但我还没有尝试，有懂行的老哥可以探探路不？

这个页面看起来gpt一些 ，为啥我的只是在网页上，你是自己写的页面吗

**Comment by huaizhu1** [comment]
我一开始也是出在无法响应这个问题，于是我尝试使用美国的原生ip进行搭建发现仍然是一样的问题，最后看到了这篇文章我又想到了一个解决办法（我就是通过这个方法解决的），我根据大佬们的文章可以得出是无法响应的根本原因在于原作者的模型套用了cloudfare的防ddos验证才导致的这个问题，于是乎我就打算从cloudfare上下手，我在美国原生ip所属的服务器上部署了cloudfare的warp，使得服务端发送请求的地址是通过cloudfare所属的节点代理发出，从而跳过了cloudfare的验证，于是乎解决了这个无法响应的问题。
最后附上成果图
![image](https://github.com/xtekky/gpt4free/assets/103626680/14c0c64a-a27a-4194-b489-e54907b5b555)
