### ISSUE TITLE
forefront change auth way

### ISSUE THREAD

**Issue by xiangsx** [xtekky/gpt4free#481]
![image](https://user-images.githubusercontent.com/29322721/236598678-6901098c-6c41-4ca2-8a00-551f588c0e91.png)

new header x-signature and they change chat url

**Comment by tilefishpoele** [comment]
do you know how they are generating x-signature

**Comment by xiangsx** [comment]
I found a way , but not sure if it work. and I dont know how to get sessionId. Still tring

https://discord.com/channels/1099825897697189898/1101062943430422628/1104265827076800573

**Comment by xiangsx** [comment]
> I found a way , but not sure if it work. and I dont know how to get sessionId. Still tring
> 
> https://discord.com/channels/1099825897697189898/1101062943430422628/1104265827076800573

it work now, thanks `FlXWare`
