### ISSUE TITLE
Will anyone still be able to execute this project successfully on May 6?

### ISSUE THREAD

**Issue by aixinjueluoshinibaba** [xtekky/gpt4free#484]
I have some errors when running, and do not understand the part of Configure the Application, please advise, thank you.

**Comment by 397278900** [comment]
> I have some errors when running, and do not understand the part of Configure the Application, please advise, thank you.

i  can't use it today

**Comment by aixinjueluoshinibaba** [comment]
Did it run successfully before? I said GTP4. Can you solve my mistake? Thank you for your reply

**Comment by aixinjueluoshinibaba** [comment]
> > I have some errors when running, and do not understand the part of Configure the Application, please advise, thank you.
> 
> i can't use it today
Did it run successfully before? I said GTP4. Can you solve my mistake? Thank you for your reply

**Comment by aixinjueluoshinibaba** [comment]
@397278900
Did it run successfully before? I said GTP4. Can you solve my mistake? Thank you for your reply.

**Comment by 397278900** [comment]
> @397278900 Did it run successfully before? I said GTP4. Can you solve my mistake? Thank you for your reply.

it seem to be GPT3.5 this project , i can use it before today.  but now.i can't use it

**Comment by manatlan** [comment]
Can't use ('you' endpoint) since today ...
(it worked yesterday)

**Comment by 397278900** [comment]
> Can't use ('you' endpoint) since today ...

yerh,it seem need mouse click when go on you.com . I hope God can solve it

**Comment by xiangsx** [comment]
you.com and forefront has add new auth today!


https://discord.com/channels/1099825897697189898/1101062943430422628/1104265827076800573
we found a new way , you can got how to run from this.

**Comment by 397278900** [comment]
> you.com and forefront has add new auth today!
> 
> https://discord.com/channels/1099825897697189898/1101062943430422628/1104265827076800573 we found a new way , you can got how to run from this.

it seem need gpt api?

**Comment by xiangsx** [comment]
> 

no, just add some code. enter that discord channel and  read to the bottom

**Comment by ruixule** [comment]
![image](https://user-images.githubusercontent.com/33270841/236616352-4aaea815-4070-45af-b4be-f9b99bf0a17d.png)
这个错误是什么情况么

**Comment by xiangsx** [comment]
> ![image](https://user-images.githubusercontent.com/33270841/236616352-4aaea815-4070-45af-b4be-f9b99bf0a17d.png)
> 这个错误是什么情况么

give up use you.com, it not work now

**Comment by ruixule** [comment]
> give up use you.com, it not work now

how to give up，and How to operate it specifically

**Comment by xiangsx** [comment]
> you.com and forefront has add new auth today!
> 
> 
> https://discord.com/channels/1099825897697189898/1101062943430422628/1104265827076800573
> we found a new way , you can got how to run from this.
> 

look at this

**Comment by ruixule** [comment]
![image](https://user-images.githubusercontent.com/33270841/236619837-14465fc4-3486-43b5-b3a9-692c3751d7af.png)
https://discord.com/channels/1099825897697189898/1101062943430422628/1104265827076800573

**Comment by xiangsx** [comment]
> ![image](https://user-images.githubusercontent.com/33270841/236619837-14465fc4-3486-43b5-b3a9-692c3751d7af.png)
> https://discord.com/channels/1099825897697189898/1101062943430422628/1104265827076800573

https://github.com/xiangsx/gpt4free-ts/commit/1938c0cfa5fc5b38a6b98253a44e99873efe0e95


look this commit , you can midify python like this

**Comment by ruixule** [comment]
> > ![image](https://user-images.githubusercontent.com/33270841/236619837-14465fc4-3486-43b5-b3a9-692c3751d7af.png)
> > https://discord.com/channels/1099825897697189898/1101062943430422628/1104265827076800573
> 
> [xiangsx/gpt4free-ts@1938c0c](https://github.com/xiangsx/gpt4free-ts/commit/1938c0cfa5fc5b38a6b98253a44e99873efe0e95)
> 
> look this commit , you can midify python like this

![image](https://user-images.githubusercontent.com/33270841/236620876-c33353d3-a2ce-423d-9773-b2f935bc249a.png)

**Comment by aixinjueluoshinibaba** [comment]
@xiangsx 
So is gpt4free still available?

**Comment by xiangsx** [comment]
> @xiangsx So is gpt4free still available?

yes, You can use this project temporarily.  https://github.com/xiangsx/gpt4free-ts

The author is currently too busy, but they will fix all issues when he return.

**Comment by MaskWeetrogan** [comment]
Worked!

**Comment by xtekky** [comment]
yh I am busy at the moment, will get back soon
