### ISSUE TITLE
pymailtm.pymailtm.CouldNotGetAccountException: HTTP 422

### ISSUE THREAD

**Issue by cabfile** [xtekky/gpt4free#486]
literally just used the gpt4 example
python 3.8.10

**Comment by HuanLinOTO** [comment]
Are you in China or other countries with firewalls? If so, please try using a proxy

**Comment by cabfile** [comment]
no im in russia

**Comment by OUYANGSIR** [comment]
> 

Excuse me, I don't know how can I use a proxy?can you provider me some step or documentation?

**Comment by 451578928** [comment]
您好，信已收到，尽快给您回复。

**Comment by HuanLinOTO** [comment]
> > 
> 
> Excuse me, I don't know how can I use a proxy?can you provider me some step or documentation?
用 clash 的话，复制对应的命令执行即可，其他代理搞成 http 协议后挂上就行 看得出来你是中国人（）

**Comment by OUYANGSIR** [comment]
> > > 
> > 
> > 
> > Excuse me, I don't know how can I use a proxy?can you provider me some step or documentation?
> 
> 用 clash 的话，复制对应的命令执行即可，其他代理搞成 http 协议后挂上就行 看得出来你是中国人（）

哈哈哈

`# usage forefront
token = forefront.Account.create(logging=False, proxy="127.0.0.1:33210")
response = gpt4free.Completion.create(
    Provider.ForeFront, prompt='Write a poem on Lionel Messi', model='gpt-4', token=token, proxy="127.0.0.1:33210"
)`
我尝试给它加了代理参数，proxy ，但是它依旧不行
