### ISSUE TITLE
Please make sure you are using a valid cloudflare clearance token and user agent.

### ISSUE THREAD

**Issue by wssb114** [xtekky/gpt4free#492]
![image](https://user-images.githubusercontent.com/132080083/236627429-ff377c93-a109-4765-846d-3cf48db45ab4.png)

**Comment by CcatAnI** [comment]
I have the same issue:
An error occurred: failed to build client out of request input: scheme htto is not supported. Please make sure you are using a valid cloudflare clearance token and user agent.
