### ISSUE TITLE
Unable to fetch the response, Please try again.

### ISSUE THREAD

**Issue by Lkeikei** [xtekky/gpt4free#493]
how to solve"Unable to fetch the response, Please try again"?

**Comment by martindanko** [comment]
I'm getting the same issue, it was working fine the other day. Do you think something may have changed that this is now being blocked?

**Comment by Yeetster-cmd** [comment]
Yeah it's super weird, it seems to only be getting a twitter png now, so that's weird x2

**Comment by jdukwjdo** [comment]
我在windows11上跑，代理已经开了TUN模式，也有这个问题

**Comment by jagauthier** [comment]
I started getting this too. I saw references  to people using Docker with ffmpeg but I don't think that has solved it.  It was working before without ffmpeg.

**Comment by smpurkis** [comment]
same for me as well

**Comment by xiangsx** [comment]
try this, it work perfect
https://github.com/xiangsx/gpt4free-ts

**Comment by xiangsx** [comment]
i will make pr for this python project tomorrow

**Comment by jagauthier** [comment]
> try this, it work perfect https://github.com/xiangsx/gpt4free-ts

Thanks.  I pulled it, and built it.. But not sure how it works.. is it a replacement for this project or a different query backend?  Do they work together?  I attempted to use it as a replacement, and there wasn't a web interface. I was able to query with curl successfully.

**Comment by xiangsx** [comment]
> > try this, it work perfect https://github.com/xiangsx/gpt4free-ts
> 
> Thanks.  I pulled it, and built it.. But not sure how it works.. is it a replacement for this project or a different query backend?  Do they work together?  I attempted to use it as a replacement, and there wasn't a web interface. I was able to query with curl successfully.
> 

Just rewritten this project using TypeScript.Not work together. I have fixed the error cause by new authentication method of forefront.

**Comment by jagauthier** [comment]
Okay got it. Thanks!

**Comment by Roselearn** [comment]
It's not worked right now.

**Comment by xuanyuan100** [comment]
the same problem.just a picture

**Comment by CmsDoter** [comment]
same for me

**Comment by shaonaoteam** [comment]
1.使用docker build 命令制作镜像。
2.使用docker compose启动容器（需要打开代理）

**Comment by gameuser1982** [comment]
I'm still getting this issue even after the update which uses the mailgw_temporary_email module.

**Comment by macross5** [comment]
Still "Unable to fetch the response, Please try again." after the "pip install mailgw_temporary_email".

**Comment by Minos-Z** [comment]
`pip install mailgw_temporary_email` after `. venv/bin/activate`.  You should do this in venv environment.

**Comment by macross5** [comment]
> `pip install mailgw_temporary_email` after `. venv/bin/activate`. You should do this in venv environment.

Im running it on docker. Im too noob to understand where i have to add the `. venv/bin/activate`

Im doing:
`sudo docker exec $NAME pip install mailgw_temporary_email
sudo docker restart $NAME `

**Comment by with1874** [comment]
> `pip install mailgw_temporary_email` after `. venv/bin/activate`. You should do this in venv environment.

It doesn't solved the problem after I did this

**Comment by xiangsx** [comment]
you.com add auth need click in web,can not work now!

forefront change their chat url,and add new auth x-signature, but it could be find a way to work
you should update your code follow this commit. dont ask "Unable to fetch response" again. Find answer in Issues.
https://github.com/xiangsx/gpt4free-ts/commit/1938c0cfa5fc5b38a6b98253a44e99873efe0e95

**Comment by hausa-han** [comment]
Bro Xiang YYDS!!!!

**Comment by phoenix1of1** [comment]
So there is a commit merger waiting for approval but in the meantime, here's a step-by-step guide on what you need to do:

Navigate to gpt4free/forefront/readme.md
Open it and amend line 6 to token = forefront.Account.create(logging=True)
There is a merge waiting to happen on https://github.com/xtekky/gpt4free/pull/504
Go to -
Navigate to the init.py inside of the forefront subfolder in your project directory.
Copy the cope from the link above.
Repeat the process for the typing.py file and requirements.txt

Once complete, don't forget to run pip install -r requirements.txt in your terminal.

Now run streamlit run streamlit_app.py

You are good to go. It's a manual workaround until the new commits have been approved and merged.

**Comment by jagauthier** [comment]
Confirmed this works.
Clone the tree, or update it.,
Then do this:

```
git fetch origin pull/504/head:ff_fixes
git checkout ff_fixes
```

Then follow install instructions as per normal.

**Comment by xukaili** [comment]
how to solve"Unable to fetch the response, Please try again"?

**Comment by jagauthier** [comment]
The answer is right there, above you.

**Comment by lovecomic** [comment]
> Confirmed this works. Clone the tree, or update it., Then do this:
> 
> ```
> git fetch origin pull/504/head:ff_fixes
> git checkout ff_fixes
> ```
> 
> Then follow install instructions as per normal.

The following error occurs after running git fetch origin pull/504/head:ff_fixes, how to solve it
fatal:origin does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rightsand the repository exists.

**Comment by jagauthier** [comment]
You have to clone the tree first...

**Comment by lovecomic** [comment]
> You have to clone the tree first...

I cloned the project first, and then followed the method you said,
git fetch origin pull /504/head:ff_fixes
git checkout ff_fixes

After that, follow the installation method and start it. After the question is sent, it still displays:
Unable to fetch the response, please try again.

**Comment by mochizuki-pg** [comment]
I check out this branch and it's up and running

<img width="787" alt="スクリーンショット 2023-05-08 10 58 59" src="https://user-images.githubusercontent.com/38402160/236719350-b23f8f3b-fcb4-4c28-bf5f-b98f6d12fa4a.png">

**Comment by EstelZhao** [comment]
> You have to clone the tree first...

fatal: couldn't find remote ref pull/504/head 
claim like this.

**Comment by mochizuki-pg** [comment]
> > You have to clone the tree first...
> 
> fatal: couldn't find remote ref pull/504/head claim like this.

```
git fetch origin refs/pull/504/head:ff_fixes
git checkout ff_fixes
```
If you type it exactly like this, does it still result in an error?

**Comment by EstelZhao** [comment]
> 

yeah, it works. After doing this and I follow the instructions like

```
 python3 -m venv venv
. venv/bin/activate
 pip3 install -r requirements.txt
```

then this 
`cp gui/streamlit_app.py .
streamlit run streamlit_app.py`

and it leads to safari and still doesn't work answering this: Unable to fetch the response, Please try again.

is it related with not using docker?

**Comment by mochizuki-pg** [comment]
Docker was started, but it also worked locally
But Docker is less dependent on Docker, so Docker is better

<img width="1164" alt="スクリーンショット 2023-05-08 12 31 58" src="https://user-images.githubusercontent.com/38402160/236727817-91d97be8-6079-4b4a-a4f5-b0a10093f36d.png">

<img width="624" alt="スクリーンショット 2023-05-08 12 30 01" src="https://user-images.githubusercontent.com/38402160/236727856-0f15b424-3b64-4567-8903-494653147954.png">

**Comment by mingchar** [comment]
![图片](https://user-images.githubusercontent.com/21221747/236736399-d880b317-caa4-4af0-93cf-47fd31fa3a39.png)
Seems it not works when using the "ff_fixes" branch.

Would some give me some advice for the proxy setup? I didn't use a proxy on my local machine.

**Comment by smallwenzi** [comment]
怎么成功跑起来

**Comment by Jaskr616** [comment]
> Confirmed this works. Clone the tree, or update it., Then do this:
> 
> ```
> git fetch origin pull/504/head:ff_fixes
> git checkout ff_fixes
> ```
> 
> Then follow install instructions as per normal.

it still not work

**Comment by EstelZhao** [comment]
> http/https proxy

how to check the  http/https proxy ?

**Comment by gameuser1982** [comment]
Are we able to add password protected http proxies?

**Comment by gameuser1982** [comment]
So I am still getting a "Unable to fetch the response, Please try again." error even after I did the following:

```
git fetch origin pull/504/head:ff_fixes
git checkout ff_fixes
```

Am I supposed to add my own http proxy to streamlit_app.py or is something else the issue?

**Comment by chao-eng** [comment]
1. 执行  
git fetch origin pull /504/head:ff_fixes
git checkout ff_fixes
2. 修改代理
result = you.Completion.create(prompt=question,proxy='127.0.0.1:7890')

**Comment by smallwenzi** [comment]
是不是只能走代理？程序不走代理可以？

**Comment by freeaswind** [comment]
![image](https://user-images.githubusercontent.com/13989977/237009678-ec1bdf4b-ed39-43af-97da-5ba2512e2043.png)
![image](https://user-images.githubusercontent.com/13989977/237009740-b2d30caa-a2e1-4a4f-ab3f-c7c3e18caee3.png)
也没报错   不知道啥原因

**Comment by dsunzhiming** [comment]
Make sure you're not using a China or Hongkong VPN. I swifted my ip to USA then it worked.
不能用中国或者香港的IP

**Comment by Hezhexi2002** [comment]
> 1. git checkout ff_fixes

你这里第一步的命令应该是git fetch origin pull/504/head:ff_fixes吧，pull之后没有空格，不然就会报错

**Comment by Hezhexi2002** [comment]
> 1. git checkout ff_fixes

你这里第一步的命令应该是git fetch origin pull/504/head:ff_fixes吧，pull之后没有空格，不然就会报错

**Comment by gameuser1982** [comment]
I am still getting the "Unable to fetch the response, Please try again" response here and for the life of me I can't figure out the issue. To further complicate things, I live in Hong Kong. So I've been reading the Chinese user responses here too.

Things I have tried:

1. Updated via git pull order main
2. Entered the following commands: ```
git fetch origin pull/504/head:ff_fixes
git checkout ff_fixes
```
3. Tried to launch streamlit_app.py and got the "Unable to fetch the response, Please try again" in the GUI.
3. Modified streamlit_app.py in the following line: `result = you.Completion.create(prompt=question,proxy='127.0.0.1:7890')`
4. Tried to launch streamlit_app.py and got the "Unable to fetch the response, Please try again" in the GUI.
5. Launched my VPN which unblocks ChatGPT in web browser
6. Tried to launch streamlit_app.py and got the "Unable to fetch the response, Please try again" in the GUI.
7. Turned off VPM
8.  Modified streamlit_app.py in the following line: `result = you.Completion.create(prompt=question,proxy='myusernamehere:mypasswordhere@12.198.49.4:32222)`
9. myusernamehere:mypasswordhere is the not the actual username and pass obviously but in the code I have the real username and pass there instead. This is a residential ip proxy and it works with ChatGPT
10. Tried to launch streamlit_app.py and got the "Unable to fetch the response, Please try again" in the GUI.

I can not get past this error.

**Comment by BatmanuGinobilieve** [comment]
> ![image](https://user-images.githubusercontent.com/39251907/236773765-17f56f4f-479d-4669-9dc6-f8ce9a67dbb8.png)
> 
> In the `streamlit_app.py` file, add your own proxy url here. Only http/https proxy supported for the moment.
> 
> ![image](https://user-images.githubusercontent.com/39251907/236774072-71394932-ce55-4cea-98c6-52d0a3d5fdc4.png)

this work

**Comment by Yicijiuhaobala** [comment]
> 
I followed the step by step you said, but it still failed, and this problem appeared

**Comment by shkwahab** [comment]
> > 
> 
> I followed the step by step you said, but it still failed, and this problem appeared



> (Issue is now solved but I am keeping this here in case it helps anyone, especially if they in HK or China)
> 
> I am still getting the "Unable to fetch the response, Please try again" response here and for the life of me I can't figure out the issue. To further complicate things, I live in Hong Kong. So I've been reading the Chinese user responses here too.
> 
> Things I have tried:
> 
> 1. Updated via git pull order main
> 2. Entered the following commands:
>    git fetch origin pull/504/head:ff_fixes
>    git checkout ff_fixes
> 3. Tried to launch streamlit_app.py and got the "Unable to fetch the response, Please try again" in the GUI.
> 4. Modified streamlit_app.py in the following line: `result = you.Completion.create(prompt=question,proxy='myusernamehere:mypasswordhere@12.198.49.4:32222)`
> 5. myusernamehere:mypasswordhere is the not the actual username and pass obviously but in the code I have the real username and pass there instead. This is a residential ip proxy and it works with ChatGPT
> 6. Tried to launch streamlit_app.py and finally got a response from GPT4! W000t!

how we get this proxy
