### ISSUE TITLE
Why docker image not work?

### ISSUE THREAD

**Issue by moonrailgun** [xtekky/gpt4free#501]
Is dockerfile still update to date?

when i clone this repo and build docker image, lose mailgw_temporary_email and ffmpeg.

is anyway to run it without py? i am not wanna install python runtime and not good at python ecological

**Comment by fenger7** [comment]
你可以把错误输出在chatgpt上，会提示给你命令，然后把命令添加到dockerfile文件中，就行。

**Comment by macross5** [comment]
atm its not working

**Comment by bruvv** [comment]
If you have an error post the error. That will help debug the issue.

**Comment by moonrailgun** [comment]
> If you have an error post the error. That will help debug the issue.

Hi, @bruvv . Thanks for your reply.

my point is, if i use docker, and docker image build success.

Its should not throw any error. its not source code compile

**Comment by MIDORIBIN** [comment]
@moonrailgun 
It works now.
`git pull` and build Docker image again.

**Comment by moonrailgun** [comment]
Nice, everything is ok. i will close this issue.
