### ISSUE TITLE
forefront连不上

### ISSUE THREAD

**Issue by homo11451419** [xtekky/gpt4free#502]
报错如下：    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='chat-server.tenant-forefront-default.knative.chi.coreweave.com', port=443): Max retries exceeded with url: /chat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
ping其中的地址结果如下：
![image](https://user-images.githubusercontent.com/127638251/236668582-0b46a99d-f203-44e3-8b43-40623f0f9fae.png)

**Comment by xiangsx** [comment]
forefront change their chat url
you can update this project follow this commit 

https://github.com/xiangsx/gpt4free-ts/commit/1938c0cfa5fc5b38a6b98253a44e99873efe0e95

**Comment by homo11451419** [comment]
> forefront change their chat url you can update this project follow this commit
> 
> [xiangsx/gpt4free-ts@1938c0c](https://github.com/xiangsx/gpt4free-ts/commit/1938c0cfa5fc5b38a6b98253a44e99873efe0e95)

    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='streaming.tenant-forefront-default.knative.chi.coreweave.com', port=443): Max retries exceeded with url: /chat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001FFB6DFB1F0>, 'Connection to streaming.tenant-forefront-default.knative.chi.coreweave.com timed out. (connect timeout=None)'))
不行啊，我在中国

**Comment by xiangsx** [comment]
if you have updated your code not just url. config proxy this line 

https://github.com/xtekky/gpt4free/blob/98339256c54525f9dbd9ea3a0addc7a92535f92a/gui/streamlit_app.py#LL13C1-L14C1

**Comment by homo11451419** [comment]
> if you have updated your code not just url. config proxy this line
> 
> https://github.com/xtekky/gpt4free/blob/98339256c54525f9dbd9ea3a0addc7a92535f92a/gui/streamlit_app.py#LL13C1-L14C1

？
我改了一下gpt4free/testing/forefront_test.py中的代码，实现用户输入-GPT回答。（在中国，you无法使用）
```python
from gpt4free import forefront
# create an account
prompt=input()
token = forefront.Account.create(logging=True)
#print(token)
# get a response
for response in forefront.StreamingCompletion.create(token=token, prompt=prompt, model='gpt-4'):
        print(response.text, end='')

**Comment by xiangsx** [comment]
![image](https://user-images.githubusercontent.com/29322721/236671520-6301388f-2099-4ef4-8011-98ef75ae1880.png)
这里有个proxy参数，需要加上

但是我劝你放弃，看起来你没有完全理解需要改哪些地方

**Comment by homo11451419** [comment]
> ![image](https://user-images.githubusercontent.com/29322721/236671520-6301388f-2099-4ef4-8011-98ef75ae1880.png) 这里有个proxy参数，需要加上
> 
> 但是我劝你放弃，看起来你没有完全理解需要改哪些地方

可是我没有代理

**Comment by xiangsx** [comment]
所以啊  劝你放弃，就算你有代理 你还是需要改挺多地方的代码的

**Comment by homo11451419** [comment]
那有没有别的办法？
自己搞一个？

**Comment by homo11451419** [comment]
> forefront change their chat url you can update this project follow this commit
> 
> [xiangsx/gpt4free-ts@1938c0c](https://github.com/xiangsx/gpt4free-ts/commit/1938c0cfa5fc5b38a6b98253a44e99873efe0e95)

url我改了，但是咋搞代理

**Comment by arashrun** [comment]
> 所以啊 劝你放弃，就算你有代理 你还是需要改挺多地方的代码的

这项目还能用不，感觉到处受阻。网站网站用不了
