### ISSUE TITLE
Reply Chinese will be garbled

### ISSUE THREAD

**Issue by with1874** [xtekky/gpt4free#507]
I use forefront, reply Chinese will be garbled.
My environment is ArchLinux, Python version 3.11.3
![image](https://user-images.githubusercontent.com/68050803/236717316-03b8d846-91f8-4880-aad3-5764598c82a8.png)

And I modified the code of streamlit_app.py
![image](https://user-images.githubusercontent.com/68050803/236718086-231d7fb4-2359-456f-ab31-87888eb6903a.png)

The same garbled characters are still displayed when using other devices to access the Network URL.
I don't know if it's my fault, please let me know, thanks

**Comment by 397278900** [comment]
> 

The author uses Chinese decoding by default, you can comment out the line "escaped = answer.encode('utf-8').decode('unicode-escape')"

**Comment by 397278900** [comment]
and  after line is st.markdown(answer).you can display chinese normal

**Comment by with1874** [comment]
> > 
> 
> The author uses Chinese decoding by default, you can comment out the line "escaped = answer.encode('utf-8').decode('unicode-escape')"

Comment out the line will get error `NameError: name 'escaped' is not defined`  
I modified this line of code like this `escaped = answer.encode('utf-8').decode('utf-8')`
I understand what's going on. Thank you !

**Comment by 397278900** [comment]
> > > 
> > 
> > 
> > The author uses Chinese decoding by default, you can comment out the line "escaped = answer.encode('utf-8').decode('unicode-escape')"
> 
> Comment out the line will get error `NameError: name 'escaped' is not defined` I modified this line of code like this `escaped = answer.encode('utf-8').decode('utf-8')` I understand what's going on. Thank you !

You're welcome, the main reason is that this great author is too dedicated.

**Comment by Kiri2002** [comment]
![image](https://github.com/xtekky/gpt4free/assets/125180256/4871fb72-08b8-4121-88c2-9c6863f2ece6)
no support chinese too

**Comment by cssword** [comment]
escaped = answer.encode('utf-8').decode('unicode-escape')
