### ISSUE TITLE
Use proxy accross Quora.Account.Create?

### ISSUE THREAD

**Issue by lfsaga** [xtekky/gpt4free#51]
I would aprreciate to know if you enabled a option for this.

**Comment by lfsaga** [comment]
Also im receiving from differents IPs the next message:
`Your device or network may be sending automated queries. We can't process your request now.`

Is this due to ratelimit or patched method?

**Comment by xtekky** [comment]
could be something else than ip, i will take a look at it

**Comment by xtekky** [comment]
its due to the proxies only being used for the email client, I will fix it soon

**Comment by xtekky** [comment]
fixed in newest update

**Comment by lfsaga** [comment]
Hi @xtekky , Did you upload to `pip3 install quora`?

**Comment by xtekky** [comment]
no, the quora pypi package is not related
