### ISSUE TITLE
500 Server Error: Internal Server Error for url: https://api.mail.gw/accounts

### ISSUE THREAD

**Issue by xtitx0327** [xtekky/gpt4free#515]
When I'm trying to create an account for Forefront, I received the error message: 
```
500 Server Error: Internal Server Error for url: https://api.mail.gw/accounts.
```

It seems to be a problem with the function `register()` in `mailgw_temporary_email`. I've tried several ways to solve it, including using proxies (I live in China). But  none of them worked. Any ideas?

**Comment by xtitx0327** [comment]
I've just tried to create an account on mail.gw manually, and got the same error... So it seems be an error of the website, instead of this repo

**Comment by nlwu** [comment]
i have the same error

**Comment by cabfile** [comment]
this issue is happening for me as well

**Comment by seedlord** [comment]
mailtm works.
install mailtm with `pip install mailtm`
replace line 12 in gpt4free/forefront/__init__py with `from mailtm import Email`

**Comment by elven2016** [comment]
> 

python test.py 
Traceback (most recent call last):
  File "/Users/huangwen/gpt4free/gpt4free/forefront/__init__.py", line 44, in create
    trace_token = response.json()['response']['id']
KeyError: 'response'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangwen/gpt4free/gpt4free/test.py", line 2, in <module>
    token = forefront.Account.create()
  File "/Users/huangwen/gpt4free/gpt4free/forefront/__init__.py", line 48, in create
    raise RuntimeError('Failed to create account!')
RuntimeError: Failed to create account!

**Comment by charbeldaher121** [comment]
pip install tempmail-lol
