### ISSUE TITLE
ModuleNotFoundError: No module named 'xtempmail'

### ISSUE THREAD

**Issue by jianzh5** [xtekky/gpt4free#517]
![image](https://user-images.githubusercontent.com/5998464/236860355-9b90ce31-3424-4c38-965e-fa6bcdde3522.png)

**Bug description**

The computer I use is a mac m1 and I get the error as shown when I execute `docker run -p 8501:8501 gpt4free:latest`

I fixed it with `pip3 install faker pip3 install xtempmail` but it doesn't work

![image](https://user-images.githubusercontent.com/5998464/236861239-1f746d48-ba6f-4fdb-8049-7c51fbe7d72e.png)

**Comment by xtekky** [comment]
can you try running without docker ?

**Comment by jianzh5** [comment]
I don't try docker to work, but I need to modify the proxy

![image](https://user-images.githubusercontent.com/5998464/237012768-789bc20c-3458-43df-8c12-4f0753a89b80.png)
