### ISSUE TITLE
an image in Dockerhub

### ISSUE THREAD

**Issue by choogoo** [xtekky/gpt4free#522]
I created an image in Dockerhub that can be run to use the project.

anyone can pull it use:

```
docker pull atorber/gpt4free:latest
```

**Comment by edvejak** [comment]
> I created an image in Dockerhub that can be run to use the project.
> 
> anyone can pull it use:
> 
> ```
> docker pull atorber/gpt4free:latest
> ```
How to use?

**Comment by stoickk** [comment]
it is still shows "Unable to fetch the response, Please try again."  maybe the problem is my ip address? how to check?
