### ISSUE TITLE
Unable to fetch the response, Please try again.

### ISSUE THREAD

**Issue by shebing5** [xtekky/gpt4free#528]

**Comment by xuexianqi456** [comment]
Same problem
![image](https://github.com/xtekky/gpt4free/assets/43470607/2f54ae35-5951-4292-875b-a4f93c8dacdb)

**Comment by kasoushu** [comment]
same problem

**Comment by hacklinshell** [comment]
> same problem

me too!

**Comment by JacobShang-max** [comment]
same problem

**Comment by LinhanXu3928** [comment]
same problem

**Comment by a1379478560** [comment]
same

**Comment by a415432669** [comment]
same

**Comment by a1379478560** [comment]
你好，邮件收到。

**Comment by qinjinghub2** [comment]
I am deploying to a server in the US so I don't have this problem, my local deployment doesn't work and it looks the same with the proxy on.

**Comment by Zekan** [comment]
from you i get cloudflare responce:
`<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7c59edf82d47161c')"></div>
        <form id="challenge-form" action="/api/streamingSearch?q=hello+world&amp;page=1&amp;count=10&amp;safeSearch=Moderate&amp;onShoppingPage=False&amp;mkt=&amp;responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&amp;domain=youchat&amp;queryTraceId=5c79de28-0359-41b9-9ad1-a694f619f747&amp;chat=%5B%5D&amp;__cf_chl_f_tk=kP4OB_Mwqw6qlsOseOGLmkK1b0XWPgBi7VbNg.GTMic-1683802945-0-gaNycGzNDuU" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="v_9TeoWe0B2ksJKVG1mqLH9z7OjkJ.Hr.4HL3oomqKA-1683802945-0-AVoQQ65GeRf-e4ehV2cEd5ea_g8pxzQbqFVjY3WpI3yLscvCTdVEpimbuFwiFNVZJFukZ0sT5F4jzjBs07xqQPyOFvNf2a5bcA6FIaQ3rbheSkmvOZzLPSPISq0kExhks7V8Upkl7CZ-CklguNEB9BJ4mW88zhpfmipdgd8lvt56IOqObcmXcSKIamJwO6uXkwc0jDWA664xuog_lgClmvw56c2EZgcRh5rUb4Ao2FtJeQpxr869ilY0IaTyEyHskBpWr6AUCYqXeXAw5rsdpIpSP1HYFJEdn2lex9bfhuvDNGigrkbvrn04S9H6KXedceaiud-kgY8TvANEEeSMMXein8S9I8MYrl0j_McQ3dFCYmaYizI7x4o1miF4eneqtoEX9U7DykMBmdljhfkIpvSri442uFvrNz-xi1Vs3qCSOJRaCnEAQx_x_8alofxMuA_VaZ-Q5x7yCTMVx2CRwLXUDd-LB6XCWPq7fUWL027PEJ1eF_36Sp68sTgWhhyzsq6DZmdnZxO2ke4OgxNWV3qjGbG__iMK4_sbnobkWr44RkKP1BqTl6a1zO8LVmBOCEBwWGziiQUGmq7U8zlyefJ540KsigSO1CredxudfJp0bBWic3liJYC_2OBNZmif4u9fGOsvAXChAMzSCmbpmXlEC8b5KbZf330FhZz9A7JpE3DASCJlIXCxi7vkFHMHEXSnPkEYsJkjbFKb6hoQi7qBe9TsrC4p0CwQmGHwcGL0qg521Wi7tX6k3vZtrswgnMDJKKGdVVPaZnlJZsaxc_caoACNEwb--L5d8aL375OzBT8vttWR43kPgdeSAxTz7D0risOy3Ez42pSG-WvAA_PXEx-1i5Va1SQLYWZmeMv6uh7PgKXRSVDxynHxBrW48bJRaq0hJqBi0jRnbhOTJ_FQ_iZ43-NLLiiISpnR-V-A7gDURpSPitn97PgGY6gWVga3mTyd0haB38IZ9yphjNkXr8qHsIWijsRqMDDsFGgE1MJjNXMGJHUipvecexoE9YDiNQ36OBwr9RcsDiMoWbbW9f0E41k95RBEnGDyijKpEoLy47Ix863JAyD2AGDz9YVN-DPz-RCYvFb7X-tVRCo4wCDRHi5vgy4LL9mJ2PKnhkRNB-ej_UqdtqKq29YuYcn3bSGJMMPdMp7Sycomy1HiE4Pmg-aFWC9SS-K45MIRMDzuGg8hi-jwYpu0MBTKnG0oAe0sPr8YhjwJ56nO5EjXJbe02KoGkfeXGWXDN7Om_WTGc11p8kTbVTFHOfhi2jBL0prnBPDXKevExH546XSeGujY1-yyqILdOVLN60PyedrGhT3X8wzwGvDdI5tY1cUWs6rjzxFamMa1g_b6CS5FWZqIdoy4BGrvn6i2BrzjZsfuEDQkajw8d3QuDeA6s0pSX3YDqzcB1jac4a2w9XrpNxDHANAyYTCC6L4TiyZJe9uiaKe9o8f7KcHcoEkkX5N2IWLtXefGggYErafJJ7wrdHcydvl6ZckLAmO5hIKCUX7FoVuwSw7CAAJfmiznZ76uGZSjZwL-9Pbnd54Ub5RQLqc98n4ecsA-18T7_xPDI8aOViv78y3T82FVEZypZ-F4C6zumSsRP03yslM-QuoxMsExpbDDkwp9vXKdkeNaVA6pOc4f8FX_5ZIBnAnKYlhxZ0S99SMM4I4osH7yTsjciWh4enhqDGfbqvBeU5fjM7RuOsQNAW8FGaw6_DoS51xGNghaqS5UuamYxHa4kHM7CjbdT240n6ai9i2PVKVa7dXw8_Tf_aAy5EWPr8JVNRo3Ddr9MfPev-aGpBD0P_May63nYZ0LyRZvRGySMMBsq5y_9QACnfmgP18oYZoilNU0BStFdhWeLdhlEP3ZyN7-0ZVWE6c6YdKVTX5_xI839EkvFMw_1PveSEeJlVfZUsxzglsLbR5b6U_b7XCyXNyWWbANRtKlT1-J8EG-5Y1__wzEtx5SSJHwn7jLa1EqTeUlcB0sGpy8lBzo7TISU_G_33rRFrc4DYiFE-JUeq8zpaNhTQfWLea1tNgr56GgYE35MtX9U5vQzibb_n9GnfW4hzLlvRrozTjK46YecEtMijH0WoL4ciidIXf0JUXJxWaTgpnuuWNkFQo2no3186U6spM0gDTisztWQFZNjF_X0uFJE2Vi5iI6SVHZJr6BkjtC0afha4A6p7pIhdIh5l-Xv-T2sRCcEJ6AsV94dbe02XeaX_of4kNu7OCr1IXW6AMGuNbj3C3MtdtVMoPOF7ofA3yBOkQ_wWeoUsCtMvF-faEBtgnZ_eUfSzz0hxI4aYTMbvmWXKDNp_Ls6DEN43xaois6xVaQA-qcH5z_s38YL3M4uRawCVfa6ii4NM8GenZV3kjzBP1t1KAQV9byJw6iyPA9WXClMZS10nYds43IqLvPS1moBbYH01xw22Gl379RpkvvoaOUH1cM7TmHImyZRj0ckhEeQglfHqFaN-LuRn9J17a2AR0cIIcDoVd1A_rGiFdRg_YVPf-L12HzVVnMwRTg-8XKu9NMF5iAdGE1zOWjlXSZra9Zfgvmxz3s_ITvewt1rw86Cew2fNAwtI6hkgmj9rvm3f4FjziA5NoMWg_Py2Od-KukLVE-GZu38PgfJIpWHfXnH6uBXKJAxzIm60f8JQ84sAQOjPkM-Ig0QCkwEn-rkPOzsvxcLGS7GSJbSLHoPCRv8O6gLnBnwvevpUpQQf9j4-TwBbhtaqvtHtm9WDdWp6s_9D8h-14LD6Ism-ri7j9KKK_5-3A7nY0rMirfgEnkqGSPGGLhEOG1xfd5jDpjV5ZnLsPbyGiq_HXBX82WNgvt_L4Tm0yp6d93THdVI4G4Ce3NziSrK2f18Mnewv_T24bqx3LIQisoo9NmZRq6EsyObkgJmJTT2K1LYSuQmdVGVzlTE2ByE9ywbaFBxNvgMp1tHGcVPkPax2FBbBuon6goly08gu0W1LMv1XWxFoe457Cbo5jLT0Cv4NU0xAkbUQeNiyk--URfof2eJJb9EwWADhi6aqPlGPVkmwCydorgLX3iIgnUJMcSJhfJpZlxm0x0bxoA_mTg8R_wx4BefIe-W6Y1my36Z5MA0I5EJf6saTeuht3KY36bScbTeKCNqzWmlKX0qQazibWrIHXrkCy48fRjSZGHXwZWxYvWR6FIfkoNl-WyxpkOa9x8HKAK18uZOqEZx1ce2z5lKm4w63XyHyxod3QoyW_r4q4mlbizo6EYAe88eeRsitmg4ysN15DDsU7AB5jv6uRtZjJKSP93gqFz3Aivw-Zf2ldJbuC8QC9I_O-ZumLPgNCO3gbn6VNVbfAqAxKuOHtzJ69OBjZZBOguUc7btPC9QL2Kag5CjIpv01NuJ8ZRxmL-g4ynfXR5GA14ud2HEuvu-awJzZ6ZdNKO-rp_BRFCmMLACmYwN3ix_Sq5yCJkkSZUweYxeOeviDWXReDH8vljzvSvp-BTBy7JvQ4W_riVGD82uc_WxfjOf0ysPdLeEDJp91zBhuk71DCXOn8JDMithfCdJqbXWFM9LsujI2kOVMKJtCqv4kDqWq2dCfeHoFprbLTVCYCl0CPEk-SoUnRzgqYMF8ABawVNi3FBJr9AtDbufUB3dRs6j2pRv6PkegwpZTZmCJIffvvBy4R3XLFOOD4gyuGanP4BkI7v-vXWyAbFLhNwCkhPtwOEQN35et-6rHYnNV_hNBdhsZ74mKmZspDQK84JWkWpXNIIgHWnZhkr8v32MMEuqJsvH1-u">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'you.com',
            cType: 'managed',
            cNounce: '99907',
            cRay: '7c59edf82d47161c',
            cHash: '27dd78f35ae9ff2',
            cUPMDTk: "\/api\/streamingSearch?q=hello+world&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=5c79de28-0359-41b9-9ad1-a694f619f747&chat=%5B%5D&__cf_chl_tk=kP4OB_Mwqw6qlsOseOGLmkK1b0XWPgBi7VbNg.GTMic-1683802945-0-gaNycGzNDuU",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cMTimeMs: '0',
            cTplV: 5,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly95b3UuY29tL2FwaS9zdHJlYW1pbmdTZWFyY2g/cT1oZWxsbyt3b3JsZCZwYWdlPTEmY291bnQ9MTAmc2FmZVNlYXJjaD1Nb2RlcmF0ZSZvblNob3BwaW5nUGFnZT1GYWxzZSZta3Q9JnJlc3BvbnNlRmlsdGVyPVdlYlBhZ2VzJTJDVHJhbnNsYXRpb25zJTJDVGltZVpvbmUlMkNDb21wdXRhdGlvbiUyQ1JlbGF0ZWRTZWFyY2hlcyZkb21haW49eW91Y2hhdCZxdWVyeVRyYWNlSWQ9NWM3OWRlMjgtMDM1OS00MWI5LTlhZDEtYTY5NGY2MTlmNzQ3JmNoYXQ9JTVCJTVE',
                ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzY0LjAuMzI4Mi4xNDAgU2FmYXJpLzUzNy4zNiBFZGdlLzE4LjE3NzIw',
                rm: 'R0VU',
                d: '7urgJbbYcwhL2nGwpfb15FPIHR5Ho1aW36BwXer6pcaEa8RwmHY3Q2zCOYdsE62w8UWAjovyIwFmD/7xwCPUUxSe5eP+c4qobZnNZDh66F+sai5O67lJFkhj0imC35yJV0hA0cecHGLYQCbahVcbM38c6ZlTehRV0C6XO0haPMREUhRr2eLDtcknieARHES8L39Pw1fFapcb7guvfLawB2RaWZuLyxhgS+xX7oykIttdb/Qgoex5DGULTLZlbPDebpksy3aKNJTIk2GrOOOovJCavZuEpvs96+K8woJjRt0FG5XuUQf1JwDCQy4sHsnuOGt6OqlH6qh2MhlJ1TRn2hbJvZ1D9TpgkaexzHaauwGwiFj9h8VMr2tsGCI73aRCXjCH2O16wRPvwhdactPXOk3A4cS9ZkgBuPMfCFW0izF56APu01/Wihwf5xrIZxDlXstk+77V3YGmQG6r9XNr8Y9GorA82s0SkJvqq/qvMKiQhtyPVpvburwcJ+azTnbI1ChMCgwlWGVaxFJbhtwGIXHPb/yijpf9x7m0X8a4RZPY/csqmrJNclpVAeGGPp3obSVIa8URNNgOfk49avi9RsVc7MAnB+ClciaJgYELeBdA6FbVpzz2bj+CHCpUuRdx',
                t: 'MTY4MzgwMjk0NS4zMTIwMDA=',
                m: 'YST8BHwuS5p/8PZIQ/zjikJtdTKa/k08Llvg7ETZMvQ=',
                i1: 'e+PEkphA5zDnt7bReJqFOg==',
                i2: 'jVAmj9FRJcDdu0GHXpYXOw==',
                zh: 'BU21EkXYP+I6NEpAg17QVB4TEcOw1l6tGo/69Ra4gqc=',
                uh: 'vcG6IVmSwbXXUvTbl67KXvTS/JKGF2negV9qsAB/IVc=',
                hh: 'cNfrIzsKSTr4mqRDNa0YE7odWG0r8ob93axg8HGA798=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=7c59edf82d47161c');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/managed/v1?ray=7c59edf82d47161c';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/streamingSearch?q=hello+world&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=5c79de28-0359-41b9-9ad1-a694f619f747&chat=%5B%5D&__cf_chl_rt_tk=kP4OB_Mwqw6qlsOseOGLmkK1b0XWPgBi7VbNg.GTMic-1683802945-0-gaNycGzNDuU" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>


</body>
</html>
`

**Comment by kdxq** [comment]
same

**Comment by fawdlstty** [comment]
same problem

**Comment by hydehk** [comment]
I have the same problem now.
I used to be able to use it with VPN setting to US yesterday, but today it doesn't work.

**Comment by ds6ga6** [comment]
same problem

**Comment by maxens-git** [comment]
same problem

**Comment by zaijie001** [comment]
same problem. The first time it worked, but the second time I started getting that error.

**Comment by farhanfHARAHAP** [comment]
same

**Comment by rawmaofat** [comment]
So, how should I solve this problem?
