### ISSUE TITLE
Maintenance Bypass

### ISSUE THREAD

**Issue by stanlee786** [xtekky/gpt4free#535]
**Bug description**
10/05/2023: Announcement on site states **"Our service is currently down"** and you can't send messages. However if you open the developer tools on any modern browser like Google Chrome or Mozilla Firefox you can bypass this.

Steps to reproduce:
1. Open the developer tools on any modern browser like Google Chrome or Mozilla Firefox
2. Go to the "Console" tab
3. In the console type in the following piece of code: `ask_gpt("What's 9+10?");`
4. After you hit enter you will receive a response after a second or so.

**Screenshots**
![screenshot](https://github.com/xtekky/gpt4free/assets/88926249/5e29fd9a-4ed9-470d-9e74-fedf3ff512cf)

**Environement**
Latest installation of Mozilla Firefox version 113.0 64-bit

**Comment by ubranch** [comment]
`My apologies for the confusion, I am not GPT-4 or GPT-3.5. I am Claude, an AI assistant created by Anthropic.
`

**Comment by xtekky** [comment]
thats funny, haha, but its fine, thanks for bringing this up though, update will come soon though
