### ISSUE TITLE
有安装成功的吗？

### ISSUE THREAD

**Issue by hanksandy** [xtekky/gpt4free#538]
1、先是问题一
![image](https://github.com/xtekky/gpt4free/assets/49809805/83663a33-e911-437e-b88e-43b462a1fa0d)
这个问题解决了之后中
![image](https://github.com/xtekky/gpt4free/assets/49809805/f9e53a1c-3d7c-4e68-abfe-943fc22c7866)
2、再是问题二
![image](https://github.com/xtekky/gpt4free/assets/49809805/41d465ff-6a38-4098-beb0-7500ed467bb0)

3、感觉不断的问题，就是没看到成功。。。

**Comment by chao-eng** [comment]
需要手动添加代理

**Comment by nongfu9woo** [comment]
在streamlit_app.py中，给result添加proxy代理，如果还是出现同样的问题，换一个节点

**Comment by heyjie** [comment]
加个代理就可以了
![image](https://github.com/xtekky/gpt4free/assets/41108496/75eee72a-8382-4aaa-a0ee-c95359693d08)

**Comment by xiaoyao20084321** [comment]
> 在streamlit_app.py中，给result添加proxy代理，如果还是出现同样的问题，换一个节点

我的You添加代理后成功返回数据了，但是Poe的添加代理还是失败，提示tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://poe.com/login": unexpected EOF，这是什么原因

**Comment by Oraer** [comment]
> 

我在服务器上配置了科学上网，我使用的是docker-compose部署，那么我该如何在容器中添加proxy代理呢？

**Comment by ZHDeveloper** [comment]
这gpt能返回中文回答吗？

**Comment by xxz1968** [comment]
添加代理也没用，这不是梯子的问题。不管改不改代码，都是一样。
![image](https://github.com/xtekky/gpt4free/assets/106124875/58bdb174-43f7-4bbe-b87f-ed3bf408635f)

**Comment by Michael-C-H** [comment]
> 

同问，我的回复一直是英文

**Comment by ipdor** [comment]
应该是网络问题，我的国外服务器直接可以运行gui并对话（couldn't find ffmpeg的提示不影响），简单试了几次没有出现retry。倒是gpt4free/you/readme.md的例子对话中有时会出现retry。

**Comment by Michael-C-H** [comment]
有配置项可以配置默认返回的语言是中文的吗？

**Comment by xxz1968** [comment]
我也安装了ffmpeg，运行也正常，但还是一直提示我C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by xxz1968** [comment]
安装似乎也很简单，也没有调用API，这么简单的安装用改没有什么问题，但是就是无法运行，是不是API的问题

**Comment by nongfu9woo** [comment]
我是本地运行(不会用docker)，在streamlit_app.py中，添加代理result = you.Completion.create(prompt=question, proxy="127.0.0.1:10809") # 改为自己的端口号，如果提示unable to fetch，换节点。至少目前我碰到的问题就是这样解决的。

**Comment by nongfu9woo** [comment]
> > 我是本地运行(不会用docker)，在streamlit_app.py中，添加代理result = you.Completion.create(prompt=question, proxy="127.0.0.1:10809") # 改为自己的端口号，如果提示unable to fetch，换节点。至少目前我碰到的问题就是这样解决的。
> 
> 我you也可以运行成功， 你换成poe试试可以不

没有poe的包吧，
![图片](https://github.com/xtekky/gpt4free/assets/49931174/601c4e3a-d5a8-4586-a600-8124a8a5fb8b)
换过forefront的，因为机器人验证的问题，没法用

**Comment by xiaoyao20084321** [comment]
> 

quora，就是poe

**Comment by jzboy** [comment]
> quora，就是poe

我换成quora和forefront都没办法使用，提示这个An error occurred: Completion.create() missing 1 required positional argument: 'account_data'. Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by nongfu9woo** [comment]
> > > > 我是本地运行(不会用docker)，在streamlit_app.py中，添加代理result = you.Completion.create(prompt=question, proxy="127.0.0.1:10809") # 改为自己的端口号，如果提示unable to fetch，换节点。至少目前我碰到的问题就是这样解决的。
> > > 
> > > 
> > > 我you也可以运行成功， 你换成poe试试可以不
> > 
> > 
> > 没有poe的包吧， ![图片](https://user-images.githubusercontent.com/49931174/237609529-601c4e3a-d5a8-4586-a600-8124a8a5fb8b.png) 换过forefront的，因为机器人验证的问题，没法用
> > quora，就是poe

你是怎么使用poe的？我试了下仓库里提供的几个demo，一直卡在token的问题，卡在waiting for message就走不下去了

**Comment by DETALA** [comment]
换了一万个节点，香港和日本的都不行，最后还是美国的可以用

**Comment by xiangsx** [comment]
这里目前应该都不能用了把，等作者忙完会回来维护的，别着急


可以先用ts版本的
https://github.com/xiangsx/gpt4free-ts

**Comment by s123456-max** [comment]
限制字数啊 这个太难用了

**Comment by whz11** [comment]
> > 
> 
> 我在服务器上配置了科学上网，我使用的是docker-compose部署GPT4free，那么我该如何在容器中添加proxy代理呢？

你可以在配置项中将原本的地址localhost改为host.docker.internal，这样docker会用你宿主机的地址

**Comment by DETALA** [comment]
我的本地网址也不行，但是换另外一个192的可以，不过说实话，我用起来效果很一般，还没3.5好用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xtekky/gpt4free"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 中午12:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xtekky/gpt4free] 有安装成功的吗？ (Issue #538)





 
应该是能安装成功了（也装了ffmpeg，运行没报错），但就是用不了(部署在国外服务器上的)
 Ctrl+Enter提出了问题，但并没有返回消息（过很久才返回“Unable to fetch the response, Please try again.”）；
 点Think命令行界面就返回一个个 retry...

**Comment by huguiqi** [comment]
<img width="959" alt="image" src="https://github.com/xtekky/gpt4free/assets/490617/f7b93681-c37e-48f8-a182-2048f83092fc">
成功搭建好

**Comment by yang50825** [comment]
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Python返回的信息，
Unable to fetch the response, Please try again.
GUI返回的信息，
楼主问题解决了吗

**Comment by wwfcnu** [comment]
> <img alt="image" width="959" src="https://user-images.githubusercontent.com/490617/239164485-f7b93681-c37e-48f8-a182-2048f83092fc.png"> 成功搭建好

请问大佬是怎么搭建的

**Comment by haobarry** [comment]
> 在streamlit_app.py中，给result添加proxy代理，如果还是出现同样的问题，换一个节点

怎么添加？

**Comment by huguiqi** [comment]
> 

代理节点换成台湾或者新加坡

**Comment by yang50825** [comment]
> 在streamlit_app.py中，给result添加proxy代理，如果还是出现同样的问题，换一个节点

怎么设置

**Comment by yang50825** [comment]
现在我把proxy的http前缀去掉了，但是返回英文，不会联想上下文，感觉挺一般的

**Comment by yang50825** [comment]
![image](https://github.com/xtekky/gpt4free/assets/102711398/738f1fd6-fb4d-4977-b384-f92a3f939140)

**Comment by joeaki1983** [comment]
you可以用(需要在_init_.py里面加上代理，但是非常难用，经常返回英文，丢失上下文， 改成forefront之后， 提示 An error occurred: Completion.create() missing 1 required positional argument: 'account_data'. Please make sure you are using a valid cloudflare clearance token and user agent.   搞了半天搞不定。

**Comment by make-a** [comment]
> 这gpt能返回中文回答吗？

``` python
def get_answer(question: str) -> str:
    # Set cloudflare clearance cookie and get answer from GPT-4 model
    try:
        question = "请使用中文回答我的问题\n" + question
        result = you.Completion.create(prompt=question, proxy="127.0.0.1:7890")
        decoded_str = bytes(result.text, 'utf-8').decode('unicode_escape')
        return decoded_str
```
在文件streamlit_app.py里改一下就行，把用中文回答加到你的问题前面，然后这里的decoded_str是需要对返回的数据解码，不然就是乱码了，反正我是这么做的哈哈
![image](https://github.com/xtekky/gpt4free/assets/80375078/5c1e790a-141d-48b3-ae64-f1f99aa970e2)

**Comment by wwfcnu** [comment]
> 

原来如此

**Comment by cscainiao** [comment]
![image](https://github.com/xtekky/gpt4free/assets/38780513/2d9cfbf9-599e-4c97-bf7e-1ad59e884c81)
这里改成自己的端口只的是运行的端口吗，比如我的访问链接是http://localhost:8501/    那么我这就改为8051吗

**Comment by cscainiao** [comment]
![image](https://github.com/xtekky/gpt4free/assets/38780513/c16c9a9e-cff9-4531-a811-772f1e884f80)
返回这种需要改哪里呢

**Comment by tignioj** [comment]
已经设置了代理，换了几个节点仍旧显示无响应`Unable to fetch the response, Please try again.`
```python
# result = you.Completion.create(prompt=question)
 result = you.Completion.create(prompt=question, proxy="127.0.0.1:7890") 
```

**Comment by 2658548663** [comment]
成功了，很容易，但是感觉挺一般的

**Comment by nqf** [comment]
https://github.com/fantasy-peak/cpp-freegpt-webui

**Comment by hozeeee** [comment]
> 这gpt能返回中文回答吗？



> 我是本地运行(不会用docker)，在streamlit_app.py中，添加代理result = you.Completion.create(prompt=question, proxy="127.0.0.1:10809") # 改为自己的端口号，如果提示unable to fetch，换节点。至少目前我碰到的问题就是这样解决的。

我看了一下代码，docker运行可以考虑在 g4f/api/config.json 添加 proxy 配置，这个文件默认没有，需要创建
