### ISSUE TITLE
git clone a project and find it useless

### ISSUE THREAD

**Issue by Hzzhang-nlp** [xtekky/gpt4free#544]
**Known Issues** // delete this
- you.com issue / fix: use proxy, or vpn, your country is probably flagged
- forefront account creation error / use your own session or wait for fix

**Bug description**
What did you do, what happened, which file did you try to run, in which directory
Describe what you did after downloading repo, such as moving to this repo, running this file.

ex.

**Screenshots**

**Environement**
- python version
- location ( are you in a cloudfare flagged country ) ?

**Additional context**

**Comment by Hzzhang-nlp** [comment]
![image](https://github.com/xtekky/gpt4free/assets/39661319/57b04479-7357-46ad-8cf2-d1e4fda65a04)

**Comment by Hzzhang-nlp** [comment]
无论输入什么需求，都无法获取响应

**Comment by 397278900** [comment]
1. Check the proxy in the init file
2. Try to use US servers

**Comment by gameuser1982** [comment]
VPN doesn't seem to work for some reason. I tried to use a vpn that I know is unblocked for chatgpt but it gives that error. The fix I found was using a proxy.

1. Updated the cloned repo via `git pull order main`

2. Entered the following commands:

```
git fetch origin pull/504/head:ff_fixes
git checkout ff_fixes
```

3. Modified streamlit_app.py in the following line: `result = you.Completion.create(prompt=question,proxy='myusernamehere:mypasswordhere@12.198.49.4:32222`)

change myusernamehere:mypasswordhere@12.198.49.4:32222 to your actual http proxy.

launch with `python -m streamlit run streamlit_app.py`  (you may need to change python to python3 depending on your python installation)

**Comment by Hzzhang-nlp** [comment]
The method you said still doesn't work。

**Comment by kigner** [comment]
https://youtu.be/aisZpYTHq3o 看这个视频的置顶评论。
