### ISSUE TITLE
you.com challenge-form

### ISSUE THREAD

**Issue by iaston** [xtekky/gpt4free#546]
![image](https://github.com/xtekky/gpt4free/assets/11807657/f7e8e347-3896-4272-a55e-8710ef767a08)

When using you, I encountered a request for human-machine identification, response code: 503

Has anyone encountered it and how to solve it?

**Comment by enganese** [comment]
I encounter the same issue, even tho I randomly use one of my 10 proxies by shuffling them. How to solve? Proxy doesn't help!
