### ISSUE TITLE
CHEATER: GPT4 in website is actually gpt3

### ISSUE THREAD

**Issue by vaibhavard** [xtekky/gpt4free#55]
Why are you misleading people?

**Comment by xtekky** [comment]
Hi
- this has nothing to do with this repo
- the website is opensourced
- this repo provides free scripts to use gpt-4
- The gpt-4 option on my site is not functional yet but will be in the future
- nothing prevents you from using other services providing gpt-4
- I am providing a free service and you are freely hating on it
- please just go look for another service, you are not welcome here

**Comment by vaibhavard** [comment]
@xtekky 
Really Sorry, just was frustrated to find that **i cannot access gpt4** from anywhere!. (I have a great idea in mind , but i cannot implement it just because of openai's policy of keeping gpt4 paid)
Spent many hours trying to access GPT4 , but to no avail. Infact , many github repos , website (ora.sh) , and other platforms .. which promised access to _gpt4 also turned  to be fake and instead in reality gpt3 was being Used._

I myself had try to reverse engineer poe , but it took many hours and ultimately poe blocked the temp email i was using (recaptcha)

I thereby understand how much time and effort it took for you to make this whole repository which also without any incentive. Its great that you devoted your time and effort to this and i now acknowledge this effort completely! 

**Thanks for providing this repository to the open source community , extremely sorry for the earlier message , i take it back and i regret for the inconvenience caused to you by this.😟**

Infact , the entire open source community is really essential for me , since it has played a great part in helping me build my projects. That's why , it important for me and (maybe others like me) to encourage other and to not dissapoint them...

![image](https://user-images.githubusercontent.com/57561743/233620345-cc3f4f9b-4843-4bb7-828d-89de9a26f548.png)
