### ISSUE TITLE
Unable to fetch the response, Please try again.

### ISSUE THREAD

**Issue by AlwaysZmx** [xtekky/gpt4free#552]
![IMG_20230514_171809.jpg](https://github.com/xtekky/gpt4free/assets/29172927/6263b9db-3362-4c5b-b043-80b62213a61b)

**Comment by kigner** [comment]
https://youtu.be/aisZpYTHq3o

**Comment by shebing5** [comment]
> [https://youtu.be/aisZpYTHq3o ](https://youtu.be/aisZpYTHq3o)
this is wrong

**Comment by windosx** [comment]
@AlwaysZmx network problem
If you deployed by docker, modify `docker-compose.yml`, uncomment the following codes:
```yaml
   ...
    # environment:
      # - http_proxy=http://127.0.0.1:1080 # modify this for your proxy
      # - https_proxy=http://127.0.0.1:1080 # modify this for your proxy
    ...
```
Then rebuild docker image & re-run.

If you run in command-line, just add `HTTP_PROXY={PROXY}` and `HTTPS_PROXY={PROXY}` to your environment variables.

**Comment by AlwaysZmx** [comment]
> @AlwaysZmx network problem If you deployed by docker, modify `docker-compose.yml`, uncomment the following codes:
> 
> ```yaml
>    ...
>     # environment:
>       # - http_proxy=http://127.0.0.1:1080 # modify this for your proxy
>       # - https_proxy=http://127.0.0.1:1080 # modify this for your proxy
>     ...
> ```
> 
> Then rebuild docker image & re-run.
> 
> If you run in command-line, just add `HTTP_PROXY={PROXY}` and `HTTPS_PROXY={PROXY}` to your environment variables.

我是用railway部署的，正常来说不用代理应该就可以正常访问的

**Comment by aboelf** [comment]
It's network problem.don't use hongkong proxy.use japan or usa.

**Comment by aboelf** [comment]
> > @AlwaysZmx network problem If you deployed by docker, modify `docker-compose.yml`, uncomment the following codes:
> > ```yaml
> >    ...
> >     # environment:
> >       # - http_proxy=http://127.0.0.1:1080 # modify this for your proxy
> >       # - https_proxy=http://127.0.0.1:1080 # modify this for your proxy
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then rebuild docker image & re-run.
> > If you run in command-line, just add `HTTP_PROXY={PROXY}` and `HTTPS_PROXY={PROXY}` to your environment variables.
> 
> 我是用railway部署的，正常来说不用代理应该就可以正常访问的

就是网络问题，用docker部署的，设置好香港代理发现还不行，改为日本节点就可以了。

**Comment by sz-winner** [comment]
我本机用clash梯子，在you\_init_.py加了一行本地代理地址和端口号后，问题解决了
![image](https://github.com/xtekky/gpt4free/assets/58689499/3a04486e-9414-40a8-9161-6e5351bfb329)

**Comment by make-a** [comment]
> 我本机用clash梯子，在you_init_.py加了一行本地代理地址和端口号后，问题解决了 ![image](https://user-images.githubusercontent.com/58689499/239479015-3a04486e-9414-40a8-9161-6e5351bfb329.png)

我的这样也可以了
