### ISSUE TITLE
Incorrect Python version

### ISSUE THREAD

**Issue by adamruehle** [xtekky/gpt4free#556]
After cloning the gpt4free repository (into a OneDrive folder on Windows), I am able to set up the virtual environment. However, running ``pip3 install -r requirements.txt`` gives this error ``streamlit-chat requires Python '>=3.8' but the running Python is 3.6.8``. It appears that Python 3.6.8 is installed under the ``venv/bin`` directory. I'm not sure how I can fix this problem.
![image](https://github.com/xtekky/gpt4free/assets/75347356/d1c8b681-e0c0-4f4e-963c-5a1a04ff7f2a)

**Comment by Wudext** [comment]
You should install Python 3.8 or higher to use this API, it`s definetely not an xtekky`s issue.
