### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by Zaidbaidadekalb** [xtekky/gpt4free#558]
Every time i run 
``
python3 -m streamlit run streamlit_app.py
``
i get this error 

ModuleNotFoundError: No module named 'Crypto'
![aasdasdasd](https://github.com/xtekky/gpt4free/assets/87798207/9656db7e-fa71-4f5f-a61d-a5bb986b8430)

**Comment by sondo2503** [comment]
Run this command
```python
pip3 install pycryptodome
```

**Comment by coderwpf** [comment]
> 
python 3.11 error ModuleNotFoundError: No module named 'Crypto'

**Comment by dsshvetsov** [comment]
I have the same error. module installation did not help((

**Comment by enganese** [comment]
### **The error occurs for multiple reasons**:
```
1) Not having the pycryptodome package installed by running pip install pycryptodome.
2) Installing the package in a different Python version than the one you're using.
3) Installing the package globally and not in your virtual environment.
4) Your IDE running an incorrect version of Python.
5) Naming your module crypto.py which would shadow the official module.
6) Declaring a variable named Crypto which would shadow the imported variable.
```


Reference: [Solution of this issue](https://bobbyhadz.com/blog/python-no-module-named-crypto)

**Comment by bestK** [comment]
``` shell
python3 -m venv venv
# in windows
& d:/workspace/gpt4free/venv/Scripts/Activate.ps1
# mac or linux
. venv/bin/activate
pip3 install -r requirements.txt
# testing
mv  .\testing\forefront_test.py .
py .\testing\forefront_test.py  
```
![image](https://github.com/xtekky/gpt4free/assets/14979305/b2a434e7-113b-43b8-9362-a9779b9658a3)
