### ISSUE TITLE
what should I do to solve this problem

### ISSUE THREAD

**Issue by jian2Entic** [xtekky/gpt4free#565]
An error occured, please make sure you are using a cf_clearance token and correct useragent | Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations: CAfile: E:\Desktop\工具\gpt4free\venv\lib\site-packages\curl_cffi\cacert.pem CApath: none'

**Comment by editor-syntax** [comment]
make sure you have valid cf_clearance cookie
