### ISSUE TITLE
deepai Unauthorized for url

### ISSUE THREAD

**Issue by k1287988804** [xtekky/gpt4free#572]
Traceback (most recent call last):
  File "c:\MyProjects\gpt4free\gpt4free\test.py", line 15, in <module>
    for chunk in deepai.ChatCompletion.create(messages):
  File "c:\MyProjects\gpt4free\gpt4free\deepai\__init__.py", line 56, in create
    r.raise_for_status()
  File "C:\ProgramData\Python10\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.deepai.org/chat_response

--------------------
I was able to get data normally before, but suddenly it doesn’t work, has it been detected? 😢

**Comment by k1287988804** [comment]
It work now，I didn't do anything

**Comment by ading2210** [comment]
Your IP may have been banned or rate limited. I might add some sort of automatic proxy selection in the future though.

**Comment by noes14155** [comment]
Needs automatic proxy. After 10 requests server automatically blocks that IP. Unauthorized after that

**Comment by JinhuaLiang** [comment]
Hi guys, any idea how to fix this issue? I think the above comment makes sense as I was banned after 26 response. Yet I have no clues to solve this. Any help would be appreciated.

**Comment by Aryan2-1** [comment]
I'm getting same please any solutions

**Comment by xBigPanda** [comment]
me as well

**Comment by xBigPanda** [comment]
solution: make a deep ai account, log in, go to profile and copy api key, then replace the "api_key":api_key in the headers in deepai.py file with "api_key": api_key u got from ur profile

**Comment by amit-pathak11** [comment]
This API is no more working after 7-10 responses, it gives the "Unauthorized" error. I tried with different proxies and still not working!
