### ISSUE TITLE
Test forefront fail

### ISSUE THREAD

**Issue by johnson-jo** [xtekky/gpt4free#583]
Test forefront with below codes, it seems not work. 

# create an account
        token = forefront.Account.create(logging=True)
        print(token)

        # get a response
        for response in forefront.StreamingCompletion.create(token=token, prompt='hello world', model='gpt-4'):
            print(response.text, end='')

Error Msg:
An error occurred: local variable 'response' referenced before assignment.

**Comment by xtekky** [comment]
forefront is currently patched
