### ISSUE TITLE
poe account creation [help needed]

### ISSUE THREAD

**Issue by xtekky** [xtekky/gpt4free#60]
I have successfully integrated a gmail temp client, but i am recently getting these errors:
```
{'data': {'sendVerificationCode': {'status': 'automated_request_detected', 'errorMessage': "Your device or network may be sending automated queries. We can't process your request now."}}, 'extensions': {'is_final': True}}
```

even when using proxies, a proper recaptcha solving service, tls and double checking params, this was still occuring and I am clueless what's causing this issue, if you find out please let me know

**Comment by ItsJustTomDev** [comment]
https://smailpro.com/api

**Comment by DanielShemesh** [comment]
[(https://www.emailnator.com/](https://www.emailnator.com/)

**Comment by localuser-isback** [comment]
I also second SMAIL pro, its never banned because its actual gmail accounts!

**Comment by taiyi747** [comment]
hope this code can be helpful for the project

```python
import requests
from time import sleep
from re import search, findall
session = requests.Session()
response=session.get("https://www.emailnator.com/",timeout=10)
cookies=session.cookies.get_dict()

headers = {
    'authority': 'www.emailnator.com',
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'en-US;q=0.6',
    'content-type': 'application/json',
    'origin': 'https://www.emailnator.com',
    'referer': 'https://www.emailnator.com/',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36 Edg/101.0.1722.39',
    'x-xsrf-token': cookies["XSRF-TOKEN"][:-3]+"=",
}

session.headers.update(headers)
json_data = {
    'email': [
        'domain',
        'plusGmail',
        'dotGmail',
    ],
}

response =session.post('https://www.emailnator.com/generate-email',json=json_data)
email=eval(response.text)["email"][0]
print("email:"+email)

json_data = {
    'email': email,
}
print("Start receiving verification code")
while True:
    sleep(3)
    mail_token=session.post('https://www.emailnator.com/message-list',json=json_data)
    print(mail_token.text)
    mail_token=eval(mail_token.text)["messageData"]
    if len(mail_token) == 2:
        print(mail_token[1]["messageID"])
        break

data = {
    'email': email,
    'messageID': mail_token[1]["messageID"],
}
mail_context=session.post('https://www.emailnator.com/message-list',json=data)
print(mail_context.text)
code=findall(r';">(\d{6,7})</div>', mail_context.text)[0]
```

**Comment by xtekky** [comment]
awesome !! Will check it

**Comment by wangjiegui** [comment]
please try using a proxy / wait for fix
send_code {'data': {'sendVerificationCode': {'status': 'automated_request_detected', 'errorMessage': "Your device or network may be sending automated queries. We can't process your request now."}}, 'extensions': {'is_final': True}}
waiting for code...                         I encountered the same problem

**Comment by localuser-isback** [comment]
I recommend using residental proxies as they match the IP's of actual services like AT&T they can be expensive in bulk but are totally worth it if you need to bypass stuff like this.

**Comment by xtekky** [comment]
@localuser-isback yh, btw added you back on dc if u added me idk ur username

**Comment by sudouser777** [comment]
@xtekky  any update on the issue
I have been checking the code, can you please tell me what is the token about
`quora.Account.create(logging = True, enable_bot_creation=True)` Here we are calling this method for signup/login but that method doesn't have any return statement I'm confused here
also, we can update the code to add some retry logic, In  case of the above error it's still going to check for a verification code in the mail but that shouldn't happen

**Comment by DanielShemesh** [comment]
I used the quora module with my account's token, now that account of mine was closed. I guess they started detecting bots..

**Comment by hemangjoshi37a** [comment]
Hi @xtekky,

It seems like the problem you are encountering is related to Google detecting automated requests from your network or device. Here's a possible solution you could try:

1. First, consider using residential proxies as suggested by @localuser-isback. Residential proxies are less likely to be detected as automated traffic because they come from actual internet service providers like AT&T. While they can be more expensive than datacenter proxies, they might be worth it to bypass such issues.

2. You can also implement a retry logic, as @sudouser777 suggested, to handle the error more efficiently. If the error occurs, your code should not continue checking for a verification code in the email, but instead, retry sending the request after a specific time interval.

Here's a sample code snippet to handle the retry logic:

```python
import time

def send_request_with_retry(max_retries=5, retry_interval=60):
    retries = 0
    while retries < max_retries:
        response = send_request()  # Replace this with your actual request function
        if response.status_code == 200:
            return response
        elif response.status_code == 429:  # Google detected automated request
            time.sleep(retry_interval)
            retries += 1
        else:
            break  # Handle other error codes if necessary
    return None  # Request failed after retries

response = send_request_with_retry()
```

This function will retry sending the request up to `max_retries` times, waiting `retry_interval` seconds between each attempt. Make sure to adjust these values according to your needs.

I hope this helps! Let me know if you encounter any issues or need further assistance.

**Comment by chuanhhoang** [comment]
Anyone get accounts banned?
