### ISSUE TITLE
forefront : An error occurred: Completion.create() missing 1 required positional argument: 'account_data'. Please make sure you are using a valid cloudflare clearance token and user agent.

### ISSUE THREAD

**Issue by joeaki1983** [xtekky/gpt4free#600]
It works normally under you.com , but when I change you to forefront in streamlit_app.py, it cannot be used normally, prompting "An error occurred: Completion.create() missing 1 required positional argument: 'account_data'. Please make sure you are using a valid cloudflare clearance token and user agent.     How to solve it.

**Comment by ggindinson** [comment]
You need to create account using `forefront.Account.create(logging=True)`. This method returns account token, which you should use as an account_data argument.

**Comment by ggindinson** [comment]
@xtekky can you close this issue because it's not related to technical issue?
