### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by vmajor** [xtekky/gpt4free#608]
requirements.txt is missing and cannot be found.

**Comment by ggindinson** [comment]
Check the instructions here: https://github.com/xtekky/gpt4free/pull/604

Author of PR explained how to use poetry instead of requirements.txt

> requirements.txt is missing and cannot be found.

**Comment by vmajor** [comment]
OK I see. I actually needed requirements.txt for AGiXT because it is nested inside its own requirements. Yea, no. I do not know either.

**Comment by patronum-digital** [comment]
Maybe add it?

**Comment by enganese** [comment]
Here it is:
```
websocket-client
requests
tls-client
pypasser
names
colorama
curl_cffi
streamlit==1.21.0
selenium
fake-useragent
twocaptcha
https://github.com/AI-Yash/st-chat/archive/refs/pull/24/head.zip
pydantic
pymailtm
Levenshtein
retrying
mailgw_temporary_email
pycryptodome
random-password-generator
```

If you needed `requirements.txt` for your specific situation, then add it manually for yourself. `requirements.txt` is not needed when the poetry exists already.
