### ISSUE TITLE
ModuleNotFoundError: No module named 'typings'

### ISSUE THREAD

**Issue by MrDie2233** [xtekky/gpt4free#618]
I only move streamlit_app.py from ./gui to the base folder then copy streamlit run streamlit_app.py and run. but i can't run the program. what should i do?
![Screenshot 2023-05-28 at 12-47-44 streamlit_app · Streamlit](https://github.com/xtekky/gpt4free/assets/130889067/70c63e07-a9ea-4e15-b1e7-75b98c6d839f)
![屏幕截图 2023-05-28 125049](https://github.com/xtekky/gpt4free/assets/130889067/9c546120-f297-411c-b80c-30c70e3d3f07)
![屏幕截图 2023-05-28 125303](https://github.com/xtekky/gpt4free/assets/130889067/7e51bf89-1eff-4172-9841-c7391a7f81d8)

**Comment by nkbih** [comment]
I installed and run the docker container by commands from readme, and there is same problem

**Comment by iugo** [comment]
code: https://github.com/xtekky/gpt4free/pull/610/files#diff-be3af1bb5ff64e620f43aa0245b1111573a86af42f0e422b83bf9ba6857d7032R4

**Comment by ParthenGithub** [comment]
I have same problem, both on venv and docker

**Comment by caoyifeng007** [comment]
Same for me

**Comment by othmanordaski** [comment]
also the same thing

**Comment by StasGrishaevTutu** [comment]
same issue here

**Comment by w2807** [comment]
same issue for me both on vent and docker. thanks for solving.

**Comment by maxens-git** [comment]
Same as me

**Comment by wakaru44** [comment]
For the moment, I 
```
git checkout gpt4free/aicolors/__init__.py
git switch -c rollback
docker compose down; docker compose up --build -d
```
to roll back.

**Comment by pennpeng** [comment]
+1

**Comment by Miezhiko** [comment]
https://github.com/xtekky/gpt4free/pull/620

**Comment by dudebackend** [comment]
so i solved the issue
i was running the bot not as user i was root

**Comment by dudebackend** [comment]
so i solved the issue
i was running the bot not as user i was root
so run the bot as a user
and change here gpt4free/aicolors/__init__.py

**Comment by dudebackend** [comment]
so i solved the issue
i was running the bot not as user i was root
so run the bot as a user
and change here gpt4free/aicolors/init.py
this from typings import AiColorsResponse
into this from .typings import AiColorsResponse
After that the bot will runs

**Comment by eastyy** [comment]
> so i solved the issue
> i was running the bot not as user i was root
> so run the bot as a user
> and change here gpt4free/aicolors/init.py
> this from typings import AiColorsResponse
> into this from .typings import AiColorsResponse
> After that the bot will runs

it works!

**Comment by WQR1234** [comment]
Find that line of code and add a dot before "typings".

**Comment by sparksustc** [comment]
Find that line of code and add a dot before "typings", like  " from .typings import AiColorsResponse".
Or you can simple copy all the code in typings/__init__.py into /aicolors/__init__.py like this:

# from typings import AiColorsResponse
from dataclasses import dataclass

@dataclass
class AiColorsResponse:
    background: str
    primary: str
    accent: str
    text: str

**Comment by linjunshi** [comment]
> so i solved the issue i was running the bot not as user i was root so run the bot as a user and change here gpt4free/aicolors/init.py this from typings import AiColorsResponse into this from .typings import AiColorsResponse After that the bot will runs

It works!👍 Should make that a PR to fix this issue.
