### ISSUE TITLE
useless: drop user input or make it optional

### ISSUE THREAD

**Issue by Miezhiko** [xtekky/gpt4free#625]
https://github.com/xtekky/gpt4free/blob/main/gpt4free/usesless/__init__.py#L16-L18

```python
class Account:
    @staticmethod
    def create(logging: bool = False):
        is_custom_domain = input(
            "Do you want to use your custom domain name for temporary email? [Y/n]: "
        ).upper()
```

it's bad for API, I'd suggest to keep prompts (and output tuning) fully on client side.

**Comment by enganese** [comment]
@ggindinson and me are working on API and will fix it in API update. So, don't worry. @xtekky already knows and relies on us and you should too. 

Thanks for issue! You can close it, we will fix it in API update.
