### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hamzanabulse** [xtekky/gpt4free#627]
Answer :

Unable to fetch the response, Please try again.

**Comment by CiaranYoung** [comment]
I encountered the same problem, and I tried to switch the proxy, the problem still hasn't been solved, I don't know what to do.

**Comment by sparksustc** [comment]
same thing. and my proxy can access poe.com

**Comment by CiaranYoung** [comment]
> I encountered the same problem, and I tried to switch the proxy, the problem still hasn't been solved, I don't know what to do.

yeah, I've fixed this, at least on the default web user interface (webui), you.com, because I added a line of my own proxy to the code as instructed

**Comment by CiaranYoung** [comment]
> > I encountered the same problem, and I tried to switch the proxy, the problem still hasn't been solved, I don't know what to do.
> 
> yeah, I've fixed this, at least on the default web user interface (webui), you.com, because I added a line of my own proxy to the code as instructed

just edit  gpt4free/you/__init__.py

![image](https://github.com/xtekky/gpt4free/assets/87439103/852cf3c0-89d6-48c3-a217-691599641ecd)

Add a line of your own proxy address

**Comment by JasonLeeForOnly** [comment]
> you

Problem solved! THX
