### ISSUE TITLE
Incorrect display of Russian characters.

### ISSUE THREAD

**Issue by Samsunggora** [xtekky/gpt4free#631]
Hi.
After I fixed the error :
https://github.com/xtekky/gpt4free/issues/618
The way to solve:
https://github.com/xtekky/gpt4free/issues/618#issuecomment-1567317452

I got a similar display of Russian letters:
![image](https://github.com/xtekky/gpt4free/assets/55054125/1a71d64c-2b47-43e4-93be-a290850dab2c)

At the same time it works correctly with English queries:
![image](https://github.com/xtekky/gpt4free/assets/55054125/f290cd6e-c548-405f-916f-238d0a2eb25a)

**Comment by Samsunggora** [comment]
> Could you please tell me if the problem is solved ?
No, I'll keep you posted, in this thread

**Comment by CiaranYoung** [comment]
Yes, other than English, other languages show similarly strange encoded output

**Comment by Lawlietr** [comment]
Same issue here, and i using Traditional Chinese.
I rollback to commit 471 now and work will.

**Comment by skhvisual** [comment]
> Same issue here, and i using Traditional Chinese. I rollback to commit 471 now and work will.

what is commit? Can you tell me how to solve this problem?

**Comment by Lawlietr** [comment]
> > Same issue here, and i using Traditional Chinese. I rollback to commit 471 now and work will.
> 
> what is commit? Can you tell me how to solve this problem?

Use the git checkout

`git checkout 7fbe472b74193b6dc9e0d1004ddc8f26c466ea9e`

That will go back to commit 471, that day about 3 weeks before.

**Comment by Samsunggora** [comment]
> > > Same issue here, and i using Traditional Chinese. I rollback to commit 471 now and work will.
> > 
> > 
> > what is commit? Can you tell me how to solve this problem?
> 
> Use the git checkout
> 
> `git checkout 7fbe472b74193b6dc9e0d1004ddc8f26c466ea9e`
> 
> That will go back to commit 471, that day about 3 weeks before.

It worked for me.

**Comment by skhvisual** [comment]
> It worked for me.

how did you do it ? is it necessary to make changes to a file ? more information please

**Comment by 00randomize00** [comment]
#241 works for me. Just change this line
` escaped = answer.encode('utf-8').decode('unicode-escape')`

**Comment by skhvisual** [comment]
for russian - 

file:
gpt4free-main\gpt4free\aicolors\__init__.py 

in 15 line:
"accept-language": "ru-RU,ru;q=0.5",

**Comment by JasonLeeForOnly** [comment]
> 

I tryed to change the lang attr  
'accept-language': 'zh-cn,zh;q=0.5',
for chinese char support,but still not working

**Comment by skhvisual** [comment]
zh-Hant

> 'accept-language': 'zh-cn,zh;q=0.5',

maybe - zh-Hant or zh-Hans ?

**Comment by cssword** [comment]
escaped = answer.encode('utf-8').decode('unicode-escape')

**Comment by Anan-don** [comment]
Use  default module you:
Apr 28,2023  #241 resolves the Chinese garbled character. It adds the following code : ` escaped = answer.encode('utf-8').decode('unicode-escape')`.
But  May 28,2023 #532  modifies the code : `escaped = answer.encode('utf-8').decode('utf-8')`. It is wrong.
So, we can modify the file gui/streamlit_app.py  41 line : `escaped = answer.encode('utf-8').decode('unicode-escape')`

**Comment by zhlc0756** [comment]
> 使用默认模块 you: Apr 28,2023 #241解决中文乱码。它添加了以下代码：` escaped = answer.encode('utf-8').decode('unicode-escape')`。 但是 May 28,2023 #532 修改了代码：`escaped = answer.encode('utf-8').decode('utf-8')`. 这是错误的。 所以，我们可以修改文件 gui/streamlit_app.py 的第 41 行：`escaped = answer.encode('utf-8').decode('unicode-escape')` @skhvisual @CiaranYoung @Samsunggora @JasonLeeForOnly

这对我有用。

**Comment by sonorame** [comment]
```
response = you.Completion.create(
    prompt = "Расскажи историю про кодировку-декодировку символов",
    detailed=True,
    include_links=True)
print("Bot:", response.text.encode('utf-8').decode('unicode_escape'))
```

**Comment by zhlc0756** [comment]
您好，您的邮件我已经收到。谢谢！。
