### ISSUE TITLE
gui runs ok，but can not get response

### ISSUE THREAD

**Issue by Nodewebzsz** [xtekky/gpt4free#632]
Answer :

Unable to fetch the response, Please try again.

**Comment by Ashionnal** [comment]
Yes, this problem happened to me too

**Comment by SMARK2022** [comment]
Me, too
![00157BC1](https://github.com/xtekky/gpt4free/assets/51025843/7d066add-637f-4888-a22a-c8bc62dffb3c)

**Comment by feixue1232** [comment]
me, too  ++1

**Comment by wu12364564611** [comment]
我也是

**Comment by yudapao** [comment]
俺也一样

**Comment by huchenghepang** [comment]
我是能回答,但是直接显示是youbot

**Comment by SMARK2022** [comment]
我现在可以了，应该是代理配置问题，在create函数调用加了代理就好了
