### ISSUE TITLE
I get an incomplete answer - hangs (stops)

### ISSUE THREAD

**Issue by skhvisual** [xtekky/gpt4free#635]
I get an incomplete answer - chat can't finish writing. 
When writing an answer, chat hangs (stops) at a certain word (sentence) and won't write further before it finishes writing. Short answers work, but if you need more than 1500 letters - it reaches the limit. Can you tell me how to remove this limit?

**Comment by LopeKinz** [comment]
ChatGPT 3.5 does indeed have a 1500 Word limit. Since the new OpenAI Update the chat can be "Resumed". That can take a while to implement.

**Comment by saulojoab** [comment]
was anyone able to implement resuming the answer?
