### ISSUE TITLE
Unable to fetch the response

### ISSUE THREAD

**Issue by JasonLeeForOnly** [xtekky/gpt4free#637]
**Bug description**
I use streamlit to build a website,but it unable to get any anwser,maybe proxy error but I don't know how to disposition.

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/47520063/22750996-3af2-4c0a-8538-d9d89e529540)

**Environement**
- python3.9
- China

**Comment by Blackcf** [comment]
me too

**Comment by tignioj** [comment]
+1

**Comment by pedrooct** [comment]
+1
