### ISSUE TITLE
Docker build error on

### ISSUE THREAD

**Issue by dedafrost** [xtekky/gpt4free#647]
Trying to build Docker image : 

docker build -t gpt4free:latest .

#0 21.50         File "/tmp/pip-build-env-hu_w39sz/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
#0 21.50           register_finder(pkgutil.ImpImporter, find_on_path)
#0 21.50                           ^^^^^^^^^^^^^^^^^^^
#0 21.50       AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
#0 21.50       [end of output]
#0 21.50   
#0 21.50   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 21.50 error: subprocess-exited-with-error
#0 21.50 
#0 21.50 × Getting requirements to build wheel did not run successfully.
#0 21.50 │ exit code: 1
#0 21.50 ╰─> See above for output.
ERROR: failed to solve: process "/bin/sh -c pip install --upgrade pip  && pip install -r /tmp/requirements.txt  && rm /tmp/requirements.txt" did not complete successfully: exit code: 1

**Comment by din-grogu** [comment]
#643 try this
