### ISSUE TITLE
卡在please wait

### ISSUE THREAD

**Issue by Diegozmy** [xtekky/gpt4free#652]
为什么操作后我的网站卡在了please wait？
![image](https://github.com/xtekky/gpt4free/assets/101702927/987d152a-41f6-43ef-bd33-1b987ed112fe)
像这样

**Comment by taiyi747** [comment]
已经更新pywebio-deepai版本，等待通过、
或者你可以去我的仓库查看https://github.com/taiyi747/openai-gpt4/tree/main/gui/pywebio-gui

**Comment by Diegozmy** [comment]
> Streamlit版本长时间有问题了...，等修复吧 或者移步pywebio-deepai版本，等待通过、 或者你可以去我的仓库查看https://github.com/taiyi747/openai-gpt4/tree/main/gui/pywebio-gui

请问啥叫
![图片](https://github.com/xtekky/gpt4free/assets/101702927/2edd6d72-9141-4226-8a1e-1d7b344fa06e)
![图片](https://github.com/xtekky/gpt4free/assets/101702927/d0567dc3-760b-4b00-b290-999f4bf78d88)

**Comment by xtekky** [comment]
try new version
