### ISSUE TITLE
fake_useragent Maximum amount of retries reached 

### ISSUE THREAD

**Issue by x0xntor33alx0x** [xtekky/gpt4free#663]
**Bug description**
I tried this simple code:
```python
import gpt4free
from gpt4free import Provider,  theb

token = forefront.Account.create(logging=False)
response = gpt4free.Completion.create(
  Provider.Theb, prompt='Write a poem on Lionel Messi', model='gpt-3.5', token=token
)

```
when I run this code I get this traceback:
**Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11**
    html = html.split('<table class="w3-table-all notranslate">')[1]
**IndexError: list index out of range**

  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
**urllib.error.HTTPError: HTTP Error 503: Service Unavailable**

  File "~/.local/lib/python3.8/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
**fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached**

**Environement**
- python3.8
- location: egypt
- system: ubuntu==20.04
- fake-useragent==0.1.11

**Comment by xtekky** [comment]
try new version
