### ISSUE TITLE
gpt-3.5-turbo-0613

### ISSUE THREAD

**Issue by notabene00** [xtekky/gpt4free#666]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
API that have ability to use at least `gpt-3.5-turbo-0613` with `functions`.

**Describe alternatives you've considered**
`gpt-4-0613` at most :)

**Additional context**
https://openai.com/blog/function-calling-and-other-api-updates

**Comment by nacho00112** [comment]
This is a demonic issue

**Comment by notabene00** [comment]
This is so called `feature request` - if there is a sloppy `gpt-4` sticking out somewhere, then the cheaper but more functional (than previous) version of `gpt-3.5` sounds fine. I don't think I'm the last one to have that thought.
So if the opportunity ever arises, all this issue's subscribers can be notified at once.

**Comment by xtekky** [comment]
yeah well, finding a website providing 0613 and on top of that - being able to pass the function parameter, is a bit ridulous, but I may add support on the future
