### ISSUE TITLE
Forefront_test | StreamingCompletion.create() got an unexpected keyword argument 'token' error

### ISSUE THREAD

**Issue by Pasture1** [xtekky/gpt4free#669]
**Bug description**
The error appears when replacing 
`token = forefront.Account.create(logging=True)`
With the token obtained from cookies

ex.
1. Copied forefront_test.py to the main folder
2. replaced `token = forefront.Account.create(logging=True)` with the token from cookies
3. run and get error `StreamingCompletion.create() got an unexpected keyword argument 'token' `

**Environement**
- Python version is 3.10.6
- Canada

**Comment by hamza1312** [comment]
It's not a bug bruh
