### ISSUE TITLE
Bing provider error

### ISSUE THREAD

**Issue by Em1tSan** [xtekky/gpt4free#676]
When trying to use BIng, the following error appears:

```
sing g4f.Provider.Providers.Bing provider
There is no current event loop in thread 'Thread-4 (process_request_thread)'.
<traceback object at 0x000001C5CF158D00>
127.0.0.1 - - [25/Jun/2023 04:46:01] "POST /backend-api/v2/conversation HTTP/1.1" 400 -
```
![image](https://github.com/xtekky/gpt4free/assets/70670181/fa645158-35f8-49cd-b145-af26c5f1833a)

The error occurs at the moment of sending the message. Each time the thread number is different. 

Environment: Windows 11 Pro, Python 3.10.10

**Comment by xtekky** [comment]
will be updated when I can please use other providers in the meantime
