### ISSUE TITLE
where to add the proxy address in the newly released gpt4free V2

### ISSUE THREAD

**Issue by MrGongqi** [xtekky/gpt4free#678]
I tried to install it, but encountered an issue where it reported a connection error to GitHub. I believe this is due to not setting the proxy address. Could you please let me know where to add the proxy address in the newly released gpt4free V2 ? I am using Clash

**Comment by xtekky** [comment]
still having this error ?

**Comment by MrGongqi** [comment]
Yes, the problem is still not resolved, and it is preventing me from proceeding with the installation. Can you please help me? Thank you.
