### ISSUE TITLE
Ails raise error

### ISSUE THREAD

**Issue by phamxtien** [xtekky/gpt4free#683]
**Bug description**
Today, Ails respone: 
{"error":{"message":"Hey! The webpage has been updated. Please refresh the page and try again.","type":"AI.LS: Please refresh","code":"AI.LS: NEED REFRESH"}}

**Environement**
- python version: 3.10
- location: vietnam

**Comment by airyland** [comment]
Hey! I'm the developer of AI.LS. Please refrain from crawling our website.
Each IP is allowed to ask 15 questions per day on our website, but please note that using code to scrape data is strictly prohibited and may result in a ban.
