### ISSUE TITLE
installing with pip

### ISSUE THREAD

**Issue by Eikosa** [xtekky/gpt4free#690]
It would be nice if we could install it with pip, for example:
`pip3 install gpt4free`

**Comment by Eikosa** [comment]
I think there was, but I wasn't sure because it wasn't written in the documents.

**Comment by xtekky** [comment]
the pip package hasn't been updated, I will have to take care of it

**Comment by MIDORIBIN** [comment]
I have made it possible to install from Git using the following command. However, please understand that the versioning is not appropriate and use it accordingly. (The version will always be 0.2.0, even if the code is updated.)

```shell
pip install git+https://github.com/xtekky/gpt4free.git
```
