### ISSUE TITLE
Is Poe.com still working?

### ISSUE THREAD

**Issue by chuanhhoang** [xtekky/gpt4free#695]
I don't see Poe.com in the list anymore. Is it still working?

**Comment by xtekky** [comment]
i will add it when I get it back to work, but not at the moment no

**Comment by becaHEse** [comment]
> i will add it when I get it back to work, but not at the moment no

Thanks, I'm also trying reverse poe, it's a bit troublesome, targeting https://poe.com/api/gql_POST The 'poe-formkey' in the interface and headers will change after a certain period of time, and I am still dealing with its confusion. I have roughly completed the 'poe-tag-id' parameter, and using the correct 'poe-formkey' can achieve simulation requests. As for receiving AI response data, websites are implemented through websockets, which are relatively easy to handle and do not have too many reverse reactions.
