### ISSUE TITLE
why i can't change the model to Liaobots

### ISSUE THREAD

**Issue by haoishappy** [xtekky/gpt4free#697]
![屏幕截图 2023-06-28 212848](https://github.com/xtekky/gpt4free/assets/104285718/83767d2d-e5da-4356-ad52-bd8e144bde81)
I already change the "print(g4f.Provider.Ails.params)" to "print(g4f.Provider.Liaobots.params)". Why is it prompting a "newbing" error? Anybody can help me?

**Comment by mat1rus** [comment]
ik im late, but
To change the actual provider, you need to define `provider` argument in `g4f.ChatCompletion.create`:

```py
g4f.ChatCompletion.create(
  model=g4f.Model.gpt_4
  messages=[{"role":"user","content":"hi"}],
  provider=g4f.Provider.Liaobots, # here
)
```

**Comment by Turbo1337GS** [comment]
> ik im late, but To change the actual provider, you need to define `provider` argument in `g4f.ChatCompletion.create`:
> 
> ```python
> g4f.ChatCompletion.create(
>   model=g4f.Model.gpt_4,
>   messages=[{"role":"user","content":"hi"}],
>   provider=g4f.Provider.Liaobots, # here
> )
> ```

"Liabots have security measures! Maybe that's why! Try to verify yourself using cookies or a token! I don't use Liabots, so I can't tell you exactly! Maybe Liabots also introduced new security measures on the server
