### ISSUE TITLE
Missing Credits

### ISSUE THREAD

**Issue by ading2210** [xtekky/gpt4free#698]
Hi xtekky,

Regarding the new gpt4free v2 release, it seems like you've stripped out virtually all the credit for the work I've contributed.

This is especially an issue for the Vercel wrapper, which is basically a copy-paste from the [original](https://github.com/ading2210/vercel-llm-api/), with the only mention of my involvement being a single comment halfway through the file.
https://github.com/xtekky/gpt4free/blob/25d5525bf1899eac9795e7651e496ee2f665a4fe/g4f/Provider/Providers/Vercel.py#L44
 
It seems a bit disingenuous that you're relying on code that I've written for 80% of the models that gpt4free uses, while not giving any indication of it apart from a comment in the source code which few people will read.

Furthermore, you're also violating the GNU GPL v3 by not making this fact prominent, as stated in section 5:
>  a) The work must carry *prominent notices stating that you modified it*, and giving a relevant date.

Please add some sort of credits or disclaimer to the readme of gpt4free, so that my effort, as well as the effort of all previous contributors, does not go unnoticed. 

Thanks, 
ading2210

**Comment by Visionishere** [comment]
not cool xtekky, stealing code and breaking license. big no no.

**Comment by ading2210** [comment]
@xtekky Please correct this or else I will submit a DMCA takedown notice.

**Comment by xtekky** [comment]
yeah stop being pressed guys, I generally do not take time working on the project, there is one file that does not even work right now no need to issue a whole DCMA takedown for that

**Comment by xtekky** [comment]
I'll remove the code fine

**Comment by nacho00112** [comment]
A idea, because alot of the code is by contributors, isn't better to transfer the repo to a shared user? By this way, it'll be a lot easier maintaining the code, isn't so?

**Comment by ading2210** [comment]
@xtekky You have re-added the [offending code](https://github.com/xtekky/gpt4free/blob/ac581361da1804e24d73c725cbf10e26716cb3f2/g4f/Provider/Vercel.py#L67). Please either provide some proper credits or remove it.

**Comment by ProgrammerIn-wonderland** [comment]
Bruh

**Comment by kingofnetflix** [comment]
You know what your doing now, and you still decide to break licenses and not give the man his well deserved credit (and the other contributors). Not cool. I hope you get taken down

**Comment by Scoder12** [comment]
bruh

**Comment by AverageJuliet** [comment]
bruh what is this shit

**Comment by Riftriot** [comment]
again bro
