### ISSUE TITLE
Forefront error

### ISSUE THREAD

**Issue by fera765** [xtekky/gpt4free#700]
Apparently the forefront has stopped working!

**Comment by HanHuiHH** [comment]
I have met the same problem, most of providers return nothing to me.
Forefront is the best provider, other providers are not intelligent like it, especially bing. :)

**Comment by hiwaveSupport** [comment]
![image](https://github.com/xtekky/gpt4free/assets/39630233/fb319df9-4a45-49a7-81a2-74a6a2515d6c)

Getting nothing from default provider either.
On gpt-4 getting captcha error as well.

**Comment by valokobito** [comment]
Any updates?
