### ISSUE TITLE
CaptchaChallenge: User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by killporter** [xtekky/gpt4free#703]
**Known Issues** // delete this
- you.com issue / fix: use proxy, or vpn, your country is probably flagged
- forefront account creation error / use your own session or wait for fix

**Bug description**
What did you do, what happened, which file did you try to run, in which directory
Describe what you did after downloading repo, such as moving to this repo, running this file.

anything normal in the istructions, i'm using it in a flask server

ex.

**Screenshots**

**Environement**
- python version
- location ( are you in a cloudfare flagged country ) ?

**Additional context**

**Comment by GhostService** [comment]
I have the same problem lol

**Comment by tringuyencse** [comment]
I have the same problem
