### ISSUE TITLE
[Provider Error]: g4f.Provider.Lockchat

### ISSUE THREAD

**Issue by yORmOmi** [xtekky/gpt4free#710]
**Bug description**
I don't think `g4f.Provider.Lockchat` if you go to their website, It will direct you to Youtube.

ex.
1. Go to `http://super.lockchat.app/'
2. See problem

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/133837794/84e8919a-7946-48cb-b00b-c598e0b50111)

**Environement**
- python version `Python 3.10.11`
- location Canada

**Additional context**
When I use the provider, there is no response.

**Comment by xtekky** [comment]
someone proposed a fix, should work again

**Comment by sshnaidm** [comment]
Still doesn't work for me:
```json
{
    "error": {
        "message": "you must provide a model parameter",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
```
Although `model` is passed in JSON:
```
{'temperature': 0.7, 'messages': [{'role': 'user', 'content': 'hi, give me an advice how to start running if I am a beginner'}], 'model': 'gpt-4', 'stream': True}
```

**Comment by itzrnvr** [comment]
facing the same I am not getting any response

**Comment by gh-doot** [comment]
now it takes you to some app store app
https://apps.apple.com/app/id6446304087/

**Comment by hamza1312** [comment]
Same ^, Maybe the link should be changed.

**Comment by manesec** [comment]
Seem to be NOT work again? 

The `test.py`
``` python
import g4f 
from g4f.Provider import (
    Ails,
    You,
    Bing,
    Yqcloud,
    Theb,
    Aichat,
    Bard,
    Vercel,
    Forefront,
    Lockchat,
    Liaobots,
    H2o,
    ChatgptLogin,
    DeepAi,
    GetGpt
)

response = g4f.ChatCompletion.create(model=g4f.Model.gpt_4,provider=Lockchat, messages=[
                                         {"role": "user", "content": "hi"}]) # alterative model setting

print(response)

```

I add two line two line [in here](https://github.com/xtekky/gpt4free/blob/main/g4f/Provider/Providers/Lockchat.py#L24) to debug 

![image](https://github.com/xtekky/gpt4free/assets/42072997/00750b1a-cc3f-4b0a-81e3-70483bb91a4a)

but the data return:  `b'    <meta http-equiv="X-UA-Compatible" content="IE=edge">'`
So it go wrong.

![image](https://github.com/xtekky/gpt4free/assets/42072997/cbbbea8f-4213-4d51-95b9-5ba7186c79cb)
