### ISSUE TITLE
Replace tls-client with something else

### ISSUE THREAD

**Issue by nimagp** [xtekky/gpt4free#711]
**Bug description**
What did you do, what happened, which file did you try to run, in which directory
Describe what you did after downloading repo, such as moving to this repo, running this file.

ex.
1. Attempt to install gpt4free package

**Screenshots**

**Environement**
- python version
- location ( are you in a cloudfare flagged country ) ?

**Additional context**
tls-client is a library that has a size of 34Mb, even ignoring the fact that this is inconvenient, there are binary blobs for ALL platforms in the github repo instead of tls-client go version source code or packaging different binary files for each arch in python build process
The binary files can be anything. this isn't a good idea

**Comment by xtekky** [comment]
I can switch it to using curl_cffi which has more installation problems, but the size shouldn't be a problem, unless a lot of people are encountering problems.

Unfortunately tls_client is necessary because of the numerous cloudflare blocks

**Comment by nimagp** [comment]
> I can switch it to using curl_cffi which has more installation problems, but the size shouldn't be a problem, unless a lot of people are encountering problems.
> 
> Unfortunately tls_client is necessary because of the numerous cloudflare blocks

Can you fork the library and make a build process using github actions that builds tls-client (go) on the fly and includes it in the whl file (specific to each architecture and platform)?

**Comment by nacho00112** [comment]
> I can switch it to using curl_cffi which has more installation problems, but the size shouldn't be a problem, unless a lot of people are encountering problems.
> 
> Unfortunately tls_client is necessary because of the numerous cloudflare blocks

So i can change the files that uses curl_cffi to use tls-client instead if i want to and it will still work?
