### ISSUE TITLE
ChatGPTLogin returns <Response [500]>

### ISSUE THREAD

**Issue by phamxtien** [xtekky/gpt4free#713]
**Bug description**
 Using g4f.Provider.Providers.ChatgptLogin provider
<Response [500]>

**Comment by bagusindrayana** [comment]
I don't know if it's too late, but url for https://chatgptlogin.ac is change to https://chatgptai.help and html web structure changed to, so some code to scrape not work, like function to get nonce token/id
```python
def get_nonce():
        res = requests.get('https://chatgptai.help/chatgpt-free-use-chat-online/', headers={
            "Referer": "https://chatgptai.help/chatgpt-free-use-chat-online",
            "User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
        })
        # print(res.text)

        # not work to search nonce based on src
        # src = re.search(r'class="mwai-chat mwai-chatgpt">.*<span>Send</span></button></div></div></div> <script defer src="(.*?)">', res.text).group(1)
        # decoded_string = base64.b64decode(src.split(",")[-1]).decode('utf-8')

        # immediately looking restNonce variable
        return re.search(r"let restNonce = '(.*?)';", res.text).group(1)
```
even without this funciton to fill `x-wp-nonce` header, you can still make request to api `https://chatgptai.help/wp-json/ai-chatbot/v1/chat`

**Comment by phamxtien** [comment]
https://chatgptai.help/chatgpt-free-use-chat-online/
Say 'Hi' and it returns: You exceeded your current quota, please check your plan and billing details. (OpenAI)
