### ISSUE TITLE
how to find all mode and all Provider?

### ISSUE THREAD

**Issue by win4r** [xtekky/gpt4free#717]
in this code:
model='gpt-3.5-turbo', provider=g4f.Provider.GetGpt

how do I find the all model and all Provider?

**Comment by bagusindrayana** [comment]
maybe to late, i dont really undertand what you want, but if you want see all available providers and models you can just open `/g4f/Provider/Providers/`, you can see list all provider and if you open one you can see model supported by that provider in variable `model = ['gpt-3.5-turbo']`

if you want list all available  and models in g4f you can use `dir` function, https://github.com/xtekky/gpt4free/issues/760
this will return list of attributes in class/object, example :
```python
dir(Provider) # will return something like ['AItianhu', 'Acytoo', 'AiService',... etc]
```

**Comment by yjg30737** [comment]
This is how to do it:

```python
from g4f.Provider import ProviderUtils
from g4f.models import ModelUtils

models = list(ModelUtils.convert.keys())
providers = list(ProviderUtils.convert.keys())

print(models)
print(providers)
```

**Comment by BinhPQ2** [comment]
> This is how to do it:
> 
> ```python
> from g4f.Provider import ProviderUtils
> from g4f.models import ModelUtils
> 
> models = list(ModelUtils.convert.keys())
> providers = list(ProviderUtils.convert.keys())
> 
> print(models)
> print(providers)
> ```

Thank you, it works
