### ISSUE TITLE
fix bing

### ISSUE THREAD

**Issue by agenda-shaper** [xtekky/gpt4free#719]
no one cares about free gpt 3 apis. just fix bing at least

captcha needed

**Comment by yamete0** [comment]
CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by bagusindrayana** [comment]
maybe try this version
Provider : https://gitler.moe/g4f/gpt4free/src/branch/main/g4f/Provider/Providers/Bing.py
Helper : https://gitler.moe/g4f/gpt4free/src/branch/main/g4f/Provider/Providers/helpers/bing.py

**Comment by hlohaus** [comment]
My new Bing Provider is online.
You can now solve the Captcha in Browser and then use the provider with the cookies/session from browser.
The cookies will loaded from the browser config thanks the tool "browser_cookie3".
