### ISSUE TITLE
How to continue the chat?

### ISSUE THREAD

**Issue by 64chevy** [xtekky/gpt4free#721]
How do i reply to an answer? Continue chatting with GPT.

Scenario:
I am asking gpt 3.5 to fetch some info --- I have to ask "Fetch another one" and then again "Fetch another one"

**Comment by bagusindrayana** [comment]
maybe this late, just pass previous message you send and ai response to next request. just remember to give role to each messages, ai = assistant/system and you = user
```python
[
    {'role': 'user', 'content': 'first chat you sending...'},
    {'role': 'assistant', 'content': 'Firs ai response'},
    {'role': 'user', 'content': 'second message to response to ai'},
]
```
also accurate to remember context and memory depends on provider you choose

**Comment by Heliner** [comment]
> maybe this late, just pass previous message you send and ai response to next request. just remember to give role to each messages, ai = assistant/system and you = user
> 
> ```python
> [
>     {'role': 'user', 'content': 'first chat you sending...'},
>     {'role': 'assistant', 'content': 'Firs ai response'},
>     {'role': 'user', 'content': 'second message to response to ai'},
> ]
> ```
> 
> also accurate to remember context and memory depends on provider you choose

It does not take effect on the `gpt-3.5-turbo` model

**Comment by bagusindrayana** [comment]
> > maybe this late, just pass previous message you send and ai response to next request. just remember to give role to each messages, ai = assistant/system and you = user
> > ```python
> > [
> >     {'role': 'user', 'content': 'first chat you sending...'},
> >     {'role': 'assistant', 'content': 'Firs ai response'},
> >     {'role': 'user', 'content': 'second message to response to ai'},
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > also accurate to remember context and memory depends on provider you choose
> 
> It does not take effect on the `gpt-3.5-turbo` model

what provider?

**Comment by AmayaKuro** [comment]
Basically, this project (at least Bard) does not support it, if you want to, you must provide conversation_id, response_id and choice_id of the chat that you wish to continue. 
There also a Bard git repository call [Bard-API](https://github.com/dsdanielpark/Bard-API) that let you continue as you like.

**Comment by Heliner** [comment]
> Basically, this project (at least Bard) does not support it, if you want to, you must provide conversation_id, response_id and choice_id of the chat that you wish to continue. There also a Bard git repository call [Bard-API](https://github.com/dsdanielpark/Bard-API) that let you continue as you like.

Thank you for your answer, it seems that not all providers support language context
I will close this issue

**Comment by Heliner** [comment]
> maybe this late, just pass previous message you send and ai response to next request. just remember to give role to each messages, ai = assistant/system and you = user
> 
> ```python
> [
>     {'role': 'user', 'content': 'first chat you sending...'},
>     {'role': 'assistant', 'content': 'Firs ai response'},
>     {'role': 'user', 'content': 'second message to response to ai'},
> ]
> ```
> 
> also accurate to remember context and memory depends on provider you choose

I write this code, By examining the source code, its provider is identified as GetGpt.

```
model = 'gpt-3.5-turbo'
response = g4f.ChatCompletion.create(
    model=model,
    messages=[{"role": "user", "content": "Now you are Cortana"}],
    stream=False,
)

for message in response:
    print(message, flush=True, end='')

response = g4f.ChatCompletion.create(
    model=model,
    messages=[
        {'role': 'user', 'content': 'Suppose you are Cortana now'},
        {"role": "user", "content": "who are you"},
    ],
    stream=False,
)

print("\n-----------\n")

for message in response:
    print(message, flush=True, end='')
```

**Comment by C0untFloyd** [comment]
Is there a flag or similar to detect if a provider is supporting conversation history?

**Comment by C0untFloyd** [comment]
> maybe this late, just pass previous message you send and ai response to next request. just remember to give role to each messages, ai = assistant/system and you = user
> 
> ```python
> [
>     {'role': 'user', 'content': 'first chat you sending...'},
>     {'role': 'assistant', 'content': 'Firs ai response'},
>     {'role': 'user', 'content': 'second message to response to ai'},
> ]
> ```
> 
> also accurate to remember context and memory depends on provider you choose

This worked for me with every provider I tried, even Bard, thanks OP!

**Comment by tianlichunhong** [comment]
> > maybe this late, just pass previous message you send and ai response to next request. just remember to give role to each messages, ai = assistant/system and you = user
> > ```python
> > [
> >     {'role': 'user', 'content': 'first chat you sending...'},
> >     {'role': 'assistant', 'content': 'Firs ai response'},
> >     {'role': 'user', 'content': 'second message to response to ai'},
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > also accurate to remember context and memory depends on provider you choose
> 
> This worked for me with every provider I tried, even Bard, thanks OP!

Remembered just the last question, but couldn't remember any of the previous ones.

**Comment by tianlichunhong** [comment]
These codes can implement the function of continuing to ask.
`import g4f

first=0
RepleyText=""
MessageStorage=[]
questionNum=15
while True:
    question=input("You:")
    if first==0:
        MessageStorage=[{'role': 'user', 'content': question}]
    else:
        MessageStorage.append({'role': 'user', 'content': question})
    response = g4f.ChatCompletion.create(
		model="gpt-3.5-turbo",
		messages=MessageStorage,
		stream=True,
	)
    first+=1
    RepleyText=""
    for message in response:
        print(message, flush=True, end='')
        RepleyText+=message
    print()
    if first < questionNum:
        MessageStorage.append({'role': 'assistant', 'content': RepleyText}) 
    else:
        del MessageStorage[0]
        del MessageStorage[0]
        MessageStorage.append({'role': 'assistant', 'content': RepleyText}) `

**Comment by st4rted** [comment]
> How do i reply to an answer? Continue chatting with GPT.
> 
> Scenario: I am asking gpt 3.5 to fetch some info --- I have to ask "Fetch another one" and then again "Fetch another one"

```py
import g4f

class Colors:
    """
    A class defining ANSI escape codes for text formatting.
    """
    RESET = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"

    BLACK = "\033[30m"
    RED = "\033[31m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    BLUE = "\033[34m"
    MAGENTA = "\033[35m"
    CYAN = "\033[36m"
    WHITE = "\033[37m"

    BG_BLACK = "\033[40m"
    BG_RED = "\033[41m"
    BG_GREEN = "\033[42m"
    BG_YELLOW = "\033[43m"
    BG_BLUE = "\033[44m"
    BG_MAGENTA = "\033[45m"
    BG_CYAN = "\033[46m"
    BG_WHITE = "\033[47m"

    @staticmethod
    def color_text(text, color_code):
        """
        Apply color formatting to the provided text.

        Args:
            text (str): The text to be formatted.
            color_code (str): The ANSI escape code for the desired color.

        Returns:
            str: The formatted text with the specified color.
        """
        return f"{color_code}{text}{Colors.RESET}"

class ChatBotException(Exception):
    """
    A custom exception class for chatbot-specific errors.
    """
    pass

class Conversation:
    """
    A class to manage the conversation history.
    """
    def __init__(self, max_memory=50):
        """
        Initialize a Conversation object.

        Args:
            max_memory (int): The maximum number of messages to store in the conversation history.
        """
        self.messages = []
        self.max_memory = max_memory

    def add_message(self, role: str, content: str):
        """
        Add a message to the conversation history.

        Args:
            role (str): The role of the message sender (e.g., 'user' or 'assistant').
            content (str): The content of the message.
        """
        if len(self.messages) >= self.max_memory:
            self.messages.pop(0)
        self.messages.append({'role': role, 'content': content})

    def get_messages(self):
        """
        Get the conversation history.

        Returns:
            list: A list of message dictionaries representing the conversation history.
        """
        return self.messages

class TerminalChatBot:
    """
    A class to manage the terminal-based chatbot.
    """
    def __init__(self):
        """
        Initialize a TerminalChatBot object.
        """
        self.conversation = Conversation()

    def send_message(self, content: str) -> None:
        """
        Send a message to the chatbot and display the response.

        Args:
            content (str): The user's input message.
        """
        try:
            if not content.strip():
                raise ChatBotException("Input is empty.")

            self.conversation.add_message('user', content)
            messages = [
                {"role": "user", "content": content},
                *self.conversation.get_messages()
            ]

            response = g4f.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=messages
            )

            if not response:
                raise ChatBotException("No response from the chat model.")

            formatted_response = Colors.color_text(f"Bot: {response}", Colors.UNDERLINE)
            print(formatted_response)
            self.conversation.add_message('assistant', response)
            
        except ChatBotException as e:
            print(f"Error: {e}")
        except Exception as e:
            print(f"Unexpected error: {e}")

    def start_chat(self):
        """
        Start the chatbot interaction with the user.
        """
        try:
            while True:
                user_input = input("You: ")

                if user_input.lower() == "exit":
                    break
                
                self.send_message(user_input)

        except KeyboardInterrupt:
            print("\nChat interrupted by the user.")
        except Exception as e:
            print(f"Unexpected error: {e}")

if __name__ == "__main__":
    chatbot = TerminalChatBot()
    chatbot.start_chat()
```

This is some example code I created. It utilizes `GPT-3.5-TURBO` and saves conversation history. It also has a customizable history limit, which is set to a default value of `50`, but you can change it as desired.
