### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by SunSeaLucky** [xtekky/gpt4free#733]
How to fix this:

urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='streaming.tenant-forefront-default.knative.chi.coreweave.com', port=443): Max retries exceeded with url: /free-chat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

**Comment by nonetrix** [comment]
Having this too

**Comment by kanseaveg** [comment]
![image](https://github.com/xtekky/gpt4free/assets/80022154/6d13d9e0-c32e-4c83-8872-43d8c0d07950)

get the same problem for the main revision: 99cd4088e5c9e98e39ce2b5d94bcc6bbc3190e92
![image](https://github.com/xtekky/gpt4free/assets/80022154/288ca967-e11b-40ea-a641-602c5279a3cd)

i have the set the proxy to the host 'streaming.tenant-forefront-default.knative.chi.coreweave.com', not china address, still can't use the chat code below:

```
import os

import g4f
print(g4f.Provider.Ails.params)

# normal response
response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', messages=[
                                     {"role": "user", "content": "我是不是很帅？"}]) # alterative model setting
print(response)
```
