### ISSUE TITLE
cannot used in china?

### ISSUE THREAD

**Issue by qtzjzp** [xtekky/gpt4free#734]
{"_action":"_ask","error":"an error occurred timed out","success":false}
net work problem?

**Comment by bagusindrayana** [comment]
what provider and model do you use?

**Comment by xybytz** [comment]
Try using a web proxy. China blocks lots and lots of websites anyway, so I am not that surprised.

**Comment by use-my-life** [comment]
nowdays, i can't use any providers even if i usd web proxy.

**Comment by xybytz** [comment]
Are you in china as well? China probably blocks those too. VPNS also work. Worst case scenario they block vpn websites, install one via GitHub.

**Comment by use-my-life** [comment]
right, thank you, sir. i can use some providers.

**Comment by ZYpS-leader** [comment]
g4f目前只支持3.10+，在更新后再尝试使用。可以邮箱联系我（ETRO_omega@outlook.com）,我解决了这个问题。
