### ISSUE TITLE
H2O does not work

### ISSUE THREAD

**Issue by phamxtien** [xtekky/gpt4free#735]
It is not raised an error but returns nothing.

**Comment by bagusindrayana** [comment]
![image](https://github.com/xtekky/gpt4free/assets/36830534/384e596b-8bb9-4044-90fb-043672d20b79)
i got this when visit the web https://gpt-gm.h2o.ai maybe error/down, I don't think it can be used anymore or waiting for the web to come back online

**Comment by bagusindrayana** [comment]
original web already online again, like @phamxtien say provider h2o return nothing, after print the response i got page with "Conversation not found", it seems like conversation id created from
```python
response = client.post('https://gpt-gm.h2o.ai/conversation',
                            headers=headers, json=json_data)
conversationId = response.json()['conversationId']
```
not recognized when request post a conversation
```python
completion = client.post(f'https://gpt-gm.h2o.ai/conversation/{conversationId}', stream=True, json = {})
```

**Comment by AlephZero255** [comment]
Problem fixed
https://github.com/AlephZero255/gpt4free

> It is not raised an error but returns nothing.

**Comment by phamxtien** [comment]
It runs smooth. Thanks

**Comment by phamxtien** [comment]
Completed

**Comment by phamxtien** [comment]
Today, it raise the same error :)
