### ISSUE TITLE
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub') ERROR:asyncio:Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x117399b50>

### ISSUE THREAD

**Issue by 1inhai** [xtekky/gpt4free#746]
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x117399b50>

**Comment by TXT2GAM** [comment]
same
