### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by xuanyuan100** [xtekky/gpt4free#747]
**Screenshots**

![图片](https://github.com/xtekky/gpt4free/assets/3376369/f1a351e4-ea40-41c2-83ba-d34af81ae878)

**Environement**
- python version
- location ( are you in a cloudfare flagged country ) ?
python version :Python 3.11.4,win11

**Additional context**

I run the commond "python3 -m interference.app".It prints the log :
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Java\Pro\gpt4free\gpt4free\interference\app.py", line 6, in <module>
    from g4f import Model, ChatCompletion, Provider
  File "D:\Java\Pro\gpt4free\gpt4free\g4f\__init__.py", line 2, in <module>
    from . import Provider
  File "D:\Java\Pro\gpt4free\gpt4free\g4f\Provider\__init__.py", line 2, in <module>
    from .Providers import (
  File "D:\Java\Pro\gpt4free\gpt4free\g4f\Provider\Providers\Ails.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'.

Then i run 'pip install requests'.I get this:
Requirement already satisfied: requests in d:\java\pro\gpt4free\gpt4free\venv\lib\site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\java\pro\gpt4free\gpt4free\venv\lib\site-packages (from requests) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in d:\java\pro\gpt4free\gpt4free\venv\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\java\pro\gpt4free\gpt4free\venv\lib\site-packages (from requests) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\java\pro\gpt4free\gpt4free\venv\lib\site-packages (from requests) (2023.5.7)

It does not resolve it.

**Comment by xuanyuan100** [comment]
![图片](https://github.com/xtekky/gpt4free/assets/3376369/47d9e42d-8de5-4439-b385-9bc78adff005)

**Comment by bagusindrayana** [comment]
do you have multiple versions of python installed? or only one version?
and maybe this sounds silly but maybe you can try it with command `python -m interference.app` without number 3 in `python`
because I have 2 versions of pip namely `pip3` and regular `pip` and when I run `pip` the installed library is in the `python` command version and not `python3`

**Comment by xuanyuan100** [comment]
> 
yes,I hava two difference version python3.But after I uninstall all python3 and reinstall a new version python3,I still have the same problem.
If I use python -m interference.app,I get "404".
![图片](https://github.com/xtekky/gpt4free/assets/3376369/d0c8b716-c69a-4a62-8915-d70930bc0c20)

**Comment by freedombirdone** [comment]
Try:
python3 -m pip install requests

**Comment by xuanyuan100** [comment]
> Try: `python3 -m pip install requests`

Thanks.The no module error is gone.But I still get the error "404" .
![图片](https://github.com/xtekky/gpt4free/assets/3376369/d18c7420-6025-4142-b93a-4c3c6b12c434)

**Comment by bagusindrayana** [comment]
> > Try: `python3 -m pip install requests`
> 
> Thanks.The no module error is gone.But I still get the error "404" . ![图片](https://user-images.githubusercontent.com/3376369/253846939-d18c7420-6025-4142-b93a-4c3c6b12c434.png)

don't worry, the server is running, warning 404 because the server doesn't have a route for the url `/` and UI Web
the server only have API route `/chat/completion`
https://github.com/xtekky/gpt4free/blob/53a5be288a3026bd8bfda8f2fc296ce1d0950a34/interference/app.py#L13C1-L13C1
so you just PSOT request to that API
in readme is already example to use that API with openai package, make another python file and execute that file
```python
import openai

openai.api_key = ''
//change with your 
openai.api_base = 'http://127.0.0.1:1337'

chat_completion = openai.ChatCompletion.create(stream=True,
    model='gpt-3.5-turbo', messages=[{'role': 'user', 'content': 'write a poem about a tree'}])

#print(chat_completion.choices[0].message.content)

for token in chat_completion:
    
    content = token['choices'][0]['delta'].get('content')
    if content != None:
        print(content)
```

or you can use postman to make POST request to API
![image](https://github.com/xtekky/gpt4free/assets/36830534/c2fa3317-02cb-41d4-b7e2-1d8b7e5dc51b)


and if you have error when request to API, you can change provider in `interference/app.py`
```
response = ChatCompletion.create(model=model, 
                                     stream=streaming,
                                     messages=messages,
                                     provider=Provider.AItianhu # add/change to another provider
                                    )
```

**Comment by xuanyuan100** [comment]
> > > Try: `python3 -m pip install requests`
> > 
> > 
> > Thanks.The no module error is gone.But I still get the error "404" . ![图片](https://user-images.githubusercontent.com/3376369/253846939-d18c7420-6025-4142-b93a-4c3c6b12c434.png)
> 
> don't worry, the server is running, warning 404 because the server doesn't have a route for the url `/` and UI Web the server only have API route `/chat/completion` https://github.com/xtekky/gpt4free/blob/53a5be288a3026bd8bfda8f2fc296ce1d0950a34/interference/app.py#L13C1-L13C1 so you just POST request to that API in readme is already example to use that API with openai package, make another python file and execute that file
> 
> ```python
> import openai
> 
> openai.api_key = ''
> # change with your server url
> openai.api_base = 'http://127.0.0.1:1337'
> 
> chat_completion = openai.ChatCompletion.create(stream=True,
>     model='gpt-3.5-turbo', messages=[{'role': 'user', 'content': 'write a poem about a tree'}])
> 
> #print(chat_completion.choices[0].message.content)
> 
> for token in chat_completion:
>     
>     content = token['choices'][0]['delta'].get('content')
>     if content != None:
>         print(content)
> ```
> 
> or you can use postman to make POST request to API ![image](https://user-images.githubusercontent.com/36830534/253895874-c2fa3317-02cb-41d4-b7e2-1d8b7e5dc51b.png)
> 
> and if you have error when request to API, you can change provider in `interference/app.py`
> 
> ```
> response = ChatCompletion.create(model=model, 
>                                      stream=streaming,
>                                      messages=messages,
>                                      provider=Provider.AItianhu # add/change to another provider
>                                     )
> ```

Oh,got it.Thanks.This project has no UI.So I use chatgpt-clone.This one has a better UI;
