### ISSUE TITLE
AttributeError: module 'g4f.Provider.Providers.Theb' has no attribute 'best_provider'

### ISSUE THREAD

**Issue by DanielShemesh** [xtekky/gpt4free#749]
**Bug description**

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    response = g4f.ChatCompletion.create(model=g4f.Provider.Theb, messages=[
  File "g4f/\_\_init__.py", line 23, in create
    engine = model.best_provider if not provider else provider
AttributeError: module 'g4f.Provider.Providers.Theb' has no attribute 'best_provider'

**Comment by xtekky** [comment]
should be fixed, use latest version and try other providers
