### ISSUE TITLE
chatbot.sex maintenance

### ISSUE THREAD

**Issue by Chr1s-T** [xtekky/gpt4free#75]
When I use in "https://chat.chatbot.sex/", it reported error message like this: 
{ "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }

How to solve this problem？

**Comment by ottocsb** [comment]
me too

**Comment by linsmalldragon** [comment]
me too

**Comment by iloeng** [comment]
me too

**Comment by dywin123** [comment]
help

**Comment by huangturen** [comment]
+1

**Comment by xtekky** [comment]
updating the site, check back later ; )

**Comment by MilaFabio** [comment]
{ "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }

how to fix it?

**Comment by xtekky** [comment]
fixed

**Comment by Chr1s-T** [comment]
> fixed
new error message：
{"_action":"_ask","error":"an error occured HTTPSConnectionPool(host='openprompt.co', port=443): Max retries exceeded with url: /api/chat2 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))","success":false}

**Comment by devwithadi** [comment]
@xtekky can you please also update it on branch as i have pulled and haven't got any changes we can iterate over API's to tackle
this error

**Comment by Chr1s-T** [comment]
It looks like the free requests have reached to the limit (10 times).

**Comment by Chr1s-T** [comment]
Can we at least extract the corresponding access API from the chatbot in platform.openai.com playground, as entering playground is at least easier and does not require complex validation

**Comment by xtekky** [comment]
yes you can use proxy, I will open source the current method I am using and add default Chatgpt api aswell as a config file
