### ISSUE TITLE
bing blocks gpt4free

### ISSUE THREAD

**Issue by xybytz** [xtekky/gpt4free#751]
**Bug description**
bing blocked gpt4free with captcha

To reproduce:

1. Install via pip install git+https://github.com/xtekky/gpt4free
2. import via: from gpt4free import g4f
3. Use code from the readme. (Normal Completion)

**Screenshots**
https://imgur.com/a/0lcviv0

**Environement**
-Python Version: 3.10.8
- location: United States

**Additional context**
only on bing says we have to solve a captcha

**Comment by xtekky** [comment]
yeah I will fix bing whenever I can
