### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement execjs (from g4f) (from versions: none) ERROR: No matching distribution found for execjs

### ISSUE THREAD

**Issue by CodeWithEhtisham** [xtekky/gpt4free#754]
**ERROR: Could not find a version that satisfies the requirement execjs (from g4f) (from versions: none)
ERROR: No matching distribution found for execjs**
I am trying to install g4f using pip3 but unfortunately, I face this issue 

ERROR: Could not find a version that satisfies the requirement execjs (from g4f) (from versions: none)
ERROR: No matching distribution found for execjs

I already try `pip3 install execjs ` but not solve the problem
python version: 3.8 
OS: ubuntu 20.04

**Comment by use-my-life** [comment]
you should `pip install pyexecjs` which can resolve this problem.

**Comment by tuandev1l** [comment]
@use-my-life so sad, it does not work for me. I tried in my window laptop and in google colab but it still error :((

**Comment by KMotsepe** [comment]
Also getting the error, pip install pyexecjs didn't fix the problem for me.

**Comment by nacho00112** [comment]
In the `requirements.txt` file change `execjs` to `pyexecjs` that worked for me

**Comment by paradise321** [comment]
Retry with  "pip install -U g4f" solved that problem for me.
