### ISSUE TITLE
Sample code run into: ModuleNotFoundError: No module named 'g4f.Provider.Providers'

### ISSUE THREAD

**Issue by paradise321** [xtekky/gpt4free#758]
**Bug description**
I installed the latest g4f 0.0.1.2 by "pip install -U g4f", and try to run the sample code show in https://github.com/xtekky/gpt4free:

`import g4f`
`print(g4f.Provider.Ails.params) # supported args`
`# Automatic selection of provider`
`# streamed completion`
`response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', messages=[`
`                                     {"role": "user", "content": "Hello world"}], stream=True)`

`for message in response:`
`    print(message)`

`# normal response`
`response = g4f.ChatCompletion.create(model=g4f.Model.gpt_4, messages=[`
`                                     {"role": "user", "content": "hi"}]) # alterative model setting`

`print(response)`

`# Set with provider`
`response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Forefront, messages=[`
`                                     {"role": "user", "content": "Hello world"}], stream=True)`

`for message in response:`
`    print(message)`

And below error happens:

Traceback (most recent call last):
  File "D:\Temp\...\Project\src\g4f_test1.py", line 1, in <module>
    import g4f
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\__init__.py", line 2, in <module>
    from . import Provider
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\__init__.py", line 2, in <module>
    from .Providers import (
ModuleNotFoundError: No module named 'g4f.Provider.Providers'

**Environement**
- python version: 3.11.4
- location ( are you in a cloudfare flagged country ): Yes, CN

**Additional context**

**Comment by huayune** [comment]
Me too

**Comment by yifangyujason** [comment]
me too

**Comment by notbrianbob** [comment]
Hello, for anyone who experiences this (I just experienced it too.) I dug around the pip way of installing g4f, as well as the github version. It appears that the pip version is missing the 'Providers' folder.

A work around for this until it is updated is to download the Providers folder from the main github page, then put it where your g4f is installed. (I use anaconda so for me it is 'C:\Users\myname\anaconda3\envs\gpt4free\Lib\site-packages\g4f\Provider' 

I am unsure if there are any other discrepancies so if you run into more errors, one way of debugging you can try is overwrite the entire g4f folder that pip installed, with the github g4f folder. Hope this helps!

**Comment by gongwolf** [comment]
Me too

**Comment by kaka1909** [comment]
> 

I doubt if this is caused the line "Providers" in requirements.txt. 🤔

**Comment by luxkatana** [comment]
Same problem...

**Comment by luxkatana** [comment]
> Hello, for anyone who experiences this (I just experienced it too.) I dug around the pip way of installing g4f, as well as the github version. It appears that the pip version is missing the 'Providers' folder.
> 
> A work around for this until it is updated is to download the Providers folder from the main github page, then put it where your g4f is installed. (I use anaconda so for me it is 'C:\Users\myname\anaconda3\envs\gpt4free\Lib\site-packages\g4f\Provider'
> 
> I am unsure if there are any other discrepancies so if you run into more errors, one way of debugging you can try is overwrite the entire g4f folder that pip installed, with the github g4f folder. Hope this helps!

it didn't really work, in the main branch of ``g4f`` they included the Provider folder too.. But thanks for suggesting

**Comment by nonk123** [comment]
> > Hello, for anyone who experiences this (I just experienced it too.) I dug around the pip way of installing g4f, as well as the github version. It appears that the pip version is missing the 'Providers' folder.
> > A work around for this until it is updated is to download the Providers folder from the main github page, then put it where your g4f is installed. (I use anaconda so for me it is 'C:\Users\myname\anaconda3\envs\gpt4free\Lib\site-packages\g4f\Provider'
> > I am unsure if there are any other discrepancies so if you run into more errors, one way of debugging you can try is overwrite the entire g4f folder that pip installed, with the github g4f folder. Hope this helps!
> 
> it didn't really work, in the main branch of `g4f` they included the Provider folder too.. But thanks for suggesting

The `setup.py` script simply doesn't consider the Provider folder for installation because it doesn't contain an `__init__.py` file. Could you try installing from git again now that my workaround has been merged?

**Comment by ReYaNOW** [comment]
it is now working!
thank you nonk123

**Comment by dzianisv** [comment]
I fixed this by removing 
![image](https://github.com/xtekky/gpt4free/assets/2119348/a0f7b4ca-db80-4dbf-b7b4-082b228cac01)
