### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by Ron-Caster** [xtekky/gpt4free#76]
![image](https://user-images.githubusercontent.com/56224323/233816709-699fdbeb-9fe2-4914-adcb-6b2be5a17be4.png)

I suggested this website to my friends and family, and when they tried to use this appeared. I am also facing the issue.

**Comment by Pudzill** [comment]
you suggested "https://chat.chatbot.sex/chat" to your family and friends? fahaha

**Comment by Ron-Caster** [comment]
> you suggested "https://chat.chatbot.sex/chat" to your family and friends? fahaha

Was more than smart enough to make a webApp and share it via WhatsApp ☺️https://user-images.githubusercontent.com/56224323/233817501-2c0a79b4-749e-45ee-adc9-79be89888094.MOV

**Comment by jw-star** [comment]
+1

**Comment by xtekky** [comment]
hi, currently updating the site ; )

**Comment by xtekky** [comment]
duplicate of #75
