### ISSUE TITLE
g4f.Provider.Providers.Ails return error

### ISSUE THREAD

**Issue by phamxtien** [xtekky/gpt4free#762]
It returns error:
{"error":{"message":"Hey! The webpage has been updated. Please refresh the page and try again.","type":"AI.LS: Please refresh","code":"AI.LS: NEED REFRESH"}}

**Comment by leeeawa** [comment]
#683 You should change the value of client-v in line 50 to the latest version 0.1.255.

**Comment by LovanDog** [comment]
> #683 You should change the value of client-v in line 50 to the latest version 0.1.255. g4f/Provider/Providers/Ails.py `'client-v': '0.1.255',`

doesnt help

**Comment by phamxtien** [comment]
'client-v': '0.1.260',
