### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Opening-Button-8988** [xtekky/gpt4free#766]
**Bug description**
Multiple errors when attempting to run program. Directory is gpt4free. Tried to run inference.app with python3 -m. Following instructions exactly. Fedora Silverblue with Gnome. I am NOT using toolbox.

ex.
1. Follow instructions at https://github.com/xtekky/gpt4free:
2. Ran `pip install -U g4f` but wasn't sure what to do after, because the rest of the instructions say "or", implying that's all you have to do. So I followed the instructions after "or".
3. `git clone https://github.com/xtekky/gpt4free.git`
4. `cd gpt4free`
5. `python3 -m venv venv`
6. `source venv/bin/activate`
7. `pip install -r requirements.txt`
8. `nano test.py`
9. Pasted the code from https://github.com/xtekky/gpt4free#the-g4f-package, appended `providers` exactly as is, two lines below the previous code.
10. `python3 -m interference.app`
11. Errors (see context below). I attempted to remove providers that were apparently not active, narrowed the list down to just bing, it didn't help.

**Environement**
- python 3.11.4
- Not in a cloudflare flagged country.
- pip 22.3.1 (I was prompted to update to 23.2 but haven't yet)

**Additional context**

This is the error:

```
(venv) [user@host gpt4free]$ python3 -m interference.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/var/home/user/gpt4free/interference/app.py", line 6, in <module>
    from g4f import Model, ChatCompletion, Provider
  File "/var/home/user/gpt4free/g4f/__init__.py", line 2, in <module>
    from . import Provider
  File "/var/home/user/gpt4free/g4f/Provider/__init__.py", line 2, in <module>
    from .Providers import (
  File "/var/home/user/gpt4free/g4f/Provider/Providers/Ails.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

```

Am I supposed to understand python to be able to use this project? I think the instructions need to be more accessible for people with little to no programming knowledge. If programming knowledge is required, it should be explained before the instructions, otherwise how are we supposed to know who this project is for? Is the point of this project not to make ChatGPT more accessible?

**Comment by leeeawa** [comment]
run `pip install requests`

**Comment by Opening-Button-8988** [comment]
@leeeawa 

I received this error after issuing that command:

```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests) (1.26.16)
```

**Comment by xuanyuan100** [comment]
> @leeeawa
> 
> I received this error after issuing that command:
> 
> ```
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (2.28.2)
> Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests) (3.1.0)
> Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.4)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests) (1.26.16)
> ```

https://github.com/xtekky/gpt4free/issues/747

**Comment by nonk123** [comment]
> @leeeawa
> 
> I received this error after issuing that command:
> 
> ```
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (2.28.2)
> Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests) (3.1.0)
> Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.4)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests) (1.26.16)
> ```

Not really an error. Seems like you just forgot to activate the virtualenv before running `pip install requests`.
