### ISSUE TITLE
poe Login email waiting for code...

### ISSUE THREAD

**Issue by wangjiegui** [xtekky/gpt4free#77]
email rzydtq1@femailtor.com
{
    "authority": "poe.com",
    "accept": "*/*",
    "accept-language": "en,fr-FR;q=0.9,fr;q=0.8,es-ES;q=0.7,es;q=0.6,en-US;q=0.5,am;q=0.4,de;q=0.3",
    "content-type": "application/json",
    "origin": "https://poe.com/",
    "poe-formkey": "b4c302ac8bf6cefbe398bcb1c2b0d4e70",
    "poe-tag-id": "6ed5a51a1f9945af29679bbc6ccc57d2",
    "poe-tchannel": "poe-chan52-8888-dchzlrpbfbcfcojvdofw",
    "referer": "https://poe.com/login",
    "sec-ch-ua": "\"Chromium\";v=\"112\", \"Google Chrome\";v=\"112\", \"Not:A-Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
}
please try using a proxy / wait for fix
send_code {'data': {'sendVerificationCode': {'status': 'automated_request_detected', 'errorMessage': "Your device or network may be sending automated queries. We can't process your request now."}}, 'extensions': {'is_final': True}}
waiting for code...

**Comment by xtekky** [comment]
"please try using a proxy / wait for fix"
