### ISSUE TITLE
from gpt4free import you

### ISSUE THREAD

**Issue by joe5chen** [xtekky/gpt4free#775]
File "/gpt4free/gpt4free/streamlit_app.py", line 7, in <module>
    from gpt4free import you
ImportError: cannot import name 'you' from 'gpt4free' (unknown location)

**Comment by joe5chen** [comment]
python3 -m streamlit run streamlit_app.py

**Comment by joe5chen** [comment]
This error occurred after running this command

**Comment by joe5chen** [comment]
My Environment Python 3.8.8

**Comment by joe5chen** [comment]
打扰了我找到解决办法了，就是在gpt4free/g4f/.v1下运行那段命令，就可以了

**Comment by nonk123** [comment]
Even though you got the Streamlit app to run, it's from the old, unmaintained gpt4free v1. The v2 (this repository) doesn't have an equivalent yet. You could take a look at [chatgpt-clone](https://github.com/xtekky/chatgpt-clone), but it appears to be either on hiatus ([the official website](https://g4f.ai/) where it is hosted has been reporting "temporary downtime" for about a month by now) or awaiting a v2 release as well.
