### ISSUE TITLE
Can someone please do a video tutorial.

### ISSUE THREAD

**Issue by Androidvova** [xtekky/gpt4free#778]
Can someone please do a video tutorial.

**Comment by nonk123** [comment]
There is no video tutorial. This is a Python library for developing LLM-integrated apps using reverse-engineered APIs. If you just want to chat with the AI, you'll have to use an app created by somebody else. [The official web UI](https://g4f.ai) (similar to OpenAI's ChatGPT) is currently down, but you might find something interesting by searching on GitHub.
