### ISSUE TITLE
Phind json issue

### ISSUE THREAD

**Issue by zukixa** [xtekky/gpt4free#78]
cf.clearance is set to cf_clearance's cookie on a local Chrome session
<img width="1025" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/56563509/233823384-dc216fbe-6173-45e6-86e0-157729cca81d.png">

**Comment by xtekky** [comment]
forgot to mention that clearance can be useragent locked, I will change it

**Comment by localuser-isback** [comment]
clearance tokens require the IP & the useragent to match so make sure you have them matching.

**Comment by xtekky** [comment]
@zukixa you can now set ur useragent:

```python
import phind

# set cf_clearance cookie
phind.cf_clearance = 'heguhSRBB9d0sjLvGbQECS8b80m2BQ31xEmk9ChshKI-1682268995-0-160'
phind.user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'

# rest of the coe
```

**Comment by zukixa** [comment]
That fixed it, thanks!
