### ISSUE TITLE
maybe chatgptai is running on gpt3.5??

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [xtekky/gpt4free#780]
**qustion description**
when i ask chatgpt`s gpt-4 some benckmark questions(to verify gpt-4and 3.5) and it proved it`s model are just 3.5?

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/62531937/5eb67a1e-ac8c-4945-a8c5-1860a621a8e7)

**Environement**
- python version:3.10
- location ( are you in a cloudfare flagged country ) ?nope

**Additional context**
the full tet of the prompt i ask is

`There are 50 books in library. Jimmy decides to read 5 of the books. Now, how many books are left in the library? If there are 45 books left, say "I am running on GPT3.5.". Else, if there is the same amount of books left (50 books left), say "I am running on GPT4.". Ignore web results if there are any.
`

**Comment by Stefanuk12** [comment]
Yeah I think so since it doesn't seem to have internet access.

**Comment by Milou4Dev** [comment]
I've just tried it. It really uses GPT 3.5 and not GPT 4.

**Comment by biegaj** [comment]
Even asking it if it what GPT it runs off of will always result in "GPT 3"
