### ISSUE TITLE
reverse almost every huggingface spaces

### ISSUE THREAD

**Issue by Lachine1** [xtekky/gpt4free#781]
https://huggingface.co/spaces/ysharma/Explore_llamav2_with_TGI
https://huggingface.co/spaces/LinkSoul/Chinese-Llama-2-7b
https://huggingface.co/spaces/lmsys/chatbot-arena
https://huggingface.co/spaces/huggingface-projects/llama-2-13b-chat
https://huggingface.co/spaces/huggingface-projects/llama-2-7b-chat
https://huggingface.co/spaces/monra/freegpt-webui
https://huggingface.co/spaces/huggingchat/chat-ui
https://huggingface.co/spaces/mosaicml/mpt-30b-chat
https://huggingface.co/spaces/HuggingFaceH4/falcon-chat
https://huggingface.co/spaces/cuteanya/cuteproxy
https://huggingface.co/spaces/cuteanya/cutegpt4

**Comment by Lachine1** [comment]
https://huggingface.co/spaces/HuggingFaceH4/falcon-chat-demo-for-blog

**Comment by leeeawa** [comment]
too much
