### ISSUE TITLE
add ai chat android apps

### ISSUE THREAD

**Issue by Lachine1** [xtekky/gpt4free#783]
https://play.google.com/store/apps/details?id=com.pocketai.app
https://play.google.com/store/apps/details?id=com.ai.chat.bot.aichat
https://play.google.com/store/apps/details?id=com.codeway.chatapp
https://play.google.com/store/apps/details?id=com.scaleup.chatai
https://play.google.com/store/apps/details?id=plus.adaptive.goatchat
https://play.google.com/store/apps/details?id=com.chatgpt.ai.bot.open.assistant
https://play.google.com/store/apps/details?id=com.chatbot.ai.aichat.openaibot.chat

**Comment by nacho00112** [comment]
Look at the app HTTPCanary, it's removed from play store so you will need to download the apk, it's like the `network` section of chrome's developer tools but for android apps, this work by HTTPCanary acting as a VPN it captures all the http requests made by the apps

**Comment by bagusindrayana** [comment]
> Look at the app HTTPCanary, it's removed from play store so you will need to download the apk, it's like the `network` section of chrome's developer tools but for android apps, this work by HTTPCanary acting as a VPN it captures all the http requests made by the apps

they change to app called Reqable and not support native mobile app yet https://github.com/MegatronKing/HttpCanary
i try install HTTPCanary from thirdparty android download like apkpure but not luck, did HTTPCanary required root access?

i try reverse some android apps with emulator and httptoolkit (im to retard to use something like burpsuite) most the problem I often face is they encrypted request payload or response, ratio to find unencrypted requests approx 1/5 apps, but if lucky you will find some open ai key (literally they request directly to openai api endpoint)

**Comment by bagusindrayana** [comment]
> 

https://play.google.com/store/apps/details?id=com.chatgpt.ai.bot.open.assistant
https://github.com/bagusindrayana/gpt4free/commit/1a092292cd0b6bd3b857ea6ab208b1f68b868eec#diff-d7ed56b99e8e33a6cf61ca1abbc49d1537e68813ca6e29c57c95cb42588d910f

**Comment by nacho00112** [comment]
> > Look at the app HTTPCanary, it's removed from play store so you will need to download the apk, it's like the `network` section of chrome's developer tools but for android apps, this work by HTTPCanary acting as a VPN it captures all the http requests made by the apps
> 
> they change to app called Reqable and not support native mobile app yet https://github.com/MegatronKing/HttpCanary i try install HTTPCanary from thirdparty android download like apkpure but not luck, did HTTPCanary required root access?
> 
> i try reverse some android apps with emulator and httptoolkit (im to retard to use something like burpsuite) most the problem I often face is they encrypted request payload or response, ratio to find unencrypted requests approx 1/5 apps, but if lucky you will find some open ai key (literally they request directly to openai api endpoint)

That's strange, HTTPCanary have options for root users but it worked for me without root,
May be a better way to reverse those android apps with encrypted requests is reversing their source code, so you will see what encryption they are using

**Comment by bagusindrayana** [comment]
> > > Look at the app HTTPCanary, it's removed from play store so you will need to download the apk, it's like the `network` section of chrome's developer tools but for android apps, this work by HTTPCanary acting as a VPN it captures all the http requests made by the apps
> > 
> > 
> > they change to app called Reqable and not support native mobile app yet https://github.com/MegatronKing/HttpCanary i try install HTTPCanary from thirdparty android download like apkpure but not luck, did HTTPCanary required root access?
> > i try reverse some android apps with emulator and httptoolkit (im to retard to use something like burpsuite) most the problem I often face is they encrypted request payload or response, ratio to find unencrypted requests approx 1/5 apps, but if lucky you will find some open ai key (literally they request directly to openai api endpoint)
> 
> That's strange, HTTPCanary have options for root users but it worked for me without root, May be a better way to reverse those android apps with encrypted requests is reversing their source code, so you will see what encryption they are using

my problem when use HTTPCanary  is installing CA certificate, its easier for me to use emulator and httptoolkit. but I don't think it's worth it to reverse the entire application, it's even too time consuming for me to try to install one by one application at a time just to check what requests are happening behind.

**Comment by nacho00112** [comment]
> my problem when use HTTPCanary is installing CA certificate, its easier for me to use emulator and httptoolkit. but I don't think it's worth it to reverse the entire application, it's even too time consuming for me to try to install one by one application at a time just to check what requests are happening behind.

Yeah the real problem comes with the complexity of reversing the source code, but the possibility there is
