### ISSUE TITLE
DeepAI response: 404 Client Error: Not Found for url: https://api.deepai.org/chat_response

### ISSUE THREAD

**Issue by phamxtien** [xtekky/gpt4free#785]

**Comment by alvindimas05** [comment]
You can change the requests.post url in g4f/Provider/Providers/DeepAi.py to
`
r = requests.post("https://api.deepai.org/make_me_a_pizza", headers=headers, files=files, stream=True)
`

**Note : Your ip may get banned from DeepAi because of this**
