### ISSUE TITLE
please help!

### ISSUE THREAD

**Issue by realsh1tcoder** [xtekky/gpt4free#786]
cmd output:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'gpt' did not return a valid response. The function either returned None or ended without a return statement.

file endpoint.py:
from flask import Flask, request, jsonify
from g4f import Model, ChatCompletion, Provider

app = Flask(__name__)

app.config['message_history'] = []

@app.route('/gpt', methods=['POST'])
def gpt():
    try:
        data = request.json
        user_message = data['message']

        message_history = app.config['message_history']

        print(f'Request. Message: {user_message}')

         response = ChatCompletion.create(model="gpt-3.5-turbo", provider="g4f.Provider.Aichat", messages=[{"role": "system", "content": input_text}])

        user_message = {
            'role': 'user',
            'content': input_text,
        }
        gen_response = {
            'role': 'assistant',
            'content': generated_response
        }

        message_history.extend([user_message, gen_response])

        message_history = message_history[-10:]
        
        return jsonify({"response": response})
    except Exception as e:
        return

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=1337)

file main.py
import requests
import json

SERVER_URL = 'http://127.0.0.1:1337/gpt'

message = input('User: ')

data = {
    "message": message
}

try:
   response = requests.post(SERVER_URL, json=data)

    if response.status_code == 200:
        result = response.json()
        print("Generated Text:")
        print(result)
    else:
        print(f"Request failed with status code {response.status_code}:")
        print(f"ChatGPT: {response.text}")
except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")

Location files:
C:\Users\User\Documents\cgpt\
Python version: 3.11.4

**Comment by nacho00112** [comment]
You used `"g4f.Provider.Aichat"`, it must be `g4f.Provider.Aichat` without the `""`

**Comment by nacho00112** [comment]
Remember to import `g4f` or alternatively use `from g4f import ChatCompletion, Provider` to then use `Provider.Aichat` instead of `g4f.Provider.Aichat`
