### ISSUE TITLE
这不道德吧

### ISSUE THREAD

**Issue by lin2415016** [xtekky/gpt4free#787]
这不就是让其他网站承担这个费用吗？

**Comment by ZYpS-leader** [comment]
你能不能用上啊 我用示例代码就报错requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))
还是中国地区根本就不能用 来自中国的ip都拒绝访问

**Comment by LyazS** [comment]
秦桧的位置你来跪

**Comment by ottocsb** [comment]
Put away your Virgin Heart. Why don't you focus on curbing the development of crawler? It's really funny.

**Comment by xmbhjQAQ** [comment]
lmao
