### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

### ISSUE THREAD

**Issue by ZYpS-leader** [xtekky/gpt4free#789]
is it not allowed in China? I tried to use the example program in the README but it raise the errno `requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))`.

**Comment by Korliore** [comment]
+

**Comment by sohomb91** [comment]
Following.... 
Facing the same error!
Hi @xtekky , any views on this?

**Comment by HeroBarry** [comment]
too

**Comment by wzhslap** [comment]
Is there a solution?

**Comment by xtekky** [comment]
fixed, try using different providers
