### ISSUE TITLE
ora response error

### ISSUE THREAD

**Issue by OnlywaitY** [xtekky/gpt4free#79]
When I call the ora interface in my project, the interface returns an error. 
{'error': {'message': "Cannot read properties of undefined (reading 'filter')", 'err': {}}, 'status': 500}

There is no problem with the test.

**Comment by xtekky** [comment]
ora.sh is working perfectly fine, please give more details

**Comment by OnlywaitY** [comment]
Can you provide some clues on how to solve it? I tested it myself with no problem, but when running it in the project, it gives errors, thx

**Comment by xtekky** [comment]
what do you mean by "running it in the project"

**Comment by OnlywaitY** [comment]
My personal project, just a conversational python script. Do you know anything about this error?

**Comment by xtekky** [comment]
could u share it I'll fix it, could be some bad configuration somewhere

**Comment by OnlywaitY** [comment]
I found it, which is caused by a garbled character contained in the request message I sent, which is my own problem.

Thank you very much for your reply
