### ISSUE TITLE
help help ?why i cant run it

### ISSUE THREAD

**Issue by GEM123668** [xtekky/gpt4free#806]
import g4f

print(g4f.Provider.Ails.params) # supported args

# Automatic selection of provider

# streamed completion
response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', messages=[
                                     {"role": "user", "content": "Hello world"}], stream=True)

for message in response:
    print(message)

# normal response
response = g4f.ChatCompletion.create(model=g4f.models.gpt_4, messages=[
                                     {"role": "user", "content": "hi"}]) # alterative model setting

print(response)

# Set with provider
response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Forefront, messages=[
                                     {"role": "user", "content": "Hello world"}], stream=True)

for message in response:
    print(message)
from g4f.Provider import (
    Ails,
    You,
    Bing,
    Yqcloud,
    Theb,
    Aichat,
    Bard,
    Vercel,
    Forefront,
    Lockchat,
    Liaobots,
    H2o,
    ChatgptLogin,
    DeepAi,
    GetGpt,
    AItianhu,
    EasyChat,
    Acytoo,
    DfeHub,
    AiService,
    BingHuan,
    Wewordle,
    ChatgptAi,
    opchatgpts,
)

# usage:
response = g4f.ChatCompletion.create(..., provider=ProviderName)
![image](https://github.com/xtekky/gpt4free/assets/121158914/0532dc6e-0792-4930-9938-23cdecf2c7f4)

**Comment by bagusindrayana** [comment]
Most of the GPT 4 models that are reversed are unstable, especially Bing, the error you are experiencing comes from the Bing provider

delete all code on try one chat completion
```python
response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Ails, messages=[
    {"role": "user", "content": "Hello world"}], stream=True)
```
try providers one by one or just look at readme see provider that still "Active"

also maybe you want download latest repo because they have new testing code
