### ISSUE TITLE
Some more info

### ISSUE THREAD

**Issue by Anixx** [xtekky/gpt4free#81]
* Phind, according to their official Discord channel, uses GPT-4 when expert mode switch is on (by default). I suppose otherwise it uses GPT-3.

* There are many other services that are missing, for instance, https://gpt-chatbot.ru/ (GPT-4) and others (https://chadgpt.ru/ , https://chatgpt.org , https://chatgptbot.ru/)

**Comment by xtekky** [comment]
yes but i believe that phind's llm is fine tuned or heavily instructed, as it is impossible to have a normal conversation

I appreciate your effort and will take a look at the sites soon, thank you

**Comment by xtekky** [comment]
btw, gpt4 on the russian site is not gpt4

<img width="819" alt="image" src="https://user-images.githubusercontent.com/98614666/233837781-f3c48281-3c91-4729-a7c3-485803af97ac.png">

**Comment by xtekky** [comment]
use #40

**Comment by Anixx** [comment]
There is GPT-4 tab on that site 
![изображение](https://user-images.githubusercontent.com/1271736/233840279-2c34fd92-94ef-481a-81ec-7c8b3cc6b712.png)
If not selected, it uses GPT-3

**Comment by Anixx** [comment]
GPT-3 has green avatar, GPT-4 uses blue one.

**Comment by xtekky** [comment]
I did select the gpt-4 tab, weird

**Comment by xtekky** [comment]
https://gpt-chatbot.ru/chat-gpt-ot-openai-dlya-generacii-teksta this one ? @Anixx

**Comment by Anixx** [comment]
Well, I don't know, maybe you'right, it's GPT-3
