### ISSUE TITLE
Starting a RE PROXY

### ISSUE THREAD

**Issue by mosesman831** [xtekky/gpt4free#811]
Hey guys, first of all thanks for taking your time to read this issue, I just want to ask 2 questions.

1. So how can I host the proxy with OpenAI package? I have read through the whole readme of both repos but I cannot find any detail. 

2. How can I make it host on my public IPv4 IP on my Oracle Cloud Instance? Where do I change the relevant ports and IP to host the proxy? I have tried using 127.0.0.1:55 but it failed to connect from outside my instance.

**Comment by unnaturalistic** [comment]
if you host it in 0.0.0.0:whateverport and connect to it using yourserverip:theport

**Comment by mosesman831** [comment]
But I don’t have any details about how to host it with OpenAI py package. Do you have any instructions for it?
