### ISSUE TITLE
Add support for ChatGPT

### ISSUE THREAD

**Issue by Meshwa428** [xtekky/gpt4free#819]
**what will this feature do?**

Enables us to use chatgpt's web version that is available for free, in the terminal.

**Another request**

Add support for system prompts, all of the gpt 3.5 APIs are now having the ability of system prompts

**Comment by Meshwa428** [comment]
Noo, they are the prompts that  #make the bot behave however we want it to, and these prompts are to be placed in the custom instruction tab of the website. You can view it by selecting the 3 lines on top left, then go to your profile, then you can see the custom instruction tab

**Comment by bagusindrayana** [comment]
> Noo, they are the prompts that #make the bot behave however we want it to, and these prompts are to be placed in the custom instruction tab of the website. You can view it by selecting the 3 lines on top left, then go to your profile, then you can see the custom instruction tab

what website? if you want custom persona/behavior or spesific instructor, you just pass chat message with role : system and message to describe what ai you want like like this
<img width="492" alt="image" src="https://github.com/xtekky/gpt4free/assets/36830534/5b3e29c7-604a-407c-a8e4-c0ede93fb94b">

or this example i make you to be shy guy
<img width="508" alt="image" src="https://github.com/xtekky/gpt4free/assets/36830534/c0f35839-e1d0-4425-81bb-18cbd1967b28">

**Comment by hlohaus** [comment]
I created a provider for the ChatGPT Web Version:
https://github.com/xtekky/gpt4free/blob/main/g4f/Provider/OpenaiChat.py
It use this python project:
https://github.com/acheong08/ChatGPT/tree/main/src/revChatGPT

**Comment by hzlujunyi** [comment]
> I created a provider for the ChatGPT Web Version: https://github.com/xtekky/gpt4free/blob/main/g4f/Provider/OpenaiChat.py It use this python project: https://github.com/acheong08/ChatGPT/tree/main/src/revChatGPT

Hasn't revChatGPT been archived and is not available now?

**Comment by hlohaus** [comment]
It's still in Pipe. Maybe sometimes there is new Project.
