### ISSUE TITLE
Quickjs library installation error

### ISSUE THREAD

**Issue by Luneye** [xtekky/gpt4free#823]
**Bug description**
Hello. With the latest version of g4f, it seems that we are not able to install all the dependencies it on some environments. Indeed, the Quickjs library throws me an error when I try to install it. I am actually using Windows 11 and have Visual Studio 2022 Tools installed.

Here are the steps I performed:
1. Open terminal
2. Type command pip install -U g4f
3. Gets locked with quickjs library with the error:
/Tcmodule.c /Fobuild\temp.win-amd64-cpython-311\Release\module.obj -Werror=incompatible-pointer-types
      clÿ: Ligne de commande error D8021ÿ: argument num‚rique non valide '/Werror=incompatible-pointer-types'
      (which means "command line error: invalid numeric argument")

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/73485421/ad93154d-7d83-4480-a60a-26e10f4ab3ed)

**Environement**
- python version: 3.11
- windows 11

**Already tried solutions that did not work**
- Downgraded to Visual Studio 2017 Tools
- Installation from source (python -m pip install quickjs --no-binary :all: --no-deps)

**Comment by ZaoTX** [comment]
Downgrade Python to 3.10 works for me

**Comment by Luneye** [comment]
Thanks, it worked for me too!
Sadly, it reduces the compatibilty for the whole library. I will try to fix it manually later.
