### ISSUE TITLE
Bard Image recognition support?

### ISSUE THREAD

**Issue by Meshwa428** [xtekky/gpt4free#826]
**PLEASE** add the code to make bard recognise images. Like passing an image file to a function and it uploads the image and the question asked by user, then get the response text from bard

**Comment by bagusindrayana** [comment]
maybe you want check/use another project that can do something you want
https://github.com/dsdanielpark/Bard-API
https://github.com/EvanZhouDev/bard-ai

i think gpt4free focus on just chat in general
