### ISSUE TITLE
Equing Provider does not support gpt-3.5-turbo-16k?

### ISSUE THREAD

**Issue by zing75blog** [xtekky/gpt4free#837]
i have tried enquing provider and its working fine by using gpt-3.5-turbo. But when using gpt-3.5-turbo-16k got error like this:

`File "C:\Users\Asus\anaconda3\lib\site-packages\g4f\Provider\Equing.py", line 58, in create_completion
    yield response.json()["choices"][0]["message"]["content"]
KeyError: 'choices'`

this is my sample code:

`response = g4f.ChatCompletion.create(
                model="gpt-3.5-turbo-16k",
                provider=g4f.Provider.Equing,
                messages=[
                    {"role": "user", "content": "Please generate poem"},
                ],`

**Comment by bagusindrayana** [comment]
no
{"error":{"message":"当前分组 default 下对于模型 openai:gpt-3.5-turbo-16k 无可用渠道","type":"one_api_error"}}
