### ISSUE TITLE
Can I use conversationId for ora gpt4 model?

### ISSUE THREAD

**Issue by mbogomazov** [xtekky/gpt4free#84]
I try to use example from [here](https://github.com/xtekky/gpt4free/tree/main/ora), combining usage of gpt-4 model and `ora.Completion.create()` with `conversationId` argument but get an error from api `{'error': {'message': 'Invalid status code: P2025', 'err': {'code': 'ERR_HTTP_INVALID_STATUS_CODE'}}, 'status': 500}`. What I do wrong and can i use conversationId for gpt-4 or it is possible only for gpt-3.t?

**Comment by xtekky** [comment]
Hi, just updated the gpt4_test.py example in (/testing)[./testing]

**Comment by mbogomazov** [comment]
I understood what my problem was. I try to init and continue conversation in separate scripts by saving and providing only conversationId. But it is necessary to use the same userId too. But still thanks for response
