### ISSUE TITLE
[GUI] Created gpt4free GUI

### ISSUE THREAD

**Issue by rupeshs** [xtekky/gpt4free#85]
I have created a simple gpt4free GUI.
https://github.com/rupeshs/gpt4freegui

**Comment by xtekky** [comment]
awesome, any way to do a pr, could also integrate this myself, credits ofc

**Comment by rupeshs** [comment]
@xtekky Thanks, it is possible, I will create PR later. This one was quick.

**Comment by StantheBrain** [comment]
Good job! 
Alas, I read: Gpt 4, free..., but it should have read GPT, 4free! 
GPT3 is free on OpenAI, faster, and with conversation history. 
The idea would have been good if there had been a plus to the interface proposed by OpenAI, and excellent if this work had been based on AI Dungeon 3.0! 
If the number of requests is not limited in time, it's already good, thanks!

**Comment by rupeshs** [comment]
@xtekky PR ready https://github.com/xtekky/gpt4free/pull/100

**Comment by zakgpt** [comment]
@rupeshs Where is your GPT GUI ? I've got a 404 Error Page.

**Comment by StantheBrain** [comment]
https://intelligence-artificielle.developpez.com/actu/344184/OpenAI-menace-un-projet-GitHub-populaire-d-une-action-en-justice-concernant-l-utilisation-de-l-API-qui-contourne-son-API-payante/

**Comment by StantheBrain** [comment]
A GitHub project GPT4free offers free access to OpenAI's GPT4 and GPT3.5 language models by redirecting requests to sites that have integrated GPT4, such as ''You.com'' and Quora. However, OpenAI sent a letter asking the developer of the project to remove it within five days or face legal action
