### ISSUE TITLE
How do APIs specify service providers?

### ISSUE THREAD

**Issue by Joackk** [xtekky/gpt4free#865]
When I use the command "python3 -m interference.app" to start the server and use the api, I get an error if I use gpt4, I searched the list of problems and got a reply that I need to change the service provider, how do I specify the service provider if I run it this way? I don't seem to be able to specify the service provider in the samples, can you give me a sample of how to specify the service provider using the api?

**Comment by Joackk** [comment]
Hi, is anyone there?

**Comment by bagusindrayana** [comment]
you need edit and provide spesific provider in code
```python
    response = ChatCompletion.create(model=model, 
                                     stream=stream, 
                                     messages=messages,
                                     provider=Provider.Wewordle) # spesify provider
 ```

**Comment by Joackk** [comment]
> you need edit and provide spesific provider in code
> 
> ```python
>     response = ChatCompletion.create(model=model, 
>                                      stream=stream, 
>                                      messages=messages,
>                                      provider=Provider.Wewordle) # spesify provider
> ```

Hi, I know it can be set, but this is used directly, is it also called in the local api? I think the example of calling api is another one, which does not specify the supplier.

**Comment by Joackk** [comment]
> 您需要在代码中编辑并提供特定的提供程序
> 
> ```python
>     response = ChatCompletion.create(model=model, 
>                                      stream=stream, 
>                                      messages=messages,
>                                      provider=Provider.Wewordle) # spesify provider
> ```

In the sample document, the code given after starting the server with "python3-m interference.app" calls the local interface directly and does not describe an example of how to specify a provider. How should I specify it?

**Comment by xtekky** [comment]
Its currently only changeable in the backend as compatibility of the API is only meant to be used with the openai package which does not allow passing this argument in the HTTP request.

You can create a providers list and rotate off of it for better stability:

```
from g4f.Provider A, B, C, D
from random import choice

providers = [A, B, C, D]

response = ChatCompletion.create(model=model, 
                                     stream=stream, 
                                     messages=messages,
                                     provider=choice(providers))

```

**Comment by Joackk** [comment]
> Its currently only changeable in the backend as compatibility of the API is only meant to be used with the openai package which does not allow passing this argument in the HTTP request.
> 
> You can create a providers list and rotate off of it for better stability:
> 
> ```python
> from g4f.Provider import A, B, C, D
> from random import choice
> 
> providers = [A, B, C, D]
> 
> response = ChatCompletion.create(model=model, 
>                                      stream=stream, 
>                                      messages=messages,
>                                      provider=choice(providers))
> ```

Understood. Thank you for your answer.
