### ISSUE TITLE
Add a way for the chatbots to remmember its previous chat

### ISSUE THREAD

**Issue by IYSTREEM** [xtekky/gpt4free#878]
**Is your feature request related to a problem? Please describe.**
whenever I tell the chatbot to mention anything from its previous responses it is unable to do it
**Describe the solution you'd like**
if a way of adding memory was integrated it would be really helpful

**Comment by IYSTREEM** [comment]
> > **Is your feature request related to a problem? Please describe.** whenever I tell the chatbot to mention anything from its previous responses it is unable to do it **Describe the solution you'd like** if a way of adding memory was integrated it would be really helpful
> 
> Of course it's possible, you have to implement a system yourself.

if there any example code available for it?

**Comment by IYSTREEM** [comment]
> > > > **Is your feature request related to a problem? Please describe.** whenever I tell the chatbot to mention anything from its previous responses it is unable to do it **Describe the solution you'd like** if a way of adding memory was integrated it would be really helpful
> > > 
> > > 
> > > Of course it's possible, you have to implement a system yourself.
> > 
> > 
> > if there any example code available for it?
> 
> Yes, I can send some if you'd like.

yes please do

**Comment by cxstles** [comment]
> > > > > **Is your feature request related to a problem? Please describe.** whenever I tell the chatbot to mention anything from its previous responses it is unable to do it **Describe the solution you'd like** if a way of adding memory was integrated it would be really helpful
> > > > 
> > > > 
> > > > Of course it's possible, you have to implement a system yourself.
> > > 
> > > 
> > > if there any example code available for it?
> > 
> > 
> > Yes, I can send some if you'd like.
> 
> yes please do

```py
class Conversation:
    def __init__(self, max_memory=3):
        self.messages = []
        self.max_memory = max_memory

    def add_message(self, role: str, content: str):
        if len(self.messages) >= self.max_memory:
            self.messages.pop(0)  # Remove the oldest message
        self.messages.append({'role': role, 'content': content})

    def get_messages(self):
        return self.messages
```

**Comment by IYSTREEM** [comment]
> > > > > > **Is your feature request related to a problem? Please describe.** whenever I tell the chatbot to mention anything from its previous responses it is unable to do it **Describe the solution you'd like** if a way of adding memory was integrated it would be really helpful
> > > > > 
> > > > > 
> > > > > Of course it's possible, you have to implement a system yourself.
> > > > 
> > > > 
> > > > if there any example code available for it?
> > > 
> > > 
> > > Yes, I can send some if you'd like.
> > 
> > 
> > yes please do
> 
> ```python
> class Conversation:
>     def __init__(self, max_memory=3):
>         self.messages = []
>         self.max_memory = max_memory
> 
>     def add_message(self, role: str, content: str):
>         if len(self.messages) >= self.max_memory:
>             self.messages.pop(0)  # Remove the oldest message
>         self.messages.append({'role': role, 'content': content})
> 
>     def get_messages(self):
>         return self.messages
> ```

thanks
