### ISSUE TITLE
Building wheel for quickjs (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by chekamarue** [xtekky/gpt4free#883]
Building wheels for collected packages: quickjs
  Building wheel for quickjs (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for quickjs (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\quickjs
      copying quickjs\__init__.py -> build\lib.win-amd64-cpython-311\quickjs
      running build_ext
      building '_quickjs' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\upstream-quickjs
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DCONFIG_VERSION=\"2021-03-27\" -DCONFIG_BIGNUM "-IC:\Program Files\Python311\include" "-IC:\Program Files\Python311\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcmodule.c /Fobuild\temp.win-amd64-cpython-311\Release\module.obj -Werror=incompatible-pointer-types
      cl : Command line error D8021 : invalid numeric argument '/Werror=incompatible-pointer-types'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quickjs
Failed to build quickjs
ERROR: Could not build wheels for quickjs, which is required to install pyproject.toml-based projects

even with VS 14.x installed ! i can't pass this step while installing g4f ! any fix ?

**Comment by WeOneGuy** [comment]
Try python 3.10.

**Comment by ambition85** [comment]
I installed python 3.10. but it doesn't work.

**Comment by f24816** [comment]
That is known `quickjs` issue, not related to this project. You should use [venv](https://docs.python.org/3/library/venv.html#module-venv) to setup the right environment.
