### ISSUE TITLE
ERROR: Could not build wheels for quickjs, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by xyzaf1** [xtekky/gpt4free#890]
python -m pip install -r requirements.txt on windows 10 pro got me this error:
Building wheels for collected packages: quickjs
  Building wheel for quickjs (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\quickjs
      copying quickjs\__init__.py -> build\lib.win-amd64-cpython-311\quickjs
      running build_ext
      building '_quickjs' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\upstream-quickjs
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DCONFIG_VERSION=\"2021-03-27\" -DCONFIG_BIGNUM -ID:\AI\gpt4free\venv\include -IC:\Python311\include -IC:\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcmodule.c /Fobuild\temp.win-amd64-cpython-311\Release\module.obj -Werror=incompatible-pointer-types
      cl : Befehlszeile error D8021 : Ung\x81ltiges numerisches Argument /Werror=incompatible-pointer-types.
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quickjs
  Running setup.py clean for quickjs
Failed to build quickjs

**Comment by xyzaf1** [comment]
solution: https://github.com/PetterS/quickjs/files/12180440/quickjs-1.19.2-cp311-cp311-win_amd64.zip

or use python 3.10 (didn't test it, but should work)

**Comment by C0untFloyd** [comment]
Downgrading to Python 3.10.13 worked for me.
