### ISSUE TITLE
[bug?] i don't have latest providers after updating libs pip package

### ISSUE THREAD

**Issue by h4rdee** [xtekky/gpt4free#896]
**Bug description**
I tried to update package using `pip install -U g4f`, and it seems to be working. However, seems like my `site-packages/g4f` still contain old version of lib with old providers. I tried to clear `__pycache__` both in `site-packages` and my project folders with no success. The only thing that helped was to manually clone lib's repo and replace `site-packages/g4f` contents with whatever i manually cloned. Is it normal behavior or somethings wrong with pip package itself?

**Environement**
- python: 3.9.7 x64
- location: doesn't matter in this case

**Comment by xtekky** [comment]
i haven't updated the pip package yet, it should be available a few minutes after this comment, apologise for the inconvenience
