### ISSUE TITLE
[WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by johnd0e** [xtekky/gpt4free#897]
Recent changes introduced by @hlohaus have broke most of the providers, in same manner.

Environment: Windows 10, Python 3.10.11

Sample code:
```py
import g4f
response = g4f.ChatCompletion.create(model='gpt-4', provider=g4f.Provider.Aivvm, messages=[
                                      {"role": "user", "content": "Hello"}], stream=True)
for message in response:
    print(message, end="", flush=True)
```

Result: Valid output but error in the end, see e.g. https://github.com/xtekky/gpt4free/pull/894#issuecomment-1717137234

```
Hello! How may I assist you today?Cancelling an overlapped future failed
future: <_OverlappedFuture pending overlapped=<pending, 0x12443ee3d00> cb=[_ProactorReadPipeTransport._loop_reading()]>
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 71, in _cancel_overlapped
    self._ov.cancel()
OSError: [WinError 6] The handle is invalid
```

This happens to most providers now!

**Comment by hlohaus** [comment]
Can you Update to Python 3.11?
Python have a Bug under Windows.

**Comment by johnd0e** [comment]
Thank you, that is the solution.

**Comment by johnd0e** [comment]
> Can you Update to Python 3.11?

It found that it helps with most of the providers. But not with Bing!
But solution from #898 good for Bing.
