### ISSUE TITLE
Exception: ValueError: Bard does not support "stream" argument

### ISSUE THREAD

**Issue by johnd0e** [xtekky/gpt4free#899]
Recently @hlohaus implemented streaming support for many provides.
But when I trying to use it - some providers return this:

```
Traceback (most recent call last):
  File "D:\AI\gpt4free\bard.py", line 2, in <module>
    response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Bard, messages=[
  File "D:\AI\gpt4free\g4f\__init__.py", line 45, in create
    raise Exception(
Exception: ValueError: Bard does not support "stream" argument
```
This happens with Bard, Aichat and Wewordle.

But when if add `supports_stream = True` manually to their classes - all works as expected.

Environment: Windows 10, Python 3.10.11

Sample code:

```
import g4f
response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Aichat, messages=[
                                      {"role": "user", "content": "Hello"}], stream=True)

for message in response:
    print(message, end="", flush=True)
```

**Comment by hlohaus** [comment]
Some Providers Like Bard doesn't support streaming. They send only one Message. You can enable the API, but they will still have only one Message in Response.

**Comment by johnd0e** [comment]
Thank you for clarifying.
BTW, I've just filed more issues about broken Providers.
