### ISSUE TITLE
Theb: cookies not retrieved 

### ISSUE THREAD

**Issue by johnd0e** [xtekky/gpt4free#903]
https://github.com/xtekky/gpt4free/blob/ac581361da1804e24d73c725cbf10e26716cb3f2/README.md?plain=1#L220

In fact not all providers adapted to this.

E.g. Theb is not aware of `cookies` argument, it expects cookies in `auth`.
And running locally it does not try to get cookies from browser.

P.S.
In general I believe that 2 different argument are excessive.
I propose to keep either `auth` or `cookies`, and get rid of another.

@hlohaus

**Comment by hlohaus** [comment]
TheB need a token from LocalStorage. Reading Cookies from Browser doesn't work here. You have to pass the OrgID and a Token in "auth".
