### ISSUE TITLE
GPL Violation / Missing Credits

### ISSUE THREAD

**Issue by ading2210** [xtekky/gpt4free#909]
Hello xtekky,

Back in late June, I raised an issue regarding the Vercel wrapper included with gpt4free (#698), which was a copy of [ading2210/vercel-llm-api](https://github.com/ading2210/vercel-llm-api/). Unfortunately, it seems that you have decided to completely ignore my concerns about the license violation and re-add the offending code. 

<hr>

The latest commit contains this, which is a copy-paste from the original:
https://github.com/xtekky/gpt4free/blob/ac581361da1804e24d73c725cbf10e26716cb3f2/g4f/Provider/Vercel.py#L67-L84

You only mention that the code for running the JS challenges (`_get_custom_encoding`) is based off of my work, but it's clear that most of the other code is as well. 

For instance, here's the code in gpt4free for generating the request headers:
https://github.com/xtekky/gpt4free/blob/ac581361da1804e24d73c725cbf10e26716cb3f2/g4f/Provider/Vercel.py#L32-L36

And here's the corresponding code from [vercel-llm-api](https://github.com/ading2210/vercel-llm-api/blob/main/vercel-llm-api/src/vercel_ai.py):

```python
#vercel-llm-api/src/vercel_ai.py
#lines 25-26
    self.headers = {
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.{rand1}.{rand2} Safari/537.36",
      
#lines 155-159
    headers = {**self.headers, **{
      "User-Agent": self.headers["User-Agent"].format(
        rand1=random.randint(0,9999),
        rand2=random.randint(0,9999)
      ),
```

All you've done is rearrange a few things, and apparently that's enough for you to claim everything else as your own.

<hr>

It's clear that this is still just a modified version of my original work, which falls under section 5 of the [GNU GPL v3](https://github.com/ading2210/vercel-llm-api/blob/main/LICENSE). Section 5 states that:

> a) The work must carry **prominent notices** stating that you modified it, and giving a relevant date.

A single comment buried halfway down a file does not count as a "prominent notice."

To resolve this violation, you must either:
- Completely remove any offending code from this repository (`g4f/Provider/Vercel.py`).
- Add prominent credits in the README of this project. 

It is extremely dishonest of you to take credit for the work of others, such as me and the other contributors to this project. It also goes against the spirit of open-source software in general. Contributors should at least expect to be recognized for their work, and not to have their credits wiped away a few months later like [you have done in the past](https://github.com/xtekky/gpt4free/commit/5db58fd87f230fbe5bae599bb4b120ab42cad3be#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L228).

Also, this isn't just a matter of being credited. Since you have a [Patreon](https://www.patreon.com/xtekky) and a [Ko-fi](https://ko-fi.com/xtekky) page, you are making money off of other people's work as well. 

This is the third time that you have broken the license on one of my projects so far. If this isn't fixed within a week, I will not hesitate to submit a DMCA takedown request to Github. 

Thanks,
ading2210

**Comment by mishalhossin** [comment]
God damn

**Comment by xtekky** [comment]
This has been added in a pull request, this code was not written by me. I initially completely deleted vercel from this repository. As of why I accepted the pull, I have a quite busy schedule and a lot of pull requests which I have to review and merge quickly making sure they are safe, looking out for vulnerabilities or trojans, this piece of code seemed fine to me.

I am also not making money on kofi and patreon, please do not make assumptions.

I will be removing the code again, please accept my apology.
