### ISSUE TITLE
does anyone have a coding/ai something like gpt that dosent have a limit on how many chars i can send

### ISSUE THREAD

**Issue by xmoufyy** [xtekky/gpt4free#91]

**Comment by localuser-isback** [comment]
This is sadly impossible as there API limits the number of words based on there API, you can always re-prompt it or use a different GPT version and hope they have a higher word count.

**Comment by localuser-isback** [comment]
> vector database and embeddings

Most of the time its alot of hassle for them which offers minimal return id assume but im not a company myself so yknow take that with a grain of salt
