### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by hawk911** [xtekky/gpt4free#916]
**Bug description**
I use docker-compose and have an error. 

```
docker compose up
[+] Running 1/0
 - Container gpt4free-v2-gpt4free-1  Created                                                                                                                                              0.0s Attaching to gpt4free-v2-gpt4free-1
gpt4free-v2-gpt4free-1  | Traceback (most recent call last):
gpt4free-v2-gpt4free-1  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
gpt4free-v2-gpt4free-1  |     return _run_code(code, main_globals, None,
gpt4free-v2-gpt4free-1  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
gpt4free-v2-gpt4free-1  |     exec(code, run_globals)
gpt4free-v2-gpt4free-1  |   File "/app/interference/app.py", line 10, in <module>
gpt4free-v2-gpt4free-1  |     from g4f import ChatCompletion
gpt4free-v2-gpt4free-1  |   File "/app/g4f/__init__.py", line 2, in <module>
gpt4free-v2-gpt4free-1  |     from g4f        import models
gpt4free-v2-gpt4free-1  |   File "/app/g4f/models.py", line 4, in <module>
gpt4free-v2-gpt4free-1  |     from .Provider   import BaseProvider
gpt4free-v2-gpt4free-1  |   File "/app/g4f/Provider/__init__.py", line 28, in <module>
gpt4free-v2-gpt4free-1  |     from .Vercel        import Vercel
gpt4free-v2-gpt4free-1  | ModuleNotFoundError: No module named 'g4f.Provider.Vercel'
gpt4free-v2-gpt4free-1 exited with code 1
```

**Comment by MUTRO888** [comment]
me too!

**Comment by C0untFloyd** [comment]
The vercel provider was removed for whatever reason...

**Comment by yudapao** [comment]
俺也一样

**Comment by MUTRO888** [comment]
> The vercel provider was removed for whatever reason...
do you know how to fix it?

**Comment by C0untFloyd** [comment]
Yes, restore Vercel.py from the version before this and put it back into providers again. You could also use my fork instead https://github.com/C0untFloyd/gpt4free-gradio which tries to stay up-to-date and has a chatbot UI.

**Comment by MUTRO888** [comment]
> Yes, restore Vercel.py from the version before this and put it back into providers again. You could also use my fork instead https://github.com/C0untFloyd/gpt4free-gradio which tries to stay up-to-date and has a chatbot UI.

i did not find the Vercel.py,but i found one in your fork. i copied it and out it into the "gf4-provider",but when i loaded the website ,it showed 404

**Comment by C0untFloyd** [comment]
Sorry, I don't use docker and don't know the docker image does or what website you're talking about.

**Comment by MUTRO888** [comment]
> Sorry, I don't use docker and don't know the docker image does or what website you're talking about.

can you please tell me your solutions?thank you very much!

**Comment by C0untFloyd** [comment]
Issue has been resolved, just do a git pull.
