### ISSUE TITLE
pip install phind

### ISSUE THREAD

**Issue by FiveTechSoft** [xtekky/gpt4free#92]
pip install phind
ERROR: Could not find a version that satisfies the requirement phind (from versions: none)
ERROR: No matching distribution found for phind

How to solve it ?

many thanks!

**Comment by FiveTechSoft** [comment]
its provided in the example

https://github.com/xtekky/gpt4free/blob/main/phind/phind_test.py

**Comment by FiveTechSoft** [comment]
the solution was to rename __init__.py as phind.py

https://github.com/xtekky/gpt4free/blob/main/phind/__init__.py

**Comment by AbdelrhmanNile** [comment]
> the solution was to rename **init**.py as phind.py
> 
> https://github.com/xtekky/gpt4free/blob/main/phind/__init__.py

the solution actually is to move the `phind_test.py` into the parent directory so it can be imported but yeah this works too

**Comment by FiveTechSoft** [comment]
> @FiveTechSoft i know but how about getting my own cookie?

With such value works, no idea where it comes from

**Comment by AbdelrhmanNile** [comment]
@markstark74 rename the file `__init__.py` to `phind.py`

**Comment by AbdelrhmanNile** [comment]
no need for installing anything
