### ISSUE TITLE
Doesn't work via docker

### ISSUE THREAD

**Issue by stasbalazuk** [xtekky/gpt4free#927]
**Bug description**
I did everything according to these instructions:
Setting up with Docker:
If you have Docker installed, you can easily set up and run the project without manually installing dependencies.

First, ensure you have both Docker and Docker Compose installed.

Install Docker
Install Docker Compose
Clone the GitHub repo:

git clone https://github.com/xtekky/gpt4free.git
Navigate to the project directory:
cd gpt4free
Build the Docker image:
docker compose build
Start the service using Docker Compose:
docker compose up
You server will now be running at http://localhost:1337. You can interact with the API or run your tests as you would normally.

To stop the Docker containers, simply run:

docker compose down
Note: When using Docker, any changes you make to your local files will be reflected in the Docker container thanks to the volume mapping in the docker-compose.yml file. If you add or remove dependencies, however, you'll need to rebuild the Docker image using docker compose build.

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/36307559/85e12673-6137-48ac-911b-e870bc449920)
![image](https://github.com/xtekky/gpt4free/assets/36307559/651c31cb-1394-458c-a2b2-4045688049fd)
![image](https://github.com/xtekky/gpt4free/assets/36307559/bfb4aecf-449f-47ec-ba9e-2b71afa0bc54)

**Comment by sadnessgirl** [comment]
I encountered the same proble

**Comment by FacundoMartinezCampos** [comment]
same problem!

**Comment by Quynhpt98** [comment]
the same here

**Comment by maclxf** [comment]
the same too

**Comment by thebigbone** [comment]
It's an API, not a web interface. Use ```/chat/completions``` endpoint and send a POST request with appropriate data.

Like this:

```bash
curl -X POST -H "Content-Type: application/json" -d '{
  "model": "gpt-3.5-turbo",
  "stream": false,
  "messages": [
    {
      "role": "user",
      "content": "hello, are you GPT 4?"
    }
  ]
}' http://localhost:1337/chat/completions

```

Response:

```json
{
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "Hello! Yes, I am powered by GPT-4.0. How can I assist you today?",
        "role": "assistant"
      }
    }
  ],

```

**Comment by stasbalazuk** [comment]
When I perform a POST request I get the following result:

![image](https://github.com/xtekky/gpt4free/assets/36307559/c3b4fc71-fed2-4e35-99b4-b2c6bd94ec94)
![image](https://github.com/xtekky/gpt4free/assets/36307559/a92d2228-dad9-4ac6-a8cd-843700f76d59)

**Comment by maclxf** [comment]
> When I perform a POST request I get the following result:
> 
> ![image](https://user-images.githubusercontent.com/36307559/269992546-c3b4fc71-fed2-4e35-99b4-b2c6bd94ec94.png) ![image](https://user-images.githubusercontent.com/36307559/269992725-a92d2228-dad9-4ac6-a8cd-843700f76d59.png)

I got this too.
Try to set Provider is the same result.

**Comment by thebigbone** [comment]
> When I perform a POST request I get the following result:
> 
> ![image](https://user-images.githubusercontent.com/36307559/269992546-c3b4fc71-fed2-4e35-99b4-b2c6bd94ec94.png) ![image](https://user-images.githubusercontent.com/36307559/269992725-a92d2228-dad9-4ac6-a8cd-843700f76d59.png)

Try it again. For some reason, it raises an exception.

**Comment by maclxf** [comment]
> When I perform a POST request I get the following result:
> 
> ![image](https://user-images.githubusercontent.com/36307559/269992546-c3b4fc71-fed2-4e35-99b4-b2c6bd94ec94.png) ![image](https://user-images.githubusercontent.com/36307559/269992725-a92d2228-dad9-4ac6-a8cd-843700f76d59.png)

I pull the latest commit and build again today.
I got this.
```
{
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {
                "content": "Error",
                "role": "assistant"
            }
        }
    ],
    "created": 1695617083
}
```

**Comment by Quynhpt98** [comment]
@maclxf  I Just pulled and tested, and everything is working for me, try to pull and check again!

**Comment by n1rvanahq** [comment]
What am I doing wrong?

![2023-9-29 21-5-34](https://github.com/xtekky/gpt4free/assets/51777618/b6940dd6-f482-4c3e-be63-b01d57d084e5)
