### ISSUE TITLE
Getting an error whan using AIVVM provider

### ISSUE THREAD

**Issue by A-FERRULLI** [xtekky/gpt4free#928]
**Bug description**
While trying for a second time the library with the provider AIVVM, I encountered a bug, the response the library get's back now is 'Error' with a response code of 500. Before, a couple of days ago it was working fine. An the weird thing is the version on their website ([chat.aivvm.com](https://chat.aivvm.com)) is still working.

1. Send any prompt using the provider 'g4f.Provider.Aivvm'
2. Send it
3. See error

**Environement**
- python version 3.9
- location France

**Additional context**
I'm using it through a Flask app, but I tried without, just regular python and g4f and still, error...

**Comment by A-FERRULLI** [comment]
Edited for spelling

**Comment by reciprocated** [comment]
> **Bug description** While trying for a second time the library with the provider AIVVM, I encountered a bug, the response the library get's back now is 'Error' with a response code of 500. Before, a couple of days ago it was working fine. An the weird thing is the version on their website ([chat.aivvm.com](https://chat.aivvm.com)) is still working.
> 
> 1. Send any prompt using the provider 'g4f.Provider.Aivvm'
> 2. Send it
> 3. See error
> 
> **Environement**
> 
> * python version 3.9
> * location France
> 
> **Additional context** I'm using it through a Flask app, but I tried without, just regular python and g4f and still, error...

Oh, I think `Aivvm` is now utilizing Cloudflare. I attempted to use it in the past, and I'm quite certain it used Cloudflare protection.

**Comment by A-FERRULLI** [comment]
Oh, then how can we use it then ? Or is it the point of Cloudflare, to block any outside api calls ?

**Comment by xtekky** [comment]
should be fixed

**Comment by reciprocated** [comment]
> should be fixed

did the pypi lib get updated 2?
