### ISSUE TITLE
RuntimeError: Use "create_async" instead of "create" function in a async loop.

### ISSUE THREAD

**Issue by bitsnaps** [xtekky/gpt4free#937]
I've just tried to run the code on README using colab, and everything works fine except this one:
```python
# Set with provider
response = g4f.ChatCompletion.create(
    model="gpt-3.5-turbo",
    provider=g4f.Provider.DeepAi,
    messages=[{"role": "user", "content": "Tell me a joke"}],
    stream=True
)

for message in response:
    print(message)
```
It throws `RuntimeError: Use "create_async" instead of "create" function in a async loop.`, I tried to set `stream` to `False` but it didn't help.

P.S. At the beginning I got an error for missing `execjs` dependency, until I installed `PyExecJS` package ( using: `%pip install PyExecJS`.).

**Comment by mraniki** [comment]
I hit similar issue. Might be due to the provider setup.
Try Bing. I manage to get it work with this code
https://github.com/mraniki/MyLLM/blob/main/myllm/main.py

**Comment by hlohaus** [comment]
You have to use create_async, if your code run already a async loop in the parent:
```
response = await  g4f.ChatCompletion.create_async(
    model="gpt-3.5-turbo",
    provider=g4f.Provider.DeepAi,
    messages=[{"role": "user", "content": "Tell me a joke"}]
)
print(response)
```

**Comment by bitsnaps** [comment]
> You have to use create_async, if your code run already a async loop in the parent:
> 
> ```
> response = await  g4f.ChatCompletion.create_async(
>     model="gpt-3.5-turbo",
>     provider=g4f.Provider.DeepAi,
>     messages=[{"role": "user", "content": "Tell me a joke"}]
> )
> print(response)
> ```

Nice, but now the response need to be formatted somehow? (I get `<coroutine object ChatCompletion.create_async at 0x7c3ee3b2ace0>` in the output)

**Comment by hlohaus** [comment]
The await is missing, if you have a coroutine.

**Comment by bitsnaps** [comment]
> The await is missing, if you have a coroutine.

Oops! my bad, you're totally right
```python
# Set with provider
response = await g4f.ChatCompletion.create_async(
    model="gpt-3.5-turbo",
    provider=g4f.Provider.DeepAi,
    messages=[{"role": "user", "content": "Tell me a joke"}],
)
print(response)
```
I'll sent PR to update the doc.
