### ISSUE TITLE
Probably unnecessary dependencies

### ISSUE THREAD

**Issue by RockChinQ** [xtekky/gpt4free#942]
**Bug description**
Hi there, I just made a project which depends gpt4free, but when I build a docker image for it, I found it's extremly large (up to 10GB), and I found torch, tensorflow and transformers depended by g4f.  
In my view, such a reverse engineering lib will only need requests, websockets or other network-related libs, is these DL related libs unnecessary and can I uninstall them?

**Environement**
- base image: python:3.10.13-bullseye
- python 3.10.13
- location: China, host loc: Eastern Asia

**Additional context**
- dockerfile: https://github.com/RockChinQ/free-one-api/blob/main/Dockerfile
- docker image: rockchin/free-one-api

**Comment by iaston** [comment]
agree +1

**Comment by RockChinQ** [comment]
After uninstalling these dependencies and delete dir starts with nvidia* in the site-package dir, g4f still work well. So I guess these packages were added accidently?
