### ISSUE TITLE
Bing Proxy

### ISSUE THREAD

**Issue by owlcloud** [xtekky/gpt4free#948]
Is it possible to add proxy support to bing as an argument?
It worked well for me, but today he decided to tell me that he could not create a new conversation, and before that, by mistake in the loop code, I sent too many requests, and he probably blocked me by ip.

**Comment by owlcloud** [comment]
Missing conversationSignature in response

**Comment by devashish-bhake** [comment]
same here the bing provider is for some reason not giving any response.

**Comment by owlcloud** [comment]
Bing does not provide a response because when creating a conversation, a json response is received, but without conversationSignature. The problem may be with authorization. I tried a proxy, the result was the same. I haven't tried cookies yet.

**Comment by devashish-bhake** [comment]
the cookies will probably result the same. I am guessing the problem is in storing the cookies because it may not be able to keep the cookies active.

**Comment by devashish-bhake** [comment]
One more peculiarity that i noticed when working with gradio for testing interfacing and prompting for gpt-4, is if you put a prompt and it throws an error with no logs in gradio terminal, just submitting a blank string after that error will result in the output of the previous prompt which resulted the error. I don't understand how and why did that happen.

**Comment by devashish-bhake** [comment]
also with bing it most of the times results in 'Exception: Failed to create conversation.'

**Comment by hlohaus** [comment]
i fixed the issue with conversationSignature and Failed to create conversation.
if i clear the cookie jar, the second request works.

**Comment by devashish-bhake** [comment]
could you elaborate step by step or in code so that I can get a better idea..?

**Comment by hlohaus** [comment]
You can now pass proxy at create:

...create(...., proxy="http://host:post")
