### ISSUE TITLE
If some one is free please tell me the best way to use Openaichat.py provider

### ISSUE THREAD

**Issue by Meshwa428** [xtekky/gpt4free#949]
Please 🙏 tell me how to implement the access token in Openaichat

I was trying to pass the acces token in the chatcompletion.create(other stuff...,
          access_token="my access token")

But still it won't responde and just gives out some errors

**Comment by hlohaus** [comment]
Yes instead of Cookies, you can pass the access_token. Where did you get the token from?

**Comment by Meshwa428** [comment]
You can get the access token from https://chat.openai.com/api/auth/session

**Comment by hlohaus** [comment]
You have still errors?
```
    response = g4f.ChatCompletion.create(
        model=g4f.models.gpt_35_turbo,
        provider=g4f.Provider.OpenaiChat,
        messages=[{"role": "user", "content": "Create me a image with a lion."}],
        access_token="eyJhbGciOiJ.........",
        auth=True
    )
```
Works for me

**Comment by Sublexyy** [comment]
how to enable gpt4? i've a plus subscription, if i use this code

`response = g4f.ChatCompletion.create(
    model=g4f.models.gpt_4,
    provider=g4f.Provider.OpenaiChat,
    messages=[{"role": "user", "content": "am i talking with gpt4?"}],
    access_token="XXXX",
    auth=True`
    
  it answers:
  
  You are currently interacting with ChatGPT, which is based on the GPT-3.5 architecture. As of my last knowledge update in September 2021, GPT-4 had not been released. If there have been any subsequent versions released after that date, I would not have information about them. Please check the official OpenAI website or other reliable sources for the most up-to-date information on their AI models.

**Comment by loic-roux-404** [comment]
> how to enable gpt4? i've a plus subscription, if i use this code
> 
> `response = g4f.ChatCompletion.create( model=g4f.models.gpt_4, provider=g4f.Provider.OpenaiChat, messages=[{"role": "user", "content": "am i talking with gpt4?"}], access_token="XXXX", auth=True`
> 
> it answers:
> 
> You are currently interacting with ChatGPT, which is based on the GPT-3.5 architecture. As of my last knowledge update in September 2021, GPT-4 had not been released. If there have been any subsequent versions released after that date, I would not have information about them. Please check the official OpenAI website or other reliable sources for the most up-to-date information on their AI models.
> 
> how can i use gpt4?

GPT4 not available
