### ISSUE TITLE
Ora gpt-4 is broken

### ISSUE THREAD

**Issue by mbogomazov** [xtekky/gpt4free#95]
Got an error (also it would be nice if you add error handling to code): `{'conversationId': '7f35d2b2-d869-4786-a9fc-6b65cd9bbb94', 'userId': '63aae951-feeb-4cd3-8fa1-e6d6918d61cf', 'elapsed': 92, 'error': {'title': 'Authentication error', 'message': 'Specified user must be signed in'}}` when use example from repo

**Comment by xtekky** [comment]
fixed, check the readme.md

```python
# if using CompletionModel.load set these
ora.user_id = '...'
ora.session_token = '...'

# normal gpt-4: b8b12eaa-5d47-44d3-92a6-4d706f2bcacf
model = ora.CompletionModel.load(chatbot_id, 'gpt-4') # or gpt-3.5
```

**Comment by onetenthdev** [comment]
ur broken, gottem

**Comment by xtekky** [comment]
wym lmfao
