### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Vaksoa** [xtekky/gpt4free#96]
1. Are there any plans on implementing something like AutoGPT with these API's?
2. Will there be support for large documents (or codebases) via vector databases to exceed some character limitations?
3. Will there be quick follow-up questions after an answer to press and send?
4. Will there be a prompt hub like in SinCode (Marve)?
5. Are there any plans to attribute sources to the response prompts if the internet access is enabled?
6. Also will there be any additional functionality like answer regeneration, editing, system messages, etc...?

**Comment by onetenthdev** [comment]
yo @Vaksoa less entitlement, plz build yourself or get lost 😝

@xtekky is building tools for the broader people. very much appreciate, cant take focus

**Comment by thanhtoan1196** [comment]
any updates?
