### ISSUE TITLE
Bing Images

### ISSUE THREAD

**Issue by timaaos** [xtekky/gpt4free#960]
**Is your feature request related to a problem? Please describe.**
I want to get images that Bing GPT-4 generates.

**Describe the solution you'd like**
The Image in PIL format or base64 png

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Also, when Bing GPT-4 generates image - it gives error smth like KeyError: 'adaptiveCards' on 263 line of Bing.py

**Comment by hlohaus** [comment]
i fixed the error.
Also i added in this case a link in the response:

Prompt:
Create me a image with a lion.

Response:
Sure, I'll try to create that for you.

https://www.bing.com/images/create?q=a%20lion
