### ISSUE TITLE
Which model to use in PerplexityAi?

### ISSUE THREAD

**Issue by Sid1249** [xtekky/gpt4free#964]
Bug description
I'm trying to use the PerplexityAi provider from the g4f package to translate Hindi text to English using the gpt-3.5-turbo model. However, I'm encountering an HTTP 403 error when attempting to send a request to Perplexity.ai.

Steps to reproduce:

Downloaded the g4f repo and set up the environment.
Ran the provided script to translate Hindi text from an input directory.
Utilized the PerplexityAi provider for the g4f.ChatCompletion.create method.
Encountered the HTTP Error 403 while processing.

Code:
```
def get_translation_from_model(hindi_text):
    prompt = "Translate the following Hindi text Strictly to English, your response should be without any explanatory " \
             "text or markdown\n\n" + hindi_text
    try:
        response = g4f.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            provider=PerplexityAi
        )
        print(response)
        return response
    except Exception as e:
        print(f"Error encountered while translating: {str(e)}")
        return ""

```

Screenshots
<img width="487" alt="Screenshot 2023-10-01 at 11 46 48 AM" src="https://github.com/xtekky/gpt4free/assets/33166377/cbfb88c9-7c96-430e-849b-3e7a72a447a2">

Environment

Python version: 3.9
Location: India, not flagged by cloudfare

Additional context
I've looked into the internal library code for the PerplexityAi provider and noticed that it might not use gpt-3.5-turbo, in that case what should be the model here?

**Comment by st4rted** [comment]
> Bug description I'm trying to use the PerplexityAi provider from the g4f package to translate Hindi text to English using the gpt-3.5-turbo model. However, I'm encountering an HTTP 403 error when attempting to send a request to Perplexity.ai.
> 
> Steps to reproduce:
> 
> Downloaded the g4f repo and set up the environment. Ran the provided script to translate Hindi text from an input directory. Utilized the PerplexityAi provider for the g4f.ChatCompletion.create method. Encountered the HTTP Error 403 while processing.
> 
> Code:
> 
> ```
> def get_translation_from_model(hindi_text):
>     prompt = "Translate the following Hindi text Strictly to English, your response should be without any explanatory " \
>              "text or markdown\n\n" + hindi_text
>     try:
>         response = g4f.ChatCompletion.create(
>             model="gpt-3.5-turbo",
>             messages=[{"role": "user", "content": prompt}],
>             provider=PerplexityAi
>         )
>         print(response)
>         return response
>     except Exception as e:
>         print(f"Error encountered while translating: {str(e)}")
>         return ""
> ```
> 
> Screenshots <img alt="Screenshot 2023-10-01 at 11 46 48 AM" width="487" src="https://user-images.githubusercontent.com/33166377/271811881-cbfb88c9-7c96-430e-849b-3e7a72a447a2.png">
> 
> Environment
> 
> Python version: 3.9 Location: India, not flagged by cloudfare
> 
> Additional context I've looked into the internal library code for the PerplexityAi provider and noticed that it might not use gpt-3.5-turbo, in that case what should be the model here?

for provider, try using `g4f.Provider.PerplexityAI`.

**Comment by st4rted** [comment]
> Bug description I'm trying to use the PerplexityAi provider from the g4f package to translate Hindi text to English using the gpt-3.5-turbo model. However, I'm encountering an HTTP 403 error when attempting to send a request to Perplexity.ai.
> 
> Steps to reproduce:
> 
> Downloaded the g4f repo and set up the environment. Ran the provided script to translate Hindi text from an input directory. Utilized the PerplexityAi provider for the g4f.ChatCompletion.create method. Encountered the HTTP Error 403 while processing.
> 
> Code:
> 
> ```
> def get_translation_from_model(hindi_text):
>     prompt = "Translate the following Hindi text Strictly to English, your response should be without any explanatory " \
>              "text or markdown\n\n" + hindi_text
>     try:
>         response = g4f.ChatCompletion.create(
>             model="gpt-3.5-turbo",
>             messages=[{"role": "user", "content": prompt}],
>             provider=PerplexityAi
>         )
>         print(response)
>         return response
>     except Exception as e:
>         print(f"Error encountered while translating: {str(e)}")
>         return ""
> ```
> 
> Screenshots <img alt="Screenshot 2023-10-01 at 11 46 48 AM" width="487" src="https://user-images.githubusercontent.com/33166377/271811881-cbfb88c9-7c96-430e-849b-3e7a72a447a2.png">
> 
> Environment
> 
> Python version: 3.9 Location: India, not flagged by cloudfare
> 
> Additional context I've looked into the internal library code for the PerplexityAi provider and noticed that it might not use gpt-3.5-turbo, in that case what should be the model here?

Actually, ignore my previous reply. `PerplexityAI` is not working. I just checked, and yeah, it's down.
