### ISSUE TITLE
Bing Provider Captcha Issues

### ISSUE THREAD

**Issue by NCCoder2** [xtekky/gpt4free#966]
Whenever I try using the gpt-4 model with Bing, it says, "CaptchaChallenge: User needs to solve CAPTCHA to continue."  Anyway to bypass this?

**Comment by hlohaus** [comment]
You can solve the Captcha in your Browser. Open the Bing Website and create a new Conversation. A Captcha should be shown. G4F use automatic the Cookies/Session from your Browser.

**Comment by Hilbert-Yaa** [comment]
It doesn't work on my end...

**Comment by DoxrGitHub** [comment]
The fake cookies don't work for me either. I too am getting this issue.

**Comment by firedfox** [comment]
The solution @hlohaus provided works for me.

Try open the developer tools on [bing.com]() in browser and run following js code in the console to get all cookies.

```js
JSON.stringify(document.cookie
  .split(';')
  .reduce((acc, cur) => {
    cookie = cur.trim().split('=');
    acc[cookie[0]] = cookie[1];
    return acc;
}, {}))
```

Then paste the JSON text into the python code to replace `{"Fake": ""}`
