### ISSUE TITLE
g4f.Provider.Aivvm can't work at new version v-0.1.4.2

### ISSUE THREAD

**Issue by tianlichunhong** [xtekky/gpt4free#969]
Is there a bug in the new version? g4f.Provider.Aivvm work fine in version v-0.1.4.0. But after：pip install -U g4f， g4f.Provider.Aivvm not work anymore. Other provider work fine.

Error in v-0.1.4.2:

Traceback (most recent call last):
  File "/test.py", line 41, in <module>
    for message in response:
  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/Aivvm.py", line 62, in create_completion
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://chat.aivvm.com/api/chat

**Comment by xtekky** [comment]
should work again now
<img width="998" alt="image" src="https://github.com/xtekky/gpt4free/assets/98614666/26c3d167-17c0-4a85-8c72-b73a866c39d0">

**Comment by tianlichunhong** [comment]
Yes, work fine. Thank you very much for your hard work!  ：）
