### ISSUE TITLE
where to find the value of 'cf_clearance' cookie for phind.com?

### ISSUE THREAD

**Issue by AbdelrhmanNile** [xtekky/gpt4free#97]
where to find it? using firefox browser

**Comment by localuser-isback** [comment]
Im  going to be releasing an API to generate the token for you but you can extract it from the dev console in the application cookies

**Comment by AbdelrhmanNile** [comment]
@localuser-isback i looked in Storage -> cookies and didnt find it there, i also used this [CF-Clearance-Scraper](https://github.com/Xewdy444/CF-Clearance-Scraper) and it says phind.com doesnt have a cloudflare captcha
can you tell how to extract it exactly?

**Comment by xtekky** [comment]
@AbdelrhmanNile Hi, you can look in the cookies tab in your browser or open devtools > network > click on any request that is using the sites url and then search for clearance token in the headers or in the cookies tab of the request

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/98614666/234081077-5fb14e2e-01da-428f-a301-70d5354878b7.png">

**Comment by AbdelrhmanNile** [comment]
@xtekky thanks!

**Comment by AbdelrhmanNile** [comment]
well, its not there
<img src="https://i.imgur.com/bygtih5.jpg">

**Comment by xtekky** [comment]
weird, I think they removed Cloudflare, could u just set the cookie to empty ? @AbdelrhmanNile I will check it rn

**Comment by AbdelrhmanNile** [comment]
@xtekky yeah it works without the cookie
