### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by toulefan** [xtekky/gpt4free#970]
Hello, when I enter http://localhost:1337/ in my browser it returns a blank page with that written :
### **Not Found**
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

And this line also appears in the docker : 
`2023-10-02 15:28:28 172.18.0.1 - - [02/Oct/2023 13:28:28] "GET / HTTP/1.1" 404 -`

So I also tried the adress http://172.18.0.2:1337/
but my browser won't give me access to that page giving the ERR_CONNECTION_TIMED_OUT as error message.

Please can you help me fix that ?

**Comment by Skolaczk** [comment]
I have the same bug

**Comment by darthalex2014** [comment]
+

**Comment by Wodksk** [comment]
我也是，怎么都访问不了

**Comment by OKHand-Zy** [comment]
I have the same bug . 
have any one fix it?

**Comment by OstriySous** [comment]
+1
Any fixes?

**Comment by shdf2** [comment]
Same problem here.
Please fix this !

**Comment by xtekky** [comment]
this is not to display the gui, just an inteference api
