### ISSUE TITLE
multiple values for keyword argument 'stream'

### ISSUE THREAD

**Issue by tristandevs** [xtekky/gpt4free#976]
**Code:**
```py
import g4f
import asyncio

async def main():
 response = await g4f.ChatCompletion.create_async(
    model="gpt-4",
    provider=g4f.Provider.Bing,
    messages=[{"role": "user", "content": "Hello world"}],
    stream=True,
 )

 print(response)

asyncio.run(main())
```

**Error:**
`TypeError: g4f.Provider.Bing.Bing.create_async_generator() got multiple values for keyword argument 'stream'`

**Comment by hlohaus** [comment]
create_async doesn't support stream=True,

**Comment by plia7** [comment]
> create_async doesn't support stream=True,

@hlohaus Hi, do you have an example for a small code snippet where you can use stream=True?

I want to basically make it stream the respond in the command line, is it possible?

Thank you.

**Comment by hlohaus** [comment]
I have included the AsyncClient with examples in the documentation.
