### ISSUE TITLE
Create monitoring website.

### ISSUE THREAD

**Issue by taiyi747** [xtekky/gpt4free#98]
https://chat.gpt.bz/
The website has gone down. In fact, many websites are currently experiencing crashes and service interruptions due to high traffic. I think we need to set up a monitoring webpage to confirm if the websites are down.

I should have the energy to do something in this area, but I don't know what your thoughts are on this issue. Websites require servers to run. 

Can you provide a little support?

**Comment by localuser-isback** [comment]
I agree, alot of these open links die fast due to that reason exactly or often the owner shuts them down after it starts costing them.

**Comment by xtekky** [comment]
I think its because of this repo haha, but will continue adding sites that work, there is like 100 chinese clones that are literally the same but need some time ; )

**Comment by taiyi747** [comment]
I am thinking about how to monitor these websites, whether to monitor their APIs or their web pages. Although these websites may be accessible, their API services may have actually failed.
