### ISSUE TITLE
NameError: name 'AItianhu' is not defined

### ISSUE THREAD

**Issue by v67bruno** [xtekky/gpt4free#989]
**Bug description**
`g4f/models.py", line 65, in <module> DeepAi, ChatgptLogin, ChatgptAi, Aivvm, GptGo, AItianhu, Aichat, AItianhuSpace, Myshell, Aibn, ChatForAi, FreeGpt, Ylokh, Cromicle`
`NameError: name 'AItianhu' is not defined`

**Environement**
- python 3.10.9
- g4f 1.4.9

**Comment by KirovClassBattlecruiser** [comment]
same issue, im on python 3.11.5 on windows 10, having installed g4f 1.4.9 with python -m pip install -U g4f!

**Comment by KirovClassBattlecruiser** [comment]
https://github.com/xtekky/gpt4free/pull/991 fixes it

**Comment by Josh-XT** [comment]
@xtekky can you do a release so that this fix is applied to the Python package on Pypi?  The current version is broken.

**Comment by xtekky** [comment]
fixed
