### ISSUE TITLE
Packaging this project as PyPI package

### ISSUE THREAD

**Issue by yusufsahinhamza** [xtekky/gpt4free#99]
Hello, i see that this project needs to be packaged as it's listed in Todo list in README, i have forked the repository and i'll be working on packaging it in this fork/branch: https://github.com/yusufsahinhamza/gpt4free/tree/create-pypi-package. You guys may want to watch there and comment anything you want, then i'll create a pull request when it's done.

**Comment by localuser-isback** [comment]
I personally think it would be better to wait until xtekky does it himself or the program is more stable. development is still very new and the backend might not even be python in the future.

**Comment by xtekky** [comment]
Hi, yes it would be better if I have control, nice idea but updates will be faster, publishing to pypi will happen in 1-2 days
