### ISSUE TITLE
AItianhu is inactive

### ISSUE THREAD

**Issue by marz1k** [xtekky/gpt4free#995]
![изображение](https://github.com/xtekky/gpt4free/assets/86841505/5fc139c2-2528-4383-85e3-28012f99b2bd)

**Comment by vmjcv** [comment]
Note that AItianhu has login authentication enabled, like this:
![image](https://github.com/xtekky/gpt4free/assets/25278695/38781b48-3b2f-423a-9b30-e3d14827b0af)

if you want to fix it, you need generate a token in code.
the js code like this :
```
        const g = {
            answer: f,
            timestamp: p.timestamp,
            prefix: p.prefix,
            checksum: p.checksum,
            action: yi.isAuto ? 0 : 1,
            click_cnt: u.current,
            move_distance: bh(),
            stay_duration: new Date().getTime() - Yh,
            dev_tool: 0,
            console_on: 0,
            user_agents: v,
            user_agent: navigator.userAgent,
            os_version: A.name + " " + A.version,
            language: navigator.language,
            resolution: window.screen.width + "x" + window.screen.height,
            robot_hit: h,
            trace: Ot,
            rule_id: (window.challenge_conf || {}).rule_id
        }
          , m = yield yi.verify(g).catch(I=>{
            throw a(vr(5)),
            I
        }
```
Its seems to cryptographically hash the current number of clicks, distance traveled, etc. if we can fake this we will get a proper cookie.
document.cookie = "sl-chlg-token=" + m.token + "; max-age=3600; path=/",

Sorry the js code is really long, I didn't read all of it in its entirety
