### ISSUE TITLE
How can I use it through a socks proxy? where to pass it?

### ISSUE THREAD

**Issue by koutkout** [xtekky/gpt4free#999]
where shall i pass my proxy for it to work?

**Comment by hlohaus** [comment]
You can pass argument `proxy="socks://localhost:1337" to many, but not all providers.

**Comment by koutkout** [comment]
Thanks. When can you make it for all providers? is there an easier way to pass all traffic in a python program through a tunnel?

**Comment by koutkout** [comment]
I would appreciate if you can put it to all providers or at least highlight which providers accept and which doesn't. I guess making it to all providers should not be a challenge if you can use it in your base class. I might be wrong
